### PR TITLE
`<format>`: fix `std::format("{:#.precision}", floating)`

### LINKED ISSUE #3003: <format>: Incorrect decimal point placement when using alternate form without a type
@fsb4000 reported a bug in libc++'s format implementation. While investigating that bug I noticed that for a small part I'm in good company; MSVC STL has the same bug:
```
std::format("{:#.{}}\n", 1200.0 0);  // 1e+03. instead of 1.e+03
std::format("{:#.{}g}\n", 1200.0 0); // 1.e+03 as expected (types a, e, and f are good too.)
```
More examples at https://godbolt.org/z/fTsKaf6vz

### PR DESCRIPTION
**Pull request by achabense**
- Fixes #3003.
- Fixes another formatting problem - there should be no trailing zeros for `"{:#precision}", floating` (only `G/g` can have trailing zeros[[ref]](https://en.cppreference.com/w/cpp/utility/format/formatter#:~:text=In%20addition%2C%20for%20g%20and%20G%20conversions%2C%20trailing%20zeros%20are%20not%20removed%20from%20the%20result.)).

### CODE REVIEW

File: tests/std/tests/GH_003003_format_fix_decimal_point_and_trailing_zero/test.cpp [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+    assert(std::format("{:#.4}", 0.123) == "0.123");
+    assert(std::format("{:#.5}", 0.123) == "0.123");
+    
+    assert(std::format("{:#.0}", 10.1) == "1.e+01");
+    assert(std::format("{:#.1}", 10.1) == "1.e+01");
+    assert(std::format("{:#.2}", 10.1) == "10.");
+    assert(std::format("{:#.3}", 10.1) == "10.1");
+    assert(std::format("{:#.4}", 10.1) == "10.1");
+    assert(std::format("{:#.5}", 10.1) == "10.1");
+}
```
Comment (achabense) [inline tests/std/tests/GH_003003_format_fix_decimal_point_and_trailing_zero/test.cpp:33]: Only `none` type is affected by this pr, so there are no checks for other format types('g','a','f',etc).

File: tests/std/tests/GH_003003_format_fix_decimal_point_and_trailing_zero/env.lst [hunk 2]
```diff
@@ -0,0 +1,4 @@
+# Copyright (c) Microsoft Corporation.
+# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
+
+RUNALL_INCLUDE ..\usual_latest_matrix.lst
```
Comment (achabense) [inline tests/std/tests/GH_003003_format_fix_decimal_point_and_trailing_zero/env.lst:4]: The ...mat_"fix"_deci... in the folder name seems redundant...

Comment (frederick-vs-ja) [reply tests/std/tests/GH_003003_format_fix_decimal_point_and_trailing_zero/env.lst:4]: Perhaps we should use concepts_20_matrix.lst which skips EDG. IIUC this bug needs to be and will be fixed in C++20 mode.
```suggestion
RUNALL_INCLUDE ..\concepts_20_matrix.lst
```

**Comment by StephanTLavavej** [comment]
Moving to WIP as there are unexpected passes in libcxx.

**Comment by StephanTLavavej** [comment]
I looked up the failing test names in the Azure Pipelines output, removed the corresponding lines from `tests/libcxx/expected_results.txt`, then validated that the directory and the newly added test are passing with:

```
python tests\utils\stl-lit\stl-lit.py %STL%\tests\std\tests\GH_003003_format_decimal_point %STL%\llvm-project\libcxx\test\std\utilities\format\format.functions --order=random -o testing_x64.log
```

**Comment by StephanTLavavej** [comment]
@achabense - your PR description originally said:

> Fixes another formatting problem - there should be no trailing zeros when `G/g` is not specified([ref](https://en.cppreference.com/w/cpp/utility/format/formatter#:~:text=In%20addition%2C%20for%20g%20and%20G%20conversions%2C%20trailing%20zeros%20are%20not%20removed%20from%20the%20result.)).

quoting cppreference:

> For floating-point types, the alternate form causes the result of the conversion of finite values to always contain a decimal-point character, even if no digits follow it. Normally, a decimal-point character appears in the result of these conversions only if a digit follows it. In addition, for **g** and **G** conversions, trailing zeros are not removed from the result.

I believe that your PR description is reversed. cppreference is saying that, for the alternate form, when `G/g` **ARE** specified, trailing zeros **ARE EMITTED**. (This is because the usual behavior of `G/g` is to trim trailing zeros.)

Your code change appears to implement what cppreference says, which is also my understanding of the printf/format behavior here:

```diff
 case chars_format::general:
-    if (_Specs._Alt) {
+    if (_Specs._Alt && (_Specs._Type == 'g' || _Specs._Type == 'G')) {
 // [CODE THAT INCREMENTS _Zeroes_to_append]
```

I'll update your PR description to match cppreference and your code, but wanted to mention this in case I got totally confused.

File: stl/inc/format [hunk 3]
```diff
@@ -2864,7 +2864,7 @@ _NODISCARD _OutputIt _Fmt_write(
 
     auto _To_upper  = false;
     auto _Format    = chars_format::general;
-    auto _Exponent  = '\0';
+    auto _Exponent  = 'e';
```
Comment (StephanTLavavej) [inline stl/inc/format:2867]: Suggestion: This makes the following assignments `_Exponent = 'e';` dead; I think we should remove them. The resulting code will be easier to understand: usually we print decimal, where `'e'` is the proper exponent, but for hexfloats we need `'p'` to be the exponent. (The decimal exponent can actually appear for scientific and general; it can't appear for fixed so initializing it to `'e'` is unnecessary but harmless.)

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Thank you for these significant runtime correctness fixes! :heart_eyes_cat: :hammer_and_wrench: :sparkles:

**Comment by StephanTLavavej** [comment]
I'm *speculatively* mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Review by strega-nil — APPROVED** [review]

**Review by strega-nil-ms — APPROVED** [review]

**Review by barcharcraz — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Thanks again for these fixes! :rocket: :rocket: :rocket:
