### PR TITLE
`<ranges>`: Fix regression with `ranges::to` for ADL-only `begin`/`end`

### LINKED ISSUE #5172: `<ranges>`: `ranges::to` use range-based for loops in append branches
https://github.com/microsoft/STL/blob/89ca073a866d24db42b3f4c5e406be4b28a148f4/stl/inc/__msvc_ranges_to.hpp#L1124-L1136

To save the include overhead of `ranges::for_each`, MSVC-STL uses range-based for loop to iterate over the range. However, this is not guaranteed to be well-formed as the former does not extract iterators and sentinels through `ranges::begin`/`ranges::end`.
A disgusting and contrived case could be:

https://godbolt.org/z/Kc3dsvnfW

```cpp
#include <ranges>

struct Vector {
  void push_back(int);
};

struct OnlyADLRange {
  void begin() = delete;
  void end() = delete;
  friend int* begin(OnlyADLRange&);
  friend int* end(OnlyADLRange&);
};

int main() {
  std::ranges::contiguous_range auto r = OnlyADLRange{};
  auto v = r | std::ranges::to<Vector>(); // only well-formed in libstdc++
}
```
Above, only libstdc++ _explicitly_ uses `ranges::begin`/`ranges::end` to get iterators-pair and iterates over the ranges via a while loop so there is no issue.

### PR DESCRIPTION
**Pull request by frederick-vs-ja**
In #4539, the `ranges::for_each` call in the resolution of LWG-4016 was "manually inlined" to reduce inclusion dependency. However, the inlining was not always correct, because builtin-in range-`for` may just stop and fail when a deleted member `begin`/`end` function is encountered, while `ranges` CPOs continue to consider ADL-found `begin`/`end`.

As a result, we should still use `ranges::begin`/`ranges::end`.

Fixes #5172.

### CODE REVIEW

File: stl/inc/__msvc_ranges_to.hpp [hunk 1]
```diff
@@ -1121,7 +1121,11 @@ namespace ranges {
                 if constexpr (_Sized_and_reservable<_Rng, _Container>) {
                     _Cont.reserve(static_cast<range_size_t<_Container>>(_RANGES size(_Range)));
                 }
-                for (auto&& _Elem : _Range) {
+
+                auto _Iter = _RANGES begin(_Range);
+                auto _Sent = _RANGES end(_Range);
```
Comment (hewillk) [inline stl/inc/__msvc_ranges_to.hpp:1126]:
```suggestion
                const auto _Sent = _RANGES end(_Range);

```

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Thanks for fixing this conformance bug in one of the STL's shortest-named functions! :hammer_and_wrench: :lady_beetle: :two:
