### PR TITLE
`<regex>`: Implement collating ranges

### LINKED ISSUE #5204: `<regex>`: Collating ranges are broken
When the `regex_constants::collate` flag is set, character ranges fail to match characters according to the locale's collation order.

# Test case
```cpp
#include <iostream>
#include <locale>
#include <regex>

using namespace std;

int main() {
    const locale de("de_DE");

    regex_traits<wchar_t> traits;
    traits.imbue(de);
    wregex re(L"[a-z]", regex_constants::collate);
    re.imbue(de);

    const wchar_t eszett = L'ß';
    const wchar_t s = L's';
    const wchar_t t = L't';
    const wchar_t ss[] = {L's', L's'};
    const wchar_t minus = L'-';
    const auto stransform = traits.transform(&s, &s + 1);
    const auto ttransform = traits.transform(&t, &t + 1);
    const auto eszetttransform = traits.transform(&eszett, &eszett + 1);
    const auto sstransform = traits.transform(begin(ss), end(ss));

    cout << regex_match(L"ß", re) << '\n';

    cout << (stransform <= eszetttransform
                && eszetttransform <= ttransform)
            << ' '
            << (sstransform == eszetttransform)
            << '\n';

    return 0;
}
```
[Godbolt link](https://godbolt.org/z/363ojExdE)

# Expected behavior
The range should match `ß`, since `ß` collates like `ss` and should be sorted between `s` and `t` (and thus between `a` and `z` as well). Hence, the output of this program should be:
```
1
1 1
```

# Actual behavior
The range does not match `ß`, so the actual output is:
```
0
1 1
```
Note that the output of the second line shows that the problem does not lie in the implementation of `regex_traits<wchar_t>::transform`, as it returns sort keys that are equal for `ß` and `ss` and place `ß` between `s` and `t`.

### PR DESCRIPTION
**Pull request by muellerj2**
Resolves #5204. Follow-up to #5164 and #5209.

When compiled under `/MD` or `/MDd`, the new test cases specific to collating ranges are skipped:
* if compiled with `/Zc:wchar_t-` because the test will fail due to #5236.
* if there is a mismatch with `_ITERATOR_DEBUG_LEVEL` because the stack will be corrupted when `std::collate<wchar_t>::do_transform()` is called in the linked DLL.

Drive-by changes:
* Mark `_Parser::_Error()` as `[[noreturn]]`.
* In `_Matcher::_Skip()` and `_Matcher::_Do_class()`, `_STD` qualify calls to some free functions and clean up the control flow that translates the current character and converts it to an unsigned value.

### CODE REVIEW

File: stl/inc/regex [hunk 1]
```diff
@@ -2917,7 +2917,8 @@ void _Builder<_FwdIt, _Elem, _RxTraits>::_Add_range2(const _Elem _Arg0, const _E
 
         _Node->_Small->_Mark(_Ex0);
     }
-    if (_Ex1 >= _Ex0) {
+
+    if (_Flags & regex_constants::collate || _Ex1 >= _Ex0) {
```
Comment (muellerj2) [inline stl/inc/regex:2921]: The control flow is subtle around here but the function ends up doing the right thing: When the `collate` flag is set, the `_Builder` constructor sets the member variables such that `_Get_tmax()` and `_Get_bmax()` return `0`. This means that the preceding loop is skipped and the inner if condition is false (even when `_Ex1 - _Ex0` in the following line underflows). So in the end, the code just adds the bounds to `_Node->_Ranges`.

File: tests/std/tests/GH_005204_regex_collating_ranges/test.cpp [hunk 2]
```diff
@@ -0,0 +1,333 @@
+// Copyright (c) Microsoft Corporation.
```
Comment (CaseyCarter) [inline tests/std/tests/GH_005204_regex_collating_ranges/test.cpp:1]: This new test needs to be added to `tests/std/tests.lst` so the testing infra picks it up.

File: tests/std/tests/GH_005204_regex_collating_ranges/test.cpp [hunk 3]
```diff
@@ -0,0 +1,333 @@
...
+        }
+    }
+
+    {
+        test_wregex_locale collate_A_to_z_regex(&g_regexTester, L"[A-z]", "de-DE", regex_constants::collate);
+        collate_A_to_z_regex.should_search_fail(L"a");
+        for (wchar_t ascii_upper = L'A'; ascii_upper < 'Z'; ++ascii_upper) {
+            collate_A_to_z_regex.should_search_match(wstring(1, ascii_upper), wstring(1, ascii_upper));
+        }
+        for (wchar_t ascii_lower = L'b'; ascii_lower <= 'z'; ++ascii_lower) {
```
Comment (StephanTLavavej) [inline tests/std/tests/GH_005204_regex_collating_ranges/test.cpp:311]: The comparisons should be against L character literals, although it doesn't make a real difference.

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Thanks! This makes sense and looks good to me. The comprehensive test coverage is excellent. :heart_eyes_cat:

I pushed a trivial merge with `main` followed by a bunch of nitpicks. The most significant changes were to `regex_with_locale_should_throw()`, to actually use `syntax` and to properly record failure when an exception is thrown with an unexpected code.

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
Thanks for sorting out this bug! :joy_cat: :lady_beetle: :magic_wand:
