### PR TITLE
`<ranges>`: Fix misused list-initializations

### LINKED ISSUE #3014: `<ranges>`: list-initialization is misused
Non-list-initialization (parentheses) and list-initialization (curly braces) styles are mixed in the `<ranges>`, however, the latter does not provide any observable benefit and may bring potential issues.
We should use non-list-initialization consistently, as the standard does.

```cpp
#include <ranges>
#include <initializer_list>
#include <utility>

struct I {
  using difference_type = int;
  using value_type = int;
  I(std::initializer_list<int*>) = delete;
  I(int*);
  int operator*() const;
  I& operator++();
  I operator++(int);
};

struct R {
  int* begin();
  I begin() const;
  std::unreachable_sentinel_t end() const;
};

int main() {
  auto r = R{} | std::views::transform(std::identity{});
  decltype(std::as_const(r).begin()) c = r.begin();
}
```
https://godbolt.org/z/89eo678qd

### PR DESCRIPTION
**Pull request by JMazurkiewicz**
Fixes #3014.

Library parts affected by this issue:
* `move_sentinel<S>` (two constructors),
* `transform_view<R, F>::_Iterator`,
* `join_view<R>::_Iterator`,
* `join_with_view<R, P>::_Iterator` (two constructors),
* `join_with_view<R, P>::_Sentinel`
* `elements_view<R, N>::_Iterator`.

### CODE REVIEW

**Review by strega-nil-ms — APPROVED** [review]
Thanks!

File: tests/std/tests/P0896R4_ranges_iterator_machinery/test.cpp [hunk 1]
```diff
@@ -11,13 +11,12 @@
 #include <utility>
 #include <vector>
 
+#include <range_algorithm_support.hpp>
+
 #define STATIC_ASSERT(...) static_assert(__VA_ARGS__, #__VA_ARGS__)
 
 namespace ranges = std::ranges;
```
Comment (StephanTLavavej) [inline tests/std/tests/P0896R4_ranges_iterator_machinery/test.cpp:18]: This also provides `STATIC_ASSERT` and the namespace alias:

https://github.com/microsoft/STL/blob/e7f52446c6f41fddbed31904f594a1f711f85601/tests/std/include/range_algorithm_support.hpp#L19-L21

File: tests/std/tests/P0896R4_views_elements/test.cpp [hunk 2]
```diff
@@ -394,6 +394,27 @@ constexpr void instantiation_test() {
 #endif // TEST_EVERYTHING
 }
 
+// GH-3014 "<ranges>: list-initialization is misused"
+void test_gh_3014() { // COMPILE-ONLY
+    using P = pair<int, int>;
```
Comment (StephanTLavavej) [inline tests/std/tests/P0896R4_views_elements/test.cpp:399]: This shadows an identical typedef at file scope:
https://github.com/microsoft/STL/blob/e7f52446c6f41fddbed31904f594a1f711f85601/tests/std/tests/P0896R4_views_elements/test.cpp#L15

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Also thanks! I pushed a commit to delete 3 redundant lines, FYI @strega-nil-ms.

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
Thanks again for finding and fixing these occurrences of this bug! :hammer_and_wrench: :lady_beetle: :sparkles:
