### PR TITLE
Fix `put_time()` crash on invalid format specifier

### LINKED ISSUE #4820: `<iomanip>`: `std::put_time` should copy unknown conversion specifiers instead of crash
# Describe the bug
I know that behind the scenes `std::put_time` does use `strftime` which leads to crash if some kind of invalid input is provided. I haven't exactly read the standard, but the cplusplus.com [docs](https://cplusplus.com/reference/iomanip/put_time/) on the function says if anything wrong happens, it should set the `failbit` on the stream and not crash the program. While undefined behavior is allowed for `strftime` on invalid input, this does not seems to be the case for `std::put_time` and this is why I'm reporting this as a bug.

Now, some ideas from my research on the topic. According to MS docs the only way to recover from `strftime` error case is to use `_set_invalid_parameter_handler`/`_set_thread_local_invalid_parameter_handler` https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/set-invalid-parameter-handler-set-thread-local-invalid-parameter-handler?view=msvc-170

The first one seems unfeasible as it will modify the global CRT invalid handler for C functions. The second option about thread local storage might be a better option if set and unset before/after calling `std::put_time` and using it to properly flag the stream error. This would still trigger an assert in debug mode, but at least it will not crash release versions.

But in general, the best solution for me would be for the UCRT team to modify the existing `strftime` implementations or create a completely new variant which can handle errors in a more graceful manner, but if this is not possible at least the STL team should try to handle this case somehow by perhaps using the workaround I've proposed.

# Command-line test case
```
C:\Temp>type repro.cpp
#include <iostream>
#include <iomanip>
#include <sstream>
#include <ctime>

int main() {
    std::time_t t = std::time(0);
    std::tm* now = std::localtime(&t);
    std::ostringstream output;
    output << std::put_time(now, "%E%J%P"); // some random invalid formatting string

    if(output.good()) {
        std::cout << "All good\n";
    } else {
        std::cout << "Date time formatting failed due to invalid input\n";
    }
}

C:\Temp>cl /EHsc /W4 /WX /std:c++20 .\repro.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.36.32546 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

repro.cpp
Microsoft (R) Incremental Linker Version 19.36.32546.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:repro.exe
repro.obj

C:\Temp>.\repro.exe
!!!App Crashed!!!
```

# Expected behavior
That would be for the program to NOT crash and output "Date time formatting failed due to invalid input".

(Edited: See analysis below.)

# STL version
VS 2022 17.6.16

### PR DESCRIPTION
**Pull request by TheStormN**
Fixes #4820. The test case also verifies the situation where an invalid specifier is given when a modifier is being used. For example "%E% some text"

This is my first PR, so sorry if something is wrong in formatting or ABI terms.

### CODE REVIEW

File: stl/inc/xloctime [hunk 1]
```diff
@@ -760,6 +768,17 @@ protected:
     }
 
 private:
+    static constexpr bool __CLRCALL_OR_CDECL _Is_valid_fmt_specifier(char _Specifier) {
+        constexpr char _Valid_specifiers[] = "aAbBcCdDeFgGhHIjmMnprRStTuUVwWxXyYzZ";
+        for (const char _Valid_specifier : _Valid_specifiers) {
+            if (_Valid_specifier == _Specifier) {
+                return true;
+            }
+        }
```
Comment (TheStormN) [inline stl/inc/xloctime:777]: I was thinking about binary search here, but I guess this would require movement to a .cpp file which as of now does not exist for `xloctime`. I'm accepting any guidelines or suggestions.

File: stl/inc/xloctime [hunk 2]
```diff
@@ -890,6 +917,17 @@ protected:
...
+    static constexpr bool __CLRCALL_OR_CDECL _Is_valid_fmt_specifier(const char _Specifier) {
+        constexpr char _Valid_specifiers[] = "aAbBcCdDeFgGhHIjmMnprRStTuUVwWxXyYzZ";
+        for (const char _Valid_specifier : _Valid_specifiers) {
+            if (_Valid_specifier == _Specifier) {
+                return true;
+            }
+        }
+
+        return false;
+    }
```
Comment (TheStormN) [inline stl/inc/xloctime:929]: I was thinking about `std::binary_search` here, but I guess this would require movement to a .cpp file which as of now does not exist for xloctime. I'm accepting any guidelines or suggestions.

File: tests/std/tests/Dev11_0836436_get_time/test.cpp [hunk 3]
```diff
@@ -792,16 +794,17 @@ void test_invalid_argument() {
     time_t t = time(nullptr);
     tm currentTime;
     localtime_s(&currentTime, &t);
+    currentTime.tm_hour = 25; // set invalid hour
```
Comment (TheStormN) [inline tests/std/tests/Dev11_0836436_get_time/test.cpp:797]: Windows implementation of `strftime()` does crash when invalid `struct tm` is supplied. However, in `std::put_time()` shouldn't that be just `ios_base::badbit` instead of a crash?

File: stl/inc/xloctime [hunk 4]
```diff
@@ -651,6 +651,17 @@ protected:
...
+constexpr bool _Is_valid_fmt_specifier(const char _Specifier) {
+    constexpr char _Valid_specifiers[] = "aAbBcCdDeFgGhHIjmMnprRStTuUVwWxXyYzZ";
+    for (const char _Valid_specifier : _Valid_specifiers) {
+        if (_Valid_specifier == _Specifier) {
+            return true;
+        }
+    }
+
+    return false;
+}
```
Comment (TheStormN) [inline stl/inc/xloctime:663]: I was thinking about `std::binary_search` here, but I guess this would require movement to a .cpp file which as of now does not exist for xloctime. I'm accepting any guidelines or suggestions.

P.S. Also should I have __CLRCALL_OR_CDECL here?

File: stl/inc/xloctime [hunk 5]
```diff
@@ -651,6 +651,17 @@ protected:
...
+constexpr bool _Is_valid_fmt_specifier(const char _Specifier) {
+    constexpr char _Valid_specifiers[] = "aAbBcCdDeFgGhHIjmMnprRStTuUVwWxXyYzZ%";
+    for (const char _Valid_specifier : _Valid_specifiers) {
+        if (_Valid_specifier == _Specifier) {
+            return true;
+        }
+    }
+
+    return false;
+}
```
Comment (TheStormN) [inline stl/inc/xloctime:663]: I was thinking about `std::binary_search` here, but I guess this would require movement to a .cpp file which as of now does not exist for `xloctime`. Also not sure this is the correct place for this function in general. I'm accepting any guidelines or suggestions.

P.S. Also should I have __CLRCALL_OR_CDECL here?

File: stl/inc/xloctime (hunk 4 above)
Comment (TheStormN) [inline stl/inc/xloctime:663]: I was thinking about чstd::binary_searchч here, but I guess this would require movement to a .cpp file which as of now does not exist for чxloctimeч. Also not sure this is the correct place for this function in general. I'm accepting any guidelines or suggestions.

P.S. Also should I have __CLRCALL_OR_CDECL here?

File: stl/inc/xloctime [hunk 6]
```diff
@@ -651,6 +651,17 @@ protected:
     __CLR_OR_THIS_CALL ~time_get_byname() noexcept override {}
 };
 
+constexpr bool _Is_valid_fmt_specifier(const char _Specifier) {
+    constexpr char _Valid_specifiers[] = "aAbBcCdDeFgGhHIjmMnprRStTuUVwWxXyYzZ";
+    for (const char _Valid_specifier : _Valid_specifiers) {
```
Comment (jovibor) [inline stl/inc/xloctime:656]: This array will be recreated each call.
It's gonna be quite expensive at runtime, better make it `static`.

Comment (TheStormN) [reply stl/inc/xloctime:656]: I thought that making it `constexpr` would have the same effect? If not I will change it as part of the next commit when more reviews come in case I have to change something else.

Comment (jovibor) [reply stl/inc/xloctime:656]: `constexpr` and `static` are quite orthogonal.
[Here](https://stackoverflow.com/a/13867690/4582609) is a good explanation.

Comment (frederick-vs-ja) [reply stl/inc/xloctime:656]: > This array will be recreated each call. It's gonna be quite expensive at runtime, better make it `static`.

But if we do so, the enclosing `_Is_valid_fmt_specifier` function itself can't be `constexpr` until C++23, see WG21-P2242R3 and WG21-P2647R1 (both of which are not yet implemented by MSVC at this moment).

Comment (jovibor) [reply stl/inc/xloctime:656]: > But if we do so, the enclosing `_Is_valid_fmt_specifier` function itself can't be `constexpr`

Of course.
But this function is intended for runtime only, because the `put` method itself isn't `constexpr`. Or am I missing something?

File: stl/inc/xloctime (hunk 4 above)
Comment (frederick-vs-ja) [reply stl/inc/xloctime:663]: > P.S. Also should I have __CLRCALL_OR_CDECL here?

IIUC, no. This macro is DLL-related, and we shoudn't touch the DLLs just for this issue.

It can be still fine to move `_Is_valid_fmt_specifier` to an import library. But as the function body is very simple, I think it's better to make it header only.

Comment (StephanTLavavej) [reply stl/inc/xloctime:663]: Things should be injected into the import lib only when necessary (e.g. WinAPI calls) or there is a *very* compelling throughput reason (e.g. charconv tables). Import lib additions are "eternal" and they are subject to strict constraints (can't drag in arbitrary stuff like non-core headers), so we don't want to add them arbitrarily.

The basic rule is that header-only code is happy code. Separately compiled code is weird and scary. I learned these lessons at great cost.

Comment (AlexGuteniev) [reply stl/inc/xloctime:663]: If you want the runtime perf, `std::binary_earch` isn't even the best strategy here.

The best is to have 256-char byte-bool or bit mask pre-computed. Though I'm not sure if it fits here, as `static constexpr` is questioned below. But with `_Is_constant_evaluated()` should be doable for runtime only.

Another good strategy may be to implement it like `if (_Specifier == 'a' || _Specifier == 'A' || ...)`. the compiler is likely to convert char ranges to machine word bitsets, chechk them with `bt` instruction, and do fewer steps that `std::binary_earch` i

Comment (TheStormN) [reply stl/inc/xloctime:663]: Then I guess instead of `if (_Specifier == 'a' || _Specifier == 'A' || ...)` it would be even better to do switch/case table?

Comment (AlexGuteniev) [reply stl/inc/xloctime:663]: >  it would be even better to do switch/case table?

Yes. 
Unfortunately MSVC can'te emit for switch/case anything better than jump table. Other compilers do,
See https://godbolt.org/z/sbo6oEqnj

Although both are ugly in the source, so it depends on if the optimization is justified here.

Computing a `static const` bitmap or bytemap is also good (IMO, better that `if (...||...)`, and not ugly in the source.

Comment (AlexGuteniev) [reply stl/inc/xloctime:663]: I don't know. @StephanTLavavej are optimization justified here?

Comment (TheStormN) [reply stl/inc/xloctime:663]: Just to mention that largest bottleneck of the `std::put_time` is the call to strftime which for the non-wchar version will  convert the string to wchar internally, then fill the result and convert back to char and this is done for each and every specifier in a loop.

In case we don't want to rewrite the implementation to not use `strftime` at all, a much better runtime optimization would be to prepare the whole string in advance with properly escaping characters that would cause `strftime` to crash and then call it only once. If we do that, the optimization for the loop here will be completely not worth it.

Comment (AlexGuteniev) [reply stl/inc/xloctime:663]: Ok, agree

**Comment by TheStormN** [comment]
@StephanTLavavej Sorry for the ping, but I see that not only this, but quite few more PRs are waiting for reviews and eventual merge for considerable time. I'm wondering what is the workflow in general? How much time it usually takes and do you have dedicated time for reviewing community supplied PRs?

**Comment by StephanTLavavej** [comment]
> Sorry for the ping, but I see that not only this, but quite few more PRs are waiting for reviews and eventual merge for considerable time. I'm wondering what is the workflow in general? How much time it usually takes and do you have dedicated time for reviewing community supplied PRs?

My apologies for the delay - yes, the backlog has been accumulating. (This is something that I monitor with the [STL Status Chart](https://microsoft.github.io/STL/).)

The problem is that I am currently the only STL maintainer able to spend up to 100% of their time on the STL. (See our Maintainer Priorities issue #4700 for weekly updates.) Everyone else is working on high-priority projects like ASAN and even requesting small amounts of their time to review my own PRs is difficult (but necessary as all code must be reviewed by at least one other person, not even I am allowed to check in whatever I want).

I occasionally have non-STL tasks to deal with (ConcRT, ATL/MFC every other quarter). Additionally, I just took a few days off for vacation (my niece's cat-themed 6th birthday party), during which the backlog further accumulated, and as soon as I got back I was slammed with high-priority STL-specific but non-review work - I had to fix a regression on Win11 24H2 (#4844), revert my glorious changes to drop Win7 (#4857), update our LLVM submodule to fix internal "credential scanner" failures (#4862), and fix `/analyze` warnings for bounds safety (#4856). Today I thought I'd finally have time to get back to reviews, but upon checking the STL-ASan-CI history to record occurrences of sporadic x86 crashes that we missed in #4324 (because I don't get email notifications of STL-ASan-CI failures), I noticed that the *x64* tests [failed](https://dev.azure.com/vclibs/STL/_build/results?buildId=17171&view=results) right before I left for vacation. I find sporadic test failures to be absolutely intolerable and in this case I actually knew how to fix them, since in #3922 I had fixed a similar failure with x86 SSE2 instructions and enhanced the ASan machinery to print out unrecognized bytes. So I've spent all day fixing that (and bogus comments) in LLVM ASan, and now validating it with a build. I also have to review an important STL document that my double boss sent to me yesterday.

When the world isn't on fire and I can sit down and review PRs, usually I can dedicate most of my day to it (excluding only meetings and email). The time that it takes to review a PR varies, depending on how complicated the problem and solution are, how familiar I am with the area, how well-structured the PR's commit history and description are, and how much the PR has already been reviewed by other contributors. If the PR is clean and I know the area deeply, I can easily power through a thousand lines in an hour. If the area is complicated, or I notice that something is messed up, a few dozen lines can take longer to either fix or write up what's wrong.

When there are no major distractions, I can usually keep up with or slightly exceed the rate of incoming PRs, which is how we've been able to drain the formerly-numbering-80 PR backlog. But as queueing theory explains, when a source and drain are closely balanced with little excess capacity, any increase in source throughput or reduction in drain throughput causes a massive increase in the backlog (aka why store checkout lines can be massive, etc.).

I'm hoping to make review progress next week, although I can't promise anything. (I try to review high-priority PRs first, but the order in which I review PRs is highly variable - I also like to review easy PRs first, until I'm in the zone and can really focus on complicated changes.)

File: tests/std/tests/Dev11_0836436_get_time/test.cpp (hunk 3 above)
Comment (StephanTLavavej) [reply tests/std/tests/Dev11_0836436_get_time/test.cpp:797]: The Standard's wording is less clear than I'd like (probably because it's from an early era when specifications were written less precisely), but it seems to me that crashing is disallowed, because "nothing permits it to fail". I suspect that `failbit` is actually what should be set, since the requested conversion can't be performed due to bogus input. `badbit` generally means "something is wrong with the stream itself".

A followup PR would be reasonable.

File: stl/inc/xloctime (hunk 4 above)
Comment (StephanTLavavej) [reply stl/inc/xloctime:663]: Yeah, I find the "`strftime` is the bottleneck" rationale persuasive, so I'm not too concerned about optimizing this code, even though a table would be an efficient strategy when considered in isolation. This approach is fine unless and until we look into optimizing the code as a whole (i.e. let's worry about correctness and performance separately).

File: stl/inc/xloctime (hunk 6 above)
Comment (StephanTLavavej) [reply stl/inc/xloctime:656]: I haven't checked the codegen (I am a lazy kitty :cat2:) but my understanding of the compiler front-end and back-end tells me that it will emit code to push each element of the array on the stack, as I have observed previously - i.e. @jovibor is correct. This is because using an array makes it "address-taken". The compiler back-end can coalesce constants, but it has to preserve the observable guarantee that "distinct objects are at distinct addresses", so as soon as something is address-taken, the back-end will usually emit it as a distinct object.

Additionally, my understanding is that `constexpr` doesn't really increase the potential for optimizations in MSVC (other compilers may differ). MSVC doesn't consider it a hint that computations can be eagerly boiled down. The optimizer is able to do constant propagation, inlining, etc. and boil things down to constants (as long as the source code is available header-only, or LTCG gets iinvolved), but `constexpr` doesn't make that more likely.

Disclaimer: I'm not a compiler dev and could be wrong.

In practice, what this means for library code is that we try to consistently say `static constexpr` for arrays, but plain `constexpr` for scalar constants. With the noted exception (thanks @frederick-vs-ja) that if the function has to be `constexpr`, then that currently limits us from saying `static constexpr` (so annoying).

What we should *actually* do here is lift out the array to namespace scope, where it can be `_INLINE_VAR constexpr`. As I agreed in the other comment thread, optimizing the performance isn't critical here, but we may as well avoid gratuitous costs when doing so is cheap in terms of source code impact, and lifting out the array is very easy. This way, the valid characters will be "burned into ROM" in a single place that all template instantiations can use (`.rdata`, I think?), without the compiler emitting annoying instructions to push each character onto the stack before looping.

I'll validate and push changes.

File: tests/std/tests/Dev11_0836436_get_time/test.cpp [hunk 7]
```diff
@@ -905,3 +908,24 @@ void test_gh_2848() {
...
+        assert(wss.rdstate() == ios_base::goodbit);
+        assert(wss.str() == L"%Ei%!%E%J%P");
+    }
+
+    {
+        stringstream ss;
+        ss << put_time(&currentTime, "%Ei%!%E%J%P");
+        assert(ss.rdstate() == ios_base::goodbit);
+        assert(ss.str() == "%Ei%!%E%J%P");
+    }
```
Comment (StephanTLavavej) [inline tests/std/tests/Dev11_0836436_get_time/test.cpp:930]: This test coverage is great! I'd like to extend it a bit:

* Let's test the fast path for percent escaping. I'm sure we exercise it elsewhere, but covering it here would be good too.
* Let's test that `wchar_t`s aren't truncated, both with and without modifiers.
* `%E%J` here is interesting - it's actually being parsed as `%E%` followed by `J`. Which is fine, but it implies that we should also test something like `%E%Z`. `%Z` is a known conversion specifier, but if we see `%E%` followed by `Z`, both are copied literally.

**Review by StephanTLavavej — APPROVED** [review]

**Comment by TheStormN** [comment]
I can see, why PR reviews can take so much time. You not only do the reviews, but also fix your own comments. :)

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
Thanks for fixing this longstanding bug with severe impact, and congratulations on your first microsoft/STL commit! :heart_eyes_cat: :hammer_and_wrench: :partying_face:

This is expected to ship in VS 2022 17.12 Preview 3.

**Comment by TheStormN** [comment]
> Thanks for fixing this longstanding bug with severe impact, and congratulations on your first microsoft/STL commit! 😻 🛠️ 🥳
> 
> This is expected to ship in VS 2022 17.12 Preview 3.

Thank you! What is the dead line to catch the 17.12 RPM version as I plan to have two more PR's regarding `put_time`? :)

P.S. Also, just out of curiosity, why there is an 'internal repo' on which you mirror the PRs?

**Comment by StephanTLavavej** [comment]
Changes will stop flowing from our development branch into 17.12 Preview 3 on 2024-08-30 (3 weeks from now). That's not the release date, it's just when an internal merge from `prod/fe` (the branch that the compiler front-end and libraries share) to MSVC `main` happens. After that point, changes will need to be manually ported with special boss approval to get into 17.12 Preview 3, or any later Preview, up to and including 17.12 General Availability. That process is intentionally tedious to avoid devs injecting risk late into a release cycle, so we avoid porting changes except for critical bugs.

Aug 30 is the date that the branch is "snapped" but we need at least a couple of days to review and merge a change, so I'd say that a PR has to be completely ready by Mon, Aug 26 if it's to have a chance of making it through the review and merge process in time.

The internal repo is where all of the MSVC toolset (including the compiler front-end, back-end, linker, and other libraries) is built. While 99.9% of STL development happens on GitHub and is then mirrored to MSVC, the MSVC-internal repo builds more flavors that we haven't ported to our CMake build system yet (notably `/clr` and `/clr:pure` - we just need to find the time but haven't found it in the last 5 years) and other variants such as OneCore and Spectre (ditto). While all of the STL's own tests are on GitHub, the MSVC-internal repo has tons of compiler tests that also exercise the STL to some extent, and all of the tests (both the ones on GitHub and the ones that are internal-only) are also run with internal "checked" builds of the compiler with assertions enabled, which catch compiler bugs that aren't always visible in the publicly available "retail" compiler. The internal repo is responsible for packaging up the VCRedist, and ensuring that headers and libs and sources are installed to the right directories in the VS Installer. Finally, only the MSVC-internal build generates the normal `msvcp140.dll` name (GitHub intentionally builds `msvcp140_oss.dll` to avoid conflicts), and can officially sign it as Microsoft (which we could never do for our "unofficial" OSS builds).

Although all of that internal stuff is happening, we ensure that our GitHub repo is binary-identical at nearly all times to a subdirectory of our internal repo (`src/vctools/crt/github`), with temporary divergence typically only when the compiler back-end devs want to make changes in their `prod/be` branch and code takes some time to flow over. This is how GitHub remains the source of truth for development, even though the MSVC repo is where the bits are built. (Also incentivizing us to do 99.9% of our development in public is that the GitHub build and test systems are *way better and faster* than the internal equivalents.)

**Comment by TheStormN** [comment]
Thank you for the detailed explanations! I will try my best to catch the deadline.
