### PR TITLE
`<regex>`: Compare against `char` directly

### LINKED ISSUE #5673: `<regex>`: After `_Uelem` changes, Build2 asserts in the Real World Code test suite
After merging #5592, our test team reported VSO-2548012 "\[RWC\]\[prod/fe\]\[Regression\] Build2 test failed with Assertion failed: `type () == line_type::special`, file C:\gitP\Build2\build2-toolchain-0.17.0\build2\libbuild2/script/regex.hxx, line 208". The affected code is:

https://github.com/build2/build2/blob/05d68f47aa044da9161d9bfabdd153602169d902/libbuild2/script/regex.hxx#L200-L210
```cpp
        // Provide basic_regex (such as from msvcrt) with the ability to
        // explicitly cast line_chars to implementation-specific numeric
        // types (enums, msvcrt's _Uelem, etc).
        //
        template <typename T>
        explicit
        operator T () const
        {
          assert (type () == line_type::special);
          return static_cast<T> (special ());
        }
```

I haven't yet attempted to repro this myself. I don't know if it's a bug in Build2 (i.e. a non-Standard assumption that we've broken), or a bug in #5592. I also don't know if this is further affected by the currently open #5671.

FYI @muellerj2.

### PR DESCRIPTION
**Pull request by StephanTLavavej**
Fixes #5673 and fixes VSO-2548012 in conjunction with small Build2 changes.

Build2 is doing something extremely complicated and fragile with user-defined character types and `regex`. When we construct user-defined `_Elem` from ordinary `char`s, that triggers assertions in their machinery, even though the resulting homogeneous comparisons between `_Elem` and `_Elem` are arguably more cromulent.

This PR slightly backs off from the purity of such comparisons, resulting in code that's somewhat closer to our old way of doing things, but still avoiding the internal `_Uelem` machinery. Now we directly compare `_Elem` to `char`. Build2 has heterogeneous comparison operators that handle this.

It will still be necessary to update Build2 to round-trip their user-defined character type instead of asserting, but that's a less invasive change: https://github.com/build2/build2/pull/478

This makes no difference to the vast, vast majority of users who simply use `char` or `wchar_t`.

### CODE REVIEW

File: tests/std/tests/GH_000995_regex_custom_char_types/test.cpp [hunk 1]
```diff
@@ -101,7 +101,29 @@ class test_regex_traits {
...
+    bool operator!=(const signed_wchar_enum left, const char right) {
+        return static_cast<short>(left) != right;
+    }
+
+    bool operator==(const char left, const signed_wchar_enum right) {
+        return left == static_cast<short>(right);
+    }
+
+    bool operator!=(const char left, const signed_wchar_enum right) {
+        return left != static_cast<short>(right);
```
Comment (davidmrdavid) [inline tests/std/tests/GH_000995_regex_custom_char_types/test.cpp]: just curious - any reason not to define this based on `operator==`. As in

```C++
    return !(left == right);
```

File: tests/std/tests/GH_000995_regex_custom_char_types/test.cpp [hunk 2]
```diff
@@ -101,7 +101,29 @@ class test_regex_traits {
     rx_traits inner;
 };
 
-enum class signed_wchar_enum : short {};
+namespace signed_wchar_ns {
```
Comment (davidmrdavid) [inline tests/std/tests/GH_000995_regex_custom_char_types/test.cpp]: for my own learning - `_ns` here stands for namespace, right?

Comment (StephanTLavavej) [reply tests/std/tests/GH_000995_regex_custom_char_types/test.cpp]: Yes.

File: tests/std/tests/GH_000995_regex_custom_char_types/test.cpp (hunk 1 above)
Comment (StephanTLavavej) [reply tests/std/tests/GH_000995_regex_custom_char_types/test.cpp]: More or less stylistic. The direct definition is better in terms of debug codegen, not that it matters in a test. For anything complicated (e.g. an `operator<`), defining one in terms of another is definitely more robust.

File: tests/std/tests/GH_000995_regex_custom_char_types/test.cpp [hunk 3]
```diff
@@ -101,7 +101,29 @@ class test_regex_traits {
     rx_traits inner;
 };
 
-enum class signed_wchar_enum : short {};
+namespace signed_wchar_ns {
+    enum class signed_wchar_enum : short {};
+
+    bool operator==(const signed_wchar_enum left, const char right) {
+        return static_cast<short>(left) == right;
```
Comment (muellerj2) [inline tests/std/tests/GH_000995_regex_custom_char_types/test.cpp]: It would actually be more correct to do the following casts in this operator:

```
return static_cast<unsigned short>(left) == static_cast<unsigned char>(right);
```

But it doesn't really matter much for this test, since the parser only compares positive `char`s.

Comment (StephanTLavavej) [reply tests/std/tests/GH_000995_regex_custom_char_types/test.cpp]: I can do that.

**Comment by StephanTLavavej** [comment]
@davidmrdavid @muellerj2 I've pushed changes to the test, improving the casts and centralizing the operators. Thanks for the reviews! :heart_eyes_cat:

**Review by muellerj2 — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
I've pushed a non-trivial merge with `main`, reverse-mirroring what I did in MSVC-PR-662263.

This fixes the conflict in `GH_000995_regex_custom_char_types` with #5671 (which had moved and altered code in the test). Now, `signed_wchar_enum` and `ullong_enum` are gaining comparison operators through the same technique, `wrapped_character`'s operators have been adjusted now that it's templated on `Elem`, and they're all implemented in terms of each other. (I suppose I was ultimately persuaded that it's the simpler thing to do, thanks for the review comment.)
