### PR TITLE
Fix rethrowing the caught exception from streambuf

### LINKED ISSUE #4322: `<ostream>`: Exception from streambuf should be caught and not rethrown
Originally reported as DevCom-10555755 / VSO-1939195 / AB#1939195 . I've cleaned up the repro and especially the Standardese citations, so I believe this is a bug.

```
D:\GitHub\STL\out\x64>type meow.cpp
```
```cpp
#include <cassert>
#include <iostream>
#include <sstream>
#include <stdexcept>
using namespace std;

class MyStreamBuf : public streambuf {
protected:
    // N4971 [streambuf.virt.get]/1-2:
    // "streamsize showmanyc();
    // Returns: An estimate of the number of characters available in the sequence, or -1.
    // If it returns a positive value, then successive calls to underflow() will not return
    // traits::eof() until at least that number of characters have been extracted from the stream.
    // If showmanyc() returns -1, then calls to underflow() or uflow() will fail. [Note 277]
    // Default behavior: Returns zero."

    // Note 277:
    // "underflow or uflow can fail by throwing an exception prematurely. The intention
    // is not only that the calls will not return eof() but that they will return "immediately"."

    int_type underflow() override {
        throw runtime_error("WOOF");
    }
};

int main() {
    MyStreamBuf rdbuf;
    ostringstream oss;
    assert(oss.exceptions() == ios_base::goodbit);

    try {
        // N4971 [ostream.inserters]/8-9:
        // "basic_ostream& operator<<(basic_streambuf<charT, traits>* sb);
        // Gets characters from sb and inserts them in *this. Characters are
        // read from sb and inserted until any of the following occurs:
        // [...]
        // - an exception occurs while getting a character from sb.
        // If the function inserts no characters, it calls setstate(failbit) (which
        // may throw ios_base::failure ([iostate.flags])). If an exception was thrown
        // while extracting a character, the function sets failbit in the error state,
        // and if failbit is set in exceptions() the caught exception is rethrown."
        oss << &rdbuf;
        cout << "No exception observed in main().\n";
    } catch (const runtime_error&) {
        cout << "Caught runtime_error in main().\n";
    }

    assert(oss.rdstate() == ios_base::failbit);
}
```
```
D:\GitHub\STL\out\x64>cl /EHsc /nologo /W4 /MTd /Od meow.cpp && meow
meow.cpp
Caught runtime_error in main().
```

libstdc++ and libc++ print "No exception observed in main()." as shown by https://godbolt.org/z/Yq3noKn8s .

### PR DESCRIPTION
**Pull request by grcm10**
Fixes #4322

### CODE REVIEW

**Review by kirankokare09 — APPROVED** [review]

File: stl/inc/ostream [hunk 1]
```diff
@@ -493,8 +493,10 @@ public:
                 _TRY_BEGIN
                 _Meta = _Traits::eq_int_type(_Traits::eof(), _Meta) ? _Strbuf->sgetc() : _Strbuf->snextc();
                 _CATCH_ALL
-                _Myios::setstate(ios_base::failbit);
-                _RERAISE;
+                // N4971 [ostream.inserters]/8-9: "...If an exception was thrown
```
Comment (StephanTLavavej) [inline stl/inc/ostream:496]: Reducing this citation from the longer one in #4322 is good, but now this is quoting part of paragraph 9 only, so it should be adjusted accordingly.

File: stl/inc/ostream [hunk 2]
```diff
@@ -493,8 +493,10 @@ public:
                 _TRY_BEGIN
                 _Meta = _Traits::eq_int_type(_Traits::eof(), _Meta) ? _Strbuf->sgetc() : _Strbuf->snextc();
                 _CATCH_ALL
-                _Myios::setstate(ios_base::failbit);
-                _RERAISE;
+                // N4971 [ostream.inserters]/8-9: "...If an exception was thrown
+                // while extracting a character, the function sets failbit in the error state,
+                // and if failbit is set in exceptions() the caught exception is rethrown."
+                _Myios::setstate(ios_base::failbit, (_Myios::exceptions() == ios_base::failbit));
```
Comment (StephanTLavavej) [inline stl/inc/ostream:499]: The parentheses here are unnecessary. We usually omit unnecessary parentheses, except in certain contexts where precedence is notoriously confusing for humans (e.g. around bitwise operators) or to silence compiler warnings (e.g. when mixing `&&` and `||`).

File: tests/std/tests/GH_001858_iostream_exception/test.cpp [hunk 3]
```diff
@@ -229,6 +235,33 @@ void test_ostream_exceptions() {
...
+        try {
+            os << &buffer;
+        } catch (const ios_base::failure&) {
+            assert(false);
+        } catch (const test_exception&) {
+            assert(false);
+        }
+    }
+
+    { // operator<< rethrow the caught exception if failbit is set in exceptions()
```
Comment (StephanTLavavej) [inline tests/std/tests/GH_001858_iostream_exception/test.cpp:252]: Grammar: `operator<<` is singular, so it `rethrows`.

File: tests/std/tests/GH_001858_iostream_exception/test.cpp [hunk 4]
```diff
@@ -229,6 +235,33 @@ void test_ostream_exceptions() {
             // Expected case
         }
     }
+
+    { // operator<< with exceptions
+        basic_ostream<CharT> os(buffer.to_buf());
+        os.exceptions(ios_base::goodbit);
```
Comment (StephanTLavavej) [inline tests/std/tests/GH_001858_iostream_exception/test.cpp:241]: This is inconsistent. `exceptions()` defaults to `goodbit`, so we don't need to say that here. Above, there are pairs of test cases that say `// meow` (using the default behavior) and then `// meow with exceptions` where `exceptions()` is called. I think we should follow that convention here.

For extra clarity, we could cite #4322.

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Thanks for fixing this bug and especially for adding test coverage, this looks great! :heart_eyes_cat: I pushed a few nitpicky changes for consistency, nothing major. This should be part of our next merge batch (not sure when, maybe this week, possibly next week).

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
Thanks for fixing this ancient bug! :lady_beetle: :hammer_and_wrench: :heart_eyes_cat:
