### PR TITLE
Fix uninitialized_meow again

### LINKED ISSUE #1712: <memory>: ranges::uninitialized_copy and ranges::uninitialized_move fail to compile with trivial types
**Describe the bug**
`ranges::uninitialized_copy` and `ranges::uninitialized_move` fail to compile with trivial types, common first range and non-common second range.

**Code**
```
#include <memory>
#include <ranges>

using namespace std;

int main() {
    int arr[3]{0, 1, 2};
    int arr2[3];

    ranges::uninitialized_copy(begin(arr), end(arr), begin(arr2), unreachable_sentinel);
}
```

**Expected behavior**
Should compile fine.

**STL version**
Microsoft Visual Studio Community 2019 Preview
Version 16.10 Preview 1

### PR DESCRIPTION
**Pull request by miscco**
Urgh, thanks to @AdamBucior for finding this bug.

While I believe we should be able to expand coverage, we might want to squeeze this into Preview2

Fixes #1712.

### CODE REVIEW

File: tests/std/tests/P0896R4_ranges_alg_uninitialized_copy/test.cpp [hunk 1]
```diff
@@ -235,6 +235,30 @@ struct memcpy_test {
             assert(ranges::equal(input, expected_input_long));
             assert(ranges::equal(output, expected_output));
         }
+
+        { // Validate no common input range
```
Comment (CaseyCarter) [inline tests/std/tests/P0896R4_ranges_alg_uninitialized_copy/test.cpp:239]: "no common" should probably be "non-common" in all of these comments. Also in the other test. (Whew, I found something.)

**Review by CaseyCarter — CHANGES_REQUESTED** [review]

File: tests/std/tests/P0896R4_ranges_alg_uninitialized_copy/test.cpp (hunk 1 above)
Comment (miscco) [reply tests/std/tests/P0896R4_ranges_alg_uninitialized_copy/test.cpp]: Done, I would suggest to move the sized_sentinel optimization to after the preview 2 merge point?

File: tests/std/tests/P0896R4_ranges_alg_uninitialized_copy/test.cpp [hunk 2]
```diff
@@ -215,19 +215,20 @@ struct memcpy_test {
         }
 
         { // Validate input shorter
-            int input[]  = {13, 55, 12345};
-            int output[] = {-1, -1, -1, -1};
+            int input[] = {13, 55, 12345};
+            int output[4];
```
Comment (CaseyCarter) [inline tests/std/tests/P0896R4_ranges_alg_uninitialized_copy/test.cpp:219]: Ditto not a great idea. Note that the `construct_at` on 222 could hide a bug that results in the algorithm writing past the end of its proper output or have UB if `result.out` is past the end of `output`. (It's also somewhat silly to `construct_at` when we could simply `*result.out = -1;`.)

File: tests/std/tests/P0896R4_ranges_alg_uninitialized_move/test.cpp [hunk 3]
```diff
@@ -205,8 +205,8 @@ struct memcpy_test {
 
     static void call() {
         { // Validate matching ranges
-            int input[]  = {13, 55, 12345};
-            int output[] = {-1, -1, -1};
+            int input[] = {13, 55, 12345};
+            int output[3];
```
Comment (CaseyCarter) [inline tests/std/tests/P0896R4_ranges_alg_uninitialized_move/test.cpp:209]: Ditto all comments from the other test ;)

**Review by CaseyCarter — CHANGES_REQUESTED** [review]

File: tests/std/tests/P0896R4_ranges_alg_uninitialized_copy/test.cpp (hunk 1 above)
Comment (CaseyCarter) [reply tests/std/tests/P0896R4_ranges_alg_uninitialized_copy/test.cpp]: > Done, I would suggest to move the sized_sentinel optimization to after the preview 2 merge point?

Yes, I agree that we should rush the bugfix and put off the potential optimization for another day.

File: tests/std/tests/P0896R4_ranges_alg_uninitialized_copy/test.cpp [hunk 4]
```diff
@@ -204,8 +204,8 @@ struct memcpy_test {
 
     static void call() {
         { // Validate matching ranges
-            int input[]  = {13, 55, 12345};
-            int output[] = {-1, -1, -1};
+            int input[] = {13, 55, 12345};
+            int output[3];
```
[the remark this answers is not in the document]
Comment (miscco) [reply tests/std/tests/P0896R4_ranges_alg_uninitialized_copy/test.cpp:208]: My reasoning was that reading the indeterminate value will break the test, as during runtime we will most certainly break because the chance of comparing equal is slim. During constant evaluation we will get a hit in the face from the compiler

[the remark this answers is not in the document]
Comment (CaseyCarter) [reply tests/std/tests/P0896R4_ranges_alg_uninitialized_copy/test.cpp:208]: (1) There is no "during constant evaluation" for these tests (not on this branch, anyway 😃).
(2) It's almost always a mistake to reason about the result of undefined behavior. What happens on this run may differ from what happens on the next, compiler flags may change the behavior, future compiler versions may do something completely different, etc. There's no reason to throw a grenade here and hope it does the right thing when we had a perfectly workable test a commit ago.

**Review by CaseyCarter — APPROVED** [review]

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Thanks for fixing these compiler errors! :hammer_and_wrench: :smiley_cat: :rocket:
