### PR TITLE
<type_traits>: Implement Layout-compatibility and Pointer-interconvertibility Traits

### LINKED ISSUE #18: P0466R5 Layout-Compatibility And Pointer-Interconvertibility Traits
[P0466R5](https://wg21.link/P0466R5) Layout-Compatibility And Pointer-Interconvertibility Traits

Feature-test macros as of WG21-N4842:
```
#define __cpp_lib_is_layout_compatible 201907L
#define __cpp_lib_is_pointer_interconvertible 201907L
```

This needs compiler support, implemented by Microsoft-internal MSVC-PR-227560 for VS 2019 16.7.

Compiler bugs encountered:
* VSO-1231996 Missing `__builtin_*` intrinsics helpers for Corresponding Member and Pointer-interconvertibility Traits
  + Fixed for VS 2019 16.9 Preview 2 by MSVC-PR-282455
* VSO-1232619 `__builtin_is_pointer_interconvertible_base_of` intrinsic returns incorrect values
  + Fixed for VS 2019 16.9 Preview 2 by MSVC-PR-285501

### PR DESCRIPTION
**Pull request by MahmoudGSaleh**
This PR implements [P0466R5](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p0466r5.pdf). It will close #18.

This is ready for review:

- [x] implement feature calling by compiler intrinsics in <type_traits>
- [x] implement tests
- [x] All tests passing (including clang and BE)

The following bugs are used to track related issues:
* [LLVM 48860](https://bugs.llvm.org/show_bug.cgi?id=46685) - MSVC Compatibility: Implement intrinsics for P0466R5 - Layout-compatibility and Pointer-interconvertibility Traits 
* VSO-1268984 - [EDG] New compiler intrinsics for Layout-compatibility and Pointer-interconvertibility Traits need to be understood by EDG

### CODE REVIEW

**Comment by StephanTLavavej** [comment]
I've marked this PR as a draft and removed WIP from the title.

Many of the test failures are caused by Clang not understanding the new compiler builtins. We should request them by filing an LLVM bug, and then guard the definitions accordingly.

File: stl/inc/type_traits [hunk 1]
```diff
@@ -1804,6 +1804,36 @@ inline constexpr bool is_nothrow_invocable_r_v =
...
+// STRUCT TEMPLATE is_pointer_interconvertible_base_of
+template <class _Base, class _Derived>
+struct is_pointer_interconvertible_base_of
+    : bool_constant<__builtin_is_pointer_interconvertible_base_of(_Base, _Derived)> {};
+
+template <class _Base, class _Derived>
+inline constexpr bool is_pointer_interconvertible_base_of_v = __builtin_is_pointer_interconvertible_base_of(
+    _Base, _Derived);
+
+// STRUCT TEMPLATE is_pointer_interconvertible_with_class
```
Comment (StephanTLavavej) [inline stl/inc/type_traits:1824]: This is a `FUNCTION TEMPLATE`. Ditto below.

File: stl/inc/type_traits [hunk 2]
```diff
@@ -1804,6 +1804,36 @@ inline constexpr bool is_nothrow_invocable_r_v =
...
+template <class _Sty, class _ObjTy>
+inline constexpr bool is_pointer_interconvertible_with_class(_ObjTy _Sty::*_Pm) noexcept {
```
Comment (StephanTLavavej) [inline stl/inc/type_traits:1826]: For functions, `constexpr` implies `inline`, and we conventionally avoid saying `inline` unnecessarily. Ditto below.

Comment (StephanTLavavej) [inline stl/inc/type_traits:1826]: This function is a "pure observer" - it has no side effects, so its only purpose is to generate its return value. This is our top criterion for marking functions as `_NODISCARD`. Ditto below.

File: stl/inc/yvals_core.h [hunk 3]
```diff
@@ -1207,7 +1207,9 @@
 #define __cpp_lib_integer_comparison_functions 202002L
 #define __cpp_lib_interpolate                  201902L
 #define __cpp_lib_is_constant_evaluated        201811L
+#define __cpp_lib_is_layout_compatible         202101L
```
Comment (StephanTLavavej) [inline stl/inc/yvals_core.h:1210]: These values are incorrect. The correct values are noted in #18 (typically they correspond to the month that a feature was voted into the Working Paper); the authoritative source is WG21-N4878 17.3.2 [version.syn], and [SD-FeatureTest](https://isocpp.org/std/standing-documents/sd-6-sg10-feature-test-recommendations) should provide the same info with more context.

Comment (StephanTLavavej) [inline stl/inc/yvals_core.h:1210]: Note that the feature-test macros need to correspond to the feature's availability, so if the definitions of the type traits need to be guarded for Clang, the feature-test macros need to be guarded in the same way.

Comment (StephanTLavavej) [inline stl/inc/yvals_core.h:1210]: New feature-test macros need to be tested in `tests/std/tests/VSO_0157762_feature_test_macros`.

File: tests/std/tests/P0466R5_layout_compatibility_and_pointer_interconvertibility_traits/test.cpp [hunk 4]
```diff
@@ -0,0 +1,179 @@
+// Copyright (c) Microsoft Corporation.
+// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
+#include <assert.h>
+#include <iostream>
```
Comment (StephanTLavavej) [inline tests/std/tests/P0466R5_layout_compatibility_and_pointer_interconvertibility_traits/test.cpp:4]: It appears that `<iostream>` is unused.

File: tests/std/tests/P0466R5_layout_compatibility_and_pointer_interconvertibility_traits/test.cpp [hunk 5]
```diff
@@ -0,0 +1,179 @@
...
+            int a;
+        };
+
+        // A standard-layout class
+        struct B {
+            int b;
+        };
+
+        // Not a standard-layout class
+        struct C : public A, public B {};
```
Comment (StephanTLavavej) [inline tests/std/tests/P0466R5_layout_compatibility_and_pointer_interconvertibility_traits/test.cpp:155]: `struct` implies `public` for data members and base classes, and we conventionally avoid repeating it. (But while `class` implies `private`, we conventionally repeat that when it occurs.)

**Review by StephanTLavavej — CHANGES_REQUESTED** [review]

File: tests/std/tests/P0466R5_layout_compatibility_and_pointer_interconvertibility_traits/test.cpp [hunk 6]
```diff
@@ -0,0 +1,179 @@
...
+        enum E3 : unsigned int { e7, e8, e9 };
+
+        ASSERT(is_layout_compatible_v<int, int>);
+        ASSERT(is_layout_compatible_v<E1, E2>);
+        ASSERT(is_layout_compatible_v<S1, S2>);
+
+        ASSERT(!is_layout_compatible_v<int, char>);
+        ASSERT(!is_layout_compatible_v<E1, E3>);
+        ASSERT(!is_layout_compatible_v<S1, S3>);
+    }
```
[the remark this answers is not in the document]
Comment (CaseyCarter) [reply tests/std/tests/P0466R5_layout_compatibility_and_pointer_interconvertibility_traits/test.cpp:49]: It would also be nice to verify that the results are not affected by cv-qualifiers on the types.

File: tests/std/tests/P0466R5_layout_compatibility_and_pointer_interconvertibility_traits/test.cpp [hunk 7]
```diff
@@ -0,0 +1,179 @@
...
+        ASSERT(is_pointer_interconvertible_base_of_v<A, E>);
+        ASSERT(is_pointer_interconvertible_base_of_v<A, A1>);
+        ASSERT(is_pointer_interconvertible_base_of_v<A, A2>);
+        ASSERT(is_pointer_interconvertible_base_of_v<A, A3>);
+        ASSERT(is_pointer_interconvertible_base_of_v<A2, A3>);
+
+        ASSERT(!is_pointer_interconvertible_base_of_v<A4, A>);
+        ASSERT(!is_pointer_interconvertible_base_of_v<A1, E>);
+        ASSERT(!is_pointer_interconvertible_base_of_v<A3, E>);
+    }
```
Comment (CaseyCarter) [inline tests/std/tests/P0466R5_layout_compatibility_and_pointer_interconvertibility_traits/test.cpp:87]: Ditto results should be oblivious to cv-qualifiers.

File: tests/std/tests/P0466R5_layout_compatibility_and_pointer_interconvertibility_traits/test.cpp [hunk 8]
```diff
@@ -0,0 +1,179 @@
...
+        };
+#pragma warning(pop)
+        class E : public A {
+            int v1 = 2;
+        };
+
+        class A1 : public A {};
+        class A2 : public A {};
+        class A3 : public A2 {};
+        class A4 : A1, A3 {};
```
Comment (CaseyCarter) [inline tests/std/tests/P0466R5_layout_compatibility_and_pointer_interconvertibility_traits/test.cpp:72]: Why'd we switch from public to private inheritance here? It shouldn't make any difference since the trait sees private bases (as does `is_base_of`), so the anomaly is suspect.

File: tests/std/tests/P0466R5_layout_compatibility_and_pointer_interconvertibility_traits/test.cpp [hunk 9]
```diff
@@ -0,0 +1,179 @@
...
+        ASSERT(!is_corresponding_member(&S1::v2, &S2::v1));
+
+        // Same member - different class (not layout compatible)
+        ASSERT(!is_corresponding_member(&S1::v1, &S4::v1));
+        ASSERT(!is_corresponding_member(&S1::v2, &S4::v2));
+
+        // Same member - different class (not layout compatible)
+        ASSERT(!is_corresponding_member(&S3::v1, &S4::v1));
+        ASSERT(!is_corresponding_member(&S3::v2, &S4::v2));
+    }
```
Comment (CaseyCarter) [inline tests/std/tests/P0466R5_layout_compatibility_and_pointer_interconvertibility_traits/test.cpp:140]: This is missing test cases for corresponding members in the common initial sequence of two different standard-layout types that also have non-corresponding members:
```c++
struct X {
  int v1;
  int v2;
  void* v3;
};

struct Y {
  int v1;
  int v2;
  double v3;
};

ASSERT(is_corresponding_member(&X::v1, &Y::v1));
ASSERT(is_corresponding_member(&X::v2, &Y::v2));
ASSERT(!is_corresponding_member(&X::v1, &Y::v2));
ASSERT(!is_corresponding_member(&X::v2, &Y::v1));
ASSERT(!is_corresponding_member(&X::v3, &Y::v3));
```

**Review by CaseyCarter — CHANGES_REQUESTED** [review]

File: tests/std/tests/P0466R5_layout_compatibility_and_pointer_interconvertibility_traits/test.cpp (hunk 5 above)
Comment (CaseyCarter) [reply tests/std/tests/P0466R5_layout_compatibility_and_pointer_interconvertibility_traits/test.cpp:155]: > `struct` implies `public` for data members and base classes, and we conventionally avoid repeating it. (But while `class` implies `private`, we conventionally repeat that when it occurs.)

I find this inconsistency disturbing. Could we choose one or the other?

File: tests/std/tests/P0466R5_layout_compatibility_and_pointer_interconvertibility_traits/test.cpp (hunk 6 above)
[the remark this answers is not in the document]
Comment (MahmoudGSaleh) [reply tests/std/tests/P0466R5_layout_compatibility_and_pointer_interconvertibility_traits/test.cpp:85]: Added recommended tests, including for types cv-qualifiers .

File: tests/std/tests/P0466R5_layout_compatibility_and_pointer_interconvertibility_traits/test.cpp (hunk 7 above)
Comment (MahmoudGSaleh) [reply tests/std/tests/P0466R5_layout_compatibility_and_pointer_interconvertibility_traits/test.cpp:125]: Fixed

File: tests/std/tests/P0466R5_layout_compatibility_and_pointer_interconvertibility_traits/test.cpp (hunk 9 above)
Comment (MahmoudGSaleh) [reply tests/std/tests/P0466R5_layout_compatibility_and_pointer_interconvertibility_traits/test.cpp:183]: Added missing test. Names the structs S5 and S6 though for consistency

File: tests/std/tests/P0466R5_layout_compatibility_and_pointer_interconvertibility_traits/test.cpp (hunk 5 above)
Comment (MahmoudGSaleh) [reply tests/std/tests/P0466R5_layout_compatibility_and_pointer_interconvertibility_traits/test.cpp:195]: Fixed

File: tests/std/tests/P0466R5_layout_compatibility_and_pointer_interconvertibility_traits/test.cpp [hunk 10]
```diff
@@ -0,0 +1,215 @@
...
+        union U {
+            int v1;
+            char v2;
+        };
+
+        ASSERT(is_pointer_interconvertible_with_class(&C::b));
+        ASSERT(!is_pointer_interconvertible_with_class<C>(&C::b));
+
+        ASSERT(is_pointer_interconvertible_with_class(&U::v1));
+        ASSERT(is_pointer_interconvertible_with_class(&U::v2));
```
Comment (MahmoudGSaleh) [inline tests/std/tests/P0466R5_layout_compatibility_and_pointer_interconvertibility_traits/test.cpp:206]: These tests are newly added.

File: stl/inc/type_traits (hunk 1 above)
Comment (MahmoudGSaleh) [reply stl/inc/type_traits]: Fixed

File: stl/inc/type_traits (hunk 2 above)
Comment (MahmoudGSaleh) [reply stl/inc/type_traits]: Fixed

File: stl/inc/yvals_core.h (hunk 3 above)
Comment (MahmoudGSaleh) [reply stl/inc/yvals_core.h]: Added new feature-test macros tests

File: tests/std/tests/P0466R5_layout_compatibility_and_pointer_interconvertibility_traits/test.cpp (hunk 4 above)
Comment (MahmoudGSaleh) [reply tests/std/tests/P0466R5_layout_compatibility_and_pointer_interconvertibility_traits/test.cpp]: Removed unused include

File: stl/inc/yvals_core.h (hunk 3 above)
[the remark this answers is not in the document]
Comment (MahmoudGSaleh) [reply stl/inc/yvals_core.h]: Fixed

File: stl/inc/type_traits (hunk 2 above)
[the remark this answers is not in the document]
Comment (MahmoudGSaleh) [reply stl/inc/type_traits]: Fixed

File: tests/std/tests/P0466R5_layout_compatibility_and_pointer_interconvertibility_traits/test.cpp [hunk 11]
```diff
@@ -0,0 +1,179 @@
...
+            S s1;
+            int v2;
+            int v3;
+        };
+
+        enum E1 { e1, e2, e3 };
+
+        enum E2 : int { e4, e5, e6 };
+
+        enum E3 : unsigned int { e7, e8, e9 };
```
[the remark this answers is not in the document]
Comment (MahmoudGSaleh) [reply tests/std/tests/P0466R5_layout_compatibility_and_pointer_interconvertibility_traits/test.cpp]: Made the enumerators differ in number of elements

File: tests/std/tests/P0466R5_layout_compatibility_and_pointer_interconvertibility_traits/test.cpp (hunk 8 above)
Comment (MahmoudGSaleh) [reply tests/std/tests/P0466R5_layout_compatibility_and_pointer_interconvertibility_traits/test.cpp]: Fixed, made consistent

File: stl/inc/type_traits (hunk 2 above)
Comment (MahmoudGSaleh) [reply stl/inc/type_traits]: Fixed, thanks for the clarification

File: stl/inc/yvals_core.h (hunk 3 above)
Comment (MahmoudGSaleh) [reply stl/inc/yvals_core.h]: Resolved

File: stl/inc/yvals_core.h [hunk 12]
```diff
@@ -1207,7 +1207,9 @@
 #define __cpp_lib_integer_comparison_functions 202002L
 #define __cpp_lib_interpolate                  201902L
 #define __cpp_lib_is_constant_evaluated        201811L
+#define __cpp_lib_is_layout_compatible         202101L
 #define __cpp_lib_is_nothrow_convertible       201806L
+#define __cpp_lib_is_pointer_interconvertible  202101L
```
[the remark this answers is not in the document]
Comment (MahmoudGSaleh) [reply stl/inc/yvals_core.h]: resolved

File: stl/inc/type_traits [hunk 13]
```diff
@@ -1804,6 +1804,36 @@ inline constexpr bool is_nothrow_invocable_r_v =
...
+template <class _Base, class _Derived>
+struct is_pointer_interconvertible_base_of
+    : bool_constant<__builtin_is_pointer_interconvertible_base_of(_Base, _Derived)> {};
+
+template <class _Base, class _Derived>
+inline constexpr bool is_pointer_interconvertible_base_of_v = __builtin_is_pointer_interconvertible_base_of(
+    _Base, _Derived);
+
+// STRUCT TEMPLATE is_pointer_interconvertible_with_class
+template <class _Sty, class _ObjTy>
```
[the remark this answers is not in the document]
Comment (MahmoudGSaleh) [reply stl/inc/type_traits]: Used suggested names

File: stl/inc/type_traits (hunk 1 above)
[the remark this answers is not in the document]
Comment (MahmoudGSaleh) [reply stl/inc/type_traits]: Fixed

**Comment by MahmoudGSaleh** [comment]
Analyzing the x86 failures.

File: tests/std/tests/P0466R5_layout_compatibility_and_pointer_interconvertibility_traits/test.cpp [hunk 14]
```diff
@@ -0,0 +1,215 @@
...
+
+        struct S5 {
+            int v1;
+
+        private:
+            int v2;
+        };
+
+
+        const struct S6 {
```
Comment (cpplearner) [inline tests/std/tests/P0466R5_layout_compatibility_and_pointer_interconvertibility_traits/test.cpp:51]: `const` is meaningless here. Ditto for `volatile` below.

```suggestion
        using S6 = const struct {
```

File: stl/inc/type_traits [hunk 15]
```diff
@@ -1804,6 +1804,38 @@ inline constexpr bool is_nothrow_invocable_r_v =
...
+    : bool_constant<__builtin_is_pointer_interconvertible_base_of(_Base, _Derived)> {};
+
+template <class _Base, class _Derived>
+inline constexpr bool is_pointer_interconvertible_base_of_v = __builtin_is_pointer_interconvertible_base_of(
+    _Base, _Derived);
+
+// FUNCTION TEMPLATE is_pointer_interconvertible_with_class
+template <class _ClassTy, class _MemberTy>
+_NODISCARD constexpr bool is_pointer_interconvertible_with_class(_MemberTy _ClassTy::*_Pm) noexcept {
+    return __builtin_is_pointer_interconvertible_with_class(_ClassTy, _Pm);
```
Comment (CaseyCarter) [inline stl/inc/type_traits:1828]: Current state: hundreds of errors from `/BE` compiles complaining that `_ClassTy` on this line is a type, which I suppose suggests that nobody ever taught EDG this intrinsic?

File: tests/std/tests/P0466R5_layout_compatibility_and_pointer_interconvertibility_traits/test.cpp (hunk 14 above)
Comment (MahmoudGSaleh) [reply tests/std/tests/P0466R5_layout_compatibility_and_pointer_interconvertibility_traits/test.cpp:51]: Thanks for pointing this out. I'll use this style in the tests:
ASSERT(is_layout_compatible_v<_const_ S1, S2>);

Comment (MahmoudGSaleh) [reply tests/std/tests/P0466R5_layout_compatibility_and_pointer_interconvertibility_traits/test.cpp]: Fixed

File: stl/inc/type_traits (hunk 15 above)
Comment (MahmoudGSaleh) [reply stl/inc/type_traits:1829]: Disabled the /BE tests and filed bug on EDG

File: stl/inc/type_traits [hunk 16]
```diff
@@ -1804,6 +1804,40 @@ inline constexpr bool is_nothrow_invocable_r_v =
     _Select_invoke_traits<_Callable, _Args...>::template _Is_nothrow_invocable_r<_Rx>::value;
 #endif // _HAS_CXX17
 
+#if _HAS_CXX20
+#ifndef __EDG__ // TRANSITION, VSO-1268984
+#ifndef __clang__ // TRANSITION, LLVM-Bug #: To Be Filed
```
Comment (CaseyCarter) [inline stl/inc/type_traits:1809]: I could live with merging this as-is and fixing later, but it would be nice to have the LLVM bug# now. I or Stephan can post the report for you if the delay is getting an account up at bugs.llvm.org.

**Review by CaseyCarter — CHANGES_REQUESTED** [review]

File: tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp [hunk 17]
```diff
@@ -864,6 +864,24 @@ STATIC_ASSERT(__cpp_lib_is_nothrow_convertible == 201806L);
 #endif
 #endif
 
+#if _HAS_CXX20
```
[the remark this answers is not in the document]
Comment (MahmoudGSaleh) [reply tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp]: Good catch. Fixed.

**Review by CaseyCarter — APPROVED** [review]

File: stl/inc/type_traits (hunk 16 above)
Comment (MahmoudGSaleh) [reply stl/inc/type_traits:1809]: Yes, I'm still waiting for the account approval. I'd like to go through the process of creating the LLVM bug, but would also be fine if you want to post the report.

Comment (CaseyCarter) [reply stl/inc/type_traits:1809]: If you are interested in the full process then I won't stand in your way ;)

File: tests/std/tests/P0466R5_layout_compatibility_and_pointer_interconvertibility_traits/test.cpp [hunk 18]
```diff
@@ -0,0 +1,200 @@
...
+        ASSERT(is_pointer_interconvertible_base_of_v<A, D>);
+        ASSERT(is_pointer_interconvertible_base_of_v<A, A1>);
+        ASSERT(is_pointer_interconvertible_base_of_v<A, A2>);
+        ASSERT(is_pointer_interconvertible_base_of_v<A, A3>);
+        ASSERT(is_pointer_interconvertible_base_of_v<A2, A3>);
+
+        ASSERT(!is_pointer_interconvertible_base_of_v<A1, A2>);
+        ASSERT(!is_pointer_interconvertible_base_of_v<A4, A>);
+        ASSERT(!is_pointer_interconvertible_base_of_v<B, C>);
+    }
```
Comment (StephanTLavavej) [inline tests/std/tests/P0466R5_layout_compatibility_and_pointer_interconvertibility_traits/test.cpp:109]: The Condition for `is_pointer_interconvertible_base_of` is:

> `Derived` is unambiguously derived from `Base` without regard to cv-qualifiers, and each object of type `Derived` is pointer-interconvertible (6.8.3) with its `Base` subobject, or `Base` and `Derived` are not unions and name the same class type without regard to cv-qualifiers.

So the following cases aren't being tested:

* Non-`public` inheritance (as WG21-P0466 notes, "Here the derivation relationship need not be public, as pointer-interconvertibility does not respect access control.")
* `<int, int>` should be `false` (this tests "the same class type")
* `<MyUnion, MyUnion>` should be `false` (this tests "are not unions")

The requirements are:

> If `Base` and `Derived` are non-union class types and are not (possibly cv-qualified versions of) the same type, `Derived` shall be a complete type.

This indicates further test cases, where the compiler can confidently report `false` or `true` even when an input is incomplete:

* `<void, void>` should be `false`
* `<int, IncompleteClass>` should be `false`
* `<MyUnion, IncompleteClass>` should be `false`
* `<const IncompleteClass, IncompleteClass>` should be `true`

File: tests/std/tests/P0466R5_layout_compatibility_and_pointer_interconvertibility_traits/test.cpp [hunk 19]
```diff
@@ -0,0 +1,200 @@
...
+        ASSERT(!is_corresponding_member(&S1::v1, &S2::v2));
+        ASSERT(!is_corresponding_member(&S1::v2, &S2::v1));
+        ASSERT(!is_corresponding_member(&S1::v1, &S4::v1));
+        ASSERT(!is_corresponding_member(&S1::v2, &S4::v2));
+        ASSERT(!is_corresponding_member(&S3::v1, &S4::v1));
+        ASSERT(!is_corresponding_member(&S3::v2, &S4::v2));
+        ASSERT(!is_corresponding_member(&S5::v1, &S6::v2));
+        ASSERT(!is_corresponding_member(&S5::v2, &S6::v1));
+        ASSERT(!is_corresponding_member(&S5::v3, &S6::v3));
+    }
```
Comment (StephanTLavavej) [inline tests/std/tests/P0466R5_layout_compatibility_and_pointer_interconvertibility_traits/test.cpp:167]: WG21-N4878 [meta.member]/4:

> "*Returns:* `true` if and only if `S1` and `S2` are standard-layout types, `M1` and `M2` are object types, `m1` and `m2` are not null, and `m1` and `m2` point to corresponding members of the common initial sequence (11.4) of `S1` and `S2`."

This indicates additional test cases:

* Non-standard-layout types
* Pointers to member functions
* Null pointers

File: tests/std/tests/P0466R5_layout_compatibility_and_pointer_interconvertibility_traits/test.cpp [hunk 20]
```diff
@@ -0,0 +1,200 @@
...
+            int v1;
+            char v2;
+        };
+
+        ASSERT(is_pointer_interconvertible_with_class(&C::b));
+        ASSERT(!is_pointer_interconvertible_with_class<C>(&C::b));
+
+        ASSERT(is_pointer_interconvertible_with_class(&U::v1));
+        ASSERT(is_pointer_interconvertible_with_class(&U::v2));
+    }
```
Comment (StephanTLavavej) [inline tests/std/tests/P0466R5_layout_compatibility_and_pointer_interconvertibility_traits/test.cpp:191]: WG21-N4878 [meta.member]/2:

> *Returns:* `true` if and only if `S` is a standard-layout type, `M` is an object type, `m` is not null, and each
object `s` of type `S` is pointer-interconvertible (6.8.3) with its subobject `s.*m`.

Additional tests:

* Non-standard-layout type
* Pointer to member function
* Null pointer

**Review by StephanTLavavej — CHANGES_REQUESTED** [review]

File: tests/std/tests/P0466R5_layout_compatibility_and_pointer_interconvertibility_traits/test.cpp [hunk 21]
```diff
@@ -0,0 +1,200 @@
+// Copyright (c) Microsoft Corporation.
+// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
+#include <assert.h>
+#include <type_traits>
+
```
[the remark this answers is not in the document]
Comment (MahmoudGSaleh) [reply tests/std/tests/P0466R5_layout_compatibility_and_pointer_interconvertibility_traits/test.cpp:5]: Added to test.lst

File: tests/std/tests/P0466R5_layout_compatibility_and_pointer_interconvertibility_traits/test.cpp [hunk 22]
```diff
@@ -0,0 +1,200 @@
...
+        ASSERT(is_pointer_interconvertible_base_of_v<A, volatile C>);
+        ASSERT(is_pointer_interconvertible_base_of_v<volatile A, const C>);
+        ASSERT(is_pointer_interconvertible_base_of_v<A, D>);
+        ASSERT(is_pointer_interconvertible_base_of_v<A, A1>);
+        ASSERT(is_pointer_interconvertible_base_of_v<A, A2>);
+        ASSERT(is_pointer_interconvertible_base_of_v<A, A3>);
+        ASSERT(is_pointer_interconvertible_base_of_v<A2, A3>);
+
+        ASSERT(!is_pointer_interconvertible_base_of_v<A1, A2>);
+        ASSERT(!is_pointer_interconvertible_base_of_v<A4, A>);
```
[the remark this answers is not in the document]
Comment (MahmoudGSaleh) [reply tests/std/tests/P0466R5_layout_compatibility_and_pointer_interconvertibility_traits/test.cpp]: I've removed the An classes to eliminate redundancy, but the same tests should still be applicable through the remaining classes

File: tests/std/tests/P0466R5_layout_compatibility_and_pointer_interconvertibility_traits/test.cpp [hunk 23]
```diff
@@ -7,10 +7,15 @@ using namespace std;
 
 #define ASSERT(...) assert((__VA_ARGS__))
 
+struct S { // struct with static type, so declaring global
```
Comment (CaseyCarter) [inline tests/std/tests/P0466R5_layout_compatibility_and_pointer_interconvertibility_traits/test.cpp:10]:
```suggestion
struct S { // Must be declared at namespace scope due to static data member
```

File: tests/std/tests/P0466R5_layout_compatibility_and_pointer_interconvertibility_traits/test.cpp [hunk 24]
```diff
@@ -55,21 +60,34 @@ constexpr bool test() {
...
-        ASSERT(is_layout_compatible_v<S1, S2>);
-        ASSERT(is_layout_compatible_v<S4, S4>);
-        ASSERT(is_layout_compatible_v<const volatile S4, S4>);
+        ASSERT(is_layout_compatible_v<int[], int[]>);
+        ASSERT(is_layout_compatible_v<int[3], int[3]>);
+
+        // TRANSITION, VSO-1269781
+        // ASSERT(is_layout_compatible_v<const int[], int[]>);
+        // ASSERT(is_layout_compatible_v<const int[3], int[3]>);
+        // ASSERT(is_layout_compatible_v<int[], volatile int[]>);
```
Comment (CaseyCarter) [inline tests/std/tests/P0466R5_layout_compatibility_and_pointer_interconvertibility_traits/test.cpp:79]: VSO-1269781 is an MSVC bug, there's no reason to hide these particular cases from Clang and EDG (more than they already are).
```suggestion
#if defined(__clang__) || defined(__EDG__) // TRANSITION, VSO-1269781
        ASSERT(is_layout_compatible_v<const int[], int[]>);
        ASSERT(is_layout_compatible_v<const int[3], int[3]>);
        ASSERT(is_layout_compatible_v<int[], volatile int[]>);
#endif // TRANSITION, VSO-1269781
```

File: tests/std/tests/P0466R5_layout_compatibility_and_pointer_interconvertibility_traits/test.cpp [hunk 25]
```diff
@@ -79,17 +97,22 @@ constexpr bool test() {
...
+        class E : public A {
             union {};
         };
 #pragma warning(pop)
-        class A1 : public A {};
-        class A2 : public A {};
-        class A3 : public A2 {};
-        class A4 : public A1, public A3 {};
+        class F : private A {}; // Non-public inheritance
+        class NS : public B, public C {}; // Non-standard
```
Comment (CaseyCarter) [inline tests/std/tests/P0466R5_layout_compatibility_and_pointer_interconvertibility_traits/test.cpp:109]: All of these types are non-standard, the standard doesn't define them. I think you mean non-standard-layout. (Also on 183 and 228.)

**Review by CaseyCarter — CHANGES_REQUESTED** [review]

File: tests/std/tests/P0466R5_layout_compatibility_and_pointer_interconvertibility_traits/test.cpp (hunk 25 above)
Comment (MahmoudGSaleh) [reply tests/std/tests/P0466R5_layout_compatibility_and_pointer_interconvertibility_traits/test.cpp:109]: Yes, non-standard layout. I'll update the comments.

**Review by CaseyCarter — APPROVED** [review]

File: tests/std/tests/P0466R5_layout_compatibility_and_pointer_interconvertibility_traits/test.cpp [hunk 26]
```diff
@@ -98,14 +122,21 @@ constexpr bool test() {
...
+        ASSERT(is_pointer_interconvertible_base_of_v<C, D>);
+        ASSERT(is_pointer_interconvertible_base_of_v<I, I>);
+        ASSERT(is_pointer_interconvertible_base_of_v<const I, I>);
+
+        ASSERT(!is_pointer_interconvertible_base_of_v<int, int>);
+        ASSERT(!is_pointer_interconvertible_base_of_v<void, void>);
+        ASSERT(!is_pointer_interconvertible_base_of_v<A, int>);
         ASSERT(!is_pointer_interconvertible_base_of_v<B, C>);
+        ASSERT(!is_pointer_interconvertible_base_of_v<A, NS>);
+        ASSERT(!is_pointer_interconvertible_base_of_v<B, NS>);
```
Comment (StephanTLavavej) [inline tests/std/tests/P0466R5_layout_compatibility_and_pointer_interconvertibility_traits/test.cpp:136]: This is an extremely good test (I noticed that it goes beyond my previous round of feedback, and tests the standard-layout part of pointer-interconvertible, arriving at a different answer than classic `is_base_of_v`). Thanks for adding it!

File: tests/std/tests/P0466R5_layout_compatibility_and_pointer_interconvertibility_traits/test.cpp [hunk 27]
```diff
@@ -144,26 +175,39 @@ constexpr bool test() {
...
         ASSERT(!is_corresponding_member(&S1::v2, &S4::v2));
         ASSERT(!is_corresponding_member(&S3::v1, &S4::v1));
         ASSERT(!is_corresponding_member(&S3::v2, &S4::v2));
         ASSERT(!is_corresponding_member(&S5::v1, &S6::v2));
         ASSERT(!is_corresponding_member(&S5::v2, &S6::v1));
         ASSERT(!is_corresponding_member(&S5::v3, &S6::v3));
+        ASSERT(!is_corresponding_member<NS, NS>(&NS::v1, &NS::w1));
+        ASSERT(!is_corresponding_member(&S7::f1, &S7::f1));
+        ASSERT(!is_corresponding_member<S1, S2, int, int>(nullptr, nullptr));
+        ASSERT(!is_corresponding_member<S1, S2, int, int>(&S1::v1, nullptr));
```
Comment (StephanTLavavej) [inline tests/std/tests/P0466R5_layout_compatibility_and_pointer_interconvertibility_traits/test.cpp:210]: I think it would be slightly better to use `static_cast` to form null pointers of the desired types, allowing template argument deduction to be used normally. That will make the remaining explicit template arguments (for `NS`) stand out as being necessary. I'll push a change for this (and the `nullptr` below).

**Review by StephanTLavavej — COMMENTED** [review]
This looks great! I'll verify and push a change to use `static_cast` for `nullptr`, then I'll mirror this to MSVC.

**Review by StephanTLavavej — APPROVED** [review]

**Review by CaseyCarter — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Thanks for implementing this feature with a comprehensive set of tests, and congratulations on your first microsoft/STL commit! :tada: :smile_cat:
