### PR TITLE
`<chrono>`: Fix formatting for unusual `duration`s

### LINKED ISSUE #3644: `<chrono>`: Some (weird) durations still cannot be formatted
Repro:

```c++
#include <chrono>
#include <format>
#include <iostream>

int main() {
  // remove `+ 1` to get rid of an error (see https://godbolt.org/z/9WGMoWeeo)
  using R = std::ratio<128 + 64 + 8 + 1, std::numeric_limits<int>::max()>;
  using D = std::chrono::duration<int, R>;
  std::cout << std::format("{:%Q %q}\n", D{4});
}
```

Build:

```console
PS D:\stl-playground> cl /std:c++20 /EHsc /nologo .\chronat.cpp
chronat.cpp
D:\stl\out\build\x64\out\inc\chrono(4949): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'std::chrono::hh_mm_ss<_Ty>'
        with
        [
            _Ty=std::chrono::duration<int,R>
        ]
D:\stl\out\build\x64\out\inc\chrono(4949): note: No constructor could take the source type, or constructor overload resolution was ambiguous
D:\stl\out\build\x64\out\inc\chrono(5013): note: see reference to function template instantiation 'std::chrono::hh_mm_ss<_Ty> std::chrono::_Hh_mm_ss_part_underflow_to_zero<_Ty>(const _Duration &)' being compiled
        with
        [
            _Ty=std::chrono::duration<int,R>,
            _Duration=std::chrono::duration<int,R>
        ]
# [...]
```

Compiler explorer: https://godbolt.org/z/o71s74c8K

### PR DESCRIPTION
**Pull request by frederick-vs-ja**
Fixes #3644. `hh_mm_ss<_Duration>` seems wrong for `_Hh_mm_ss_part_underflow_to_zero` to me.

Need to explore how to accept `duration<I, ratio<9223372036854775806, 9223372036854775807>>`. Currently libstdc++ rejects it, while libc++ accepts it ([Godbolt link](https://godbolt.org/z/6nb5EMKdx)).

Edit: the current approach for calculation of `hh_mm_ss<D>::fractional_width` doesn't seem right. I'm trying to fix it.

Edit 2: now the formatting is made well-formed, but UB may happen.

### CODE REVIEW

**Comment by StephanTLavavej** [comment]
As a reminder, I strongly recommend running tests locally before pushing changes. You don't have to do a full test pass every time, but at a minimum, running the `*chrono*` and `*format*` directories would be easy and quick:

```
C:\GitHub\STL\tests\std\tests>dir /b *chrono* *format*
GH_002558_format_presetPadding
P0092R1_polishing_chrono
P0355R7_calendars_and_time_zones_formatting
P0645R10_text_formatting_args
P0645R10_text_formatting_custom_formatting
P0645R10_text_formatting_death
P0645R10_text_formatting_formatting
P0645R10_text_formatting_grapheme_clusterization
P0645R10_text_formatting_legacy_text_encoding
P0645R10_text_formatting_parse_contexts
P0645R10_text_formatting_parsing
P0645R10_text_formatting_utf8
P2093R14_formatted_output
```

(As a general rule, if attempting to fix failed test directories, all of those should be rerun too.)

This helps conserve CI system resources, and helps you iterate faster - win-win! :smile_cat:

**Comment by frederick-vs-ja** [comment]
Currently no implementation correctly formats `duration<int64_t, ratio<INT64_MAX -1, INT64_MAX>>{40}` ([Godbolt link](https://godbolt.org/z/GfaEsqMnz)). In MSVC STL, libc++, and libstdc++, `hh_mm_ss` is used when formatting `duration` and thus `duration_cast` is also involved. And it's extremly easy for `duration_cast` to cause UB when the souce type is `duration<int64_t, ratio<INT64_MAX -1, INT64_MAX>>`.

However, it seems that [[time.format]](https://eel.is/c++draft/time.format) doens't say `duration_cast` or `hh_mm_ss` is equivalently used when formatting `duration`, so perhaps the current standard wording is requiring correctly formatting such `duration`...

File: stl/inc/chrono [hunk 1]
```diff
@@ -1578,16 +1578,23 @@ namespace chrono {
...
             }
-            return _Result == 19 ? 6 : _Result;
+            for (; _Den % 5 == 0; _Den /= 5, ++_Power_of_5_in_den) {
+            }
+
+            if (_Den != 1) {
+                return 6u;
+            }
+            const auto _Result = _STD max(_Power_of_2_in_den, _Power_of_5_in_den);
+            return _Result > 18u ? 6u : _Result;
```
Comment (strega-nil-ms) [inline stl/inc/chrono:1597]: This is really, really clever and I like it.

File: stl/inc/chrono [hunk 2]
```diff
@@ -1578,16 +1578,23 @@ namespace chrono {
...
             // If it can't be represented, 6 is returned.
             // Example: _Fractional_width(1, 8) would return 3 for 0.125.
-            _STL_ASSERT(_Num > 0 && _Den > 0, "Numerator and denominator can't be less than 1.");
-            unsigned int _Result = 0;
-            for (; _Num % _Den != 0 && _Result < 19; _Num = _Num % _Den * 10, ++_Result) {
+            auto _Den = _Duration::period::den;
+            _STL_ASSERT(_Duration::period::num > 0 && _Den > 0, "Numerator and denominator can't be less than 1.");
+            unsigned int _Power_of_2_in_den = 0u;
+            unsigned int _Power_of_5_in_den = 0u;
+            for (; _Den % 2 == 0; _Den /= 2, ++_Power_of_2_in_den) {
```
Comment (strega-nil-ms) [inline stl/inc/chrono:1588]: We can make this faster by doing a `countr_zero`. (although I'm not that concerned about it)

**Review by strega-nil-ms — APPROVED** [review]

**Comment by strega-nil-ms** [comment]
Wait, actually, I'm trying to understand the UB here...

**Comment by frederick-vs-ja** [comment]
> Wait, actually, I'm trying to understand the UB here... could you write up an example?

I attempted to test formatting `duration<int, ratio<INT64_MAX - 1, INT64_MAX>>{40}`. The duration needs to undergo `_Hh_mm_ss_part_underflow_to_zero`, and thus `_Remove_duration_part`. Finally `duration_cast<days>(...)` needs to be called, and signed integer overflow is unavoidable.

Reduced example that contains needed runtime operations and fails to compile due to integer overflow ([Godbolt link](https://godbolt.org/z/59sq5vfqh)):
```C++
#include <chrono>
#include <cstdint>
#include <limits>
#include <ratio>
#include <type_traits>

using LongRatio = std::ratio<INT64_MAX - 1, INT64_MAX>;
using D = std::chrono::duration<int, LongRatio>;

constexpr auto weird40 = D{40};
constexpr auto cast_to_day = std::chrono::duration_cast<std::chrono::days>(weird40);
```

**Comment by strega-nil-ms** [comment]
I do feel like we should open an LWG issue for this...

**Comment by frederick-vs-ja** [comment]
> I do feel like we should open an LWG issue for this...

I've filed LWG-3921.

**Review by strega-nil-ms — APPROVED** [review]

File: stl/inc/chrono (hunk 2 above)
Comment (StephanTLavavej) [reply stl/inc/chrono:1588]: Good observation. I believe there's nothing to do here because we're immediately computing a `static constexpr` so everything happens at compile-time, and there is no significant throughput gain to be had here.

File: tests/std/tests/P0355R7_calendars_and_time_zones_formatting/test.cpp [hunk 3]
```diff
@@ -20,6 +21,8 @@
 using namespace std;
 using namespace chrono;
 
+constexpr auto intmax_max = numeric_limits<intmax_t>::max();
```
Comment (StephanTLavavej) [inline tests/std/tests/P0355R7_calendars_and_time_zones_formatting/test.cpp:24]: Technically should include `<cstdint>`.

File: tests/std/tests/P0355R7_calendars_and_time_zones_formatting/test.cpp [hunk 4]
```diff
@@ -247,13 +250,22 @@ void empty_braces_helper(
 
 template <typename CharT>
 void test_duration_formatter() {
+    using LongRatio = ratio<intmax_max - 1, intmax_max>;
```
Comment (StephanTLavavej) [inline tests/std/tests/P0355R7_calendars_and_time_zones_formatting/test.cpp:253]: Surprisingly (and pre-existingly), should include `<ratio>` (`<chrono>` isn't guaranteed to drag it in).

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Thanks! I pushed a conflict-free merge with `main` and trivial header inclusions for the test.

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
We forgot to defend `_STD max` against macroization - pushed.

**Comment by StephanTLavavej** [comment]
Thanks for investigating and fixing this bug! :watch: :tada: :smile_cat:
