### PR TITLE
Fix reliability issues in the parallelize tool

### LINKED ISSUE #1619: parallelize tool may hang or crash
**Describe the bug**
Adding batching of input files to the parallelize tool for my own needs (cuts the runtime for clang-format in half for me), I believe I encountered two issues:

1. Quite often it would crash upon returning from `p.wait_all()` since a kernel mode operation corrupted the stack. This goes away when using an explicit manual-reset event for `OVERLAPPED` in `output_collecting_pipe`.
2. It can hang on exit because the `output_collecting_pipe` destructor does not clear the `running` flag. The threadpool callback then starts another IO operation which never completes.

If useful, I can prepare a patch to fix these.

### PR DESCRIPTION
**Pull request by gix**
Fixes #1619

### CODE REVIEW

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Thanks! I'm far from a Windows API expert but I compared this to the documentation (e.g. the [`OVERLAPPED` docs](https://docs.microsoft.com/en-us/windows/win32/api/minwinbase/ns-minwinbase-overlapped)) and this all looks good to me. :smile_cat:

**Comment by CaseyCarter** [comment]
FYI @BillyONeal. Feel free to review if you like, mostly I want you to know we've found a race condition in parallelize that you may want to pick up if you've reused the tool elsewhere.

File: tools/inc/stljobs.h [hunk 1]
```diff
@@ -305,14 +315,17 @@ struct output_collecting_pipe {
...
+
         readIo = tp_io{std::move(readHandle), callback, this, nullptr};
 
         start();
     }
 
     ~output_collecting_pipe() noexcept {
         if (readIo) {
-            if (running.load()) {
+            if (running.exchange(false)) {
```
Comment (BillyONeal) [inline tools/inc/stljobs.h:328]: This is broken: if it matters then that means something is trying to destroy output_collecting_pipe while another thread is doing some operation to it; the calling code made the mistake.

File: tools/inc/stljobs.h [hunk 2]
```diff
@@ -305,14 +315,17 @@ struct output_collecting_pipe {
         writeHandle = create_file(pipeNameBuffer, GENERIC_WRITE | FILE_READ_ATTRIBUTES, 0, &inheritSa, OPEN_EXISTING,
             FILE_FLAG_OVERLAPPED, HANDLE{});
 
+        readEvent         = create_event(nullptr, TRUE, FALSE, nullptr);
+        overlapped.hEvent = readEvent.get();
```
Comment (BillyONeal) [inline tools/inc/stljobs.h:319]: Can you point to docs indicating that such an event is necessary?

File: tools/inc/stljobs.h (hunk 1 above)
Comment (BillyONeal) [reply tools/inc/stljobs.h:328]: (It's possible that we might need a WaitForThreadpoolXxx call here rather than this exchange edit)

Comment (BillyONeal) [reply tools/inc/stljobs.h:328]: Upon further reflection with @StephanTLavavej I think I understand now: this is to prevent the callback function from calling read_some() again if it gets `ERROR_OPERATION_ABORTED` resulting from the call to `CancelIoEx`.

Perhaps that should be a comment? Or maybe just call stop().

File: tools/inc/stljobs.h (hunk 2 above)
Comment (StephanTLavavej) [reply tools/inc/stljobs.h:319]: After talking to @BillyONeal (trying to understand more of this code that he originally wrote), I would also like to understand why this explicit event is necessary.

In #1619 you said:

> Quite often it would crash upon returning from `p.wait_all()` since a kernel mode operation corrupted the stack. This goes away when using an explicit manual-reset event for `OVERLAPPED` in `output_collecting_pipe`.

From what I saw, nothing in the `OVERLAPPED` docs (or various blog posts about this API) indicates that relying on `hEvent == nullptr` could be harmful. We don't have any code that's trying to wait on the file handle.

Could it be possible that an explicit event is needed for your modifications to the parallelize tool, but not for the current sources?

File: tools/inc/stljobs.h (hunk 1 above)
Comment (StephanTLavavej) [reply tools/inc/stljobs.h:328]: A comment along the lines of `// prevent callback() from calling read_some()` would be sufficient. Replacing this with `stop()` would also be reasonable (slightly less efficient, as I understand it, but not in a noticeable way).

**Review by StephanTLavavej — CHANGES_REQUESTED** [review]

**Review by barcharcraz — APPROVED** [review]
Looks good to me after clarifications to STL's questions.

File: tools/inc/stljobs.h (hunk 2 above)
Comment (gix) [reply tools/inc/stljobs.h:319]: > We don't have any code that's trying to wait on the file handle.

This is most likely a problem in itself, see further below.

> Could it be possible that an explicit event is needed for your modifications to the parallelize tool, but not for the current sources?

If it does happen with the current sources, it is very rare. But it still feels lucky. The only modifications I did was using `subprocess_directive` to get a list of files beforehand. I've pushed a reduced sample to https://github.com/gix/STL/tree/gh1619-repro

Running in the parallelize directory:
```
cl -nologo -EHsc -O2 -std:c++latest -I..\inc -DWIN32_LEAN_AND_MEAN -DNOMINMAX .\parallelize.cpp -link -opt:ref -opt:icf userenv.lib
while ($true) { .\parallelize.exe "clang-format.exe -i" .; if ($LASTEXITCODE -ne 0) { echo $LASTEXITCODE; break } }
```
soon crashes here with
```
Unhandled exception thrown: write access violation. this was 0x1F6C0000120.
```
or
```
Unhandled exception at 0x00007FFD365F85D3 (ntdll.dll) in parallelize.exe: 0xC0000005: Access violation reading location 0x00000223C0000120.
```

What is very suspicious is the involvement of C0000120 which is the NTSTATUS code for `STATUS_CANCELLED`. So it looks like the kernel writes to an already free'd `OVERLAPPED` structure.

Re-reading the docs for [WaitForThreadpoolIoCallbacks](https://docs.microsoft.com/en-us/windows/win32/api/threadpoolapiset/nf-threadpoolapiset-waitforthreadpooliocallbacks) leads me to believe that my fix might even be incomplete and a call to `GetOverlappedResult` (or an equivalent wait operation) must be inserted after `CancelIoEx`. But doing so without a manual reset event just hangs. Doing several non-blocking `GetOverlappedResult` calls (without a manual reset event) shows the error switching from `ERROR_IO_INCOMPLETE` to `ERROR_OPERATION_ABORTED`.

**Comment by BillyONeal** [comment]
>a call to GetOverlappedResult (or an equivalent wait operation) must be inserted after CancelIoEx.

The thread pool is responsible for performing that wait, and then we wait on the threadpool with `WaitForThreadpoolIoCallbacks`.

>Doing several non-blocking GetOverlappedResult calls (without a manual reset event) 

You need separate manual reset events if you issue multiple outstanding IOs on the same file handle. If an event is not supplied, the "secret event" in the file handle itself is used as the synchronization entity. ( https://devblogs.microsoft.com/oldnewthing/20190719-00/?p=102722 ) We never issue concurrent IOs here so the one in the file handle should be OK.

**Comment by gix** [comment]
> The thread pool is responsible for performing that wait, and then we wait on the threadpool with `WaitForThreadpoolIoCallbacks`.

To my knowledge this isn't true. The docs state:

> When fCancelPendingCallbacks is set to TRUE, only queued callbacks are canceled. Pending I/O requests are not canceled. Therefore, the caller should call GetOverlappedResult for the OVERLAPPED structure to check whether the I/O operation has completed before freeing the structure.

Completed here means that the result is written back to the OVERLAPPED structure (aborted or not). So in the repro case, there aren't any queued callbacks, just a single pending one (from the last call to `read_some`) which is then cancelled, but nothing waits for it to actually complete, and the OVERLAPPED goes out of scope before the result is written back, corrupting the stack.

> You need separate manual reset events if you issue multiple outstanding IOs on the same file handle. If an event is not supplied, the "secret event" in the file handle itself is used as the synchronization entity. ( https://devblogs.microsoft.com/oldnewthing/20190719-00/?p=102722 ) We never issue concurrent IOs here so the one in the file handle should be OK.

This is my understanding as well. But here the named pipe handle cannot be used to wait, it's never signaled (again?). But "waiting" with a loop of non-blocking `GetOverlappedResult` (which is basically the same as checking the lower DWORD of `OVERLAPPED.Internal` for an `NTSTATUS` code) clearly shows that the operation is still incomplete. This also happens when the `WaitForThreadpoolIoCallbacks` call is moved before or just after `CancelIoEx`.

**Comment by BillyONeal** [comment]
> To my knowledge this isn't true. The docs state:
> 
> > When fCancelPendingCallbacks is set to TRUE, only queued callbacks are canceled. Pending I/O requests are not canceled. Therefore, the caller should call GetOverlappedResult for the OVERLAPPED structure to check whether the I/O operation has completed before freeing the structure.

I see, then maybe the right fix is to pass false rather than true there?

>But here the named pipe handle cannot be used to wait, it's never signaled (again?).

Yes, because we passed `FILE_SKIP_SET_EVENT_ON_HANDLE`. We are not ever waiting on these events, we are using completion ports (via the thread pool) instead of these blocking primitives.

**Comment by StephanTLavavej** [comment]
The [gh1619-repro branch](https://github.com/gix/STL/tree/gh1619-repro) indeed repros for me, thanks. (I observe `The API "CancelIoEx" failed unexpectedly; last error 0x00000490`.) Calling `WaitForThreadpoolWaitCallbacks(wait, FALSE);` instead of `TRUE` doesn't fix it. The event does fix it.

It's interesting that `enum_files_using_git()` doesn't actually do anything with the `result`; it seems that merely beginning and completing the `subprocess_executive` is enough to cause the repro. (It's also interesting that repro seems to happen quite readily when run in the `tools\parallelize` directory, where it processes only one file.) Changing the command to `git status` appears to make the repro vanish, so perhaps it's related to processing a large amount of returned input?

I think I'm satisfied with this investigation. We have a repro, we have a change that fixes it, the change doesn't appear to be harmful in any way, and although we can't really explain why it works, the documentation is overall very vague (as Billy noted) so this isn't too surprising. We know of no other solutions, so I think we should merge the fix and revise it later if we learn more. (And I ultimately suspect that this is responsible for occasional infrastructure hangs, so there is a real productivity improvement here.)

**Review by StephanTLavavej — APPROVED** [review]

**Comment by gix** [comment]
> The [gh1619-repro branch](https://github.com/gix/STL/tree/gh1619-repro) indeed repros for me, thanks. (I observe `The API "CancelIoEx" failed unexpectedly; last error 0x00000490`.) Calling `WaitForThreadpoolWaitCallbacks(wait, FALSE);` instead of `TRUE` doesn't fix it. The event does fix it.

I still believe that it's not fully correct (why it already works with just an event I don't know). Either:

1. Remove `FILE_SKIP_SET_EVENT_ON_HANDLE` (which I initially missed) and wait after cancelling with `GetOverlappedResult`.
2. Keep `FILE_SKIP_SET_EVENT_ON_HANDLE` but instead use event and also wait with `GetOverlappedResult` (this one now seems unnecessary since we don't have multiple IO operations on the same handle).

I don't think just using `WaitForThreadpoolWaitCallbacks(wait, FALSE);` is enough. In my tests it seems to work but the docs don't support it.

**Comment by StephanTLavavej** [comment]
I've mirrored this to the MSVC-internal repo for merging. If you can improve the fix with `GetOverlappedResult` that would be great as a followup PR.

**Comment by StephanTLavavej** [comment]
Thanks for improving this tool, and congratulations on your first microsoft/STL commit! :tada: :gear: :smile_cat:
