### PR TITLE
Fix make_shared with throwing destructors

### LINKED ISSUE #1733: <memory>: error C2694 when calling make_shared on class with throwing destructor
```
C:\Temp>type meow.cpp
```
```cpp
#include <memory>
using namespace std;

struct A {
  A() {}
  ~A() noexcept(false) {}
};

int main() { auto a = make_shared<A>(); }
```
```
C:\Temp>cl /EHsc /nologo /W4 meow.cpp
meow.cpp
D:\GitHub\STL\out\build\x86\out\inc\memory(2015): error C2694: 'std::_Ref_count_obj2<_Ty>::~_Ref_count_obj2(void)': overriding virtual function has less restrictive exception specification than base class virtual member function 'std::_Ref_count_base::~_Ref_count_base(void) noexcept'
        with
        [
            _Ty=A
        ]
D:\GitHub\STL\out\build\x86\out\inc\memory(2015): note: see declaration of 'std::_Ref_count_obj2<_Ty>::~_Ref_count_obj2'
        with
        [
            _Ty=A
        ]
D:\GitHub\STL\out\build\x86\out\inc\memory(1072): note: see declaration of 'std::_Ref_count_base::~_Ref_count_base'
D:\GitHub\STL\out\build\x86\out\inc\memory(2730): note: see reference to class template instantiation 'std::_Ref_count_obj2<_Ty>' being compiled
        with
        [
            _Ty=A
        ]
meow.cpp(9): note: see reference to function template instantiation 'std::shared_ptr<A> std::make_shared<A,>(void)' being compiled
```

Originally reported as DevCom-1306429 and Microsoft-internal VSO-1265102 / AB#1265102 .

### PR DESCRIPTION
**Pull request by StephanTLavavej**
Fixes #1733.

The STL is allowed to assume that user destructors don't emit exceptions (WG21-N4878 [tab:cpp17.destructible]), but user destructors can be marked `noexcept(false)` as long as they never emit exceptions when interacting with the STL. The bug being fixed here is that 9 out of 10 `shared_ptr` control blocks would fail to compile for `noexcept(false)` destructors. (The only unaffected control block was the simplest, `_Ref_count`, which stores only a pointer.)

We can mark `~_Ref_count_resource()` and `~_Ref_count_resource_alloc()` as `noexcept` and define them as `= default;` thanks to WG21-N4878 [dcl.fct.def.default]/2.2:

> The type `T`<sub>1</sub> of an explicitly defaulted special member function `F` is allowed to differ from the type `T`<sub>2</sub> it would have had if it were implicitly declared, as follows: [...] `T`<sub>1</sub> and `T`<sub>2</sub> may have differing exception specifications

For the other destructors which were already being provided by the library, the fix is to mark them as `noexcept`. I'm additionally marking them as `virtual override` for consistency, and copying the `// TRANSITION, should be non-virtual` comment from the base class.

Because this interacts with virtual member functions, we need to think carefully about ABI. I manually verified that the vtable layout isn't changing;

```
C:\Temp>type meow.cpp
```
```cpp
#include <memory>
using namespace std;

int main() {
    shared_ptr<int> sp{new int, default_delete<int>{}};
}
```
```
C:\Temp>cl /EHsc /nologo /W4 /std:c++latest /c /d1reportSingleClassLayout_Ref_count_resource meow.cpp
meow.cpp
```

Before:
===
```
class std::_Ref_count_resource<int *,struct std::default_delete<int> >  size(16):
        +---
 0      | +--- (base class std::_Ref_count_base)
 0      | | {vfptr}
 4      | | _Uses
 8      | | _Weaks
        | +---
12      | ?$_Compressed_pair@U?$default_delete@H@std@@PAH$00 _Mypair
        +---

std::_Ref_count_resource<int *,struct std::default_delete<int> >::$vftable@:
        | &?$_Ref_count_resource@PAHU?$default_delete@H@std@@_meta
        |  0
 0      | &std::_Ref_count_resource<int *,struct std::default_delete<int> >::_Destroy
 1      | &std::_Ref_count_resource<int *,struct std::default_delete<int> >::_Delete_this
 2      | &std::_Ref_count_resource<int *,struct std::default_delete<int> >::{dtor}
 3      | &std::_Ref_count_resource<int *,struct std::default_delete<int> >::_Get_deleter

std::_Ref_count_resource<int *,struct std::default_delete<int> >::_Get_deleter this adjustor: 0
std::_Ref_count_resource<int *,struct std::default_delete<int> >::_Destroy this adjustor: 0
std::_Ref_count_resource<int *,struct std::default_delete<int> >::_Delete_this this adjustor: 0
std::_Ref_count_resource<int *,struct std::default_delete<int> >::{dtor} this adjustor: 0
std::_Ref_count_resource<int *,struct std::default_delete<int> >::__delDtor this adjustor: 0
std::_Ref_count_resource<int *,struct std::default_delete<int> >::__vecDelDtor this adjustor: 0
```

After:
===
```
class std::_Ref_count_resource<int *,struct std::default_delete<int> >  size(16):
        +---
 0      | +--- (base class std::_Ref_count_base)
 0      | | {vfptr}
 4      | | _Uses
 8      | | _Weaks
        | +---
12      | ?$_Compressed_pair@U?$default_delete@H@std@@PAH$00 _Mypair
        +---

std::_Ref_count_resource<int *,struct std::default_delete<int> >::$vftable@:
        | &?$_Ref_count_resource@PAHU?$default_delete@H@std@@_meta
        |  0
 0      | &std::_Ref_count_resource<int *,struct std::default_delete<int> >::_Destroy
 1      | &std::_Ref_count_resource<int *,struct std::default_delete<int> >::_Delete_this
 2      | &std::_Ref_count_resource<int *,struct std::default_delete<int> >::{dtor}
 3      | &std::_Ref_count_resource<int *,struct std::default_delete<int> >::_Get_deleter

std::_Ref_count_resource<int *,struct std::default_delete<int> >::{dtor} this adjustor: 0
std::_Ref_count_resource<int *,struct std::default_delete<int> >::_Get_deleter this adjustor: 0
std::_Ref_count_resource<int *,struct std::default_delete<int> >::_Destroy this adjustor: 0
std::_Ref_count_resource<int *,struct std::default_delete<int> >::_Delete_this this adjustor: 0
std::_Ref_count_resource<int *,struct std::default_delete<int> >::__delDtor this adjustor: 0
std::_Ref_count_resource<int *,struct std::default_delete<int> >::__vecDelDtor this adjustor: 0
```

The virtual function table order is unchanged, and it follows the base class order (which, after thinking about it for a moment, is how virtual functions must work):

https://github.com/microsoft/STL/blob/c5ee3b32bd3ee219b6d93d72f24429ae6e240ced/stl/inc/memory#L1046-L1121

The only difference is that `/d1reportSingleClassLayout` is reporting "`this` adjustors" in derived order, and I'm inserting the definitions of `~_Ref_count_resource()` and `~_Ref_count_resource_alloc()` near the top. As far as I know, this difference is purely cosmetic (it doesn't reflect any physical ordering).

The test contains comments indicating which control blocks are being tested; mostly for clarity, partially so that any future searches for control block names will find these tests.

Along the way, I reported (internally, because I was a lazy kitty) and worked around:

* VSO-1292292 "EDG mishandles trivial throwing destructors"
* VSO-1292293 "EDG incorrectly rejects defaulted noexcept dtor when a data member has a throwing dtor"

### CODE REVIEW

File: stl/inc/memory [hunk 1]
```diff
@@ -1145,6 +1145,12 @@ public:
     _Ref_count_resource(_Resource _Px, _Dx _Dt)
         : _Ref_count_base(), _Mypair(_One_then_variadic_args_t{}, _STD move(_Dt), _Px) {}
 
+#ifdef __EDG__ // TRANSITION, VSO-1292293
+    virtual ~_Ref_count_resource() noexcept override {} // TRANSITION, should be non-virtual
```
Comment (miscco) [inline stl/inc/memory:1149]: I find the `virtual override` to be a code smell. A function that is marked as override *must* be virtual. So this is only adding noise

**Review by miscco — APPROVED** [review]
As said i do not like `virtual override` together but do not really care too much either

File: stl/inc/memory (hunk 1 above)
Comment (StephanTLavavej) [reply stl/inc/memory:1149]: That’s a reasonable point, and it’s tracked by #303. In this PR, I’m remaining consistent with the current convention; if and when we decide to change it, we should do so globally.

File: tests/std/tests/P0674R1_make_shared_for_arrays/test.cpp [hunk 2]
```diff
@@ -623,6 +623,67 @@ void test_allocate_shared_array_unknown_bounds() {
...
+};
+static_assert(!is_nothrow_destructible_v<NontrivialThrowingDtor>);
+static_assert(!is_trivially_destructible_v<NontrivialThrowingDtor>);
+
+struct TrivialThrowingDtor {
+    ~TrivialThrowingDtor() noexcept(false) = default;
+};
+
+#ifndef __EDG__ // TRANSITION, VSO-1292292
+static_assert(!is_nothrow_destructible_v<TrivialThrowingDtor>);
```
Comment (CaseyCarter) [inline tests/std/tests/P0674R1_make_shared_for_arrays/test.cpp:638]: If the bug is that EDG thinks this type is nothrow destructible, I suggest adding an `#else` branch asserting the bug (with an appropriate comment) so we can't fail to notice when the bug is fixed.

**Review by CaseyCarter — APPROVED** [review]

File: tests/std/tests/P0674R1_make_shared_for_arrays/test.cpp (hunk 2 above)
Comment (StephanTLavavej) [reply tests/std/tests/P0674R1_make_shared_for_arrays/test.cpp:638]: I can do that - however, it will `static_assert` when EDG is updated internally, in advance of that shipping in a public Preview. Not only will a non-STL dev encounter the `static_assert`, but we wouldn't be able to remove this workaround atomically. Therefore, I am inclined to leave this as-is, but I can make the change if you really want it.

Comment (CaseyCarter) [reply tests/std/tests/P0674R1_make_shared_for_arrays/test.cpp:638]: > I can do that - however, it will `static_assert` when EDG is updated internally, in advance of that shipping in a public Preview. Not only will a non-STL dev encounter the `static_assert`, but we wouldn't be able to remove this workaround atomically. Therefore, I am inclined to leave this as-is, but I can make the change if you really want it.

You've talked me out of it.

**Review by MahmoudGSaleh — APPROVED** [review]

**Comment by MikeGitb** [comment]
Is there a (easy to suppress) way to warn about it? If I go all the way to mark a destructor as `noexcept(false)` I'm pretty sure I actually expect it to fail at some point or another and a warning, that this configuration is not supported by the STL would be nice.

**Comment by StephanTLavavej** [comment]
@MikeGitb 
> Is there a (easy to suppress) way to warn about it?

That's a reasonable question - the answer is "unfortunately no". The STL doesn't have great mechanisms to emit such warnings, or to allow users to suppress them. The main mechanism available to us is `[[deprecated]]`, which we reserve for only ISO and Microsoft deprecations, and the suppression system involves verbose macros (where the verbosity is somewhat of an advantage). Warning about conformant, non-deprecated code is a big step, and we need to be cautious to avoid emitting annoying false positives. `[[nodiscard]]` is an example where we do emit warnings far beyond what the Standard suggests, but we are extremely careful to not emit false positives. (We have `#pragma message` for file-level problems, like including C++20 headers in C++14 mode, but those don't activate /WX.) When we've previously warned about conformant code that wasn't inherently flawed, it really annoyed users (that was warning about using raw pointers as output iterators).

In this case, although you would like to be warned, other users might not, and they might not enjoy having to suppress a new warning when upgrading. The last problem I can think of is there's no good way to suppress such a warning in a *targeted* manner - to say "okay, I know that `~Meow() noexcept(false)` shouldn't emit exceptions at runtime, mark it as okay but continue to warn for other types". This leads me to think that we shouldn't attempt to implement such a warning.
