### PR TITLE
Use `steady_clock` in timed mutex test

### LINKED ISSUE #1472: VSO_0226079_mutex is sporadically failing
We encountered a sporadic test failure:

```
Assertion failed: time_execution([this] { unique_lock<Mutex> ul(mtx, 50ms); assert(!ul.owns_lock()); }) >= 50ms,
file C:\a\1\s\tests\std\tests\VSO_0226079_mutex\test.cpp, line 327
```

https://github.com/microsoft/STL/blob/ea156e730cf3370d0551a0532669b7de90c78915/tests/std/tests/VSO_0226079_mutex/test.cpp#L324-L327

It appears that `system_clock` behavior may be making this test unreliable.

### PR DESCRIPTION
**Pull request by AlexGuteniev**
_Can I tell you only one solution to this problem? Ditch the second clock!_

Fixes #1472

With the series of PRs ended with #4755 we should be fine with this change.

### CODE REVIEW

**Comment by StephanTLavavej** [comment]
Re-labeling as "test" because this isn't a product code bug.

File: tests/std/tests/VSO_0226079_mutex/test.cpp [hunk 1]
```diff
@@ -148,12 +148,9 @@ class other_mutex_thread {
 
 template <typename Func>
 nanoseconds time_execution(Func&& f) {
-    // system_clock currently powers mutex waits, so we're using system_clock
-    // rather than high_resolution_clock here for consistency. This should be
-    // fixed with VSO-133414, VSO-166543, VSO-189735.
```
Comment (StephanTLavavej) [inline tests/std/tests/VSO_0226079_mutex/test.cpp:153]: No change requested: For the record, these were

* VSO-133414 `<condition_variable>`: `wait_until()` is implemented with relative time
* VSO-166543 `<condition_variable>`: `wait_until` and `sleep_until` functions don't behave correctly for user-defined clocks
* VSO-189735 `<thread>`: `std::this_thread::sleep_for` hangs when system time is moved backwards

which indeed should all be fixed now.

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Awesome - thanks for digging this up and fixing it! :heart_eyes_cat:

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
:stopwatch: :lock: :hammer_and_wrench:
===
