### PR TITLE
`<ranges>`: Fix truncation warnings and improve overflow check for `repeat_view`

### LINKED ISSUE #4251: `<ranges>`: `repeat_view<T, unsigned int>` emits truncation warnings
Found by `std/ranges/range.factories/range.repeat.view/iterator/minus.pass.cpp` in the upcoming libcxx update.

```
D:\GitHub\STL\out\x64>type meow.cpp
```
```cpp
#include <cassert>
#include <iostream>
#include <ranges>
using namespace std;

int main() {
    auto rv    = views::repeat(1729, 20u);
    auto first = rv.begin();
    auto last  = rv.end();
    assert(last - first == 20);
    first += 2;
    last -= 3;
    assert(last - first == 15);
}
```
```
D:\GitHub\STL\out\x64>cl /EHsc /nologo /W4 /std:c++latest /MTd /Od meow.cpp && meow
meow.cpp
D:\GitHub\STL\out\x64\out\inc\ranges(1574): warning C4244: '-=': conversion from '__int64' to 'unsigned int', possible loss of data
D:\GitHub\STL\out\x64\out\inc\ranges(1574): note: the template instantiation context (the oldest one first) is
D:\GitHub\STL\out\x64\out\inc\ranges(1484): note: while compiling class 'std::ranges::repeat_view<_Ty,unsigned int>::_Iterator'
        with
        [
            _Ty=int
        ]
D:\GitHub\STL\out\x64\out\inc\ranges(1560): note: while compiling class template member function 'std::ranges::repeat_view<_Ty,unsigned int>::_Iterator &std::ranges::repeat_view<_Ty,unsigned int>::_Iterator::operator -=(__int64) noexcept'
        with
        [
            _Ty=int
        ]
meow.cpp(12): note: see the first reference to 'std::ranges::repeat_view<_Ty,unsigned int>::_Iterator::operator -=' in 'main'
        with
        [
            _Ty=int
        ]
D:\GitHub\STL\out\x64\out\inc\ranges(1557): warning C4244: '+=': conversion from '__int64' to 'unsigned int', possible loss of data
D:\GitHub\STL\out\x64\out\inc\ranges(1557): note: the template instantiation context (the oldest one first) is
D:\GitHub\STL\out\x64\out\inc\ranges(1543): note: while compiling class template member function 'std::ranges::repeat_view<_Ty,unsigned int>::_Iterator &std::ranges::repeat_view<_Ty,unsigned int>::_Iterator::operator +=(__int64) noexcept'
        with
        [
            _Ty=int
        ]
meow.cpp(11): note: see the first reference to 'std::ranges::repeat_view<_Ty,unsigned int>::_Iterator::operator +=' in 'main'
        with
        [
            _Ty=int
        ]
```

At first glance, it doesn't seem that the user code is provoking these warnings, instead it's how the STL widens and narrows types.

In our implementation, I see that we have:

https://github.com/microsoft/STL/blob/cf1313c39169dc376761eddee23c5e408e01aaa9/stl/inc/ranges#L1490

and then we're performing debug checks with `static_cast<_Index_type>(_Off)` and finally saying `_Current += _Off;`:

https://github.com/microsoft/STL/blob/cf1313c39169dc376761eddee23c5e408e01aaa9/stl/inc/ranges#L1543-L1559

My vague guess is that after the debug checks, we should be able to use `static_cast<_Index_type>(_Off)` to avoid the warning. However, I'm not sure if we should be checking that `difference_type _Off` can be losslessly `static_cast<_Index_type>(_Off)` in the first place, which is why I'm filing this issue instead of just changing the implementation.

### PR DESCRIPTION
**Pull request by frederick-vs-ja**
Fixes #4251.

### CODE REVIEW

File: tests/std/tests/P2474R2_views_repeat_death/test.cpp [hunk 1]
```diff
@@ -81,6 +81,51 @@ void test_iter_add_neg_overflow() {
...
 }
 
+template <class I>
+using iota_diff_t = ranges::range_difference_t<ranges::iota_view<I>>;
+
+template <class U>
+constexpr auto positive_huge_diff = iota_diff_t<U>{iota_diff_t<U>{static_cast<U>(-1)} + 1};
+
+template <class U>
+constexpr auto negative_huge_diff = iota_diff_t<U>{-iota_diff_t<U>{static_cast<U>(-1)} - 1};
```
Comment (StephanTLavavej) [inline tests/std/tests/P2474R2_views_repeat_death/test.cpp:91]: Style nitpick: These should use direct-init of `Type var{init}` instead of `auto var = Type{init}`, where `auto` simply obscures what's happening.

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Thanks for fixing this libcxx failure! I pushed a conflict-free merge with `main` followed by a couple of style nitpicks and correcting a duplicated test line.

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
I've pushed a merge with `main` to resolve a trivial adjacent-edit conflict in `tests/libcxx/expected_results.txt`.

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Thanks for *repeatedly* fixing these libcxx failures! :repeat: :joy_cat: :tada:
