### PR TITLE
`<numeric>`: switch `transform_reduce` from direct list initialization to copy non-list initialization

### LINKED ISSUE #4129: `<numeric>`: Parallel `transform_reduce` incorrectly uses list-initialization
# Describe the bug
The following program doesn't compile with MSVC STL due to narrowing conversion in list-initialization.

(originally discovered by @Mq-b in https://github.com/Mq-b/Loser-HomeWork/commit/099c66aea5dd371580e1e4116341f375bec78b5d)

```C++
#include <execution>
#include <numeric>
#include <string>
#include <vector>

int main()
{
    std::vector<std::string>strVec{"Only", "for", "testing", "purpose"};
    std::size_t res = std::transform_reduce(
        std::execution::par,
        strVec.begin(), strVec.end(),
        0,
        [](std::size_t a, std::size_t b) {return a + b; },
        [](std::string s) {return s.size(); }
    ); // the value of res is 21
}
```

https://github.com/microsoft/STL/blob/f392449fb72d1a387ac5025d508e8442914477f9/stl/inc/execution#L4235

Per [[transform.reduce]](https://eel.is/c++draft/transform.reduce), IIUC list-initialization shouldn't be used here. We should only use implicit conversion (in other words, copy-initialization).

There're some other parallel numeric algorithms direct-initializing `_Ty` variables from the results of the binary operations. Perhaps they are also buggy.
(Despite being contrived, it's possible to make `T(bin_op(l, r))` ill-formed while `T t = bin_op(l, r);` being well-formed.)

# Command-line test case
[Godbolt link](https://godbolt.org/z/o495ax43o)

### PR DESCRIPTION
**Pull request by yqZhang4480**
Fixes #4129.

### CODE REVIEW

File: stl/inc/execution [hunk 1]
```diff
@@ -4235,7 +4235,7 @@ struct _Static_partitioned_transform_reduce2 { // transformed reduction task sch
             auto& _Transform_op = _This->_Transform_op;
             auto _Chunk         = _This->_Basis._Get_chunk(_Key);
             auto _Next          = _Chunk._First;
-            _Ty _Val{_Reduce_op(_Transform_op(*_Chunk._First), _Transform_op(*++_Next))};
+            _Ty _Val = _Reduce_op(_Transform_op(*_Chunk._First), _Transform_op(*++_Next));
```
Comment (frederick-vs-ja) [inline stl/inc/execution:4238]: `=` needs to be aligned to make clang-format happy.
```suggestion
            _Ty _Val            = _Reduce_op(_Transform_op(*_Chunk._First), _Transform_op(*++_Next));
```

Comment (yqZhang4480) [reply stl/inc/execution:4239]: Thank you for pointing it out, I used a different way to make both me and clang-format happy :-P

**Review by frederick-vs-ja — COMMENTED** [review]
LGTM. However, it seems preferred to add a test case to the related test file ([`tests/std/tests/P0024R2_parallel_algorithms_transform_reduce/test.cpp`](https://github.com/microsoft/STL/blob/main/tests/std/tests/P0024R2_parallel_algorithms_transform_reduce/test.cpp)).

File: stl/inc/execution (hunk 1 above)
Comment (frederick-vs-ja) [reply stl/inc/execution:4239]: Oh, I forgot to suggest that [GitHub's close/fix/resolve syntax](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) should be used so that the issue can be automatically closed by merging this PR.

**Comment by yqZhang4480** [comment]
@microsoft-github-policy-service agree

**Comment by yqZhang4480** [comment]
Sorry for the inconvenience, but I'm encountering some troubles with running clang-format. I plan to dedicate some time to investigate these issues. If you'd like, please run clang-format on your end, thanks.

**Comment by fsb4000** [comment]
```
D:\build\out\inc\numeric(217): error C2220: the following warning is treated as an error
D:\build\out\inc\numeric(217): warning C4267: '=': conversion from 'size_t' to '_Ty', possible loss of data
        with
        [
            _Ty=int
        ]
D:\build\out\inc\numeric(217): note: the template instantiation context (the oldest one first) is
D:\a\_work\1\s\tests\std\tests\P0024R2_parallel_algorithms_transform_reduce\test.cpp(155): note: see reference to function template instantiation '_Ty std::transform_reduce<unsigned __int64*,int,std::plus<size_t>,test_case_narrowing_conversion::<lambda_1>>(const _InIt,const _InIt,_Ty,_BinOp,_UnaryOp)' being compiled
        with
        [
            _Ty=int,
            _InIt=size_t *,
            _BinOp=std::plus<size_t>,
            _UnaryOp=test_case_narrowing_conversion::<lambda_1>
        ]
D:\build\out\inc\numeric(197): warning C4267: '=': conversion from 'size_t' to '_Ty', possible loss of data
        with
        [
            _Ty=int
        ]
D:\build\out\inc\numeric(197): note: the template instantiation context (the oldest one first) is
D:\a\_work\1\s\tests\std\tests\P0024R2_parallel_algorithms_transform_reduce\test.cpp(163): note: see reference to function template instantiation '_Ty std::transform_reduce<unsigned __int64*,size_t*,int,std::plus<size_t>,std::plus<size_t>>(_InIt1,_InIt1,_InIt2,_Ty,_BinOp1,_BinOp2)' being compiled
        with
        [
            _Ty=int,
            _InIt1=size_t *,
            _InIt2=size_t *,
            _BinOp1=std::plus<size_t>,
            _BinOp2=std::plus<size_t>
        ]
D:\build\out\inc\execution(4008): warning C4267: '=': conversion from 'size_t' to '_Ty', possible loss of data
        with
        [
            _Ty=int
        ]
D:\build\out\inc\execution(4008): note: the template instantiation context (the oldest one first) is
D:\a\_work\1\s\tests\std\tests\P0024R2_parallel_algorithms_transform_reduce\test.cpp(157): note: see reference to function template instantiation '_Ty std::transform_reduce<const std::execution::parallel_policy&,unsigned __int64*,int,std::plus<size_t>,test_case_narrowing_conversion::<lambda_1>,0>(_ExPo,const _FwdIt,const _FwdIt,_Ty,_BinOp,_UnaryOp) noexcept' being compiled
        with
        [
            _Ty=int,
            _ExPo=const std::execution::parallel_policy &,
            _FwdIt=size_t *,
            _BinOp=std::plus<size_t>,
            _UnaryOp=test_case_narrowing_conversion::<lambda_1>
        ]
```

File: tests/std/tests/P0024R2_parallel_algorithms_transform_reduce/test.cpp [hunk 2]
```diff
@@ -1,7 +1,9 @@
 // Copyright (c) Microsoft Corporation.
 // SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
 
-#pragma warning(disable : 4242 4244 4365) // test_case_incorrect_special_case_reasoning tests narrowing on purpose
+// test_case_incorrect_special_case_reasoning & test_case_narrowing_conversion tests narrowing on purpose
+#pragma warning(disable : 4242 4244 4365)
```
Comment (frederick-vs-ja) [inline tests/std/tests/P0024R2_parallel_algorithms_transform_reduce/test.cpp:5]: Now warning [C4267](https://learn.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-3-c4267?view=msvc-170) should also be suppressed.
```suggestion
#pragma warning(disable : 4242 4244 4267 4365)
```

File: stl/inc/execution [hunk 3]
```diff
@@ -4235,7 +4235,8 @@ struct _Static_partitioned_transform_reduce2 { // transformed reduction task sch
             auto& _Transform_op = _This->_Transform_op;
             auto _Chunk         = _This->_Basis._Get_chunk(_Key);
             auto _Next          = _Chunk._First;
-            _Ty _Val{_Reduce_op(_Transform_op(*_Chunk._First), _Transform_op(*++_Next))};
+
+            _Ty _Val = _Reduce_op(_Transform_op(*_Chunk._First), _Transform_op(*++_Next));
```
Comment (strega-nil-ms) [inline stl/inc/execution:4239]: Note that this is (in my opinion) correctly using copy-initialization – the return type of `binary_op` (`_Reduce_op` here) must be convertible to `T` (`_Ty`).

**Review by strega-nil-ms — APPROVED** [review]

File: tests/std/tests/P0024R2_parallel_algorithms_transform_reduce/test.cpp [hunk 4]
```diff
@@ -1,7 +1,9 @@
 // Copyright (c) Microsoft Corporation.
 // SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
 
-#pragma warning(disable : 4242 4244 4365) // test_case_incorrect_special_case_reasoning tests narrowing on purpose
+// test_case_incorrect_special_case_reasoning & test_case_narrowing_conversion tests narrowing on purpose
```
Comment (StephanTLavavej) [inline tests/std/tests/P0024R2_parallel_algorithms_transform_reduce/test.cpp:4]: Comment nitpicks: This should now say "test" to be grammatical. Additionally, we avoid abbreviating "and" to "&" in comments, to avoid confusion with its various meanings in C++.

File: tests/std/tests/P0024R2_parallel_algorithms_transform_reduce/test.cpp [hunk 5]
```diff
@@ -144,6 +146,25 @@ void test_case_incorrect_special_case_reasoning() {
     assert(transform_reduce(begin(c), end(c), d, 0, multiplies<>{}, plus<unsigned char>{}) == 0);
 }
 
+void test_case_narrowing_conversion() {
+    size_t a[]         = {1, 2, 3};
+    auto return_itself = [](size_t a) { return a; };
```
Comment (StephanTLavavej) [inline tests/std/tests/P0024R2_parallel_algorithms_transform_reduce/test.cpp:151]: Style nitpick: It's somewhat confusing for `return_itself`'s parameter to have the same name as the `a` array immediately above. Any other name like `x` would be clearer.

File: tests/std/tests/P0024R2_parallel_algorithms_transform_reduce/test.cpp [hunk 6]
```diff
@@ -144,6 +146,25 @@ void test_case_incorrect_special_case_reasoning() {
     assert(transform_reduce(begin(c), end(c), d, 0, multiplies<>{}, plus<unsigned char>{}) == 0);
 }
 
+void test_case_narrowing_conversion() {
+    size_t a[]         = {1, 2, 3};
+    auto return_itself = [](size_t a) { return a; };
+    // Initializing a smaller type (int here) with a larger type (size_t here).
+    // According to [transform.reduce](7.1-7.4),
```
Comment (StephanTLavavej) [inline tests/std/tests/P0024R2_parallel_algorithms_transform_reduce/test.cpp:153]: These Standardese citations are great! While section names like \[transform.reduce\] are stable, paragraph numbers aren't, so we conventionally cite the Working Paper number when mentioning paragraph numbers, so we can track down what was meant if the paragraphs are ever reshuffled. N4971 is the current WP, and these numbers are still valid. Occurs below.

Also, the "*Mandates:* All of \[...\] are convertible to `T`." part is important, so I think we should cite paragraphs 7 and 3 in their entirety, not just their sub-bullets.

Finally, our style is to say \[stable.name\]/paragraph.

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Thanks, this looks great! Apologies for the holiday-induced delay in getting this reviewed. I pushed a commit for minor stylistic issues I noticed.

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
Thanks for fixing this bug and congratulations on your first microsoft/STL commit! :tada: :heart_eyes_cat: :rocket:

This is expected to ship in VS 2022 17.10 Preview 1.
