### PR TITLE
`<variant>`: Make `visit<R>` correctly handle conversions to non-movable types

### LINKED ISSUE #2970: `<variant>`: `visit<R>()` uses wrong `static_assert`
https://github.com/microsoft/STL/blob/b7e0365b5e2f9de738e8fbea42b6cc6880efe531/stl/inc/variant#L1650-L1653

`_Variant_all_visit_results_implicitly_convertible` requires `_Convertible_from_all` which require `is_convertible` which doesn't know about guaranteed elision.

```cpp
#include <variant>

struct A {
  A() = default;
  A(const A&) = delete;
};

struct B {
  A operator()();
};

int main() {
  std::visit<A>(
    [](auto f) { return f(); }, std::variant<B>{});
}
```
https://godbolt.org/z/EcMfM5ffz

### PR DESCRIPTION
**Pull request by frederick-vs-ja**
Fixes #2970.

`std::visit<R>` may need similar strategy to `std::is_invocable_r` to handle conversions to non-movable types.

### CODE REVIEW

**Comment by frederick-vs-ja** [comment]
DevCom-10024578 still matters (the compiler version in which it's fixed isn't release).

**Comment by CaseyCarter** [comment]
> `std::visit<R>` may need similar strategy to `std::is_invocable_r` to handle conversions to non-movable types.

The second I saw the bug report: "Why didn't we fix `visit<R>` when we fixed this same problem in `is_invocable_r`?"

**Review by strega-nil-ms — APPROVED** [review]
LGTM! Thanks!

File: tests/std/tests/P0088R3_variant/test.cpp [hunk 1]
```diff
@@ -6971,6 +6971,27 @@ namespace msvc {
...
+                };
+
+                struct convertible_to_immobile_other {
+                    operator immobile_data() const {
+                        return immobile_data{1138};
+                    }
+                };
+
+                using VarTestConv = std::variant<convertible_to_immobile_one, convertible_to_immobile_other>;
+                // TRANSITION, DevCom-10024578
```
Comment (StephanTLavavej) [inline tests/std/tests/P0088R3_variant/test.cpp:6989]: This was marked as fixed in 17.3 Preview 3, but it appears that the workaround is still necessary. We should report a new bug.

File: tests/std/tests/P0088R3_variant/test.cpp [hunk 2]
```diff
@@ -6971,6 +6971,27 @@ namespace msvc {
                 using R = immobile_data;
                 assert(std::visit<R>(std::identity{}, std::variant<int, short>{13}).x == 13);
                 assert(std::visit<R>(std::identity{}, std::variant<int, short>{short{42}}).x == 42);
+
+                // Verify that conversions to an object is not copied/moved are correctly handeled
```
Comment (StephanTLavavej) [inline tests/std/tests/P0088R3_variant/test.cpp:6975]: Grammar, typo:
```suggestion
                // Verify that conversions to an object that can't be copied/moved are correctly handled
```

**Review by StephanTLavavej — APPROVED** [review]

File: tests/std/tests/P0088R3_variant/test.cpp (hunk 1 above)
Comment (CaseyCarter) [reply tests/std/tests/P0088R3_variant/test.cpp]: I've filed DevCom-10111923 which is identical to DevCom-10024578 except for using `__is_convertible_to(B, A)` instead of `__is_constructible(A, B)`. I'll update the PR.

**Review by CaseyCarter — APPROVED** [review]

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

File: tests/std/tests/P0088R3_variant/test.cpp (hunk 1 above)
Comment (frederick-vs-ja) [reply tests/std/tests/P0088R3_variant/test.cpp]: This should be now DevCom-10112408.

@CaseyCarter has reported DevCom-10111923, but IIUC it doesn't block the original test case. Since `_Invoke_convertible` is using handmade SFINAE instead of that intrinsic.

**Comment by frederick-vs-ja** [comment]
@CaseyCarter thank you for reporting DevCom-10111923!

However, IIUC the bug in MSVC's `__is_convertible_to` doesn't block the original test case. Since `_Invoke_convertible` is using handmade SFINAE instead of that intrinsic.
https://github.com/microsoft/STL/blob/b7e0365b5e2f9de738e8fbea42b6cc6880efe531/stl/inc/type_traits#L1617-L1622

I thought it might be needed to report another bug, which is reported as DevCom-10112408 now. The bug was originally reported by @fsb4000 in a comment of DevCom-10024578, but hasn't been fixed in 17.3 Preview3.

@StephanTLavavej perhaps we should change the bug number (again). I'm sorry for not considering it before.

**Comment by frederick-vs-ja** [comment]
Again, I'm sorry for changing this so late. But it may be misleading if one day `__is_convertible_to` (it might be my fault mentioning it in the issue) gets fixed but the actual implicit conversion doesn't.

**Comment by StephanTLavavej** [comment]
Thanks for reporting the new bug and updating the citation - I agree that this is the correct thing to do, although it is slightly logistically annoying for me :joy_cat:

I just merged the original bug number into the MSVC-internal repo before I saw your comment, so I'll merge the updated PR here, and then mirror the comment update as a followup MSVC-PR.
