### PR TITLE
`<filesystem>`: `__std_fs_get_stats` should work on FAT32

### LINKED ISSUE #233: <filesystem>: `directory_entry` does not work for paths on FAT32 filesystems
From #232, we had this sample code:

```
// compile with: cl /std:c++17 /permissive- /EHsc /Od /Zi symlink.cpp
// run: .\symlink does_not_exist
//
#include <filesystem>
#include <iostream>
namespace fs = std::filesystem;

int main(int argc, const char* argv[])
{
  if (argc < 2)
  {
    std::cerr << "Missing file path argument\n";
    return -1;
  }
  fs::path dst(argv[1]);

  std::error_code err1;
  fs::directory_entry src(dst, err1);
  std::cout << "directory_entry(" << dst << ") = " << err1 << " " << err1.message() << "\n";

  std::error_code err2;
  src.refresh(err2);
  std::cout << "refresh(" << dst << ") = " << err2 << " " << err2.message() << "\n";

  return 0;
}
```

Running this on a FAT32 file system (e.g. on a USB key but I tested with just a RAMDISK formatted to FAT32) gives the following result. (`src` is a directory on the G: drive demonstrated here)
```
G:\> /path/to/symlink.exe src
directory_entry("src") = system:0 The operation completed successfully.
refresh("src") = system:87 The parameter is incorrect.
```

I tried to workaround this by calling `std::directory_entry::status( std::error_code& ec )` and `std::directory_entry::symlink_status( std::error_code& ec )` as well. But they both fail, giving no way to confirm if a path on a FAT32 filesystem is indeed a directory or not.

I tested this myself on Windows 7, but my colleague who had first encountered the problem narrowed down here I believe was on Windows 10.

### PR DESCRIPTION
**Pull request by fsb4000**
Fixes #233 

изображение

изображение

### CODE REVIEW

File: stl/src/filesystem.cpp [hunk 1]
```diff
@@ -907,7 +907,14 @@ struct alignas(long long) _Aligned_file_attrs {
     if (_Bitmask_includes(_Flags, _Attribute_tag_info_data)) {
         FILE_ATTRIBUTE_TAG_INFO _Info;
         if (!GetFileInformationByHandleEx(_Handle._Get(), FileAttributeTagInfo, &_Info, sizeof(_Info))) {
-            return __std_win_error{GetLastError()};
+            const DWORD _Error = GetLastError();
+            if (_Error == ERROR_INVALID_PARAMETER) {
```
Comment (AlexGuteniev) [inline stl/src/filesystem.cpp:911]: I don't like checking against `ERROR_INVALID_PARAMETER`.

Can we avoid calling this for non-reparse-points (by checking attributes obtained with other parametet)?

Comment (fsb4000) [reply stl/src/filesystem.cpp:911]: `GetFileInformationByHandleEx` with `FileBasicInfo`  returns attribute `FILE_ATTRIBUTE_REPARSE_POINT`

https://docs.microsoft.com/en-us/windows/win32/fileio/file-attribute-constants

Comment (fsb4000) [reply stl/src/filesystem.cpp:911]: llvm libc++ works in that way: https://github.com/llvm/llvm-project/blob/e356027016c6365b3d8924f54c33e2c63d931492/libcxx/src/filesystem/posix_compat.h#L172-L194

Comment (fsb4000) [reply stl/src/filesystem.cpp:911]: I don't know. I'm fine with checking against `ERROR_INVALID_PARAMETER`. I will wait for more opinions...

File: stl/src/filesystem.cpp [hunk 2]
```diff
@@ -907,7 +907,14 @@ struct alignas(long long) _Aligned_file_attrs {
     if (_Bitmask_includes(_Flags, _Attribute_tag_info_data)) {
         FILE_ATTRIBUTE_TAG_INFO _Info;
         if (!GetFileInformationByHandleEx(_Handle._Get(), FileAttributeTagInfo, &_Info, sizeof(_Info))) {
-            return __std_win_error{GetLastError()};
+            const DWORD _Error = GetLastError();
+            if (_Error == ERROR_INVALID_PARAMETER) {
+                // Calling GetFileInformationByHandleEx with FileAttributeTagInfo fails on FAT file system with
+                // ERROR_INVALID_PARAMETER. Clear _Info.ReparseTag to indicate no symlinks are possible.
+                _Info.ReparseTag = 0;
```
Comment (StephanTLavavej) [inline stl/src/filesystem.cpp:914]: `FILE_ATTRIBUTE_TAG_INFO _Info;` was garbage-initialized, `FileAttributes` isn't cleared, and then we assign it to `_Stats->_Attributes`. Does `GetFileInformationByHandleEx` fill it with a reasonable value, even in this `ERROR_INVALID_PARAMETER` case?

Comment (fsb4000) [reply stl/src/filesystem.cpp:914]: No :(

**Review by AlexGuteniev — APPROVED** [review]

File: stl/src/filesystem.cpp (hunk 1 above)
Comment (AlexGuteniev) [reply stl/src/filesystem.cpp]: Thanks for fixing this.

I think relying on `ERROR_INVALID_PARAMETER` was not safe as it is observed behavior of specific filesystem driver; this could be different on another filesystem, like exFAT or ReFS, or even with an update of the existing driver (like in Win12).

I understand the performance consideration for saving a system call, but correctness goes first.

File: stl/src/filesystem.cpp [hunk 3]
```diff
@@ -888,11 +888,10 @@ struct alignas(long long) _Aligned_file_attrs {
...
 
-    constexpr auto _Basic_info_data = __std_fs_stats_flags::_Attributes | __std_fs_stats_flags::_Last_write_time;
-    constexpr auto _Attribute_tag_info_data = __std_fs_stats_flags::_Attributes | __std_fs_stats_flags::_Reparse_tag;
-    constexpr auto _Standard_info_data      = __std_fs_stats_flags::_File_size | __std_fs_stats_flags::_Link_count;
+    constexpr auto _Basic_info_data    = __std_fs_stats_flags::_Attributes | __std_fs_stats_flags::_Last_write_time;
+    constexpr auto _Standard_info_data = __std_fs_stats_flags::_File_size | __std_fs_stats_flags::_Link_count;
 
-    if (_Flags != _Attribute_tag_info_data && _Bitmask_includes(_Flags, _Basic_info_data)) {
+    if (_Bitmask_includes(_Flags, _Basic_info_data | __std_fs_stats_flags::_Reparse_tag)) {
         // we have data FileBasicInfo can fill in, that FileAttributeTagInfo wouldn't exactly fill in
```
Comment (BillyONeal) [inline stl/src/filesystem.cpp:895]: I think this comment is now a lie

**Comment by fsb4000** [comment]
DevCom-1638272 with the same issue.

**Review by strega-nil-ms — APPROVED** [review]
I have looked this over (with a pen and paper to make sure I understood the function!) and I believe this to be a correct and good change. I also had billy look over my shoulder at it, and he didn't have any major problems.

My one concern was adding an extra function call when checking _only_ for reparse point data, but given that we have multiple calls to `GetFileInformationByHandleEx` anyways, and the call is quite cheap, I'm no longer concerned.

Thanks!

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
Thanks for fixing this most modern filesystem library to work with this most ancient filesystem! :joy_cat: :tada: :rocket:
