### PR TITLE
`<ranges>`: Fix `ranges::equal` for ranges with integer-class `range_difference_t`

### LINKED ISSUE #3550: `<ranges>`: `ranges::equal` does not work for ranges with integer-class `range_difference_t`
Repro:

```c++
#include <algorithm>
#include <ranges>

using namespace std;

void f() {
  auto v = views::iota(0ull, 5ull) | views::stride(2); // range_difference_t<v> == _Unsigned128
  auto w = views::iota(0ull, 5ull) | views::stride(2);
  (void)ranges::equal(v, w);
}
```

Expected: *correct compilation*
Got: *error* (see link below)
Compiler explorer: https://godbolt.org/z/crcbMfY7z
Discovered while implementing #2923

### PR DESCRIPTION
**Pull request by JMazurkiewicz**
Closes #3550.

### CODE REVIEW

File: tests/std/tests/P0896R4_ranges_alg_equal/test.cpp [hunk 1]
```diff
@@ -79,6 +79,11 @@ constexpr void smoke_test() {
         assert(!equal(begin(arr1), unreachable_sentinel, begin(arr2), end(arr2)));
         assert(!equal(begin(arr1), end(arr1), begin(arr2), unreachable_sentinel));
     }
+    {
+        // Validate GH-3550: "<ranges>: ranges::equal does not work for ranges with integer-class range_difference_t"
+        auto v = std::ranges::subrange{std::views::iota(0ull, 10ull)} | std::views::drop(2);
```
Comment (StephanTLavavej) [inline tests/std/tests/P0896R4_ranges_alg_equal/test.cpp:84]: Nitpick: `range_algorithm_support.hpp` provides a top-level namespace alias `ranges` which this test prefers to use instead of `std::ranges`:

https://github.com/microsoft/STL/blob/daa994bfc41c36196c536f2b68388f859d6bd656/tests/std/include/range_algorithm_support.hpp#L21
https://github.com/microsoft/STL/blob/daa994bfc41c36196c536f2b68388f859d6bd656/tests/std/tests/P0896R4_ranges_alg_equal/test.cpp#L15

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I have **massively reworked** this PR by changing 16.7% of its lines :zany_face: :joy_cat:

Thanks for the fix!

**Review by CaseyCarter — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I pushed a commit to work around a notorious `/clr` bug affecting `views::iota`.

**Review by CaseyCarter — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Thanks for finding and fixing this ranges bug! :lady_beetle: :hammer_and_wrench: :smile_cat:
