### PR TITLE
Fix `ranges::is_permutation`'s helper lambdas

### LINKED ISSUE #2888: `<algorithm>`: `ranges::is_permutation`'s helper lambda does not specify return type
https://github.com/microsoft/STL/blob/ef62d3fa0b8e4e2406b9bb74e916e1ca8a1df802/stl/inc/algorithm#L1010-L1013

https://github.com/microsoft/STL/blob/ef62d3fa0b8e4e2406b9bb74e916e1ca8a1df802/stl/inc/algorithm#L1099-L1102

The lambda needs to specify return type eg `-> bool` since _`boolean-testable`_ _only_ requires that the return type of `Pred` can be converted to `bool`.

```cpp
#include <algorithm>

struct Bool {
  operator bool() { return true; };
  Bool() = default;
  Bool(const Bool&) = delete;
};

int main() {
  Bool b;
  int x[] = {42};
  std::ranges::is_permutation(x, x, [&](auto, auto) -> Bool& { return b; });
}
```
https://godbolt.org/z/dPKKeex9o

### PR DESCRIPTION
**Pull request by JMazurkiewicz**
Fixes #2888.

### CODE REVIEW

**Review by strega-nil-ms — APPROVED** [review]
Thanks!

File: tests/std/tests/P0896R4_ranges_alg_is_permutation/test.cpp [hunk 1]
```diff
@@ -134,6 +134,17 @@ struct instantiator {
             assert(ranges::is_permutation(
                 r1, r2, {}, [](int n) { return n + 1; }, [](int n) { return n - 1; }));
         }
+        { // Test GH-2888: `<algorithm>`: `ranges::is_permutation`'s helper lambda does not specify return type
+            struct NonCopyableBool {
+                constexpr operator bool() {
+                    return true;
+                };
```
Comment (CaseyCarter) [inline tests/std/tests/P0896R4_ranges_alg_is_permutation/test.cpp:141]:
```suggestion
                }
```

**Review by CaseyCarter — APPROVED** [review]
All good except for an extraneous semicolon, which I'll cleanup.

File: tests/std/tests/P0896R4_ranges_alg_is_permutation/test.cpp [hunk 2]
```diff
@@ -134,6 +134,17 @@ struct instantiator {
...
         }
+        { // Test GH-2888: `<algorithm>`: `ranges::is_permutation`'s helper lambda does not specify return type
+            struct NonCopyableBool {
+                constexpr operator bool() {
+                    return true;
+                }
+
+                NonCopyableBool()                       = default;
+                NonCopyableBool(const NonCopyableBool&) = delete;
+            } b;
```
Comment (StephanTLavavej) [inline tests/std/tests/P0896R4_ranges_alg_is_permutation/test.cpp:145]: No change requested: We usually avoid defining a struct and a variable together. Separating the definitions consumes an extra line, but makes it clearer that two things are being defined (similar rationale to avoiding `Type obj1, obj2;`).

This stylistic nitpick isn't worth resetting testing, but I wanted to note it for the future.

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
:white_check_mark: No modules impact here (I am double-checking in-flight PRs to make sure we don't miss any needed `export`s).

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
compiler for Thanks :joy_cat: errors! :white_check_mark: these fixing :tada:
