### PR TITLE
Re-enable ASAN string annotations

### LINKED ISSUE #3205: <vector>: x86 ASAN failure with pmr::monotonic_buffer_resource
Might be related to: https://github.com/microsoft/STL/pull/3164
-
Initializing std::vector + std::pmr::monotonic_buffer_resource causes ASAN to throw an exception in x86 mode under certain conditions. 

The following code shows this, but unfortunately I was unable to add ASAN to MSVC in compiler explorer, so instead GCC x86 and x64 were added to show there's no problem there.
https://godbolt.org/z/sM931fbP3
https://godbolt.org/z/vbzEa4cba

The code from the first link for posterity's sake:
```
#include <array>
#include <iostream>
#include <memory_resource>
#include <vector>

int main()
{
    using T = std::pmr::vector<std::uint8_t>;

    std::array<std::uint8_t, 8192> buffer{};
    std::pmr::monotonic_buffer_resource mbr(buffer.data(), buffer.size(), 
        std::pmr::null_memory_resource());
    
    T vec1(128, &mbr);
    T vec2(128, &mbr);

    std::cout << "So far so good\n";

    T vec3(100, &mbr);
    T vec4(128, &mbr); // <-- asan throws exception here

    std::cout << "All good\n";
}
```

Visual Studio 2022 versions:
- v17.4.0, various preview versions (preview 2.1, preview 6)
- v17.5.0

Notable compiler settings / flags
- Debug mode
- x86 (NOT x64)
- C++17 / C++20
- Address sanitizer enabled (/fsanitize=address)

NB: ASAN would only thow an exception in x86 mode + Visual Studio 2022. I was unable to reproduce the issue with Visual Studio 2019, neither x86 nor x64 (I don't have a VS2019 version number at hand, but it was quite recent).

### PR DESCRIPTION
**Pull request by strega-nil-ms**
tested with the bugs with the previous implementation!

Fixes #3205 
internal PR for testing purposes: ~~MSVC-PR-433542~~ ~~MSVC-PR-440101~~ MSVC-PR-440279
Fixes the following internal bugs: VSO-1664238, VSO-1586016, VSO-1543191

### CODE REVIEW

**Comment by CaseyCarter** [comment]
## 🚨 WARNING: Inadvertent LLVM submodule reference revert detected! 🚨

File: stl/inc/xstring [hunk 1]
```diff
@@ -2569,37 +2547,43 @@ private:
             return;
         }
 
-        // We need to check whether we have a misaligned SSO buffer because of the proxy in `_Container_base` (e.g. x86)
+        // When SSO is active, the buffer may not be aligned on an ASan shadow memory boundary;
```
Comment (CaseyCarter) [inline stl/inc/xstring:2550]: Could we say "might not" to avoid the English language's confusion over whether "may not" means "might not" or "must not"?

File: stl/inc/xmemory [hunk 2]
```diff
@@ -776,6 +776,21 @@ _NODISCARD constexpr allocation_result<typename allocator_traits<_Alloc>::pointe
 // The number of user bytes a single byte of ASAN shadow memory can track.
 _INLINE_VAR constexpr size_t _Asan_granularity = 8;
 
+_NODISCARD inline const void* _Get_asan_aligned_first(const void* _First, const void* _Last) noexcept {
+    const auto _First_address     = reinterpret_cast<uintptr_t>(_First);
+    const auto _Last_address       = reinterpret_cast<uintptr_t>(_Last);
```
Comment (CaseyCarter) [inline stl/inc/xmemory:781]: In before Stephan suggests you configure your editor to format-on-save.

File: stl/inc/xmemory [hunk 3]
```diff
@@ -776,6 +776,21 @@ _NODISCARD constexpr allocation_result<typename allocator_traits<_Alloc>::pointe
...
+_NODISCARD inline const void* _Get_asan_aligned_first(const void* _First, const void* _Last) noexcept {
+    const auto _First_address     = reinterpret_cast<uintptr_t>(_First);
+    const auto _Last_address       = reinterpret_cast<uintptr_t>(_Last);
+
+    const auto _Aligned_address = (_First_address + _Asan_granularity - 1) & ~(_Asan_granularity - 1);
+
+    if (_Aligned_address > _Last_address) {
+        return nullptr;
+    } else {
+        // strict provenance requires that we reconstruct `_Aligned_address` via `_First`
```
Comment (CaseyCarter) [inline stl/inc/xmemory:788]: "Strict [pointer] provenance"? Why do we care? We've never supported an implementation with strict pointer provenance, and the pertinent parts of the Standard have been removed. Is this actually an issue for ASAN?

File: stl/inc/xstring (hunk 1 above)
Comment (CaseyCarter) [reply stl/inc/xstring:2550]: Our variable names are all `_Asan_meow`, but this says "ASan". Can we pick a capitalization and use it consistently everywhere?

File: stl/inc/xstring [hunk 4]
```diff
@@ -2569,37 +2547,43 @@ private:
             return;
         }
 
-        // We need to check whether we have a misaligned SSO buffer because of the proxy in `_Container_base` (e.g. x86)
+        // When SSO is active, the buffer may not be aligned on an ASan shadow memory boundary;
         if constexpr (_Memcpy_val_offset % _Asan_granularity != 0) {
-            const uintptr_t _Alignment_offset = reinterpret_cast<uintptr_t>(_Ptr) & (_Asan_granularity - 1);
-            if (_Alignment_offset != 0 && _Capacity == _BUF_SIZE - 1) {
-                return;
+            // The alignment can be incorrect on this platform and for this type
```
Comment (CaseyCarter) [inline stl/inc/xstring:2552]: I don't understand what this comment wants to tell me.

File: stl/inc/xstring [hunk 5]
```diff
@@ -2569,37 +2547,43 @@ private:
...
         if constexpr (_Memcpy_val_offset % _Asan_granularity != 0) {
-            const uintptr_t _Alignment_offset = reinterpret_cast<uintptr_t>(_Ptr) & (_Asan_granularity - 1);
-            if (_Alignment_offset != 0 && _Capacity == _BUF_SIZE - 1) {
-                return;
+            // The alignment can be incorrect on this platform and for this type
+            if (_Capacity == _BUF_SIZE - 1) {
+                // This string is in SSO mode, so we need to check if the buffer happens to be aligned or not
+                const uintptr_t _Buffer_alignment = reinterpret_cast<uintptr_t>(_First) & (_Asan_granularity - 1);
+                if (_Buffer_alignment != 0) {
+                    // NOTE TO REVIEWER: shouldn't this do the `_Aligned_first` thing that's done when in large string mode?
```
Comment (CaseyCarter) [inline stl/inc/xstring:2557]: Maybe the prior intent was to throw our hands in the air, and not try to ASan annotate when the SSO us unaligned?

File: stl/inc/xmemory [hunk 6]
```diff
@@ -776,6 +776,21 @@ _NODISCARD constexpr allocation_result<typename allocator_traits<_Alloc>::pointe
 // The number of user bytes a single byte of ASAN shadow memory can track.
 _INLINE_VAR constexpr size_t _Asan_granularity = 8;
 
+_NODISCARD inline const void* _Get_asan_aligned_first(const void* _First, const void* _Last) noexcept {
```
Comment (CaseyCarter) [inline stl/inc/xmemory:779]: Both arguments could be `const`.

File: stl/inc/xmemory (hunk 3 above)
Comment (strega-nil-ms) [reply stl/inc/xmemory:788]: It is not, but I was nervous about pointer provenance and I don't know the exact rules -.-

File: stl/inc/xstring (hunk 1 above)
Comment (strega-nil-ms) [reply stl/inc/xstring:2550]: I don't love this suggestion; `ASan` is the more "correct" capitalization as a shortening of "AddressSanitizer", but for variable names, `asan` is more appropriate. At the beginning of a name, due to our naming style, it should be `_Asan`.

File: stl/inc/xmemory (hunk 3 above)
Comment (CaseyCarter) [reply stl/inc/xmemory:788]: I don't either - they don't come up often. C++17 [basic.stc.dynamic.safety]/3.4 says we can perform arithmetic in the `uintptr_t` domain if the result converted back to a pointer would compare equal to a safely-derived pointer computable in the pointer domain. So we could simply return the result of reinterpreting `_Aligned_address` even on an implementation with strict pointer safety (which again, ours is not).

File: stl/inc/xstring (hunk 1 above)
Comment (CaseyCarter) [reply stl/inc/xstring:2550]: That's a reasonable argument - I withdraw my naming gripe. My concern about "may not" remains.

Comment (strega-nil-ms) [reply stl/inc/xstring:2550]: Yeah, working on fixing.

File: stl/inc/vector [hunk 7]
```diff
@@ -539,33 +539,10 @@ private:
...
-        if (_Capacity > _Alignment_offset) {
-            return _CFirst + _Alignment_offset;
-        }
-
-        return nullptr;
-    }
-
     static _CONSTEXPR20 void _Apply_annotation(
-        pointer _First_, pointer _End_, pointer _Old_last_, pointer _New_last_) noexcept {
+        pointer _First_, pointer _Buffer_last_, pointer _Old_last_, pointer _New_last_) noexcept {
```
Comment (CaseyCarter) [inline stl/inc/vector:543]: (Sung to the tune of "you kids get off my lawn!") Why are we renaming `_End`? We have a lot of history with using `first`, `last`, and `end` to refer to the three pointers in a `vector`.

File: stl/inc/xmemory [hunk 8]
```diff
@@ -776,6 +776,30 @@ _NODISCARD constexpr allocation_result<typename allocator_traits<_Alloc>::pointe
...
+_NODISCARD inline const void* _Get_asan_aligned_first(const void* const _First, const void* const _Last) noexcept {
+    const auto _First_address = reinterpret_cast<uintptr_t>(_First);
+    const auto _Last_address  = reinterpret_cast<uintptr_t>(_Last);
+
+    const auto _Aligned_address = (_First_address + _Asan_granularity - 1) & ~(_Asan_granularity - 1);
+
+    if (_Aligned_address > _Last_address) {
+        return nullptr;
+    } else {
+        return reinterpret_cast<const char*>(_Aligned_address);
```
Comment (CaseyCarter) [inline stl/inc/xmemory:788]: Any reason for `const char*` here when the function returns `const void*`?

File: stl/inc/xmemory [hunk 9]
```diff
@@ -776,6 +776,30 @@ _NODISCARD constexpr allocation_result<typename allocator_traits<_Alloc>::pointe
...
+    }
+}
+
+// Works for standard containers with the `value_type` typedef.
```
Comment (CaseyCarter) [inline stl/inc/xmemory:792]: 🔥 (Fighting the war on comments!)

File: stl/inc/xmemory [hunk 10]
```diff
@@ -776,6 +776,30 @@ _NODISCARD constexpr allocation_result<typename allocator_traits<_Alloc>::pointe
...
+template <class _Container, class = void>
+_INLINE_VAR constexpr size_t _Container_allocation_minimum_alignment = alignof(typename _Container::value_type);
+
+template <class _Container>
+_INLINE_VAR constexpr size_t _Container_allocation_minimum_alignment<_Container,
+    void_t<decltype(_Container::allocator_type::_Minimum_allocation_alignment)>> =
+    alignof(typename _Container::value_type) > _Container::allocator_type::_Minimum_allocation_alignment
+        ? alignof(typename _Container::value_type)
+        : _Container::allocator_type::_Minimum_allocation_alignment;
```
Comment (CaseyCarter) [inline stl/inc/xmemory:801]: Could we use `_Max_value` instead of the conditional operator here?

File: stl/inc/xstring [hunk 11]
```diff
@@ -2526,38 +2516,34 @@ private:
...
+        // annotates exactly the pointer as valid
+        _Remove_annotation();
 
-        if (_Capacity >= _Asan_granularity) { // We are guaranteed to have sufficient space to find an aligned address
-            return reinterpret_cast<const void*>(
-                (reinterpret_cast<uintptr_t>(_CFirst) + (_Asan_granularity - 1)) & ~(_Asan_granularity - 1));
-        }
+        auto& _My_data              = _Mypair._Myval2;
+        const void* const _My_buf   = _My_data._Bx._Buf;
+        const void* const _Ptr_last = &_My_data._Bx._Ptr + 1;
```
Comment (CaseyCarter) [inline stl/inc/xstring:2530]: `_Ptr` can have program-defined type:
```suggestion
        const void* const _Ptr_last = _STD addressof(_My_data._Bx._Ptr) + 1;
```

File: stl/inc/xstring [hunk 12]
```diff
@@ -2526,38 +2516,34 @@ private:
...
+        const void* const _Buf_last = _My_data._Bx._Buf + _BUF_SIZE;
 
-        uintptr_t _Alignment_offset = reinterpret_cast<uintptr_t>(_CFirst) & (_Asan_granularity - 1);
-        if (_Alignment_offset != 0) {
-            _Alignment_offset = _Asan_granularity - _Alignment_offset;
-        }
+        constexpr bool _Small_string_always_aligned = _Memcpy_val_offset % _Asan_granularity == 0;
```
Comment (CaseyCarter) [inline stl/inc/xstring:2533]: Doesn't this assume that `*this` is always aligned to `_Asan_granularity` (8), which I think is true only on 64-bit platforms? (Also on 2566. If this were a `private: static constexpr` class member we'd only need to fix it once =))

File: stl/inc/xstring [hunk 13]
```diff
@@ -2526,38 +2516,34 @@ private:
...
+            __sanitizer_annotate_contiguous_container(_My_buf, _Buf_last, _Buf_last, _Ptr_last);
+        } else {
+            const auto _My_buf_address = reinterpret_cast<uintptr_t>(_My_buf);
+            if ((_My_buf_address & (_Asan_granularity - 1)) == 0) {
+                __sanitizer_annotate_contiguous_container(_My_buf, _Buf_last, _Buf_last, _Ptr_last);
+            }
 
-        if (_Capacity > _Alignment_offset) {
-            return _CFirst + _Alignment_offset;
+            // otherwise, there's nothing to do - we can't annotate just the latter nybble of the byte
```
Comment (CaseyCarter) [inline stl/inc/xstring:2542]: I don't think `nybble` is a word.

File: stl/inc/xstring [hunk 14]
```diff
@@ -2569,43 +2555,43 @@ private:
...
 
-        // We need to check whether we have a misaligned SSO buffer because of the proxy in `_Container_base` (e.g. x86)
-        if constexpr (_Memcpy_val_offset % _Asan_granularity != 0) {
-            const uintptr_t _Alignment_offset = reinterpret_cast<uintptr_t>(_Ptr) & (_Asan_granularity - 1);
-            if (_Alignment_offset != 0 && _Capacity == _BUF_SIZE - 1) {
-                return;
-            }
-        }
+        // Note that `_Capacity`, `_Old_size`, and `_New_size` do not include the null terminator,
+        // so we need to add one back.
```
Comment (CaseyCarter) [inline stl/inc/xstring:2559]:
```suggestion
        // `_Capacity`, `_Old_size`, and `_New_size` do not include the null terminator
```

File: stl/inc/xstring [hunk 15]
```diff
@@ -2569,43 +2555,43 @@ private:
...
+        constexpr bool _Small_string_always_aligned = _Memcpy_val_offset % _Asan_granularity == 0;
+        if constexpr (_Large_string_always_aligned && _Small_string_always_aligned) {
+            __sanitizer_annotate_contiguous_container(_First, _Buf_last, _Old_last, _New_last);
         } else {
-            const void* _Aligned_first = _Get_aligned_first(_First, _Capacity + 1);
+            const void* const _Aligned_first = _STD _Get_asan_aligned_first(_First, _Buf_last);
             if (!_Aligned_first) {
-                // There is no aligned address within the underlying buffer. Nothing to do
+                // There is no aligned address within the underlying buffer.
+                // This should be impossible, as the minimum allocation size for string is 16...
```
Comment (CaseyCarter) [inline stl/inc/xstring:2573]: This is assuming `char`; not all `basic_string`s are `string`.

File: stl/inc/xstring [hunk 16]
```diff
@@ -2569,43 +2555,43 @@ private:
...
                 return;
             }
 
-            const void* _Aligned_old_last = _Old_last < _Aligned_first ? _Aligned_first : _Old_last;
-            const void* _Aligned_new_last = _New_last < _Aligned_first ? _Aligned_first : _New_last;
-            const void* _Aligned_end      = _End < _Aligned_first ? _Aligned_first : _End;
-            __sanitizer_annotate_contiguous_container(
-                _Aligned_first, _Aligned_end, _Aligned_old_last, _Aligned_new_last);
+            // last must be >= than first, so fix up when `_Aligned_first > _*_last`
+            // note that _Buf_last must be > 16 from _First, so it certainly is past _Aligned_first (< _First + 8)
```
Comment (CaseyCarter) [inline stl/inc/xstring:2579]: Ditto `char` assumptions?

File: stl/inc/xstring [hunk 17]
```diff
@@ -2744,8 +2730,11 @@ private:
         _Container_proxy_ptr<_Alty> _Proxy(_Alproxy, _My_data);
 
         if (_Count < _BUF_SIZE) {
+            _My_data._Myres = _BUF_SIZE - 1;
+
             _My_data._Mysize = _Count;
-            _My_data._Myres  = _BUF_SIZE - 1;
```
Comment (CaseyCarter) [inline stl/inc/xstring:2748]: Is this just churn?

File: stl/inc/xstring (hunk 13 above)
Comment (StephanTLavavej) [reply stl/inc/xstring:2542]: https://en.wikipedia.org/wiki/Nibble
> In computing, a nibble[1] (occasionally nybble, nyble, or nybl to match the spelling of byte)

I've seen "nybble" before, although not the other two that Wikipedia mentions. (Interestingly, Wikipedia doesn't know what "hexit" is, and that word is super useful.) I think either "nibble" or "nybble" here are fine.

File: stl/inc/xmemory (hunk 10 above)
Comment (CaseyCarter) [reply stl/inc/xmemory:801]: Yes, I'm the person that counts the number of template instantiations and alias expansions to evaluate the complexity of metaprogramming, so this suggestion may seem out of character. I think we all have at least a mild dislike of the conditional operator, especially when used to implement min / max which requires repeating everything twice, and the names we repeat here are not short. This reaches my threshold of "I'm willing to pay a few microseconds of compile time to not have to read this."

File: stl/inc/xstring (hunk 15 above)
Comment (strega-nil-ms) [reply stl/inc/xstring:2573]: no it isn't; all `basic_string`s (as far as I know) have a small buffer of at least (byte) size `16`.

File: stl/inc/xstring (hunk 16 above)
Comment (strega-nil-ms) [reply stl/inc/xstring:2579]: This is still in the world of bytes.

File: stl/inc/xstring (hunk 17 above)
Comment (strega-nil-ms) [reply stl/inc/xstring:2748]: I wanted to put the `size` set next to the `_ASAN_STRING_CREATE`

File: stl/inc/xstring (hunk 15 above)
Comment (CaseyCarter) [reply stl/inc/xstring:2573]: Per:

https://github.com/microsoft/STL/blob/fb386c01083245a80db2666433235918c40d8363/stl/inc/xstring#L2273

`sizeof(value_type[_BUF_SIZE]) * sizeof(value_type)` is `16` iff `sizeof(value_type)` divides `16`, i.e., `sizeof(value_type)` is 1, 2, 4, 8, or 16. `sizeof(value_type[_BUF_SIZE]) >= 16` holds when `sizeof(_Ty)` is a power of two or greater than 15.

Comment (strega-nil-ms) [reply stl/inc/xstring:2573]: right, exactly

Comment (strega-nil-ms) [reply stl/inc/xstring:2573]: oh, I see what you're saying; I meant "the minimum allocation size for [all] string [types] is [at least] 16". Will fix.

File: stl/inc/vector (hunk 7 above)
Comment (strega-nil-ms) [reply stl/inc/vector:543]: I... really dislike this convention, but I'll follow it. `_End` confused the heck out of me.

File: stl/inc/xmemory (hunk 8 above)
Comment (strega-nil-ms) [reply stl/inc/xmemory:788]: missed edit.

File: stl/inc/xstring (hunk 12 above)
Comment (strega-nil-ms) [reply stl/inc/xstring:2533]: This checks if `*this` is always aligned to `_Asan_granularity`; yeah, it'll be true only on 64-bit platforms.

Comment (CaseyCarter) [reply stl/inc/xstring:2533]: Per our offline discussion: this validates that the offset of the SSO buffer within `*this` is a multiple of `_Asan_granularity`, but it might still be misaligned if `this` itself is not aligned to a multiple of `_Asan_granularity`.

File: stl/inc/xstring [hunk 18]
```diff
@@ -2514,6 +2504,9 @@ private:
 #endif // _HAS_CXX17
 
 #ifdef _INSERT_STRING_ANNOTATION
+    constexpr bool _Small_string_always_asan_aligned =
+        alignof(*this) >= 8 && _Memcpy_val_offset % _Asan_granularity == 0;
```
Comment (CaseyCarter) [inline stl/inc/xstring:2508]: Should this `8` be `_Asan_granularity`?

File: stl/inc/vector [hunk 19]
```diff
@@ -539,33 +539,10 @@ private:
...
-        }
-
-        return nullptr;
-    }
-
     static _CONSTEXPR20 void _Apply_annotation(
         pointer _First_, pointer _End_, pointer _Old_last_, pointer _New_last_) noexcept {
         _STL_INTERNAL_CHECK(_First_ != nullptr);
-        _STL_INTERNAL_CHECK(_End_ != nullptr);
+        _STL_INTERNAL_CHECK(_Buffer_last_ != nullptr);
```
Comment (CaseyCarter) [inline stl/inc/vector:545]: `_Buffer_last_` here that should have been reverted to `_End_`.

File: stl/inc/vector [hunk 20]
```diff
@@ -579,24 +556,24 @@ private:
...
-        if constexpr (_Has_minimum_allocation_alignment<vector>) {
+        const void* const _First    = _STD _Unfancy(_First_);
+        const void* const _End      = _STD _Unfancy(_End_);
+        const void* const _Old_last = _STD _Unfancy(_Old_last_);
+        const void* const _New_last = _STD _Unfancy(_New_last_);
+        if constexpr ((_Container_allocation_minimum_alignment<vector>) > _Asan_granularity) {
             __sanitizer_annotate_contiguous_container(_First, _End, _Old_last, _New_last);
         } else {
-            const void* const _Aligned_first = _Get_aligned_first(_First, _End);
+            const void* const _Aligned_first = _STD _Get_asan_aligned_first(_First, _Buffer_last);
```
Comment (CaseyCarter) [inline stl/inc/vector:566]: `_Buffer_last` here that should have been reverted to `_End`.

File: stl/inc/xstring [hunk 21]
```diff
@@ -2526,38 +2519,33 @@ private:
...
+        const void* const _My_buf   = _My_data._Bx._Buf;
+        const void* const _Ptr_last = _STD addressof(_My_data._Bx._Ptr) + 1;
+        const void* const _Buf_last = _My_data._Bx._Buf + _BUF_SIZE;
 
-        uintptr_t _Alignment_offset = reinterpret_cast<uintptr_t>(_CFirst) & (_Asan_granularity - 1);
-        if (_Alignment_offset != 0) {
-            _Alignment_offset = _Asan_granularity - _Alignment_offset;
-        }
+        if constexpr (_Small_string_always_aligned) {
+            __sanitizer_annotate_contiguous_container(_My_buf, _Buf_last, _Buf_last, _Ptr_last);
```
Comment (CaseyCarter) [inline stl/inc/xstring:2537]: Does this depend on `sizeof(_My_data._Bx._Ptr)` being a multiple of 8, or 4, or anything? I've forgotten half of what I once understood about ASan. (Also on 2541.)

Comment (strega-nil-ms) [reply stl/inc/xstring:2537]: it does not. The way it works is that each 8-byte region can be marked "first-N-valid", so having 1 byte, 2 bytes, etc. is fine as long as the first byte is on an asan boundary.

File: stl/inc/xstring [hunk 22]
```diff
@@ -2569,43 +2557,38 @@ private:
...
 
-        // Needs to consider the null terminator
-        const char* _First    = reinterpret_cast<const char*>(_Ptr);
-        const char* _End      = reinterpret_cast<const char*>(_Ptr + _Capacity + 1);
-        const char* _Old_last = reinterpret_cast<const char*>(_Ptr + _Old_size + 1);
-        const char* _New_last = reinterpret_cast<const char*>(_Ptr + _New_size + 1);
-        if constexpr (_Has_minimum_allocation_alignment_string<basic_string>) {
-            __sanitizer_annotate_contiguous_container(_First, _End, _Old_last, _New_last);
+        constexpr bool _Large_string_always_aligned =
+            (_Container_allocation_minimum_alignment<basic_string>) > _Asan_granularity;
```
[the remark this answers is not in the document]
Comment (strega-nil-ms) [reply stl/inc/xstring:2566]: you're right.

File: stl/inc/vector [hunk 23]
```diff
@@ -579,24 +556,22 @@ private:
...
-        const auto _First    = reinterpret_cast<const char*>(_Unfancy(_First_));
-        const auto _End      = reinterpret_cast<const char*>(_Unfancy(_End_));
-        const auto _Old_last = reinterpret_cast<const char*>(_Unfancy(_Old_last_));
-        const auto _New_last = reinterpret_cast<const char*>(_Unfancy(_New_last_));
-        if constexpr (_Has_minimum_allocation_alignment<vector>) {
+        const void* const _First    = _STD _Unfancy(_First_);
+        const void* const _End      = _STD _Unfancy(_End_);
+        const void* const _Old_last = _STD _Unfancy(_Old_last_);
+        const void* const _New_last = _STD _Unfancy(_New_last_);
+        if constexpr ((_Container_allocation_minimum_alignment<vector>) > _Asan_granularity) {
```
Comment (miscco) [inline stl/inc/vector:563]: Are those additional braces needed?
```suggestion
        if constexpr (_Container_allocation_minimum_alignment<vector> > _Asan_granularity) {
```

File: stl/inc/xmemory [hunk 24]
```diff
@@ -776,6 +776,63 @@ _NODISCARD constexpr allocation_result<typename allocator_traits<_Alloc>::pointe
 // The number of user bytes a single byte of ASAN shadow memory can track.
 _INLINE_VAR constexpr size_t _Asan_granularity = 8;
 
+struct _AsanAlignedPointers {
+    const void* _First;
+    const void* _End;
+
+    constexpr const void* _Clamp(const void* _Mid) const noexcept {
```
Comment (miscco) [inline stl/inc/xmemory:783]: Should be 
```suggestion
    _NODISCARD constexpr const void* _Clamp(const void* _Mid) const noexcept {
```

File: stl/inc/xmemory [hunk 25]
```diff
@@ -776,6 +776,63 @@ _NODISCARD constexpr allocation_result<typename allocator_traits<_Alloc>::pointe
...
+    const void* const _First, const void* const _Last) noexcept {
+    constexpr static uintptr_t _Mask = ~(_Asan_granularity - 1);
+
+    const auto _First_address = reinterpret_cast<uintptr_t>(_First);
+    const auto _Last_address  = reinterpret_cast<uintptr_t>(_Last);
+
+    const uintptr_t _Aligned_first_address = (_First_address + _Asan_granularity - 1) & _Mask;
+    const uintptr_t _Aligned_last_address  = _Last_address & _Mask;
+
+    if (_Aligned_first_address == _Aligned_last_address) {
```
Comment (miscco) [inline stl/inc/xmemory:818]: Should we be super defensive and check for `<=`

File: stl/inc/xstring [hunk 26]
```diff
@@ -2366,7 +2366,6 @@ struct _String_constructor_rvalue_allocator_tag {
     _Xlength_error("string too long");
 }
 
-#if 0 // TRANSITION, VSO-1586016: String annotations disabled temporarily.
```
Comment (miscco) [inline stl/inc/xstring:2369]: That makes me soo happy. Thanks a lot 🎉

File: stl/inc/xstring [hunk 27]
```diff
@@ -2514,6 +2504,11 @@ private:
 #endif // _HAS_CXX17
 
 #ifdef _INSERT_STRING_ANNOTATION
+    // this is a function so we can get the alignment of the class while defining it.
+    static constexpr bool _Small_string_always_asan_aligned() {
```
Comment (miscco) [inline stl/inc/xstring:2508]:
```suggestion
    _NODISCARD static constexpr bool _Small_string_always_asan_aligned() noexcept {
```

File: stl/inc/xstring [hunk 28]
```diff
@@ -2526,38 +2521,62 @@ private:
...
-        // Extends/shrinks the annotated range by _Count
-        if (_Count == 0) {
-            return;
-        }
-
+    _CONSTEXPR20 void _Modify_annotation(const size_type _Old_size, const size_type _New_size) const noexcept {
         auto& _My_data = _Mypair._Myval2;
-        _Apply_annotation(
-            _My_data._Myptr(), _My_data._Myres, _My_data._Mysize, static_cast<size_type>(_My_data._Mysize + _Count));
+        _Apply_annotation(_My_data._Myptr(), _My_data._Myres, _Old_size, _New_size);
```
Comment (miscco) [inline stl/inc/xstring:2526]: I am not a fan of removing the size check, as `_Myptr()` does some work

File: stl/inc/xstring [hunk 29]
```diff
@@ -2843,9 +2861,11 @@ private:
 #endif // _HAS_CXX20
                     _Traits::copy(_Unfancy(_New_ptr), _Old_ptr, _My_data._Mysize);
                     if (_My_data._Myres >= _BUF_SIZE) { // Need to deallocate old storage
+                        _ASAN_STRING_REMOVE(*this);
                         _Al.deallocate(_My_data._Bx._Ptr, _My_data._Myres + 1);
                         _My_data._Bx._Ptr = _New_ptr;
                     } else {
+                        _ASAN_STRING_SWITCH_TO_LARGE(_My_data);
```
Comment (miscco) [inline stl/inc/xstring:2868]: Something is fishy here.

At the end of the function we call `_ASAN_STRING_CREATE(*this);` Why do we already have a valid ASAN region here and still do that?

File: stl/inc/xstring [hunk 30]
```diff
@@ -3169,7 +3189,6 @@ private:
 
 #ifdef _INSERT_STRING_ANNOTATION
                 if (!_Right_data._Large_string_engaged()) {
-                    _ASAN_STRING_REMOVE(_Right);
```
Comment (miscco) [inline stl/inc/xstring:3172]: Thanks for cleaning that up

File: stl/inc/xstring [hunk 31]
```diff
@@ -2843,9 +2861,11 @@ private:
 #endif // _HAS_CXX20
                     _Traits::copy(_Unfancy(_New_ptr), _Old_ptr, _My_data._Mysize);
                     if (_My_data._Myres >= _BUF_SIZE) { // Need to deallocate old storage
+                        _ASAN_STRING_REMOVE(*this);
```
Comment (miscco) [inline stl/inc/xstring:2864]: Is that really valid? It is happening in a loop after all

**Review by miscco — COMMENTED** [review]
I am a bit rusty on the invariants that we provide (last years code, urghh)

`_Construct_from_iter` gives me some strange feelings, as I am unsure where the repeated calls to `_ASAN_STRING_REMOVE` come from

File: stl/inc/vector (hunk 23 above)
Comment (strega-nil-ms) [reply stl/inc/vector:563]: They are, else `clang-format` does a `_Container_alignment_minimum_alignment < vector >> _Asan_granularity`

File: stl/inc/xmemory (hunk 25 above)
Comment (strega-nil-ms) [reply stl/inc/xmemory:818]: That's impossible unless someone passed `_First_address > _Last_address` so that should just be a precondition check (`_STL_ASSERT` maybe)

File: stl/inc/xstring (hunk 29 above)
Comment (strega-nil-ms) [reply stl/inc/xstring:2868]: `_ASAN_STRING_SWITCH_TO_LARGE` creates a valid ASAN region _inside the SSO buffer_ for the pointer. `_ASAN_STRING_CREATE` then creates a valid ASAN region in the large buffer.

File: stl/inc/xstring (hunk 31 above)
Comment (strega-nil-ms) [reply stl/inc/xstring:2864]: It happens in a loop, but only happens on reallocation.

File: stl/inc/xmemory (hunk 25 above)
Comment (strega-nil-ms) [reply stl/inc/xmemory:818]: oops, no you're totally right - if `_First_address` and `_Last_address` are in the same shadow memory section, this is what happens.

File: stl/inc/xmemory [hunk 32]
```diff
@@ -776,6 +776,63 @@ _NODISCARD constexpr allocation_result<typename allocator_traits<_Alloc>::pointe
...
+//    int meow; // bytes [0, 4)
+//    char buffer[16]; // bytes [4, 20)
+//    int purr; // bytes [20, 24)
+// };
+// you cannot mark `buffer + [0, 4)`, since `buffer + 0` doesn't start a shadow memory section
+// (i.e., it's not on an 8-byte boundary).
+// Additionally, if you attempt to mark up to `buffer + 16` (the real end of buffer), it'll also mark `purr`.
+// Thus, the only part you can _actually_ mark is the complete shadow memory section of `buffer + [4, 12)`
+// (i.e., bytes [8, 16)).
+_NODISCARD inline _AsanAlignedPointers _Get_asan_aligned_first_end(
```
Comment (strega-nil-ms) [inline stl/inc/xmemory:808]: @ras0219 has convinced me that we can maybe just mask off the `first` pointer without concern for being on a shadow memory boundary, since we _must_ assume that the stuff before the `first` pointer is valid...

File: stl/inc/xstring [hunk 33]
```diff
@@ -3883,6 +3881,7 @@ public:
 #endif // _HAS_CXX20
         {
             if (_Growth <= _Mypair._Myval2._Myres - _Old_size) { // growth fits
+                _ASAN_STRING_MODIFY(*this, _Old_size, _Old_size + _Growth);
                 _Mypair._Myval2._Mysize = _Old_size + _Growth;
                 _Elem* const _Old_ptr   = _Mypair._Myval2._Myptr();
                 _Elem* const _Insert_at = _Old_ptr + _Off;
```
Comment (amyw-msft) [inline stl/inc/xstring:3887]: `replace(const size_type _Off, size_type _Nx, const size_type _Count, const _Elem _Ch)` is missing annotation coverage

File: stl/inc/xmemory [hunk 34]
```diff
@@ -776,6 +776,118 @@ _NODISCARD constexpr allocation_result<typename allocator_traits<_Alloc>::pointe
...
+        _STL_ASSERT(_Mid >= _First, "");
+        if (_Mid > _End) {
+            return _End;
+        } else {
+            return _Mid;
+        }
+    }
+};
+
+// The way that ASan shadow memory works, each eight byte block of memory ("shadow memory section")
```
Comment (amyw-msft) [inline stl/inc/xmemory:793]: I love giant explain-y comments :) esp. with diagrams!

File: stl/inc/xstring [hunk 35]
```diff
@@ -2526,38 +2467,78 @@ private:
...
 
-    _NODISCARD static const void* _Get_aligned_first(const void* _First, const size_type _Capacity) noexcept {
-        const char* _CFirst = reinterpret_cast<const char*>(_First);
-
-        if (_Capacity >= _Asan_granularity) { // We are guaranteed to have sufficient space to find an aligned address
-            return reinterpret_cast<const void*>(
-                (reinterpret_cast<uintptr_t>(_CFirst) + (_Asan_granularity - 1)) & ~(_Asan_granularity - 1));
+    _CONSTEXPR20 static void _Remove_sso_annotation(const _Scary_val& _My_data) noexcept {
+        // Removes annotation of the SSO buffer with shadow memory.
+        // This results in the ability to copy into the SSO buffer without worrying.
```
Comment (amyw-msft) [inline stl/inc/xstring:2481]: I imagine the extra calls here are mostly about removing the reliance on the string's current state for `_Create_annotation` and `_Remove_annotation` to make sure we're always doing what we intend? Can they be implemented in terms of `_Apply_annotation` to reduce code duplication?

File: tests/std/tests/GH_002030_asan_annotate_string/test.cpp [hunk 36]
```diff
@@ -1845,6 +1835,13 @@ void test_DevCom_10116361() {
     s1.~string();
 }
 
+void test_DevCom_10109507() {
```
Comment (amyw-msft) [inline tests/std/tests/GH_002030_asan_annotate_string/test.cpp:1838]: We don't seem to test `string::replace` in other areas of this test - perhaps should add thorough tests for that function like the others?

File: stl/CMakeLists.txt [hunk 37]
```diff
@@ -7,6 +7,7 @@ set(HEADERS
     ${CMAKE_CURRENT_LIST_DIR}/inc/__msvc_format_ucd_tables.hpp
     ${CMAKE_CURRENT_LIST_DIR}/inc/__msvc_int128.hpp
     ${CMAKE_CURRENT_LIST_DIR}/inc/__msvc_iter_core.hpp
+    ${CMAKE_CURRENT_LIST_DIR}/inc/__msvc_sanitizer_annotate_container.hpp
```
Comment (amyw-msft) [inline stl/CMakeLists.txt:10]: Sorry not sure of the process, but just wanted to make sure it's caught that is a needed setup change when we mirror into MSVC.

File: stl/inc/vector [hunk 38]
```diff
@@ -579,24 +494,37 @@ private:
...
-        const auto _End      = reinterpret_cast<const char*>(_Unfancy(_End_));
-        const auto _Old_last = reinterpret_cast<const char*>(_Unfancy(_Old_last_));
-        const auto _New_last = reinterpret_cast<const char*>(_Unfancy(_New_last_));
-        if constexpr (_Has_minimum_allocation_alignment<vector>) {
-            __sanitizer_annotate_contiguous_container(_First, _End, _Old_last, _New_last);
+        const void* const _First    = _STD _Unfancy(_First_);
+        const void* const _End      = _STD _Unfancy(_End_);
+        const void* const _Old_last = _STD _Unfancy(_Old_last_);
+        const void* const _New_last = _STD _Unfancy(_New_last_);
+        if constexpr ((_Container_allocation_minimum_alignment<vector>) > _Asan_granularity) {
```
[the remark this answers is not in the document]
Comment (amyw-msft) [reply stl/inc/vector:501]: Same in string.

File: stl/inc/vector [hunk 39]
```diff
@@ -579,24 +494,37 @@ private:
...
+
+            // old state:
+            //   [_Aligned._First, _Old_fixed) valid
+            //   [_Old_fixed, _Aligned._End) poison
+            //   [_Aligned._End, _End) valid
+            // new state:
+            //   [_Aligned._First, _New_fixed) valid
+            //   [_New_fixed, _Aligned._End) poison
+            //   [_Aligned._End, _End) valid
+            _CSTD __sanitizer_annotate_contiguous_container(_Aligned._First, _Aligned._End, _Old_fixed, _New_fixed);
```
[the remark this answers is not in the document]
Comment (amyw-msft) [reply stl/inc/vector:527]: Same in string.

File: tests/std/tests/GH_002030_asan_annotate_string/test.cpp [hunk 40]
```diff
@@ -1,15 +1,11 @@
 // Copyright (c) Microsoft Corporation.
 // SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
```
Comment (amyw-msft) [inline tests/std/tests/GH_002030_asan_annotate_string/test.cpp:2]: May want to also test everything works for x86 `string`s when forced on a 4-byte boundary (I think by default the compiler won't do this, but it is technically allowed) and for a custom allocator that doesn't return 8-byte aligned addresses. The tests in the PR I abandoned covered these if you want to take them.

**Review by amyw-msft — CHANGES_REQUESTED** [review]

File: stl/inc/vector (hunk 38 above)
[the remark this answers is not in the document]
Comment (strega-nil-ms) [reply stl/inc/vector:501]: Technically no, since ASan will just push `_End` to the end of the shadow memory section anyways; however, it may make sense to do so anyways in case this function starts _actually_ checking.

File: stl/inc/vector (hunk 39 above)
[the remark this answers is not in the document]
Comment (strega-nil-ms) [reply stl/inc/vector:527]: I need to think this through, will get back to you.

File: stl/inc/xstring (hunk 35 above)
Comment (strega-nil-ms) [reply stl/inc/xstring:2481]: They cannot be; these are functions on the SSO buffer _regardless_ of the current SSO state of the string.

File: stl/inc/xstring [hunk 41]
```diff
@@ -2569,43 +2550,52 @@ private:
...
-            __sanitizer_annotate_contiguous_container(
-                _Aligned_first, _Aligned_end, _Aligned_old_last, _Aligned_new_last);
-        }
-    }
-
-#define _ASAN_STRING_MODIFY(n)    _Modify_annotation((n))
-#define _ASAN_STRING_REMOVE(_Str) (_Str)._Remove_annotation()
-#define _ASAN_STRING_CREATE(_Str) (_Str)._Create_annotation()
+            const auto _Aligned = _STD _Get_asan_aligned_first_end(_First, _End);
+            // The buffer must always have size >= 9 bytes, so it will always end at least one shadow memory section.
```
[the remark this answers is not in the document]
Comment (strega-nil-ms) [reply stl/inc/xstring:2570]: Exactly, that's what this does.

File: stl/inc/vector (hunk 39 above)
[the remark this answers is not in the document]
Comment (strega-nil-ms) [reply stl/inc/vector:527]: I think that `_Aligned._End` is moving the opposite way as to what you're expecting.

[the remark this answers is not in the document]
Comment (amyw-msft) [reply stl/inc/vector:527]: I read your diagram again and yeah I misunderstood the direction of end adjustment. Clamp to end handles my concern then. So, we're accepting false negatives in right out-of-bounds scenarios, though I guess only for allocations without a pre-aligned `_End`? Hm, that both feels like an atypical scenario but also one where it's not hard to get into?
```
vector<int, some_custom_allocator_so_we_use_the_realigning_path<int>> a = {1, 2, 3};
a.reserve(5);
a[a.size()] = 4; // will error, in poisoned zone
a[a.size() + 1] = 5; // will not error, in next 8-byte chunk, but also still part of the allocation made by vector
```
The poisoning here would look like:
```
fa fa 00 04 00 fa fa
```
when I might argue it should look like:
```
fa fa 00 04 fc fa fa
```
Thoughts?

[the remark this answers is not in the document]
Comment (amyw-msft) [reply stl/inc/vector:527]: I guess my point is that we're not annotating an arbitrary structure, right? If we receive an allocation that we know is from the heap, then we can make the assumption that the allocation isn't right next to another structure that needs to be valid and we can provide better protection. I guess at that point the question is whether that's a reasonable assumption for custom allocators?

[the remark this answers is not in the document]
Comment (strega-nil-ms) [reply stl/inc/vector:527]: The other option is to over-allocate, but that's a change in behavior that we'd have to consider a lot since it may break someone's custom allocator.

File: stl/inc/xstring (hunk 35 above)
Comment (amyw-msft) [reply stl/inc/xstring:2481]: _Apply_annotation is static though - it doesn't use any container state, just what's passed in. _Remove_sso_annotation could just be:
```
_Apply_annotation(_My_data._Bx._Buf, _BUF_SIZE - 1, 0, _BUF_SIZE - 1);
```
No?

That said, I see the clarity value in using `__sanitizer_annotate_contiguous_container` directly. It's mostly the complication that comes with having multiple code paths that bothers me and needing to worry about how those interweave.

Comment (amyw-msft) [reply stl/inc/xstring:2481]: I'm essentially just worried that some SSO buffer annotations are removed with `_Remove_sso_annotation` and some are removed with `_Apply_annotation`. It does appear to be fine in practice though since `_Apply_annotation` is the one with the potentially smaller brush and it is also the only one that poisons, so I'm convinced it doesn't need to change.

File: stl/inc/vector (hunk 39 above)
[the remark this answers is not in the document]
Comment (amyw-msft) [reply stl/inc/vector:527]: Makes sense! Thanks :)

File: stl/inc/vector (hunk 38 above)
[the remark this answers is not in the document]
Comment (amyw-msft) [reply stl/inc/vector:501]: I see - both this check and the `_Small/Large_string_always_asan_aligned` checks in string are just optimizations then, yeah? It makes the code (at least, when you don't see how it all fits together) quite a bit more complex - might be worth removing the optimization?

File: stl/inc/xstring [hunk 42]
```diff
@@ -2514,6 +2449,12 @@ private:
 #endif // _HAS_CXX17
 
 #ifdef _INSERT_STRING_ANNOTATION
+    // this is a function so we can get the alignment of the class while defining it.
+    _NODISCARD static constexpr bool _Small_string_always_asan_aligned() noexcept {
+        return alignof(basic_string) >= _Asan_granularity && _Memcpy_val_offset % _Asan_granularity == 0
+            && (sizeof(value_type[_BUF_SIZE]) % _Asan_granularity == 0 || alignof(size_type) >= _Asan_granularity);
```
Comment (StephanTLavavej) [inline stl/inc/xstring:2455]: Comments explaining the meaning of each sub-condition here would be very helpful.

File: stl/inc/xstring [hunk 43]
```diff
@@ -2648,13 +2638,13 @@ public:
...
         : _Mypair(_One_then_variadic_args_t{}, _Al) { // construct from _Right [_Roff, <end>), potentially move
-        _Move_construct_from_substr(_Right, _Roff, npos, _Al);
+        _Move_construct_from_substr(_Right, _Roff, npos);
     }
 
     constexpr basic_string(
         basic_string&& _Right, const size_type _Roff, const size_type _Count, const _Alloc& _Al = _Alloc())
         : _Mypair(_One_then_variadic_args_t{}, _Al) { // construct from _Right [_Roff, _Roff + _Count), potentially move
-        _Move_construct_from_substr(_Right, _Roff, _Count, _Al);
+        _Move_construct_from_substr(_Right, _Roff, _Count);
```
Comment (StephanTLavavej) [inline stl/inc/xstring:2647]: I think a merge was incorrectly resolved here - please double-check that you've merged with `main` and picked up #3178. There are related stray changes to `_Move_construct_from_substr` below.

File: stl/inc/xstring [hunk 44]
```diff
@@ -3866,11 +3863,12 @@ public:
         const size_type _Old_size    = _Mypair._Myval2._Mysize;
         const size_type _Suffix_size = _Old_size - _Nx - _Off + 1;
         if (_Count < _Nx) { // suffix shifts backwards; we don't have to move anything out of the way
-            _Mypair._Myval2._Mysize = _Old_size - (_Nx - _Count);
             _Elem* const _Old_ptr   = _Mypair._Myval2._Myptr();
             _Elem* const _Insert_at = _Old_ptr + _Off;
             _Traits::move(_Insert_at, _Ptr, _Count);
             _Traits::move(_Insert_at + _Count, _Insert_at + _Nx, _Suffix_size);
+            _ASAN_STRING_MODIFY(*this, _Old_size, _Old_size - (_Nx - _Count));
+            _Mypair._Myval2._Mysize = _Old_size - (_Nx - _Count);
```
Comment (StephanTLavavej) [inline stl/inc/xstring:3871]: Suggestion: This mentions `_Old_size - (_Nx - _Count)` twice. Could we extract to `_New_size`?

File: stl/inc/xstring [hunk 45]
```diff
@@ -4437,42 +4429,36 @@ public:
...
         }
 
         _STD swap(_My_data._Mysize, _Right_data._Mysize);
         _STD swap(_My_data._Myres, _Right_data._Myres);
+
+        // intentionally swapped, since if `_Right_large` before, now `*this` is large (and vice versa).
+        if (!_Right_large) {
+            _ASAN_STRING_CREATE(*this);
+        }
+        if (!_My_large) {
```
Comment (StephanTLavavej) [inline stl/inc/xstring:4459]: Style: There should be a newline between non-chained `if`-statements.

File: tests/std/tests/GH_002030_asan_annotate_string/env.lst [hunk 46]
```diff
@@ -2,9 +2,9 @@
 # SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
 
 # This test matrix is the usual test matrix, with all currently unsupported options removed, crossed with the ASan flags.
-# TRANSITION, VSO-1350252
-# Due to a bug in the ASan libs using ASan with /MD or /MT requires IDL==0 and using /MDd or /MTd requires IDL==2.
-# clang-cl does not currently support targeting /MDd or /MTd.
+
+# TRANSITION, VSO-1350252 - due to vcasan.lib including the standard library, we can't use it (pending new release).
```
Comment (StephanTLavavej) [inline tests/std/tests/GH_002030_asan_annotate_string/env.lst:6]: Which release, specifically? This will help us notice when the workaround should be removed during a toolset update. Also applies to `GH_002030_asan_annotate_vector/env.lst`.

File: tests/std/tests/GH_002030_asan_annotate_string/test.cpp [hunk 47]
```diff
@@ -170,29 +166,23 @@ class input_iterator_tester {
...
+    const void* const buf_end = str.data() + (str.capacity() + 1);
 
-    size_t buffer_size  = (str.capacity() + 1) * sizeof(CharType);
-    void* buffer        = const_cast<void*>(static_cast<const void*>(str.data()));
-    void* aligned_start = align(8, 1, buffer, buffer_size);
-
-    if (!aligned_start) {
-        return true;
+    _AsanAlignedPointers aligned;
+    if constexpr ((_Container_allocation_minimum_alignment<basic_string<CharType, char_traits<CharType>, Alloc>>) > 8) {
```
Comment (StephanTLavavej) [inline tests/std/tests/GH_002030_asan_annotate_string/test.cpp:175]: Question: Is `> 8` correct here, or should it be `>= 8`?

File: tests/std/tests/GH_002030_asan_annotate_string/test.cpp [hunk 48]
```diff
@@ -170,29 +166,23 @@ class input_iterator_tester {
...
 #ifdef __SANITIZE_ADDRESS__
-    constexpr auto proxy_size = _Size_after_ebco_v<_Container_base>;
-    if constexpr (proxy_size % _Asan_granularity != 0) { // If we have a misaligned SSO buffer we disable ASAN
-        constexpr size_t max_sso_size = (16 / sizeof(CharType) < 1 ? 1 : 16 / sizeof(CharType)) - 1;
-        if (str.capacity() == max_sso_size) {
-            return true;
-        }
-    }
+    const void* const buffer  = str.data();
+    const void* const buf_end = str.data() + (str.capacity() + 1);
```
Comment (StephanTLavavej) [inline tests/std/tests/GH_002030_asan_annotate_string/test.cpp:172]: Suggestion: The parentheses could be omitted here, which would be consistent with `str.data() + str.size() + 1` below.

File: tests/std/tests/GH_002030_asan_annotate_string/test.cpp [hunk 49]
```diff
@@ -1845,6 +1835,13 @@ void test_DevCom_10116361() {
     s1.~string();
 }
 
+void test_DevCom_10109507() {
+    // replace failed to correctly munge asan annotations while working
+    string s("abcd");
+    s.replace(0, 1, "ef", 2);
+    s.replace(0, 0, "xy", 2);
```
Comment (StephanTLavavej) [inline tests/std/tests/GH_002030_asan_annotate_string/test.cpp:1842]: Should we assert the value of `s` after each `replace` call, to minimally verify that changes are happening?

File: tests/std/tests/GH_002030_asan_annotate_vector/test.cpp [hunk 50]
```diff
@@ -148,19 +154,23 @@ class input_iterator_tester {
...
-    size_t buffer_bytes = vec.capacity() * sizeof(T);
-    void* buffer        = vec.data();
-    void* aligned_start = align(8, 1, buffer, buffer_bytes);
+    const void* buffer  = vec.data();
+    const void* buf_end = vec.data() + vec.capacity();
+    _AsanAlignedPointers aligned;
 
-    if (!aligned_start) {
-        return true;
+    if constexpr ((_Container_allocation_minimum_alignment<vector<T, Alloc>>) > 8) {
```
Comment (StephanTLavavej) [inline tests/std/tests/GH_002030_asan_annotate_vector/test.cpp:161]: Also double-checking, is `> 8` correct or should it be `>= 8`?

**Review by StephanTLavavej — CHANGES_REQUESTED** [review]

**Comment by StephanTLavavej** [comment]
Thanks, this looks good! I was able to review all files.

File: stl/inc/vector (hunk 38 above)
[the remark this answers is not in the document]
Comment (amyw-msft) [reply stl/inc/vector:501]: Ah, because we still want to over-poison when using the default allocator to catch right oob situations when the capacity doesn't line up? Might want to add comments about that being the strategy, perhaps to the xmemory comment?

File: stl/inc/xmemory [hunk 51]
```diff
@@ -776,6 +776,118 @@ _NODISCARD constexpr allocation_result<typename allocator_traits<_Alloc>::pointe
...
+        reinterpret_cast<const void*>(reinterpret_cast<uintptr_t>(_Last) & _Mask),
+    };
+}
+
+template <class _Container, class = void>
+_INLINE_VAR constexpr size_t _Container_allocation_minimum_alignment = alignof(typename _Container::value_type);
+
+template <class _Container>
+_INLINE_VAR constexpr size_t _Container_allocation_minimum_alignment<_Container,
+    void_t<decltype(_Container::allocator_type::_Minimum_allocation_alignment)>> =
```
Comment (amyw-msft) [inline stl/inc/xmemory:895]: Since custom allocators will leave false negatives, we likely want to document that behavior at https://learn.microsoft.com/en-us/cpp/sanitizers/error-container-overflow?view=msvc-170 and perhaps allow folks to opt-in to the over-poisoning by adding `_Minimum_allocation_alignment` to their allocators (maybe rename it to be obviously ASAN related - I believe it's otherwise unused?).

**Comment by StephanTLavavej** [comment]
`GH_002030_asan_annotate_string` is failing for x86:

```
Assertion failed: verify_string(input_iterator_constructed),
file D:\a\_work\1\s\tests\std\tests\GH_002030_asan_annotate_string\test.cpp, line 438
```

File: stl/inc/xmemory [hunk 52]
```diff
@@ -776,6 +776,126 @@ _NODISCARD constexpr allocation_result<typename allocator_traits<_Alloc>::pointe
 // The number of user bytes a single byte of ASAN shadow memory can track.
 _INLINE_VAR constexpr size_t _Asan_granularity = 8;
```
Comment (zacklj89) [inline stl/inc/xmemory:777]: Since `_Asan_granularity - 1` is used more than a couple of times, I'm wondering if it makes sense to add a named variable for readability?

File: stl/inc/xstring [hunk 53]
```diff
@@ -3938,8 +3955,9 @@ public:
         const size_type _Old_size = _Mypair._Myval2._Mysize;
         if (_Count < _Nx || _Count - _Nx <= _Mypair._Myval2._Myres - _Old_size) {
             // either we are shrinking, or the growth fits
-            _Mypair._Myval2._Mysize = _Old_size + _Count - _Nx; // may temporarily overflow;
-                                                                // OK because size_type must be unsigned
+            // may temporarily overflow; OK because size_type must be unsigned
+            _ASAN_STRING_MODIFY(*this, _Old_size, _Old_size + _Count - _Nx);
+            _Mypair._Myval2._Mysize = _Old_size + _Count - _Nx;
```
Comment (zacklj89) [inline stl/inc/xstring:3960]: `_New_size` was used on 3887

```suggestion
            const auto _New_size = _Old_size + _Count - _Nx;
            _ASAN_STRING_MODIFY(*this, _Old_size, _New_size);
            _Mypair._Myval2._Mysize = _New_size;
```

**Review by zacklj89 — COMMENTED** [review]
I'm a little late to the review, but great job! This is a big ASAN accomplishment. The cleanups and comments are incredibly helpful.

It also looks like there is a failing string test. After that, I think it looks good to me.

File: stl/inc/xmemory (hunk 51 above)
Comment (strega-nil-ms) [reply stl/inc/xmemory]: microsoft/cpp-docs#4274

**Review by StephanTLavavej — APPROVED** [review]

**Review by amyw-msft — APPROVED** [review]
Looks great :). Just leaving a note to only merge after prod/be ASAN testing complete.

**Comment by StephanTLavavej** [comment]
Thanks Amy! I will definitely wait for that testing.

I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
MSVC-PR-433542 has failed checks; it may be an innocuous option difference between `prod/fe`'s Clang 15 and `prod/be`'s Clang 14, but I'm going to remove this PR from the current merge batch until this is investigated.

**Comment by strega-nil-ms** [comment]
Error report from MSVC-PR-433542:

- Runall-x86:
   + `std x86chk: *`: this is a clang version mismatch issue - prod/be uses clang 14, we use clang 15, so this is `-Wno-unqualified-std-cast-call` biting us. Not a problem
   + `compiler x86chk: tests\cxx\modules\regress\ADO1217191`: this is an issue with an outdated version of the code, that declared `constexpr auto _Mask` in a function; I can't say I understand the error, but it is solved by removing `_Mask` in favor of `_Asan_granularity_mask`
- Runall-amd64: same as Runall-x86
- MSVC-ASAN-Private:
   + `ASanStress_amd64_amd64: await (vso275614 ( -Od ) exe)`: this is a _weird_ error.
     This seems to be a bug in `co_await` such that `string` is unaligned:
     ```
     6>==7512==ERROR: AddressSanitizer: bad parameters to __sanitizer_annotate_contiguous_container:
      6>      beg     : 0x1240058202a1
      6>      end     : 0x1240058202b8
      6>      old_mid : 0x1240058202b1
      6>      new_mid : 0x1240058202a
     ```
     coming from `_Create_annotation` in something that's only called in SSO mode; this clearly is assuming
     that `_Small_string_always_aligned`, so `beg = _Bx._Buf`, `end = aligned_after(_Bx._Buf + 16)`.
     I don't know what to do here, given that it's a very fundamental bug in experimental generator.
- MSVC-ASAN-UnitTests-Private:
   + `Fuzzer_x86chk_*`: this found a bug! in `_Take_contents`, if `_Right` is large,
     we need to remove the asan annotations on the SSO buffer before copying from it.
     We should just not do the memcpy when `_INSERT_STRING_ANNOTATION` is turned on,
     like we already do in `_Swap_data`.
   + `AsanWindows_*_MT(d)`: looks like libconcrt is being built without `/fsanitize=address`
     and without `/D_ANNOTATE_VECTOR`; not sure what's going on here.
   + `AsanWindows_amd64chk_MD`: this was an issue with replacing `AddVectoredExceptionHandler`;
     not sure what went wrong here, but unrelated to my changes.
- MSVC-OSS-x86-All-Private-ASan:
   + assimp: looks like we found a bug in the project
   + azure-sdk-c: looks like a bug in project (also this is C, so almost certainly unrelated to my changes)
   + cpprestsdk: cpprestsdk incorrectly, intentionally, reads out of bounds in `win32_encryption::win32_encryption`.
   + glslang: dunno how this is happening, but it's unrelated to my changes.
   + libzmq: failure to allocate enough memory - unrelated
   + onnx: unrelated to my changes; access on stack
   + qt6: failed to build; misaligned global in moc - unrelated.
   + websocketpp: this is extremely weird; we're getting access failures when trying to read `_Aligned`, the local variable, in `_Apply_annotation`. I don't know how this could possibly be happening.

### TL;DR

The only concerning failures (to me) are:

- The `await` tests, which show that `co_await`'d variables are misaligned in experimental coroutines
- `Fuzzer_x86chk_*`: an actual bug, which is fixed in the latest commit.
- websocketpp: there is an issue where `_Apply_annotation` reading `_Aligned` is treated as out of bounds. This is extremely concerning and I don't know what to do with this.

**Comment by StephanTLavavej** [comment]
Thanks for analyzing the MSVC-PR results!

On GitHub, `GH_002030_asan_annotate_string` is failing for x64. As a reminder, please run updated tests locally before pushing changes. (Usually, running for x64 is sufficient, but given ASAN's alignment sensitivity, running for both x64 and x86 would be a good idea.)
 
This repros locally and running `python tests\utils\stl-lit\stl-lit.py C:\GitHub\STL\tests\std\tests\GH_002030_asan_annotate_string C:\GitHub\STL\tests\std\tests\GH_002030_asan_annotate_vector --order=random -o testing_x64.log` takes 3 minutes on my 8C/16T i7-10700 at work. (`--max-failures 1` stops after 40 seconds after finding the first failure.) `python C:\GitHub\STL\tools\scripts\print_failures.py testing_x64.log` can then be used to inspect the log.

**Comment by StephanTLavavej** [comment]
@strega-nil-ms is investigating an LTCG ICE found in MSVC-internal (prod/be) testing. Moving back to WIP until that's resolved. Thanks Nicole! :ice_cube: :cold_face: :snowboarder:

**Comment by strega-nil-ms** [comment]
I consider this ready for merging based on the MSVC testing!

File: stl/inc/xstring [hunk 54]
```diff
@@ -2527,91 +2462,83 @@ private:
...
-        }
-    }
+        // for the non-aligned buffer options, the buffer must always have size >= 9 bytes,
+        // so it will always end at least one shadow memory section.
 
-#define _ASAN_STRING_MODIFY(n)    _Modify_annotation((n))
-#define _ASAN_STRING_REMOVE(_Str) (_Str)._Remove_annotation()
-#define _ASAN_STRING_CREATE(_Str) (_Str)._Create_annotation()
+        _Asan_aligned_pointers _Aligned;
+        if constexpr (_Large_string_always_asan_aligned) {
```
Comment (amyw-msft) [inline stl/inc/xstring:2502]: This is essentially the same as what's in vector with the SSO stuff gone, but it's written differently (clamp is avoided in vector since everything happens under the if constexpr instead of setting _Aligned). Or am I missing something?

**Review by amyw-msft — APPROVED** [review]
LGTM after Open3d_amd64 passes :)

File: stl/inc/xstring (hunk 54 above)
Comment (strega-nil-ms) [reply stl/inc/xstring:2502]: yeah, I could rewrite the vector stuff to more closely follow the string stuff, if you like?

Comment (StephanTLavavej) [reply stl/inc/xstring:2502]: If the vector implementation is currently correct, I would prefer to see that changed in a followup PR, to avoid too much happening at once. (If the question were changing string to align more closely with vector, then that would be reasonable to do in this PR which is already changing string significantly.)

File: stl/inc/xstring [hunk 55]
```diff
@@ -3162,38 +3089,31 @@ private:
...
+
             _Traits::copy(_My_data._Bx._Buf, _Right_data._Bx._Buf, _Right_data._Mysize + 1);
+            _My_data._Myres  = _BUF_SIZE - 1;
+            _My_data._Mysize = _Right_data._Mysize;
+
             _Right_data._Orphan_all();
         }
 
-        _My_data._Mysize = _Right_data._Mysize;
-        _My_data._Myres  = _Right_data._Myres;
```
Comment (StephanTLavavej) [inline stl/inc/xstring:3196]: I'm unsure as to why these lines are being changed. (When `_Right_data` is small, `_Right_data._Myres` should be `_BUF_SIZE - 1` by definition.)

I believe that both forms are correct, but the original form probably has slightly better codegen.

**Review by StephanTLavavej — APPROVED** [review]

File: stl/inc/xstring [hunk 56]
```diff
@@ -2521,80 +2463,82 @@ private:
...
-    }
-
     static _CONSTEXPR20 void _Apply_annotation(const value_type* const _First, const size_type _Capacity,
         const size_type _Old_size, const size_type _New_size) noexcept {
 #if _HAS_CXX20
         if (_STD is_constant_evaluated()) {
             return;
         }
 #endif // _HAS_CXX20
+       // Don't annotate small strings; only annotate on the heap.
```
Comment (CaseyCarter) [inline stl/inc/xstring:2481]: Missing a space of indent.

File: stl/inc/xstring [hunk 57]
```diff
@@ -2521,80 +2463,82 @@ private:
...
+        if (_Capacity == _BUF_SIZE - 1) {
+            return;
+        }
 
         if (!_Asan_string_should_annotate) {
```
Comment (CaseyCarter) [inline stl/inc/xstring:2486]: We should combine this with the previous `if`.

File: stl/inc/xstring [hunk 58]
```diff
@@ -4392,8 +4330,10 @@ public:
         // exchange a string in large mode with one in small mode
         const pointer _Ptr = _Starts_large._Bx._Ptr;
         _Destroy_in_place(_Starts_large._Bx._Ptr);
+
         _Starts_large._Activate_SSO_buffer();
-        _Traits::copy(_Starts_large._Bx._Buf, _Starts_small._Bx._Buf, _BUF_SIZE);
+        _Traits::copy(_Starts_large._Bx._Buf, _Starts_small._Bx._Buf, _Starts_small._Mysize + 1);
```
Comment (CaseyCarter) [inline stl/inc/xstring:4335]: Are we intentionally removing the "copy the entire SSO buffer" microoptimization here?

File: tests/std/tests/GH_002030_asan_annotate_string/env.lst [hunk 59]
```diff
@@ -2,9 +2,9 @@
 # SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
 
 # This test matrix is the usual test matrix, with all currently unsupported options removed, crossed with the ASan flags.
-# TRANSITION, VSO-1350252
-# Due to a bug in the ASan libs using ASan with /MD or /MT requires IDL==0 and using /MDd or /MTd requires IDL==2.
-# clang-cl does not currently support targeting /MDd or /MTd.
+
+# TRANSITION, VSO-1350252 - due to vcasan.lib including the standard library, we can't use it (pending 17.5 preview 2).
+# TRANSITION, google/sanitizers#328 - clang-cl does not currently support targeting /MDd or /MTd.
```
Comment (CaseyCarter) [inline tests/std/tests/GH_002030_asan_annotate_string/env.lst:7]:
```suggestion
# TRANSITION, google/sanitizers#328 - clang-cl does not currently support targetting /MDd or /MTd.
```

File: tests/std/tests/GH_002030_asan_annotate_string/env.lst [hunk 60]
```diff
@@ -2,9 +2,9 @@
 # SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
 
 # This test matrix is the usual test matrix, with all currently unsupported options removed, crossed with the ASan flags.
-# TRANSITION, VSO-1350252
-# Due to a bug in the ASan libs using ASan with /MD or /MT requires IDL==0 and using /MDd or /MTd requires IDL==2.
-# clang-cl does not currently support targeting /MDd or /MTd.
+
+# TRANSITION, VSO-1350252 - due to vcasan.lib including the standard library, we can't use it (pending 17.5 preview 2).
```
Comment (CaseyCarter) [inline tests/std/tests/GH_002030_asan_annotate_string/env.lst:6]: Does "it" mean "the standard library" or "vcasan.lib"? Is this waiting for VSO-1350252 to be fixed, or for 17.5 preview 2 to release?

**Review by CaseyCarter — APPROVED** [review]
None of these comments should block merging; we can address any of them in a followup (if at all).

File: stl/inc/xstring [hunk 61]
```diff
@@ -2514,6 +2504,11 @@ private:
 #endif // _HAS_CXX17
 
 #ifdef _INSERT_STRING_ANNOTATION
+    // this is a function so we can get the alignment of the class while defining it.
```
[the remark this answers is not in the document]
Comment (CaseyCarter) [reply stl/inc/xstring]: Outdated.

File: tests/std/tests/GH_002030_asan_annotate_string/env.lst (hunk 59 above)
Comment (StephanTLavavej) [reply tests/std/tests/GH_002030_asan_annotate_string/env.lst:7]: One T is correct here.

File: stl/inc/xstring (hunk 58 above)
Comment (strega-nil-ms) [reply stl/inc/xstring:4335]: ah, this is a change from when SBO was annotated; it should probably be reverted.

File: tests/std/tests/GH_002030_asan_annotate_string/env.lst (hunk 60 above)
Comment (strega-nil-ms) [reply tests/std/tests/GH_002030_asan_annotate_string/env.lst:6]: vcasan.lib; this is waiting for whatever release fixed VSO-1350252.

File: stl/inc/xstring (hunk 58 above)
Comment (StephanTLavavej) [reply stl/inc/xstring:4335]: I can validate this change if you're too busy with non-STL work this week. (I would also like to try reverting https://github.com/microsoft/STL/pull/3164#discussion_r1044943528 .) I hope that wouldn't reset ASAN testing since these are non-ASAN-specific codepaths.

Comment (strega-nil-ms) [reply stl/inc/xstring:4335]: I can do so; the LKG stuff took _way_ less time than I expected (it was green without work, surprisingly).

**Review by CaseyCarter — APPROVED** [review]

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
Thanks for overhauling this machinery and helping users find bugs in their code! :heart_eyes_cat: :hammer_and_wrench: :sparkles:
