### PR TITLE
`<atomic>`: Add member `difference_type` to `atomic<void*>` and its friends

### LINKED ISSUE #4688: `<atomic>`: `atomic_ref<void*>` and `atomic<void*>` lack `difference_type`
While updating our libcxx test suite, I found that https://github.com/llvm/llvm-project/blob/af6812085cc7a7251a3095acbc96343ce660f135/libcxx/test/std/atomics/atomics.ref/member_types.pass.cpp is failing with:

```
error: no type named 'difference_type' in 'std::atomic_ref<void *>'
```

AFAICT, this happens because `atomic_ref`:

https://github.com/microsoft/STL/blob/63354c3fa9c1fb2ab1fccb58c47d23c6af1c290f/stl/inc/atomic#L2323-L2324

and `atomic`:

https://github.com/microsoft/STL/blob/63354c3fa9c1fb2ab1fccb58c47d23c6af1c290f/stl/inc/atomic#L2143-L2144

check for `is_pointer_v<_TVal> && is_object_v<remove_pointer_t<_TVal>>`:

https://github.com/microsoft/STL/blob/63354c3fa9c1fb2ab1fccb58c47d23c6af1c290f/stl/inc/atomic#L2128-L2141

Yet WG21-N4981 \[atomics.ref.pointer\] depicts:

```cpp
template<class T> struct atomic_ref<T*> {
private:
  T** ptr; // exposition only

public:
  using value_type = T*;
  using difference_type = ptrdiff_t;
```

and \[atomics.types.pointer\] depicts:

```cpp
template<class T> struct atomic<T*> {
  using value_type = T*;
  using difference_type = ptrdiff_t;
```

without making any special cases for `void*`.

### PR DESCRIPTION
**Pull request by frederick-vs-ja**
Fixes #4688.

It seems intentional that `atomic(_ref)<T*>` are SFINAE-friendly on atomic pointer arithmetic. So this PR adds another mediate base class to avoid breaking the SFINAE-friendliness.

Also updates the comments in `Dev11_0863628_atomic_compare_exchange/test.cpp` to cite WG21-N4981.

### CODE REVIEW

**Comment by cpplearner** [comment]
> It seems intentional that `atomic(_ref)<T*>` are SFINAE-friendly on atomic pointer arithmetic. So this PR adds another mediate base class to avoid breaking the SFINAE-friendliness.

I don't think that matches the standard, which uses "*Mandates*" ([\[atomics.types.pointer\]/5](http://eel.is/c++draft/atomics.types.pointer#5), [\[atomics.ref.pointer\]/3](http://eel.is/c++draft/atomics.ref.pointer#3)).

**Comment by cpplearner** [comment]
> It seems intentional that `atomic(_ref)<T*>` are SFINAE-friendly on atomic pointer arithmetic. So this PR adds another mediate base class to avoid breaking the SFINAE-friendliness.

I don't think that matches the standard, which uses "*Mandates*" ([\[atomics.types.pointer\]/5](http://eel.is/c++draft/atomics.types.pointer#5), [\[atomics.ref.pointer\]/3](http://eel.is/c++draft/atomics.ref.pointer#3)).

**Comment by frederick-vs-ja** [comment]
> > It seems intentional that `atomic(_ref)<T*>` are SFINAE-friendly on atomic pointer arithmetic. So this PR adds another mediate base class to avoid breaking the SFINAE-friendliness.
> 
> I don't think that matches the standard, which uses "_Mandates_" ([[atomics.types.pointer]/5](http://eel.is/c++draft/atomics.types.pointer#5), [[atomics.ref.pointer]/3](http://eel.is/c++draft/atomics.ref.pointer#3)).

_Mandates_ doesn't mean the ill-formedness shall be SFINAE-unfriendly, although we ususally use `static_assert`s or straightforward hard errors for it.

Previously, #4014 made _Mandates_ for `forward_like` SFINAE-friendly.

File: tests/std/tests/Dev11_0863628_atomic_compare_exchange/test.cpp [hunk 1]
```diff
@@ -553,6 +558,70 @@ void test_double_identical_results() {
...
 }
 
+// Also test GH-4688 "<atomic>: atomic_ref<void*> and atomic<void*> lack difference_type"
+template <class, class = void>
+constexpr bool atomic_has_member_difference_type = false;
+template <class T>
+constexpr bool atomic_has_member_difference_type<T, void_t<typename atomic<T>::difference_type>> = true;
+
+STATIC_ASSERT(
+    atomic_has_member_difference_type<signed char>&& is_same_v<atomic<signed char>::difference_type, signed char>);
```
Comment (StephanTLavavej) [inline tests/std/tests/Dev11_0863628_atomic_compare_exchange/test.cpp:568]: There's no need to positively test `atomic_has_member_difference_type`, which greatly increases verbosity here. Mentioning `atomic<MEOW>::difference_type` will already verify its existence.

File: tests/std/tests/P0019R8_atomic_ref/test.cpp [hunk 2]
```diff
@@ -40,6 +40,80 @@ struct int128 {
...
+              && std::is_same_v<std::atomic_ref<volatile void*>::difference_type, std::ptrdiff_t>);
+static_assert(atomic_ref_has_member_difference_type<const volatile void*>
+              && std::is_same_v<std::atomic_ref<const volatile void*>::difference_type, std::ptrdiff_t>);
+static_assert(atomic_ref_has_member_difference_type<void (*)()>
+              && std::is_same_v<std::atomic_ref<void (*)()>::difference_type, std::ptrdiff_t>);
+static_assert(atomic_ref_has_member_difference_type<bigint (*)(int128)>
+              && std::is_same_v<std::atomic_ref<bigint (*)(int128)>::difference_type, std::ptrdiff_t>);
+
+static_assert(!atomic_ref_has_member_difference_type<bool>);
+static_assert(!atomic_ref_has_member_difference_type<nullptr_t>);
```
Comment (StephanTLavavej) [inline tests/std/tests/P0019R8_atomic_ref/test.cpp:113]: This should be `std::nullptr_t`.

File: tests/std/tests/Dev11_0863628_atomic_compare_exchange/test.cpp [hunk 3]
```diff
@@ -553,6 +558,70 @@ void test_double_identical_results() {
...
+STATIC_ASSERT(atomic_has_member_difference_type<char16_t>&& is_same_v<atomic<char16_t>::difference_type, char16_t>);
+STATIC_ASSERT(atomic_has_member_difference_type<char32_t>&& is_same_v<atomic<char32_t>::difference_type, char32_t>);
+STATIC_ASSERT(atomic_has_member_difference_type<wchar_t>&& is_same_v<atomic<wchar_t>::difference_type, wchar_t>);
+
+#if _HAS_CXX20 // P0020R6 Floating Point Atomic
+STATIC_ASSERT(atomic_has_member_difference_type<float>&& is_same_v<atomic<float>::difference_type, float>);
+STATIC_ASSERT(atomic_has_member_difference_type<double>&& is_same_v<atomic<double>::difference_type, double>);
+STATIC_ASSERT(
+    atomic_has_member_difference_type<long double>&& is_same_v<atomic<long double>::difference_type, long double>);
+#else // _HAS_CXX20 / !_HAS_CXX20
```
Comment (StephanTLavavej) [inline tests/std/tests/Dev11_0863628_atomic_compare_exchange/test.cpp:596]: This should be an arrow comment.

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Thanks for the quick fix and comprehensive test coverage, this is great! :heart_eyes_cat:

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
Thanks for making a difference! :joy_cat: :zany_face: :green_heart:

**Comment by frederick-vs-ja** [comment]
😹Well, we should partially revert this for `atomic_ref<NonObject*>` due to [P3323R1](https://wg21.link/P3323R1). Although `atomic<NonObject*>` should still have `difference_type`.
