### PR TITLE
<filesystem>: create_directories() throw for empty paths

### LINKED ISSUE #1283: <filesystem>: create_directories() should throw for empty paths
Reported by Ville Voutilainen:

```
C:\Temp>type meow.cpp
```
```cpp
#include <filesystem>
#include <iostream>
using namespace std;
using namespace std::filesystem;

int main() {
    cout << boolalpha;

    const path p{};

    try {
        const bool result = create_directories(p);

        cout << "create_directories returned " << result << ".\n";
    } catch (const filesystem_error& e) {
        cout << "create_directories threw " << e.what() << ".\n";
    }
}
```
```
C:\Temp>cl /EHsc /nologo /W4 /std:c++17 /MTd meow.cpp && meow
meow.cpp
create_directories returned false.
```

This behavior differs from libstdc++ on Compiler Explorer:
```
create_directories threw filesystem error: cannot create directories: Invalid argument [].
```

And from libc++ on Compiler Explorer:
```
create_directories threw filesystem error: in create_directory: No such file or directory [""].
```

### PR DESCRIPTION
**Pull request by Arzaghi**
Fixes #1283

### CODE REVIEW

File: stl/inc/filesystem [hunk 1]
```diff
@@ -3750,6 +3750,10 @@ namespace filesystem {
 
     // FUNCTION create_directories
     inline bool create_directories(const path& _Path, error_code& _Ec) {
+        if (_Path.empty()) {
+            _Throw_fs_error("create_directories", _Make_ec(__std_win_error::_Invalid_parameter), _Path);
```
Comment (MattStephanson) [inline stl/inc/filesystem:3754]: Filesystem functions that have an `error_code` argument should usually use that to indicate errors, rather than throwing. See [N4861](https://wg21.link/n4861) [fs.err.report].

Comment (Arzaghi) [reply stl/inc/filesystem]: Thanks. That's right. also I chose `__std_win_error::_Path_not_found` as the thrown error and also as the `error_code` just to make it consistent with the `create_directory` behavior on the same input. Please let me know if it's not the right choice.

Comment (MattStephanson) [reply stl/inc/filesystem]: Looks good to me.

File: tests/std/tests/P0218R1_filesystem/test.cpp [hunk 2]
```diff
@@ -3570,6 +3570,7 @@ void test_temp_directory_path() {
 void test_create_directory() {
     const test_temp_directory tempDir("create_directory"sv);
     const path p = tempDir.directoryPath / L"__std.c++17.filesystem.create_directory"sv;
+    const path emptyPath{};
```
Comment (CaseyCarter) [inline tests/std/tests/P0218R1_filesystem/test.cpp:3573]: If we don't need an lvalue for any reason, I think `path{}` is even more clearly and readably an empty path than is `emptyPath`. Why not simply use `path{}`?

File: tests/std/tests/P0218R1_filesystem/test.cpp [hunk 3]
```diff
@@ -3608,6 +3609,17 @@ void test_create_directory() {
         }
     }
 
+    // test empty path
```
Comment (CaseyCarter) [inline tests/std/tests/P0218R1_filesystem/test.cpp:3612]: A few general comments:
1. This is in the middle of function `test_create_directory` (which primarily tests `std::fs::create_directory`), I think the following function `test_create_dirs_and_remove_all` (which primarily tests `std::fs::create_directories` and `std::fs::remove_all`) would be a better place.
1. Since we're adding this test case in response to a bug report, we'd conventionally include the bug# and a brief description in the comment (as on line 3623 below). I'd expect to see something about GH-1283 here.
1. Using the `EXPECT` machinery would better integrate this test case with the rest of the test, which also generally tests both throwing and non-throwing paths. Something like:
```c++
EXPECT(create_directories(path{}, ec) == false);
EXPECT(bad(ec));
EXPECT(throws_filesystem_error([] { create_directories(path{}); }, "create_directories", path{});
```
should do the job.

**Review by CaseyCarter — CHANGES_REQUESTED** [review]
Sorry for the slow review: I'm picking up `<filesystem>` since @BillyONeal left, and the spec for this function in particular is, erm, not great.

**Comment by BillyONeal** [comment]
> since @BillyONeal left

That guy is such a traitor

**Comment by CaseyCarter** [comment]
> > since @BillyONeal left
> 
> That guy is such a traitor

ikr?

File: tests/std/tests/P0218R1_filesystem/test.cpp (hunk 3 above)
Comment (Arzaghi) [reply tests/std/tests/P0218R1_filesystem/test.cpp]: I'm sorry. It seems I was too careless about these tests.

**Review by CaseyCarter — APPROVED** [review]

**Review by StephanTLavavej — APPROVED** [review]
Looks good to me, and `__std_win_error::_Path_not_found` seems to be a reasonable error to return (among the various constants we have). Thanks for fixing this!

**Comment by StephanTLavavej** [comment]
Thanks for fixing this bug and helping the STL stay on the path to conformance! :rocket:
