### PR TITLE
Remove attempt to use tzcnt as bsf

### LINKED ISSUE #2330: <bit>: `countr_one(uint8) != 0` bad codegen on x86/x64
Originally reported as DevCom-1578571 by Jörn Heusipp.

> VS2022 cl 19.30.30705 generates non-universally-available tzcnt instruction for expression `std::countr_one(static_cast<unsigned char>(0b11111110)) != 0`
> 
> minimal test case:
> 
> ```cpp
> #include <bit>
> bool fail() {
> 	return std::countr_one(static_cast<unsigned char>(0b11111110)) != 0;
> }
> ```
> The problem can be seen in the asm output of the attached file `fail.cpp` in `fail.cod` when built with `cl.exe /c /O2 /W4 /std:c++20 /FAcu /arch:IA32 fail.cpp` (as done by running `compile_and_run.cmd`). (see [test.zip](https://aka.ms/dc/file?name=Bb3bf2a2743b74ad880967877243e592e637721457220993680_test.zip&tid=b3bf2a2743b74ad880967877243e592e637721457220993680) )
> 
> MSVC generates `bool fail()` as (comments removed)
> 
> ```
> ?fail@@YA_NXZ PROC					; fail, COMDAT
>   00000	51		 push	 ecx
>   00001	b8 01 ff ff ff	 mov	 eax, -255		; ffffff01H
>   00006	f3 0f bc c0	 tzcnt	 eax, eax
>   0000a	0f 95 c0	 setne	 al
>   0000d	59		 pop	 ecx
>   0000e	c3		 ret	 0
> ?fail@@YA_NXZ ENDP					; fail
> ```
> which uses the `tzcnt` instruction.
> 
> The `tzcnt` instruction is part of the “BMI1” x86 instruction set extensions (see https://www.felixcloutier.com/x86/tzcnt) which cannot be assumed to be universally available, especially not when compiling x86 32bit code with `/arch:IA32`.
> 
> In case of CPUs that do not implement `tzcnt` it is documented as falling back to `bsf` (https://www.felixcloutier.com/x86/bsf) by the CPU. Especially notice the different semantics regarding setting the zero flag (ZF).
> 
> On my Intel Sandy Bridge (i7-3930K) where “BMI1” is not present in the cpuid feature flags, the generated code causes `tzcnt` (interpreted as `bsf`) to not set `ZF`, which causes `setne` to set `al` to 1, which is the wrong result.
> 
> The same problem is also reproducible on an Intel Xeon E5-2697 v2 (Ivy Bridge) and an AMD Phenom X4 9650 (K10), which also do not support `BMI1`. Wikipedia agrees (https://en.wikipedia.org/wiki/X86_Bit_manipulation_instruction_set#Supporting_CPUs).
> 
> `compile_and_run.cmd` (in a VS2022 x86 prompt) should output `fail` on systems without `BMI1` and `ok` on systems with `BMI1`.
> 
> Note that MSVC also generates `tzcnt` on amd64 where it is also not generally available, certainly not when targetting only SSE2, so this bug does affects both, x86 and amd64 code generation.
> 
> AVX extensions also do not imply BMI1 extensions availability. I have not researched whether AVX2 implies BMI1 on all known hardware.
> 
> The bug was originally triggered by the libopenmpt (https://lib.openmpt.org/) unit tests (https://github.com/OpenMPT/openmpt/blob/master/build/vs2022win10/libopenmpt_test.sln “Release”) when built with VS2022 in C++20 mode (see https://github.com/OpenMPT/openmpt/blob/master/src/mpt/base/bit.hpp#L185) targetting x86 or amd64. See https://github.com/OpenMPT/openmpt/blob/master/src/mpt/base/tests/tests_base_bit.hpp#L163, where it triggers failures in multiple test cases on a Sandy Bridge CPU.
> 
> Additional reference: https://www.intel.com/content/dam/www/public/us/en/documents/manuals/64-ia-32-architectures-software-developer-instruction-set-reference-manual-325383.pdf.

https://godbolt.org/z/aPjnojjcx. Note how the compiler makes use of ZF in `compare_0`. `tzcnt` sets ZF when the _result_ is 0, but `bsf` sets ZF when the _input_ is 0.

### PR DESCRIPTION
**Pull request by AlexGuteniev**
Resolves #2330
Fixes VSO-1434895/AB#1434895.

### CODE REVIEW

**Review by barcharcraz — APPROVED** [review]
How different is the codegen between the bsf version and the tzcnt version?

This is kinda pre-existing but we should do some benchmarks to determine if it's even worth doing the tzcnt version if we need to dynamically check for it.

**Comment by AlexGuteniev** [comment]
> but we should do some benchmarks to determine if it's even worth doing the tzcnt version if we need to dynamically check for it. 

We'll track this as #2133

**Comment by AlexGuteniev** [comment]
> How different is the codegen between the bsf version and the tzcnt version?

Remember bsf requires a branch for zero input

**Comment by AlexGuteniev** [comment]
@StephanTLavavej no, this wasn't really caused by #1540. Maybe some specific case was caused by #1540, but the bug was always there since `counr_zero` implementation.

File: stl/inc/limits [hunk 1]
```diff
@@ -1111,6 +1111,8 @@ _NODISCARD int _Countr_zero_bsf(const _Ty _Val) noexcept {
         const unsigned int _High = _Val >> 32;
         if (!_BitScanForward(&_Result, _High)) {
             return _Digits;
+        } else {
+            return static_cast<int>(_Result + 32);
```
Comment (barcharcraz) [inline stl/inc/limits:1115]: ummm, doesn't this break on anything lower than UI32_MAX-1

**Comment by StephanTLavavej** [comment]
@AlexGuteniev Thanks, I was confused! I've restored your PR description.

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

File: tests/std/tests/GH_001103_countl_zero_correctness/test.cpp [hunk 2]
```diff
@@ -42,27 +42,27 @@ int main() {
 
     assert(_Countr_zero_bsf(static_cast<unsigned char>(0x00)) == 8);
     assert(_Countr_zero_bsf(static_cast<unsigned char>(0x13)) == 0);
-    assert(_Countr_zero_bsf(static_cast<unsigned char>(0x82)) == 1);
+    assert(_Countr_zero_bsf(static_cast<unsigned char>(0x80)) == 7);
     assert(_Countr_zero_bsf(static_cast<unsigned char>(0xF8)) == 3);
 
     assert(_Countr_zero_bsf(static_cast<unsigned short>(0x0000)) == 16);
     assert(_Countr_zero_bsf(static_cast<unsigned short>(0x0013)) == 0);
-    assert(_Countr_zero_bsf(static_cast<unsigned short>(0x8002)) == 1);
```
Comment (barcharcraz) [inline tests/std/tests/GH_001103_countl_zero_correctness/test.cpp]: why remove these tests? Instead of just adding the additional tests for large suffixes

**Review by barcharcraz — CHANGES_REQUESTED** [review]

File: tests/std/tests/GH_001103_countl_zero_correctness/test.cpp (hunk 2 above)
Comment (AlexGuteniev) [reply tests/std/tests/GH_001103_countl_zero_correctness/test.cpp]: I don't think it adds much coverage, as we have ` == 3` tests

Comment (AlexGuteniev) [reply tests/std/tests/GH_001103_countl_zero_correctness/test.cpp]: Discussed: we'll have another PR to fix tests to keep this PR mirrored as it is.

**Review by barcharcraz — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Thanks for investigating and fixing this bug! :lady_beetle: :zero: :one:

**Comment by AlexGuteniev** [comment]
> Fixed a bug affecting older CPUs where the STL generated the newer tzcnt instruction instead of the fallback bsf instruction. This affected <bit>'s countr_zero() and countr_one(), <numeric>'s gcd() and lcm(), and vector<bool>'s optimized implementations of find() and relational/spaceship operators. #2333

This is too aggressive. I mean probably gcd and lcm and vector<bool> are fine. For this bug to manifest we would need to _immediately compare the result against zero_. See @statementreply 's demo: https://godbolt.org/z/aPjnojjcx

I would have said "This affected <bit>'s countr_zero() and countr_one(), and _potentially_ ..."
