### PR TITLE
`<regex>`: `regex_traits::transform_primary` should yield primary sort keys appropriate for the imbued locale

### LINKED ISSUE #5291: LWG-4186 `regex_traits::transform_primary` mistakenly detects `typeid` of a function
LWG-4186 `regex_traits::transform_primary` mistakenly detects `typeid` of a function

### LINKED ISSUE #5435: `<regex>`: Equivalence classes have unexpected behavior with `std::wregex`
Repros with VS 2022 17.14 Preview 4 with microsoft/STL `main`, including #5392. Tracked by internal VSO-127463 / AB#127463 , originally reported by an external user through the defunct Microsoft Connect site on 2015-06-02.

```
C:\Temp>type meow.cpp
```
```cpp
#include <locale>
#include <print>
#include <regex>
#include <string>
using namespace std;

[[nodiscard]] string escape_wide(const wstring& wstr) {
    string ret{R"(L")"};
    for (const auto& wch : wstr) {
        ret += format(R"(\x{:x})", static_cast<unsigned short>(wch));
    }
    ret += R"(")";
    return ret;
}

void display_result(const wstring& wstr, const wstring& pattern) {
    const locale loc{"fr-FR"};

    wregex rgx;
    rgx.imbue(loc);
    rgx.assign(pattern, regex_constants::icase | regex_constants::collate);

    const bool result = regex_match(wstr, rgx);

    regex_traits<wchar_t> tr;
    tr.imbue(loc);
    const wstring primary_sort_key = tr.transform_primary(wstr.begin(), wstr.end());

    println("wstr: {}; result: {:>5}; primary_sort_key: {}", escape_wide(wstr), result, escape_wide(primary_sort_key));
}

int main() {
    display_result(L"E", L"[[=e=]]");
    display_result(L"\u00C8", L"[[=e=]]"); // LATIN CAPITAL LETTER E WITH GRAVE
    display_result(L"\u00C9", L"[[=e=]]"); // LATIN CAPITAL LETTER E WITH ACUTE
    display_result(L"\u00CA", L"[[=e=]]"); // LATIN CAPITAL LETTER E WITH CIRCUMFLEX

    display_result(L"e", L"[[=e=]]");
    display_result(L"\u00E8", L"[[=e=]]"); // LATIN SMALL LETTER E WITH GRAVE
    display_result(L"\u00E9", L"[[=e=]]"); // LATIN SMALL LETTER E WITH ACUTE
    display_result(L"\u00EA", L"[[=e=]]"); // LATIN SMALL LETTER E WITH CIRCUMFLEX
}
```
```
C:\Temp>cl /EHsc /nologo /W4 /std:c++latest /MTd /Od meow.cpp && meow
meow.cpp
wstr: L"\x45"; result:  true; primary_sort_key: L"\xe\x21\x1\x1\x1\x1\x0"
wstr: L"\xc8"; result: false; primary_sort_key: L"\xe\x21\x1\xf\x1\x1\x1\x0"
wstr: L"\xc9"; result: false; primary_sort_key: L"\xe\x21\x1\xe\x1\x1\x1\x0"
wstr: L"\xca"; result: false; primary_sort_key: L"\xe\x21\x1\x12\x1\x1\x1\x0"
wstr: L"\x65"; result:  true; primary_sort_key: L"\xe\x21\x1\x1\x1\x1\x0"
wstr: L"\xe8"; result: false; primary_sort_key: L"\xe\x21\x1\xf\x1\x1\x1\x0"
wstr: L"\xe9"; result: false; primary_sort_key: L"\xe\x21\x1\xe\x1\x1\x1\x0"
wstr: L"\xea"; result: false; primary_sort_key: L"\xe\x21\x1\x12\x1\x1\x1\x0"
```

The user expects `regex_match` to always return `true` here.

I don't understand why [`LCMapStringEx`](https://learn.microsoft.com/en-us/windows/win32/api/winnls/nf-winnls-lcmapstringex) with `LCMAP_SORTKEY` is producing these primary sort keys. Are we supposed to be passing extra flags to ignore diacritics?

### PR DESCRIPTION
**Pull request by muellerj2**
Fixes #5435. Fixes #5291.

The actual work is done in two new functions `__std_regex_transform_primary_char/wchar_t`, which are basically 1:1 copies of `_Strxfrm()` and `_Wcsxfrm()` but pass different flags to `__crtLCMapStringA/W`. I also took the liberty to correct the SAL annotations.

`__crtLCMapStringA/W` are declared in `awint.hpp` which includes `yvals.h`. I'm uncertain if this is the best approach, but I undefined `_ENFORCE_ONLY_CORE_HEADERS` so that `awint.hpp` can be included.

`transform_primary` has to check the types of the collate facets using RTTI, so I made the function always returns an empty string when dynamic RTTI is disabled/`_CPPRTTI` is undefined. The implementation itself is heavily based on `collate::do_transform` (including the change in #5431). It also needs access to the internals of `collate`, so I made `_Regex_traits` a friend of it.

There is a behavior change for the C locale: As I explained in more detail in #5435, the traits requirement in [\[re.req\]/20](https://eel.is/c++draft/re.req#20) is actually misleading, since it is wrong for precisely one locale: the C locale (or the POSIX locale, see the collation order definition here: https://pubs.opengroup.org/onlinepubs/9799919799/basedefs/V1_chap07.html#tag_07_03_02_06). Since the equivalence classes are derived from POSIX and the definition of `regex_traits::transform_primary` also alludes to "primary sort keys" which indirectly reference terminology from the POSIX standard (https://pubs.opengroup.org/onlinepubs/9799919799/basedefs/V1_chap07.html#tag_07_03_02), I think we should do as POSIX says: "A" should not match `[[=a=]]`.

This has consequences:
* When I implemented #5392, I assumed [\[re.req\]/20](https://eel.is/c++draft/re.req#20), so I didn't add any character translation using `translate` and `translate_nocase` when parsing equivalences. Now we have to add such logic in `_Parser::_Do_ex_class2` to handle potentially case-sensitive sort keys when case-insensitive regexes are used (else "A" would even fail to match `[[=A=]]`).
* A number of test cases (some of my own making) failed, because they all assumed that lower and upper case characters are equivalent in the C locale.

Since matching and parsing of equivalences no longer go through `collate::transform`, related tests no longer have to be skipped under IDL mismatch.

### CODE REVIEW

File: stl/src/regex.cpp [hunk 1]
```diff
@@ -0,0 +1,124 @@
...
+#include <clocale>
+#include <crtdefs.h>
+#include <cstdlib>
+#include <cstring>
+#include <internal_shared.h>
+
+#include <Windows.h>
+
+#undef _ENFORCE_ONLY_CORE_HEADERS
+#include "awint.hpp"
```
Comment (AlexGuteniev) [inline stl/src/regex.cpp:14]: I'm sure this is fine. But I think it would be a good idea to include SCARY COMMENT here and into `awint.hpp`.
Search for "MAJOR LIMITATIONS" to find the existing instances of it.

Comment (frederick-vs-ja) [reply stl/src/regex.cpp:18]: Given this should be fine, is it possible to make `awint.hpp` itself suitable for core-ness?

Comment (muellerj2) [reply stl/src/regex.cpp:18]: Maybe. I think the header includes `yvals.h` only for `_CRTIMP2`.

File: tests/libcxx/expected_results.txt [hunk 2]
```diff
@@ -830,7 +830,6 @@ std/re/re.alg/re.alg.search/basic.pass.cpp FAIL
 std/re/re.alg/re.alg.search/ecma.pass.cpp FAIL
 std/re/re.alg/re.alg.search/extended.pass.cpp FAIL
 std/re/re.traits/lookup_collatename.pass.cpp FAIL
-std/re/re.traits/transform_primary.pass.cpp FAIL
```
Comment (muellerj2) [inline tests/libcxx/expected_results.txt:833]: This test actually passes now, but it is skipped as "unsupported" because of

```cpp
// REQUIRES: locale.cs_CZ.ISO8859-2
```

I honestly don't really know how the test harness works. What do we have to change to make this test run? The "cs_CZ" locale is available to us.

In other news, I think all remaining "not analyzed" regex failures are due to #5393 with probably one exception: the failing match_prev_avail test (which, I have to admit, I haven't looked into myself yet).

Comment (StephanTLavavej) [reply tests/libcxx/expected_results.txt:833]: I thought this was supposed to be taken care of by https://github.com/microsoft/STL/blob/8e9f4ee42faec6931a09bc6c1ef018cef712e52a/tests/utils/stl/test/features.py#L32-L45 but I don't totally understand all of the machinery.

Comment (muellerj2) [reply tests/libcxx/expected_results.txt:833]: Ah, I think I have figured out what the problem is.

The government of the Czech Republic asked a couple of years ago that the country should be called "Czechia" in English. And I just tested that: When I use "Czech_Czech Republic.1250", `setlocale()` fails, but it succeeds for "Czech_Czechia.1250".

So "Czech_Czechia.1250" has to be added to the alternate names.

File: stl/src/regex.cpp [hunk 3]
```diff
@@ -0,0 +1,128 @@
...
+
+            if (size == 0) {
+                // buffer not big enough, get size required.
+                size = __crtLCMapStringW(locale_name,
+                    LCMAP_SORTKEY | LINGUISTIC_IGNORECASE | LINGUISTIC_IGNOREDIACRITIC | NORM_IGNOREKANATYPE
+                        | NORM_IGNOREWIDTH,
+                    string2, static_cast<int>(n2), nullptr, 0);
+
+                if (size == 0) {
+                    size = INT_MAX; // default error
```
Comment (StephanTLavavej) [inline stl/src/regex.cpp:114]: `INT_MAX` was a bug fixed by #5431, right? The header here is checking `if (_Count == static_cast<size_t>(-1)) {` so I'm 99.9% sure we need to change this.

File: tests/std/tests/GH_005204_regex_collating_ranges/test.cpp [hunk 4]
```diff
@@ -535,36 +535,100 @@ void test_gh_994() {
...
-    g_regexTester.should_match("AaAabcaAaad", "[[=a=]bc]*d");
-#endif // !defined(SKIP_COLLATE_TESTS)
+    g_regexTester.should_not_match("AaAabcaAaad", "[[=a=]bc]*d");
+    g_regexTester.should_match("AaAaaAaab", "[[=a=]]*b", icase);
+    g_regexTester.should_not_match("AaAaaAaab", "[[=a=]]*c", icase);
+    g_regexTester.should_match("AaAabcaAaad", "[[=a=]bc]*d", icase);
+}
+
+void test_gh_5435() {
+    // GH-5345: <regex>: Equivalence classes have unexpected behavior with std::wregex
```
Comment (StephanTLavavej) [inline tests/std/tests/GH_005204_regex_collating_ranges/test.cpp:595]: Digit transposition in the comment.

File: tests/std/tests/GH_005204_regex_collating_ranges/test.cpp [hunk 5]
```diff
@@ -535,36 +535,100 @@ void test_gh_994() {
...
+        test_wregex_locale eq_e_regex(&g_regexTester, L"^[[=e=]]*b$", "en-US");
+        eq_e_regex.should_search_match(L"e\u00c8Eb", L"e\u00c8Eb"); // U+00C8 LATIN CAPITAL LETTER E WITH GRAVE
+        eq_e_regex.should_search_fail(L"eb\u00c8Eb"); // U+00C8 LATIN CAPITAL LETTER E WITH GRAVE
+        eq_e_regex.should_search_match(L"e\u00e8Eb", L"e\u00e8Eb"); // U+00E8 LATIN SMALL LETTER E WITH GRAVE
+        eq_e_regex.should_search_match(L"e\u00c9Eb", L"e\u00c9Eb"); // U+00C9 LATIN CAPITAL LETTER E WITH ACUTE
+        eq_e_regex.should_search_match(L"e\u00e9Eb", L"e\u00e9Eb"); // U+00E9 LATIN SMALL LETTER E WITH ACUTE
+        eq_e_regex.should_search_match(L"e\u00caEb", L"e\u00caEb"); // U+00CA LATIN CAPITAL LETTER E WITH CIRCUMFLEX
+        eq_e_regex.should_search_match(L"e\u00eaEb", L"e\u00eaEb"); // U+00EA LATIN SMALL LETTER A WITH CIRCUMFLEX
+        eq_e_regex.should_search_match(L"e\u00cbEb", L"e\u00cbEb"); // U+00CB LATIN CAPITAL LETTER E WITH DIAERESIS
+        eq_e_regex.should_search_match(L"e\u00ebEb", L"e\u00ebEb"); // U+00EB LATIN SMALL LETTER A WITH DIAERESIS
```
Comment (StephanTLavavej) [inline tests/std/tests/GH_005204_regex_collating_ranges/test.cpp:622]: "SMALL LETTER A" copy-paste issues here.

File: tests/libcxx/expected_results.txt (hunk 2 above)
Comment (StephanTLavavej) [reply tests/libcxx/expected_results.txt:833]: Excellent! If that's always the name in the latest versions of Win11 / Server 2025, we should change it instead of keeping the old name.

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Thanks! :heart_eyes_cat: I pushed some fixes, the most significant being `INT_MAX`, please double-check.

:warning: Note to self: I'll need to perform MSVC-internal changes to add the new file `regex.cpp`, and I will likely need to push changes to deal with `/clr:pure`.

File: tests/libcxx/expected_results.txt (hunk 2 above)
Comment (StephanTLavavej) [reply tests/libcxx/expected_results.txt:833]: I'll create a PR for this change, this part of the test code needs a minor cleanup.

Comment (StephanTLavavej) [reply tests/libcxx/expected_results.txt:833]: Done: #5480

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
As foretold by the ancient prophecy, I had to push a commit to fix `/clr:pure`.

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I resolved a trivial adjacent-add conflict with #5437 in `GH_005204_regex_collating_ranges`.

**Comment by StephanTLavavej** [comment]
Thanks for implementing this new LWG issue and fixing this ancient bug! :black_cat: :green_heart: :tada:
