### PR TITLE
`constexpr` `mutex` constructor

### LINKED ISSUE #2285: <mutex> : std::mutex::mutex is not constexpr
This is mentioned in other issues, but I wanted a bug report tracking this explicitly. For the curious see #946.

`std::mutex::mutex` is `constexpr` as of c++11, but even in c++17 MSVC will not support it.
Minimal repro:
https://godbolt.org/z/5Yc56hEG7
```c++
#include <mutex>

struct S {
    constexpr S() noexcept = default;
    std::mutex m_mutex;
};

static constexpr S s{};
```

### PR DESCRIPTION
**Pull request by cpplearner**
Fixes #2285.

~Because this might cause problem in complicated (and formally forbidden) scenarios (see discussion in #3770), I chose to make this opt-in via the `_USE_CONSTEXPR_MUTEX_CONSTRUCTOR` macro. If `_USE_CONSTEXPR_MUTEX_CONSTRUCTOR` is not defined, `mutex` will call `_Mtx_init_in_situ` as before.~

~For the same reason, I changed `stl_critical_section_win7` and `stl_condition_variable_win7` back to polymorphic classes, even though their vptrs are no longer accessed. (If `_USE_CONSTEXPR_MUTEX_CONSTRUCTOR` is defined, no `stl_critical_section_win7` object will be created.)~

### CODE REVIEW

File: tests/std/tests/VSO_0226079_mutex/test.cpp [hunk 1]
```diff
@@ -468,6 +468,17 @@ void test_vso_1253916() {
...
+#ifdef _USE_CONSTEXPR_MUTEX_CONSTRUCTOR
+    struct test_type {
+        constexpr test_type() {}
+        mutex mtx;
+    };
+
+    test_type obj;
+#endif // _USE_CONSTEXPR_MUTEX_CONSTRUCTOR
+}
+
```
Comment (frederick-vs-ja) [inline tests/std/tests/VSO_0226079_mutex/test.cpp:481]: Should we also test `constinit`?

File: stl/inc/mutex [hunk 2]
```diff
@@ -31,37 +31,20 @@ _STD_BEGIN
...
-
 class _Mutex_base { // base class for all mutex types
 public:
+#ifdef _USE_CONSTEXPR_MUTEX_CONSTRUCTOR
+    constexpr _Mutex_base(int _Flags = 0) noexcept {
+        _Mtx_storage._Critical_section = {};
+        _Mtx_storage._Thread_id        = -1;
+        _Mtx_storage._Type             = _Flags | _Mtx_try;
+        _Mtx_storage._Count            = 0;
+    }
```
Comment (frederick-vs-ja) [inline stl/inc/mutex:42]: It seems to me that this definition is only well-formed since C++20 (WG21-P1331R2) (although I have no idea why MSVC and Clang accept this).
Likewise, changing the active member of a union is permitted in constant evaluation only since C++20 (WG21-P1330R0).

Perhaps the constant initialization can only be performed in C++20 mode and later due to the current implementation. Strangely, given `mutex` is not made a literal type and thus we can't define a `constexpr` `mutex` variable, IIUC we can't assert the constant initialization until C+20.

**Comment by StephanTLavavej** [comment]
This change is much more complicated than I hoped to see - in particular, I don't understand why we would need to make the implementation polymorphic again. The only "punching through" we identified was the count (outside of the aligned storage, so polymorphicness is irrelevant), `native_handle()` (which we do not believe was used in practice outside our superficial test suite, and is now `=delete`d so if users upgrade their headers they'll notice), and now `constexpr` construction (and with an escape hatch, I don't think we need to be concerned about the "print driver" scenario of new headers with an old DLL that is technically forbidden by MSDN).

I think this should be opt-out and that we should keep the null vptr placeholder approach from #3770.

File: stl/inc/mutex (hunk 2 above)
Comment (frederick-vs-ja) [reply stl/inc/mutex:42]: `[[clang::require_constant_initialization]]` may be helpful.

File: stl/inc/mutex [hunk 3]
```diff
@@ -110,23 +93,16 @@ private:
     friend condition_variable;
     friend condition_variable_any;
 
-    union {
-        _Aligned_storage_t<_Mtx_internal_imp_size, _Mtx_internal_imp_alignment> _Mtx_storage;
-        _Mtx_internal_imp_mirror _Mtx_storage_mirror;
-    };
+    _Mtx_internal_imp_t _Mtx_storage{};
 
     _Mtx_t _Mymtx() noexcept { // get pointer to _Mtx_internal_imp_t inside _Mtx_storage
```
Comment (StephanTLavavej) [inline stl/inc/mutex:98]: Nitpick: This function comment has outlived its usefulness and is no longer particularly accurate - we should just remove it.

File: stl/inc/xthreads.h [hunk 4]
```diff
@@ -25,40 +26,64 @@ struct _Thrd_t { // thread identifier for Win32
     _Thrd_id_t _Id;
 };
 
-// Size and alignment for _Mtx_internal_imp_t and _Cnd_internal_imp_t
+using _Smtx_t = void*;
+
+struct _Stl_critical_section {
+    void* _Unused       = nullptr;
```
Comment (StephanTLavavej) [inline stl/inc/xthreads.h:32]: I think we should keep `// TRANSITION, ABI: was the vptr` here.

File: stl/src/primitives.hpp [hunk 5]
```diff
@@ -71,26 +43,23 @@ namespace Concurrency {
...
-            new (p) stl_critical_section_win7;
+        // TRANSITION, only used when constexpr mutex constructor is not enabled
+        inline void create_stl_critical_section(void* p) {
+            new (p) _Stl_critical_section;
         }
 
-        inline void create_stl_condition_variable(stl_condition_variable_win7* p) {
+        inline void create_stl_condition_variable(void* p) {
             new (p) stl_condition_variable_win7;
         }
```
Comment (StephanTLavavej) [inline stl/src/primitives.hpp:53]: Changing these parameter types to be `void*` doesn't appear to be necessary, and slightly weakens type safety. (This is only used in `stl/src` so we don't need to worry about `new (p)` selecting something other than True Placement New, that's why aren't globally qualifying it either.)

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Thanks, this looks great! I pushed extremely minor changes.

Having thought about this extensively during the previous PR, I think that this change is correct and safe, and it's a good simplification too.

File: stl/inc/mutex [hunk 6]
```diff
@@ -110,23 +93,16 @@ private:
     friend condition_variable;
     friend condition_variable_any;
 
-    union {
-        _Aligned_storage_t<_Mtx_internal_imp_size, _Mtx_internal_imp_alignment> _Mtx_storage;
-        _Mtx_internal_imp_mirror _Mtx_storage_mirror;
-    };
+    _Mtx_internal_imp_t _Mtx_storage{};
```
Comment (strega-nil-ms) [inline stl/inc/mutex:96]: This will break the debugger definitions; we probably want that to be updated as part of this.

Comment (strega-nil-ms) [reply stl/inc/mutex:96]: Oh, yep, we discussed this in the other PR, nvm.

**Review by strega-nil-ms — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
Unfortunately, I need to pull this from the merge batch. It's causing the internal build to consistently fail with:

```
D:\msvc\src\vctools\asan\mt\llvm-symbolizer.nativeproj(79,5): error MSB3073:
The command ""D:\msvc\src\ExternalAPIs\cmake\bin\ninja.exe" "bin/llvm-symbolizer.exe"   " exited with code 1.
```

I don't know what's causing this yet.

**Comment by StephanTLavavej** [comment]
We're very close to understanding the root cause - the MSVC-internal build is using fresh STL headers, but a previously installed copy of `msvcp140.dll` on the system. The fix will also be MSVC-internal; it appears that this PR is working by design (we knew that it would require an updated DLL).

**Comment by CaseyCarter** [comment]
> We're very close to understanding the root cause - the MSVC-internal build is using fresh STL headers, but a previously installed copy of `msvcp140.dll` on the system. The fix will also be MSVC-internal; it appears that this PR is working by design (we knew that it would require an updated DLL).

In other words: Thanks for finding a bug in our internal build!

**Comment by StephanTLavavej** [comment]
We'll need to ensure that the VCRedist is unlocked for this.

**Comment by StephanTLavavej** [comment]
:warning: Note to self: This requires MSVC-internal changes...
===

... found by @zacklj89 (:heart_eyes_cat:); I will investigate adding a complete set of DLLs to that list.

@MahmoudGSaleh will notify the appropriate people that 17.8 Preview 2 needs to have an unlocked VCRedist.

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
I've had to push an additional commit to avoid a `/clr` compiler error:

```
.\test.cpp(479): error C2127: 'obj2': illegal initialization of 'constinit' entity with a non-constant expression
```

`/clr` just hates constant initialization so there's nothing we can do about this except skip the test coverage.

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Thanks for fixing this unfixable bug!!! :heart_eyes_cat: :heart_eyes_cat: :heart_eyes_cat:
