### PR TITLE
`<xlocnum>`: Fix grouping for `num_get`

### LINKED ISSUE #1277: <xlocnum>: We don't match numpunct groups correctly in do_get
https://github.com/microsoft/STL/blob/be0441cda16c2cb49d0bc3710d77912b866992a4/tests/libcxx/skipped_tests.txt#L564-L565

Reduced test case:

```
C:\Temp>type meow.cpp
```
```cpp
//===----------------------------------------------------------------------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#include <cassert>
#include <cstddef>
#include <ios>
#include <locale>
#include <streambuf>
#include <string>

class my_facet : public std::num_get<char, const char*> {
public:
    explicit my_facet(std::size_t refs = 0) : std::num_get<char, const char*>(refs) {}
};

class my_numpunct : public std::numpunct<char> {
protected:
    virtual char_type do_thousands_sep() const {
        return '_';
    }
    virtual std::string do_grouping() const {
        return "\1\2\3";
    }
};

int main() {
    const my_facet f(1);
    std::ios my_ios(nullptr);
    my_ios.imbue(std::locale{std::locale{}, new my_numpunct});

    long v                     = -1;
    const char str[]           = "+1_";
    std::ios_base::iostate err = std::ios_base::goodbit;
    const char* const iter     = f.get(std::begin(str), std::end(str), my_ios, err, v);
    assert(iter == std::end(str) - 1);
    assert(err == std::ios_base::failbit);
    assert(v == 1);
}
```
```
C:\Temp>cl /EHsc /nologo /W4 /MTd meow.cpp && meow
meow.cpp
Assertion failed: v == 1, file meow.cpp, line 42
```

### PR DESCRIPTION
**Pull request by frederick-vs-ja**
Fixes #1277.

Unblocking one libcxx test:
- `std/localization/locale.categories/category.numeric/locale.num.get/facet.num.get.members/get_long.pass.cpp`

Also moves the test for non-ending unlimited grouping to the new test file.

I'm not sure when the grouping string is `"\0"s` which means grouping is not limited:
- whether `"17,,29"` can be parsed without setting `failbit`, and
- whether `"0,x1729"` should be parsed as a whole...

### CODE REVIEW

File: stl/inc/xlocnum [hunk 1]
```diff
@@ -244,7 +244,10 @@ __PURE_APPDOMAIN_GLOBAL locale::id numpunct<_Elem>::id;
 #endif // !defined(_CRTBLD) || defined(CRTDLL2) || !defined(_DLL) || defined(_M_CEE_PURE)
 
 struct _Num_get_parse_result {
-    int8_t _Base; // 0 for parsing failure, otherwise 10 or 16
+    // For integers: negative values mean for parsing failure, while the "actual" base (used by _Getifld) is ~_Base.
```
Comment (StephanTLavavej) [inline stl/inc/xlocnum:247]: Grammar: should say "mean parsing failure".

File: stl/inc/xlocnum [hunk 2]
```diff
@@ -632,8 +652,10 @@ protected:
     }
 
 private:
-    int __CLRCALL_OR_CDECL _Getifld(char* _Ac, _InIt& _First, _InIt& _Last, ios_base::fmtflags _Basefield,
-        const locale& _Loc) const { // get integer field from [_First, _Last) into _Ac
+    template <int = 0> // TRANSITON, ABI
```
Comment (StephanTLavavej) [inline stl/inc/xlocnum:655]: Typo, should be TRANSITION.

File: stl/inc/xlocnum [hunk 3]
```diff
@@ -657,9 +689,17 @@ private:
             }
         }
 
+        // skip leading separator before digits
```
Comment (StephanTLavavej) [inline stl/inc/xlocnum:692]: Nitpick: I believe this should say "separators" plural, because it has the same `while` loop.

File: tests/std/tests/GH_001277_num_get_bad_grouping/test.cpp [hunk 4]
```diff
@@ -0,0 +1,462 @@
...
+        const char* iter      = f.get(sep_str, sep_str + len + 1, instr, err, v);
+        assert(iter == sep_str + len);
+        assert(err == instr.failbit);
+        assert(v == static_cast<Flt>(-1729.0));
+    }
+}
+
+class my_numput : public num_put<char, char*> {
+public:
+public:
```
Comment (StephanTLavavej) [inline tests/std/tests/GH_001277_num_get_bad_grouping/test.cpp:275]: Repeated line.

**Review by StephanTLavavej — APPROVED** [review]

**Review by barcharcraz — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by CaseyCarter** [comment]
Thanks for helping to fix numerous problems in our number-parsing code.
