### PR TITLE
`<any>`: Skip the contents when static RTTI is disabled

### LINKED ISSUE #3114: `std.ixx`: Defining `_HAS_STATIC_RTTI=0` and importing `std` fails to compile due to `any`.
**Describe the bug**
(Very) recently, #2930 was merged into `main` to add the `std` and `std.compat` module interface units from [P2465R3](https://wg21.link/P2465R3). I went to go test this out in a forked repository to see how it works out. Typically, I define `_HAS_STATIC_RTTI=0` as a define for the projects which I work on. However, this results in a compilation error due to `<any>` requiring that `_HAS_STATIC_RTTI != 0`.

**Command-line test case**
[Assume that the current directory contains std.ixx.]
```
C:\Temp>cl /EHsc /W4 /WX /GR- /D "_HAS_STATIC_RTTI=0" /permissive- /std:c++latest .\std.ixx
Microsoft (R) C/C++ Optimizing Compiler Version 19.34.31823.3 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

/std:c++latest is provided as a preview of language features from the latest C++
working draft, and we're eager to hear about bugs and suggestions for improvements.
However, note that these features are provided as-is without support, and subject
to changes or removal as the working draft evolves. See
https://go.microsoft.com/fwlink/?linkid=2045807 for details.

std.ixx
C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.34.31823\include\any(22): fatal error C1189: #error:  class any requires static RTTI.
```

**Expected behavior**
According to the [original paper](https://wg21.link/P2465R3), there are no exceptions as to which declarations from the `std` namespace are actually exported by the `std` module; thus, the current behavior is technically correct. In practice, however, I can see this causing a lot of issues in real-world projects.

The only thing which I can think of for working around this is to conditionally `#include <any>` within `std.ixx` depending on the value of `_HAS_STATIC_RTTI`. This would technically be non-conformant, but `_HAS_STATIC_RTTI` is already a non-standard macro. Besides, if the user already defined `_HAS_STATIC_RTTI=0`, then it's pretty safe to assume that they weren't going to use anything in `<any>`, anyways.

I didn't see any mention of this in #3108, but if this issue was already discussed elsewhere, then please feel free to close this bug report.

**STL version**
This issue was found in a fork from the STL repo's `main` branch at [commit 2f03bdf](https://github.com/microsoft/STL/commit/2f03bdf361f7f153b4216c60a0d9491c0be13a73). Since the issue was reported early enough, current users of the MSVC STL are not affected by this bug. With that said, this still seems like a fairly urgent issue.

### PR DESCRIPTION
**Pull request by frederick-vs-ja**
This PR is making `#include <any>` effectless rather than erroneous when static RTTI is disabled.

Fixes #3114.

### CODE REVIEW

File: stl/inc/any [hunk 1]
```diff
@@ -12,16 +12,15 @@
 #if !_HAS_CXX17
 _EMIT_STL_WARNING(STL4038, "The contents of <any> are available only with C++17 or later.");
 #else // ^^^ !_HAS_CXX17 / _HAS_CXX17 vvv
+#if !_HAS_STATIC_RTTI
```
Comment (CaseyCarter) [inline stl/inc/any:15]:
```suggestion
#elif !_HAS_STATIC_RTTI // ^^^ !_HAS_CXX17 / _HAS_CXX17 vvv
```

File: stl/inc/any [hunk 2]
```diff
@@ -444,6 +443,7 @@ _STD_END
 _STL_RESTORE_CLANG_WARNINGS
 #pragma warning(pop)
 #pragma pack(pop)
+#endif // _HAS_STATIC_RTTI
 #endif // _HAS_CXX17
```
Comment (CaseyCarter) [inline stl/inc/any:447]:
```suggestion
#endif // ^^^ _HAS_STATIC_RTTI ^^^
```

File: stl/inc/any [hunk 3]
```diff
@@ -12,16 +12,15 @@
 #if !_HAS_CXX17
 _EMIT_STL_WARNING(STL4038, "The contents of <any> are available only with C++17 or later.");
 #else // ^^^ !_HAS_CXX17 / _HAS_CXX17 vvv
+#if !_HAS_STATIC_RTTI
+_EMIT_STL_WARNING(STL4040, "The contents of <any> are available only when RTTI is available.");
```
Comment (CaseyCarter) [inline stl/inc/any:16]:
```suggestion
_EMIT_STL_WARNING(STL4040, "The contents of <any> require static RTTI.");
```

File: stl/inc/yvals_core.h [hunk 4]
```diff
@@ -1357,7 +1357,9 @@ _EMIT_STL_ERROR(STL1004, "C++98 unexpected() is incompatible with C++23 unexpect
 
 // STL4039 is used to warn that "The contents of <coroutine> are not available with /await."
 
-// next warning number: STL4040
+// STL4040 is used to warn that "The contents of <meow> are available only when RTTI is available."
```
Comment (CaseyCarter) [inline stl/inc/yvals_core.h:1360]:
```suggestion
// STL4040 is used to warn that "The contents of <any> require static RTTI."
```

**Review by CaseyCarter — CHANGES_REQUESTED** [review]

**Review by CaseyCarter — APPROVED** [review]

**Comment by strega-nil-ms** [comment]
Do we want to additionally not include `<any>` in `std.ixx` when `_HAS_STATIC_RTTI=0`? It seems like we shouldn't be printing an error here.

**Comment by StephanTLavavej** [comment]
@strega-nil-ms Agreed - the intention is for `std.ixx` to respect all of our various modes. I can validate and push changes.

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Ok, I've pushed the following changes (FYI @CaseyCarter @strega-nil-ms):

* std.ixx: Guard `<any>` with `_HAS_STATIC_RTTI`.
  + `<algorithm>` is always included first, so `<yvals_core.h>` is available.
* Add `/D_HAS_STATIC_RTTI=0` coverage to `P2465R3_standard_library_modules`.
  + Also reduce the `/analyze` coverage to one configuration. (It found no issues when originally added, so we don't need to spend an entire crosslist on it.) Combined, this reduces the number of configurations from 8 to 6.
* Guard `__cpp_lib_any` with `_HAS_STATIC_RTTI`, add test coverage.
  + We should have done this earlier (as we do for headers where `/clr:pure` is blocked, etc.) but now is also a good time.
* `VSO_0000000_has_static_rtti`: Comment the apparently unused include.

Thanks @frederick-vs-ja for working on this - if we're going to have this not-exactly-encouraged-but-still-supported mode, it should behave reasonably, and I think your change makes the story coherent. :heart_eyes_cat:

**Review by CaseyCarter — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
Thanks for fixing the first bug after Standard Library Modules was merged! :lady_beetle: :white_check_mark: :heart_eyes_cat:
