### PR TITLE
`<memory>`: Add `nullptr` check in `std::allocator`

### LINKED ISSUE #2362: <memory>: Add nullptr check in std::allocator
**Describe the bug**
As discussed with @StephanTLavavej on the STL Discord server, it might be a good idea to add a debug-only nullptr assertion inside `std::allocator<T>::deallocate`, checking the pointer parameter. Passing nullptr to this member function is undefined behavior when the passed size is non-zero, however users not aware of this fact might pass nullptr expecting behavior similar to passing nullptr to `operator delete`, given that they are closely related.

Although many nullptr assertions have been removed from the STL because it is normally obvious in the debugger when a nullptr dereference occurs, this case is a bit different. At least in the latest VS2022 preview version of the STL, this UB may only become noticeable after a pointer subtraction in a certain branch somewhere within `deallocate` causes the pointer to underflow to `0xFFFF...` followed by a dereference of the underflowed pointer, making a misuse of this member function not only rarely noticeable and if it does get noticed, it is rather non-obvious what went wrong.

**Command-line test case**
```
C:\Temp>type repro.cpp
#include <memory>

int main() {
	std::allocator<char> al;
	al.deallocate(nullptr, 4117);
}

C:\Temp>cl /EHsc /W4 /WX .\repro.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.23.28019.1 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

repro.cpp
Microsoft (R) Incremental Linker Version 14.23.28019.1
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:repro.exe
repro.obj

C:\Temp>.\repro.exe
Exception thrown: read access violation.
**_Ptr_user** was 0xFFFFFFFFFFFFFFFF.
```

**Expected behavior**
```
Debug Assertion Failed!

Expression: Pointer passed to deallocate() must be obtained from allocate() or allocate_at_least().
```

Or a similar message.

**STL version**
Microsoft Visual Studio Community 2022 (64-bit) - Preview
Version 17.1.0 Preview 1.1

### PR DESCRIPTION
**Pull request by fsb4000**
Fixes #2362

### CODE REVIEW

File: tests/std/tests/Dev09_126254_persistent_aux_allocators/test.cpp [hunk 1]
```diff
@@ -98,6 +98,13 @@ void dump_map() {
     }
 }
 
+void test_gh_2362() {
+    allocator<int> al;
+    int* ptr = al.allocate(0);
+    assert(ptr == nullptr);
```
Comment (AlexGuteniev) [inline tests/std/tests/Dev09_126254_persistent_aux_allocators/test.cpp:104]: I'm not sure if this `assert` is needed. It is the current implementation detail, which can be freely changed.

Comment (fsb4000) [reply tests/std/tests/Dev09_126254_persistent_aux_allocators/test.cpp:104]: Should I add additional `al.deallocate(nullptr, 0);` or if we can change that `nullptr` is not returned for `allocate(0)` then `deallocate(nullptr, 0);` might be invalid too?

Comment (AlexGuteniev) [reply tests/std/tests/Dev09_126254_persistent_aux_allocators/test.cpp:104]: I think the later, so just remove the assert.

File: stl/inc/xmemory [hunk 2]
```diff
@@ -826,6 +826,7 @@ public:
     _CONSTEXPR20 allocator& operator=(const allocator&) = default;
 
     _CONSTEXPR20 void deallocate(_Ty* const _Ptr, const size_t _Count) {
+        _STL_ASSERT(_Ptr != nullptr || _Count == 0, "You can't deallocate a bunch of memory at nullptr");
```
Comment (CaseyCarter) [inline stl/inc/xmemory:829]: How about "null pointer cannot point to a block of non-zero size"?

File: tests/std/tests/Dev09_126254_persistent_aux_allocators/test.cpp [hunk 3]
```diff
@@ -98,6 +98,12 @@ void dump_map() {
     }
 }
 
+void test_gh_2362() {
```
Comment (CaseyCarter) [inline tests/std/tests/Dev09_126254_persistent_aux_allocators/test.cpp:101]: Could we have a one-line-ish description of what we're testing here so this function makes sense even if #2362 goes away?

File: tests/std/tests/Dev09_126254_persistent_aux_allocators/test.cpp [hunk 4]
```diff
@@ -98,6 +98,12 @@ void dump_map() {
     }
 }
 
+void test_gh_2362() {
+    allocator<int> al;
+    int* ptr = al.allocate(0);
+    al.deallocate(ptr, 0);
```
Comment (CaseyCarter) [inline tests/std/tests/Dev09_126254_persistent_aux_allocators/test.cpp:104]: I'd also like to see a test for an over-aligned type since they go through some different codepaths.

**Review by CaseyCarter — CHANGES_REQUESTED** [review]

**Review by CaseyCarter — APPROVED** [review]

**Review by mnatsuhara — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
Thanks for improving runtime diagnostics for users! :heart_eyes_cat: :white_check_mark: :tada:
