### PR TITLE
change SFINAE constraint on `construct_at` (MSVC workaround)

### LINKED ISSUE #2620: `<xutility>`: SFINAE constraint on `construct_at` prevents emplacing immovable objects with copy elision
**Describe the bug**
Currently the constraint on `construct_at` is implemented via SFINAE
https://github.com/microsoft/STL/blob/f099e9c9f91187376e85385b135ac62ef933e54f/stl/inc/xutility#L132-L134

This causes an error when trying to emplace immovable objects with copy elision:
`xutility(145): error C2783: '_Ty *std::construct_at(_Ty *const ,_Types &&...) noexcept(<expr>)': could not deduce template argument for '<unnamed-symbol>'`

Example code:

```cpp
struct S
{
    int v;
    S(int v): v(v) {}
    S(const S&) = delete;
};

union U
{
    char c;
    S s;
    U(): c{} {}
    ~U() noexcept {}
};

struct copy_elider
{
    operator S() const { return S(42); }
};

int main()
{
    U u;
    // AFAIK this should work since C++17 mandates copy elision
    std::construct_at(&u.s, copy_elider{});
}
```

Yet if the constraint is implemented via concepts, i.e.
```cpp
template <class _Ty, class... _Types>
    requires requires (void* ptr, _Types&&... _Args) { ::new (ptr) _Ty(static_cast<_Types&&>(_Args)...); }
constexpr _Ty* construct_at(_Ty* const _Location, _Types&&... _Args) noexcept(
```
then the example code above works as expected. I don't know the reason that these two behaviors differ though...

This issue hinders the ability to emplace immovable objects into `optional`s or `variant`s using the copy elision converter trick shown above.

**STL version**
VS Community 2022, Version 17.1.2

### PR DESCRIPTION
**Pull request by fsb4000**
Fixes #2620 

EDG gives error on both version of the constraint.

Also the Developer Community has a maintenance now, so I'll create DevCom bugs later(about EDG and MSVC)

### CODE REVIEW

File: stl/inc/xutility [hunk 1]
```diff
@@ -130,9 +130,13 @@ _NODISCARD constexpr void* _Voidify_iter(_Iter _It) noexcept {
 
 #if _HAS_CXX20
 template <class _Ty, class... _Types,
+#if 0 // TRANSITION, DevCom-XXXX, DevCom-XXXX
```
Comment (CaseyCarter) [inline stl/inc/xutility:133]: Calling out the obvious "we need these `XXXX`s filled in before committing" so there will be a comment on the conversation to immediately clarify why this is blocked.

File: stl/inc/xutility [hunk 2]
```diff
@@ -130,9 +130,13 @@ _NODISCARD constexpr void* _Voidify_iter(_Iter _It) noexcept {
...
 template <class _Ty, class... _Types,
+#if 0 // TRANSITION, DevCom-XXXX, DevCom-XXXX
     class = void_t<decltype(::new (_STD declval<void*>()) _Ty(_STD declval<_Types>()...))>>
-constexpr _Ty* construct_at(_Ty* const _Location, _Types&&... _Args) noexcept(
-    noexcept(::new (_Voidify_iter(_Location)) _Ty(_STD forward<_Types>(_Args)...))) /* strengthened */ {
+#else // ^^^ no workaround // workaround vvv
+    void_t<decltype(::new (_STD declval<void*>()) _Ty(_STD declval<_Types>()...))>* = nullptr>
+#endif // TRANSITION, DevCom-XXXX, DevCom-XXXX
+    constexpr _Ty* construct_at(_Ty* const _Location, _Types&&... _Args) noexcept(
+        noexcept(::new (_Voidify_iter(_Location)) _Ty(_STD forward<_Types>(_Args)...))) /* strengthened */ {
```
Comment (CaseyCarter) [inline stl/inc/xutility:139]: If we outdent these, will clang-format simply put them back? Is the situation any better if we duplicate line 132 into both sides of the preprocessor conditional? It's not a hard blocker, but it would be nice if we could return the original indentation of these two lines.

**Review by CaseyCarter — CHANGES_REQUESTED** [review]

File: stl/inc/xutility (hunk 2 above)
Comment (fsb4000) [reply stl/inc/xutility:139]: Yes, if we duplicate line 132 then clang-format will outdent these.

File: stl/inc/xutility (hunk 1 above)
Comment (miscco) [reply stl/inc/xutility:133]: Shouldn't this be `#ifdef __EDG__`

Comment (fsb4000) [reply stl/inc/xutility]: Sure, because the workaround doesn't help EDG we can use original code for EDG.

File: tests/std/tests/GH_002620_construct_at_workaround/test.cpp [hunk 3]
```diff
@@ -27,7 +27,7 @@ struct copy_elider {
 int main() {
     U u;
     // GH-2620: <xutility>: SFINAE constraint on construct_at prevents emplacing immovable objects with copy elision
-#ifndef __EDG__ // TRANSITION, DevCom-XXXX
+#ifndef __EDG__ // TRANSITION, DevCom-10000388
```
Comment (miscco) [inline tests/std/tests/GH_002620_construct_at_workaround/test.cpp:30]: With the `#ifdef __EDG__` this should always work now

Comment (fsb4000) [reply tests/std/tests/GH_002620_construct_at_workaround/test.cpp:30]: Maybe I wrote something wrong at the issue. EDG gives an error for both variants.
Look DevCom-10000388 :
```
$ cl main.cpp /nologo /std:c++latest /BE
main.cpp
"main.cpp", line 37: error: no instance of function template "construct_at1"
          matches the argument list
            argument types are: (S *, copy_elider)
      construct_at1(&u.s, copy_elider{});
      ^

"main.cpp", line 38: error: no instance of function template "construct_at2"
          matches the argument list
            argument types are: (S *, copy_elider)
      construct_at2(&u.s, copy_elider{});
      ^
```

**Review by CaseyCarter — APPROVED** [review]

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
@fsb4000 @CaseyCarter I pushed changes for a couple of style nitpicks (when reviewing, I should be less nitpicky about things that don't really matter, but I couldn't resist here :joy_cat:). Looks good, thanks for finding out how to make MSVC happy here!

File: tests/std/tests/GH_002620_construct_at_workaround/test.cpp [hunk 4]
```diff
@@ -7,7 +7,7 @@ using namespace std;
 
 struct S {
     int v;
-    S(int v) : v(v) {}
+    S(int v_) : v(v_) {}
```
Comment (CaseyCarter) [inline tests/std/tests/GH_002620_construct_at_workaround/test.cpp:10]: Could be `explicit` to avoid misuse; probably not worth resetting testing.

**Review by CaseyCarter — APPROVED** [review]

**Comment by fsb4000** [comment]
DevCom had closed the bug as a duplicate so I updated DevCom issue number and added `explicit`.

**Review by CaseyCarter — APPROVED** [review]

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
Unfortunately, this is blocked by VSO-1513874 "Changing `construct_at` SFINAE causes Modules bogus error C2660: 'operator new': function does not take 3 arguments".

**Review by raghavthind2005 — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
The blocking bug has been fixed for 17.3 Preview 2 (I confirmed that this was one of the last fixes to get in).

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I've pushed a merge with `main`, resolving a trivial adjacent-add conflict in `tests/std/test.lst`. This should be unblocked now that we've merged toolset update #2791.

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Review by CaseyCarter — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Thanks for finding out how to exceed the compiler's correctness! :white_check_mark: :white_check_mark: :white_check_mark:
