### PR TITLE
prevent random distributions from returning NaN/Inf

### LINKED ISSUE #1174: <random>: Some random number distributions could return NaN
**Describe the bug**

`normal_distribution`, `lognormal_distribution`, `fisher_f_distribution`, and `student_t_distribution` could return NaN.

**Command-line test case**

`#include`s [tests/std/tests/GH_001017_discrete_distribution_out_of_range/bad_random_engine.hpp](https://github.com/microsoft/STL/blob/8e8770cb1635386e84c8ab12f0df47fb0e35951c/tests/std/tests/GH_001017_discrete_distribution_out_of_range/bad_random_engine.hpp)

```
C:\Users\He\source\repos\STL\out>type random.cpp
```
```
#include <cassert>
#include <cmath>
#include <random>

#include "bad_random_engine.hpp"

using namespace std;

template <class Distribution>
void test(Distribution&& distribution) {
    for (bad_random_generator rng; !rng.has_cycled_through();) {
        const auto x = distribution(rng);
        assert(!isnan(x));
    }
}

int main() {
    test(normal_distribution<>{});
    test(lognormal_distribution<>{});
    test(fisher_f_distribution<>{});
    test(student_t_distribution<>{});
}
```
```
C:\Users\He\source\repos\STL\out>cl /EHsc /W4 /WX /O2 random.cpp
用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.28.29115 版
版权所有(C) Microsoft Corporation。保留所有权利。

random.cpp
Microsoft (R) Incremental Linker Version 14.28.29115.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:random.exe
random.obj

C:\Users\He\source\repos\STL\out>.\random.exe
Assertion failed: !isnan(x), file random.cpp, line 13
```

**STL version**

```
https://github.com/microsoft/STL/commit/e000d3feaf6acaf6214aedcfa21de483931ccbb7
```

### PR DESCRIPTION
**Pull request by Arzaghi**
Fixes #1174

### CODE REVIEW

**Comment by Arzaghi** [comment]
> * For `fisher_f_distribution`, should we also reject here if `_Px == _Ty{1}`? That would generate infinity rather than NaN.
> * The issue mentions `student_t_distribution`, but there's no change to it. It's not obvious to me how it would cause NaN, but `_Rs == 0` would give infinity.

That's right. Thank you for that. I just tested the code for isNan(x) and I didn't catch that. I fix it now.

File: stl/inc/random [hunk 1]
```diff
@@ -2936,7 +2936,7 @@ private:
                 _Vx1 = 2 * _NRAND(_Eng, _Ty) - 1;
                 _Vx2 = 2 * _NRAND(_Eng, _Ty) - 1;
                 _Sx  = _Vx1 * _Vx1 + _Vx2 * _Vx2;
-                if (_Sx < 1) {
+                if (_Sx < 1 && _Sx != 0) {
```
[the remark this answers is not in the document]
Comment (Arzaghi) [reply stl/inc/random:2939]: > * For `fisher_f_distribution`, should we also reject here if `_Px == _Ty{1}`? That would generate infinity rather than NaN.
> * The issue mentions `student_t_distribution`, but there's no change to it. It's not obvious to me how it would cause NaN, but `_Rs == 0` would give infinity.

That's right. Thank you for that. I just tested the code for isNan(x) and didn't catch isInf(x). I thought `_Px == _Ty{1}` could not happen at all. I fix it now. Thanks.

Here is my test program with a slight improvement of the @statementreply test code on the issue description. however I'm not sure is it a good idea to add time-consuming test to unit tests?

```cpp
#include <cassert>
#include <cmath>
#include <random>
#include <iostream>

#include "\tests\std\tests\GH_001017_discrete_distribution_out_of_range\bad_random_engine.hpp"

using namespace std;

template <class Distribution>
void test(Distribution&& distribution) {	
	for (bad_random_generator rng; !rng.has_cycled_through();) {
		const auto x = distribution(rng);
		assert(!isnan(x) && !isinf(x));
	}
}

int main() {
	test(normal_distribution<>{});
	std::cout << "normal_distribution\t\tok" << std::endl;

	test(lognormal_distribution<>{});	
	std::cout << "lognormal_distribution\t\tok" << std::endl;

	test(fisher_f_distribution<>{});	
	std::cout << "fisher_f_distribution\t\tok" << std::endl;

	test(student_t_distribution<>{});	
	std::cout << "student_t_distribution\t\tok" << std::endl;

	std::cout << "Done!";
	std::cin.get();
	return 0;
}
```

**Comment by Arzaghi** [comment]
Here is my test program with a slight improvement of the @statementreply test code on the issue description. however, I'm not sure is it a good idea to add time-consuming tests to unit tests?

```cpp
#include <cassert>
#include <cmath>
#include <random>
#include <iostream>

#include "\tests\std\tests\GH_001017_discrete_distribution_out_of_range\bad_random_engine.hpp"

using namespace std;

template <class Distribution>
void test(Distribution&& distribution) {	
	for (bad_random_generator rng; !rng.has_cycled_through();) {
		const auto x = distribution(rng);
		assert(!isnan(x) && !isinf(x));
	}
}

int main() {
	test(normal_distribution<>{});
	std::cout << "normal_distribution\t\tok" << std::endl;

	test(lognormal_distribution<>{});	
	std::cout << "lognormal_distribution\t\tok" << std::endl;

	test(fisher_f_distribution<>{});	
	std::cout << "fisher_f_distribution\t\tok" << std::endl;

	test(student_t_distribution<>{});	
	std::cout << "student_t_distribution\t\tok" << std::endl;

	std::cout << "Done!";
	std::cin.get();
	return 0;
}
```

File: stl/inc/random (hunk 1 above)
[the remark this answers is not in the document]
Comment (Arzaghi) [reply stl/inc/random]: > This is fine as far as preventing NaN, but will overflow for `_Sx` less than ~7.8e-306 for `double`. On the other hand, even with `_Vx1` and `_Vx2` on the order of `numeric_limits<double>::min`, the true value of `_Fx` is around 38. So maybe this could be made to work for all nonzero `_Sx`, though it's a bit beyond the scope of the original issue.

Thank you. I've found the exact min value for _Sx that causes the calculation to overflow.

File: stl/inc/random [hunk 2]
```diff
@@ -2929,14 +2929,17 @@ private:
             _Res   = _Xx2;
             _Valid = false;
         } else { // generate two values, store one, return one
+            const _Ty _MinSx{static_cast<_Ty>(7.8159598771420286e-306)};
```
Comment (MattStephanson) [inline stl/inc/random:2932]: The issue with this is that the exact value depends on the type and, more importantly, how `log` is calculated. I was thinking of using scaling, similar to #935 for small arguments to `log`. Something like the following (caveats: not well-tested, only `double`, not STL style). The 1e-4 threshold is mostly arbitrary, but I could make it more rigorous if people are interested. Or not, since it should only take that path once every 10^8 calls.
```
double Vx1, Vx2, Fx;
for (;;) {
    Vx1 = 2 * std::generate_canonical<double, size_t(-1)>(g) - 1;
    Vx2 = 2 * std::generate_canonical<double, size_t(-1)>(g) - 1;
    double Sx = Vx1 * Vx1 + Vx2 * Vx2;
    if (Sx >= 1.0 || (Vx1 == 0.0 && Vx2 == 0.0)) {
        continue;
    }
    double tmp;
    if (Sx <= 1.0e-4) {
        double maxAbs = std::max(std::abs(Vx1), std::abs(Vx2));
        const int expMax = std::ilogb(maxAbs);
        Vx1 = std::scalbn(Vx1, -expMax);
        Vx2 = std::scalbn(Vx2, -expMax);
        Sx = Vx1 * Vx1 + Vx2 * Vx2;
        constexpr double ln2 = 0.6931471805599453;
        tmp = std::log(Sx) + static_cast<double>(expMax) * (2.0 * ln2);
    }
    else {
        tmp = std::log(Sx);
    }
    Fx = sqrt(-2.0 * tmp / Sx);
    break;
}
```

Comment (Arzaghi) [reply stl/inc/random]: @MattStephanson 
I just refactor your code in the most recent commit. I didn't encounter any bugs during my tests.
Thank you for the idea and the implementation.

File: stl/inc/random [hunk 3]
```diff
@@ -2932,15 +2932,32 @@ private:
...
                     break;
                 }
             }
-            const auto _Fx = static_cast<_Ty>(_CSTD sqrt(-2.0 * _CSTD log(_Sx) / _Sx));
+
+            _Ty _LogSx;
+            if (_Sx > 1.0e-4) {
+                _LogSx = _STD log(_Sx);
+            } else {
+                // Bad _Sx value! It will cause overflow on log calculation
```
Comment (MattStephanson) [inline stl/inc/random:2949]: This is a little misleading, because it must be much smaller to actually overflow. 
```suggestion
                // Bad _Sx value! Very small values will overflow log(_Sx)/_Sx

```

**Review by MattStephanson — COMMENTED** [review]
Nice work, this looks mostly good to me. I just have a few minor points.

**Review by cbezault — CHANGES_REQUESTED** [review]
If there's something that I'm missing with regards to those `static_cast`s then this LGTM. Otherwise could you just choose a consistent style for getting the type of variables you want?

File: stl/inc/random [hunk 4]
```diff
@@ -4001,12 +4028,18 @@ private:
         _Ty _Px;
         _Ty _Vx1;
         _Ty _Vx2;
+        const _Ty _Vx3{1};
```
[the remark this answers is not in the document]
Comment (Arzaghi) [reply stl/inc/random:4031]: > I kind of feel like storing the constant `1` in an obscurely named variable is less illuminating than just writing out. `_Ty{1}` whenever you need it. No change requested though. I don't feel super strongly.

I use it in two places. 

https://github.com/microsoft/STL/blob/109ec2ac050e2ba5108f1dee6a483edfaff35074/stl/inc/random#L4037-L4042

That's because if the value in the formula changed for any reason, then we should take care of that value in the `if` statement as well. So, I thought it is better to have it as a `const variable`

**Review by cbezault — APPROVED** [review]

File: stl/inc/random [hunk 5]
```diff
@@ -2932,15 +2932,32 @@ private:
...
+            } else {
+                // Bad _Sx value! Very small values will overflow log(_Sx)/_Sx
+                // generating a new value based on scaling method.
+                const _Ty _Ln2{static_cast<_Ty>(0.69314718055994530941723212145818)};
+                const _Ty _Maxabs{(_STD max)(_STD abs(_Vx1), _STD abs(_Vx2))};
+                const int _ExpMax{_STD ilogb(_Maxabs)};
+                _Vx1   = _STD scalbn(_Vx1, -_ExpMax);
+                _Vx2   = _STD scalbn(_Vx2, -_ExpMax);
+                _Sx    = _Vx1 * _Vx1 + _Vx2 * _Vx2;
+                _LogSx = _STD log(_Sx) + static_cast<_Ty>(_ExpMax) * (_Ln2 * 2);
```
[the remark this answers is not in the document]
Comment (Arzaghi) [reply stl/inc/random:2957]: The suggestion caused a [narrowing conversion error](https://dev.azure.com/vclibs/STL/_build/results?buildId=5062&view=logs&j=cdd012bc-41eb-580d-7644-e3ee22f60668&t=fa6988c9-f03e-5298-dc6f-c8d5e7a135a0&l=982) during the tests. I've reverted it to an explicit conversion.

**Review by cbezault — APPROVED** [review]

File: stl/inc/random [hunk 6]
```diff
@@ -2932,15 +2932,32 @@ private:
...
-                if (_Sx < 1) {
+                if (_Sx < _Ty{1} && _Vx1 != _Ty{0} && _Vx2 != _Ty{0}) {
+                    // good values!
                     break;
                 }
             }
-            const auto _Fx = static_cast<_Ty>(_CSTD sqrt(-2.0 * _CSTD log(_Sx) / _Sx));
+
+            _Ty _LogSx;
+            if (_Sx > 1.0e-4) {
```
Comment (StephanTLavavej) [inline stl/inc/random:2946]: This is comparing against a `double`, so it'll widen `float` to `double`. Should it instead be comparing against `_Ty{1e-4}`, like the comparison against `_Ty{1e-12}` below? Note, however, that there is a value difference. I am uncertain what to do here (I suspect that the _precise_ threshold isn't terribly important so using `_Ty` should be fine).

```
C:\Temp>type meow.cpp
#include <stdio.h>

int main() {
    printf("%.1000g\n", 1e-4);
    printf("%.1000g\n", 1e-4f);
}

C:\Temp>cl /EHsc /nologo /W4 meow.cpp && meow
meow.cpp
0.000100000000000000004792173602385929598312941379845142364501953125
9.99999974737875163555145263671875e-05
```

File: stl/inc/random [hunk 7]
```diff
@@ -2932,15 +2932,32 @@ private:
...
+                _LogSx = _STD log(_Sx);
+            } else {
+                // Bad _Sx value! Very small values will overflow log(_Sx)/_Sx
+                // generating a new value based on scaling method.
```
Comment (StephanTLavavej) [inline stl/inc/random:2950]: Would this be clearer? We have comments of the form `Full sentence. Another full sentence.` (with capitalization and punctuation) and comments of the form `sentence fragment` (no capitalization, no period), which are both fine. However, it's confusing when sentences and sentence fragments are mixed without any punctuation.
```suggestion
                // Bad _Sx value! Very small values will overflow log(_Sx) / _Sx.
                // Generate a new value based on scaling method.
```

File: tests/std/tests/GH_001017_discrete_distribution_out_of_range/test.cpp [hunk 8]
```diff
@@ -6,6 +6,22 @@
 
 #include "bad_random_engine.hpp"
 
+template <class Distribution>
+void Test_for_NaN_Inf(Distribution&& distribution) {
+    for (bad_random_generator rng; !rng.has_cycled_through();) {
+        const auto rand_value = distribution(rng);
+        assert(!isnan(rand_value) && !isinf(rand_value));
```
Comment (StephanTLavavej) [inline tests/std/tests/GH_001017_discrete_distribution_out_of_range/test.cpp:13]: Would it be better to assert these separately, so if it ever fails, we'll immediately see whether the failure was due to nan or inf?

File: tests/std/tests/GH_001017_discrete_distribution_out_of_range/test.cpp [hunk 9]
```diff
@@ -6,6 +6,22 @@
...
+template <class Distribution>
+void Test_for_NaN_Inf(Distribution&& distribution) {
+    for (bad_random_generator rng; !rng.has_cycled_through();) {
+        const auto rand_value = distribution(rng);
+        assert(!isnan(rand_value) && !isinf(rand_value));
+    }
+}
+
+template <class T>
+void Test_distributions() {
```
Comment (StephanTLavavej) [inline tests/std/tests/GH_001017_discrete_distribution_out_of_range/test.cpp:18]: Adding test coverage here is great, thanks. Although git history is always available, we conventionally add a comment like:
```cpp
// Additionally test GH-1174 "<random>: Some random number distributions could return NaN"
```
so if this section of the test fails, we can easily look up the bug/PR and understand the context.

**Review by StephanTLavavej — CHANGES_REQUESTED** [review]
This looks good to me, thanks. I have three superficial comments about comments (heh) and asserts, and one slightly more significant question about using a `double` versus `_Ty` constant. If the answer there is that comparing against `1.0e-4` is intentional and correct, I'm happy.

File: tests/std/tests/GH_001017_discrete_distribution_out_of_range/test.cpp (hunk 8 above)
Comment (StephanTLavavej) [reply tests/std/tests/GH_001017_discrete_distribution_out_of_range/test.cpp:13]: I suppose this doesn't really matter if the test is deterministic; we'd need to debug into it anyways to determine which distribution triggered the failure, since the line number alone won't give us that template instantiation context. No change requested here (but splitting up `assert(condition1 && condition2)` is a general principle to keep in mind for the future).

File: stl/inc/random (hunk 6 above)
Comment (MattStephanson) [reply stl/inc/random:2946]: I suggested this, so I'll confirm that it's not intended to be a precise threshold. The precise one would be based on preventing underflow in ` _Vx1 * _Vx1 + _Vx2 * _Vx2` and overflow in `2*log(_Sx)/_Sx`. For `float` those limits are about 4e-16 and 5e-37, so 1e-4 is very conservative. `_Ty{1e-4}` would be better, to avoid the unnecessary conversion cost.

Comment (StephanTLavavej) [reply stl/inc/random:2946]: Thanks - I'll go ahead and push changes then.

**Review by StephanTLavavej — APPROVED** [review]

File: tests/std/tests/GH_001017_discrete_distribution_out_of_range/test.cpp (hunk 9 above)
Comment (Arzaghi) [reply tests/std/tests/GH_001017_discrete_distribution_out_of_range/test.cpp:18]: This is a relatively old PR. I didn't know this rule at that time. :)

File: stl/inc/random (hunk 7 above)
Comment (Arzaghi) [reply stl/inc/random]: Sorry I was a little late. Thanks for your feedback and also applying it. It's always very difficult for me to follow English grammar and the repo rules on writing comments. Unfortunately, English is not my native language. I'm going to try my best on the next PRs. :)

File: tests/std/tests/GH_001017_discrete_distribution_out_of_range/test.cpp (hunk 9 above)
Comment (StephanTLavavej) [reply tests/std/tests/GH_001017_discrete_distribution_out_of_range/test.cpp:18]: No problem at all! It's one of our unwritten conventions that I still need to collect in a document.

**Comment by StephanTLavavej** [comment]
Thanks again for fixing this silent bad codegen in `<random>` - the very worst category of bug! :beetle: :x: => :smile_cat: :tada:
