### PR TITLE
resize_and_overwrite: fix warning C4018

### LINKED ISSUE #2524: <xstring>: resize_and_overwrite generates warning C4018 when Operation returns int
**The bug description**
According to C++23 draft the `Operation op` of `std::string` member function `resize_and_overwrite` does not have to return `size_t`, it can also return, for ex., `int` (https://eel.is/c++draft/string.capacity#8):
> [21.3.3.5] Capacity [string.capacity]
> ...
> Mandates: OP has an integer-like type ([iterator.concept.winc]).

When `op` returns `int` the compiler produces "warning C4018: '<=': signed/unsigned mismatch" inside STL implementation code that performs `_STL_VERIFY` check on `op` return value under debug build.

**Command-line test case**
```
#include <string>
int main() {
	std::string s;
	s.resize_and_overwrite(1, [](char* buffer, size_t) {
		*buffer = 'x';
		int i = 1;
		return i;
	});
}
```
Compile for debug, x86 platform and with /std:c++latest, /W3.

**Expected behavior**
No warning produced by the compiler.

**STL version**
STL version from master having `resize_and_overwrite` implemented.

**How to fix**
The fix is very simple - replace `auto` with `size_t` inside the following line of `resize_and_overwrite` implementation:
```
const auto _Result_size = _STD move(_Op)(_Mypair._Myval2._Myptr(), _New_size);
```
Alternatively, contact compiler team to make them disable useless warning C4018 by default for x86 builds (it is already disabled for x64 builds).

### PR DESCRIPTION
**Pull request by fsb4000**
Fixes #2524

`cmp_less_equal` is in `utility`

`xutility` includes `utility`

`xmemory` includes `xutility`

`xstring` includes `xmemory`

### CODE REVIEW

**Comment by cpplearner** [comment]
`cmp_less_equal` doesn't work with the upcoming `_Unsigned128` (#2518) though.

File: tests/std/tests/P0980R1_constexpr_strings/test.cpp [hunk 1]
```diff
@@ -2383,6 +2383,19 @@ constexpr void test_all() {
     static_assert(test_allocator_awareness<CharType>());
 }
 
+#if _HAS_CXX23
+void test_gh_2524() // COMPILE-ONLY
+{
```
Comment (StephanTLavavej) [inline tests/std/tests/P0980R1_constexpr_strings/test.cpp:2388]: No change requested (mega-nitpick, not worth resetting testing): This brace should be attached to the function. (clang-format would ordinarily fix this, but it's inhibited from doing so by the comment.)

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo. Requesting or pushing changes is totally fine, but please notify me if that happens.

**Review by CaseyCarter — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Thanks for fixing this warning! :tada: :smile_cat: :white_check_mark:
