### PR TITLE
`<format>`: Fix handling of replacement field when format-spec is absent

### LINKED ISSUE #4636: `<format>`: Call to `next_arg_id` may result in unexpected error (regression)
When user-defined formatter calls `next_arg_id` and format-spec is empty we will get compiler error.

Example:
```c++
#include <print>

struct FormatNextArg {};

template <> struct std::formatter<FormatNextArg> {
public:
  template <class ParseContext> constexpr auto parse(ParseContext &ctx) {
    auto it = ctx.begin();
    if (it != ctx.end() && *it != '}') {
      throw std::format_error{"Expected empty spec"};
    }

    arg_id = ctx.next_arg_id();
    return it;
  }

  template <class FormatContext>
  auto format(FormatNextArg, FormatContext &ctx) const {
    return std::format_to(ctx.out(), "arg-id: {}", arg_id);
  }

private:
  size_t arg_id;
};

int main() {
  // std::println("{}, {}", FormatNextArg{}, 0, FormatNextArg{}, "1"); // Does not compile since VS 17.10
  std::println("{:}, {:}", FormatNextArg{}, 2, FormatNextArg{}, "3"); // Works, replacement field is not empty
}
```

Introduced by: #4078
Compiler explorer (VS 17.9): https://godbolt.org/z/rsje4j1hP

### PR DESCRIPTION
**Pull request by frederick-vs-ja**
Fixes #4636. Also fixes the runtime behavior - both output line in the reported example should be `arg-id: 1, arg-id: 3`.

I've verified that the example posted in #4078 still fails to compile (when using `/utf-8` or a `wchar_t` variant). But I don't know how to test such error in the test suits of MSVC STL.

### CODE REVIEW

**Comment by StephanTLavavej** [comment]
Thanks! There are numerous test failures. As a reminder, when making changes to `<format>`, it's a good idea to run all of the directories with `format` in their name.

File: tests/std/tests/P0645R10_text_formatting_custom_formatting/test.cpp [hunk 1]
```diff
@@ -58,10 +58,10 @@ struct not_const_formattable_type {
 template <>
 struct std::formatter<basic_custom_formattable_type, char> {
     constexpr basic_format_parse_context<char>::iterator parse(basic_format_parse_context<char>& parse_ctx) {
-        if (parse_ctx.begin() != parse_ctx.end()) {
+        if (parse_ctx.begin() != parse_ctx.end() && *parse_ctx.begin() != '}') {
```
Comment (frederick-vs-ja) [inline tests/std/tests/P0645R10_text_formatting_custom_formatting/test.cpp:61]: Per [[tab:formatter.basic]](https://eel.is/c++draft/tab:formatter.basic), it seems that we should also accept ranges starting with `'}'`.

Comment (barcharcraz) [reply tests/std/tests/P0645R10_text_formatting_custom_formatting/test.cpp:61]: yeah, this is just the case where it's not the last replacement field in the string, so you got `{:.*}`

In fact, I think the '}' case is the _only_ case for us, but it's good to check both anyway.

File: tests/std/tests/P0645R10_text_formatting_custom_formatting/test.cpp [hunk 2]
```diff
@@ -58,10 +58,10 @@ struct not_const_formattable_type {
 template <>
 struct std::formatter<basic_custom_formattable_type, char> {
     constexpr basic_format_parse_context<char>::iterator parse(basic_format_parse_context<char>& parse_ctx) {
-        if (parse_ctx.begin() != parse_ctx.end()) {
+        if (parse_ctx.begin() != parse_ctx.end() && *parse_ctx.begin() != '}') {
             throw format_error{"only empty specs please"};
         }
-        return parse_ctx.end();
+        return parse_ctx.begin();
```
Comment (barcharcraz) [inline tests/std/tests/P0645R10_text_formatting_custom_formatting/test.cpp:64]: This should be non-functional, correct? It's a matter of if we "match" the closing '}' or not.

File: tests/std/tests/P0645R10_text_formatting_custom_formatting/test.cpp [hunk 3]
```diff
@@ -276,6 +276,68 @@ void test_basic_format_context_construction() {
...
+
+template <class CharT>
+struct std::formatter<NeedMagicWord, CharT> {
+    constexpr auto parse(basic_format_parse_context<CharT> const& ctx) {
+        constexpr basic_string_view<CharT> magic_word{TYPED_LITERAL(CharT, "narf")};
+        auto [i, j] = ranges::mismatch(ctx, magic_word);
+        if (j != magic_word.end()) {
+            throw format_error{"you didn't say the magic word!"};
+        }
+        if (i != ctx.end() && *i != '}') {
```
Comment (StephanTLavavej) [inline tests/std/tests/P0645R10_text_formatting_custom_formatting/test.cpp:324]: Style: Newline between non-chained `if`-statements.

File: stl/inc/format [hunk 4]
```diff
@@ -3606,9 +3606,9 @@ struct _Format_checker {
         : _Parse_context(_Fmt, _Num_args, _Arg_type),
           _Parse_funcs{&_Compile_time_parse_format_specs<_Args, _ParseContext>...} {}
     constexpr void _On_text(const _CharT*, const _CharT*) const noexcept {}
-    constexpr void _On_replacement_field(const size_t _Id, const _CharT*) const {
-        _ParseContext _Parse_ctx({});
-        (void) _Parse_funcs[_Id](_Parse_ctx);
+    constexpr void _On_replacement_field(const size_t _Id, const _CharT* _Last) {
+        _Parse_context.advance_to(_Parse_context.begin() + (_Last - &*_Parse_context.begin()));
```
Comment (StephanTLavavej) [inline stl/inc/format:3610]: Instead of `&*_Parse_context.begin()`, right line 3614 below says `_Parse_context.begin()._Unwrapped()`. We should follow that precedent. Occurs again on 3647. I see that this was likely copied from pre-existing inconsistency on 3655, let's change that one too.

File: tests/std/tests/P0645R10_text_formatting_custom_formatting/test.cpp [hunk 5]
```diff
@@ -276,6 +276,68 @@ void test_basic_format_context_construction() {
...
+        return it;
+    }
+
+    template <class FormatContext>
+    auto format(FormatNextArg, FormatContext& ctx) const {
+        return format_to(ctx.out(), TYPED_LITERAL(CharT, "arg-id: {}"), arg_id);
+    }
+
+private:
+    size_t arg_id;
```
Comment (StephanTLavavej) [inline tests/std/tests/P0645R10_text_formatting_custom_formatting/test.cpp:303]: Super nitpick, should include `<cstddef>`.

File: tests/std/tests/P0645R10_text_formatting_custom_formatting/test.cpp [hunk 6]
```diff
@@ -276,6 +276,68 @@ void test_basic_format_context_construction() {
...
+           == TYPED_LITERAL(CharT, "arg-id: 1, arg-id: 3"));
+    assert(format(TYPED_LITERAL(CharT, "{:}, {:}"), FormatNextArg{}, 2, FormatNextArg{}, TYPED_LITERAL(CharT, "3"))
+           == TYPED_LITERAL(CharT, "arg-id: 1, arg-id: 3"));
+}
+
+struct NeedMagicWord {};
+
+template <class CharT>
+struct std::formatter<NeedMagicWord, CharT> {
+    constexpr auto parse(basic_format_parse_context<CharT> const& ctx) {
```
Comment (StephanTLavavej) [inline tests/std/tests/P0645R10_text_formatting_custom_formatting/test.cpp:318]: Should use west `const`.

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Thanks! FYI @barcharcraz I pushed minor changes after you approved.

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
Thanks! Fewer correctness bugs, happier users!
:chart_with_downwards_trend: :lady_beetle:
:chart_with_upwards_trend: :heart_eyes_cat:
