### PR TITLE
Fix LWG-3699 `lexically_relative` on UNC drive paths (`\\?\C:\...`) results in a default-constructed value

### LINKED ISSUE #2256: <filesystem>: lexically_relative() can not handle long path with prefix \\?\
**Describe the bug**
I would expect that this line of code is true:
```std::filesystem::path("\\\\?\\C:\\a\\d").lexically_relative("\\\\?\\C:\\a") == "d"```
But it is not, because an empty string will be returned. The reason for that is, that inside of ```lexically_relative()``` a check ```_Relative_path_contains_root_name()``` will be executed, but this is always true. The reason is how the filesystem is handling the root name as explained in ```_Find_root_name_end()```. There is pointed out, that in my case ```\\?\``` is the root name. But at the same time, the path contains ```C:\``` which is a valid root name as well. Because of that, we have the weird behaving, that:
```std::filesystem::path("\\\\?\\C:\\a\\d").relative_path() == "C:\\a\\d")``` which is not a relative path and causes the misbehaving of lexically_relative, because it can find another root_name inside of the "relative" path.

**Command-line test case**
```
#include <iostream>
#include <filesystem>
#include <cassert>
namespace fs = std::filesystem;
 
int main()
{
    assert(fs::path("C:\\a\\d").lexically_relative("C:\\a") == "d");
}
```

**Expected behavior**
That ```\\?\C:\``` will be treated as root path and not ```\\?\```

**STL version**
* 16.11.3

**Additional context**
In another issue #1921 StephanTLavavej pointed out, that ```\\?\``` only should be used by expert users and I agree. But in case I want to use the new Desktop-Bridge I had to use the new manifest appxmanifest, which not has a property anymore longPathAware. So I don't know how my app gives the consence of supporting that. (Is there maybe a better way to opt-in to the long path app wise) And I don't find any documentation for this use case, besides https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=cmd. And so my only solution to solve this issue is, of converting the paths with the prefix ```\\?\```. But this from my point of view is not well handled by the std::filesystem lib.

### PR DESCRIPTION
**Pull request by strega-nil-ms**
Fixes #2256 and LWG-3699

This is one choice of how to implement this; it makes `lexically_relative` treat `\\?\<drive letter>:\` as equivalent to `<drive letter>:\`; another option would _just_ be to allow `\\?\<drive letter>:\` and not have them be equivalent.

### CODE REVIEW

**Comment by strega-nil-ms** [comment]
Marking `decision needed` as we need to decide whether `\\?\C:` and `C:` are "the same" for purposes of `lexically_relative`

File: tests/std/tests/P0218R1_filesystem/test.cpp [hunk 1]
```diff
@@ -3145,6 +3145,12 @@ void test_lexically_relative() {
 
     // LWG-3070
     EXPECT(path(LR"(\a:\b:)"sv).lexically_relative(LR"(\a:\c:)"sv).native() == LR"()"sv);
+
+    // LWG-3699
+    EXPECT(path(LR"(\\?\a:\foo)"sv).lexically_relative(LR"(\\?\a:\foo)"sv).native() == LR"(.)"sv);
+    EXPECT(path(LR"(a:\foo)"sv).lexically_relative(LR"(\\?\a:\foo)"sv).native() == LR"(.)"sv);
+    EXPECT(path(LR"(\\?\a:\foo)"sv).lexically_relative(LR"(a:\foo)"sv).native() == LR"(.)"sv);
+    EXPECT(path(LR"(\\?\a:\foo\bar\baz)"sv).lexically_relative(LR"(a:\foo)"sv).native() == LR"(bar\baz)"sv);
```
Comment (StephanTLavavej) [inline tests/std/tests/P0218R1_filesystem/test.cpp:3153]: We conventionally avoid `foo` and `bar` in the repo. In filesystem tests, we've used `cat`, `dog`, `elk` which are the same length (and a little bit easier to distinguish than `bar` and `baz`). (Other words would be fine too.)

File: stl/inc/filesystem [hunk 2]
```diff
@@ -1686,23 +1686,33 @@ namespace filesystem {
         return false;
     }
 
-    _NODISCARD inline path path::lexically_relative(const path& _Base) const {
+    _NODISCARD inline path path::lexically_relative(const path& _Base_) const {
+        // N4868 [fs.path.gen]
```
Comment (StephanTLavavej) [inline stl/inc/filesystem:1690]: N4910 is the current WP. It doesn't really matter for a citation like this (where it's just a section name, not a paragraph number), so changing this is optional - just wanted to note it because we should always be looking at the latest wording.

File: stl/inc/filesystem [hunk 3]
```diff
@@ -1686,23 +1686,33 @@ namespace filesystem {
...
+
         constexpr wstring_view _Dot     = L"."sv;
         constexpr wstring_view _Dot_dot = L".."sv;
 
+        // LWG-3699: `lexically_relative` on UNC drive paths (`\\?\C:\...`) results in a default-constructed value
+        // This avoids doing any unnecessary copies;
+        // the return value of `relative_path()` is lifetime extended if necessary.
+        const path& _This = _Is_drive_prefix_with_slash_slash_question(native()) ? relative_path() : *this;
+        const path& _Base =
+            _Is_drive_prefix_with_slash_slash_question(_Base_.native()) ? _Base_.relative_path() : _Base_;
```
Comment (StephanTLavavej) [inline stl/inc/filesystem:1700]: It appears that `path` member functions consistently refer to `_Text` directly, so I believe that the calls to `native()` and `_Base_.native()` here should follow this convention.

File: stl/inc/filesystem [hunk 4]
```diff
@@ -1686,23 +1686,33 @@ namespace filesystem {
         return false;
     }
 
-    _NODISCARD inline path path::lexically_relative(const path& _Base) const {
+    _NODISCARD inline path path::lexically_relative(const path& _Base_) const {
```
Comment (StephanTLavavej) [inline stl/inc/filesystem:1689]: Style: We use `_Meow`/`_Meow_` in constructors where the values are the same and we just want to avoid shadowing. Here, a significant transformation is being applied, so the similarity in names between `_Base` and `_Base_` is potentially hazardous. I recommend following the pattern used elsewhere with `_Count_raw`.

File: stl/inc/filesystem [hunk 5]
```diff
@@ -1686,23 +1686,33 @@ namespace filesystem {
...
-    _NODISCARD inline path path::lexically_relative(const path& _Base) const {
+    _NODISCARD inline path path::lexically_relative(const path& _Base_) const {
+        // N4868 [fs.path.gen]
+
         constexpr wstring_view _Dot     = L"."sv;
         constexpr wstring_view _Dot_dot = L".."sv;
 
+        // LWG-3699: `lexically_relative` on UNC drive paths (`\\?\C:\...`) results in a default-constructed value
+        // This avoids doing any unnecessary copies;
+        // the return value of `relative_path()` is lifetime extended if necessary.
```
Comment (StephanTLavavej) [inline stl/inc/filesystem:1697]: Hyphenate compound adjective:
```suggestion
        // the return value of `relative_path()` is lifetime-extended if necessary.
```

File: stl/inc/filesystem [hunk 6]
```diff
@@ -1686,23 +1686,33 @@ namespace filesystem {
...
+            _Is_drive_prefix_with_slash_slash_question(_Base_.native()) ? _Base_.relative_path() : _Base_;
+
         path _Result;
 
-        if (root_name() != _Base.root_name() || is_absolute() != _Base.is_absolute()
-            || (!has_root_directory() && _Base.has_root_directory()) || _Relative_path_contains_root_name(*this)
-            || _Relative_path_contains_root_name(_Base)) {
+        if (_This.root_name() != _Base.root_name() || _This.is_absolute() != _Base.is_absolute()
+            || (!_This.has_root_directory() && _Base.has_root_directory())
+            || (_Relative_path_contains_root_name(_This) || _Relative_path_contains_root_name(_Base))) {
```
Comment (StephanTLavavej) [inline stl/inc/filesystem:1706]: Question: Why are extra parens being introduced here? This is continuing a logical-OR chain so there are no precedence issues. The similarity in the conditions `_Relative_path_contains_root_name(_This)` and `_Relative_path_contains_root_name(_Base)` is clear, so there appears to be no need to group them with extra parens.

**Review by StephanTLavavej — CHANGES_REQUESTED** [review]
Looks good to me - all I noticed were very minor issues/questions.

File: stl/inc/filesystem (hunk 6 above)
Comment (strega-nil-ms) [reply stl/inc/filesystem:1706]: I grouped them to follow the logic of the prose better, imo. The prose is written as:

If one of the following is true:
* A
* B
* C and D
* E or F

and so I prefer to write it as a list of or-separated boolean expressions, with each element of the list being fully contained, rather than transforming the final expression by splitting up `E or F` into separate elements. I can revert it, but I do believe it's more readable (one element being on one line, rather than split so that `(C and D) or E` are on one line with `F` being on another), and this doesn't change behavior at all.

Comment (StephanTLavavej) [reply stl/inc/filesystem:1706]: Sounds good, I'm fine with this change!

**Comment by strega-nil-ms** [comment]
@StephanTLavavej fixed :)

**Comment by StephanTLavavej** [comment]
We talked about this at the weekly maintainer meeting and decided that the strategy of "UNC paths can be lexically relative to one another, but not UNC and DOS" is reasonable given the Standard's wording and our behavior here (where we consider `C:` and `c:` to be different for the purposes of lexically relative).

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
Thanks for improving filesystem behavior on Windows! :file_cabinet: :card_index_dividers: :floppy_disk:

**Comment by ZubairRafiq** [comment]
```
`#include` <filesystem> #include <vector)
#include <string> #include <iostream>

struct Result {
      std::string s1;
      std::string s2;
      }
Result test () {
      std::string test = {R" (\\?\C:\temp\test-file.txt)");
      std::filesystem::path const p(test);
      
      Result res;
      res.s1.append(p.root_name ().string()); 
      res.s2.append(p.root_path().string());

      std:: cout <‹ std::endl <‹ test <‹ std::endl;
      std::cout <‹ "root_name\t" <‹ p.root_name ().string() <‹ std:: endl;
      std::wcout <‹ L" absolute: " <‹ std::filesystem::absolute (p).wstring() <‹ std::endl; 
      std::cout <‹ "root_directory\t" <‹ p.root_directory().string() <‹ std: :end1; 
      std::cout <‹ "root_path\t" <‹ p.root_path().string() <‹ std::endl;
      std::cout <‹ "relative_path\t" <‹ p.relative_path ().string() <‹ std:: end1; 
      std::cout <‹ "parent_path\t" <‹ p.parent_path().string() ‹‹ std::endl;
      return res;
}
```


The output:
root name
absolute: w:?\C: \temp\test-file.txt
root directory
root_path
relative_path ?\C:\temp\test-file.txt
parent_path \?\C:\temp

The “root name” component extracted from the path is reported as an empty string (`””`). However, the expected value was “`C:`”, which represents the drive letter of the path.

The root directory output is `"\"`, however it should be `"C:\"`.
What is the reason for this behavior of std::filesystem::path?
