### PR TITLE
Use _mm_pause, load loop

### LINKED ISSUE #370: atomic.cpp: Spinlock powering shared_ptr atomics can lead to priority inversion
**Describe the bug**
shared_ptr's atomic functions (e.g. `std::atomic_store`) are powered by an external lock present in our separately compiled machinery, `_Lock_shared_ptr_spin_lock` and `_Unlock_shared_ptr_spin_lock`. This was written to use a plain spin lock with no mitigation to go to sleep if spinning is taking too long, nor is there any mitigation for memory bandwidth consumption.

https://github.com/microsoft/STL/blob/aa0a7a3d859ade0f6f1ff13aa4ef74b3d5ce2326/stl/src/atomic.cpp#L13-L34

In single threaded scenarios this is particularly bad when a low priority thread currently holds the spinlock, and a high priority thread spins "effectively forever".

In an ABI breaking release, it would be nice to reuse the low order bit of the reference count control block pointer in the shared_ptr; but even without an ABI breaking release we could do better by replacing the spinlock entirely with something like `SRWLOCK` on Vista and later, implementing exponential backoff, or relying on C++20 `std::atomic` waiting features once we have those implemented.

Also tracked by Developer Community as DevCom-716238 and Microsoft-internal VSO-975564.

### LINKED ISSUE #680: <xatomic.h>: Consider adding _mm_pause on x86/x64
I'm referring to this part:
https://github.com/microsoft/STL/blob/260cfafb634fe3ed64aa33242753d474170d2e2f/stl/inc/xatomic.h#L26-L40

In particular, this line:
https://github.com/microsoft/STL/blob/260cfafb634fe3ed64aa33242753d474170d2e2f/stl/inc/xatomic.h#L31

In `"winnt.h"` it is defined as follows:
`#define YieldProcessor _mm_pause`

In [documentation on YieldProcessor](https://docs.microsoft.com/en-us/windows/win32/api/winnt/nf-winnt-yieldprocessor) use of `pause` instruction is documented:
>This macro can be called on all processor platforms where Windows is supported, but it has no effect on some platforms. The definition varies from platform to platform. The following are some definitions of this macro in Winnt.h:
> ```
> #define YieldProcessor() __asm { rep nop }
> #define YieldProcessor _mm_pause
> #define YieldProcessor __yield
> ```

Other synchronization libraries also make use of `pause` instruction.

@BillyONeal explained in https://github.com/microsoft/STL/issues/613#issuecomment-599713348:
> The answer I've heard from folks that supposedly know better is "never `_mm_pause` ever" -- that macro was defined long before my time but it was defined as empty for x86/x64 and I don't think we would want to change that without extremely strong profiling evidence that it was a good idea.

Though I understand that there are some folks that know something, it all highly suspicious that this STL is the only library I know that avoids `pause`.

### PR DESCRIPTION
**Pull request by AlexGuteniev**
Resolves #680

### CODE REVIEW

File: stl/inc/xatomic.h [hunk 1]
```diff
@@ -28,7 +28,13 @@ _STL_DISABLE_CLANG_WARNINGS
 #define _INTRIN_ACQUIRE(x) x
 #define _INTRIN_RELEASE(x) x
 #define _INTRIN_ACQ_REL(x) x
+#ifdef _M_CEE_PURE
 #define _YIELD_PROCESSOR()
+#else //  ^^^ _M_CEE_PURE / !_M_CEE_PURE vvv
+extern "C" __MACHINEX86_X64(void _mm_pause(void))
```
Comment (BillyONeal) [inline stl/inc/xatomic.h:34]: This needs to be moved to `intrin0.h` rather than redeclared here.

File: stl/src/atomic.cpp [hunk 2]
```diff
@@ -4,33 +4,87 @@
...
-volatile long _Shared_ptr_flag;
+namespace {
+    // MUTEX FOR shared_ptr ATOMIC OPERATIONS
+    SRWLOCK _Shared_ptr_lock = SRWLOCK_INIT;
 
-_CRTIMP2_PURE void __cdecl _Lock_shared_ptr_spin_lock() { // spin until _Shared_ptr_flag successfully set
-#ifdef _M_ARM
-    while (_InterlockedExchange_acq(&_Shared_ptr_flag, 1)) {
-        __yield();
+#if _STL_WIN32_WINNT < _STL_WIN32_WINNT_VISTA
```
Comment (BillyONeal) [inline stl/src/atomic.cpp:18]: This may become unnecessary due to SHA1 stuff. Let me follow up with setup folks.

File: stl/src/atomic.cpp [hunk 3]
```diff
@@ -4,33 +4,87 @@
...
+_EXTERN_C
+
+_CRTIMP2_PURE void __cdecl _Lock_shared_ptr_spin_lock() { // spin until _Shared_ptr_flag successfully set
+#if _STL_WIN32_WINNT >= _STL_WIN32_WINNT_VISTA
+    AcquireSRWLockExclusive(_Shared_ptr_lock);
+#else // ^^^ _STL_WIN32_WINNT >= _STL_WIN32_WINNT_VISTA / _STL_WIN32_WINNT < _STL_WIN32_WINNT_VISTA vvv
+    if (_Acuire_srw_functions()) {
+        _Table._Pfn_AcquireSRWLockExclusive.load(_STD memory_order_relaxed)(&_Shared_ptr_lock);
+    } else {
+        while (_interlockedbittestandset(&_Shared_ptr_flag, 0) != 0) { // set bit 0
```
Comment (BillyONeal) [inline stl/src/atomic.cpp:69]: It seems like this should use `cmpxchg`. But also might be unnecessary :)

File: stl/src/atomic.cpp [hunk 4]
```diff
@@ -4,33 +4,87 @@
...
-#ifdef _M_ARM
-    __dmb(_ARM_BARRIER_ISH);
-    __iso_volatile_store32(reinterpret_cast<volatile int*>(&_Shared_ptr_flag), 0);
-#else // _M_ARM
-    _interlockedbittestandreset(&_Shared_ptr_flag, 0); // reset bit 0
-#endif // _M_ARM
+#if _STL_WIN32_WINNT >= _STL_WIN32_WINNT_VISTA
+    ReleaseSRWLockExclusive(&_Shared_ptr_lock);
+#else // ^^^ _STL_WIN32_WINNT >= _STL_WIN32_WINNT_VISTA / _STL_WIN32_WINNT < _STL_WIN32_WINNT_VISTA vvv
+    if (_Acuire_srw_functions()) {
```
Comment (BillyONeal) [inline stl/src/atomic.cpp:82]: If we keep this it shouldn't try to acquire again: if someone called this that means they already called lock

**Comment by BillyONeal** [comment]
If we're adding `_mm_pause` I think we should follow the solution that checks `__rdtsc` as demonstrated in the Intel Architecture Optimization Manual.

File: stl/src/atomic.cpp [hunk 5]
```diff
@@ -4,33 +4,87 @@
...
+
+
+    struct _Srw_functions_table {
+        _STD atomic<decltype(&::AcquireSRWLockExclusive)> _Pfn_AcquireSRWLockExclusive{nullptr};
+        _STD atomic<decltype(&::ReleaseSRWLockExclusive)> _Pfn_ReleaseSRWLockExclusive{nullptr};
+    };
+
+    _Srw_functions_table _Table;
+
+    bool _Acuire_srw_functions() {
```
Comment (StephanTLavavej) [inline stl/src/atomic.cpp:30]: "acquire" typo.

File: stl/src/atomic.cpp [hunk 6]
```diff
@@ -4,33 +4,87 @@
...
+        enum class _Shared_ptr_api_level : char {
+            __has_nothing = false,
+            __has_srwlock = true,
+            __not_set,
+        };
```
Comment (StephanTLavavej) [inline stl/src/atomic.cpp:35]: It's unusual (in our codebase) to convert `false` and `true` to `char` like this. I would expect these to be explicitly given the values `0`, `1`, and `2`.

File: stl/src/atomic.cpp [hunk 7]
```diff
@@ -4,33 +4,87 @@
...
+                    GetProcAddress(_Kernel32, "ReleaseSRWLockExclusive"));
+                if (_Pfn_AcquireSRWLockExclusive != nullptr && _Pfn_ReleaseSRWLockExclusive != nullptr) {
+                    _Table._Pfn_AcquireSRWLockExclusive.store(_Pfn_AcquireSRWLockExclusive, _STD memory_order_relaxed);
+                    _Table._Pfn_ReleaseSRWLockExclusive.store(_Pfn_ReleaseSRWLockExclusive, _STD memory_order_relaxed);
+                    _Current = _Shared_ptr_api_level::__has_srwlock;
+                }
+            }
+            _Api_level.store(_Current, _STD memory_order_release);
+        }
+        return reinterpret_cast<bool&>(_Current);
```
Comment (StephanTLavavej) [inline stl/src/atomic.cpp:55]: I believe `static_cast<bool>` would be simpler/less scary.

File: stl/src/atomic.cpp [hunk 8]
```diff
@@ -4,33 +4,87 @@
...
+            __has_srwlock = true,
+            __not_set,
+        };
+        static _STD atomic<_Shared_ptr_api_level> _Api_level{_Shared_ptr_api_level::__not_set};
+
+        _Shared_ptr_api_level _Current = _Api_level.load(_STD memory_order_acquire);
+        if (_Current == _Shared_ptr_api_level::__not_set) {
+            _Current          = _Shared_ptr_api_level::__has_nothing;
+            HMODULE _Kernel32 = GetModuleHandleW(L"Kernel32.dll");
+            if (_Kernel32 != nullptr) {
```
Comment (StephanTLavavej) [inline stl/src/atomic.cpp:42]: Is this permitted for OneCore? (winapisupp.cpp doesn't seem to think we can call GetModuleHandleW.)

File: stl/src/atomic.cpp (hunk 3 above)
Comment (AlexGuteniev) [reply stl/src/atomic.cpp:69]: We need to keep the bit 1, and query if it was 0. `lock cmpxchg`, `xchg` or `lock bts` will all do. I'm trying to avoid `lock cmpxchg` overhead, so keeping `lock bts`.

Inner load loop is to avoid needed cache line in exclusive state when we keep waiting for a good value. It is an optimization. note that `lock cmpxchg` will not perform this optimization, even if it does not do store on failure (which is also questionable)

File: stl/src/atomic.cpp (hunk 8 above)
Comment (AlexGuteniev) [reply stl/src/atomic.cpp:43]: It is under `_STL_WIN32_WINNT < _STL_WIN32_WINNT_VISTA`

File: stl/src/atomic.cpp (hunk 7 above)
Comment (AlexGuteniev) [reply stl/src/atomic.cpp:56]: It is an optimization: https://godbolt.org/z/5Y5h5P
Though can perform it differently.

File: stl/src/atomic.cpp (hunk 4 above)
Comment (AlexGuteniev) [reply stl/src/atomic.cpp:83]: I don't get it.

File: stl/src/atomic.cpp (hunk 7 above)
Comment (AlexGuteniev) [reply stl/src/atomic.cpp]: avoided `bool`

File: stl/src/atomic.cpp (hunk 6 above)
Comment (AlexGuteniev) [reply stl/src/atomic.cpp]: avoided `bool`, now it is really just an enum

File: stl/src/atomic.cpp (hunk 3 above)
Comment (BillyONeal) [reply stl/src/atomic.cpp:69]: > We need to keep the bit 1, and query if it was 0. `lock cmpxchg`, `xchg` or `lock bts` will all do. I'm trying to avoid `lock cmpxchg` overhead, so keeping `lock bts`.
> 

As far as I understand the expensive part of all `lock` instructions is the `lock` part of the instruction, not what the particular instruction does. Why is `lock bts` lower overhead than `lock cmpxchg`? The biggest thing I'm aware of there is that `bts` only works with 32 bit input but `cmpxchg` works with any size input.

> Inner load loop is to avoid needed cache line in exclusive state when we keep waiting for a good value. It is an optimization. note that `lock cmpxchg` will not perform this optimization, even if it does not do store on failure (which is also questionable)

Yes that was always fine and wasn't commenting on that :)

Comment (BillyONeal) [reply stl/src/atomic.cpp:69]: I note that the examples in Intel's optimization manuals all use `cmpxchg` or `xchg`.

File: stl/src/atomic.cpp (hunk 4 above)
Comment (BillyONeal) [reply stl/src/atomic.cpp]: What I mean is that this is trying to detect whether the SRW functions are present again, but we don't need to do that detection here. If a thread is calling `unlock`, it must have once already called `lock`, and when it called `lock` we did the detection attempt. So here we should be able to do something like:

```
const auto _Local_release = _Table._Pfn_ReleaseSRWLockExclusive.load(memory_order_relaxed);
if (_Local_release) { _Local_release(...); }
else { /* ... */ }
```

File: stl/src/atomic.cpp (hunk 3 above)
Comment (AlexGuteniev) [reply stl/src/atomic.cpp:69]: I think apart from the `lock` part, there's a small part of instruction itself (latency, dependencies, regs clobering), and (pre-existing) `lock bts` had it smaller.

Comment (AlexGuteniev) [reply stl/src/atomic.cpp:69]: I see, will investigate that

File: stl/src/atomic.cpp (hunk 4 above)
Comment (AlexGuteniev) [reply stl/src/atomic.cpp]: Yes, makes sense

**Comment by AlexGuteniev** [comment]
> If we're adding `_mm_pause` I think we should follow the solution that checks `__rdtsc` as demonstrated in the Intel Architecture Optimization Manual.

I don't think it is good to follow **Example 2-3. Dynamic Pause Loop Example** with `__rdtsc`, as I believe exact timing is subject to tuning for specific CPU, and cannot be done in a generic way.

Yet **Example 2-4. Contended Locks with Increasing Back-off Example** looks like what I want, and I think it is safe to upgrade from *Baseline Version* I'm proposing to *Improved Version*

File: stl/src/atomic.cpp (hunk 3 above)
Comment (AlexGuteniev) [reply stl/src/atomic.cpp]: Observed effect from changing one instruction to another is negligible compared to `_mm_pause` and `load` effect, and is less than the variation between runs. Apparently there's no performance reason to prefer one of instruction over another. Picking `xchg` for convenience.

File: stl/src/atomic.cpp (hunk 2 above)
Comment (BillyONeal) [reply stl/src/atomic.cpp:18]: Setup folks confirmed today that this XP support machinery can be removed. (We still need to maintain ABI compatibility with static libs that were built with the `v140_xp` and `v141_xp` toolsets, but this change does that)

Comment (AlexGuteniev) [reply stl/src/atomic.cpp]: Updated the change

File: stl/inc/atomic [hunk 9]
```diff
@@ -418,21 +418,42 @@ void _Atomic_wait_direct(
...
+    while (_InterlockedExchange(&_Spinlock, 1) != 0) {
+        while (__iso_volatile_load32(&reinterpret_cast<int&>(_Spinlock)) != 0) {
+            for (int i = _Current_backoff; i != 0; --i) {
+                _mm_pause();
+            }
+            _Current_backoff = _Current_backoff < _Max_backoff ? _Current_backoff << 1 : _Max_backoff;
+        }
     }
+#elif defined(_M_ARM) || defined(_M_ARM64)
+    while (/* TRANSITION, GH-1133, _InterlockedExchange_acq*/ _InterlockedExchange(&_Spinlock, 1) != 0) {
```
Comment (CaseyCarter) [inline stl/inc/atomic:437]: Could we please move the comment out of the code, a la:
```suggestion
    while (_InterlockedExchange(&_Spinlock, 1) != 0) { /* TRANSITION, GH-1133: _InterlockedExchange_acq
```

File: stl/inc/atomic [hunk 10]
```diff
@@ -418,21 +418,42 @@ void _Atomic_wait_direct(
...
+    }
+#else // ^^^ defined(_M_ARM) || defined(_M_ARM64) ^^^
+#error Unsupported hardware
+#endif
 }
 
 inline void _Atomic_lock_release(long& _Spinlock) noexcept {
-#if defined(_M_ARM) || defined(_M_ARM64)
+#if defined(_M_IX86) || defined(_M_X64)
+    _InterlockedExchange(&_Spinlock, 0); // TRANSITION, GH-1133: should use __iso_volatile_store32
```
Comment (CaseyCarter) [inline stl/inc/atomic:449]: Let's format this consistently with the earlier comment:
```suggestion
    _InterlockedExchange(&_Spinlock, 0); // TRANSITION, GH-1133: __iso_volatile_store32
```

File: stl/inc/xatomic.h [hunk 11]
```diff
@@ -10,6 +10,9 @@
 #if _STL_COMPILER_PREPROCESSOR
 
 #include <intrin0.h>
+#if 1 // TRANSITION, Visual Studio 2019 to include _mm_pause in <intrin0.h>
```
Comment (CaseyCarter) [inline stl/inc/xatomic.h:13]: I think it would be better to file an issue to track this change to `<intrin0.h>` and reference that issue in the TRANSITION comments here.

File: stl/inc/atomic [hunk 12]
```diff
@@ -418,21 +418,42 @@ void _Atomic_wait_direct(
...
-    while (_InterlockedExchange(&_Spinlock, 1)) {
-        _YIELD_PROCESSOR();
+#if defined(_M_IX86) || defined(_M_X64)
+    // Algorithm from Intel(R) 64 and IA-32 Architectures Optimization Reference Manual, September 2019
+    // Example 2-4. Contended Locks with Increasing Back-off Example - Improved Version, page 2-21
+    int _Current_backoff   = 1;
+    const int _Max_backoff = 64;
+    while (_InterlockedExchange(&_Spinlock, 1) != 0) {
+        while (__iso_volatile_load32(&reinterpret_cast<int&>(_Spinlock)) != 0) {
+            for (int i = _Current_backoff; i != 0; --i) {
```
[the remark this answers is not in the document]
Comment (AlexGuteniev) [reply stl/inc/atomic:430]: ` _Idx` definitely means not "index". Possibly "Ith Delay". Maybe just `_Count`?

File: stl/inc/atomic (hunk 9 above)
Comment (AlexGuteniev) [reply stl/inc/atomic:437]: Will do that.
Wanted traditional `#if 0`, but clang format is very confused about mismatched braces in preprocessor blocks.

File: stl/inc/atomic (hunk 12 above)
[the remark this answers is not in the document]
Comment (CaseyCarter) [reply stl/inc/atomic]: Works for me.

File: stl/inc/atomic [hunk 13]
```diff
@@ -418,21 +418,42 @@ void _Atomic_wait_direct(
...
+    }
+#else // ^^^ defined(_M_ARM) || defined(_M_ARM64) ^^^
+#error Unsupported hardware
+#endif
 }
 
 inline void _Atomic_lock_release(long& _Spinlock) noexcept {
-#if defined(_M_ARM) || defined(_M_ARM64)
+#if defined(_M_IX86) || defined(_M_X64)
+    _InterlockedExchange(&_Spinlock, 0); // TRANSITION, GH-1133: same  as ARM
```
Comment (StephanTLavavej) [inline stl/inc/atomic:449]:
```suggestion
    _InterlockedExchange(&_Spinlock, 0); // TRANSITION, GH-1133: same as ARM
```

File: stl/inc/atomic [hunk 14]
```diff
@@ -418,21 +418,42 @@ void _Atomic_wait_direct(
...
 #endif // _HAS_CXX20
 
-#if 1 // TRANSITION, ABI
+#if 1 // TRANSITION, ABI, GH-1151
 inline void _Atomic_lock_acquire(long& _Spinlock) noexcept {
-    while (_InterlockedExchange(&_Spinlock, 1)) {
-        _YIELD_PROCESSOR();
+#if defined(_M_IX86) || defined(_M_X64)
+    // Algorithm from Intel(R) 64 and IA-32 Architectures Optimization Reference Manual, September 2019
+    // Example 2-4. Contended Locks with Increasing Back-off Example - Improved Version, page 2-21
```
Comment (StephanTLavavej) [inline stl/inc/atomic:425]: I think we need to obtain the proper blessings for this.

File: stl/inc/xatomic.h [hunk 15]
```diff
@@ -31,7 +34,11 @@ _STL_DISABLE_CLANG_WARNINGS
 #define _INTRIN_ACQUIRE(x) x
 #define _INTRIN_RELEASE(x) x
 #define _INTRIN_ACQ_REL(x) x
+#ifdef _M_CEE_PURE
 #define _YIELD_PROCESSOR()
+#else //  ^^^ _M_CEE_PURE / !_M_CEE_PURE vvv
```
Comment (StephanTLavavej) [inline stl/inc/xatomic.h:39]:
```suggestion
#else // ^^^ _M_CEE_PURE / !_M_CEE_PURE vvv
```

File: stl/inc/atomic (hunk 14 above)
Comment (AlexGuteniev) [reply stl/inc/atomic:425]: Moved `atomic,cpp` part to #1200

Comment (BillyONeal) [reply stl/inc/atomic:425]: I'm not sure we need anything specific; the "algorithm" / what this is doing is indeed from the optimization manual in the sense that it asks to use increasing numbers of `_mm_pause` over time, but to me that's on the same level as saying 'std::vector is a dynamic array that reallocates when it runs out of space'.

File: stl/inc/atomic [hunk 16]
```diff
@@ -418,21 +418,42 @@ void _Atomic_wait_direct(
 }
 #endif // _HAS_CXX20
 
-#if 1 // TRANSITION, ABI
+#if 1 // TRANSITION, ABI, GH-1151
 inline void _Atomic_lock_acquire(long& _Spinlock) noexcept {
-    while (_InterlockedExchange(&_Spinlock, 1)) {
-        _YIELD_PROCESSOR();
+#if defined(_M_IX86) || defined(_M_X64)
+    // Algorithm from Intel(R) 64 and IA-32 Architectures Optimization Reference Manual, September 2019
```
Comment (BillyONeal) [inline stl/inc/atomic:424]:
```suggestion
    // Algorithm from Intel(R) 64 and IA-32 Architectures Optimization Reference Manual, May 2020

```

Comment (BillyONeal) [reply stl/inc/atomic:424]: (I checked that it's still on the same page)

Comment (BillyONeal) [reply stl/inc/atomic:424]: Alternately I'm not sure we need to mention this at all, I don't think there's anything novel being consumed from the optimization manual here beyond "you should implement exponential backoff using increasing amounts of pause".

File: stl/inc/atomic (hunk 14 above)
Comment (BillyONeal) [inline stl/inc/atomic:425]:
```suggestion
    // Algorithm from Intel(R) 64 and IA-32 Architectures Optimization Reference Manual, May 2020
    // Example 2-4. Contended Locks with Increasing Back-off Example - Improved Version, page 2-22

```

Alternately we should drop this reference completely; it's not like the manual saying 'you should implement exponential backoff' is particularly novel.

**Comment by cbezault** [comment]
I've finally heard back from Intel concerning the code snippet from the manual. The code in the manual is licensed under the [0BSD ](https://choosealicense.com/licenses/0bsd/) license. This means we don't need to provide any attribution, license, or copyright text. Our lawyers have suggested just keeping the comment text as-is, additionally noting the 0BSD license (nothing formal is needed).

**Comment by AlexGuteniev** [comment]
Updated. There's still GH-1197

File: stl/inc/xatomic.h [hunk 17]
```diff
@@ -10,6 +10,9 @@
 #if _STL_COMPILER_PREPROCESSOR
 
 #include <intrin0.h>
+#if 1 // TRANSITION, GH-1197
+#include <intrin.h>
+#endif // TRANSITION, GH-1197
```
Comment (CaseyCarter) [inline stl/inc/xatomic.h:15]: I'd prefer to simply declare `_mm_pause` directly here. I'm preparing the fix for #1197 to apply internally, and once that's done - so we can be "certain" of the VS version it will ship in - I'll apply a change here. (And cleanup the TRANSITION below while I'm at it.)

File: stl/inc/atomic [hunk 18]
```diff
@@ -418,21 +418,43 @@ void _Atomic_wait_direct(
...
 
-#if 1 // TRANSITION, ABI
+#if 1 // TRANSITION, ABI, GH-1151
 inline void _Atomic_lock_acquire(long& _Spinlock) noexcept {
-    while (_InterlockedExchange(&_Spinlock, 1)) {
-        _YIELD_PROCESSOR();
+#if defined(_M_IX86) || defined(_M_X64)
+    // Algorithm from Intel(R) 64 and IA-32 Architectures Optimization Reference Manual, May 2020
+    // Example 2-4. Contended Locks with Increasing Back-off Example - Improved Version, page 2-22
+    // The code in mentioned manual is distributed under0BSD license
```
Comment (CaseyCarter) [inline stl/inc/atomic:426]:
```suggestion
    // The code in mentioned manual is covered by the 0BSD license.
```

**Review by CaseyCarter — CHANGES_REQUESTED** [review]
I've "requested changes" here which I'll apply myself after the fix for GH-1197 is applied internally (`intrin.h` and `intrin0.h` are part of vcruntime which is not yet opensource).

**Review by CaseyCarter — APPROVED** [review]
I've pushed a change to (1) define `_mm_pause` directly in `xatomic.h` during the transition until the vcruntime change to `intrin0.h` goes live, and (2) Do The Right Thing in ARM64EC mode.

**Comment by AlexGuteniev** [comment]
I see that everything looks complete now

File: stl/inc/atomic (hunk 14 above)
Comment (CaseyCarter) [reply stl/inc/atomic]: Word from Intel is that all code in the pertinent manual is covered by [0BSD](https://opensource.org/licenses/0BSD). We've added a comment annotating that fact.

**Comment by CaseyCarter** [comment]
> I see that everything looks complete now

Thanks for the reminder: I've resolved all open comments and moved this back to Final Review.

File: tests/std/include/test_atomic_wait.hpp [hunk 19]
```diff
@@ -43,7 +43,7 @@ void test_atomic_wait_func_impl(UnderlyingType& old_value, const UnderlyingType
         // timing assumption that the main thread evaluates the `wait(old_value)` before this timeout expires
         std::this_thread::sleep_for(waiting_duration);
         add_seq('6');
-#endif // CAN_FAIL_ON_TIMING_ASSUMPTION
```
Comment (StephanTLavavej) [inline tests/std/include/test_atomic_wait.hpp:46]: I'm not sure why this is being removed (more than 1 line is guarded) but as there are no nearby preprocessor guards, no change requested.

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Thanks for this performance improvement! This PR went through quite a *pause* but it should be worth the wait. :pause_button: :joy_cat:
