### PR TITLE
[copy_file] allow `FILE_SHARE_*`

### LINKED ISSUE #2185: <filesystem>: copy_file(a, b, update_existing) fails when b is locked even if no copy is needed
**Describe the bug**
Consider a case where the target file is newer (or the same date) as the source file, but the target file has a lock being held somewhere. copy_file will complain about the lock being present on the target file, despite not having to copy the file.

**Command-line test case**
```
C:\Temp>type repro.cpp
#include <filesystem>
#include <fstream>
#include <iostream>
#include <string_view>
#include <Windows.h>

void write_to_file(const std::filesystem::path& file, std::string_view contents)
{
    std::ofstream stream(file);
    stream << contents;
}

int main()
{
    write_to_file(L"old.txt", "old contents");
    Sleep(10); // make sure the timestamps differ.
    write_to_file(L"new.txt", "new contents");

    // hold an exclusive handle to the file. in real world a third party program may do that.
    CreateFileW(L"new.txt", GENERIC_READ, 0, nullptr, OPEN_EXISTING, 0, nullptr);
    try
    {
        std::filesystem::copy_file("old.txt", "new.txt", std::filesystem::copy_options::update_existing);
    }
    catch (const std::filesystem::filesystem_error& err)
    {
        std::cout << err.what();
    }
}

C:\Temp>cl /EHsc /std:c++17 .\repro.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.30.30423 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

repro.cpp
Microsoft (R) Incremental Linker Version 14.30.30423.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:repro.exe
repro.obj

C:\Temp>.\repro.exe
copy_file: The process cannot access the file because it is being used by another process.: "old.txt", "new.txt"
```

**Expected behavior**
Since a copy isn't needed here, there should be no failure.

**STL version**
```
Microsoft Visual Studio Community 2022 Preview (64-bit)
Version 17.0.0 Preview 3.1
```

**Additional context**
This happens because `__std_fs_copy_file` opens a handle with exclusive access (no sharing), to check the last write time. Instead of opening an handle, `GetFileAttributesEx` can be used. It won't open an handle and will give the last write time.

### PR DESCRIPTION
**Pull request by strega-nil-ms**
The existing code does not allow other programs to hold read permissions
on `_Source` or `_Target` when
copy_options = overwrite_existing or skip_existing.
We could very easily allow reading, and could also allow writing for
skip_existing, except for a clever implementation of equivalent,
so just switch to a dumb implementation of equivalent here.

Fixes #2185

### CODE REVIEW

File: stl/src/filesystem.cpp [hunk 1]
```diff
@@ -9,6 +9,7 @@
 // Do not include or define anything else here.
 // In particular, basic_string must not be included here.
 
+#include <algorithm>
```
Comment (StephanTLavavej) [inline stl/src/filesystem.cpp:12]: Same concern as in https://github.com/microsoft/STL/pull/2715#discussion_r871953749 about including `<algorithm>` in a translation unit that's being injected into the import lib. It looks like the only use is for `_RANGES equal(_Target_id.FileId.Identifier, _Source_id.FileId.Identifier)`. As this is:

```c
typedef struct _FILE_ID_128 {
    BYTE  Identifier[16];
} FILE_ID_128, *PFILE_ID_128;
```

I think that it would be simple to call `_CSTD memcmp`.

File: stl/src/filesystem.cpp [hunk 2]
```diff
@@ -353,45 +354,68 @@ void __stdcall __std_fs_directory_iterator_close(_In_ const __std_fs_dir_handle
...
-                return {false, _Last_error};
+                if (_Target_last_write_time < _Source_last_write_time) { // _Target is newer, so update_existing
+                    _Do_copy = true;
+                }
             }
 
-            if (_Source_last_write_time <= _Target_last_write_time) { // _Target is newer, so don't update_existing
+            if (!_Do_copy) {
+                // We only need to test `equivalent()` if we _aren't_ going to `CopyFileW()`,
+                // since that call will fail with an `ERROR_SHARING_VIOLATION` anyways.
```
Comment (BillyONeal) [inline stl/src/filesystem.cpp:403]: This is Desktop and Recent only so you need this fallback: https://github.com/microsoft/STL/blob/4cd7ff723c1a28ae2a757b4856bf6ca795492b10/stl/src/filesystem.cpp#L461

File: stl/src/filesystem.cpp [hunk 3]
```diff
@@ -353,45 +354,68 @@ void __stdcall __std_fs_directory_iterator_close(_In_ const __std_fs_dir_handle
...
+                _Last_error = _Get_last_write_time_by_handle(_Target_handle._Get(), &_Target_last_write_time);
+                if (_Last_error != __std_win_error::_Success) {
+                    return {false, _Last_error};
+                }
 
-            long long _Target_last_write_time;
-            _Last_error = _Get_last_write_time_by_handle(_Target_handle._Get(), &_Target_last_write_time);
-            if (_Last_error != __std_win_error::_Success) {
-                return {false, _Last_error};
+                if (_Target_last_write_time < _Source_last_write_time) { // _Target is newer, so update_existing
```
Comment (StephanTLavavej) [inline stl/src/filesystem.cpp:396]: I believe that this comment is being damaged. The code originally said:

```cpp
if (_Source_last_write_time <= _Target_last_write_time) { // _Target is newer, so don't update_existing
```

With timestamps, greater means newer, so the comment matches the code (except for not mentioning the "same age" case).

Now the code says:

```cpp
if (_Target_last_write_time < _Source_last_write_time) { // _Target is newer, so update_existing
```

This code detects when the target is *older*. (The "so update_existing" part is correct, though.)

**Review by StephanTLavavej — CHANGES_REQUESTED** [review]

File: stl/src/filesystem.cpp (hunk 2 above)
Comment (StephanTLavavej) [reply stl/src/filesystem.cpp:403]: I see - [`GetFileInformationByHandleEx`](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-getfileinformationbyhandleex) is documented as:

> **Minimum supported client** Windows Vista [desktop apps | UWP apps]
> **Minimum supported server** Windows Server 2008 [desktop apps | UWP apps]

However, [`FILE_ID_INFO`](https://docs.microsoft.com/en-us/windows/win32/api/winbase/ns-winbase-file_id_info) says:

> **Minimum supported client** None supported
> **Minimum supported server** Windows Server 2012 [desktop apps only]

Excellent catch! It looks like the proper thing to do is to call the `__std_fs_get_file_id()` that you cited (instead of trying to replicate what it does).

File: stl/src/filesystem.cpp [hunk 4]
```diff
@@ -126,6 +126,40 @@ namespace {
...
+        }
+
+        _Last_error = __std_win_error{GetLastError()};
+#endif // _CRT_APP
+
+        return _Last_error;
+    }
+
+
     struct _File_disposition_info_ex {
```
Comment (StephanTLavavej) [inline stl/src/filesystem.cpp:163]: There's a merge conflict now that #2714 has landed. It should be simple to resolve - you're adding code immediately above where I deleted `_File_disposition_info_ex`.

**Review by StephanTLavavej — CHANGES_REQUESTED** [review]

**Review by StephanTLavavej — APPROVED** [review]

File: stl/src/filesystem.cpp [hunk 5]
```diff
@@ -126,6 +126,39 @@ namespace {
...
+        _Last_error = __std_win_error{GetLastError()};
+        switch (_Last_error) {
+        case __std_win_error::_Not_supported:
+        case __std_win_error::_Invalid_parameter:
+            break; // try more things
+        default:
+            return _Last_error; // real error, bail to the caller
+        }
+
+#ifndef _CRT_APP
```
Comment (miscco) [inline stl/src/filesystem.cpp:146]: Can we simplify the else case to simply be `return __std_win_error{...}` and move the switch into here

Comment (StephanTLavavej) [reply stl/src/filesystem.cpp:146]: This is pre-existing code that's being extracted from `__std_fs_get_file_id()`. I see what you're suggesting, and the control flow transformation wouldn't be risky, but my general preference is to avoid significantly altering code when moving it (unless it's necessary). We can do this as a followup cleanup, since this doesn't affect correctness or performance.

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
Thanks for teaching the STL how to play nice and share!

:joy_cat: :open_file_folder: :tada:
===
