### PR TITLE
Fix construct tag

### LINKED ISSUE #468: STL: Consistently use empty braces to construct tags like _Meow{}
In the STL, "tag dispatch" is one of our oldest and most common metaprogramming techniques. When we need to construct temporary tags, we had to say `_Meow()` in C++98/03. Now, we prefer to say `_Meow{}`, because this avoids looking like a function call. We're trying to follow that style in new code, but there's lots of existing code that should be updated.

For example, the `_Zero_then_variadic_args_t` and `_One_then_variadic_args_t` tag types:
https://github.com/microsoft/STL/blob/fd04f77dd217a7502c77e0cbf45e24fcb84ed17c/stl/inc/vector#L444-L450

As I recall, the difference between `T()` and `T{}` can be detected by extremely unusual user code, so we shouldn't change how any user-defined types are constructed (e.g. comparison function objects). However, STL-internal tags can be freely changed.

Additionally, for STL-internal tag types, we should strongly consider giving them `explicit` default constructors, following modern practice in the Standard, which prevents unintentional misuse (e.g. passing `{}` where a tag is expected).

### PR DESCRIPTION
**Pull request by JeanPhilippeKernel**
# Description

Fixes #468.

# Checklist

Be sure you've read README.md and understand the scope of this repo.

If you're unsure about a box, leave it unchecked. A maintainer will help you.

- [x] Identifiers in product code changes are properly `_Ugly` as per
  https://eel.is/c++draft/lex.name#3.1 or there are no product code changes.
- [ ] The STL builds successfully and all tests have passed (must be manually
  verified by an STL maintainer before automated testing is enabled on GitHub,
  leave this unchecked for initial submission).
- [x] These changes introduce no known ABI breaks (adding members, renaming
  members, adding virtual functions, changing whether a type is an aggregate
  or trivially copyable, etc.).
- [x] These changes were written from scratch using only this repository,
  the C++ Working Draft (including any cited standards), other WG21 papers
  (excluding reference implementations outside of proposed standard wording),
  and LWG issues as reference material. If they were derived from a project
  that's already listed in NOTICE.txt, that's fine, but please mention it.
  If they were derived from any other project (including Boost and libc++,
  which are not yet listed in NOTICE.txt), you *must* mention it here,
  so we can determine whether the license is compatible and what else needs
  to be done.

### CODE REVIEW

File: stl/inc/codecvt [hunk 1]
```diff
@@ -21,9 +21,9 @@ _STL_DISABLE_CLANG_WARNINGS
 #pragma warning(disable : 4127) // conditional expression is constant
 
 _STD_BEGIN
-#define _LITTLE_FIRST   1
-#define _BIG_FIRST      2
-#define _BYTES_PER_WORD 4
+constexpr int _Little_first   = 1;
+constexpr int _Big_first      = 2;
+constexpr int _Bytes_per_word = 4;
```
Comment (StephanTLavavej) [inline stl/inc/codecvt]: `_BYTES_PER_WORD` appears to have been completely unused and should be eliminated.

File: stl/inc/xmemory [hunk 2]
```diff
@@ -1241,8 +1241,10 @@ using _Iterator_base = _Iterator_base12;
 
 
 // ALIAS TEMPLATE _Container_proxy_ptr AND SUPPORTING MACHINERY
-struct _Leave_proxy_unbound {}; // tag to indicate that a proxy is being allocated before it is safe to bind to a
-                                // _Container_base12
+struct _Leave_proxy_unbound {
+    explicit _Leave_proxy_unbound() = default;
+}; // tag to indicate that a proxy is being allocated before it is safe to bind to a
+   // _Container_base12
```
Comment (StephanTLavavej) [inline stl/inc/xmemory]: This comment can now be unwrapped to a single line. (clang-format wraps excessively long comments, but won't unwrap in situations like this.)

File: stl/inc/xutility [hunk 3]
```diff
@@ -193,18 +193,30 @@ using _Algorithm_int_t = conditional_t<is_integral_v<_Ty>, _Ty, ptrdiff_t>;
...
-struct random_access_iterator_tag : bidirectional_iterator_tag {};
+struct random_access_iterator_tag : bidirectional_iterator_tag {
+    explicit random_access_iterator_tag() = default;
+};
 
 #ifdef __cpp_lib_concepts
-struct contiguous_iterator_tag : random_access_iterator_tag {};
+struct contiguous_iterator_tag : random_access_iterator_tag {
+    explicit contiguous_iterator_tag() = default;
+};
```
Comment (StephanTLavavej) [inline stl/inc/xutility]: Unfortunately, the "explicit default constructor" improvement can't be extended to these Standard types, so please revert this group of changes.

The issue is that WG21-N4849 [std.iterator.tags]/1 (see https://eel.is/c++draft/std.iterator.tags#1 for HTML instead of PDF) specifies the Standard tag types, with implicit default constructors, so we have to match that observable behavior. In contrast, we can do basically whatever we want with internal non-Standard types like `_Priority_tag` below.

File: stl/src/memory_resource.cpp [hunk 4]
```diff
@@ -8,17 +8,18 @@
 _STD_BEGIN
 namespace pmr {
 
-    static memory_resource* _Default_resource = nullptr;
+    static memory_resource* _Default_resource{nullptr};
 
-    extern "C" _CRT_SATELLITE_1 _Aligned_new_delete_resource_impl* __cdecl _Aligned_new_delete_resource() noexcept {
+    _EXTERN_C
+    _CRT_SATELLITE_1 _Aligned_new_delete_resource_impl* __cdecl _Aligned_new_delete_resource() noexcept {
```
Comment (StephanTLavavej) [inline stl/src/memory_resource.cpp]: The `extern "C"` changes in this file are unrelated to the tag changes in the rest of the PR. While this transformation doesn't change the meaning of the code, it introduces inconsistency with the declarations in `<memory_resource>`. If you believe that we should consistently rely on `_EXTERN_C` blocks for declarations and definitions, please file an enhancement issue so we can make a decision - and then if we decide on a convention, it can be cleaned up in a separate PR.

The general principle is that large code transformations/cleanups should be performed in separate PRs for ease of code reviewing and history reading. Mixing in very small changes can be OK (e.g. comment changes, or the ` _Default_resource{nullptr}` initialization change above - that one is at least thematically related to "brace-initialize more things").

I noticed similar changes in #487 but didn't object then because they were small and increased consistency between the declarations and definitions. I probably should have mentioned my concerns though, apologies for not doing so earlier.

File: stl/src/parallel_algorithms.cpp [hunk 5]
```diff
@@ -157,7 +157,7 @@ static DWORD _Get_number_of_processors() noexcept {
     return _Info.dwNumberOfProcessors;
 }
 
-extern "C" {
+EXTERN_C_START
```
Comment (StephanTLavavej) [inline stl/src/parallel_algorithms.cpp]: These are `<Windows.h>` macros, but we conventionally use the STL's macros for this (in fact, I had to look up where this was coming from). I think it would be fine to use the STL macros here in this PR.

File: stl/src/parallel_algorithms.cpp [hunk 6]
```diff
@@ -296,4 +296,4 @@ void __stdcall __std_execution_wake_by_address_all(const volatile void* _Address
 #endif // ^^^ _STL_WIN32_WINNT < _WIN32_WINNT_WIN8 ^^^
 }
 
-} // extern "C"
+EXTERN_C_END // extern "C"
```
Comment (StephanTLavavej) [inline stl/src/parallel_algorithms.cpp]: When changing this to the STL's macro, the comment should also be dropped (as it no longer serves a purpose).

File: stl/src/sharedmutex.cpp [hunk 7]
```diff
@@ -12,8 +12,7 @@
 
 using _Smtx_t = void*;
 
-extern "C" {
-
+EXTERN_C_START
```
Comment (StephanTLavavej) [inline stl/src/sharedmutex.cpp]: Same comments about using STL macros instead of `<Windows.h>` macros.

File: stl/inc/xutility (hunk 3 above)
Comment (JeanPhilippeKernel) [reply stl/inc/xutility]: Oh okay let's revert so !
thanks a lot  !! I didn't aware about that

File: stl/src/memory_resource.cpp (hunk 4 above)
Comment (JeanPhilippeKernel) [reply stl/src/memory_resource.cpp]: Yeah totally right !, let's revert and consider another PR for these changes

> The `extern "C"` changes in this file are unrelated to the tag changes in the rest of the PR. While this transformation doesn't change the meaning of the code, it introduces inconsistency with the declarations in `<memory_resource>`. If you believe that we should consistently rely on `_EXTERN_C` blocks for declarations and definitions, please file an enhancement issue so we can make a decision - and then if we decide on a convention, it can be cleaned up in a separate PR.

Comment (JeanPhilippeKernel) [reply stl/src/memory_resource.cpp]: you don't need to apologies 😉, what do you think about a file  an enhancement issue and assign it to me ? 
> I noticed similar changes in #487 but didn't object then because they were small and increased consistency between the declarations and definitions. I probably should have mentioned my concerns though, apologies for not doing so earlier.

File: stl/src/parallel_algorithms.cpp (hunk 5 above)
Comment (JeanPhilippeKernel) [reply stl/src/parallel_algorithms.cpp]: this means that we should include <yvals_core.h> 
as we said above, let's file a new enhancement issue for a diff PR

**Comment by StephanTLavavej** [comment]
Thank you for improving the codebase's consistency and readability!
