### PR TITLE
Implement LWG-4084 `std::fixed` ignores `std::uppercase`

### LINKED ISSUE #5120: LWG-4084 `std::fixed` ignores `std::uppercase`
LWG-4084 `std::fixed` ignores `std::uppercase`

### PR DESCRIPTION
**Pull request by frederick-vs-ja**
Fixes #5120.

It seems that the outputting Inf/NaN with `uppercase` was never tested before.

### CODE REVIEW

File: tests/std/tests/LWG4084_iostream_uppercase_inf_nan/test.cpp [hunk 1]
```diff
@@ -0,0 +1,104 @@
...
+template <class CharT, size_t NChar, size_t NWChar, enable_if_t<is_same_v<CharT, char>, int> = 0>
+constexpr const auto& choose_literal(const char (&s)[NChar], const wchar_t (&)[NWChar]) noexcept {
+    return s;
+}
+template <class CharT, size_t NChar, size_t NWChar, enable_if_t<is_same_v<CharT, wchar_t>, int> = 0>
+constexpr const auto& choose_literal(const char (&)[NChar], const wchar_t (&ws)[NWChar]) noexcept {
+    return ws;
+}
+
+#define STATICALLY_WIDEN(CharT, S) ::choose_literal<CharT>(S, L##S)
```
Comment (StephanTLavavej) [inline tests/std/tests/LWG4084_iostream_uppercase_inf_nan/test.cpp:21]: These arrays should always be the same size.

File: tests/std/tests/LWG4084_iostream_uppercase_inf_nan/test.cpp [hunk 2]
```diff
@@ -0,0 +1,104 @@
...
+    // LWG-4084 "std::fixed ignores std::uppercase"
+    {
+        auto s = (basic_ostringstream<CharT>{} << fixed << uppercase << numeric_limits<F>::infinity()).str();
+        assert(s == STATICALLY_WIDEN(CharT, "INF"));
+    }
+    {
+        auto s = (basic_ostringstream<CharT>{} << fixed << uppercase << numeric_limits<F>::quiet_NaN()).str();
+        assert(s == STATICALLY_WIDEN(CharT, "NAN"));
+    }
+    // also test other combinations
```
Comment (StephanTLavavej) [inline tests/std/tests/LWG4084_iostream_uppercase_inf_nan/test.cpp:34]: No change requested: This is almost repetitive enough to be worth extracting into table-based test cases, and/or extracting `numeric_limits` into `constexpr` constants, but each of them is still a single line and it's easy enough to see what's being tested.

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
THANKS FOR FIXING THIS BUG! :hammer_and_wrench: :abacus: :joy_cat:
