### PR TITLE
Use memset and memcmp in a bit more cases

### LINKED ISSUE #1183: <algorithm>: fill fails to compile with volatile pointer inputs
**Describe the bug**
Passing volatile pointers to `fill` with arguments that satisfy `_Fill_memset_is_safe` will fail to compile, as that branch calls `memset` which cannot take volatile pointers.

**Command-line test case**
```
E:\Temp>type repro.cpp
#include <cstdlib>
#include <iostream>
#include <algorithm>

void memzero(void* a_dst, std::size_t a_size)
{
    const auto     beg = static_cast<volatile char*>(a_dst);
    const auto     end = static_cast<volatile char*>(a_dst) + a_size;
    constexpr char val = 0;
    std::fill(beg, end, val);
}

int main()
{
    int num = 42;

    std::cout << num << '\n';
    memzero(&num, sizeof(num));
    std::cout << num << '\n';
}

E:\Temp>cl /EHsc /W4 /WX .\repro.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.28.29115 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

repro.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29115\include\xutility(4717): error C2664: 'void *memset(void *,int,size_t)': cannot convert argument 1 from '_FwdIt' to 'void *'
        with
        [
            _FwdIt=volatile char *
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29115\include\xutility(4717): note: Conversion loses qualifiers
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29115\include\vcruntime_string.h(63): note: see declaration of 'memset'
.\repro.cpp(10): note: see reference to function template instantiation 'void std::fill<volatile char*,char>(const _FwdIt,const _FwdIt,const _Ty &)' being compiled
        with
        [
            _FwdIt=volatile char *,
            _Ty=char
        ]
```

**Expected behavior**
The program should compile.

**STL version**
```
Microsoft Visual Studio Community 2019 Preview
Version 16.8.0 Preview 1.0
```

**Additional context**
Both GCC and Clang can compile this example, here's a [godbolt link](https://godbolt.org/z/P1MMf7).

It will actually compile if you use `std::fill(beg, end, 0);` presumably because `_Ty` is now `int` and `_Fill_memset_is_safe` evaluates to false.

### PR DESCRIPTION
**Pull request by AdamBucior**
A small PR to optimize `(ranges::)(uninitialized_)fill(_n)` when filling ranges of `bool` or `(signed|unsigned)char(8_t)` with other scalar types. Part of #431.

EDIT: Fixes #1183.

### CODE REVIEW

File: tests/std/tests/VSO_0180469_fill_family/test.cpp [hunk 1]
```diff
@@ -136,4 +136,34 @@ int main() {
 
     test_uninitialized_fill(
         [](count_copies* buff, size_t n, const count_copies& src) { uninitialized_fill_n(buff, n, src); });
+
+    // Validate int is properly converted to bool
+    {
+        bool output[] = {false, true, false};
+        fill(output, output + 3, 5);
+        for (bool elem : output) {
+            assert(elem == true);
```
Comment (statementreply) [inline tests/std/tests/VSO_0180469_fill_family/test.cpp:145]: These tests will likely pass even if `int` is not properly converted to `bool`. I suggest
```
for (const bool& elem : output) {
    assert(memcmp(&elem, &true_value, sizeof(bool)) == 0);
}
```

Comment (AdamBucior) [reply tests/std/tests/VSO_0180469_fill_family/test.cpp:145]: On my PC the assertion fails when I run:
```
#include <cassert>

using namespace std;

int main() {
    bool b;
    memset(&b, 5, 1);
    assert(b == true);
}
```
And I can't use `memcmp` because it's not constexpr

Comment (AlexGuteniev) [reply tests/std/tests/VSO_0180469_fill_family/test.cpp:145]: I think it depends on debug (`/Od`) vs release (`/O2`). 
Maybe in debug `== true` is literally comparison against true, and in release it is just test and branch on flags.

If that's right, then since tests run in debug, this looks enough.

Comment (AdamBucior) [reply tests/std/tests/VSO_0180469_fill_family/test.cpp:145]: Tested this code in release width /O2 (only replaced `assert(b == true);` with `if (b != true) abort();` because `assert` does nothing in release) and it still fails.

Comment (AdamBucior) [reply tests/std/tests/VSO_0180469_fill_family/test.cpp:145]: It mustn't be UB because this code compiles (unless it's a compiler bug):
```
#include <bit>
#include <cassert>

using namespace std;

constexpr bool f() {
    char i = 5;
    return bit_cast<bool>(i);
}

int main() {
    constexpr bool b = f();
    static_assert(b != true);
    static_assert(b != false);
}
```

Comment (AdamBucior) [reply tests/std/tests/VSO_0180469_fill_family/test.cpp:145]: Also I found that this code compiles:
```
#include <bit>
#include <algorithm>

using namespace std;

constexpr bool f() {
    char i = 2;

    bool arr[]  = {false, true, true};
    bool arr2[] = {false, true, bit_cast<bool>(i)};
    return !equal(begin(arr), end(arr), begin(arr2));
}

int main() {
    static_assert(f());
}
```
https://github.com/microsoft/STL/blob/e000d3feaf6acaf6214aedcfa21de483931ccbb7/stl/inc/xutility#L4895
Which means that `equal` should be able to use `memcmp` with `bool`.

Comment (AlexGuteniev) [reply tests/std/tests/VSO_0180469_fill_family/test.cpp:145]: Interesting.
I think it is still UB (expected behavior is a possible UB manifestation)
Usually wrong `bool`s act sometimes as true, but apparently `constexpr` evaluation does not trigger that.

Comment (AlexGuteniev) [reply tests/std/tests/VSO_0180469_fill_family/test.cpp:145]: Maybe `assert(bit_cast<char>(elem) == bit_cast<char>(bool(true)))` ?

Comment (AdamBucior) [reply tests/std/tests/VSO_0180469_fill_family/test.cpp:145]: These tests are not C++20 only so bit_cast is not always available. And even if it's UB it means that there's no reason for equal not to use `memcmp` for `bool` - not using `memcmp` in this case would make sense only if `bit_cast<bool>((char)2) == true` was always true and we know now that at least sometimes it's not.

Comment (AdamBucior) [reply tests/std/tests/VSO_0180469_fill_family/test.cpp:145]: Also `has_unique_object_representations_v<bool>` is true which (I think) means that if two `bool`s have different representations they must compare unequal.

**Comment by AdamBucior** [comment]
Changed `equal` to allow for `memcmp` with `bool` (see thread above). `memcmp` should work well with `bool` == _`(all other sizeof 1 integral types)`_

**Comment by AdamBucior** [comment]
After doing some further investigation I discovered that comparing `bool` with `unsigned char` and `char8_t` seems to not be `memcmp` safe. I think `memcmp`ing `bool` with `char` and `signed char` is safe, but I'm not entirely sure and I can't really see anyone doing it so I decided to enable it for `bool == bool` only.

**Comment by AdamBucior** [comment]
I think it's ready for review.

File: stl/inc/algorithm [hunk 2]
```diff
@@ -3993,7 +3993,9 @@ namespace ranges {
 #endif // __cpp_lib_is_constant_evaluated
                 {
                     const auto _Distance = static_cast<size_t>(_ULast - _UFirst);
-                    _CSTD memset(_UFirst, static_cast<unsigned char>(_Value), _Distance);
+                    using _DestTy        = _Iter_value_t<decltype(_UFirst)>;
+                    // first cast _Value to _DestTy in case _DestTy is bool
```
Comment (miscco) [inline stl/inc/algorithm:3997]: Given that we repeat this a lot I would suggest to create a helper function similar to `_Copy_memmove` maybe `_Fill_memset`?

Comment (AdamBucior) [reply stl/inc/algorithm:3997]: Good idea!

Comment (AdamBucior) [reply stl/inc/algorithm]: Done

File: stl/inc/xutility [hunk 3]
```diff
@@ -4751,6 +4751,12 @@ _INLINE_VAR constexpr bool _Fill_memset_is_safe =
 template <class _FwdIt, class _Ty>
 _INLINE_VAR constexpr bool _Fill_memset_is_safe<_FwdIt, _Ty, false> = false;
 
+template <class _DestTy, class _Ty>
+void _Fill_memset(_DestTy* const _Dest, const _Ty& _Val, size_t _Count) {
+    // first cast _Val to _DestTy in case _DestTy is bool
+    _CSTD memset(_Dest, static_cast<unsigned char>(static_cast<_DestTy>(_Val)), _Count);
+}
```
Comment (miscco) [inline stl/inc/xutility:4758]: No change requested: Looking forward this might not always be a pointer but at the same time we would mist likely want to update the function at that time anyway.

File: stl/inc/xutility [hunk 4]
```diff
@@ -4732,24 +4732,31 @@ struct _Is_character<char8_t> : true_type {}; // UTF-8 code units are sort-of ch
...
-    is_assignable<_Iter_ref_t<_FwdIt>, const _Ty&>>;
+_INLINE_VAR constexpr bool _Fill_memset_is_safe =
+    conjunction_v<is_scalar<_Ty>, _Is_character_or_byte_or_bool<_Unwrap_enum_t<_Iter_value_t<_FwdIt>>>,
+        is_assignable<_Iter_ref_t<_FwdIt>, const _Ty&>>;
 
 template <class _FwdIt, class _Ty>
 _INLINE_VAR constexpr bool _Fill_memset_is_safe<_FwdIt, _Ty, false> = false;
 
+template <class _DestTy, class _Ty>
+void _Fill_memset(_DestTy* const _Dest, const _Ty& _Val, size_t _Count) {
```
Comment (AlexGuteniev) [inline stl/inc/xutility:4755]: Why pass byte by reference?

Comment (AlexGuteniev) [reply stl/inc/xutility:4755]:
```suggestion
void _Fill_memset(_DestTy* const _Dest, const _Ty _Val, const size_t _Count) {
```

Comment (AdamBucior) [reply stl/inc/xutility:4755]: `_Ty` can be any scalar type but it will make no difference any way

Comment (AdamBucior) [reply stl/inc/xutility]: `_Ty` can be any scalar type but it makes no difference any way

File: tests/std/tests/P0896R4_ranges_alg_fill/test.cpp [hunk 5]
```diff
@@ -31,6 +31,13 @@ struct instantiator {
             }
             assert(result == ranges::end(output));
         }
+        { // Validate int is properly converted to bool
+            bool output[] = {false, true, false};
+            fill(ranges::begin(output), ranges::end(output), 5);
+            for (bool elem : output) {
```
[the remark this answers is not in the document]
Comment (AdamBucior) [reply tests/std/tests/P0896R4_ranges_alg_fill/test.cpp]: Done

File: stl/inc/xutility [hunk 6]
```diff
@@ -4732,24 +4732,31 @@ struct _Is_character<char8_t> : true_type {}; // UTF-8 code units are sort-of ch
...
+    _Is_character_or_byte_or_bool<_Unwrap_enum_t<remove_reference_t<_Iter_ref_t<_FwdIt>>>>,
     is_assignable<_Iter_ref_t<_FwdIt>, const _Ty&>>;
 
 template <class _FwdIt, class _Ty>
 _INLINE_VAR constexpr bool _Fill_memset_is_safe<_FwdIt, _Ty, false> = false;
 
+template <class _DestTy, class _Ty>
+void _Fill_memset(_DestTy* const _Dest, const _Ty _Val, const size_t _Count) {
+    // first cast _Val to _DestTy in case _DestTy is bool
+    _CSTD memset(_Dest, static_cast<unsigned char>(static_cast<_DestTy>(_Val)), _Count);
```
[the remark this answers is not in the document]
Comment (AdamBucior) [reply stl/inc/xutility]: Done

File: tests/std/tests/VSO_0180469_fill_family/test.cpp [hunk 7]
```diff
@@ -131,9 +131,41 @@ int main() {
     test_fill<int, char>();
     test_fill<char, int>();
 
+    test_fill<volatile char, char>();
```
[the remark this answers is not in the document]
Comment (AdamBucior) [reply tests/std/tests/VSO_0180469_fill_family/test.cpp]: Done

File: tests/std/tests/VSO_0180469_ptr_cat/test.cpp [hunk 8]
```diff
@@ -257,23 +257,31 @@ void test_case_Equal_memcmp_is_safe_comparator() {
...
-                      typename vector<Elem2>::const_iterator, Pr> == Expected);
-    STATIC_ASSERT(
-        _Equal_memcmp_is_safe<typename vector<Elem1>::iterator, typename array<Elem2, 1>::iterator, Pr> == Expected);
-    STATIC_ASSERT(_Equal_memcmp_is_safe<typename vector<Elem1>::iterator, typename array<Elem2, 1>::const_iterator,
-                      Pr> == Expected);
+    if constexpr (!is_same_v<Elem1, bool> && !is_same_v<Elem2, bool>) {
+        STATIC_ASSERT(_Equal_memcmp_is_safe<typename vector<Elem1>::iterator, typename vector<Elem2>::const_iterator,
+                          Pr> == Expected);
+    }
+    if constexpr (!is_same_v<Elem2, bool>) {
```
[the remark this answers is not in the document]
Comment (AdamBucior) [reply tests/std/tests/VSO_0180469_ptr_cat/test.cpp]: Done

File: tests/std/tests/VSO_0180469_ptr_cat/test.cpp [hunk 9]
```diff
@@ -257,23 +257,31 @@ void test_case_Equal_memcmp_is_safe_comparator() {
...
+        STATIC_ASSERT(_Equal_memcmp_is_safe<typename array<Elem1, 1>::const_iterator,
+                          typename vector<Elem2>::const_iterator, Pr> == Expected);
+    }
+    if constexpr (!is_same_v<Elem1, bool>) {
```
[the remark this answers is not in the document]
Comment (AdamBucior) [reply tests/std/tests/VSO_0180469_ptr_cat/test.cpp]: Done

**Comment by miscco** [comment]
It seems your formatting is behaving strangely

**Comment by AdamBucior** [comment]
> It seems your formatting is behaving strangely

For some reason visual studio didn't run clang-format automatically.

File: stl/inc/xutility [hunk 10]
```diff
@@ -4917,7 +4923,8 @@ template <class _Ty1, class _Ty2>
 _INLINE_VAR constexpr bool _Can_memcmp_elements<_Ty1*, _Ty2*, false> = is_same_v<remove_cv_t<_Ty1>, remove_cv_t<_Ty2>>;
 
 template <class _Elem1, class _Elem2>
-_INLINE_VAR constexpr bool _Can_memcmp_elements<_Elem1, _Elem2, false> = false;
+_INLINE_VAR constexpr bool _Can_memcmp_elements<_Elem1, _Elem2, false> =
+    is_same_v<_Elem1, bool>&& is_same_v<_Elem2, bool>;
```
Comment (CaseyCarter) [inline stl/inc/xutility:4927]: Why are we afraid to compare the object representations of `bool`s with those of non-`bool` objects of integral type with the same size?

Comment (AlexGuteniev) [reply stl/inc/xutility:4927]: I guess:
```C++
char a[] = {2,2,2};
bool b[] = {true, true, true}
```
would `memcmp` as `false`, whereas we expect `true`, no?

Comment (AdamBucior) [reply stl/inc/xutility:4927]: The problem is the concern about the representations other than 0 and 1. `bit_cast<bool>(char(-128)) == signed char(-128)` is `true` but `bit_cast<bool>(char(-128)) == unsigned char(-128)` is `false` because of integral promotion. If we don't care about the other representations we can `memcmp` between `bool` and non-`bool`.

> I guess:
> 
> ```c++
> char a[] = {2,2,2};
> bool b[] = {true, true, true}
> ```
> 
> would `memcmp` as `false`, whereas we expect `true`, no?

`char(2) == true` is `false` because of integral promotion (`char(2)` is promoted to `int(2)` and `true` is promoted to `1`).

Comment (CaseyCarter) [reply stl/inc/xutility:4927]: > I guess:
> 
> ```c++
> char a[] = {2,2,2};
> bool b[] = {true, true, true}
> ```
> 
> would `memcmp` as `false`, whereas we expect `true`, no?

`true` promotes to `int{1}` and `char{2}` promotes to `int{2}`, so `char{2} == true` is evaluated as `2 == 1` after the Usual Arithmetic Conversions, which evaluates to `false`.

Comment (CaseyCarter) [reply stl/inc/xutility:4927]: > The problem is the concern about the representations other than 0 and 1. `bit_cast<bool>(char(-128)) == signed char(-128)` is `true`

`bit_cast<bool>(char(x))` has undefined behavior if `char(x)` is any value other than `char{0}` or `char{1}` per [[[bit.cast]/2](http://eel.is/c++draft/bit.cast#2) "For the result and each object created within it, if there is no value of the object’s type corresponding to the value representation produced, the behavior is undefined."

Comment (AdamBucior) [reply stl/inc/xutility]: OK

**Review by CaseyCarter — APPROVED** [review]

File: tests/std/tests/VSO_0180469_ptr_cat/test.cpp [hunk 11]
```diff
@@ -377,10 +388,13 @@ void equal_safe_test_cases() {
     test_case_Equal_memcmp_is_safe<sizeof(int) == sizeof(long), unsigned long, unsigned int>();
     test_case_Equal_memcmp_is_safe<true, long long, unsigned long long>();
     test_case_Equal_memcmp_is_safe<true, unsigned long long, long long>();
-    // memcmp is not safe for bool types
-    test_case_Equal_memcmp_is_safe<false, bool, bool>();
-    test_case_Equal_memcmp_is_safe<false, bool, char>();
-    test_case_Equal_memcmp_is_safe<false, char, bool>();
+#pragma warning(push)
+#pragma warning(disable : 4806) // no value of type '_Elem1' promoted to type '_Elem2' can equal the given constant
```
Comment (StephanTLavavej) [inline tests/std/tests/VSO_0180469_ptr_cat/test.cpp:392]: It appears that this warning is being emitted by the `_Can_memcmp_elements` machinery - so this push/disable/pop should appear in `<xutility>` rather than in "user" code. (We suppress warnings in tests when the tests themselves are doing something strange-but-okay. Here, calling `std::equal` on ranges of `bool` and `char` is perfectly fine, so the product code needs to suppress the warning from internal machinery.)

**Review by StephanTLavavej — CHANGES_REQUESTED** [review]

File: tests/std/tests/VSO_0180469_ptr_cat/test.cpp (hunk 11 above)
Comment (StephanTLavavej) [reply tests/std/tests/VSO_0180469_ptr_cat/test.cpp]: I went ahead and pushed a change for this.

**Review by StephanTLavavej — APPROVED** [review]

**Review by CaseyCarter — APPROVED** [review]

**Comment by CaseyCarter** [comment]
Thanks for making our bitwise-equality optimizations a bit more effective!
