### PR TITLE
`<ranges>`: Fix `zip_transform_view` by not using possibly ill-formed static data member

### LINKED ISSUE #4414: <ranges>: zip_transform does not accept non const iterable ranges
# Describe the bug
You can't feed ranges which are not const iterable, like `filter_view`, to `zip_transform`.
gcc with libstdc++ accepts this code.

# test case
```
#include <ranges>

int main() {
    using namespace std::views;
    auto evens_and_odds =
        zip_transform([](int even, int odd) { return even + odd; },
                      iota(0, 10) | filter([](int i) { return i % 2 == 0; }),
                      iota(0, 10) | filter([](int i) { return i % 2 != 0; }));
}
```

error is
```
example.cpp
C:/data/msvc/14.38.33133/include\ranges(8872): error C7602: 'std::ranges::range_reference_t': the associated constraints are not satisfied
C:/data/msvc/14.38.33133/include\xutility(2661): note: see declaration of 'std::ranges::range_reference_t'
C:/data/msvc/14.38.33133/include\xutility(2660): note: the concept 'std::ranges::range<const std::ranges::filter_view<std::ranges::iota_view<_Ty1,_Ty2>,main::<lambda_2>>>' evaluated to false
        with
        [
            _Ty1=int,
            _Ty2=int
        ]
C:/data/msvc/14.38.33133/include\xutility(2468): note: call to object of class type 'std::ranges::_Begin::_Cpo': no matching call operator found
C:/data/msvc/14.38.33133/include\xutility(2371): note: could be 'auto std::ranges::_Begin::_Cpo::operator ()(_Ty &&) noexcept(<expr>) const'
C:/data/msvc/14.38.33133/include\ranges(8872): note: the template instantiation context (the oldest one first) is
C:/data/msvc/14.38.33133/include\ranges(8969): note: see reference to variable template 'const bool std::ranges::views::_Zip_transform_fn::_Enable_cpo<`main'::`2'::<lambda_1>,std::ranges::filter_view<std::ranges::iota_view<int,int>,`main'::`2'::<lambda_2> >,std::ranges::filter_view<std::ranges::iota_view<int,int>,`main'::`2'::<lambda_3> > >' being compiled
C:/data/msvc/14.38.33133/include\ranges(8962): note: see reference to class template instantiation 'std::ranges::zip_transform_view<_Func,std::ranges::filter_view<std::ranges::iota_view<_Ty1,_Ty2>,main::<lambda_2>>,std::ranges::filter_view<std::ranges::iota_view<_Ty1,_Ty2>,main::<lambda_3>>>' being compiled
        with
        [
            _Func=main::<lambda_1>,
            _Ty1=int,
            _Ty2=int
        ]
C:/data/msvc/14.38.33133/include\ranges(8872): error C2065: '<missingId>': undeclared identifier
Compiler returned: 2
```

https://godbolt.org/z/o41csG3jr

# Expected behavior
Code compiles without an error

# STL version
Microsoft (R) C/C++ Optimizing Compiler Version 19.38.33133 for x64

### PR DESCRIPTION
**Pull request by frederick-vs-ja**
Fixes #4414.

While there's DevCom-1603671 which directly results in the reported error, the library implementation is also currently somehow broken - the initializer of `_Enable_const_begin_end` may be ill-formed when the value is expected to be `false`, which can make `ranges::range<const ranges::zip_transform_view<...>>` ill-formed when it should be `false`.

### CODE REVIEW

File: tests/std/tests/P2321R2_views_zip_transform/test.cpp [hunk 1]
```diff
@@ -858,6 +872,10 @@ int main() {
         test_one(three_element_transform_closure, three_range_transform_results_array, test_element_array_one,
             test_element_array_two, test_element_array_three);
     }
+    {
+        STATIC_ASSERT(test_gh_4414());
```
Comment (AlexGuteniev) [inline tests/std/tests/P2321R2_views_zip_transform/test.cpp:876]: (Pre-existing) I'm wondering why would C++20 tests use `STATIC_ASSERT` macro rather than terse `static_assert`

Comment (StephanTLavavej) [reply tests/std/tests/P2321R2_views_zip_transform/test.cpp:876]: It stringifies the condition. MSVC doesn't report the condition (`/diagnostics:caret` reports it indirectly, but we currently don't use that in our tests - I think we did in the past):

```
C:\Temp>type woof.cpp
static_assert(17 == 29);

C:\Temp>cl /EHsc /nologo /W4 /std:c++latest /c woof.cpp
woof.cpp
woof.cpp(1): error C2607: static assertion failed

C:\Temp>cl /EHsc /nologo /W4 /std:c++latest /c /diagnostics:caret woof.cpp
woof.cpp
woof.cpp(1,18): error C2607: static assertion failed
static_assert(17 == 29);
                 ^

C:\Temp>clang-cl /EHsc /nologo /W4 /std:c++latest /c woof.cpp
woof.cpp(1,15): error: static assertion failed due to requirement '17 == 29'
    1 | static_assert(17 == 29);
      |               ^~~~~~~~
1 error generated.
```

IIRC, other maintainers liked the stringifying, whereas I didn't care - unlike runtime assertions (which can be sporadic, so it's helpful to capture in logs what failed, even if it's technically possible to go look up line numbers), `static_assert`s tend not to start failing, or if they do it's because of `constexpr` evaluation in which case the line isn't actually interesting, so I have to build the test case myself anyways, in which case I can see the line right there.

I think the status quo is that some, but not all, C++20-and-above tests use the `STATIC_ASSERT` macro while others use terse `static_assert`, reflecting the strength of maintainer feelings about this.

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
:zipper_mouth_face: :magic_wand: :heart_eyes_cat:
===
