### PR TITLE
`<deque>`: Make `deque::shrink_to_fit` never relocate elements

### LINKED ISSUE #4072: `<deque>`: `shrink_to_fit()` should follow the Standard
WG21-N4958 \[deque.capacity\]/6:

> *Effects:* `shrink_to_fit` is a non-binding request to reduce memory use but does not change the size of the sequence.
> \[*Note 1:* The request is non-binding to allow latitude for implementation-specific optimizations. - *end note*\]
> If the size is equal to the old capacity, or if an exception is thrown other than by the move constructor of a non-*Cpp17CopyInsertable* `T`, then there are no effects."

We unconditionally move, which is a bug:

https://github.com/microsoft/STL/blob/283cf32878948f41b5b68fe60860e0c4dca85ce1/stl/inc/deque#L998

(#4071 is patching this line in an unrelated way.)

`vector` provides its strong guarantees correctly, like this (note that it doesn't directly use `move_if_noexcept()`):

https://github.com/microsoft/STL/blob/283cf32878948f41b5b68fe60860e0c4dca85ce1/stl/inc/vector#L837-L842

### PR DESCRIPTION
**Pull request by frederick-vs-ja**
Fixes #4072 by providing stronger guarantee.

### CODE REVIEW

File: stl/inc/deque [hunk 1]
```diff
@@ -986,19 +986,58 @@ public:
...
+            if (_Map() != nullptr) {
+                _Reset_map();
+            }
+            return;
+        }
+
+        const auto _First_block_ptr = _Map() + static_cast<_Map_difference_type>(_Myoff() / _Block_size);
+        const auto _Last_block_ptr =
+            _Map() + static_cast<_Map_difference_type>((_Myoff() + _Mysize() - 1) / _Block_size + 1);
+        const auto _Used_block_count = static_cast<size_type>(_Last_block_ptr - _First_block_ptr);
```
Comment (achabense) [inline stl/inc/deque:999]: `_Last_block_ptr` is able to come before `_First_block_ptr` doe to masking

File: tests/std/tests/Dev10_860421_deque_push_back_pop_front/test.cpp [hunk 2]
```diff
@@ -259,11 +259,36 @@ void test_exception_safety_for_throwing_movable() {
...
+
+    deque<ThrowingMovable> d2;
+    for (int i = removed_count; i < 1729 - removed_count; ++i) {
+        d2.emplace_back(i);
+    }
+
+    d.shrink_to_fit(); // additionally ensures that no constructor or assignment operator of the element type is called
+    assert(d == d2);
+}
+
```
Comment (achabense) [inline tests/std/tests/Dev10_860421_deque_push_back_pop_front/test.cpp:284]: The problem in [the above comment](https://github.com/microsoft/STL/pull/4091/files#r1359805829), we'd better might be able to get caught by:
deque<...> with exactly 128 elements.
pop-front 120 elements.
push-back 1 elements.
shrink_to_fit.

File: stl/inc/deque (hunk 1 above)
Comment (achabense) [inline stl/inc/deque:999]: `_Last_block_ptr` is able to come before `_First_block_ptr`, as masking is needed. Try this:
```
        std::deque<int> deq(128);
        for (int i = 0; i < 120; ++i) {
            deq.pop_back();
        }
        for (int i = 0; i < 10; ++i) {
            deq.push_front(1);
        }
        deq.shrink_to_fit();
```

File: tests/std/tests/Dev10_860421_deque_push_back_pop_front/test.cpp [hunk 3]
```diff
@@ -259,11 +259,36 @@ void test_exception_safety_for_throwing_movable() {
...
+        d.pop_back();
+    }
+
+    deque<ThrowingMovable> d2;
+    for (int i = removed_count; i < 1729 - removed_count; ++i) {
+        d2.emplace_back(i);
+    }
+
+    d.shrink_to_fit(); // additionally ensures that no constructor or assignment operator of the element type is called
+    assert(d == d2);
```
Comment (achabense) [inline tests/std/tests/Dev10_860421_deque_push_back_pop_front/test.cpp:282]: I'd suggest adding an extra test like
```
    std::deque<int> deq(128);
    for (int i = 0; i < 120; ++i) {
        deq.pop_back();
    }
    deq.push_front(1);
    deq.shrink_to_fit();

    std::deque<int> deq2(128);
    for (int i = 0; i < 120; ++i) {
        deq2.pop_front();
    }
    deq2.push_back(1);
    deq2.shrink_to_fit();
```

File: stl/inc/deque [hunk 4]
```diff
@@ -986,19 +986,58 @@ public:
...
+        _Orphan_all(); // the map can be shrinked, invalidate all iterators
+
+        const auto _Copy_end = _STD _Uninitialized_copy_unchecked(
+            _First_block_ptr, _Last_block_ptr, _New_map); // transfer the ownership of blocks to pointers in the new map
+        _STD _Uninitialized_value_construct_n_unchecked1(
+            _Copy_end, _New_block_count - _Used_block_count); // zero out the rest of the new map
+        _STD fill(
+            _First_block_ptr, _Last_block_ptr, nullptr); // zero out the old map because the ownership is transferred
+
+        _Reset_map();
```
Comment (achabense) [inline stl/inc/deque:1036]:
```
_STD fill(
    _First_block_ptr, _Last_block_ptr, nullptr); // zero out the old map because the ownership is transferred

_Reset_map();
```

This can be just deallocating `_Map()`: `_Almap.deallocate(_Map(), _Mapsize());`

File: stl/inc/deque [hunk 5]
```diff
@@ -986,19 +986,58 @@ public:
...
+                *_Block_it = nullptr;
+            }
         }
 
-        if ((empty() && _Mapsize() > 0)
-            || (!empty() && size() <= _Newcapacity && _Newcapacity < _Oldcapacity)) { // worth shrinking, do it
-            deque _Tmp(
-                _STD make_move_iterator(_Unchecked_begin()), _STD make_move_iterator(_Unchecked_end()), _Getal());
-            swap(_Tmp);
+        size_type _New_block_count = 1; // should be power of 2
```
Comment (achabense) [inline stl/inc/deque:1015]: This can start from `_Minimum_map_size` as it's a power of 2.

File: stl/inc/deque (hunk 1 above)
Comment (frederick-vs-ja) [reply stl/inc/deque]: Thanks! I totally ignored that fact that the internal map is a circular buffer.

**Comment by achabense** [comment]
Hmm, the impl is still not correct... try:
```
    std::deque<int> deq(128);
    for (int i = 0; i < 120; i++) {
        deq.pop_back();
    }
    for (int i = 0; i < 5; i++) {
        deq.push_front(0);
    }
    deq.shrink_to_fit();
```

File: stl/inc/deque [hunk 6]
```diff
@@ -986,19 +986,68 @@ public:
...
+
+        // deallocate unused blocks
 
-        if (_Newcapacity < _Block_size * _Minimum_map_size) {
-            _Newcapacity = _Block_size * _Minimum_map_size;
+        for (auto _Block_idx = _Map_difference_type{0}; _Block_idx != _First_block_idx; ++_Block_idx) {
+            auto& _Block_ptr = _Map()[static_cast<_Map_difference_type>(_Block_idx & (_Mapsize() - 1))];
+            if (_Block_ptr != nullptr) {
+                _Getal().deallocate(_Block_ptr, _Block_size);
+                _Block_ptr = nullptr;
```
Comment (achabense) [inline stl/inc/deque:1006]: Some area in [0, x) ∈ [0, `_First_block_idx`) might still belong to active area...

**Comment by achabense** [comment]
<details>
<summary>Pull request</summary>

```cpp
    void shrink_to_fit() {
        if (empty()) {
            if (_Map() != nullptr) {
                _Reset_map();
            }
            return;
        }

        const _Map_difference_type _Index_mask = _Map_distance() - 1;
        const _Map_difference_type _First_block_idx = _Getblock(_Myoff());
        const _Map_difference_type _Last_block_idx = _Getblock(_Myoff() + size() - 1); // the block `back()` belongs to.

        if (_First_block_idx == _Last_block_idx) {
            return;
        }

        // deallocate unused blocks
        _Map_difference_type _Unused_block_idx = (_Last_block_idx + 1) & _Index_mask;
        size_type _Unused_block_count = 0;
        while (_Unused_block_idx != _First_block_idx) {
            ++_Unused_block_count;
            auto& _Block_ptr = _Map()[static_cast<_Map_difference_type>(_Unused_block_idx)];
            if (_Block_ptr != nullptr) {
                _Getal().deallocate(_Block_ptr, _Block_size);
                _Block_ptr = nullptr;
            }
            _Unused_block_idx = (_Unused_block_idx + 1) & _Index_mask;
        }

        const size_type _Used_block_count = _Mapsize() - _Unused_block_count;

        size_type _New_block_count = _Minimum_map_size; // should be power of 2
        while (_New_block_count < _Used_block_count) {
            _New_block_count *= 2;
        }
        if (_New_block_count >= _Mapsize()) {
            return;
        }

        // worth shrinking the internal map, do it

        _Alpty _Almap(_Getal());
        const auto _New_map = _Almap.allocate(_New_block_count);

        _Orphan_all(); // shrinkable, invalidate all iterators

        _Map_difference_type _New_block_idx = 0;
        while (_New_block_idx < static_cast<_Map_difference_type>(_Used_block_count)) {
            _STD _Construct_in_place(
                _New_map[_New_block_idx], _Map()[(_First_block_idx + _New_block_idx) & _Index_mask]);
            ++_New_block_idx;
        }
        // zero out the rest of the new map
        _STD _Uninitialized_value_construct_n_unchecked1(
            _New_map + _New_block_idx, _New_block_count - _Used_block_count);

        // destroy block pointers, and free storage for map.
        for (_Map_difference_type _Block = 0; _Block < _Map_distance(); ++_Block) {
            _STD _Destroy_in_place(_Map()[_Block]);
        }
        _Almap.deallocate(_Map(), _Mapsize());

        _Map() = _New_map;
        _Mapsize() = _New_block_count;
        _Myoff() %= _Block_size;
    }
```
</details>

**Comment by achabense** [comment]
```
    std::deque<int> deq(128);
    deq.shrink_to_fit();
    assert(deq.size() == 128);
    assert(!_CrtDumpMemoryLeaks());
```

File: stl/inc/deque [hunk 7]
```diff
@@ -986,19 +986,63 @@ public:
...
+        for (auto _Block_idx = _First_block_idx; _Block_idx != _Last_block_idx;
+             _Block_idx = static_cast<_Map_difference_type>((_Block_idx + 1) & (_Mapsize() - 1)), ++_New_block_idx) {
+            // transfer the ownership of blocks to pointers in the new map
+            _STD _Construct_in_place(_New_map[_New_block_idx], _Map()[_Block_idx]);
+        }
+        // zero out the rest of the new map
+        _STD _Uninitialized_value_construct_n_unchecked1(
+            _New_map + _New_block_idx, _New_block_count - static_cast<size_type>(_New_block_idx));
+
+        for (auto _Block = _Map_distance(); _Block > 0;) {
```
Comment (grcm10) [inline stl/inc/deque:1037]: Should we add if( _Map() != nullptr) before deallocating map?

Comment (frederick-vs-ja) [reply stl/inc/deque:1037]: I believe we shouldn't. At the point where `deallocate` gets called, the `deque` must be non-empty, so `_Map()` must be non-null.

File: stl/inc/deque [hunk 8]
```diff
@@ -986,19 +986,63 @@ public:
...
+                _Reset_map();
+            }
+            return;
+        }
 
-        if (_Newcapacity < _Block_size * _Minimum_map_size) {
-            _Newcapacity = _Block_size * _Minimum_map_size;
+        const auto _First_block_idx = static_cast<_Map_difference_type>(_Myoff() / _Block_size);
+        const auto _Last_block_idx =
+            static_cast<_Map_difference_type>(((_Myoff() + _Mysize() - 1) / _Block_size + 1) & (_Mapsize() - 1));
```
Comment (achabense) [inline stl/inc/deque:998]: As the calculation is complex here, I think it's better to add comment that `_Last_block_idx` is the past-the-end index.

Comment (frederick-vs-ja) [reply stl/inc/deque:998]: Now I think that "last" possibly have misleading impression, given we're actually operating on a circular buffer. Perhaps we should use another word instead of "last".

File: tests/std/tests/Dev10_860421_deque_push_back_pop_front/test.cpp [hunk 9]
```diff
@@ -259,11 +259,54 @@ void test_exception_safety_for_throwing_movable() {
...
+
+    // ensure that the circular buffer is correctly handled
+    {
+        deque<ThrowingMovable> deq(128);
+        deq.pop_back();
+        deq.emplace_front(0);
```
[the remark this answers is not in the document]
Comment (StephanTLavavej) [reply tests/std/tests/Dev10_860421_deque_push_back_pop_front/test.cpp:288]: Yeah, `deque` is really weird. I agree that this coverage is reasonable and I agree that it's not worth the extra effort to try to write a really comprehensive test.

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Thank you! :heart_eyes_cat: After getting up to speed with your excellent overhaul here, I pushed a bunch of changes to make the logic clearer for my cat-sized brain.

This is vastly better than our original implementation of `shrink_to_fit()`, and now that I can see what the fix is doing, I'm not too worried about it subtly breaking `deque` invariants. However, this is definitely complex enough to need 3 maintainer eyes, so I'll ask for a final review before moving this to ready to merge.

**Review by CaseyCarter — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Thanks for fixing everyone's favorite STL container! :hammer_and_wrench: :joy_cat: :tada:
