### PR TITLE
`<chrono>`: Fix `formatter` ignoring dynamically provided width

### LINKED ISSUE #4201: `<chrono>` `<format>`: `duration` formatting ignores dynamic width
```
C:\Temp>type meow.cpp
```
```cpp
#include <chrono>
#include <format>
#include <iostream>
#include <string>
#include <thread>
using namespace std;

int main() {
#ifdef __GLIBCXX__
    cout << "libstdc++\n";
#elif defined(_LIBCPP_VERSION)
    cout << "libc++\n";
#elif defined(_MSVC_STL_UPDATE)
    cout << "microsoft/STL\n";
#endif
    const auto id = this_thread::get_id();
    cout << format("       int {{:20}}: [{:20}]\n", 1729);
    cout << format("       int {{:{{}}}}: [{:{}}]\n", 1729, 20);
    cout << format("thread::id {{:20}}: [{:20}]\n", id);
    cout << format("thread::id {{:{{}}}}: [{:{}}]\n", id, 20);
    cout << format(" seconds {{:20%T}}: [{:20%T}]\n", 314159s);
    cout << format(" seconds {{:{{}}%T}}: [{:{}%T}]\n", 314159s, 20);
}
```
```
C:\Temp>cl /EHsc /nologo /W4 /std:c++latest /MTd /Od meow.cpp && meow
meow.cpp
microsoft/STL
       int {:20}: [                1729]
       int {:{}}: [                1729]
thread::id {:20}: [               34680]
thread::id {:{}}: [               34680]
 seconds {:20%T}: [87:15:59            ]
 seconds {:{}%T}: [87:15:59]
```
https://godbolt.org/z/YbM9qnocf

When formatting a `duration`, the fact that `{:20%T}` respects the statically provided width but `{:{}%T}` ignores the dynamically provided width is *super* buggy, and neither libstdc++ nor libc++ exhibit that behavior.

(There's a separate question of whether `duration` should default to being left-aligned or right-aligned. MSVC and libstdc++ chose left, libc++ chose right.)

(libc++ is also printing the hours mod 24, unlike MSVC and libstdc++.)

### PR DESCRIPTION
**Pull request by mt3d**
Fixes #4201.

As has @cpplearner noted, `_Chrono_formatter::_Write()` calls and returns `_Write_aligned` before trying to check if a width is provided dynamically. The updated behavior is now similar to that of `_Formatter_base::format()`.

### CODE REVIEW

File: stl/inc/chrono [hunk 1]
```diff
@@ -5477,7 +5477,14 @@ namespace chrono {
 
             int _Estimated_width = -1;
             (void) _Measure_string_prefix(_Stream.view(), _Estimated_width);
-            return _Write_aligned(_STD move(_FormatCtx.out()), _Estimated_width, _Specs, _Fmt_align::_Left,
+
+            auto _FormatSpecs = _Specs;
```
Comment (StephanTLavavej) [inline stl/inc/chrono:5481]: Naming nitpick: We conventionally use `_Ugly_snake_case` for variables, and `_UglyCamelCase` for template parameters. `<format>` and its related code are somewhat inconsistent (e.g. `_FormatCtx` violates this convention) but we should try to follow it in new code. This will improve consistency with the existing code you mentioned, where the name is `_Format_specs`:

https://github.com/microsoft/STL/blob/87580ca91c1a34645d22f79f7640a13f68bb31c5/stl/inc/format#L3639-L3643

File: tests/std/tests/GH_004201_chrono_formatter/test.cpp [hunk 2]
```diff
@@ -0,0 +1,15 @@
+#include <cassert>
```
Comment (StephanTLavavej) [inline tests/std/tests/GH_004201_chrono_formatter/test.cpp:1]: This newly added file needs our copyright/license banner.

File: tests/std/tests/GH_004201_chrono_formatter/test.cpp [hunk 3]
```diff
@@ -0,0 +1,15 @@
+#include <cassert>
+#include <chrono>
+#include <format>
+#include <iostream>
+#include <string>
+#include <thread>
```
Comment (StephanTLavavej) [inline tests/std/tests/GH_004201_chrono_formatter/test.cpp:6]: `<iostream>` and `<thread>` were used in #4201, but not in this test, so they should be dropped here.

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Thanks for fixing this bug and adding a test! :heart_eyes_cat: I pushed a commit to fix minor nitpicks.

We simultaneously merge PRs to GitHub and our MSVC-internal repo; this is a semi-manual process so we batch up PRs to save time. Your PR will be part of the next batch, likely in the next couple of days.

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I've pushed a merge with `main` to resolve a trivial adjacent-add conflict in `tests/std/test.lst` with #4275.
