### PR TITLE
`<ranges>`: Fix dispatching for `views::counted`

### LINKED ISSUE #5183: `<ranges>`: `views::counted::_Choose()` misses difference casting for `contiguous_iterator` case
https://github.com/microsoft/STL/blob/89ca073a866d24db42b3f4c5e406be4b28a148f4/stl/inc/ranges#L4214-L4220

The second difference argument passed into `span` misses the `size_t` casting, which would cause a hard error if it is not implicitly-convertible to `size_t`.
testcase:

```cpp
#include <ranges>

struct ContiguousIter {
  using iterator_category = std::contiguous_iterator_tag;
  using difference_type = std::_Signed128;
  using element_type = char;
  element_type& operator*() const;
  ContiguousIter& operator++();
  ContiguousIter operator++(int);
  ContiguousIter& operator--();
  ContiguousIter operator--(int);
  ContiguousIter& operator+=(difference_type);
  ContiguousIter& operator-=(difference_type);
  element_type* operator->() const;
  element_type& operator[](difference_type) const;
  friend ContiguousIter operator+(ContiguousIter, difference_type);
  friend ContiguousIter operator+(difference_type, ContiguousIter);
  friend ContiguousIter operator-(ContiguousIter, difference_type);
  friend difference_type operator-(ContiguousIter, ContiguousIter);
  auto operator<=>(const ContiguousIter&) const = default;
};

int main() {
  ContiguousIter it;
  std::ranges::contiguous_range auto r = std::views::counted(it, 42); // boom
}
```

 https://godbolt.org/z/e1hv1o6h8

This can be a good first issue.

### PR DESCRIPTION
**Pull request by frederick-vs-ja**
Fixes #5183 (which is a bit beyond good first issue, IMO).

Drive-by changes:
- Fixing `test::redifference_iterator`, which should always have `iterator_concept`.
- Cleaning up using-declarations in `P0896R4_views_counted/test.cpp`.

There's a bug of MSVC which forbids `using ranges::contiguous_range; contiguous_range auto cat = meow();` to work. I've reported DevCom-10823410 for it.

### CODE REVIEW

File: tests/std/include/range_algorithm_support.hpp [hunk 1]
```diff
@@ -977,13 +982,8 @@ namespace test {
...
-    template <std::_Signed_integer_like Diff, std::input_iterator It>
-    class redifference_iterator : public redifference_iterator_category_base<Diff, It> {
-    public:
-        using value_type      = std::iter_value_t<It>;
-        using difference_type = Diff;
+        using value_type       = std::iter_value_t<It>;
+        using difference_type  = Diff;
 
         redifference_iterator() = default;
         constexpr explicit redifference_iterator(It it) : i_{std::move(it)} {}
```
Comment (StephanTLavavej) [inline tests/std/include/range_algorithm_support.hpp:989]: There are x64 test failures, separate from the x86 AV problem that's currently blocking all PR checks:

```
"C:\a\_work\1\s\tests\std\include\range_algorithm_support.hpp", line 989:
          error: "i_" is not a nonstatic data member or base class of class
          "test::redifference_iterator<std::_Signed128,
```

**Review by StephanTLavavej — CHANGES_REQUESTED** [review]

File: tests/std/include/range_algorithm_support.hpp (hunk 1 above)
Comment (StephanTLavavej) [reply tests/std/include/range_algorithm_support.hpp:981]: `P0896R4_views_counted` is still failing. As a reminder, it's always a good idea to rerun a failing test locally before pushing changes.

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
:vampire: :cookie: :1234:
===
