### PR TITLE
Misc constexpr

### LINKED ISSUE #203: <string_view>: basic_string_view::copy() mistakenly marked constexpr before C++20 P1032R1
**Describe the bug**
During implementation #50 i found that string_view::copy mistakenly marked constexpr before p1032r1

**Command-line test case**
I guess all versions with string_view support:

```
C:\Users\billy\Desktop>type string_view_copy.cpp
#include <string_view>
#include <array>

constexpr auto test_string_view_copy() {
    std::string_view a("oops");
    std::array<char,3> a1 = {'1','2','3'};
    a.copy(a1.data(), 3);
    return a1.size();
}


int main() {
    constexpr auto n = test_string_view_copy();
}

C:\Users\billy\Desktop>cl /EHsc /W4 /WX .\cl /std:c++17 /EHsc /MDd /W4 /WX string_view_copy.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.23.28106.4 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

string_view_copy.cpp
string_view_copy.cpp(13): error C2131: expression did not evaluate to a constant
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\xstring(1322): note: failure was caused by call of undefined function or one not declared 'constexpr'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\xstring(1322): note: see usage of 'std::_Narrow_char_traits<char,int>::copy'
```

**Expected behavior**
Something like this
```
cl /std:c++17 /EHsc /MDd /W4 /WX string_view_copy.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.23.28106.4 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

string_view_copy.cpp
string_view_copy.cpp(4): error C3615: constexpr function 'test_string_view_copy' cannot result in a constant expression
string_view_copy.cpp(7): note: failure was caused by call of undefined function or one not declared 'constexpr'
string_view_copy.cpp(7): note: see usage of 'std::basic_string_view<char,std::char_traits<char>>::copy'
string_view_copy.cpp(13): error C2131: expression did not evaluate to a constant
string_view_copy.cpp(13): note: function violates 'constexpr' rules or has errors
string_view_copy.cpp(13): note: see usage of 'test_string_view_copy'
```

**Additional context**

### PR DESCRIPTION
**Pull request by miscco**
# Description
This addresses parts of #50 now that `is_constant_evaluated` has been implemented and we can proceed. I did not add the feature test macros fo functional and array as the larger parts are still open.

Note that there was one prexisting bug with the constructor of `insert_iterator` that missed the `explicit` keyword 

Also tuple is hell...

Fixes #203.

# Checklist

Be sure you've read README.md and understand the scope of this repo.

If you're unsure about a box, leave it unchecked. A maintainer will help you.

- [x] Identifiers in product code changes are properly `_Ugly` as per
  https://eel.is/c++draft/lex.name#3.1 or there are no product code changes.
- [ ] The STL builds successfully and all tests have passed (must be manually
  verified by an STL maintainer before automated testing is enabled on GitHub,
  leave this unchecked for initial submission).
- [x] These changes introduce no known ABI breaks (adding members, renaming
  members, adding virtual functions, changing whether a type is an aggregate
  or trivially copyable, etc.).
- [x] These changes were written from scratch using only this repository,
  the C++ Working Draft (including any cited standards), other WG21 papers
  (excluding reference implementations outside of proposed standard wording),
  and LWG issues as reference material. If they were derived from a project
  that's already listed in NOTICE.txt, that's fine, but please mention it.
  If they were derived from any other project (including Boost and libc++,
  which are not yet listed in NOTICE.txt), you *must* mention it here,
  so we can determine whether the license is compatible and what else needs
  to be done.

### CODE REVIEW

**Comment by BillyONeal** [comment]
@miscco Could we trouble you to add tests for these things now that we have tests in the repo?

**Comment by miscco** [comment]
yes thats on my list for the coming days

**Comment by miscco** [comment]
Lets write some tests...

:: cries in tuple ::

On a more serious note I dont think I can write the tests fo the `*_inserter` as we do not have constexpr containers with `push_back`

**Comment by BillyONeal** [comment]
> :: cries in tuple ::

Yeah, that's the thing with this change and why we aren't already shipping it. A few lines of product code but a lot of tests are necessary. (That's why we haven't jumped on / tried to merge this now that we have tests here on GH)

> On a more serious note I dont think I can write the tests fo the `*_inserter` as we do not have constexpr containers with `push_back`

You can write something like this pseudocode:

````
struct constexpr_container {
    using value_type = int;

    array<5> buffer{};
    size_t selected = 0;
    void push_back(int i) { buffer[selected++] = i; }
};

constexpr bool test() {
    constexpr_container c;
    auto tested = back_inserter(c);
    *tested++ = 42;
    *tested++ = 1729;
    *tested++ = 1234;
    assert(c.buffer == {42, 1729, 1234, 0, 0});
    return true;
}

int main() {
assert(test());
static_assert(test());
}

**Comment by miscco** [comment]
@BillyONeal Thanks a lot for the code example. I will try it out, the other tests are hopefully finished. I went with all those tuple constructors on [cppreference ](https://en.cppreference.com/w/cpp/utility/tuple/tuple)

**Comment by miscco** [comment]
I went through all the changes and even found some bugs. 

Who would have thought that tests do actually help.

**Comment by BillyONeal** [comment]
And people wonder why I'm so adamant about "no product changes without corresponding tests"

**Comment by miscco** [comment]
Do you have no faith?

**Comment by BillyONeal** [comment]
None.

**Comment by BillyONeal** [comment]
> I am a random person from the internet, what could go wrong?

It has nothing to do with you being a random person on the internet, only the "person" part. The only person I've seen with a brain compiler with a near 0% failure rate is Stephan ... and even then not close enough to 0 that I don't want tests :)

File: tests/std/tests/P1032R1_Misc_constexpr/test.cpp [hunk 1]
```diff
@@ -0,0 +1,195 @@
...
+        assert(input.buffer[0] == 0 && input.buffer[1] == 42 && input.buffer[2] == 1729 && input.buffer[3] == 1234
+               && input.buffer[4] == 4 && input.buffer[5] == 5);
+    }
+
+    // test default_inserter
+    {
+        string_view in     = "This is some string";
+        string_view needle = "some";
+        default_searcher foo{needle.begin(), needle.end()};
+        auto [first, second] = foo(in.begin(), in.end());
```
Comment (miscco) [inline tests/std/tests/P1032R1_Misc_constexpr/test.cpp]: This feels like a bug. `first` and `second` are not used at all but there is no `unused variable` warning/error. which triggered everywhere else.

Could this be due to the implicit code generated by the compiler for the structured bindings?

**Comment by miscco** [comment]
I rebased on #589

**Comment by miscco** [comment]
Rebased again due to whatever conflict there was

**Comment by CaseyCarter** [comment]
From https://github.com/microsoft/STL/pull/599#discussion_r391329686: we'll need to rebase this atop #599, update the value of `__cpp_lib_array_constexpr`, and fix libc++'s `language.support\support.limits\support.limits.general\array.version.pass.cpp` test.

**Comment by miscco** [comment]
So I rebased upon @Weheineman work and now I get some erros that I really do not understand:

> --
> C:\agent\_work\1\s\tests\std\tests\Dev11_0343056_pair_tuple_ctor_sfinae\test.cpp(150,19): error: unused variable 't3' [-Werror,-Wunused-variable]
> 
>         tuple<A*> t3(allocator_arg, al, nullptr);
>                   ^
> 
> C:\agent\_work\1\s\tests\std\tests\Dev11_0343056_pair_tuple_ctor_sfinae\test.cpp(144,19): error: unused variable 't1' [-Werror,-Wunused-variable]
> 
>         tuple<A*> t1(allocator_arg, al);
>                   ^
> 2 errors generated.
> --

Those variables were unused before. How does my change affect this code?

The other errors seem valid as string_view::copy was incorrectly marked as `constexpr` in C++17 and I will simply add a `#if _HAS_CXX20`

**Comment by miscco** [comment]
Rebased on master. I still have no Idea why the tests a suddenly failing. 

Should we investigate or should we simply add a `(void)` to supress those warnings

**Comment by StephanTLavavej** [comment]
> Should we investigate or should we simply add a `(void)` to supress those warnings

Just `(void)` is fine. Those tests aren't interested in actually using the variables, just verifying that they can be constructed. Now that you're adding `constexpr` to the constructors, Clang can more easily see that there are no interesting side effects, so it warns.

File: tests/std/tests/P1032R1_Misc_constexpr/test.cpp (hunk 1 above)
Comment (StephanTLavavej) [reply tests/std/tests/P1032R1_Misc_constexpr/test.cpp]: Perhaps it's because sometimes people want to ignore part of the output (I've heard they name variables `_` to do this), but yeah, seems like a diagnostic opportunity.

File: stl/inc/iterator [hunk 2]
```diff
@@ -38,27 +38,28 @@ public:
     using difference_type = void;
 #endif // __cpp_lib_concepts
 
-    explicit back_insert_iterator(_Container& _Cont) noexcept /* strengthened */ : container(_STD addressof(_Cont)) {}
+    explicit _CONSTEXPR20 back_insert_iterator(_Container& _Cont) noexcept /* strengthened */
```
[the remark this answers is not in the document]
Comment (miscco) [reply stl/inc/iterator:41]: Done

File: tests/std/tests/P1032R1_miscellaneous_constexpr/test.cpp [hunk 3]
```diff
@@ -0,0 +1,195 @@
...
+#include <utility>
+
+using namespace std;
+
+struct constexpr_container {
+    using value_type = int;
+    using iterator   = array<value_type, 6>::iterator;
+
+    array<value_type, 6> buffer{};
+    size_t selected = 0;
```
[the remark this answers is not in the document]
Comment (miscco) [reply tests/std/tests/P1032R1_miscellaneous_constexpr/test.cpp:20]: Technically correct is the best correct. Done

File: tests/std/tests/P1032R1_miscellaneous_constexpr/test.cpp [hunk 4]
```diff
@@ -0,0 +1,195 @@
...
+    constexpr void push_back(const value_type i) {
+        buffer[selected++] = i;
+    }
+    constexpr void push_front(const value_type i) {
+        buffer[selected++] = i;
+    }
```
[the remark this answers is not in the document]
Comment (miscco) [reply tests/std/tests/P1032R1_miscellaneous_constexpr/test.cpp:26]: Added a comment that each functio is for a test of the specific iterator

File: tests/std/tests/P1032R1_miscellaneous_constexpr/test.cpp [hunk 5]
```diff
@@ -0,0 +1,195 @@
...
+    constexpr iterator insert(iterator where, const value_type i) {
+        *where = i;
```
[the remark this answers is not in the document]
Comment (miscco) [reply tests/std/tests/P1032R1_miscellaneous_constexpr/test.cpp:28]: Added a comment that it is purely for test of `insert_iterator`

File: tests/std/tests/P1032R1_miscellaneous_constexpr/test.cpp [hunk 6]
```diff
@@ -0,0 +1,195 @@
...
+        return where;
+    }
+    constexpr iterator begin() {
+        return std::next(buffer.begin());
```
[the remark this answers is not in the document]
Comment (miscco) [reply tests/std/tests/P1032R1_miscellaneous_constexpr/test.cpp:32]: Good habits break hard. I removed all occurances of `std::` from the file

File: tests/std/tests/P1032R1_miscellaneous_constexpr/test.cpp [hunk 7]
```diff
@@ -0,0 +1,195 @@
...
+    }
+
+    // test pair assignment operator
+    {
+        pair<int, int> input{1, 2};
+        pair<int, int> copyAssignment;
+        copyAssignment = input;
+
+        pair<int, int> moveAssignment;
+        moveAssignment = std::move(input);
```
[the remark this answers is not in the document]
Comment (miscco) [reply tests/std/tests/P1032R1_miscellaneous_constexpr/test.cpp:54]: Ditto

File: tests/std/tests/P1032R1_miscellaneous_constexpr/test.cpp [hunk 8]
```diff
@@ -0,0 +1,195 @@
...
+        *where = i;
+        return where;
+    }
+    constexpr iterator begin() {
+        return std::next(buffer.begin());
+    }
+};
+
+constexpr bool run_tests() {
+    // test tuple pair constructor
```
[the remark this answers is not in the document]
Comment (miscco) [reply tests/std/tests/P1032R1_miscellaneous_constexpr/test.cpp:37]: Done

File: tests/std/tests/P1032R1_miscellaneous_constexpr/test.cpp [hunk 9]
```diff
@@ -0,0 +1,195 @@
...
+    {
+        tuple<int, int, double, double> first{1, 2, 0.5, 2.0};
+        tuple<double, int> second{2.0, 1};
+        pair<tuple<int, int, double, double>, tuple<double, int>> foo{
+            first, second, make_index_sequence<4>{}, make_index_sequence<2>{}};
```
[the remark this answers is not in the document]
Comment (miscco) [reply tests/std/tests/P1032R1_miscellaneous_constexpr/test.cpp:42]: Removed

File: tests/std/tests/P1032R1_miscellaneous_constexpr/test.cpp [hunk 10]
```diff
@@ -0,0 +1,195 @@
...
+
+        pair<tuple<int, int, double, double>, tuple<double, int>> bar{piecewise_construct_t{}, first, second};
```
[the remark this answers is not in the document]
Comment (miscco) [reply tests/std/tests/P1032R1_miscellaneous_constexpr/test.cpp:44]: Replaced all `foo´s with `meow`s

File: tests/std/tests/P1032R1_miscellaneous_constexpr/test.cpp [hunk 11]
```diff
@@ -0,0 +1,195 @@
...
+        swap(pair1, pair2);
+        assert(pair1.first == 3 && pair1.second == 4 && pair2.first == 1 && pair2.second == 2);
+
+        pair1.swap(pair2);
+        assert(pair1.first == 1 && pair1.second == 2 && pair2.first == 3 && pair2.second == 4);
+    }
+
+    // test empty tuple
+    {
+        allocator<int> alloc;
```
[the remark this answers is not in the document]
Comment (miscco) [reply tests/std/tests/P1032R1_miscellaneous_constexpr/test.cpp:77]: Done

File: tests/std/tests/P1032R1_miscellaneous_constexpr/test.cpp [hunk 12]
```diff
@@ -0,0 +1,195 @@
...
+        tuple<> tuple_alloc{allocator_arg_t{}, alloc};
```
[the remark this answers is not in the document]
Comment (miscco) [reply tests/std/tests/P1032R1_miscellaneous_constexpr/test.cpp:78]: Done

File: tests/std/tests/P1032R1_miscellaneous_constexpr/test.cpp [hunk 13]
```diff
@@ -0,0 +1,195 @@
...
+        tuple<> tuple_alloc_value{_Alloc_exact_args_t{}, alloc};
+
+        swap(tuple_alloc, tuple_alloc_copy);
+        tuple_alloc.swap(tuple_alloc_copy);
+    }
+
+    // test tuple
+    {
+        allocator<int> alloc;
+        tuple<short, int> conversionInput{short(1), 1};
```
[the remark this answers is not in the document]
Comment (miscco) [reply tests/std/tests/P1032R1_miscellaneous_constexpr/test.cpp:89]: Done

File: tests/std/tests/P1032R1_miscellaneous_constexpr/test.cpp [hunk 14]
```diff
@@ -0,0 +1,195 @@
...
+        tuple<int, double> tuple_alloc_move{allocator_arg_t{}, alloc, std::move(tuple_alloc)};
+
+        swap(tuple_alloc, tuple_alloc_copy);
+        tuple_alloc.swap(tuple_alloc_copy);
+    }
+
+    // test array::swap
+    {
+        array<int, 2> array1{1, 2};
+        array<int, 2> array2{3, 4};
```
[the remark this answers is not in the document]
Comment (miscco) [reply tests/std/tests/P1032R1_miscellaneous_constexpr/test.cpp:111]: Added braces just to be safe and consistent

File: tests/std/tests/P1032R1_miscellaneous_constexpr/test.cpp [hunk 15]
```diff
@@ -0,0 +1,195 @@
...
+        array<int, 0> array_empty1 = {};
+        array<int, 0> array_empty2 = {};
+
+        swap(array_empty1, array_empty2);
+        array_empty1.swap(array_empty2);
+    }
+
+    // test array::fill
+    {
+        array<int, 2> foo = {};
```
[the remark this answers is not in the document]
Comment (miscco) [reply tests/std/tests/P1032R1_miscellaneous_constexpr/test.cpp:128]: meow

File: tests/std/tests/P1032R1_miscellaneous_constexpr/test.cpp [hunk 16]
```diff
@@ -0,0 +1,195 @@
...
+    }
+
+    // test back_inserter
+    {
+        constexpr_container input;
+        int toBeMoved = 5;
+        auto tested   = back_inserter(input);
+
+        *tested++   = 42;
+        *(++tested) = 1729;
```
[the remark this answers is not in the document]
Comment (miscco) [reply tests/std/tests/P1032R1_miscellaneous_constexpr/test.cpp:140]: Removed, although I find it easier to grog that way

File: tests/std/tests/P1032R1_miscellaneous_constexpr/test.cpp [hunk 17]
```diff
@@ -0,0 +1,195 @@
...
+        *tested++   = 1234;
+        tested      = 4;
+        tested      = std::move(toBeMoved);
+
+        assert(input.buffer[0] == 0 && input.buffer[1] == 42 && input.buffer[2] == 1729 && input.buffer[3] == 1234
+               && input.buffer[4] == 4 && input.buffer[5] == 5);
+    }
+
+    // test default_inserter
```
[the remark this answers is not in the document]
Comment (miscco) [reply tests/std/tests/P1032R1_miscellaneous_constexpr/test.cpp:181]: renamed to default_searcher

File: tests/std/tests/P1032R1_miscellaneous_constexpr/test.cpp [hunk 18]
```diff
@@ -0,0 +1,195 @@
...
+    {
+        string_view in     = "This is some string";
+        string_view needle = "some";
+        default_searcher foo{needle.begin(), needle.end()};
+        auto [first, second] = foo(in.begin(), in.end());
```
[the remark this answers is not in the document]
Comment (miscco) [reply tests/std/tests/P1032R1_miscellaneous_constexpr/test.cpp:186]: Done

**Comment by miscco** [comment]
> 
> 
> > Should we investigate or should we simply add a `(void)` to supress those warnings
> 
> Just `(void)` is fine. Those tests aren't interested in actually using the variables, just verifying that they can be constructed. Now that you're adding `constexpr` to the constructors, Clang can more easily see that there are no interesting side effects, so it warns.

I just realized that these are libc++ tests so just adding `(void)` will take me about a year, so I add them to skipped

File: stl/inc/yvals_core.h [hunk 19]
```diff
@@ -173,6 +173,7 @@
 // P1006R1 constexpr For pointer_traits<T*>::pointer_to()
 // P1023R0 constexpr For std::array Comparisons
 // P1024R3 Enhancing span Usability
+// P1032R1 Miscellaneous constexpr
```
[the remark this answers is not in the document]
Comment (miscco) [reply stl/inc/yvals_core.h:176]: Thanks a lot ;)

[the remark this answers is not in the document]
Comment (miscco) [reply stl/inc/yvals_core.h:176]: There was some reason but I cannot really remember anymore. Will fix this with some `is_constant_evaluated` magic

**Comment by miscco** [comment]
Added string changes

**Comment by CaseyCarter** [comment]
> > > Should we investigate or should we simply add a `(void)` to supress those warnings
> > 
> > 
> > Just `(void)` is fine. Those tests aren't interested in actually using the variables, just verifying that they can be constructed. Now that you're adding `constexpr` to the constructors, Clang can more easily see that there are no interesting side effects, so it warns.
> 
> I just realized that these are libc++ tests so just adding `(void)` will take me about a year, so I add them to skipped

I've [updated `test/std/utilities/tuple/tuple.tuple/tuple.cnstr/alloc_const_Types.pass.cpp` upstream](https://github.com/llvm/llvm-project/commit/470eb62d7bcd57fa59bc29e8d662b1c24d84fbc4) to silence the "unused variable" warning, and pushed an LLVM reference update into #708. We'll have to fixup whichever of this PR or #708 that merges second, but I thought it made more sense to update the LLVM reference in the "Clang 10" PR than in this one.

**Comment by miscco** [comment]
Thanks Casey, I will habe a look at it tomorrow

**Comment by miscco** [comment]
I believe we need to disable version.pass too, wondering how that worked given the different states of C++17/20 progress

**Comment by CaseyCarter** [comment]
> I've [updated `test/std/utilities/tuple/tuple.tuple/tuple.cnstr/alloc_const_Types.pass.cpp` upstream](https://github.com/llvm/llvm-project/commit/470eb62d7bcd57fa59bc29e8d662b1c24d84fbc4) to silence the "unused variable" warning, and pushed an LLVM reference update into #708 

This "tiny update" wasn't: upstream has been tinkering with the test machinery in ways that break us. I've pulled the update out of #708 while @cbezault and I figure out what's happened and how to fix it. I'll get back to you ;)

File: stl/inc/xstring [hunk 20]
```diff
@@ -118,7 +118,7 @@ struct _Char_traits { // properties of a string or stream element
         if (!_STD is_constant_evaluated())
 #endif // __cpp_lib_is_constant_evaluated
         {
-            return reinterpret_cast<_Elem*>(_CSTD memset(reinterpret_cast<wchar_t*>(_First), _Ch, _Count));
+            return reinterpret_cast<_Elem*>(_CSTD memset(_First, _Ch, _Count));
```
Comment (CaseyCarter) [inline stl/inc/xstring:121]:
```suggestion
            return static_cast<_Elem*>(_CSTD memset(_First, _Ch, _Count));

```

Comment (CaseyCarter) [reply stl/inc/xstring:121]: Pre-existing: How is this not completely broken when `sizeof(_Elem) != 1`?

Comment (CaseyCarter) [reply stl/inc/xstring:121]: ...unless I can convince everyone that we should not ship a primary `char_traits` template?

Comment (miscco) [reply stl/inc/xstring:121]: Ist there a specialization for `wchar_t`?

I guess that should be safe then

File: tests/libcxx/expected_results.txt [hunk 21]
```diff
@@ -450,28 +450,11 @@ std/language.support/support.limits/support.limits.general/functional.version.pa
 std/language.support/support.limits/support.limits.general/iterator.version.pass.cpp SKIP
 std/language.support/support.limits/support.limits.general/memory.version.pass.cpp SKIP
 
-# C++20 P1032R1 "Miscellaneous constexpr"
+# C++20 P1032R1 "Miscellaneous constexpr" is not fully implemented by libc++
```
[the remark this answers is not in the document]
Comment (miscco) [reply tests/libcxx/expected_results.txt:453]: Done

File: stl/inc/xstring (hunk 20 above)
Comment (miscco) [reply stl/inc/xstring]: Argh, this was just me bein clueless and assuming that memset would to the right thing.
Turns out it requires jts second argument (`_Ch`) to be of type `int` and then casts it hard to `unsigned char`. 

That means we cannut use it here. 

And I was wondering why it was missing...

**Comment by miscco** [comment]
Out of curriosity, I found that the following is not compiling:

```cpp
        string_view in     = "This is some string";
        string_view needle = "some";
        default_searcher meow{needle.begin(), needle.end()};
        auto [first, last] = meow(in.begin(), in.end());
        string_view result1(first, last - first); // <-- Does not compile
        string_view result2(first, last);          // <-- Does not compile
```

I would have expected to be able to create a `string_view` back from the two iterators

File: stl/inc/xstring [hunk 22]
```diff
@@ -82,13 +93,25 @@ struct _Char_traits { // properties of a string or stream element
...
+#ifdef __cpp_lib_is_constant_evaluated
+        if (!_STD is_constant_evaluated())
+#endif // __cpp_lib_is_constant_evaluated
+        {
+            return static_cast<_Elem*>(_CSTD memmove(_First1, _First2, _Count * sizeof(_Elem)));
+        }
+
+        for (size_t _Idx = 0; _Idx < _Count; ++_Idx) {
+            *(_First1 + _Idx) = *(_First2 + _Idx);
+        }
```
Comment (CaseyCarter) [inline stl/inc/xstring:108]: This won't work if `_First1` is in `[_First2, _First2 + _Count)`, since it overwrites the contents of `[_First1, _First2 + _Count)` before copying from that range.
```suggestion
        if (_First1 <= _First2) {
            for (size_t _Idx = 0; _Idx < _Count; ++_Idx) {
                *(_First1 + _Idx) = *(_First2 + _Idx);
            }
        } else {
            for (size_t _Idx = _Count; _Idx-- > 0;) {
                *(_First1 + _Idx) = *(_First2 + _Idx);
            }
        }
```

File: stl/inc/xstring [hunk 23]
```diff
@@ -169,11 +192,22 @@ struct _WChar_traits { // char_traits for the char16_t-likes: char16_t, wchar_t,
...
+        {
+            return reinterpret_cast<_Elem*>(
+                _CSTD wmemcpy(reinterpret_cast<wchar_t*>(_First1), reinterpret_cast<const wchar_t*>(_First2), _Count));
+        }
+
+        for (size_t _Idx = 0; _Idx < _Count; ++_Idx) {
+            *(_First1 + _Idx) = *(_First2 + _Idx);
+        }
+
+        return static_cast<_Elem*>(_First1);
```
Comment (CaseyCarter) [inline stl/inc/xstring:210]: Ditto:
```suggestion
        return _First1;
```

File: stl/inc/xstring [hunk 24]
```diff
@@ -198,17 +232,40 @@ struct _WChar_traits { // char_traits for the char16_t-likes: char16_t, wchar_t,
...
+        {
+            return reinterpret_cast<_Elem*>(
+                _CSTD wmemmove(reinterpret_cast<wchar_t*>(_First1), reinterpret_cast<const wchar_t*>(_First2), _Count));
+        }
+
+        for (size_t _Idx = 0; _Idx < _Count; ++_Idx) {
+            *(_First1 + _Idx) = *(_First2 + _Idx);
+        }
+
+        return static_cast<_Elem*>(_First1);
```
Comment (CaseyCarter) [inline stl/inc/xstring:250]: Ditto:
```suggestion
        return _First1;
```

File: stl/inc/xstring [hunk 25]
```diff
@@ -198,17 +232,40 @@ struct _WChar_traits { // char_traits for the char16_t-likes: char16_t, wchar_t,
...
+        if (!_STD is_constant_evaluated())
+#endif // __cpp_lib_is_constant_evaluated
+        {
+            return reinterpret_cast<_Elem*>(
+                _CSTD wmemmove(reinterpret_cast<wchar_t*>(_First1), reinterpret_cast<const wchar_t*>(_First2), _Count));
+        }
+
+        for (size_t _Idx = 0; _Idx < _Count; ++_Idx) {
+            *(_First1 + _Idx) = *(_First2 + _Idx);
+        }
```
Comment (CaseyCarter) [inline stl/inc/xstring:248]: Ditto:
```suggestion
        if (_First1 <= _First2) {
            for (size_t _Idx = 0; _Idx < _Count; ++_Idx) {
                *(_First1 + _Idx) = *(_First2 + _Idx);
            }
        } else {
            for (size_t _Idx = _Count; _Idx-- > 0;) {
                *(_First1 + _Idx) = *(_First2 + _Idx);
            }
        }
```

File: stl/inc/xstring [hunk 26]
```diff
@@ -198,17 +232,40 @@ struct _WChar_traits { // char_traits for the char16_t-likes: char16_t, wchar_t,
...
-        return reinterpret_cast<_Elem*>(_CSTD wmemset(reinterpret_cast<wchar_t*>(_First), _Ch, _Count));
+#ifdef __cpp_lib_is_constant_evaluated
+        if (!_STD is_constant_evaluated())
+#endif // __cpp_lib_is_constant_evaluated
+        {
+            return reinterpret_cast<_Elem*>(_CSTD wmemset(reinterpret_cast<wchar_t*>(_First), _Ch, _Count));
+        }
+
+        _Elem* _Next = _First;
+        for (; 0 < _Count; --_Count, ++_Next) {
```
Comment (CaseyCarter) [inline stl/inc/xstring:264]: `_Next` isn't used outside this loop, and eww Yoda conditional:
```suggestion
        for (_Elem* _Next = _First; _Count > 0; --_Count, ++_Next) {
```

File: stl/inc/xstring [hunk 27]
```diff
@@ -326,10 +383,21 @@ struct _Narrow_char_traits { // Implement char_traits for narrow character types
...
+#endif // __cpp_lib_is_constant_evaluated
+        {
+            return static_cast<_Elem*>(_CSTD memcpy(_First1, _First2, _Count));
+        }
+
+        for (size_t _Idx = 0; _Idx < _Count; ++_Idx) {
+            *(_First1 + _Idx) = *(_First2 + _Idx);
+        }
+
+        return static_cast<_Elem*>(_First1);
```
Comment (CaseyCarter) [inline stl/inc/xstring:400]: Ditto:
```suggestion
        return _First1;
```

File: stl/inc/xstring [hunk 28]
```diff
@@ -361,16 +429,40 @@ struct _Narrow_char_traits { // Implement char_traits for narrow character types
...
+#endif // __cpp_lib_is_constant_evaluated
+        {
+            return static_cast<_Elem*>(_CSTD memmove(_First1, _First2, _Count));
+        }
+
+        for (size_t _Idx = 0; _Idx < _Count; ++_Idx) {
+            *(_First1 + _Idx) = *(_First2 + _Idx);
+        }
+
+        return static_cast<_Elem*>(_First1);
```
Comment (CaseyCarter) [inline stl/inc/xstring:446]: Ditto:
```suggestion
        return _First1;
```

File: stl/inc/xstring [hunk 29]
```diff
@@ -361,16 +429,40 @@ struct _Narrow_char_traits { // Implement char_traits for narrow character types
...
+#ifdef __cpp_lib_is_constant_evaluated
+        if (!_STD is_constant_evaluated())
+#endif // __cpp_lib_is_constant_evaluated
+        {
+            return static_cast<_Elem*>(_CSTD memmove(_First1, _First2, _Count));
+        }
+
+        for (size_t _Idx = 0; _Idx < _Count; ++_Idx) {
+            *(_First1 + _Idx) = *(_First2 + _Idx);
+        }
```
Comment (CaseyCarter) [inline stl/inc/xstring:444]: Ditto:
```suggestion
        if (_First1 <= _First2) {
            for (size_t _Idx = 0; _Idx < _Count; ++_Idx) {
                *(_First1 + _Idx) = *(_First2 + _Idx);
            }
        } else {
            for (size_t _Idx = _Count; _Idx-- > 0;) {
                *(_First1 + _Idx) = *(_First2 + _Idx);
            }
        }
```

File: stl/inc/xstring [hunk 30]
```diff
@@ -361,16 +429,40 @@ struct _Narrow_char_traits { // Implement char_traits for narrow character types
...
-        return static_cast<_Elem*>(_CSTD memset(_First, _Ch, _Count));
+#ifdef __cpp_lib_is_constant_evaluated
+        if (!_STD is_constant_evaluated())
+#endif // __cpp_lib_is_constant_evaluated
+        {
+            return static_cast<_Elem*>(_CSTD memset(_First, _Ch, _Count));
+        }
+
+        _Elem* _Next = _First;
+        for (; 0 < _Count; --_Count, ++_Next) {
```
Comment (CaseyCarter) [inline stl/inc/xstring:461]: Ditto:
```suggestion
        for (_Elem* _Next = _First; _Count > 0; --_Count, ++_Next) {
```

File: stl/inc/xstring [hunk 31]
```diff
@@ -1306,7 +1398,8 @@ public:
         *this  = _Tmp;
     }
 
-    constexpr size_type copy(_Out_writes_(_Count) _Elem* const _Ptr, size_type _Count, const size_type _Off = 0) const {
```
Comment (CaseyCarter) [inline stl/inc/xstring:1309]: Hmmmmm - this was previously `constexpr` because we speculatively implemented the proposed resolution of LWG-2780 (and on 3865). LWG-2780 was resolved by application of WG21-P1032. So while this is a righteous change, I'm concerned about breaking users who took advantage of this previously non-portable behavior in C++17 mode. I think I'd rather keep vanilla `constexpr` on these functions, and continue to have C++17 be not-quite conforming here.

Opinions?

File: stl/inc/iterator [hunk 32]
```diff
@@ -92,27 +93,28 @@ public:
     using difference_type = void;
 #endif // __cpp_lib_concepts
 
-    explicit front_insert_iterator(_Container& _Cont) : container(_STD addressof(_Cont)) {}
+    _CONSTEXPR20 explicit front_insert_iterator(_Container& _Cont) : container(_STD addressof(_Cont)) {}
 
-    front_insert_iterator& operator=(const typename _Container::value_type& _Val) { // push value into container
+    _CONSTEXPR20 front_insert_iterator& operator=(
+        const typename _Container::value_type& _Val) { // push value into container
```
Comment (CaseyCarter) [inline stl/inc/iterator:99]:
```suggestion
    _CONSTEXPR20 front_insert_iterator& operator=(const typename _Container::value_type& _Val) {
        // push value into container
```

File: tests/std/tests/P0220R1_string_view/test.cpp [hunk 33]
```diff
@@ -1034,11 +1034,11 @@ static_assert(test_case_iterators<char, constexpr_char_traits>());
 static_assert(test_case_prefix<char, constexpr_char_traits>());
 static_assert(test_case_suffix<char, constexpr_char_traits>());
 static_assert(test_case_swap<char, constexpr_char_traits>());
-static_assert(test_case_copy<constexpr_char_traits>());
 static_assert(test_case_Copy_s<constexpr_char_traits>());
 static_assert(test_case_substr<constexpr_char_traits>());
 static_assert(test_case_compare<char, constexpr_char_traits>());
 #if _HAS_CXX20
+static_assert(test_case_copy<constexpr_char_traits>());
```
Comment (CaseyCarter) [inline tests/std/tests/P0220R1_string_view/test.cpp:1041]: If we revert the change to `basic_string_view` we should revert this test change also.

File: stl/inc/tuple [hunk 34]
```diff
@@ -163,20 +163,21 @@ struct _Tuple_val { // stores each value in a tuple
     constexpr _Tuple_val(_Other&& _Arg) : _Val(_STD forward<_Other>(_Arg)) {}
 
     template <class _Alloc, class... _Other, enable_if_t<!uses_allocator_v<_Ty, _Alloc>, int> = 0>
-    _Tuple_val(const _Alloc&, allocator_arg_t, _Other&&... _Arg) : _Val(_STD forward<_Other>(_Arg)...) {}
+    _CONSTEXPR20 _Tuple_val(const _Alloc&, allocator_arg_t, _Other&&... _Arg) : _Val(_STD forward<_Other>(_Arg)...) {}
```
Comment (CaseyCarter) [inline stl/inc/tuple:166]: `_Tuple_val` is internal machinery; we can simply make these `constexpr`. (Here, 172, and 179.)

File: stl/inc/tuple [hunk 35]
```diff
@@ -209,18 +210,18 @@ public:
...
     template <class _Alloc>
-    tuple(allocator_arg_t, const _Alloc&, const tuple&) noexcept /* strengthened */ {}
+    _CONSTEXPR20 tuple(allocator_arg_t, const _Alloc&, const tuple&) noexcept /* strengthened */ {}
 
     template <class _Tag, enable_if_t<is_same_v<_Tag, _Exact_args_t>, int> = 0>
     constexpr tuple(_Tag) noexcept /* strengthened */ {}
 
     template <class _Tag, class _Alloc, enable_if_t<is_same_v<_Tag, _Alloc_exact_args_t>, int> = 0>
-    tuple(_Tag, const _Alloc&) noexcept /* strengthened */ {}
+    _CONSTEXPR20 tuple(_Tag, const _Alloc&) noexcept /* strengthened */ {}
```
Comment (CaseyCarter) [inline stl/inc/tuple:222]: Ditto "plain `constexpr` because internal machinery". (And on 255, 261, and 264.)

File: stl/inc/tuple [hunk 36]
```diff
@@ -627,27 +631,28 @@ public:
...
 
-    void swap(tuple& _Right) noexcept(conjunction_v<_Is_nothrow_swappable<_This>, _Is_nothrow_swappable<_Rest>...>) {
+    _CONSTEXPR20 void swap(tuple& _Right) noexcept(
+        conjunction_v<_Is_nothrow_swappable<_This>, _Is_nothrow_swappable<_Rest>...>) {
         _Swap_adl(_Myfirst._Val, _Right._Myfirst._Val);
         _Mybase::swap(_Right._Get_rest());
     }
 
-    _Mybase& _Get_rest() noexcept { // get reference to rest of elements
+    _CONSTEXPR20 _Mybase& _Get_rest() noexcept { // get reference to rest of elements
```
Comment (CaseyCarter) [inline stl/inc/tuple:655]: Ditto "plain `constexpr` internal machinery".

File: stl/inc/tuple [hunk 37]
```diff
@@ -825,7 +830,7 @@ constexpr tuple<_This, _Rest...>::tuple(_Tag, _Tpl&& _Right, index_sequence<_Ind
 template <class _This, class... _Rest>
 template <class _Tag, class _Alloc, class _Tpl, size_t... _Indices,
     enable_if_t<is_same_v<_Tag, _Alloc_unpack_tuple_t>, int>>
-tuple<_This, _Rest...>::tuple(_Tag, const _Alloc& _Al, _Tpl&& _Right, index_sequence<_Indices...>)
+_CONSTEXPR20 tuple<_This, _Rest...>::tuple(_Tag, const _Alloc& _Al, _Tpl&& _Right, index_sequence<_Indices...>)
```
Comment (CaseyCarter) [inline stl/inc/tuple:833]: Ditto "plain `constexpr` internal machinery" (Also 1004) be careful to update the declaration of 1004 in `<utility>` consistently.

File: stl/inc/utility [hunk 38]
```diff
@@ -265,18 +265,18 @@ struct pair { // store a pair of values
 #endif // ^^^ !_HAS_CONDITIONAL_EXPLICIT ^^^
 
     template <class _Tuple1, class _Tuple2, size_t... _Indexes1, size_t... _Indexes2>
-    pair(_Tuple1& _Val1, _Tuple2& _Val2, index_sequence<_Indexes1...>, index_sequence<_Indexes2...>);
+    _CONSTEXPR20 pair(_Tuple1& _Val1, _Tuple2& _Val2, index_sequence<_Indexes1...>, index_sequence<_Indexes2...>);
```
Comment (CaseyCarter) [inline stl/inc/utility:268]: This should be plain `constexpr` since it's internal machinery.

File: stl/inc/xstring (hunk 22 above)
Comment (miscco) [reply stl/inc/xstring:108]: Any reason to not copy backwards by default?

File: stl/inc/xstring (hunk 25 above)
Comment (miscco) [reply stl/inc/xstring:248]: Ditto always copy backwards?

File: stl/inc/xstring (hunk 26 above)
Comment (miscco) [reply stl/inc/xstring]: That is what you get for mindlessly copying code around

File: stl/inc/xstring (hunk 29 above)
Comment (miscco) [reply stl/inc/xstring:443]: Ditto only copying backwards?

File: stl/inc/tuple (hunk 34 above)
Comment (miscco) [reply stl/inc/tuple:166]: Done

File: stl/inc/tuple (hunk 35 above)
Comment (miscco) [reply stl/inc/tuple:222]: Done

File: stl/inc/tuple (hunk 36 above)
Comment (miscco) [reply stl/inc/tuple:655]: Done

File: stl/inc/tuple (hunk 37 above)
Comment (miscco) [reply stl/inc/tuple:833]: Done

File: stl/inc/utility (hunk 38 above)
Comment (miscco) [reply stl/inc/utility:268]: Done

File: stl/inc/xstring (hunk 22 above)
Comment (miscco) [reply stl/inc/xstring:108]: Also related. All other siblings of this method have a non-`const` `_Count` parameter that is then directly decremented in the loop. I believe we should stay consistent and follow the same pattern everywhere:

```cpp
    _NODISCARD static _CONSTEXPR17 const _Elem* find(
        _In_reads_(_Count) const _Elem* _First, size_t _Count, const _Elem& _Ch) noexcept /* strengthened */ {
        // look for _Ch in [_First, _First + _Count)
        for (; 0 < _Count; --_Count, ++_First) {
            if (*_First == _Ch) {
                return _First;
            }
        }

        return nullptr;
    }
```

File: stl/inc/xstring (hunk 31 above)
Comment (miscco) [reply stl/inc/xstring:1309]: *gasps* non conformance *gasps*

Im fine with it but I guess that is not my desicion ;)

File: stl/inc/xstring (hunk 22 above)
Comment (CaseyCarter) [reply stl/inc/xstring:108]: > Any reason to not copy backwards by default?

Copying backwards doesn't work if `_First2` is in `[_First1, _First1 + _Count)`.

> All other siblings of this method have a non-`const` `_Count` parameter that is then directly decremented in the loop. I believe we should stay consistent and follow the same pattern everywhere.

I have no strong feelings, so feel free to make changes if you do.

**Comment by miscco** [comment]
A question for the language lawyers:

* A `constexpr` function is expressedly forbidden to invoke undefined behavior.
* `char_traits::copy` explicitly names calling it with overlapping ranges as UB

The question is should we work around the issue by doing the "right" thing and copy backwards or should we `static_assert` that the input range is indeed valid.

**Comment by miscco** [comment]
That warning seems invalid. Should we suppress it?

**Comment by StephanTLavavej** [comment]
It indeed appears that the `warning C6101: Returning uninitialized memory '*_First1'.  A successful path through the function does not set the named _Out_ parameter.` is spurious. I've been grumbling for *years* about our SAL annotations, especially now that SAL is not the future. (Usually it's because SAL annotations are extremely difficult to craft, and almost every time I see one being added, I can find something wrong with it - but spurious warnings are also a concern.) I see 3 possible approaches:
1. Suppress the warning.
2. Suppress the warning and file a reduced test case on Developer Community to be a good kitty.
3. Remove these SAL annotations.

File: stl/inc/xstring (hunk 31 above)
Comment (StephanTLavavej) [reply stl/inc/xstring:1309]: I highly doubt there are any such users, because the traits `copy` wasn't `constexpr`, so this would only have been possible with a custom traits class.

**Comment by miscco** [comment]
I tried reducing this but ended up in hell or heaven depending on how you look at it as I was not able to reproduce the issue in a reduced test case.

Could I just throw the glass from the table and let you be the rescue kitty to file the issue?

Also I have to note that the test failures do not make any sense. 

The failing tests never instantiate anything related to char. This should be the tests for char_traits not the generic algorithm tests

**Comment by StephanTLavavej** [comment]
Sure, thanks for trying. I’ll investigate soon - currently trying to get #621 merged before the 16.7 branch locks down for release. 🐱

**Comment by miscco** [comment]
Someone intertested in fixing clang?

**Comment by CaseyCarter** [comment]
> Someone interested in fixing clang?

I took a quick peek: the `char_traits`-related failures seem legitimate. We can't compare pointers into distinct arrays with relational operators in a constant expression even if MSVC doesn't know it's supposed to diagnose doing so as ill-formed. I think this is fixable for `char` and `char8_t` by using `__builtin_memcpy` and `__builtin_memmove`, and for `char16_t`, `wchar_t`, and perhaps `unsigned short` with `__builtin_wmemcpy` and `__builtin_wmemmove` (I don't remember if MSVC supports these). We'll have to leave MSVC (and `char32_t` for Clang) broken until we can get the compilers straightened out.

**Comment by miscco** [comment]
I am slightly torn here. Should we pull those changes out of the PR then. I mean these changes all require constexpr string and while it is worked on I am unsure at which time frame we can actually expect to use it. 

On the other hand setting feature macros is kinda cool

Also to be sure the fix you suggest is using the built ins instead of memmove because they are ideed constexpr. I hoe that w do not need any `if constexpr` here. I will have a look at this in the evening

**Comment by CaseyCarter** [comment]
> I am slightly torn here. Should we pull those changes out of the PR then. I mean these changes all require constexpr string and while it is worked on I am unsure at which time frame we can actually expect to use it.

I would rather merge what we can now than wait for three compiler front ends to implement the intrinsics we need to support `constexpr char_traits`.

> Also to be sure the fix you suggest is using the built ins instead of memmove because they are ideed constexpr. I hoe that w do not need any `if constexpr` here. I will have a look at this in the evening

Yes, the clang `__builtin_w?mem(cpy|move)` intrinsics are usable both in and out of constant expressions, so you should be able to simply:
```c++
    static _Elem* copy(_Out_writes_(_Count) _Elem* const _First1, _In_reads_(_Count) const _Elem* const _First2,
        const size_t _Count) noexcept /* strengthened */ {
        // copy [_First2, _First2 + _Count) to [_First1, ...)
#ifdef __clang__
        __builtin_memcpy(_First1, _First2, _Count);
        return _First1;
#else // ^^^ Clang / Other vvv
        return static_cast<_Elem*>(_CSTD memcpy(_First1, _First2, _Count));
#endif // __clang__
    }
```
for `_Narrow_char_traits::copy`, for example.

**Comment by miscco** [comment]
I went ahead and added a `_CONSTEXPR20_MEMOP` define. Should we have a `TRANSITION` comment? 

If so what would that number be?

I believe for assign we do not need those special cases as we only have one array

File: stl/inc/xstring [hunk 39]
```diff
@@ -169,11 +179,19 @@ struct _WChar_traits { // char_traits for the char16_t-likes: char16_t, wchar_t,
...
     }
 
-    static _Elem* copy(_Out_writes_all_(_Count) _Elem* const _First1, _In_reads_(_Count) const _Elem* const _First2,
-        const size_t _Count) noexcept /* strengthened */ {
+    static _CONSTEXPR20_MEMOP _Elem* copy(_Out_writes_all_(_Count) _Elem* const _First1,
+        _In_reads_(_Count) const _Elem* const _First2, const size_t _Count) noexcept /* strengthened */ {
         // copy [_First2, _First2 + _Count) to [_First1, ...)
+#ifdef __clang__
+        if constexpr (is_same_v<_Elem, wchar_t>) {
+            __builtin_wmemcpy(_First1, _First2, _Count);
```
Comment (cbezault) [inline stl/inc/xstring:187]: Are we missing a return statement here?

Comment (StephanTLavavej) [reply stl/inc/xstring:187]: I just pushed a fix. Thanks for finding this!

**Comment by StephanTLavavej** [comment]
After fixing the missing `return` statement, I am no longer experiencing crashes during the test run, but I am observing:

```
  Unexpected Failures:     9
  Unexpected Passes  :    18
```

Still investigating. (I figured fixing the crashes was important so I pushed a change before resolving everything.)

**Comment by miscco** [comment]
Thanks a lot i habe Bern busy the last week

File: stl/inc/xstring [hunk 40]
```diff
@@ -56,11 +56,15 @@ struct _Char_traits { // properties of a string or stream element
 
         return _Count;
     }
-
```
Comment (StephanTLavavej) [inline stl/inc/xstring:59]: This newline should be restored. We always separate functions with newlines, except in rare cases of very repetitive short functions.

File: stl/inc/xstring (hunk 31 above)
Comment (StephanTLavavej) [reply stl/inc/xstring:1304]: As I mentioned in the other comment, I'd like to resolve this in favor of the righteous, theoretically-source-breaking but in practice nobody will encounter it, change. Please meow if you are concerned.

File: stl/inc/xstring [hunk 41]
```diff
@@ -3764,7 +3822,8 @@ public:
         return size() == 0;
     }
 
-    size_type copy(_Out_writes_(_Count) _Elem* const _Ptr, size_type _Count, const size_type _Off = 0) const {
+    _CONSTEXPR20_MEMOP size_type copy(
+        _Out_writes_(_Count) _Elem* const _Ptr, size_type _Count, const size_type _Off = 0) const {
```
Comment (StephanTLavavej) [inline stl/inc/xstring:3826]: This change, modifying `basic_string`, should be reverted. [P1032R1](https://wg21.link/P1032R1) doesn't modify `basic_string` at all. (I was initially confused, because its sections 11 and 12 depict two `copy` changes - but they're changing the `basic_string_view` class definition in `[string.view.template]` and the `basic_string_view` member function definition in `[string.view.ops]`. Bonus confusion: the latter has a section name of `"String operations"`.)

It's #43 [P0980R1](https://wg21.link/P0980R1) `constexpr` `std::string`, which @mnatsuhara is currently investigating, that will change `basic_string::copy`. (I find it amusing that C++20 had so many `constexpr` papers, leading to double bonus confusion here - misreading P1032R1 as changing `basic_string::copy` won't be error-corrected by checking the Working Paper because it was changed there by another paper! :joy_cat:)

As an aside, which is now moot, this would have to be `_CONSTEXPR20`, not `_CONSTEXPR20_MEMOP`, since this calls `_Traits::copy` to do work, and the user might have provided a custom `constexpr` traits class.

File: tests/std/tests/P1032R1_miscellaneous_constexpr/test.cpp [hunk 42]
```diff
@@ -0,0 +1,207 @@
+// Copyright (c) Microsoft Corporation.
+// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
+
+#include <array>
+#include <assert.h>
+#include <functional>
+#include <iterator>
+#include <memory>
+#include <stddef.h>
+#include <string>
```
Comment (StephanTLavavej) [inline tests/std/tests/P1032R1_miscellaneous_constexpr/test.cpp:10]: `<string>` should be unnecessary in this test.

File: stl/inc/xstring [hunk 43]
```diff
@@ -56,11 +56,15 @@ struct _Char_traits { // properties of a string or stream element
 
         return _Count;
     }
-
-    static _Elem* copy(_Out_writes_all_(_Count) _Elem* const _First1, _In_reads_(_Count) const _Elem* _First2,
-        size_t _Count) noexcept /* strengthened */ {
+    static _CONSTEXPR20_MEMOP _Elem* copy(_Out_writes_all_(_Count) _Elem* const _First1,
+        _In_reads_(_Count) const _Elem* const _First2, const size_t _Count) noexcept /* strengthened */ {
```
Comment (StephanTLavavej) [inline stl/inc/xstring:60]: Note to self: I will investigate avoiding `_CONSTEXPR20_MEMOP` (and fixing the remaining skipped tests?) by using `is_constant_evaluated` as a fallback.

File: tests/libcxx/expected_results.txt [hunk 44]
```diff
@@ -482,26 +483,15 @@ std/language.support/support.limits/support.limits.general/iterator.version.pass
...
-std/strings/char.traits/char.traits.specializations/char.traits.specializations.char8_t/copy.pass.cpp FAIL
-std/strings/char.traits/char.traits.specializations/char.traits.specializations.char8_t/move.pass.cpp FAIL
-std/strings/char.traits/char.traits.specializations/char.traits.specializations.wchar.t/assign3.pass.cpp FAIL
-std/strings/char.traits/char.traits.specializations/char.traits.specializations.wchar.t/copy.pass.cpp FAIL
+std/strings/char.traits/char.traits.specializations/char.traits.specializations.char32_t/copy.pass.cpp:0 FAIL
+std/strings/char.traits/char.traits.specializations/char.traits.specializations.char32_t/move.pass.cpp:0 FAIL
+std/strings/char.traits/char.traits.specializations/char.traits.specializations.char8_t/copy.pass.cpp:0 FAIL
+std/strings/char.traits/char.traits.specializations/char.traits.specializations.char8_t/move.pass.cpp:0 FAIL
+std/strings/char.traits/char.traits.specializations/char.traits.specializations.wchar.t/copy.pass.cpp:0 FAIL
 std/strings/char.traits/char.traits.specializations/char.traits.specializations.wchar.t/move.pass.cpp FAIL
```
[the remark this answers is not in the document]
Comment (miscco) [reply tests/libcxx/expected_results.txt:495]: They fail because one compiler supports constexpr and the other not as far as I understand it.

At least that was what I read from the error message

File: stl/inc/xstring (hunk 43 above)
Comment (miscco) [reply stl/inc/xstring:60]: Originally we did that. However, the problem is that to not crash users with overlapping ranges we would need to compare two iterators that might be from different arrays. 

Maybe comparing the unwrapped iterators would be the better choice.

Also to note. The comparison is only necessary to support technically UB usage of copy as overlapping ranges are explicitely forbidden

**Comment by miscco** [comment]
@StephanTLavavej I am confused sligthly do you want to have a look at it or should I. I would not want to waste your time medling with it

File: stl/inc/xstring (hunk 43 above)
Comment (StephanTLavavej) [reply stl/inc/xstring:60]: Thanks, I see the discussion now (still getting used to keeping up with GitHub's unstructured comments outside of code review lines).

I'm going to try a hilariously simple hack - we should be able to compare pointers for *equality* even if we can't compare for *less-than*, so when `is_constant_evaluated`, just blast through one of the ranges in linear time and check for overlap at every location! (Linear time is constant time, thanks `constexpr`.) If that doesn't work, I will be :crying_cat_face:

File: tests/libcxx/expected_results.txt (hunk 44 above)
[the remark this answers is not in the document]
Comment (StephanTLavavej) [reply tests/libcxx/expected_results.txt:495]: Yeah, the `:0` are MSVC (while `:1` is Clang, due the order in which we list their configurations). Definitely caused by the builtins.

**Comment by StephanTLavavej** [comment]
Apologies for the confusion - I am continuing to review/edit, since you mentioned you're fairly busy at the moment, I think this is very close to being merged (thank you! :smiley_cat:), and this is currently my top priority as it'll be needed for @mnatsuhara's work. I just submitted a review since it's a good way to make my current understanding and action items visible, and I didn't want to forget anything overnight.

**Comment by miscco** [comment]
Ok so I will leave this one in your capable hands and have a look at the equal memcmp stuff

File: stl/inc/xstring (hunk 43 above)
Comment (miscco) [reply stl/inc/xstring:60]: That would even be efficient because you can essentially do it while copying.

Ship it!

File: stl/inc/xstring (hunk 41 above)
Comment (mnatsuhara) [reply stl/inc/xstring:3826]: @StephanTLavavej Can I get some clarification as to why a potentially user-provided `constexpr` traits class requires `_CONSTEXPR20` instead of `_CONSTEXPR20_MEMOP`?  (I imagine this will also apply to `_CONSTEXPR20_DYNAMIC_ALLOC` in [P0980R1](https://wg21.link/P0980R1)).

Comment (StephanTLavavej) [reply stl/inc/xstring:3826]: @mnatsuhara Sure! `_CONSTEXPR20` says "`constexpr` in C++20 (and later), `inline` in C++17 (and earlier)". `_CONSTEXPR20_MEMOP` is a refinement, saying "C++20 says this should be `constexpr`, but we specifically need support for `constexpr` compiler builtins that only Clang provides at the moment". So currently in this PR, the `char_traits` functions that are directly calling compiler builtins for Clang, and otherwise calling C functions, need to be marked `_CONSTEXPR20_MEMOP` to reflect this implementation limitation.

However, this doesn't apply transitively to `basic_string_view::copy`. C++20 marks `basic_string_view::copy` as `constexpr`, and it calls `_Traits::copy` to do work. Our `char_traits::copy` is marked `_CONSTEXPR20_MEMOP` because of the use of builtins - but the `basic_string_view` could have been given a user-defined character traits class, and the user might have implemented a `constexpr` `copy` with the plain Core Language. In that case, marking `basic_string_view::copy` as `_CONSTEXPR20_MEMOP` would be unnecessarily limiting - it would be non-`constexpr` for MSVC in C++20 mode, even though the user provided a `constexpr`-capable traits class and there is no use of the compiler builtin (or C `memcpy`). So `basic_string_view::copy` should be marked as `_CONSTEXPR20`, which will then make it `constexpr` in C++20 mode **if** the traits class has `constexpr` `copy` (e.g. `char_traits` for Clang, or user-defined traits that implemented `constexpr`).

> (I imagine this will also apply to _CONSTEXPR20_DYNAMIC_ALLOC in P0980R1).

I believe you're correct - the same "customization" logic applies, with allocators instead of traits. Even if an implementation doesn't support `constexpr` `new` and `delete`, as long as our `allocator_traits` machinery is `_CONSTEXPR20`, a user should be able to implement a `constexpr`-compatible pool allocator (although maybe not due to the lack of `reinterpret_cast`?).

In general, I see little potential harm from applying `_CONSTEXPR20_MEOW` in a targeted, non-transitive manner (i.e. only in the places that directly need additional compiler support). If customization through a template parameter (allocator/traits/etc.) is possible, then either it actually matters for users (like `copy`) so `_CONSTEXPR20` is correct, or it turns out not to be possible to customize in a `constexpr` fashion without compiler support, but the compiler will never realize that so it won't emit "no `constexpr` ever possible, this is ill-formed no-diagnostic-required and I can emit a diagnostic here". The only scenario I can envision seeing a compiler complain about is where we mark an internal function as `_CONSTEXPR20_MEOW`, we mark an outer/public layer as `_CONSTEXPR20`, there are no sources of customization along the way, and the compiler notices that we have an always-`constexpr` (in C++20) function calling an always-non-`constexpr` function (without `MEOW` support), and it emits the not-actually-required diagnostic - in which case we can just go fix it up.

File: stl/inc/xstring (hunk 43 above)
Comment (StephanTLavavej) [reply stl/inc/xstring:60]: I discovered that LWG-3085 "`char_traits::copy` precondition too weak" was filed in March 2018. The precondition as written in the WP (permitting overlap in the opposite direction as `std::copy`) makes no sense; I believe that the intention was always to forbid any overlap and to permit directly calling `memcpy`. I prefer the Proposed Resolution and have told the LWG so.

So, I am going to try the following:
* call the builtin when available,
* otherwise use `is_constant_evaluated` to call `memcpy/memmove` at runtime,
* otherwise at compiletime, *don't* check for overlap in `copy`, do check for any overlap in `move`.

File: stl/inc/xstring (hunk 41 above)
Comment (StephanTLavavej) [reply stl/inc/xstring:3826]: Resolving as I'm reverting the `basic_string` change tracked here - but if I can further clarify the `constexpr` situation, please let me know.

File: tests/libcxx/expected_results.txt (hunk 44 above)
[the remark this answers is not in the document]
Comment (StephanTLavavej) [reply tests/libcxx/expected_results.txt:495]: Ok, I completely understand what was happening here - the `char16_t` and `wchar_t` `move` tests were failing for **both** MSVC (lacking the builtin) and Clang (because `reinterpret_cast` was being used, which is forbidden for `constexpr`). I should be able to fix all failures now.

File: stl/inc/xstring (hunk 43 above)
Comment (StephanTLavavej) [reply stl/inc/xstring:60]: Testing this now. Note that we only have to check for overlap in one direction (the direction forbidden by `std::copy`), but we have to perform the check as a separate initial pass - we can't start copying and then discover overlap, because it'll be too late to salvage the wreckage.

**Comment by StephanTLavavej** [comment]
I believe the product code is done - just need to review the test and extend it for overlapping ranges.

**Comment by miscco** [comment]
That isa simple and elegant solution to the mess I did with those char_traits. Thanks a lot 👍

**Comment by StephanTLavavej** [comment]
Summary of test changes:

* Unwrap comment.
* Rename `first` and `second` tuples to avoid not-really-shadowing `meow.first` and `meow.second`.
* In general, attempt to use unique values for test data, so corresponding values are easier to see.
* Add `assert`s to verify that operations work correctly, in addition to compiling.
* Style: Use `{}` to initialize `pair` even though it performs value-initialization.
* Style: Use `copyAssignment` as the assignment source for `copyAssignmentConvertible`.
* Change comment to `test pair swap` because both member and non-member `swap` are being tested. Ditto `test array swap`.
* Don't test internal `_Alloc_exact_args_t` machinery.
* Test more empty `tuple<>` operations: allocator move-construction, copy assignment, and move assignment.
* Test more `tuple` operations:
  + The `const Types&...` constructor is rarely used, but it's mainly used for things that don't perfectly forward, like braces and `0` as a null pointer constant. Added `tuple_alloc_non_forwarding_value` to test this.
  + We need to `move(conversionInput)` and `move(conversionInputPair)`, otherwise they'll be copied. (Note: it's okay to "reuse" moved-from objects here, since they're ultimately storing `int` and `double` etc. where moves don't actually modify them.)
  + Assignments.
* Test empty `array::fill`.
* The insert iterator tests are usually using non-`const` rvalues like `42`, so we actually need an lvalue (or here, a `const` lvalue) to test the copy overload. So, change `move(toBeMoved)` to `toBeCopied`.
* Add comprehensive tests for `char_traits` `move`/`copy`/`assign` and `basic_string_view::copy`. This covers the 5 character types: `char`, `char16_t`, `char32_t`, `wchar_t`, and `char8_t`. I chose to replicate the code instead of macroizing the literals.

**Comment by miscco** [comment]
Stephan: This is good, just some final touches.

Also Stephan: Add a zillion lines of test, fixes bad style, cleanes up everything.

You are amazing. 

And terryfing

But mostly amazing

**Comment by StephanTLavavej** [comment]
One more change - I requested compiler support from MSVC (DevCom-1046483) and EDG (Microsoft-internal VSO-1129974), so I added a centralized macro that we'll be able to update in the future, with a `TRANSITION` comment citing the bug numbers.

File: stl/inc/xstring [hunk 45]
```diff
@@ -82,17 +105,60 @@ struct _Char_traits { // properties of a string or stream element
...
-    static _Elem* assign(_Out_writes_all_(_Count) _Elem* const _First, size_t _Count, const _Elem _Ch) noexcept
+    static _CONSTEXPR20 _Elem* assign(
+        _Out_writes_all_(_Count) _Elem* const _First, size_t _Count, const _Elem _Ch) noexcept
     /* strengthened */ {
         // assign _Count * _Ch to [_First, ...)
-        _Elem* _Next = _First;
-        for (; 0 < _Count; --_Count, ++_Next) {
+        for (_Elem* _Next = _First; _Count > 0; --_Count, ++_Next) {
             *_Next = _Ch;
         }
```
Comment (mnatsuhara) [inline stl/inc/xstring:163]: Since this pattern is pre-existing in for this function, I'm sure there is a reason, but it isn't obvious to me.  Why does this function not follow the previous functions' patterns of calling the `_CSTD mem*` functions if not evaluated in `constexpr` context?  Is it a subtlety of the definitions or edge cases of the functions?

File: stl/inc/xstring [hunk 46]
```diff
@@ -191,23 +272,45 @@ struct _WChar_traits { // char_traits for the char16_t-likes: char16_t, wchar_t,
...
     /* strengthened */ {
         // assign _Count * _Ch to [_First, ...)
+#ifdef __cpp_lib_is_constant_evaluated
+        if (_STD is_constant_evaluated()) {
+            for (_Elem* _Next = _First; _Count > 0; --_Count, ++_Next) {
+                *_Next = _Ch;
+            }
+
+            return _First;
+        }
```
Comment (mnatsuhara) [inline stl/inc/xstring:311]: This looks like the same code contained in `_Char_traits::assign` function.  Can we substitute with `_Primary_char_traits::assign(_First, _Count, _Ch)`, similar to what is done in the `copy` and `move` functions?

Comment (StephanTLavavej) [reply stl/inc/xstring:311]: Yep - during constant evaluation, there's no reason to avoid calling helper functions. (At runtime, there's the minor concern of debug codegen.) I'll make this change, thanks!

File: stl/inc/xstring (hunk 45 above)
Comment (CaseyCarter) [reply stl/inc/xstring:163]: Good catch! I stopped here and started typing this comment. The reasoning is that `memset` only works for byte-sized characters, and this `_Char_traits` class template supports char-like types with size greater than one. `_Narrow_char_traits` is used for char-like types of size 1 - notably `char` and `char8_t` - and its `assign` does call `memset` on line 511.

Comment (StephanTLavavej) [reply stl/inc/xstring:163]: The subtlety is that `assign()` for arbitrary `_Elem` has to repeatedly copy that element - which could be 4-byte `char32_t`, or (after centralizing the code as you identified in your other comment) 2-byte `char16_t`, or 1-byte `char`, etc. There's no 4-byte counterpart to `wmemset()` and `memset()`. `copy()` and `move()` differ because the width of the character doesn't matter when copying/moving byte sequences around, we just need `_Count * sizeof(_Elem)` to handle that variation.

Do you think this is worth commenting?

Comment (mnatsuhara) [reply stl/inc/xstring:163]: To me it is worth commenting, since the other functions follow such a clear pattern and this one notably differs.  If you're making the other change anyway, it seems worth it to me to also throw a comment in there.

Comment (StephanTLavavej) [reply stl/inc/xstring:163]: After thinking about this, I think the things that make this more mysterious are (1) the verbose workarounds needed until we get `__builtin_memcpy`/`__builtin_memmove` support in all compilers, and (2) the fact that `copy` and `move` appear with `find` in the middle (!) and `assign` afterwards. If the intrinsic/workaround `copy/move` appeared together, then all of the "plain loop" functions, the change in patterns would be less weird. So I think this calls for both a reordering *and* a comment.

Comment (StephanTLavavej) [reply stl/inc/xstring:168]: Ok, I've added:

```
    // For copy/move, we can uniformly call memcpy/memmove (or their builtin versions) for all element types.
```

followed by:

```
    // For compare/length/find/assign, we can't uniformly call CRT functions (or their builtin versions).
    // 8-bit: memcmp/strlen/memchr/memset; 16-bit: wmemcmp/wcslen/wmemchr/wmemset; 32-bit: nonexistent
```

File: stl/inc/xstring [hunk 47]
```diff
@@ -34,6 +40,90 @@ struct _Char_traits { // properties of a string or stream element
...
+#endif // __cpp_lib_is_constant_evaluated
+
+        _CSTD memcpy(_First1, _First2, _Count * sizeof(_Elem));
+#endif // ^^^ !_HAS_MEMCPY_MEMMOVE_INTRINSICS ^^^
+
+        return _First1;
+    }
+
+    _Pre_satisfies_(_Dest_size >= _Count) static _Elem* _Copy_s(_Out_writes_all_(_Dest_size) _Elem* const _First1,
```
Comment (CaseyCarter) [inline stl/inc/xstring:68]: `_CONSTEXPR20`? It seems peculiar that `_Copy_s` isn't `constexpr` when `copy` is.

File: stl/inc/xstring [hunk 48]
```diff
@@ -278,13 +343,22 @@ struct char_traits<unsigned short> : _WChar_traits<unsigned short> {};
...
     using off_type   = streamoff;
     using state_type = mbstate_t;
 
+    using _Primary_char_traits::_Copy_s;
+    using _Primary_char_traits::copy;
+    using _Primary_char_traits::move;
+
     _NODISCARD static _CONSTEXPR17 int compare(_In_reads_(_Count) const _Elem* const _First1,
         _In_reads_(_Count) const _Elem* const _First2, const size_t _Count) noexcept /* strengthened */ {
         // compare [_First1, _First1 + _Count) with [_First2, ...)
```
Comment (CaseyCarter) [inline stl/inc/xstring:364]: Why isn't the body of this function simply `return __builtin_memcmp(_First1, _First2, _Count);`? I remember deciding that we should use `__builtin_u8memcmp` because we could, not because it actually made any difference. I also think I recall that we were reticent to simply use `__builtin_memcp` all the time out of fear of regressing default mode with bugs in the shiny new C++17 intrinsic. But looking at this mess today, `return __builtin_memcmp(_First1, _First2, _Count);` is really attractive.

File: stl/inc/xstring [hunk 49]
```diff
@@ -310,7 +384,7 @@ struct _Narrow_char_traits { // Implement char_traits for narrow character types
 #if _HAS_U8_INTRINSICS
```
Comment (CaseyCarter) [inline stl/inc/xstring:384]: Ditto "this entire function body could as well be `return __builtin_strlen(_First);`

File: stl/inc/xstring (hunk 48 above)
Comment (CaseyCarter) [reply stl/inc/xstring:364]: (Feel free to file an issue asking me to investigate this and the following comment - I recognize that we've let these `char_traits` changes creep beyond the scope of the PR, and I'm asking for more.)

**Comment by StephanTLavavej** [comment]
Thanks for building one more stage of the C++20 rocket! :rocket: :smile_cat:

File: stl/inc/xstring (hunk 47 above)
Comment (StephanTLavavej) [reply stl/inc/xstring:68]: Will submit a followup PR.

File: stl/inc/xstring (hunk 48 above)
Comment (StephanTLavavej) [reply stl/inc/xstring:364]: Will submit a followup PR.

File: stl/inc/xstring (hunk 49 above)
Comment (StephanTLavavej) [reply stl/inc/xstring:384]: This one appears to be justified. While `memcmp` takes `const void *`, `strlen` takes `const char *`.
