### PR TITLE
LWG-3554 Add `const charT*` overloads for `chrono::parse`

### LINKED ISSUE #1928: <chrono>: Missing parse overloads
**Describe the bug**

A new LWG issue was just filed because of a defect in the C++20 chrono `parse` overloads.

https://cplusplus.github.io/LWG/issue3554

As I write this, the issue hasn't been looked at by the LWG.  I am hopeful for a quick P0 resolution.  The recommended wording in the issue has been implemented at https://github.com/HowardHinnant.

**Command-line test case**

This should work:

```
in >> parse("%F %T", tp);
```

where `tp` is `system_clock::time_point` and `in` is any `istream`.  Right now it doesn't work because `parse` is lacking an overload to take the format string literal.

### PR DESCRIPTION
**Pull request by cpplearner**
Implements LWG-3554 "`chrono::parse` needs `const charT*` and `basic_string_view<charT>` overloads" (despite the title, LWG-3554 does not add `basic_string_view` overloads).

Fixes #1928

### CODE REVIEW

File: stl/inc/chrono [hunk 1]
```diff
@@ -5138,53 +5138,76 @@ namespace chrono {
...
     template <class _CharT, class _Traits, class _Alloc, class _Parsable>
     struct _Time_parse_iomanip {
-        _Time_parse_iomanip(const basic_string<_CharT, _Traits, _Alloc>& _Fmt_, _Parsable& _Tp_,
+        _Time_parse_iomanip(const _CharT* _Fmt_, _Parsable& _Tp_,
             basic_string<_CharT, _Traits, _Alloc>* _Abbrev_ = nullptr, minutes* _Offset_ = nullptr)
             : _Fmt{_Fmt_}, _Tp{_Tp_}, _Abbrev{_Abbrev_}, _Offset{_Offset_} {}
+        _Time_parse_iomanip(_Time_parse_iomanip&&) = delete;
 
-        const basic_string<_CharT, _Traits, _Alloc>& _Fmt;
+        const _CharT* _Fmt;
```
Comment (cpplearner) [inline stl/inc/chrono:5146]: This changes the member type of `_Time_parse_iomanip`. If this is considered to break ABI, a new class template can be used for the `const charT*` cases.

Comment (CaseyCarter) [reply stl/inc/chrono:5146]: Yes, it looks like this is going to trigger ODR violations when linking old and new code.

File: tests/std/tests/P0355R7_calendars_and_time_zones_io/test.cpp [hunk 2]
```diff
@@ -147,15 +147,15 @@ void test_parse(const CharT* str, const CharT* fmt, Parsable& p, type_identity_t
     basic_stringstream<CharT> sstr{str};
     if (abbrev) {
         if (offset) {
-            sstr >> parse(basic_string<CharT>{fmt}, p, *abbrev, *offset);
+            sstr >> parse(fmt, p, *abbrev, *offset);
```
Comment (MattStephanson) [inline tests/std/tests/P0355R7_calendars_and_time_zones_io/test.cpp:150]: These changes leave only three fairly narrow tests that call `parse` with a `basic_string`. There's already a test, `parse_wchar` that's intended to provide basic testing of different character types. It may be worthwhile to try to generalize it to work with all combinations of narrow/wide and raw/`basic_string` format strings. The `WIDEN` macro at the beginning of this file might be a good starting point, but then you'd have to figure out how to either keep that as a raw string or convert it to a `basic_string`.

File: stl/inc/chrono [hunk 3]
```diff
@@ -5136,54 +5136,95 @@ namespace chrono {
         return _Istr;
     }
 
+    template <class _CharT, class _Traits, class _Alloc, class _Parsable>
+    struct _Time_parse_iomanip_c_str {
+        _Time_parse_iomanip_c_str(const _CharT* _Fmt_, _Parsable& _Tp_,
+            basic_string<_CharT, _Traits, _Alloc>* _Abbrev_ = nullptr, minutes* _Offset_ = nullptr)
+            : _Fmt{_Fmt_}, _Tp{_Tp_}, _Abbrev{_Abbrev_}, _Offset{_Offset_} {}
+        _Time_parse_iomanip_c_str(_Time_parse_iomanip_c_str&&) = delete;
```
Comment (MattStephanson) [inline stl/inc/chrono:5144]: I don't know how others feel, but I'd prefer a space here. Same for `_Time_parse_iomanip` below.
```suggestion
            : _Fmt{_Fmt_}, _Tp{_Tp_}, _Abbrev{_Abbrev_}, _Offset{_Offset_} {}
            
        _Time_parse_iomanip_c_str(_Time_parse_iomanip_c_str&&) = delete;
```

File: stl/inc/chrono [hunk 4]
```diff
@@ -5136,54 +5136,95 @@ namespace chrono {
...
+
+        const _CharT* _Fmt;
+        _Parsable& _Tp;
+        basic_string<_CharT, _Traits, _Alloc>* _Abbrev;
+        minutes* _Offset;
+    };
+
     template <class _CharT, class _Traits, class _Alloc, class _Parsable>
     struct _Time_parse_iomanip {
```
Comment (MattStephanson) [inline stl/inc/chrono:5153]: Maybe a `// TRANSITION, ABI` comment to the effect that this can be replaced with `_Time_parse_iomanip_c_str` in the future?

Comment (cpplearner) [reply stl/inc/chrono:5153]: The small code duplication is not bad enough to worry me, personally. Storing a reference to `basic_string` also has a tiny benefit, that is the format string is not invalidated if the `basic_string` is resized after the call to `parse`.

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
Thanks for implementing this LWG issue resolution in a *timely* manner! :joy_cat: :watch: :tada:
