### PR TITLE
Remove obsolete conditional compilation from <compare>

### LINKED ISSUE #1050: <compare>: 0 <=> partial_ordering::unordered returns invalid value
**Command-line test case**

```
C:\Users\He\source\test>type partial_unordered.cpp
#include <compare>

static_assert(0 <=> std::partial_ordering::unordered == std::partial_ordering::unordered);

C:\Users\He\source\test>cl /EHsc /std:c++latest /W4 /WX /c partial_unordered.cpp
用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.27.29016 版
版权所有(C) Microsoft Corporation。保留所有权利。

/std:c++latest 作为最新的 C++
working 草稿中的语言功能预览提供。我们希望你提供有关 bug 和改进建议的反馈。
但是，请注意，这些功能按原样提供，没有支持，并且会随着工作草稿的变化
而更改或移除。有关详细信息，请参阅
https://go.microsoft.com/fwlink/?linkid=2045807。

partial_unordered.cpp
partial_unordered.cpp(3): error C2607: 静态断言失败
```

The error message means "static assertion failed".

**STL version**
```
https://github.com/microsoft/STL/commit/8fcc25fe97bee8fa64232aed5848df0d7c0b6d42
```

### PR DESCRIPTION
**Pull request by CaseyCarter**
Now that EDG has caught up to `__cpp_impl_three_way_comparison == 201907`, we no longer need "downlevel" compatibility for C++20 compilers that either don't define the feature-test macro or define it to a lesser value. We can now assume that `_HAS_CXX20` implies `__cpp_impl_three_way_comparison >= 201907`.

Also fixes #1050.

### CODE REVIEW

File: stl/inc/compare [hunk 1]
```diff
@@ -32,7 +32,7 @@ using _Compare_t    = signed char;
 // These "pretty" enumerator names are safe since they reuse names of user-facing entities.
 enum class _Compare_eq : _Compare_t { equal = 0, equivalent = equal };
 enum class _Compare_ord : _Compare_t { less = -1, greater = 1 };
-enum class _Compare_ncmp : _Compare_t { unordered = -127 };
+enum class _Compare_ncmp : _Compare_t { unordered = -128 };
```
Comment (CaseyCarter) [inline stl/inc/compare:35]: **NOTE WELL**: I'm changing the representation of `partial_ordering::unordered` here which breaks `/std:c++latest` ABI.

File: tests/std/tests/P0768R1_spaceship_operator/test.cpp [hunk 2]
```diff
@@ -187,7 +179,101 @@ void test_algorithm() {
...
+
+static_assert(!(std::partial_ordering::greater == 0));
+static_assert(std::partial_ordering::greater != 0);
+static_assert(!(std::partial_ordering::greater < 0));
+static_assert(std::partial_ordering::greater > 0);
+static_assert(!(std::partial_ordering::greater <= 0));
+static_assert(std::partial_ordering::greater >= 0);
+
+static_assert(!(std::partial_ordering::unordered == 0));
+static_assert(std::partial_ordering::unordered != 0);
```
Comment (CaseyCarter) [inline tests/std/tests/P0768R1_spaceship_operator/test.cpp:207]: This seems like it may be a mistake that WG21 introduced in P1185. I will investigate.

**Comment by StephanTLavavej** [comment]
Since this is a bugfix and enhancement for currently shipping code, do you want to merge it into the `feature/spaceship` branch (where we're accumulating P1614R2 work), or should it merge directly into `master`? I would expect the latter.

**Comment by CaseyCarter** [comment]
> Since this is a bugfix and enhancement for currently shipping code, do you want to merge it into the `feature/spaceship` branch (where we're accumulating P1614R2 work), or should it merge directly into `master`? I would expect the latter.

When I created the PR it was just a cleanup to `<compare>`, and `feature/spaceship` made sense. After tacking on the bugfix, I agree I should have retargeted this at `master`.

File: tests/std/tests/P0768R1_spaceship_operator/test.cpp (hunk 2 above)
Comment (CaseyCarter) [reply tests/std/tests/P0768R1_spaceship_operator/test.cpp:207]: > This seems like it may be a mistake that WG21 introduced in P1185. I will investigate.

It was P1614R2, not P1185R2, which removed the `!=` operators for the comparison category types. This was the behavior before that change as well. 🤷

File: stl/inc/compare [hunk 3]
```diff
@@ -78,38 +64,36 @@ public:
     }
 
     _NODISCARD friend constexpr bool operator<=(const partial_ordering _Val, _Literal_zero) noexcept {
-        return _Val._Value <= 0 && _Val._Is_ordered();
+        return static_cast<signed char>(static_cast<unsigned char>(_Val._Value) - 1) < 0;
```
Comment (StephanTLavavej) [inline stl/inc/compare:67]: This branchless logic is exceedingly clever - thank you!

File: stl/inc/compare [hunk 4]
```diff
@@ -78,38 +64,36 @@ public:
...
     }
 
-#ifdef __cpp_impl_three_way_comparison
     _NODISCARD friend constexpr partial_ordering operator<=>(const partial_ordering _Val, _Literal_zero) noexcept {
         return _Val;
     }
 
     _NODISCARD friend constexpr partial_ordering operator<=>(_Literal_zero, const partial_ordering _Val) noexcept {
-        return partial_ordering{static_cast<_Compare_ord>(-_Val._Value)};
+        return partial_ordering{static_cast<_Compare_ord>(0 - static_cast<unsigned>(_Val._Value))};
```
Comment (StephanTLavavej) [inline stl/inc/compare:95]:
```suggestion
        return partial_ordering{static_cast<_Compare_ord>(0 - static_cast<unsigned int>(_Val._Value))};
```

Comment (StephanTLavavej) [inline stl/inc/compare:95]: This is also very clever (I had to work out what it does to all of the input values to see how it exchanges `less` and `greater` while leaving `equivalent` and `unordered` unchanged). :smile_cat:

File: tests/std/tests/P0768R1_spaceship_operator/test.cpp (hunk 2 above)
Comment (StephanTLavavej) [reply tests/std/tests/P0768R1_spaceship_operator/test.cpp:207]: Doesn't this imitate the behavior of floating-point NANs, where they compare non-equal to everything else?

File: tests/std/tests/P0768R1_spaceship_operator/test.cpp [hunk 5]
```diff
@@ -187,7 +179,101 @@ void test_algorithm() {
...
-#endif // defined(__cpp_impl_three_way_comparison) && defined(__cpp_lib_concepts)
+#endif // __cpp_lib_concepts
+
+// Guard against regression of GH-1050: 0 <=> partial_ordering::unordered returns invalid value
+static_assert(!(std::partial_ordering::less == 0));
+static_assert(std::partial_ordering::less != 0);
+static_assert(std::partial_ordering::less < 0);
+static_assert(!(std::partial_ordering::less > 0));
+static_assert(std::partial_ordering::less <= 0);
+static_assert(!(std::partial_ordering::less >= 0));
```
Comment (StephanTLavavej) [inline tests/std/tests/P0768R1_spaceship_operator/test.cpp:190]: We should also have tests for literal `0` on the left-hand side, given that this selects different overloads and doesn't go through centralized logic. Currently, only `0 <=> MEOW` is tested.

File: stl/inc/compare (hunk 4 above)
Comment (CaseyCarter) [reply stl/inc/compare:95]: Yes, it took me a minute or two to figure out how to negate `CHAR_MIN` into `CHAR_MIN` without undefined behavior.

File: tests/std/tests/P0768R1_spaceship_operator/test.cpp (hunk 5 above)
Comment (CaseyCarter) [reply tests/std/tests/P0768R1_spaceship_operator/test.cpp:190]: I think I'd prefer to make the symmetry manifest by having the `(_Literal_zero, meow)` overloads delegate to the `(meow, _Literal_zero)` overloads.

Comment (CaseyCarter) [reply tests/std/tests/P0768R1_spaceship_operator/test.cpp:190]: > > Currently, only 0 <=> MEOW is tested.
>
> I think I'd prefer to make the symmetry manifest by having the `(_Literal_zero, meow)` overloads delegate to the `(meow, _Literal_zero)` overloads.

That's great, Casey, but it doesn't address the actual comment. Go ahead and be explicit about delegation of the `_Literal_zero` overloads as you like, and then add `meow <=> 0` tests.

Comment (CaseyCarter) [reply tests/std/tests/P0768R1_spaceship_operator/test.cpp:190]: > That's great, Casey, but it doesn't address the actual comment. Go ahead and be explicit about delegation of the `_Literal_zero` overloads as you like, and then add `meow <=> 0` tests.

That does seem to be what the comment is asking for, but given that there are already both `meow <=> 0` and `0 <=> meow` tests, I think my first interpretation - that the comment was asking for e.g. `0 < meow` tests - was the correct one.

File: tests/std/tests/P0768R1_spaceship_operator/test.cpp (hunk 2 above)
Comment (CaseyCarter) [reply tests/std/tests/P0768R1_spaceship_operator/test.cpp:207]: This `static_assert` has held all the way back to P0515R3. It doesn't match my intuition, either.

File: tests/std/tests/P0768R1_spaceship_operator/test.cpp (hunk 5 above)
Comment (StephanTLavavej) [reply tests/std/tests/P0768R1_spaceship_operator/test.cpp:190]: Yes, I was asking for `0 < MEOW` (and `0 > MEOW` etc.) tests.

**Comment by StephanTLavavej** [comment]
(Re-adding the Spaceship project as this is relevant, although it's targeted at `master`)

File: tests/std/tests/P0768R1_spaceship_operator/test.cpp (hunk 5 above)
Comment (CaseyCarter) [reply tests/std/tests/P0768R1_spaceship_operator/test.cpp:190]: I notice this conversation isn't resolved: would you still like `0 < MEOW` tests despite that those overloads now directly delegate to the `MEOW > 0` overloads? I'm not concerned, but it's five minutes work so I don't mind, either.

Comment (StephanTLavavej) [reply tests/std/tests/P0768R1_spaceship_operator/test.cpp:190]: Yes, I would. There's a nonzero chance we're going to say "hey, there are extra function calls in debug mode" and modify this code later.

**Comment by StephanTLavavej** [comment]
Another occurrence of `##[error]We stopped hearing from agent BUILD0000CG. Verify the agent machine is running and has a healthy network connection. Anything that terminates an agent process, starves it for CPU, or blocks its network access can cause this error.` This seems to be happening more frequently? Rerunning.

File: stl/inc/compare [hunk 6]
```diff
@@ -235,21 +203,7 @@ public:
         return _Val._Value == 0;
     }
 
-#if defined(__cpp_impl_three_way_comparison) && __cpp_impl_three_way_comparison >= 201902L
     _NODISCARD friend constexpr bool operator==(const strong_ordering&, const strong_ordering&) noexcept = default;
```
Comment (statementreply) [inline stl/inc/compare:206]:
```suggestion
    _NODISCARD friend constexpr bool operator==(strong_ordering, strong_ordering) noexcept = default;
```

Has all supported compilers implemented WG21-P1946?

File: stl/inc/compare [hunk 7]
```diff
@@ -53,21 +53,7 @@ public:
         return _Val._Value == 0;
     }
 
-#if defined(__cpp_impl_three_way_comparison) && __cpp_impl_three_way_comparison >= 201902L
     _NODISCARD friend constexpr bool operator==(const partial_ordering&, const partial_ordering&) noexcept = default;
```
Comment (statementreply) [inline stl/inc/compare:56]:
```suggestion
    _NODISCARD friend constexpr bool operator==(partial_ordering, partial_ordering) noexcept = default;
```

The same

File: stl/inc/compare [hunk 8]
```diff
@@ -144,21 +128,7 @@ public:
         return _Val._Value == 0;
     }
 
-#if defined(__cpp_impl_three_way_comparison) && __cpp_impl_three_way_comparison >= 201902L
     _NODISCARD friend constexpr bool operator==(const weak_ordering&, const weak_ordering&) noexcept = default;
```
Comment (statementreply) [inline stl/inc/compare:131]:
```suggestion
    _NODISCARD friend constexpr bool operator==(weak_ordering, weak_ordering) noexcept = default;
```

The same

File: tests/std/tests/P0768R1_spaceship_operator/test.cpp [hunk 9]
```diff
@@ -15,15 +15,11 @@ constexpr bool test_ord(T val) {
     assert((0 == val) == (Z == comp::equal));
     assert((val != 0) == (Z != comp::equal));
     assert((0 != val) == (Z != comp::equal));
-#ifdef __cpp_impl_three_way_comparison
     assert(((val <=> 0) == 0) == (Z == comp::equal));
     assert(((0 <=> val) == 0) == (Z == comp::equal));
```
Comment (statementreply) [inline tests/std/tests/P0768R1_spaceship_operator/test.cpp:19]: Also test `!= 0`?

File: stl/inc/compare (hunk 6 above)
Comment (CaseyCarter) [reply stl/inc/compare:206]: They seem to have: the test passes after changing all of these, in any case.

File: tests/std/tests/P0768R1_spaceship_operator/test.cpp [hunk 10]
```diff
@@ -35,15 +31,11 @@ constexpr bool test_ord(T val) {
     assert((0 >= val) == (Z != comp::greater && Z != comp::unordered));
     assert((val >= 0) == (Z != comp::less && Z != comp::unordered));
     assert((0 <= val) == (Z != comp::less && Z != comp::unordered));
-#ifdef __cpp_impl_three_way_comparison
     assert(((val <=> 0) < 0) == (Z == comp::less));
     assert(((0 <=> val) < 0) == (Z == comp::greater));
```
[the remark this answers is not in the document]
Comment (CaseyCarter) [reply tests/std/tests/P0768R1_spaceship_operator/test.cpp:35]: All the redundancy! The `val op 0` and `0 op val` tests in this function are redundant with the `static_assert`s for the same expressions added in this PR - I'll remove the much more verbose `static_assert`s.

_These_ tests are now redundant as well: we've added exhaustive coverage for every case of `val <=> 0` and `0 <=> val`, and (as I just said above) we already have coverage for `val op 0`, these are now combinations of expressions tested elsewhere which should be struck.

File: tests/std/tests/P0768R1_spaceship_operator/test.cpp (hunk 9 above)
Comment (CaseyCarter) [reply tests/std/tests/P0768R1_spaceship_operator/test.cpp:19]: Ditto "these tests and the proposed additions are redundant combinations of expressions tested elsewhere."

File: stl/inc/compare [hunk 11]
```diff
@@ -177,30 +147,28 @@ public:
...
         return _Val;
     }
 
     _NODISCARD friend constexpr weak_ordering operator<=>(_Literal_zero, const weak_ordering _Val) noexcept {
         return weak_ordering{static_cast<_Compare_ord>(-_Val._Value)};
     }
-#endif // __cpp_impl_three_way_comparison
 
 private:
     _Compare_t _Value;
```
[the remark this answers is not in the document]
Comment (CaseyCarter) [reply stl/inc/compare:174]: I convinced myself long ago that these types would always be inlined away and wouldn't appear on "ABI boundaries", but I'm less happy with that decision today. I'm also concerned that it will very likely be too late to fix the ABI when we discover for certain that it's a problem. So yes, I think I'd like to make this change but I think it should be in a followup PR to keep this uncontroversial bugfix separate from that potentially controversial performance improvement. Is that ok?

[the remark this answers is not in the document]
Comment (CaseyCarter) [reply stl/inc/compare:170]: (Implemented at https://github.com/CaseyCarter/STL/compare/CaseyCarter:compare...CaseyCarter:compare_aggregate.)

[the remark this answers is not in the document]
Comment (statementreply) [reply stl/inc/compare:170]: I'm okay with a separate PR and keeping this cleanup + bugfix only.

File: tests/std/tests/P0768R1_spaceship_operator/test.cpp [hunk 12]
```diff
@@ -10,61 +10,86 @@
 enum class comp { equal, nonequal, less, greater, unordered };
 
 template <comp Z, class T>
-constexpr bool test_ord(T val) {
+constexpr bool test_order(T val) {
```
[the remark this answers is not in the document]
Comment (CaseyCarter) [reply tests/std/tests/P0768R1_spaceship_operator/test.cpp:13]: > Pre-existing: `val` could be `const`.

👍

> I'm also not sure why `Z` is a template parameter while `T` is a runtime parameter, although no change requested there.

Perhaps at one time it was important for `Z` to be a constant expression, or I thought I would need it to be such? I'm not certain, but I'm also not bothered by this structure.

File: stl/inc/compare [hunk 13]
```diff
@@ -78,44 +64,50 @@ public:
...
+        // The stored value is either less (0xff), equivalent (0x00), greater (0x01), or unordered (0x80).
+        // Subtracting 1 produces either 0xfe, 0xff, 0x00, or 0x7f. The high bit is set in the result
+        // if and only if the initial value was less or equivalent, for which we want to return true.
+#if defined(__clang__) || defined(__EDG__) // TRANSITION, DevCom-1117991
+        return static_cast<signed char>(static_cast<unsigned char>(_Val._Value) - 1) < 0;
+#else // ^^^ no workaround / workaround vvv
+        auto _Tmp = static_cast<unsigned char>(_Val._Value);
+        --_Tmp;
+        return static_cast<bool>(_Tmp >> 7);
+#endif // TRANSITION, DevCom-1117991
```
Comment (statementreply) [inline stl/inc/compare:76]:
```suggestion
        // The stored value is either less (0xff), equivalent (0x00), greater (0x01), or unordered (0x80).
        // Subtracting from 0 produces either 0x01, 0x00, 0xff, or 0x80. The result is greater than or equal to 0
        // if and only if the initial value was less or equivalent, for which we want to return true.
        return static_cast<signed char>(0 - static_cast<unsigned int>(_Val._Value)) >= 0;
```

It seems that this form (equivalent to `0 <=> _Val >= 0`) is [not affected](https://godbolt.org/z/njqEdT) by DevCom-1117991.

Comment (StephanTLavavej) [reply stl/inc/compare]: Thanks - in addition to being simpler and compiler-independent, the fact that we're already using this technique for `0 <=> _Val` makes it easier to reason about, and doesn't increase our exposure to compiler bugs. And thanks for validating the codegen! I've merged your suggestion and will port it to the MSVC-internal PR.

**Comment by StephanTLavavej** [comment]
Thanks @statementreply for finding this correctness issue before the C++20 ABI locked down, and for improving the fix. Thanks @CaseyCarter for the fix and cleanup, and for helping with the compiler bug investigation. 😸

File: stl/inc/compare (hunk 11 above)
[the remark this answers is not in the document]
Comment (CaseyCarter) [reply stl/inc/compare:176]: Submitted #1065.
