### PR TITLE
<system_error>: explicitly pass the system locale ID for system_category messages

### LINKED ISSUE #2451: <system_error>: FormatMessageA needs be used in a different way
**Describe the bug**

Windows settings have “user language id” and “system language id”.  They can be different.  std::system_category().message() returns "???" when they are different.

By default FormatMessage returns a string in “user language”. The Unicode version of FormatMessage works good in all cases. But the ANSI version, like all other ANSI version Windows APIs, would try to convert the result string to a multibyte string based on “system language id”. It goes wrong when the two ids are different. For example, If your user language is Chinese but the system language is English,  it can only returns “????”, because you can’t encode a Chinese string in ISO-8859-1. 

So if you need to return the error message in std::string type, there are two solutions:

1.	Pass the system language id to FormatMessageA
2.	If you use FormatMessageW, you can set the language id to the system language or thread ACP(the user language). Then when you use WideCharToMultiByte, use CP_ACP for the system language and CP_THREAD_CP for the user language.

**Command-line test case**
```c++

int main() {
    setlocale(LC_ALL, "");
	LANGID user_language_id = GetUserDefaultLangID();
	WCHAR buf[1024];
	int ret = GetUserDefaultLocaleName(buf,sizeof(buf)/sizeof(buf[0]));
	assert(ret != 0);
	std::wcout << user_language_id << L" " << buf << "\n";
	ret = GetSystemDefaultLocaleName(buf, sizeof(buf) / sizeof(buf[0]));
	assert(ret != 0);
	LANGID system_language_id = GetSystemDefaultLangID();
	std::wcout << system_language_id << L" " << buf << std::endl;
    
    wil::unique_hfile file_handle(CreateFile(L"D:\\non_exist_file.txt", GENERIC_READ, FILE_SHARE_READ, NULL, OPEN_EXISTING, FILE_ATTRIBUTE_NORMAL, NULL));
    if (file_handle.get() == INVALID_HANDLE_VALUE) {
        const auto error_code = GetLastError();
        std::string errmsg = std::system_category().message(error_code); //Sometimes the string only contains "???"
    }
  return 0;
}
```
To compile it:
C:\Temp>cl /EHsc .\repro.cpp

To reproduce the error:
I assume you have a clean Windows installation. Then please create a new user without Administrator privilege. Then login to the user, go to settings and change the display language to something different. Like, Chinese.  In such a case, you only changed the user's locale, not the system. Because the user doesn't have the privilege to change system level settings. 

Then run the code, use your debugger to inspect the binary content of the error message. Do not print it out. Printing is a different problem.  Just look the raw bytes. 

**Expected behavior**
The error message should contain useful information. 

**STL version**
VS 2022 17.0.3

**Additional context**

### PR DESCRIPTION
**Pull request by fsb4000**
Fixes #2451 

```c++
type main.cpp
#include <clocale>
#include <iostream>
#include <string>

#include <Windows.h>

int main() {
    setlocale(LC_ALL, "");
    auto file_handle(CreateFile(
        L"D:\\non_exist_file.txt", GENERIC_READ, FILE_SHARE_READ, NULL, OPEN_EXISTING, FILE_ATTRIBUTE_NORMAL, NULL));
    if (file_handle == INVALID_HANDLE_VALUE) {
        const auto error_code = GetLastError();
        std::string errmsg    = std::system_category().message(error_code); // Sometimes the string only contains "???"
        std::cout << errmsg << '\n';
    }
}
```

If we have different “user language id” and “system language id” (this is how we can reach it: https://github.com/microsoft/STL/issues/2451#issuecomment-1107744166) FormatMessageA can choose “user language id” instead of “system language id” if we pass 0.

Before
```
>main
??????? ?? ??????? ????? ????????? ????.
```
After
```
>main
The system cannot find the path specified.
```

### CODE REVIEW

File: stl/src/syserror_import_lib.cpp [hunk 1]
```diff
@@ -47,7 +47,7 @@ _NODISCARD size_t __CLRCALL_PURE_OR_STDCALL __std_system_error_allocate_message(
     // pre: *_Ptr_str == nullptr
     const unsigned long _Chars =
         FormatMessageA(FORMAT_MESSAGE_ALLOCATE_BUFFER | FORMAT_MESSAGE_FROM_SYSTEM | FORMAT_MESSAGE_IGNORE_INSERTS,
-            nullptr, _Message_id, 0, reinterpret_cast<char*>(_Ptr_str), 0, nullptr);
+            nullptr, _Message_id, GetSystemDefaultLangID(), reinterpret_cast<char*>(_Ptr_str), 0, nullptr);
```
Comment (StephanTLavavej) [inline stl/src/syserror_import_lib.cpp:50]: This seems correct to me (after reading the analysis in the PR description and linked bug) - my only concern is that [the `GetSystemDefaultLangID()` documentation](https://docs.microsoft.com/en-us/windows/win32/api/winnls/nf-winnls-getsystemdefaultlangid) says that this is "desktop apps only", which could be a problem for apps that are built for UWP.

After clicking on the [Language Identifiers documentation](https://docs.microsoft.com/en-us/windows/win32/intl/language-identifiers), I wonder if we could use this constant?

> The following are predefined language identifiers:
> `LANG_SYSTEM_DEFAULT`. The operating system default language.

I observe that this appears to work for my plain English system but I haven't set up the cross-language scenario to test.

**Review by StephanTLavavej — CHANGES_REQUESTED** [review]

File: stl/src/syserror_import_lib.cpp (hunk 1 above)
Comment (sylveon) [reply stl/src/syserror_import_lib.cpp:50]: I believe this might work (`LANG_SYSTEM_DEFAULT` ends up expanding to 2) - but I don't have a system to test with either.

Comment (fsb4000) [reply stl/src/syserror_import_lib.cpp:50]: Unfortunally `LANG_SYSTEM_DEFAULT` doesn't work for me.
But I found another way: [GetLocaleInfoEx](https://docs.microsoft.com/en-us/windows/win32/api/winnls/nf-winnls-getlocaleinfoex) (Minimum supported client 	Windows Vista [desktop apps | UWP apps])
```c++
#include <clocale>
#include <iostream>

#include <Windows.h>

int main() {
    setlocale(LC_ALL, "");
    {
        char str[100] = {0};
        FormatMessageA(FORMAT_MESSAGE_FROM_SYSTEM | FORMAT_MESSAGE_IGNORE_INSERTS, nullptr, 3, GetSystemDefaultLangID(),
            str, 99, nullptr);
        std::cout << str;
    }
    {
        char str[100] = {0};
        FormatMessageA(FORMAT_MESSAGE_FROM_SYSTEM | FORMAT_MESSAGE_IGNORE_INSERTS, nullptr, 3, LANG_SYSTEM_DEFAULT, str,
            99, nullptr);
        std::cout << str;
    }
    {
        DWORD value;
        const int ret = GetLocaleInfoEx(LOCALE_NAME_SYSTEM_DEFAULT, LOCALE_ILANGUAGE | LOCALE_RETURN_NUMBER,
            reinterpret_cast<LPWSTR>(&value), sizeof(value) / sizeof(wchar_t));
        char str[100] = {0};
        if (ret == 0) {
            value = 0;
        }
        FormatMessageA(FORMAT_MESSAGE_FROM_SYSTEM | FORMAT_MESSAGE_IGNORE_INSERTS, nullptr, 3, value, str, 99, nullptr);
        std::cout << str;
    }
}
```
изображение

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Review by raghavthind2005 — APPROVED** [review]

**Review by CaseyCarter — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Thanks for investigating and fixing this runtime correctness bug! :detective: :lady_beetle: :heart_eyes_cat:
