### PR TITLE
`<cmath>`: add arithmetic overloads for `std::lerp`

### LINKED ISSUE #2112: <cmath>: std::lerp is missing Arithmetic overloads
**Describe the bug**
According to C++20 standard paragraph 20.8.1.2 std::lerp is not an exception to expansion of acceptable parameters to integral and mixed floating point types.
I.e. overload 4) from https://en.cppreference.com/w/cpp/numeric/lerp is missing.

**Code example**
```
#include<cmath>

int main()
{
    std::lerp(int{},int{},int{});
    std::lerp(float{}, float{}, double{});
}
```
https://godbolt.org/z/3EaKbGrW9

**Current behaviour**
```
<source>(5): error C2668: 'std::lerp': ambiguous call to overloaded function
C:/data/msvc/14.30.30423-Pre/include\cmath(1390): note: could be 'long double std::lerp(const long double,const long double,const long double) noexcept'
C:/data/msvc/14.30.30423-Pre/include\cmath(1386): note: or       'double std::lerp(const double,const double,const double) noexcept'
C:/data/msvc/14.30.30423-Pre/include\cmath(1382): note: or       'float std::lerp(const float,const float,const float) noexcept'
<source>(5): note: while trying to match the argument list '(int, int, int)'
<source>(6): error C2666: 'std::lerp': 3 overloads have similar conversions
C:/data/msvc/14.30.30423-Pre/include\cmath(1390): note: could be 'long double std::lerp(const long double,const long double,const long double) noexcept'
C:/data/msvc/14.30.30423-Pre/include\cmath(1386): note: or       'double std::lerp(const double,const double,const double) noexcept'
C:/data/msvc/14.30.30423-Pre/include\cmath(1382): note: or       'float std::lerp(const float,const float,const float) noexcept'
<source>(6): note: while trying to match the argument list '(float, float, double)'
Compiler returned: 2
```

**Expected behavior**
Compilation of the code with no issues.

### PR DESCRIPTION
**Pull request by fsb4000**
Fixes #2112 

Should I add `remove_volatile` or `remove_cv` for `if constexpr` conditions?

I think "No" but I am unsure.

### CODE REVIEW

File: stl/inc/cmath [hunk 1]
```diff
@@ -1323,6 +1324,19 @@ _NODISCARD constexpr inline long double lerp(
     const long double _ArgA, const long double _ArgB, const long double _ArgT) noexcept {
     return _Common_lerp(_ArgA, _ArgB, _ArgT);
 }
+
+template <class _Ty>
+concept _Arithmetic = is_arithmetic_v<_Ty>;
+
+template <_Arithmetic _Ty1, _Arithmetic _Ty2, _Arithmetic _Ty3>
+_NODISCARD constexpr auto lerp(const _Ty1 _ArgA, const _Ty2 _ArgB, const _Ty3 _ArgT) noexcept {
```
Comment (strega-nil-ms) [inline stl/inc/cmath:1332]: Note that there is a comment on line 1312; LWG-3223 says we may not want to implement this. @BillyONeal, do you have any comments?

Comment (strega-nil-ms) [inline stl/inc/cmath:1332]: Note that there is a comment on line 1312; LWG-3223 says we may not want to implement this. @BillyONeal, do you have any comments?

**Review by strega-nil-ms — CHANGES_REQUESTED** [review]
Not clear that this should be implemented

File: stl/inc/cmath (hunk 1 above)
Comment (BillyONeal) [reply stl/inc/cmath:1332]: This seems like an implementation over a technicality rather than something someone should ever call.

Comment (strega-nil-ms) [reply stl/inc/cmath:1332]: Given that LWG hasn't responded for 2.5 years, I think it's reasonable to implement; however, that comment on line 1312 should be deleted.

**Review by CaseyCarter — CHANGES_REQUESTED** [review]
We can remove this again if LWG-3223 gains traction, but for now we're just creating a portability landmine by diverging from libc++ and libstdc++ (https://godbolt.org/z/TrPs9zae5). I'm happy to implement this if we cleanup the comment on 1312.

File: stl/inc/cmath [hunk 2]
```diff
@@ -1323,6 +1321,19 @@ _NODISCARD constexpr inline long double lerp(
...
+concept _Arithmetic = is_arithmetic_v<_Ty>;
+
+template <_Arithmetic _Ty1, _Arithmetic _Ty2, _Arithmetic _Ty3>
+_NODISCARD constexpr auto lerp(const _Ty1 _ArgA, const _Ty2 _ArgB, const _Ty3 _ArgT) noexcept {
+    if constexpr (is_same_v<_Ty1, long double> || is_same_v<_Ty2, long double> || is_same_v<_Ty3, long double>) {
+        return _STD lerp(
+            static_cast<long double>(_ArgA), static_cast<long double>(_ArgB), static_cast<long double>(_ArgT));
+    } else {
+        return _STD lerp(static_cast<double>(_ArgA), static_cast<double>(_ArgB), static_cast<double>(_ArgT));
+    }
```
Comment (CaseyCarter) [inline stl/inc/cmath:1335]: This can be simplified to:
```c++
using _Tgt = conditional_t<_Is_any_of_v<long double, _Ty1, _Ty2, _Ty3>, long double, double>;
return _Common_lerp(static_cast<_Tgt>(_ArgA), static_cast<_Tgt>(_ArgB), static_cast<_Tgt>(_ArgT));
```
(I've tested, so I'll go ahead and push this.)

File: stl/inc/cmath [hunk 3]
```diff
@@ -23,6 +23,7 @@
 #endif // _HAS_CMATH_INTRINSICS
 
 #if _HAS_CXX20
+#include <type_traits>
```
Comment (CaseyCarter) [inline stl/inc/cmath:26]: `is_arithmetic_v` (and the `_Is_any_of_v` that I'm adding as well) is defined in `<xtr1common>` which is already included - we don't need `<type_traits>`.

**Review by CaseyCarter — APPROVED** [review]

**Comment by CaseyCarter** [comment]
> Should I add `remove_volatile` or `remove_cv` for `if constexpr` conditions?
> 
> I think "No" but I am unsure.

Not necessary. Top-level cv-qualifiers are stripped away by template argument deduction.

**Comment by fsb4000** [comment]
> Not necessary. Top-level cv-qualifiers are stripped away by template argument deduction.

Yes, but a person could do a stupid thing like an explicit template instantiation, should we care about it?

https://gcc.godbolt.org/z/o89jraYbM

https://gcc.godbolt.org/z/e7T8E8sEn

**Comment by CaseyCarter** [comment]
> Yes, but a person could do a stupid thing like an explicit template instantiation, should we care about it?
> 
> https://gcc.godbolt.org/z/o89jraYbM

The Standard doesn't necessarily even say there's a template here, let alone what the template parameters are and what they mean. This is "play stupid games, win stupid prizes"-level undefined behavior.

File: stl/inc/cmath [hunk 4]
```diff
@@ -1323,6 +1320,15 @@ _NODISCARD constexpr inline long double lerp(
     const long double _ArgA, const long double _ArgB, const long double _ArgT) noexcept {
     return _Common_lerp(_ArgA, _ArgB, _ArgT);
 }
+
+template <class _Ty>
+concept _Arithmetic = is_arithmetic_v<_Ty>;
+
+template <_Arithmetic _Ty1, _Arithmetic _Ty2, _Arithmetic _Ty3>
```
Comment (StephanTLavavej) [inline stl/inc/cmath:1327]: This is guarded by `_HAS_CXX20`, but not `__cpp_lib_concepts`. Therefore, we should use SFINAE like `hypot()` above.

File: tests/std/tests/P0811R3_midpoint_lerp/test.cpp [hunk 5]
```diff
@@ -1023,6 +1023,15 @@ bool test_lerp() {
...
 }
 
+void test_gh_2112() {
+    // GH-2112 <cmath>: std::lerp is missing Arithmetic overloads
+    assert(lerp(int{}, int{}, int{}) == 0.0);
+    STATIC_ASSERT(lerp(int{}, int{}, int{}) == 0.0);
+
+    assert(lerp(float{}, float{}, double{}) == 0.0);
+    STATIC_ASSERT(lerp(float{}, float{}, double{}) == 0.0);
+}
```
Comment (StephanTLavavej) [inline tests/std/tests/P0811R3_midpoint_lerp/test.cpp:1033]: Suggestion: Although this is small (only 2 test cases), it would be more consistent with the other test functions to make this a `constexpr bool` function that `main()` tests at both compiletime and runtime, allowing the `STATIC_ASSERT` repetition here to be dropped.

File: tests/std/tests/P0811R3_midpoint_lerp/test.cpp [hunk 6]
```diff
@@ -1023,6 +1023,15 @@ bool test_lerp() {
     return true;
 }
 
+void test_gh_2112() {
```
Comment (StephanTLavavej) [inline tests/std/tests/P0811R3_midpoint_lerp/test.cpp:1026]: I would additionally like to see a small amount of test coverage for the type computation - basically ensuring that `decltype(lerp(args))` is `double` when a mix of types without `long double` is involved, but `long double` when any `long double` appears. It doesn't need to be super exhaustive, but we should test a `long double` in every position, e.g.

`int, int, int => double`
`long double, int, int => long double`
`int, long double, int => long double`
`int, int, long double => long double`

**Review by StephanTLavavej — CHANGES_REQUESTED** [review]

**Review by CaseyCarter — APPROVED** [review]

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
:warning: Note to self:
===

I must `export` this new overload of `lerp()`.

**Review by CaseyCarter — APPROVED** [review]

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
Thanks for fixing this bug and improving `<cmath>` portability! :lady_beetle: :white_check_mark: :smile_cat:
