### PR TITLE
`<chrono>` LWG-3536: leave duration unchanged on failed parse

### LINKED ISSUE #1740: LWG-3536 Should chrono::from_stream assign zero to duration for failure?
Noticed by @MattStephanson and investigated by @mnatsuhara.

WG21-N4878 [time.duration.io]/3:
> ```cpp
> template<class charT, class traits, class Rep, class Period, class Alloc = allocator<charT>>
>   basic_istream<charT, traits>&
>     from_stream(basic_istream<charT, traits>& is, const charT* fmt,
>                 duration<Rep, Period>& d,
>                 basic_string<charT, traits, Alloc>* abbrev = nullptr,
>                 minutes* offset = nullptr);
> ```
> *Effects:* Attempts to parse the input stream `is` into the duration `d` using the format flags given in the NTCTS `fmt` as specified in [time.parse]. If the parse parses everything specified by the parsing format flags without error, and yet none of the flags impacts a duration, `d` will be assigned a zero value. If `%Z` is used and successfully parsed, that value will be assigned to `*abbrev` if `abbrev` is non-null. If `%z` (or a modified variant) is used and successfully parsed, that value will be assigned to `*offset` if `offset` is non-null.

[time.parse]/11:
> If the type being parsed cannot represent the information that the format flag refers to, `is.setstate(ios_base::failbit)` is called.
> [*Example 1:* A `duration` cannot represent a `weekday`. -- *end example*]
> However, if a flag refers to a "time of day" (e.g. `%H`, `%I`, `%p`, etc.), then a specialization of `duration` is parsed as the time of day elapsed since midnight.

[time.parse]/12:
> If the `from_stream` overload fails to parse everything specified by the format string, or if insufficient information is parsed to specify a complete duration, time point, or calendrical data structure, `setstate(ios_base::failbit)` is called on the `basic_istream`.

What happens for the `duration` overload of `from_stream()`? My interpretation of the Standardese:

Format | Stream | Result | Rationale
:---:|:---:|:---:|:---
`"%j"` | `"10"` | Success, `days{10}`
`"%j"` | `"meow"` | `failbit`, **unknown**
`"%a"` | `"Saturday"` | `failbit`, `duration::zero()` | [time.parse]/11 "cannot represent", [time.duration.io]/3 "none of the flags impacts a duration"
`"%a"` | `"Caturday"` | `failbit`, **unknown**
`"literal"` | `"literal"` | `failbit`, `duration::zero()` | [time.parse]/12 "insufficient information", [time.duration.io]/3 "none of the flags impacts a duration"
`"literal"` | `"meow"` | `failbit`, **unknown**

When the parse simply fails, should the `duration` be set to zero, or should it be unchanged? Nothing seems to address this specific case.

On one hand, it seems that there's no Standardese telling us to assign zero, so we shouldn't. On the other hand, it seems very strange for `"%a"` parsing `"Saturday"` to set `failbit` and assign zero, while `"%a"` parsing `"Caturday"` sets `failbit` and leaves the `duration` unchanged.

The other `from_stream()` overloads all clearly address this, e.g. [time.cal.wd.nonmembers]/7 "If the parse fails to decode a valid weekday, `is.setstate(ios_base::failbit)` is called and `wd` is not modified."

### PR DESCRIPTION
**Pull request by yuanhongzhao**
Fixes #1740.

### CODE REVIEW

File: tests/std/tests/P0355R7_calendars_and_time_zones_io/test.cpp [hunk 1]
```diff
@@ -262,6 +262,12 @@ void parse_seconds() {
 
     fail_parse("1.2 1.3", "%S %S", time_ms);
     fail_parse("1.2 2.2", "%S %S", time_ms);
+
+    // LWG-3536, failed parse leaves duration unmodified.
+    minutes mm{20};
+    istringstream iss{"2:2:20"};
+    iss >> parse(string{"%H:%M:%S"}, mm);
+    assert(iss.fail() && mm == 20min);
```
Comment (mnatsuhara) [inline tests/std/tests/P0355R7_calendars_and_time_zones_io/test.cpp:270]: Is there any reason we couldn't use the helper function `fail_parse` here?

File: tests/std/tests/P0355R7_calendars_and_time_zones_io/test.cpp [hunk 2]
```diff
@@ -262,6 +262,12 @@ void parse_seconds() {
 
     fail_parse("1.2 1.3", "%S %S", time_ms);
     fail_parse("1.2 2.2", "%S %S", time_ms);
+
+    // LWG-3536, failed parse leaves duration unmodified.
+    minutes mm{20};
```
Comment (mnatsuhara) [inline tests/std/tests/P0355R7_calendars_and_time_zones_io/test.cpp:267]: Just for a sanity check, I'd love a few additional test cases.  The case that you have is great for checking invalidity due to truncation (e.g., the given type would need to truncate the information parsed because it cannot store all of it) but it would also be great to have test cases for
- category mismatch (e.g., parse a month and try to store it in a duration)
- an obviously invalid input string (e.g., `""` and try to store the parse result in a duration)
  - Thanks @MattStephanson for the suggestion!

**Review by mnatsuhara — CHANGES_REQUESTED** [review]
Thanks for working on this issue!  Apologies for the delay in review, the maintainers have been steadily working through the PR backlog.  The actual product code changes look great, the only changes I'm requesting are some additional test cases!  Once you add those, I'll be satisfied 😸

File: tests/std/tests/P0355R7_calendars_and_time_zones_io/test.cpp (hunk 1 above)
Comment (MattStephanson) [reply tests/std/tests/P0355R7_calendars_and_time_zones_io/test.cpp:270]: `fail_parse` resets its argument.
https://github.com/microsoft/STL/blob/5ac862362900773fb95a8c9ab58fe49721e8cd92/tests/std/tests/P0355R7_calendars_and_time_zones_io/test.cpp#L165-L168

It's more or less a copy-paste of `test_parse`, which I wrote that way because there are a few instances of parsing the same value different ways, and I wanted to be certain that I was actually asserting on a new value, not a stale one from a previous parse.
https://github.com/microsoft/STL/blob/5ac862362900773fb95a8c9ab58fe49721e8cd92/tests/std/tests/P0355R7_calendars_and_time_zones_io/test.cpp#L243-L248

**Review by mnatsuhara — APPROVED** [review]
Thanks for pushing changes addressing my review comments!  These changes look good to me -- moving into "Final Review" mode now 😸

File: tests/std/tests/P0355R7_calendars_and_time_zones_io/test.cpp [hunk 3]
```diff
@@ -221,6 +221,29 @@ void test_limits(const char* flag, const IntType min, const IntType max) {
     assert(value == TimeType{max});
 }
 
+void test_lwg_3536() {
+    // LWG-3536, "Should chrono::from_stream() assign zero to duration for failure?"
+    minutes mm{20};
+
+    {
+        istringstream iss{"2:2:20"};
```
Comment (StephanTLavavej) [inline tests/std/tests/P0355R7_calendars_and_time_zones_io/test.cpp:229]: This test is correct, but I have a clarity nitpick. When choosing values to use in tests, I believe that choosing distinct values for distinct purposes makes it easier to understand what the test is doing. Here, `20` is the initial value of `minutes mm`, which the test expects to remain unchanged after parse failure. This input reuses the value `20` for the number of seconds being parsed, but there is no relationship between the two - it's the mere presence of non-zero seconds that causes the parse to fail. Changing this to any other non-zero value, like `30`, would (very slightly) improve clarity.

File: tests/std/tests/P0355R7_calendars_and_time_zones_io/test.cpp [hunk 4]
```diff
@@ -262,6 +285,8 @@ void parse_seconds() {
 
     fail_parse("1.2 1.3", "%S %S", time_ms);
     fail_parse("1.2 2.2", "%S %S", time_ms);
+
+    test_lwg_3536();
```
Comment (StephanTLavavej) [inline tests/std/tests/P0355R7_calendars_and_time_zones_io/test.cpp:289]: This call is being added to `parse_seconds()`, but LWG-3536 isn't specific to parsing `seconds`, and the test physically parses `minutes`.

I believe that it would be clearer to move this call into `test_parse()`, immediately above `parse_seconds();`, so that the order of the function calls matches the order of the function definitions. It also makes logical sense for `test_parse()` to begin by verifying the LWG-3536 behavior for failed parses, before testing the various types.

**Review by StephanTLavavej — COMMENTED** [review]
Thanks for implementing this LWG issue resolution! This looks good to me - I'll push changes for minor clarity improvements.

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
FYI @mnatsuhara, I pushed minor changes after you approved.

**Comment by StephanTLavavej** [comment]
I'm mirroring this to an MSVC-internal PR. Please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
Thanks for implementing this LWG issue resolution, and congratulations on your first microsoft/STL commit! :tada: :heart_eyes_cat: :rocket:

This will ship in VS 2022 17.1 Preview 1.
