### PR TITLE
`vector_algorithms.cpp`: fix incorrect activation of bitmap find-meow-of algorithms

### LINKED ISSUE #5757: `<string>`: `wstring::find_first_of` crashes on some inputs
# Describe the bug
When a specific mix of characters in 0-255 range and not in 0-255 range is passed to `wstring::find_rist_of`, it crashes.

# Command-line test case
```
**********************************************************************
** Visual Studio 2026 Developer Command Prompt v18.0.0-insiders
** Copyright (c) 2025 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'

C:\Program Files\Microsoft Visual Studio\18\Insiders>cd %temp%

C:\Users\ALEXG~1\AppData\Local\Temp>type woof.cpp
```
```c++
#include <string>
#include <iostream>

using namespace std;

int main() {
    wstring hay(200, L'z');
    wstring needle;
    needle.resize(32);

    for (int k = 0; k != 32; k += 16) {
        for (int i = 0; i != 8; ++i) {
            needle[i + k] = 'a' + i;
        }

        for (int i = 8; i != 16; ++i) {
            needle[i + k] = 0xFF00 + i;
        }
    }

    auto pos = hay.find_first_of(needle);
    cout << "Found at:" << pos;
}
```
```
C:\Users\ALEXG~1\AppData\Local\Temp>cl woof.cpp /EHsc
Microsoft (R) C/C++ Optimizing Compiler Version 19.50.35503 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

woof.cpp
Microsoft (R) Incremental Linker Version 14.50.35503.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:woof.exe
woof.obj

C:\Users\ALEXG~1\AppData\Local\Temp>woof.exe

C:\Users\ALEXG~1\AppData\Local\Temp>echo %errorlevel%
-1073741819
```

# Expected behavior
No crash, print something, %errorlevel% zero

# STL version
19.50.35503 for x64

# Additional context
Reported internally

### PR DESCRIPTION
**Pull request by AlexGuteniev**
Fix #5757

The activation function `_Can_fit_256_bits_sse` skipped past some elements, which caused incorrect activation of bitmap algorithm, which then addressed array out-of-bounds.

### CODE REVIEW

File: tests/std/tests/VSO_0000000_vector_algorithms/test.cpp [hunk 1]
```diff
@@ -1710,6 +1710,25 @@ void test_basic_string(mt19937_64& gen) {
...
+            needle[i + k] = static_cast<wchar_t>(L'a' + i);
+        }
+
+        for (unsigned int i = 8; i != 16; ++i) {
+            needle[i + k] = static_cast<wchar_t>(0xFF00 + i);
+        }
+    }
+
+    const auto pos = hay.find_first_of(needle);
+    assert(pos == 0);
```
Comment (Sir-Walrus) [inline tests/std/tests/VSO_0000000_vector_algorithms/test.cpp:1730]: shouldn't this be npos aka -1?

Comment (AlexGuteniev) [reply tests/std/tests/VSO_0000000_vector_algorithms/test.cpp:1730]: No, 'e' is in haystack, and 'e' is one of the needle element.

Comment (Sir-Walrus) [reply tests/std/tests/VSO_0000000_vector_algorithms/test.cpp:1730]: Oh right, that's find_first_of, mixed it up with find.

File: tests/std/tests/VSO_0000000_vector_algorithms/test.cpp [hunk 2]
```diff
@@ -1710,6 +1710,25 @@ void test_basic_string(mt19937_64& gen) {
     }
 }
 
+void test_gh_5757_find_first_of() {
```
Comment (StephanTLavavej) [inline tests/std/tests/VSO_0000000_vector_algorithms/test.cpp:1714]: We conventionally capture the bug title in a comment.

File: tests/std/tests/VSO_0000000_vector_algorithms/test.cpp [hunk 3]
```diff
@@ -1710,6 +1710,25 @@ void test_basic_string(mt19937_64& gen) {
     }
 }
 
+void test_gh_5757_find_first_of() {
+    const wstring hay(40, L'e');
+    wstring needle;
+    needle.resize(32);
+
+    for (unsigned int k = 0; k != 32; k += 16) {
+        for (int i = 0; i != 8; ++i) {
```
Comment (StephanTLavavej) [inline tests/std/tests/VSO_0000000_vector_algorithms/test.cpp]: It seems unnecessarily inconsistent for this `i` to be `int`, when everything else is `unsigned int`. Adding it to `L'a'` should be fine either way.

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
Thanks for investigating and fixing this regression so quickly! :hammer_and_wrench: :detective: :magic_wand:
