### PR TITLE
`<xloctime>`: Fix `time_get::do_get` to parse a literal `%`

### LINKED ISSUE #6130: `<xloctime>`: `time_get::do_get` doesn't parse a literal `%`
# Describe the bug
MSVC STL's [`time_get::do_get`](https://github.com/microsoft/STL/blob/117ca965fe2f7157540edd9df5a62b0e42d7ece2/stl/inc/xloctime#L436) doesn't know the `%%` specifier. It should recognize this specifier and consume a literal `%`.

# Command-line test case
```
D:\test>type test-time-get-do-get.cpp
```
```c++
#include <cassert>
#include <ctime>
#include <iomanip>
#include <sstream>

int main() {
    std::tm t{};
    std::stringstream ss{"% "};
    ss >> std::get_time(&t, "%%");
    assert(!ss.fail());
}
```
```
D:\test>cl /EHsc test-time-get-do-get.cpp
```
```
Microsoft (R) C/C++ Optimizing Compiler Version 19.50.35725 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

test-time-get-do-get.cpp
Microsoft (R) Incremental Linker Version 14.50.35725.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:test-time-get-do-get.exe
test-time-get-do-get.obj
```
```
D:\test>test-time-get-do-get.exe
```
```
Assertion failed: !ss.fail(), file test-time-get-do-get.cpp, line 10
```

# Expected behavior
Assertion passed.

# STL version
https://github.com/microsoft/STL/commit/117ca965fe2f7157540edd9df5a62b0e42d7ece2

# Additional context
Both #6129 and this issue concern `time_get::do_get` (and affect the same `libcxx` test file), but they can be fixed independently.

In fact, IMO this issue is much easier to fix and could be a "good first issue".

### PR DESCRIPTION
**Pull request by mirion-dev**
Fixes #6130.

### CODE REVIEW

**Comment by mirion-dev** [comment]
@microsoft-github-policy-service agree

File: tests/std/tests/GH_006130_time_get_do_get_format/test.cpp [hunk 1]
```diff
@@ -0,0 +1,14 @@
...
+#include <cassert>
+#include <ctime>
+#include <iomanip>
+#include <sstream>
+
+int main() {
+    std::tm t{};
+    std::stringstream ss{"% "};
+    ss >> std::get_time(&t, "%%");
+    assert(!ss.fail());
```
Comment (frederick-vs-ja) [inline tests/std/tests/GH_006130_time_get_do_get_format/test.cpp]: I wonder whether it would be better to also verify the result of `ss.str()` after extraction. Also, I think it's valuable to also verify that `eofbit` is set or not set as required.

**Comment by mirion-dev** [comment]
It seems like the CI pipeline is unstable. Timed out twice.

[82db724](https://dev.azure.com/vclibs/STL/_build/results?buildId=20393&view=logs&j=ea158d5b-97f7-500e-5989-7da1f56be164&t=91f86df2-32da-48a0-a98b-ea0e9da72b3d): `##[warning]Task 'ComponentGovernanceComponentDetection' didn't finish download within 1200 seconds.`

[60e5e9e](https://dev.azure.com/vclibs/STL/_build/results?buildId=20394&view=logs&jobId=1b05ade7-b24c-5ac9-c731-7705b3745dc5&j=1b05ade7-b24c-5ac9-c731-7705b3745dc5): `##[warning]Agent Stl-2026-02-20T0952-arm64-Pool 20 did not respond to a cancelation request with 00:05:00.`

File: tests/std/tests/GH_006130_time_get_do_get_format/test.cpp [hunk 2]
```diff
@@ -0,0 +1,22 @@
+// Copyright (c) Microsoft Corporation.
```
Comment (cpplearner) [inline tests/std/tests/GH_006130_time_get_do_get_format/test.cpp]: Instead of adding a new directory, can you add the test code to `tests/std/tests/Dev11_0836436_get_time/test.cpp`?

In this repo, extending an existing test (if reasonable) is preferred over adding a new test, because a new test has a higher runtime cost. This is not a strict requirement though.

**Comment by StephanTLavavej** [comment]
Our CI system is usually pretty reliable (we've put a lot of effort into fixing flaky tests etc.) but in the event of timeouts or flaky failures, you can report them to the `#stalled-checks` channel on the STL Discord and I can click rerun, as I've done so here. Thanks (and sorry for the minor headache, nobody hates flaky CIs more than I do).

**Comment by mirion-dev** [comment]
> Our CI system is usually pretty reliable (we've put a lot of effort into fixing flaky tests etc.) but in the event of timeouts or flaky failures, you can report them to the `#stalled-checks` channel on the STL Discord and I can click rerun, as I've done so here. Thanks (and sorry for the minor headache, nobody hates flaky CIs more than I do).

Thanks for the rerun and the information! I'll make sure to report similar flaky issues on Discord in the future.

File: tests/std/tests/GH_006130_time_get_do_get_format/test.cpp (hunk 2 above)
Comment (mirion-dev) [reply tests/std/tests/GH_006130_time_get_do_get_format/test.cpp]: Done!

File: tests/std/tests/Dev11_0836436_get_time/test.cpp [hunk 3]
```diff
@@ -961,3 +963,20 @@ void test_gh_4882() {
         fieldValidation(testData.field, testData.hi, testData.fmt);
     }
 }
+
+void test_gh_6130() {
+    // GH-6130 <xloctime>: time_get::do_get doesn't parse a literal %
+    {
+        tm t{};
+        stringstream ss{"%"};
+        ss >> get_time(&t, "%%");
```
Comment (StephanTLavavej) [inline tests/std/tests/Dev11_0836436_get_time/test.cpp]: Style: When testing streams, we generally use the "weakest", most specific kind. Using an `istringstream` here will make it clearer that we're only testing input, because we don't need the full power of a `stringstream`.

File: tests/std/tests/Dev11_0836436_get_time/test.cpp [hunk 4]
```diff
@@ -961,3 +963,20 @@ void test_gh_4882() {
...
     }
 }
+
+void test_gh_6130() {
+    // GH-6130 <xloctime>: time_get::do_get doesn't parse a literal %
+    {
+        tm t{};
+        stringstream ss{"%"};
+        ss >> get_time(&t, "%%");
+        assert(!ss.fail() && ss.eof());
```
Comment (StephanTLavavej) [inline tests/std/tests/Dev11_0836436_get_time/test.cpp]: Important: We try to avoid asserting multiple conditions simultaneously. If `assert(X && Y);` ever fails, the logs won't indicate which one was the problem. Separate `assert(X);` and `assert(Y);` will produce helpful logs.

**Comment by StephanTLavavej** [comment]
I will need to resolve merge conflicts with #6133.

First, there will be trivial adjacent-add conflicts in `tests/std/tests/Dev11_0836436_get_time/test.cpp`.

Second, there will be a stealth merge conflict in `tests/libcxx/expected_results.txt`. I'll need to remove this:

https://github.com/microsoft/STL/blob/2626cf1ee9d26be701b9bdbd2fb30db240456456/tests/libcxx/expected_results.txt#L561-L565

and replace it with:

```
# Assertion failed: base(i) == in+sizeof(in)/sizeof(in[0])-1
# We fixed GH-6129 "<xloctime>: time_get::do_get uses the wrong format for %c and %x",
# which appears to have created a conflict with `#ifdef _WIN32` test code
# commented with `On Windows, the "%c" format lacks the leading week day`.
std/localization/locale.categories/category.time/locale.time.get.byname/get_one.pass.cpp FAIL
std/localization/locale.categories/category.time/locale.time.get.byname/get_one_wide.pass.cpp FAIL
```

File: tests/std/tests/Dev11_0836436_get_time/test.cpp (hunk 4 above)
Comment (mirion-dev) [reply tests/std/tests/Dev11_0836436_get_time/test.cpp]: Got it

**Comment by cpplearner** [comment]
> ```
> # Assertion failed: base(i) == in+sizeof(in)/sizeof(in[0])-1
> # We fixed GH-6129 "<xloctime>: time_get::do_get uses the wrong format for %c and %x",
> # which appears to have created a conflict with `#ifdef _WIN32` test code
> # commented with `On Windows, the "%c" format lacks the leading week day`.
> std/localization/locale.categories/category.time/locale.time.get.byname/get_one.pass.cpp FAIL
> std/localization/locale.categories/category.time/locale.time.get.byname/get_one_wide.pass.cpp FAIL
> ```

These tests expect `time_get` to treat `%c` as something like `"%m/%d/%Y %I:%M:%S %p"` in the `en_US.UTF-8` locale, not `"%a %b %e %T %Y"` which we use after #6133 (nor `"%b %d %H : %M : %S %Y"` which we use before #6133). I figured that we shouldn't bother with locale-dependent specifiers. I filed LWG-4541.

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo. Please notify me if any further changes are pushed, otherwise no action is required.

**Comment by StephanTLavavej** [comment]
Resolved merge conflicts with #6133:

* Trivial adjacent-add conflict in `tests/std/tests/Dev11_0836436_get_time/test.cpp`.
* Stealth merge conflict in `tests/libcxx/expected_results.txt`, needed to adjust expected FAIL lines.

**Comment by StephanTLavavej** [comment]
Thanks for fixing this bug and getting rid of a libcxx skip! :heart_eyes_cat: :cat2: :black_cat:
