### PR TITLE
Fix boyer_moore_searcher with the Rytter correction

### LINKED ISSUE #713: <functional>: boyer_moore_searcher produces incorrect results
Originally reported as DevCom-987357 and Microsoft-internal VSO-1101729:

```
C:\Temp>type meow.cpp
#include <algorithm>
#include <functional>
#include <iostream>
#include <string_view>
using namespace std;

int main() {
    const string_view text{
        "fbdhhihagdjcdibfdfdgbbhjcdifffdjdaighiaaaehigjegec"
        "jffcaecagcbiaeadhebggbijfdeihiceajbcjcjghhbjfcebge"};
    const string_view pattern{"aaa"};

    cout << "These should be identical:" << endl;

    {
        const default_searcher ds(pattern.begin(), pattern.end());

        const auto it_ds = search(text.begin(), text.end(), ds);

        if (it_ds == text.end()) {
            cout << "Not found" << endl;
        } else {
            cout << "Offset is " << it_ds - text.begin() << endl;
        }
    }

    {
        const boyer_moore_searcher bms(pattern.begin(), pattern.end());

        const auto it_bms = search(text.begin(), text.end(), bms);

        if (it_bms == text.end()) {
            cout << "Not found" << endl;
        } else {
            cout << "Offset is " << it_bms - text.begin() << endl;
        }
    }

    {
        const boyer_moore_horspool_searcher bmhs(pattern.begin(), pattern.end());

        const auto it_bmhs = search(text.begin(), text.end(), bmhs);

        if (it_bmhs == text.end()) {
            cout << "Not found" << endl;
        } else {
            cout << "Offset is " << it_bmhs - text.begin() << endl;
        }
    }
}

C:\Temp>cl /EHsc /nologo /W4 /MTd /std:c++17 meow.cpp
meow.cpp

C:\Temp>meow
These should be identical:
Offset is 38
Not found
Offset is 38
```

### PR DESCRIPTION
**Pull request by StephanTLavavej**
This fixes #713, silent bad codegen in an important C++17 feature.

The Boyer-Moore algorithm (published 1977) relies on a "delta2" table, but that paper didn't explain how to generate the table. Another paper by Knuth, Morris, and Pratt (also 1977) provided the algorithm for the delta2 table. Actually, it provided two algorithms producing tables compatible with the usage of delta2: a basic algorithm `dd` and an improved algorithm `dd'`. We implemented the latter, and properly translated it from 1-based indexing to 0-based indexing.

However, the published algorithm for `dd'` was incorrect! This was discovered and fixed by Rytter in 1980, which we weren't aware of until we received a bug report. While the "Rytter correction" was known in the computer science literature, I find it very curious that it isn't constantly mentioned when explaining Boyer-Moore (e.g. Wikipedia's page currently makes no mention of this).

This PR applies this 40-year-old bugfix and significantly expands our test coverage.

* `<functional>`
  * Add top-level `const` to `_Shifts`. (This is the `dd'` output array; I kept the name.)
  * Rename `_Pat_size` to `_Mx` to follow the naming in the published algorithms.
  * Fix comment typo: `_RanIt` doesn't exist, it's `_RanItPat`.
  * Add comments about the history for future programmer-archaeologists.
  * Rename `_Suffix_fn` to `_Fx`, again following the papers. Note that in the usage below, there is a semantic change: `_Suffix_fn` stored 0-based values, while `_Fx` stores 1-based values. This undoes a micro-optimization (`_Suffix_fn` avoided unnecessarily translating between the 0-based and 1-based domains), but with the increased usage of `f` in the Rytter correction, I wanted greater correspondence with the published algorithms in order to verify the implementation.
  * `_Fx` can be top-level `const` (we don't reassign/reset the `unique_ptr`).
  * Obscure bugfix: `unique_ptr<T[]>` uses `default_delete<T[]>` which uses `delete[]`, so we should use `new[]` to match, not `::new[]`. (This makes a difference only for pathologically fancy `_Diff` types.)
  * Change 0-based `_Idx` to 1-based `_Kx`.
  * Change 0-based `_Suffix` to 1-based `_Tx`.
  * Rename 1-based `_Idx` to 1-based `_Jx`. (While the code was correct, I found it confusing that `_Idx` was 0-based in other loops but 1-based in this loop.)
  * Note that after these changes, the code closely corresponds to the published algorithms, except that subscripting needs to adjust from 1-based to 0-based indexing.
  * Implement the Rytter correction, which replaces the final loop of the KMP77 algorithm.
  * For clarity and debug codegen, I extracted a repeated array access into `_Temp` after verifying that this doesn't disturb the algorithm.
* `P0220R1_searchers/test.cpp`
  * Add test cases to `test_boyer_moore_table2_construction()` from Rytter's paper, and other repetitive patterns where the Rytter correction produces different results. Those patterns were "made from scratch" but for the results, I just used the output of the implementation and manually verified selected answers for the AB and ABC categories against my understanding of delta2's meaning (including the unused last entry, see #714; I was able to understand why it's 10 for `"aaaaaaaaaa"`, 2 for `"abaabaabaa"`, and why it should be 1 for `"ababababab"` and `"abcabcabc"`).
  * Add the test case from #713, plus hand-selected test cases from the randomized testing below (selected for interesting-looking patterns).
  * Add randomized test coverage for both Boyer-Moore and Boyer-Moore-Horspool (the latter is not known to have any bugs). This uses a fully-seeded `mt19937` (for speed, instead of directly using `random_device`). It prints out the needle/haystack for any failures, so we don't need the seed printing/reload machinery from `P0067R5_charconv/test.cpp`. (I'm using `mt19937` for 32-bit performance, since we don't need 64-bit values.) The randomized coverage uses alphabets from `[a-b]` to `[a-f]`; the former finds more examples of the bug being fixed here (as it's more likely to create highly repetitive patterns). Expanding the alphabet makes repetition unlikely, which is why I stop at `[a-f]`. The test does a few things to improve non-optimized debug performance (reusing `needle` and `haystack` to avoid repeated allocations, using `const char *` to avoid iterator overhead), although I didn't pursue this to the ultimate limit (e.g. `uniform_int_distribution` is somewhat costly and could be avoided at the expense of some bias). Finally, as with the other randomized coverage, I print out timing statistics if it takes a long time; on my i7-8700 it's tuned to take ~400 ms which seems reasonable (given the number of configurations, the performance of VMs, and the time needed for compilation).

While this changes the behavior of a function, it is ABI-safe. This doesn't require coordinated changes across functions - the rest of the Boyer-Moore machinery is unchanged, and the layout of the delta2 table is unchanged. We're simply filling it with different values. In the event of mismatch, the linker will either pick the correct or incorrect algorithm, so this can't make things any worse.

### CODE REVIEW

File: stl/inc/functional [hunk 1]
```diff
@@ -1768,31 +1768,57 @@ private:
...
-    // builds Boyer-Moore's delta_2 table from a pattern [_Pat_first, _Pat_first + _Pat_size)
-    // pre: _Shifts is a pointer to _Pat_size _Iter_diff_t<_RanIt>s
-    if (_Pat_size == 0) {
+void _Build_boyer_moore_delta_2_table(_Iter_diff_t<_RanItPat>* const _Shifts, const _RanItPat _Pat_first,
+    const _Iter_diff_t<_RanItPat> _Mx, _Pred_eq& _Eq) {
+    // Builds Boyer-Moore's delta_2 table from a pattern [_Pat_first, _Pat_first + _Mx).
+    // pre: _Shifts is a pointer to _Mx _Iter_diff_t<_RanItPat>s.
+    // This is the `dd'` algorithm from "Fast Pattern Matching In Strings" by Knuth, Morris, and Pratt (1977).
+    // Note that the published algorithm used 1-based indexing!
+    // This contains the "Rytter correction" from "Algorithms For String Searching: A Survey" by Baeza-Yates (1989),
```
Comment (BillyONeal) [inline stl/inc/functional:1777]: In the msvc version of this PR please check in a copy of `Baeza-Yates` to doc/ if you can. (I know we can't on GitHub due to licensing)

File: stl/inc/functional [hunk 2]
```diff
@@ -1768,31 +1768,57 @@ private:
...
+        _Fx[static_cast<size_t>(_Jx - 1)] = _Tx;
+        while (_Tx <= _Mx && !_Eq(_Pat_first[_Jx - 1], _Pat_first[_Tx - 1])) {
+            _Shifts[_Tx - 1] = (_STD min)(_Shifts[_Tx - 1], _Mx - _Jx);
+            _Tx              = _Fx[static_cast<size_t>(_Tx - 1)];
         }
     }
 
-    for (_Diff _Idx = 0; _Idx <= _Suffix; ++_Idx) {
-        _Shifts[_Idx] = (_STD min)(_Shifts[_Idx], _Pat_size + _Suffix - _Idx);
+    // Rytter correction
```
Comment (BillyONeal) [inline stl/inc/functional:1801]: I don't really think this comment explains anything you didn't already explain on 1777.

File: stl/inc/functional [hunk 3]
```diff
@@ -1768,31 +1768,57 @@ private:
...
+    _Diff _Qx = _Tx;
+    _Tx       = _Mx + 1 - _Qx;
```
Comment (BillyONeal) [inline stl/inc/functional:1803]: I think it would be better if this didn't reuse _Tx; even if the paper uses this form that's less clear for both humans and optimizers since the same variable is being used for different values?

File: stl/inc/functional [hunk 4]
```diff
@@ -1768,31 +1768,57 @@ private:
...
 
     using _Diff = _Iter_diff_t<_RanItPat>;
-    unique_ptr<_Diff[]> _Suffix_fn{::new _Diff[static_cast<size_t>(_Pat_size)]};
-    for (_Diff _Idx = 0; _Idx < _Pat_size; ++_Idx) {
-        _Shifts[_Idx] = 2 * _Pat_size - _Idx - 1;
+
+    const unique_ptr<_Diff[]> _Fx{new _Diff[static_cast<size_t>(_Mx)]};
+
+    for (_Diff _Kx = 1; _Kx <= _Mx; ++_Kx) {
+        _Shifts[_Kx - 1] = 2 * _Mx - _Kx;
```
Comment (BillyONeal) [inline stl/inc/functional:1789]: Preexisting: this should probably hoist `2*_Mx` and overflow check it?

```
if ((numeric_limits<_Diff>::max)() - _Mx < _Mx) {
    _Xlength_error("pattern is too long");
}
```

File: stl/inc/functional [hunk 5]
```diff
@@ -1768,31 +1768,57 @@ private:
...
-    for (_Diff _Idx = _Pat_size; _Idx > 0; --_Idx, (void) --_Suffix) {
-        _Suffix_fn[static_cast<size_t>(_Idx - 1)] = _Suffix;
-        while (_Suffix < _Pat_size && !_Eq(_Pat_first[_Idx - 1], _Pat_first[_Suffix])) {
-            _Shifts[_Suffix] = (_STD min)(_Shifts[_Suffix], _Pat_size - _Idx);
-            _Suffix          = _Suffix_fn[static_cast<size_t>(_Suffix)];
+    _Diff _Tx = _Mx + 1;
+    for (_Diff _Jx = _Mx; _Jx > 0; --_Jx, (void) --_Tx) {
+        _Fx[static_cast<size_t>(_Jx - 1)] = _Tx;
+        while (_Tx <= _Mx && !_Eq(_Pat_first[_Jx - 1], _Pat_first[_Tx - 1])) {
+            _Shifts[_Tx - 1] = (_STD min)(_Shifts[_Tx - 1], _Mx - _Jx);
```
Comment (BillyONeal) [inline stl/inc/functional:1796]: I don't really feel that leaving this with 1 indexing as published then doing -1 into every array access is 'clearer' but you touched it last so you get to say what the pattern is :D

Comment (BillyONeal) [inline stl/inc/functional:1796]: Preexisting: `_Mx-_Jx` might accidentally promote to int so it needs a cast.

File: stl/inc/functional [hunk 6]
```diff
@@ -1768,31 +1768,57 @@ private:
...
+        _Fx[static_cast<size_t>(_Jx - 1)] = _Tx1;
+        while (_Tx1 >= 1 && !_Eq(_Pat_first[_Jx - 1], _Pat_first[_Tx1 - 1])) {
+            _Tx1 = _Fx[static_cast<size_t>(_Tx1 - 1)];
+        }
+    }
+
+    _Diff _Qx1 = 1;
+    while (_Qx < _Mx) {
+        for (_Diff _Kx = _Qx1; _Kx <= _Qx; ++_Kx) {
+            _Shifts[_Kx - 1] = (_STD min)(_Shifts[_Kx - 1], _Mx + _Qx - _Kx);
```
Comment (BillyONeal) [inline stl/inc/functional:1814]: Ditto needs cast

File: stl/inc/functional [hunk 7]
```diff
@@ -1768,31 +1768,57 @@ private:
...
+        }
+        _Qx1 = _Qx + 1;
```
Comment (BillyONeal) [inline stl/inc/functional:1816]: We might need casts to suppress warnings for this

File: stl/inc/functional (hunk 1 above)
Comment (StephanTLavavej) [reply stl/inc/functional:1777]: Already done. (I'm grateful to Baeza-Yates, whose personal website linked to Google Scholar, which linked to https://dl.acm.org/doi/pdf/10.1145/74697.74700 containing the full PDF of his paper, with an exceedingly helpful summary of the history here.)

File: stl/inc/functional (hunk 2 above)
Comment (StephanTLavavej) [reply stl/inc/functional:1801]: I could be persuaded to drop this comment, although it marks the point where we have to stop following the KMP77 algorithm.

File: stl/inc/functional (hunk 3 above)
Comment (StephanTLavavej) [reply stl/inc/functional:1803]: For humans, I think clarity means "corresponds to the published algorithm"; introducing a separate name makes such correspondence harder to see. (I already moved some variable definitions down to their initializations.) I don't think that `_Tx2` or something would buy anything.

For optimizers, `_Tx` is very obviously being overwritten here; I'm not concerned about confusing them at all.

File: stl/inc/functional (hunk 5 above)
Comment (StephanTLavavej) [reply stl/inc/functional:1796]: I *strongly* believe that verifying that every `[]` subscript contains a `- 1` adjustment is easier than:
* Using 0-based indexing to simplify the subscripts, but
* Adjusting back to the 1-based domain for other usage, but
* Staying in the 0-based domain when values are merely stored and retrieved (this was the clever `_Suffix_fn` micro-optimization), but
* Avoiding adjustments when they would cancel each other out (the original final loop ended with `_Pat_size + _Suffix - _Idx` where it added 0-based `_Suffix` and then subtracted 0-based `_Idx`).

My brain, which can read hexfloats natively and find the one correctness-damaging typo in a thousand-line diff, was having trouble keeping up with the switching between 0-based and 1-based code, especially with the significant added code in the Rytter correction.

File: stl/inc/functional (hunk 3 above)
Comment (StephanTLavavej) [reply stl/inc/functional:1803]: If I truly understood the algorithm and could provide descriptive names for all variables, then in addition to adjusting everything to 0-indexing, I could distinctly name the two phases of `_Tx`. Since I don't have such understanding at this moment, I believe we should prioritize matching the published algorithm.

File: stl/inc/functional (hunk 2 above)
Comment (StephanTLavavej) [reply stl/inc/functional:1801]: Hmm, I think the best of both worlds would be to move the Baeza-Yates and Rytter citations down to this point, avoiding the redundancy!

File: stl/inc/functional (hunk 4 above)
Comment (BillyONeal) [reply stl/inc/functional:1789]: Ideally this overflow check shouldn't be needed, I filed #726 to track that.

File: stl/inc/functional (hunk 2 above)
Comment (BillyONeal) [reply stl/inc/functional:1801]: Agreed, that would be awesome!

File: stl/inc/functional (hunk 4 above)
Comment (StephanTLavavej) [reply stl/inc/functional]: Added overflow check with a slightly rephrased message. I didn't attempt to extract `2 * _Mx` out of the loop (it's a single arithmetic operation that the compiler can easily see).

File: stl/inc/functional (hunk 5 above)
Comment (StephanTLavavej) [reply stl/inc/functional]: Added cast (which solves both the transition from the `size_t` domain back to `_Diff`, and the need for `std::min` to be given the same types).

File: stl/inc/functional (hunk 6 above)
Comment (StephanTLavavej) [reply stl/inc/functional]: Added.

File: stl/inc/functional (hunk 7 above)
Comment (StephanTLavavej) [reply stl/inc/functional:1821]: Now that everything's in the `size_t` domain, no casts should be necessary here.

File: stl/inc/functional [hunk 8]
```diff
@@ -1768,31 +1768,62 @@ private:
...
 
-    using _Diff = _Iter_diff_t<_RanItPat>;
-    unique_ptr<_Diff[]> _Suffix_fn{::new _Diff[static_cast<size_t>(_Pat_size)]};
-    for (_Diff _Idx = 0; _Idx < _Pat_size; ++_Idx) {
-        _Shifts[_Idx] = 2 * _Pat_size - _Idx - 1;
+    if ((numeric_limits<_Diff>::max)() - _Pat_size < _Pat_size) {
+        _Xlength_error("Boyer-Moore pattern is too long");
+    }
+
+    const size_t _Mx = static_cast<size_t>(_Pat_size);
```
Comment (CaseyCarter) [inline stl/inc/functional:1787]:
```suggestion
    const auto _Mx = static_cast<size_t>(_Pat_size);
```

File: tests/std/tests/P0220R1_searchers/test.cpp [hunk 9]
```diff
@@ -290,6 +357,89 @@ void test_case_BM_unicode32() {
...
+                    report_randomized_failure("boyer_moore_horspool_searcher", needle, haystack);
+                }
+            }
+        }
+    }
+
+    const auto finish = chrono::steady_clock::now();
+    const auto ms     = chrono::duration_cast<chrono::milliseconds>(finish - start);
+
+    if (ms.count() > 10'000) {
```
Comment (CaseyCarter) [inline tests/std/tests/P0220R1_searchers/test.cpp:437]: If we named `ms` something descriptive like `elapsed`, we could stay in the duration domain here and test `elapsed > 10s` which is beautifully clear.

File: stl/inc/functional (hunk 8 above)
Comment (StephanTLavavej) [reply stl/inc/functional:1787]: Yep, that's the usual convention! Done.

File: tests/std/tests/P0220R1_searchers/test.cpp [hunk 10]
```diff
@@ -290,6 +357,89 @@ void test_case_BM_unicode32() {
...
+    cout << "This is a randomized test.\n";
+    cout << "DO NOT IGNORE/RERUN THIS FAILURE.\n";
+    cout << "You must report it to the STL maintainers.\n";
+    assert(false);
+}
+
+void initialize_randomness(mt19937& mt) {
+    constexpr size_t n = mt19937::state_size;
+    constexpr size_t w = mt19937::word_size;
+    static_assert(w % 32 == 0);
```
[the remark this answers is not in the document]
Comment (StephanTLavavej) [reply tests/std/tests/P0220R1_searchers/test.cpp:371]: I derived this from the charconv test where this is necessary for `mt19937_64` but you're right, this is unnecessarily complicated (we won't never need to use the 64-bit engine here). I've simplified this.

File: tests/std/tests/P0220R1_searchers/test.cpp (hunk 9 above)
Comment (StephanTLavavej) [reply tests/std/tests/P0220R1_searchers/test.cpp:437]: Great idea, simplified!

File: tests/std/tests/P0220R1_searchers/test.cpp (hunk 10 above)
[the remark this answers is not in the document]
Comment (CaseyCarter) [reply tests/std/tests/P0220R1_searchers/test.cpp]: > this is necessary for `mt19937_64`

For `mt19937_64` it's precisely 64 =)

**Comment by shreevatsa** [comment]
For what it's worth: note that although Knuth mentions Rytter's correction in his list of papers (see P71 in [his vita](https://cs.stanford.edu/~knuth/vita.pdf#page=21)), his reprint of this paper (as Chapter 9 of [Selected Papers on Design of Algorithms](https://cs.stanford.edu/~knuth/da.html)) says Rytter's is a more complicated correction than necessary:

image

(skipping a page and a bit…)

image

— sorry if this is irrelevant or already well-known; just posting here in case it's helpful.

File: stl/inc/functional (hunk 1 above)
Comment (miscco) [reply stl/inc/functional]: I am unsure about links in comments but linking that paper might help.

**Comment by miscco** [comment]
This makes me really appreciate the current times where naming is actually considered as important.

That said the algorithm is a clear implementation of the paper.

File: stl/inc/functional [hunk 11]
```diff
@@ -1768,31 +1768,62 @@ private:
 
 // FUNCTION TEMPLATE _Build_boyer_moore_delta_2_table
 template <class _RanItPat, class _Pred_eq>
-void _Build_boyer_moore_delta_2_table(_Iter_diff_t<_RanItPat>* _Shifts, const _RanItPat _Pat_first,
+void _Build_boyer_moore_delta_2_table(_Iter_diff_t<_RanItPat>* const _Shifts, const _RanItPat _Pat_first,
     const _Iter_diff_t<_RanItPat> _Pat_size, _Pred_eq& _Eq) {
-    // builds Boyer-Moore's delta_2 table from a pattern [_Pat_first, _Pat_first + _Pat_size)
-    // pre: _Shifts is a pointer to _Pat_size _Iter_diff_t<_RanIt>s
+    // Builds Boyer-Moore's delta_2 table from a pattern [_Pat_first, _Pat_first + _Pat_size).
```
Comment (mattspring) [inline stl/inc/functional:1773]: If you're gonna change this line, fix the scope operator mismatch, right?

Comment (SuperWig) [reply stl/inc/functional:1773]: `[a, b)` means inclusive, exclusive. Unless you're saying this should be inclusive for both?

**Comment by mozjag** [comment]
> For what it's worth: note that although Knuth mentions Rytter's correction in his list of papers (see P71 in [his vita](https://cs.stanford.edu/~knuth/vita.pdf#page=21)), the addendum to his reprint of this paper (as Chapter 9 of [Selected Papers on Design of Algorithms](https://cs.stanford.edu/~knuth/da.html)) seems to suggest that there may be simpler corrections than Rytter's:

This might also be of interest: "[On the *shift*-table in Boyer-Moore’s String Matching Algorithm](https://pdfs.semanticscholar.org/6c13/862a3f1d68434104a0da698e93cf892f9516.pdf)" by Yang Wang, which discusses a different way to compute the *shift*-table. It also includes an improved version (by A. V. Aho) of the original algorithm.

File: stl/inc/functional (hunk 11 above)
Comment (StephanTLavavej) [reply stl/inc/functional:1773]: Like almost all ranges in the STL, this is indeed an inclusive-exclusive (aka half-open) range, so the `[first, last)` notation is correct and conventional as @SuperWig noted. Thank you, @mattspring, for bringing the potential typo to our attention - it is so easy to swap `]` and `)` and the difference is significant.

Comment (mattspring) [reply stl/inc/functional:1773]: Whoops, protip: don't drink and review strangers repos

Comment (CaseyCarter) [reply stl/inc/functional:1773]: > Whoops, protip: don't drink and review strangers repos

Does this mean it's ok to drink while reviewing repos you're a member of? Asking for a friend.
