### PR TITLE
Fix the `_Choose_pocca_v` branch in `basic_string::operator=(const&)`

### LINKED ISSUE #3997: `<xstring>`: Fix `basic_string::operator=(const&)` thoroughly
`basic_string::operator=(const&)` is still problematic even after #3862. For example:
https://github.com/microsoft/STL/blob/60f18856c56389001c38a9929ef37bd5c01c4e47/stl/inc/xstring#L3170-L3175
1. After `_Tidy_deallocate` the string is left in SSO mode, so the pointer should be constructed instead of assigned.
2. The new allocation lacks ASAN annotation.

These are what I can find. As the branch is in such a broken state, I'm uncertain whether there are other problems.

### PR DESCRIPTION
**Pull request by achabense**
Fixes #3997; also adds test coverages for non-trivial pointers.
---update---
Fixes another lifetime problem in `_Take_contents`. Hopefully fixes all the lifetime issue of `_Ptr` in `basic_string`. Possibly related to #3949.

Thanks to @frederick-vs-ja for suggesting adding test coverage for non-trivial pointers! Also thanks for implementing `VSO_0000000_fancy_pointers`, that test helps me a lot

---update (solved with workaround)---
The updated test meets another problem in `static_assert(test_sequence<vector>)`'s `test_sequence_move_ctor`... (see https://github.com/microsoft/STL/pull/4031#discussion_r1328413358)

### CODE REVIEW

File: tests/std/tests/VSO_0000000_allocator_propagation/test.cpp [hunk 1]
```diff
@@ -34,6 +34,165 @@ _CONSTEXPR20 void assert_is_permutation(const Container& cont, initializer_list<
...
+
+    _CONSTEXPR20 lifetime_checked_pointer& operator=(const lifetime_checked_pointer& other) noexcept {
+        assert(living && other.living);
+        ptr = other.ptr;
+        return *this;
+    }
+
+    _CONSTEXPR20 explicit operator bool() const noexcept {
+        assert(living);
+        return static_cast<bool>(ptr);
```
Comment (achabense) [inline tests/std/tests/VSO_0000000_allocator_propagation/test.cpp:70]: strangely, when I uses `ptr != nullptr`, I get the following error:

<details>
<summary>Result</summary>

```
-- Testing: 30 tests, 16 workers --
PASS: std :: tests/VSO_0000000_allocator_propagation:00 (1 of 30)
PASS: std :: tests/VSO_0000000_allocator_propagation:08 (2 of 30)
UNSUPPORTED: std :: tests/VSO_0000000_allocator_propagation:17 (3 of 30)
UNSUPPORTED: std :: tests/VSO_0000000_allocator_propagation:18 (4 of 30)
UNSUPPORTED: std :: tests/VSO_0000000_allocator_propagation:19 (5 of 30)
UNSUPPORTED: std :: tests/VSO_0000000_allocator_propagation:20 (6 of 30)
PASS: std :: tests/VSO_0000000_allocator_propagation:10 (7 of 30)
PASS: std :: tests/VSO_0000000_allocator_propagation:09 (8 of 30)
PASS: std :: tests/VSO_0000000_allocator_propagation:12 (9 of 30)
PASS: std :: tests/VSO_0000000_allocator_propagation:01 (10 of 30)
PASS: std :: tests/VSO_0000000_allocator_propagation:14 (11 of 30)
PASS: std :: tests/VSO_0000000_allocator_propagation:21 (12 of 30)
PASS: std :: tests/VSO_0000000_allocator_propagation:07 (13 of 30)
PASS: std :: tests/VSO_0000000_allocator_propagation:22 (14 of 30)
UNSUPPORTED: std :: tests/VSO_0000000_allocator_propagation:29 (15 of 30)
PASS: std :: tests/VSO_0000000_allocator_propagation:13 (16 of 30)
PASS: std :: tests/VSO_0000000_allocator_propagation:15 (17 of 30)
PASS: std :: tests/VSO_0000000_allocator_propagation:05 (18 of 30)
PASS: std :: tests/VSO_0000000_allocator_propagation:04 (19 of 30)
PASS: std :: tests/VSO_0000000_allocator_propagation:23 (20 of 30)
PASS: std :: tests/VSO_0000000_allocator_propagation:06 (21 of 30)
PASS: std :: tests/VSO_0000000_allocator_propagation:02 (22 of 30)
FAIL: std :: tests/VSO_0000000_allocator_propagation:24 (23 of 30)
******************** TEST 'std :: tests/VSO_0000000_allocator_propagation:24' FAILED ********************
Build setup steps:
Build steps:
Build step failed unexpectedly.
Command: "C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.38.33030\bin\HostX64\x64\cl.EXE" "-c" "(replaced)\STL\tests\std\tests\VSO_0000000_allocator_propagation\test.cpp" "-I(replaced)\STL\out\x64\out\inc" "-I(replaced)\STL\llvm-project\libcxx\test\support" "-I(replaced)\STL\tests\std\include" "/nologo" "/Od" "/W4" "/w14061" "/w14242" "/w14265" "/w14582" "/w14583" "/w14587" "/w14588" "/w14749" "/w14841" "/w14842" "/w15038" "/w15214" "/w15215" "/w15216" "/w15217" "/w15262" "/sdl" "/WX" "/D_ENABLE_STL_INTERNAL_CHECK" "/bigobj" "/FIforce_include.hpp" "/w14365" "/w15267" "/D_ENFORCE_FACET_SPECIALIZATIONS=1" "/D_STL_CALL_ABORT_INSTEAD_OF_INVALID_PARAMETER" "/BE" "/c" "/EHsc" "/MTd" "/std:c++latest" "/permissive-" "/w14640" "/Zc:threadSafeInit-"
Exit Code: 2
Standard Output:
--
test.cpp
"(replaced)\STL\tests\std\tests\VSO_0000000_allocato
          r_propagation\test.cpp", line 1844: error: expression must have a
          constant value
      static_assert(test_sequence<vector>());
                    ^
"(replaced)\STL\tests\std\tests\VSO_0000000_allocato
          r_propagation\test.cpp", line 70: note: cannot compare a pointer past
          the end of an array with a pointer to another complete object
          return ptr != nullptr;
                     ^
"(replaced)\STL\out\x64\out\inc\vector", line 111:
          note: called from:
          _STL_VERIFY(_Off == 0 || _Ptr, "cannot seek value-initialized vector iterator");
          ^
"(replaced)\STL\out\x64\out\inc\vector", line 124:
          note: called from:
          _Verify_offset(_Off);
                        ^
"(replaced)\STL\out\x64\out\inc\vector", line 305:
          note: called from:
          _Mybase::operator+=(_Off);
                             ^
"(replaced)\STL\out\x64\out\inc\xutility", line
          1414: note: called from:
          _Where += _Off;
                 ^
"(replaced)\STL\out\x64\out\inc\xutility", line
          1478: note: called from:
      _STD advance(_First, -_Off);
                  ^
"(replaced)\STL\tests\std\tests\VSO_0000000_allocato
          r_propagation\test.cpp", line 272: note: called from:
      *prev(src.end()) += 8;
           ^
"(replaced)\STL\tests\std\tests\VSO_0000000_allocato
          r_propagation\test.cpp", line 459: note: called from:
      test_sequence_copy_ctor<Sequence>();
                                       ^

--


********************
PASS: std :: tests/VSO_0000000_allocator_propagation:03 (24 of 30)
PASS: std :: tests/VSO_0000000_allocator_propagation:26 (25 of 30)
PASS: std :: tests/VSO_0000000_allocator_propagation:25 (26 of 30)
PASS: std :: tests/VSO_0000000_allocator_propagation:11 (27 of 30)
PASS: std :: tests/VSO_0000000_allocator_propagation:27 (28 of 30)
PASS: std :: tests/VSO_0000000_allocator_propagation:28 (29 of 30)
PASS: std :: tests/VSO_0000000_allocator_propagation:16 (30 of 30)
********************
Failed Tests (1):
  std :: tests/VSO_0000000_allocator_propagation:24


Testing Time: 21.60s
  Unsupported:  5
  Passed     : 24
  Failed     :  1
```
</details>

Comment (frederick-vs-ja) [reply tests/std/tests/VSO_0000000_allocator_propagation/test.cpp:70]: Perhaps we should add some comments for EDG...

**Comment by achabense** [comment]
`_Take_contents` shouldn't call `_Rght._Tidy_init`. This might cause #3949 I guess.

File: stl/inc/xstring [hunk 2]
```diff
@@ -3052,8 +3052,9 @@ private:
 
         if (_Right_data._Large_mode_engaged()) { // steal buffer
             _Construct_in_place(_My_data._Bx._Ptr, _Right_data._Bx._Ptr);
-            _Right_data._Bx._Ptr = nullptr;
             _Swap_proxy_and_iterators(_Right);
+
+            _Destroy_in_place(_Right_data._Bx._Ptr);
```
Comment (achabense) [inline stl/inc/xstring:3057]: `_Tidy_init` assumes that the pointer is not active.

File: tests/std/tests/VSO_0000000_allocator_propagation/test.cpp [hunk 3]
```diff
@@ -34,82 +34,106 @@ _CONSTEXPR20 void assert_is_permutation(const Container& cont, initializer_list<
...
+}
+_CONSTEXPR20 void decrease_counter() {
+    if (!_Is_constant_evaluated()) {
+        --pointer_counter;
+        assert(pointer_counter >= 0);
+    }
+}
+
+constexpr uintptr_t living_word = 0x86427531;
+
```
Comment (achabense) [inline tests/std/tests/VSO_0000000_allocator_propagation/test.cpp:51]: `living` and `living_word` (I need to find some better names for them) are used to detect that the pointer doesn't work in unconstructed state. A failed `assert` 100% suggests a bug; a successful `assert` suggests a high rate that the pointer really works in well-constructed state.

File: tests/std/tests/VSO_0000000_allocator_propagation/test.cpp [hunk 4]
```diff
@@ -34,82 +34,106 @@ _CONSTEXPR20 void assert_is_permutation(const Container& cont, initializer_list<
...
+    if (!_Is_constant_evaluated()) {
+        ++pointer_counter;
+    }
+}
+_CONSTEXPR20 void decrease_counter() {
+    if (!_Is_constant_evaluated()) {
+        --pointer_counter;
+        assert(pointer_counter >= 0);
+    }
+}
```
Comment (achabense) [inline tests/std/tests/VSO_0000000_allocator_propagation/test.cpp:48]: `pointer_counter` is used to detect dtor leakage.

File: tests/std/tests/VSO_0000000_allocator_propagation/test.cpp [hunk 5]
```diff
@@ -785,35 +968,57 @@ void test_string_swap(const size_t id1, const size_t id2) {
...
 
     test_string_swap<StationaryAlloc<char32_t>>(11, 11); // non-POCS, equal allocators
+    assert(pointer_counter == 0);
     // UNDEFINED BEHAVIOR, NOT TESTED - non-POCS, non-equal allocators
     test_string_swap<SwapAlloc<char32_t>>(11, 11); // POCS, equal allocators
+    assert(pointer_counter == 0);
     test_string_swap<SwapAlloc<char32_t>>(11, 22); // POCS, non-equal allocators
+    assert(pointer_counter == 0);
     test_string_swap<SwapEqualAlloc<char32_t>>(11, 22); // POCS, always-equal allocators
+    assert(pointer_counter == 0);
```
Comment (achabense) [inline tests/std/tests/VSO_0000000_allocator_propagation/test.cpp:1021]: Do I need to remove these `assert`s in `test_string`? They were used to locate the assertion failure in the main function. As the bug is solved now, I think we can just retain those in the main function?

File: tests/std/tests/VSO_0000000_allocator_propagation/test.cpp (hunk 3 above)
Comment (achabense) [reply tests/std/tests/VSO_0000000_allocator_propagation/test.cpp:51]: As the `pointer_counter` is enough to detect both bugs (and it's not hard to locate those bugs with it), can I just remove `magic_number` and `dat`? This will make the code less noisy...

File: tests/std/tests/VSO_0000000_allocator_propagation/test.cpp [hunk 6]
```diff
@@ -34,6 +34,188 @@ _CONSTEXPR20 void assert_is_permutation(const Container& cont, initializer_list<
...
+
+    _CONSTEXPR20 void assert_living() const noexcept {
+        if (!_Is_constant_evaluated()) {
+            assert(record.find(this) != record.end());
+        }
+    }
+
+    static bool none_living() noexcept {
+        return record.empty();
+    }
```
Comment (achabense) [inline tests/std/tests/VSO_0000000_allocator_propagation/test.cpp:61]: Instead of using `assert_none_living`, I'm keeping the `assert(lifetime_checker::none_living)` pattern in the main function to make it easier to locate bugs between test functions.

File: tests/std/tests/VSO_0000000_allocator_propagation/test.cpp [hunk 7]
```diff
@@ -307,7 +457,7 @@ _CONSTEXPR20 bool test_sequence() {
     test_sequence_copy_assign<Sequence, CopyAlloc<int>>(11, 22, 11); // POCCA, non-equal allocators
     test_sequence_copy_assign<Sequence, CopyEqualAlloc<int>>(11, 22, 11); // POCCA, always-equal allocators
 
-    test_sequence_move_ctor<Sequence>();
+    // test_sequence_move_ctor<Sequence>();
```
Comment (achabense) [inline tests/std/tests/VSO_0000000_allocator_propagation/test.cpp:460]: [WIP] I'm temporarily removing this test; I'm not sure what happens to `vector(vector&&)` under `StationaryAlloc` case.

File: tests/std/tests/VSO_0000000_allocator_propagation/test.cpp [hunk 8]
```diff
@@ -34,6 +34,155 @@ _CONSTEXPR20 void assert_is_permutation(const Container& cont, initializer_list<
...
+
+public:
+    test_leak(const test_leak&)            = delete;
+    test_leak& operator=(const test_leak&) = delete;
+
+    _CONSTEXPR20 test_leak() noexcept /* terminates */ : ptr(allocator<char>{}.allocate(1)) {}
+    _CONSTEXPR20 ~test_leak() {
+        allocator<char>{}.deallocate(ptr, 1);
+    }
+};
```
Comment (achabense) [inline tests/std/tests/VSO_0000000_allocator_propagation/test.cpp:48]: This works well with constexpr basic_string. I'm really confused what happens with the `vector(vector&&)` in `static_assert(test_sequence<vector>)`'s `test_sequence_move_ctor`

File: tests/std/tests/VSO_0000000_allocator_propagation/test.cpp (hunk 7 above)
Comment (achabense) [reply tests/std/tests/VSO_0000000_allocator_propagation/test.cpp:460]: <details>
<summary>Problematic</summary>

```cpp
// Copyright (c) Microsoft Corporation.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

#include <algorithm>
#include <cassert>
#include <cstdlib>
#include <cstring>
#include <deque>
#include <forward_list>
#include <functional>
#include <initializer_list>
#include <iterator>
#include <list>
#include <map>
#include <memory>
#include <new>
#include <set>
#include <string>
#include <type_traits>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>

using namespace std;

template <class Container>
_CONSTEXPR20 void assert_equal(const Container& cont, initializer_list<typename Container::value_type> il) {
    assert(equal(cont.begin(), cont.end(), il.begin(), il.end()));
}

template <class Container>
_CONSTEXPR20 void assert_is_permutation(const Container& cont, initializer_list<typename Container::value_type> il) {
    assert(is_permutation(cont.begin(), cont.end(), il.begin(), il.end()));
}

class test_leak {
    char* ptr;

public:
    test_leak(const test_leak&) = delete;
    test_leak& operator=(const test_leak&) = delete;

    _CONSTEXPR20 test_leak() noexcept /* terminates */ : ptr(allocator<char>{}.allocate(1)) {}
    _CONSTEXPR20 ~test_leak() {
        allocator<char>{}.deallocate(ptr, 1);
    }
};

template <class T>
class nontrivial_pointer : private test_leak {
public:
    T* ptr;
    _CONSTEXPR20 nontrivial_pointer() noexcept : ptr(nullptr) {}
    _CONSTEXPR20 explicit nontrivial_pointer(T* ptr_) noexcept : ptr(ptr_) {}
    _CONSTEXPR20 /*implicit*/ nontrivial_pointer(nullptr_t) noexcept : ptr(nullptr) {}

    _CONSTEXPR20 nontrivial_pointer(const nontrivial_pointer& other) noexcept : ptr(other.ptr) {}
    template <class U, enable_if_t<is_convertible_v<U*, T*>, int> = 0>
    _CONSTEXPR20 nontrivial_pointer(const nontrivial_pointer<U>& other) noexcept : ptr(other.ptr) {}
    _CONSTEXPR20 nontrivial_pointer& operator=(const nontrivial_pointer& other) noexcept {
        ptr = other.ptr;
        return *this;
    }

    _CONSTEXPR20 ~nontrivial_pointer() = default;

    _CONSTEXPR20 explicit operator bool() const noexcept {
        return static_cast<bool>(ptr);
    }
    _CONSTEXPR20 add_lvalue_reference_t<T> operator*() const noexcept {
        return *ptr;
    }
    _CONSTEXPR20 T* operator->() const noexcept {
        return ptr;
    }
    template <class I, enable_if_t<is_integral_v<I>, int> = 0>
    _CONSTEXPR20 add_lvalue_reference_t<T> operator[](I off) const noexcept {
        return ptr[off];
    }

    _CONSTEXPR20 nontrivial_pointer& operator++() noexcept {
        ++ptr;
        return *this;
    }
    _CONSTEXPR20 nontrivial_pointer operator++(int) noexcept {
        return nontrivial_pointer(ptr++);
    }
    _CONSTEXPR20 nontrivial_pointer& operator--() noexcept {
        --ptr;
        return *this;
    }
    _CONSTEXPR20 nontrivial_pointer operator--(int) noexcept {
        return nontrivial_pointer(ptr--);
    }
    template <class I, enable_if_t<is_integral_v<I>, int> = 0>
    _CONSTEXPR20 nontrivial_pointer& operator+=(I diff) noexcept {
        ptr += diff;
        return *this;
    }
    template <class I, enable_if_t<is_integral_v<I>, int> = 0>
    _CONSTEXPR20 nontrivial_pointer& operator-=(I diff) noexcept {
        ptr -= diff;
        return *this;
    }

    template <class I, enable_if_t<is_integral_v<I>, int> = 0>
    _CONSTEXPR20 friend nontrivial_pointer operator+(nontrivial_pointer ptr, I diff) noexcept {
        return ptr += diff;
    }
    template <class I, enable_if_t<is_integral_v<I>, int> = 0>
    _CONSTEXPR20 friend nontrivial_pointer operator+(I diff, nontrivial_pointer ptr) noexcept {
        return ptr += diff;
    }
    _CONSTEXPR20 friend ptrdiff_t operator-(nontrivial_pointer lhs, nontrivial_pointer rhs) noexcept {
        return lhs.ptr - rhs.ptr;
    }
    template <class I, enable_if_t<is_integral_v<I>, int> = 0>
    _CONSTEXPR20 friend nontrivial_pointer operator-(nontrivial_pointer ptr, I diff) noexcept {
        return ptr -= diff;
    }

    _CONSTEXPR20 friend bool operator==(nontrivial_pointer lhs, nontrivial_pointer rhs) noexcept {
        return lhs.ptr == rhs.ptr;
    }
    _CONSTEXPR20 friend bool operator==(nontrivial_pointer ptr, nullptr_t) noexcept {
        return !static_cast<bool>(ptr.ptr);
    }
    _CONSTEXPR20 friend bool operator==(nullptr_t, nontrivial_pointer ptr) noexcept {
        return !static_cast<bool>(ptr.ptr);
    }
    _CONSTEXPR20 friend bool operator!=(nontrivial_pointer lhs, nontrivial_pointer rhs) noexcept {
        return lhs.ptr != rhs.ptr;
    }
    _CONSTEXPR20 friend bool operator!=(nontrivial_pointer ptr, nullptr_t) noexcept {
        return static_cast<bool>(ptr.ptr);
    }
    _CONSTEXPR20 friend bool operator!=(nullptr_t, nontrivial_pointer ptr) noexcept {
        return static_cast<bool>(ptr.ptr);
    }
    _CONSTEXPR20 friend bool operator<(nontrivial_pointer lhs, nontrivial_pointer rhs) noexcept {
        return lhs.ptr < rhs.ptr;
    }
    _CONSTEXPR20 friend bool operator<=(nontrivial_pointer lhs, nontrivial_pointer rhs) noexcept {
        return lhs.ptr <= rhs.ptr;
    }
    _CONSTEXPR20 friend bool operator>(nontrivial_pointer lhs, nontrivial_pointer rhs) noexcept {
        return lhs.ptr > rhs.ptr;
    }
    _CONSTEXPR20 friend bool operator>=(nontrivial_pointer lhs, nontrivial_pointer rhs) noexcept {
        return lhs.ptr >= rhs.ptr;
    }
};

template <class T, bool IsVoid = is_void_v<T>>
struct impl_pointer_to {
    static constexpr nontrivial_pointer<T> pointer_to(T& r) noexcept {
        return nontrivial_pointer<T>(addressof(r));
    }
};

template <class T>
struct impl_pointer_to<T, true> {
    // no pointer_to for void
};

template <class T>
struct std::pointer_traits<nontrivial_pointer<T>> : public impl_pointer_to<T> {
    using pointer = nontrivial_pointer<T>;
    using element_type = T;
    using difference_type = ptrdiff_t;

    template <class U>
    using rebind = nontrivial_pointer<U>;
};

template <class T>
struct std::iterator_traits<nontrivial_pointer<T>> {
    using iterator_category = random_access_iterator_tag;
    using difference_type = ptrdiff_t;
    using value_type = remove_const_t<T>;
    using reference = add_lvalue_reference_t<T>;
    using pointer = nontrivial_pointer<T>;
};

template <class T, class POCCA, class POCMA, class POCS, class EQUAL>
class MyAlloc {
private:
    size_t _id;

    [[nodiscard]] constexpr size_t equal_id() const noexcept {
        return is_always_equal::value ? 10 : _id;
    }

public:
    [[nodiscard]] constexpr size_t id() const noexcept {
        return _id;
    }

    using value_type = T;
    using pointer = nontrivial_pointer<T>;

    using propagate_on_container_copy_assignment = POCCA;
    using propagate_on_container_move_assignment = POCMA;
    using propagate_on_container_swap = POCS;
    using is_always_equal = EQUAL;

    constexpr explicit MyAlloc(const size_t _id_) : _id(_id_) {}

    template <class U>
    constexpr MyAlloc(const MyAlloc<U, POCCA, POCMA, POCS, EQUAL>& other) noexcept : _id(other.id()) {}

    template <class U>
    [[nodiscard]] constexpr bool operator==(const MyAlloc<U, POCCA, POCMA, POCS, EQUAL>& other) const noexcept {
        return equal_id() == other.equal_id();
    }

    template <class U>
    [[nodiscard]] constexpr bool operator!=(const MyAlloc<U, POCCA, POCMA, POCS, EQUAL>& other) const noexcept {
        return equal_id() != other.equal_id();
    }

    [[nodiscard]] constexpr pointer allocate(const size_t numElements) {
        return pointer(allocator<T>{}.allocate(numElements + equal_id()) + equal_id());
    }

    constexpr void deallocate(pointer const first, const size_t numElements) noexcept {
        allocator<T>{}.deallocate(_Unfancy(first - equal_id()), numElements + equal_id());
    }
};

template <class T>
using StationaryAlloc = MyAlloc<T, false_type, false_type, false_type, false_type>;

_CONSTEXPR20 bool problematic() {
    vector<int, StationaryAlloc<int>> src(StationaryAlloc<int>(11));
    vector<int, StationaryAlloc<int>> dst(move(src)); // <<<

    return true;
}

int main() {
#if _HAS_CXX20
    static_assert(problematic());
#endif // _HAS_CXX20
}
```
</details>

Comment (achabense) [reply tests/std/tests/VSO_0000000_allocator_propagation/test.cpp:460]: Min repro; I'm doubting this is a compiler bug:
```cpp
#include <memory>
#include <type_traits>

using namespace std;

class test_leak {
    char* ptr;

public:
    test_leak(const test_leak&) = delete;
    test_leak& operator=(const test_leak&) = delete;

    constexpr test_leak() noexcept /* terminates */ : ptr(allocator<char>{}.allocate(1)) {}
    constexpr ~test_leak() {
        allocator<char>{}.deallocate(ptr, 1);
    }
};

template <class T>
class nontrivial_pointer : private test_leak {
public:
    T* ptr;
    _CONSTEXPR20 nontrivial_pointer() noexcept : ptr(nullptr) {}
    _CONSTEXPR20 explicit nontrivial_pointer(T* ptr_) noexcept : ptr(ptr_) {}
    _CONSTEXPR20 /*implicit*/ nontrivial_pointer(nullptr_t) noexcept : ptr(nullptr) {}

    _CONSTEXPR20 nontrivial_pointer(const nontrivial_pointer& other) noexcept : ptr(other.ptr) {}
    template <class U, enable_if_t<is_convertible_v<U*, T*>, int> = 0>
    _CONSTEXPR20 nontrivial_pointer(const nontrivial_pointer<U>& other) noexcept : ptr(other.ptr) {}
    _CONSTEXPR20 nontrivial_pointer& operator=(const nontrivial_pointer& other) noexcept {
        ptr = other.ptr;
        return *this;
    }

    _CONSTEXPR20 ~nontrivial_pointer() = default;

    //...
};

using pointer = nontrivial_pointer<int>;

struct al {};

struct val {
    constexpr val() :a(), b(), c() {}
    constexpr val(pointer a_, pointer b_, pointer c_) : a(a_), b(b_), c(c_) {}

    pointer a;
    pointer b;
    pointer c;
};

struct vec {
    constexpr vec(const al& a)noexcept :cp(_One_then_variadic_args_t{}, a) {}
#if 0
    // problematic, allocated storage not being deallocated
    constexpr vec(const vec& v)noexcept : cp(_One_then_variadic_args_t{}, v.cp._Get_first(),
        pointer(v.cp._Myval2.a),
        pointer(v.cp._Myval2.b),
        pointer(v.cp._Myval2.c)
    ) {}
#else
    // ok:
    constexpr vec(const vec& v)noexcept : cp(_One_then_variadic_args_t{}, v.cp._Get_first(),
        v.cp._Myval2.a,
        v.cp._Myval2.b,
        v.cp._Myval2.c
    ) {}
#endif
    // ok, though same as the problematic ctor:
    constexpr void ok2() {
        _Compressed_pair<al, val> cp(_One_then_variadic_args_t{}, al{});
        _Compressed_pair<al, val> cp2(_One_then_variadic_args_t{}, cp._Get_first(),
            pointer(cp._Myval2.a),
            pointer(cp._Myval2.b),
            pointer(cp._Myval2.c)
        );
    }

    _Compressed_pair<al, val> cp;
};

// will turn problematic if using the "#if 0" ctor.
// ok2() is always successful.
_CONSTEXPR20 bool test() {
    vec a(al{});
    vec b(a);

    b.ok2();
    return true;
}

int main() {
#if _HAS_CXX20
    static_assert(test());
#endif // _HAS_CXX20
}
```

Comment (achabense) [reply tests/std/tests/VSO_0000000_allocator_propagation/test.cpp:460]: This commit tries to put off leak check to runtime: https://github.com/microsoft/STL/commit/3f63805ae4074c2aa0bcb409550333f9fe259731.

Comment (achabense) [reply tests/std/tests/VSO_0000000_allocator_propagation/test.cpp:460]: Here is another version that restores `test_sequence_move_ctor` by trying to put off leak check to runtime: https://github.com/microsoft/STL/commit/3f63805ae4074c2aa0bcb409550333f9fe259731.

Comment (achabense) [reply tests/std/tests/VSO_0000000_allocator_propagation/test.cpp:460]: And optionally, I think it will be much easier to only fix the initial bug (`operator=(const&)` in this pr (so the test coverage will be non-trivial pointer and constexpr `test_string`, without bothering with `test_leak` etc), and make another pr to deal with `_Take_contents`) I think the main difficulty is really constexpr test coverage for leakage instead of the bugfix...

File: tests/std/tests/VSO_0000000_allocator_propagation/test.cpp (hunk 1 above)
Comment (CaseyCarter) [reply tests/std/tests/VSO_0000000_allocator_propagation/test.cpp:69]: Do you mind minimizing this so we can report the bug to EDG?

Comment (achabense) [reply tests/std/tests/VSO_0000000_allocator_propagation/test.cpp:69]: Yeah, here it is:
`"/nologo" "/Od" "/W4" "/w14061" "/w14242" "/w14265" "/w14582" "/w14583" "/w14587" "/w14588" "/w14749" "/w14841" "/w14842" "/w15038" "/w15214" "/w15215" "/w15216" "/w15217" "/w15262" "/sdl" "/WX" "/D_ENABLE_STL_INTERNAL_CHECK" "/bigobj" "/FIforce_include.hpp" "/w14365" "/w15267" "/D_ENFORCE_FACET_SPECIALIZATIONS=1" "/D_STL_CALL_ABORT_INSTEAD_OF_INVALID_PARAMETER" "/BE" "/c" "/EHsc" "/MTd" "/std:c++latest" "/permissive-" "/w14640" "/Zc:threadSafeInit-"`
```cpp
#include<cassert>

template<class T>
struct ptr {
    T* p;

    constexpr explicit operator bool() {
        //return static_cast<bool>(p); // ok.
        return p != nullptr; // problematic.
    }
};


constexpr bool problematic() {
    int arr[10]{};
    ptr p{ arr + 10 };
    assert(p);

    return true;
}

int main() {
    static_assert(problematic());
}
```

Comment (CaseyCarter) [reply tests/std/tests/VSO_0000000_allocator_propagation/test.cpp:69]: Awesome - reported as VSO-1888157 to the MSFT-internal EDG team.

Comment (CaseyCarter) [reply tests/std/tests/VSO_0000000_allocator_propagation/test.cpp:69]:
```suggestion
#ifdef __EDG__ // TRANSITION, VSO-1888157
        return static_cast<bool>(ptr);
#else // ^^^ workaround / no workaround vvv
        return ptr != nullptr;
#endif // ^^^ no workaround ^^^
```

File: tests/std/tests/VSO_0000000_allocator_propagation/test.cpp (hunk 7 above)
Comment (StephanTLavavej) [reply tests/std/tests/VSO_0000000_allocator_propagation/test.cpp:464]: With `#if 0` changed to `#if 1`, MSVC rejects but Clang accepts your test case; this seems like a compiler bug to me.

Reduced to

```
C:\Temp>type meow.cpp
```
```cpp
#include <memory>

struct test_leak {
    char* ptr;

    constexpr test_leak(int, int) : ptr(std::allocator<char>{}.allocate(1)) {}

    test_leak(const test_leak&)            = delete;
    test_leak& operator=(const test_leak&) = delete;

    constexpr ~test_leak() {
        std::allocator<char>{}.deallocate(ptr, 1);
    }
};

struct holder1 {
    constexpr holder1(const test_leak&) {}
};

struct holder2 {
    holder1 h1;

    constexpr holder2() : h1(test_leak(11, 22)) {}
};

constexpr bool test() {
    holder2 h2;
    return true;
}

int main() {
    static_assert(test());
}
```
```
C:\Temp>cl /EHsc /nologo /W4 /std:c++20 meow.cpp
meow.cpp
meow.cpp(32): error C2131: expression did not evaluate to a constant
meow.cpp(6): note: failure was caused by allocated storage not being deallocated

C:\Temp>clang-cl /EHsc /nologo /W4 /std:c++20 meow.cpp

C:\Temp>
```

and reported VSO-1888462.

**Review by StephanTLavavej — APPROVED** [review]

File: stl/inc/xstring [hunk 9]
```diff
@@ -3052,8 +3052,9 @@ private:
 
         if (_Right_data._Large_mode_engaged()) { // steal buffer
             _Construct_in_place(_My_data._Bx._Ptr, _Right_data._Bx._Ptr);
-            _Right_data._Bx._Ptr = nullptr;
```
Comment (achabense) [inline stl/inc/xstring:3055]: emm, for clarity it might be better just to put the correction `_Destroy_in_place(_Right_data._Bx._Ptr);` in this original place. apparently not worth resetting the testings though...

**Comment by achabense** [comment]
https://github.com/microsoft/STL/blob/8f67ece4a654625220642c92fa029a5cfc77afa8/stl/inc/xstring#L2963-L2966
It seems this place also lacks `_Destroy_in_place`? Not caught by the test as it is interaction part with `basic_stringbuf`.

File: tests/std/tests/VSO_0000000_allocator_propagation/test.cpp [hunk 10]
```diff
@@ -307,7 +462,9 @@ _CONSTEXPR20 bool test_sequence() {
     test_sequence_copy_assign<Sequence, CopyAlloc<int>>(11, 22, 11); // POCCA, non-equal allocators
     test_sequence_copy_assign<Sequence, CopyEqualAlloc<int>>(11, 22, 11); // POCCA, always-equal allocators
 
+#if defined(__clang__) || defined(__EDG__) // TRANSITION, VSO-1888462
     test_sequence_move_ctor<Sequence>();
+#endif // ^^^ no workaround ^^^
```
Comment (achabense) [inline tests/std/tests/VSO_0000000_allocator_propagation/test.cpp:467]: I think in compiler bug case we can still keep this test at runtime.

Comment (StephanTLavavej) [reply tests/std/tests/VSO_0000000_allocator_propagation/test.cpp:467]: Great point, I'll validate and push.

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
The product code changes are very clear and the new test coverage provides sufficient confidence that this is correct; I think we can merge this without a second maintainer approval.

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Review by CaseyCarter — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Thanks for thoroughly fixing this bug! :lady_beetle: :hammer_and_wrench: :white_check_mark:

File: tests/std/tests/VSO_0000000_allocator_propagation/test.cpp (hunk 1 above)
Comment (CaseyCarter) [reply tests/std/tests/VSO_0000000_allocator_propagation/test.cpp:71]: > Awesome - reported as [VSO-1888157](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1888157) to the MSFT-internal EDG team.

Late notification: this was fixed for VS 2022 17.9.
