### PR TITLE
Fix filesystem::remove to remove readonly files also

### LINKED ISSUE #1511: <filesystem>: remove does not delete read-only files
**Descibe the bug**
std::filesystem::remove() does not remove read-only files
The issue with this is that STL sets the FILE_ATTRIBUTE_READONLY bit when we remove the write permissions for a file.
remove should remove such files also.

**Command-line test case**
```
C:\Temp>type repro.cpp
#include <filesystem>
#include <iostream>
#include <fstream>

using namespace std;
namespace fs = std::filesystem;

int main()
{
	fs::path testfile("testfile");

	// Create the file
	fstream file;
	file.open(testfile, ios::out);
	file.close();

	// Remove write permissions
	fs::permissions(testfile,
				fs::perms::owner_write | fs::perms::group_write | fs::perms::others_write,
				fs::perm_options::remove);

	error_code E;
	//POSIX remove should remove this as well.
	fs::remove(testfile, E);
	//Should print '5 Access is denied.'
	cout << E.value() << " " << E.message() << endl;
}


C:\Temp>cl /EHsc /std:c++17 /W4 /WX .\repro.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.23.28019.1 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

repro.cpp
Microsoft (R) Incremental Linker Version 14.23.28019.1
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:repro.exe
repro.obj

C:\Temp>.\repro.exe
5 Access is denied.
```

**Expected behavior**
std::filesystem::remove() should remove 'testfile'

**STL version**
Versions that support std::filesystem

### PR DESCRIPTION
**Pull request by SibiSiddharthan**
Fixes #1511 
Remove Readonly Files also.

### CODE REVIEW

File: stl/inc/filesystem [hunk 1]
```diff
@@ -3588,8 +3588,16 @@ namespace filesystem {
     inline bool remove(const path& _Target) {
```
Comment (StephanTLavavej) [inline stl/inc/filesystem:3588]: Test coverage should be added. It would be fine to add it here:

https://github.com/microsoft/STL/blob/54cce5e15e295181e1587d2b4e2e5df50faa0702/tests/std/tests/P0218R1_filesystem/test.cpp#L3263

File: stl/inc/filesystem [hunk 2]
```diff
@@ -3588,8 +3588,16 @@ namespace filesystem {
...
         // remove file _Target (even if it is a directory); returns whether the file was removed
         // note !exists(_Target) is not an error, and merely returns false
-        const auto _Result = __std_fs_remove(_Target.c_str());
+        auto _Result = __std_fs_remove(_Target.c_str());
         if (_Result._Error != __std_win_error::_Success) {
+            if (_Result._Error == __std_win_error::_Access_denied) {
+                // Try to remove the ReadOnly Attribute and try again
+                const auto _Perm_change_err = __std_fs_change_permissions(_Target.c_str(), false, false);
+                if (_Perm_change_err != __std_win_error::_Success) {
+                    _Throw_fs_error("remove", _Perm_change_err, _Target);
```
Comment (StephanTLavavej) [inline stl/inc/filesystem:3597]: Previously, the exception-throwing and `error_code` overloads had repeated implementations (instead of one being implemented in terms of the other) because those implementations were small. Now that significant additional logic is needed to handle read-only files, we should centralize the logic. I recommend making the `error_code` implementation the fundamental one, and then moving the exception-throwing implementation below, so the exception-throwing overload can call the `error_code` overload.

Example above:
https://github.com/microsoft/STL/blob/54cce5e15e295181e1587d2b4e2e5df50faa0702/stl/inc/filesystem#L3523-L3532

File: stl/inc/filesystem [hunk 3]
```diff
@@ -3599,8 +3607,17 @@ namespace filesystem {
     inline bool remove(const path& _Target, error_code& _Ec) noexcept {
         // remove file _Target (even if it is a directory); returns whether the file was removed
         // note !exists(_Target) is not an error, and merely returns false
-        const auto _Result = __std_fs_remove(_Target.c_str());
-        _Ec                = _Make_ec(_Result._Error);
+        auto _Result = __std_fs_remove(_Target.c_str());
+        if (_Result._Error == __std_win_error::_Access_denied) {
+            // Try to remove the ReadOnly Attribute and try again
```
Comment (StephanTLavavej) [inline stl/inc/filesystem:3612]: Should this phrase be capitalized? I would expect:
```suggestion
            // Try to remove the read-only attribute and try again
```

**Review by StephanTLavavej — CHANGES_REQUESTED** [review]

File: stl/inc/filesystem (hunk 3 above)
Comment (SibiSiddharthan) [reply stl/inc/filesystem:3612]: Will change it

File: stl/inc/filesystem (hunk 1 above)
Comment (SibiSiddharthan) [reply stl/inc/filesystem]: Have added the test cases

File: stl/inc/filesystem (hunk 2 above)
Comment (SibiSiddharthan) [reply stl/inc/filesystem]: Have made the suggested changes

File: stl/inc/filesystem [hunk 4]
```diff
@@ -3585,23 +3585,33 @@ namespace filesystem {
...
+    inline bool remove(const path& _Target) {
         // remove file _Target (even if it is a directory); returns whether the file was removed
         // note !exists(_Target) is not an error, and merely returns false
-        const auto _Result = __std_fs_remove(_Target.c_str());
-        _Ec                = _Make_ec(_Result._Error);
-        return _Result._Removed;
+        error_code _Ec;
+        const auto _Result = _STD filesystem::remove(_Target, _Ec);
+        if (static_cast<__std_win_error>(_Ec.value()) != __std_win_error::_Success) {
+            _Throw_fs_error("remove", static_cast<__std_win_error>(_Ec.value()), _Target);
```
Comment (StephanTLavavej) [inline stl/inc/filesystem:3611]: While this is correct, I believe that it can be improved.

Calling `_Throw_fs_error` with `__std_win_error` will call `_Make_ec` again. Calling `_Throw_fs_error` with the `error_code` is less verbose and more efficient:

https://github.com/microsoft/STL/blob/ac4fde764ae716512bdd67e0e9577bd53947bc3d/stl/inc/filesystem#L1843-L1845
https://github.com/microsoft/STL/blob/ac4fde764ae716512bdd67e0e9577bd53947bc3d/stl/inc/filesystem#L1852-L1854

Additionally, the `error_code` can be directly tested to detect errors, as `is_empty` does above:

https://github.com/microsoft/STL/blob/ac4fde764ae716512bdd67e0e9577bd53947bc3d/stl/inc/filesystem#L3527-L3528

So this can follow the same pattern:

```suggestion
        if (_Ec) {
            _Throw_fs_error("remove", _Ec, _Target);
```

**Review by StephanTLavavej — COMMENTED** [review]
Thanks! I noticed that a couple of lines could be simplified, and verified that the tests continue to pass, so I'll push a change.

**Review by StephanTLavavej — APPROVED** [review]

**Review by mnatsuhara — APPROVED** [review]

**Comment by BillyONeal** [comment]
This seems wrong to me because we map FILE_ATTRIBUTE_READONLY to the writiable bit, so if someone uses permisions() to remove the write bit, they could expect that remove() would fail, but after this PR it succeeds.

**Comment by BillyONeal** [comment]
(That is to say, this manifestation of `remove()` seems inconsistent with how we implement `permissions()` in addition to making the call no longer atomic)

**Comment by BillyONeal** [comment]
Additionally this creates a problem if you get ERROR_ACCESS_DENIED for another reason, such as NTFS permissions. This will end up removing the FILE_ATTRIBUTE_READONLY bit, then still get ERROR_ACCESS_DENIED, reporting a failure, but the filesystem is damaged because the attribute was removed.

Here's an example repro of the problem: https://gist.github.com/BillyONeal/dbd60eda8620d17772caebd9b17b0df6

You might be able to resolve this correctly over in `__std_fs_remove` ( https://github.com/microsoft/STL/blob/ac4fde764ae716512bdd67e0e9577bd53947bc3d/stl/src/filesystem.cpp#L493 ) by doing something like:

```
    _STD _Fs_file _Handle(_Target, __std_access_rights::_Delete |  __std_access_rights::_File_read_attributes |  __std_access_rights::_File_write_attributes, _Flags, &_Last_error);
    if (_Last_error == __std_win_error::_Success) {
        // remove the readonly bit using _Handle the same way __std_fs_change_permissions does
    } else if (_Last_error == __std_win_error::_Access_denied) {
        // can't edit the readonly bit, try to open with just delete
        _Handle = _Fs_file(_Target, __std_access_rights::_Delete, &_Last_error)
    }

    if (_Last_error != __std_win_error::_Success) { return; }

    // set the deletion disposition on _Handle as before
```

**Review by StephanTLavavej — CHANGES_REQUESTED** [review]
@BillyONeal (who originally worked on `<filesystem>`) explained this issue to me, and (after I explained that POSIX indeed allows non-writeable files to be removed), I agree that a different approach appears to be necessary here. Although it seems obscure/difficult to have parent directory permissions that would allow a file's readonly bit to be cleared while file deletion still fails, in that scenario we're left with a permanent change to the file's permissions. (This is separate from any question of "filesystem races", which the STL technically does not need to worry about.)

Billy's proposed change to `filesystem.cpp` instead of `<filesystem>` sounds like it would work, and would not require an invasive overhaul. I think that manually verifying that his unusual repro is fixed would be sufficient; we don't need to add automated coverage for those weird directory permissions.

Please let us know if you'd like us to investigate the proposed change; I realize that asking for a total rewrite of the product code fix is a lot for a first-time contribution. :smile_cat:

**Comment by SibiSiddharthan** [comment]
@BillyONeal Thanks for pointing this out. In your proposed change, I think it is also important to re-set the FILE_ATTRIBUTE_READONLY bit , if we fail to delete the file even after clearing it to maintain the integrity of the file system. This is currently not possible with the current implementation of `__std_fs_remove`. As noted by @CaseyCarter, in the #1511 discussion, we should avoid doing more work than necessary to delete a normal file(which is created by 'New Text Document'), which is much more in number compared to these special cases. 

The change I propose is 
```cpp
auto _Result = __std_fs_remove(_Target.c_str());
        if (_Result._Error == __std_win_error::_Access_denied) {
            // check if read-only bit is set
            // Clear it if it is set, otherwise return
            const auto _Perm_change_err = __std_fs_change_permissions(_Target.c_str(), false, false);
            if (_Perm_change_err != __std_win_error::_Success) {
                _Ec = _Make_ec(_Perm_change_err);
                return false;
            }
            _Result = __std_fs_remove(_Target.c_str());
           // If we fail again re-set the read-only bit.
         
        }
```

**Comment by BillyONeal** [comment]
>The change I propose is [...]

The problem with that change is that it `CreateFile`s again; you want to reuse the same handle.

**Comment by SibiSiddharthan** [comment]
> The problem with that change is that it `CreateFile`s again; you want to reuse the same handle.

Yeah, 5 calls in the worst case. Is there way to pass the `HANDLE`s from function to function without modifying xfilesystem_abi.h

Then, how do we solve the issue of re-setting the FILE_ATTRIBUTE_READONLY bit, if we fail to delete the file after clearing the same?

I really think that using `DeleteFile` and `RemoveDirectory` would be better here. It should avoid the `CreateFile` calls. (Please correct me if I am missing something here.)

**Comment by BillyONeal** [comment]
> Is there way to pass the HANDLEs from function to function without modifying xfilesystem_abi.h

**Comment by BillyONeal** [comment]
> Is there way to pass the HANDLEs from function to function without modifying xfilesystem_abi.h

No. You need to make this change in `__std_fs_remove` itself.

> I really think that using DeleteFile and RemoveDirectory would be better here. 

DeleteFile and RemoveDirectory internally call CreateFile but enforce additional restrictions (that the target is a file/directory) that we don't want.

All deletions on NT work like:

1. Open the file.
2. Set the DELETE_ON_CLOSE flag.
3. Close the file.

>Then, how do we solve the issue of re-setting the FILE_ATTRIBUTE_READONLY bit, if we fail to delete the file after clearing the same?

Put it back on with SetFileInformationByHandle(Ex), the same way you remove it.

**Comment by SibiSiddharthan** [comment]
This turned out to be quite big. I am reusing the same HANDLE for the file operations. Waiting for a review.

**Comment by SibiSiddharthan** [comment]
> > I really think that using DeleteFile and RemoveDirectory would be better here.
> 
> DeleteFile and RemoveDirectory internally call CreateFile but enforce additional restrictions (that the target is a file/directory) that we don't want.
> 
> All deletions on NT work like:
> 
> 1. Open the file.
> 2. Set the DELETE_ON_CLOSE flag.
> 3. Close the file.

Thanks for the information 😄

**Comment by BillyONeal** [comment]
Hmmm this is interesting: https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntddk/ns-ntddk-_file_disposition_information_ex:

`FILE_DISPOSITION_IGNORE_READONLY_ATTRIBUTE`

Maybe you can just supply that along with our existing `FILE_FLAG_POSIX_SEMANTICS` and it'll just work on current OSes?

**Comment by SibiSiddharthan** [comment]
This looks really neat.
I can confirm it works on 19H2 (the version I am using).
But are you sure it works for previous versions of Windows?

**Comment by BillyONeal** [comment]
It explicitly *does not* work on previous versions of Windows, but the POSIX semantics feature doesn't either.

**Comment by SibiSiddharthan** [comment]
After looking at `WinBase.h`, I found this
```c
#if (_WIN32_WINNT >= _WIN32_WINNT_WIN10_RS5)
#define FILE_DISPOSITION_FLAG_IGNORE_READONLY_ATTRIBUTE  0x00000010
#endif
```
It looks like this works for versions after 1809 only (this is pretty recent).

```

**Comment by BillyONeal** [comment]
>It looks like this works for versions after 1809 only (this is pretty recent).

Makes sense. So you could try once with that, then remove it if that fails and try again, similar to what __std_fs_remove already does for the case that FILE_FLAG_POSIX_SEMANTICS are unavailable.

**Comment by SibiSiddharthan** [comment]
> > It looks like this works for versions after 1809 only (this is pretty recent).
> 
> Makes sense. So you could try once with that, then remove it if that fails and try again, similar to what __std_fs_remove already does for the case that FILE_FLAG_POSIX_SEMANTICS are unavailable.

I have made the suggested changes.
How do I test this on versions older than 1809?
One more thing why do we do this `#undef _SetFileInformationByHandle` . I found only one occurrence of this in the entire source tree

**Comment by BillyONeal** [comment]
> One more thing why do we do this `#undef _SetFileInformationByHandle` . I found only one occurrence of this in the entire source tree

It's a leftover from https://github.com/microsoft/STL/pull/1194/ (where the `#define _SetFileInformationByHandle` got deleted).

**Comment by SibiSiddharthan** [comment]
> > One more thing why do we do this `#undef _SetFileInformationByHandle` . I found only one occurrence of this in the entire source tree
> 
> It's a leftover from #1194 (where the `#define _SetFileInformationByHandle` got deleted).

I'll remove it in the next push

**Comment by SibiSiddharthan** [comment]
Hi there,
@BillyONeal, @StephanTLavavej any updates regarding this pull request.

**Comment by CaseyCarter** [comment]
> Hi there,
> @BillyONeal, @StephanTLavavej any updates regarding this pull request.

Sorry for the delay: we're in a fairly heavy crunch to get C++20 finished, and having trouble finding time to look at much of anything that isn't C++20 feature work. I've moved this back into a Review status so folks will know it's ready for another look, but I can't guarantee _when_ exactly that will happen. Thanks for understanding, I assure you we haven't forgotten this PR ;)

**Comment by SibiSiddharthan** [comment]
Thanks for the update 😃

File: stl/src/filesystem.cpp [hunk 5]
```diff
@@ -503,36 +499,124 @@ _Success_(return == __std_win_error::_Success) __std_win_error
...
+    _STD _Fs_file _Handle(_Target,
+        __std_access_rights::_Delete | __std_access_rights::_File_read_attributes
+            | __std_access_rights::_File_write_attributes,
+        _Flags, &_Last_error);
+    if (_Last_error == __std_win_error::_Success) {
+        _Able_to_change_attributes = true;
+    } else if (_Last_error == __std_win_error::_Access_denied) {
+        // change the underlying HANDLE of _Handle
+        // this might not be a good way of doing it (comment to be removed post review)
+        _Last_error = __std_fs_open_handle(&_Handle._Raw, _Target, __std_access_rights::_Delete, _Flags);
```
Comment (StephanTLavavej) [inline stl/src/filesystem.cpp:546]: I *think* this is OK, because when `_Fs_file`'s constructor calls `__std_fs_open_handle` (which calls `__vcp_CreateFile`) and that fails, [the handle is](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createfilew#return-value) `INVALID_HANDLE_VALUE`, so the destructor will do nothing. So, there's no concern about leaking a handle by overwriting `_Handle._Raw`.

I think this deserves a comment so retaining the first line `// change the underlying HANDLE of _Handle` would be good, although the second line should of course be removed.

File: stl/src/filesystem.cpp [hunk 6]
```diff
@@ -503,36 +499,124 @@ _Success_(return == __std_win_error::_Success) __std_win_error
...
+        if (_Last_error != __std_win_error::_Success) {
+            return {false, _Last_error};
+        }
+    } else {
+        return {false, _Translate_not_found_to_success(_Last_error)};
+    }
+
+    // For Windows 10 1809 or later we have this flag -> FILE_DISPOSITION_FLAG_IGNORE_READONLY_ATTRIBUTE 0x10
+    // This flag also deletes read-only files
+    // NOTE: This is currently undocumented in MSDN. Refer WinBase.h for declarations
```
Comment (StephanTLavavej) [inline stl/src/filesystem.cpp:556]:
```suggestion
    // This flag also deletes read-only files.
    // NOTE: This is currently undocumented in MSDN. Refer to WinBase.h for declarations.
```

File: stl/src/filesystem.cpp [hunk 7]
```diff
@@ -503,36 +499,124 @@ _Success_(return == __std_win_error::_Success) __std_win_error
...
+
+    // The following bits are set here
+    // FILE_DISPOSITION_FLAG_DELETE, FILE_DISPOSITION_FLAG_POSIX_SEMANTICS,
+    // FILE_DISPOSITION_FLAG_IGNORE_READONLY_ATTRIBUTE
+    _File_disposition_info_ex _Info_ex{0x3 | 0x10};
+    constexpr auto _FileDispositionInfoExClass = static_cast<FILE_INFO_BY_HANDLE_CLASS>(21);
+    if (SetFileInformationByHandle(
+            reinterpret_cast<HANDLE>(_Handle._Get()), _FileDispositionInfoExClass, &_Info_ex, sizeof(_Info_ex))) {
```
Comment (StephanTLavavej) [inline stl/src/filesystem.cpp:564]: I believe that `reinterpret_cast<HANDLE>` is unnecessary because `HANDLE` is `void*`. (We appear to use `_Handle._Get()` without a cast elsewhere.)

File: stl/src/filesystem.cpp [hunk 8]
```diff
@@ -503,36 +499,124 @@ _Success_(return == __std_win_error::_Success) __std_win_error
...
+    case __std_win_error::_Not_supported:
+        break;
+    default:
+        // If we fail for reasons other than those mentioned above just return to the caller
+        return {false, _Last_error};
+    }
 
-#undef _SetFileInformationByHandle
+    // code path for versions older than 1809
+    _Last_error = _Set_delete_flag(_Handle._Raw);
```
Comment (StephanTLavavej) [inline stl/src/filesystem.cpp:581]: I believe this should be `_Handle._Get()` since it doesn't need to modify the handle in-place.

File: stl/src/filesystem.cpp [hunk 9]
```diff
@@ -503,36 +499,124 @@ _Success_(return == __std_win_error::_Success) __std_win_error
...
+        }
+        // check if FILE_ATTRIBUTE_READONLY is set
+        if (_Basic_info.FileAttributes & FILE_ATTRIBUTE_READONLY) {
+            // try to remove FILE_ATTRIBUTE_READONLY
+            _Basic_info.FileAttributes ^= FILE_ATTRIBUTE_READONLY;
+            if (!SetFileInformationByHandle(_Handle._Get(), FileBasicInfo, &_Basic_info, sizeof(_Basic_info))) {
+                return {false, __std_win_error{GetLastError()}};
+            }
+            // removed FILE_ATTRIBUTE_READONLY, now try to set the delete flag again
+            _Last_error = _Set_delete_flag(_Handle._Raw);
```
Comment (StephanTLavavej) [inline stl/src/filesystem.cpp:600]: Another occurrence that should be `_Handle._Get()`.

File: stl/src/filesystem.cpp [hunk 10]
```diff
@@ -503,36 +499,124 @@ _Success_(return == __std_win_error::_Success) __std_win_error
...
+            if (_Last_error == __std_win_error::_Success) {
+                return {true, __std_win_error::_Success};
+            } else if (_Last_error == __std_win_error::_Access_denied) {
+                // looks like we failed to set the delete flag, after clearing the FILE_ATTRIBUTE_READONLY flag
+                // perform rollback
+                _Basic_info.FileAttributes |= FILE_ATTRIBUTE_READONLY;
+                if (!SetFileInformationByHandle(_Handle._Get(), FileBasicInfo, &_Basic_info, sizeof(_Basic_info))) {
+                    return {false, __std_win_error{GetLastError()}};
+                }
+                return {false, __std_win_error{GetLastError()}};
```
Comment (StephanTLavavej) [inline stl/src/filesystem.cpp:610]: Is this intentional? On lines 599-600 we called
```cpp
            // removed FILE_ATTRIBUTE_READONLY, now try to set the delete flag again
            _Last_error = _Set_delete_flag(_Handle._Raw);
```
and (line 603) it failed with `_Last_error == __std_win_error::_Access_denied`. We've successfully restored `FILE_ATTRIBUTE_READONLY` (lines 606-607), so we need to report the `_Access_denied` error.

However, because our last Win32 API call was the successful `SetFileInformationByHandle` (line 607), I'm not sure if calling `GetLastError()` again is correct.

I could be missing something, but it seems that we should be using the stored value of `_Last_error` here.

**Review by StephanTLavavej — CHANGES_REQUESTED** [review]
Thanks! My apologies for how long it took to review this. I think the logic looks good; all that I found were fairly superficial issues and one concern about `GetLastError` state.

File: stl/src/filesystem.cpp [hunk 11]
```diff
@@ -485,16 +485,12 @@ _Success_(return == __std_win_error::_Success) __std_win_error
...
-    const _STD _Fs_file _Handle(_Target, __std_access_rights::_Delete, _Flags, &_Last_error);
-    if (_Last_error != __std_win_error::_Success) {
-        return {false, _Translate_not_found_to_success(_Last_error)};
-    }
+struct _File_disposition_info_ex {
+    DWORD _Flags;
+};
 
+[[nodiscard]] _Success_(return == __std_win_error::_Success) __std_win_error
+    _Set_delete_flag(_In_ __std_fs_file_handle _Handle) {
```
[the remark this answers is not in the document]
Comment (SibiSiddharthan) [reply stl/src/filesystem.cpp:493]: okay

File: stl/src/filesystem.cpp [hunk 12]
```diff
@@ -503,36 +499,124 @@ _Success_(return == __std_win_error::_Success) __std_win_error
...
     constexpr auto _FileDispositionInfoExClass = static_cast<FILE_INFO_BY_HANDLE_CLASS>(21);
-    if (SetFileInformationByHandle(_Handle._Get(), _FileDispositionInfoExClass, &_Info_ex, sizeof(_Info_ex))) {
-        return {true, __std_win_error::_Success};
+    if (SetFileInformationByHandle(
+            reinterpret_cast<HANDLE>(_Handle), _FileDispositionInfoExClass, &_Info_ex, sizeof(_Info_ex))) {
+        return __std_win_error::_Success;
     }
 
-    _Last_error = __std_win_error{GetLastError()};
+    const auto _Last_error = __std_win_error{GetLastError()};
```
[the remark this answers is not in the document]
Comment (SibiSiddharthan) [reply stl/src/filesystem.cpp:512]: I am personally not fond of `auto`, but I do see a lot of them used in the same file, so that is why I used it. Will change it.

File: stl/src/filesystem.cpp (hunk 6 above)
Comment (SibiSiddharthan) [reply stl/src/filesystem.cpp:556]: done

File: stl/src/filesystem.cpp (hunk 8 above)
Comment (SibiSiddharthan) [reply stl/src/filesystem.cpp:581]: okay

File: stl/src/filesystem.cpp (hunk 9 above)
Comment (SibiSiddharthan) [reply stl/src/filesystem.cpp:600]: fixed

File: stl/src/filesystem.cpp (hunk 7 above)
Comment (SibiSiddharthan) [reply stl/src/filesystem.cpp:564]: okay

File: stl/src/filesystem.cpp (hunk 10 above)
Comment (SibiSiddharthan) [reply stl/src/filesystem.cpp:610]: Yeah, you are correct, my bad.

File: stl/src/filesystem.cpp (hunk 11 above)
[the remark this answers is not in the document]
Comment (SibiSiddharthan) [reply stl/src/filesystem.cpp:493]: I think it is better to move this to the existing unnamed namespace in the beginning of this file.

**Comment by SibiSiddharthan** [comment]
@StephanTLavavej I have made the suggested changes. Please take a look.

**Comment by StephanTLavavej** [comment]
Note for the future - GitHub makes it difficult to incrementally review a PR when the branch is force-pushed, so we recommend avoiding force-pushes unless they're really necessary. (This may change in the future as GitHub's UI improves.)

Don't worry about this case, I'll be able to handle the changes 😸 - just thought I'd mention it.

File: stl/src/filesystem.cpp (hunk 8 above)
Comment (StephanTLavavej) [reply stl/src/filesystem.cpp:579]: Ah, thanks - I didn't look at the types closely! I think that this code is fine as-is then.

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
@SibiSiddharthan Looks great! I pushed a merge with `main` and a one-line change to simplify `_Last_error`'s initialization.

@mnatsuhara FYI, this PR has changed since you approved it back in January. It's still accomplishing the same goal, just in a different way. I know you're busy with NT validation at the moment - no action requested, just wanted to highlight this.

**Comment by StephanTLavavej** [comment]
Thanks for fixing this significant correctness bug - and congratulations on your first microsoft/STL commit! :smiley_cat: :rocket: :tada: This will ship in VS 2022 17.0 Preview 3.

**Comment by SibiSiddharthan** [comment]
@StephanTLavavej, @BillyONeal Thanks a lot for your help and support. 😃
