### PR TITLE
Fix race condition in iterator debug machinery

### LINKED ISSUE #2058: `_ITERATOR_DEBUG_LEVEL` 2: crash when iterators are destroyed while container is modified
Iterator debug level 2 does not support concurrent deletion and invalidation of iterators from two different threads. When this happens, the application crashes with a nullptr access inside of the STL.

**Command-line test case**
```
C:\Temp>type repro.cpp
#include <iostream>
#include <unordered_set>
#include <future>
#include <thread>
#include <chrono>
#include <vector>

int main() {
	// Create a one element set
	std::unordered_set<int> set;
	set.insert(0);

	// Create a list of iterators to later destroy
	std::vector<std::unordered_set<int>::iterator> iters;
	for (int i = 0; i < 1000; ++i)
		iters.push_back(set.begin());

	// Concurrently destroy iterators and invalidate iterators
	{
		auto destroyIters = std::async(std::launch::async,
			[&](){
				iters.clear();
			});

		auto invalidateIters = std::async(std::launch::async,
			[&](){
				set.clear();
			});
	}

	std::cout << "Programm behaved as expected, and did not crash" << std::endl;
}

C:\Temp>cl /EHsc /W4 /WX /Zi /DEBUG /MTd /D_ITERATOR_DEBUG_LEVEL=2 .\repro.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30038.1 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

repro.cpp
Microsoft (R) Incremental Linker Version 14.29.30038.1
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:repro.exe
/debug
repro.obj

C:\Temp>.\repro.exe
[application crashes]
```

**Expected behavior**
The application should not crash.

**STL version**
    ```
    Microsoft Visual Studio Professional 2019
    Version 16.10.2
    ```

### PR DESCRIPTION
**Pull request by miscco**
Fixes #2058

### CODE REVIEW

File: stl/inc/xmemory [hunk 1]
```diff
@@ -1183,30 +1174,39 @@ public:
...
+        _Adopt_unlocked(_Parent);
     }
 
     _CONSTEXPR20_CONTAINER void _Orphan_me_unlocked() noexcept {
-        _Iterator_base12** _Pnext = &_Myproxy->_Myfirstiter;
-        while (*_Pnext && *_Pnext != this) {
-            const auto _Temp = *_Pnext; // TRANSITION, VSO-1269037
-            _Pnext           = &_Temp->_Mynextiter;
-        }
+        if (_Myproxy) { // adopted, remove self from list
```
Comment (CaseyCarter) [inline stl/inc/xmemory:1199]: Ditto flip and early-return?

File: tests/std/tests/GH_002058_debug_iterator_race/test.cpp [hunk 2]
```diff
@@ -0,0 +1,51 @@
...
+    vector<typename container::iterator> iters;
+    iters.reserve(1000);
+    {
+        auto createIters = async(launch::async, [&]() {
+            for (int i = 0; i < 1000; ++i) {
+                iters.push_back(c.begin());
+            };
+        });
+
+        auto invalidateIters = async(launch::async, [&]() { c = container{}; });
```
Comment (CaseyCarter) [inline tests/std/tests/GH_002058_debug_iterator_race/test.cpp:39]: This modification to `c` conflicts with the access of `c` on line 35 - a data race - so this program has undefined behavior. I don't think any valid program can simultaneously "create iterators" and "invalidate container", so we probably don't need test coverage for such.

**Review by CaseyCarter — CHANGES_REQUESTED** [review]

File: tests/std/tests/GH_002058_debug_iterator_race/test.cpp (hunk 2 above)
Comment (AdamBucior) [reply tests/std/tests/GH_002058_debug_iterator_race/test.cpp:39]: Wouldn't copying iterators be valid? Also isn't there still a bug in `_Iterator_base12::operator=`?

Comment (CaseyCarter) [reply tests/std/tests/GH_002058_debug_iterator_race/test.cpp:39]: > Wouldn't copying iterators be valid?

Yes, I suppose it's worth having a test case that copies a stored iterator thousands of times while simultaneously invalidating all iterators.

> Also isn't there still a bug in `_Iterator_base12::operator=`?
If (as #2058 says) the bug is that "We check `_Myproxy` before we take the lock, which introduces a race condition." then every unguarded access of `_Myproxy` is a bug, isn't it?

Comment (miscco) [reply tests/std/tests/GH_002058_debug_iterator_race/test.cpp:39]: I believe we should aim for "works as before"

File: stl/inc/xmemory [hunk 3]
```diff
@@ -1183,30 +1174,39 @@ public:
 
 #if _ITERATOR_DEBUG_LEVEL == 2
 private:
-    _CONSTEXPR20_CONTAINER void _Adopt_unlocked(_Container_proxy* _Parent_proxy) noexcept {
-        if (_Myproxy) { // adopted, remove self from list
+    _CONSTEXPR20_CONTAINER void _Adopt_unlocked(const _Container_base12* _Parent) noexcept {
+        if (_Parent) {
```
[the remark this answers is not in the document]
Comment (miscco) [reply stl/inc/xmemory:1178]: It has an else rbanch but yeah, I believe it is clearer that way

File: tests/std/tests/GH_002058_debug_iterator_race/test.cpp (hunk 2 above)
Comment (miscco) [reply tests/std/tests/GH_002058_debug_iterator_race/test.cpp:41]: Also added fixes for the assignment operator and adopted the tests

File: stl/inc/xmemory [hunk 4]
```diff
@@ -1112,53 +1112,58 @@ public:
...
     _CONSTEXPR20_CONTAINER ~_Iterator_base12() noexcept {
-        _Orphan_me_v2();
+#ifdef __cpp_lib_constexpr_dynamic_alloc
+        if (_STD is_constant_evaluated()) {
+            _Orphan_me_unlocked();
+        } else
+#endif // __cpp_lib_constexpr_dynamic_alloc
+        {
+            _Orphan_me_locked();
+        }
```
Comment (miscco) [inline stl/inc/xmemory:1145]: Note this is a little bit of unrelated debug performance improvement, but I believe we should try to minimize the effect on debug performance

**Comment by miscco** [comment]
It seems we still have some race condition somewhere

**Comment by miscco** [comment]
Oh it turns out the bug is with `_ITERATOR_DEBUG_LEVEL != 2 ` where we do not have any locks and I believe indeed destroying the underlying container is a bug.

So I would change the test to only clear the container

File: tests/std/tests/GH_002058_debug_iterator_race/test.cpp [hunk 5]
```diff
@@ -0,0 +1,53 @@
+#include <chrono>
```
Comment (CaseyCarter) [inline tests/std/tests/GH_002058_debug_iterator_race/test.cpp:1]: This seems unused.

File: tests/std/tests/GH_002058_debug_iterator_race/test.cpp [hunk 6]
```diff
@@ -0,0 +1,53 @@
+#include <chrono>
+#include <future>
+#include <list>
+#include <set>
+#include <thread>
```
Comment (CaseyCarter) [inline tests/std/tests/GH_002058_debug_iterator_race/test.cpp:5]: Ditto unused.

**Review by CaseyCarter — CHANGES_REQUESTED** [review]

**Review by CaseyCarter — APPROVED** [review]

File: tests/std/tests/GH_002058_debug_iterator_race/test.cpp [hunk 7]
```diff
@@ -0,0 +1,51 @@
...
+
+    vector<typename container::iterator> iters(1000, c.begin());
+    {
+        auto destroyIters = async(launch::async, [&]() { iters.clear(); });
+
+        auto invalidateIters = async(launch::async, [&]() { c.clear(); });
+    }
+}
+
+// Concurrently create iterators and invalidate iterators
```
Comment (AdamBucior) [inline tests/std/tests/GH_002058_debug_iterator_race/test.cpp:22]: Repeating "iterators" sounds weird.
```suggestion
// Concurrently create and invalidate iterators
```

File: tests/std/tests/GH_002058_debug_iterator_race/test.cpp [hunk 8]
```diff
@@ -0,0 +1,51 @@
+#include <future>
+#include <list>
+#include <set>
+#include <vector>
+
+using namespace std;
+
+// Concurrently destroy iterators and invalidate iterators
```
Comment (miscco) [inline tests/std/tests/GH_002058_debug_iterator_race/test.cpp:8]:
```suggestion
// Concurrently destroy and invalidate iterators
```

**Review by CaseyCarter — APPROVED** [review]

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
@CaseyCarter @miscco @mnatsuhara FYI, I've pushed a series of commits, some significant.

**Comment by StephanTLavavej** [comment]
I'm going to add this to the next batch of changes to merge - please notify me if any further commits are pushed.

**Review by mnatsuhara — APPROVED** [review]
Sorry for the wait on this review!  This looks good to me though 🥳

**Review by CaseyCarter — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Thanks for fixing this high priority bug! :beetle: :smile_cat: :tada:
