### PR TITLE
<random>: Fix parameter initialization of piecewise_constant_distribution and piecewise_linear_distribution

### LINKED ISSUE #950: <random>: piecewise_linear_distribution is still broken
**Describe the bug**

`piecewise_linear_distribution` doesn't produce the correct random number distribution.

**Command-line test case**

```
G:\Temp>type devcom_421634.cpp
#include <cstdio>
#include <iterator>
#include <random>

using namespace std;

int main() {
    constexpr double intervals[] = {0, 1, 5};
    constexpr double weights[]   = {0, 1, 0};
    constexpr double x           = 2;
    constexpr double probability = 0.55;
    constexpr int total          = 1'000'000;

    piecewise_linear_distribution<> distribution(begin(intervals), end(intervals), begin(weights));
    mt19937 generator;

    int count = 0;
    for (int i = 0; i < total; ++i) {
        if (distribution(generator) < x) {
            ++count;
        }
    }

    const double frequency = static_cast<double>(count) / total;

    printf("Expected probability = %f\n", probability);
    printf("Actual frequency     = %f (%d / %d)\n", frequency, count, total);
}

G:\Temp>cl /EHsc /W4 /WX devcom_421634.cpp
用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.26.28806 版
版权所有(C) Microsoft Corporation。保留所有权利。

devcom_421634.cpp
Microsoft (R) Incremental Linker Version 14.26.28806.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:devcom_421634.exe
devcom_421634.obj

G:\Temp>.\devcom_421634.exe
Expected probability = 0.550000
Actual frequency     = 0.718845 (718845 / 1000000)
```

**STL version**

```
Microsoft Visual Studio Community 2019
版本 16.6.3
```

**Additional context**

Also tracked on Developer Community as DevCom-421634 and by Microsoft-internal VSO-115939 / [AB#115939](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/115939).

### LINKED ISSUE #1084: <random>: std::piecewise_linear_distribution incorrectly normalizes densities
**Describe the bug**
A std::piecewise_linear_distribution is described as accepting discrete pairs of values and densities. The densities are normalized such that the distribution becomes valid (specifically the distribution integrates to 1.0).

**Command-line test case**
```
C:\Temp>type repro.cpp

#include <array>
#include <iostream>
#include <random>

int main()
{
    std::array<double, 2> values{ 5.0, 10.0 };
    std::array<double, 2> densities{ 0.0, 1.0 };

    std::piecewise_linear_distribution<double> dist(values.begin(), values.end(), densities.begin());
    std::cout << "x:    " << dist.intervals()[0] << " to " << dist.intervals()[1] << '\n'
              << "p(x): " << dist.densities()[0] << " to " << dist.densities()[1];
}

C:\Temp>cl /EHsc /W4 /WX .\repro.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.26.28806 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

repro.cpp
Microsoft (R) Incremental Linker Version 14.26.28806.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:repro.exe
repro.obj

C:\Temp>.\repro.exe
x: 5 to 10
p(x): 0 to 2
```

**Expected behavior**
In the above example Visual Studio will (incorrectly) output

    x: 5 to 10
    p(x): 0 to 2

whereas Clang and GCC will (correctly) output

    x: 5 to 10
    p(x): 0 to 0.4

In this example you can verify the distribution simply makes a triangle of area 1.0, which since the width is 5.0 (10.0 - 5.0) the second density value must be 0.4 for the area to sum to 1.0.

**STL version**
    Microsoft Visual Studio Enterprise 2019
    Version 16.6.5

**Additional context**
This bug was also reported to the Visual Studio Developer Community: https://developercommunity.visualstudio.com/content/problem/1125176/stdpiecewise-linear-distribution-incorrectly-norma.html

For context here is the relevant MSVC implementation related to this bug:
https://github.com/microsoft/STL/blob/master/stl/inc/random#L4829-L4854

and Clang's implementation:
https://github.com/llvm/llvm-project/blob/master/libcxx/include/random#L6568-L6590

### PR DESCRIPTION
**Pull request by statementreply**
Fixes #950 and fixes #1084.
Fixes [AB#115939](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/115939).

### CODE REVIEW

File: stl/inc/random [hunk 1]
```diff
@@ -4571,20 +4575,15 @@ public:
         param_type(initializer_list<_Ty> _Ilist, _Fn _Func) : _Mypbase(_Noinit) {
             if (2 <= _Ilist.size()) {
                 _Bvec.assign(_Ilist);
+
+                for (size_t _Idx = 0; _Idx < _Bvec.size() - 1; ++_Idx) {
```
[the remark this answers is not in the document]
Comment (statementreply) [reply stl/inc/random:4579]: There are several more occurrences in `discrete_distribution`, `piecewise_constant_distribution` and `piecewise_linear_distribution` where we could have `reserve`d before populating `vector`s. Perhaps for another "performance" PR?

File: stl/inc/random [hunk 2]
```diff
@@ -4562,6 +4562,10 @@ public:
                 for (size_t _Idx = 0; _Idx < _Bvec.size() - 1; ++_Idx) {
                     this->_Pvec.push_back(static_cast<double>(*_First2++));
                 }
+            } else { // default construct
+                _Bvec.clear();
+                _Bvec.push_back(0);
+                _Bvec.push_back(1);
```
Comment (AlexGuteniev) [inline stl/inc/random:4568]:
```suggestion
                _Bvec = {0, 1};
```

File: stl/inc/random [hunk 3]
```diff
@@ -4571,20 +4575,15 @@ public:
         param_type(initializer_list<_Ty> _Ilist, _Fn _Func) : _Mypbase(_Noinit) {
             if (2 <= _Ilist.size()) {
                 _Bvec.assign(_Ilist);
+
+                for (size_t _Idx = 0; _Idx < _Bvec.size() - 1; ++_Idx) {
+                    this->_Pvec.push_back(_Func(_Ty{0.5} * (_Bvec[_Idx] + _Bvec[_Idx + 1])));
+                }
             } else { // default construct
                 _Bvec.push_back(0);
                 _Bvec.push_back(1);
```
Comment (AlexGuteniev) [inline stl/inc/random:4584]:
```suggestion
                _Bvec = {0, 1};
```

Comment (miscco) [reply stl/inc/random]: I am not really sure about that. Doesnt this involve an allocation as we need a temporary?

**Comment by statementreply** [comment]
> Could that be `_Count==0` or even `_Count = _STD min(_Count, 1u);`

`_STD max(_Count, size_t{1})` 😃

File: stl/inc/random (hunk 3 above)
Comment (AlexGuteniev) [reply stl/inc/random]: `initializer_list` is not a container. It is not expected to allocate for its temporaries.

Comment (AlexGuteniev) [reply stl/inc/random]: Or do you imagine temporary `vector` constructed just before assignment? No, `vector` has `operator=` that accepts `initializer_list` directly

Comment (AlexGuteniev) [reply stl/inc/random]: https://godbolt.org/z/M43E5M

Both are not really good, but `initializer_list` version is still better.
At least allocates just once (like with reserve) and never checks if needed to reallocate (so no unnecessary branches):
```asm
        lea     edx, QWORD PTR [rax+2]    ; rax was zero plus two, so rdx is two
        call    int * std::allocator<int>::allocate(unsigned __int64) ; std::allocator<int>::allocate
```


clang version with `push_back` looks especially dumb. clang substituted all variables (and avoided branches), but still decided to allocate one element, then allocate two:
```asm
        mov     edi, 4
        call    operator new(unsigned long)
        mov     r15, rax
        mov     dword ptr [rax], 0
        add     rax, 4
        mov     qword ptr [r14], r15
        mov     qword ptr [r14 + 8], rax
        mov     qword ptr [r14 + 16], rax
        mov     edi, 8
        call    operator new(unsigned long)
```

Comment (AlexGuteniev) [reply stl/inc/random]: Honestly, this screams for `boost::small_vector<int, 2>`, that what I would have requested _at work_ :-)

**Comment by StephanTLavavej** [comment]
Thanks - I verified that your AB#nnn citation properly linked the MS-internal bug to this PR. :tada:

File: stl/inc/random (hunk 1 above)
[the remark this answers is not in the document]
Comment (StephanTLavavej) [reply stl/inc/random:4574]: A separate performance PR would make sense. Cautionary note: a single `reserve` after `vector` construction is fine, but we should be careful to avoid `reserve` in anything that the user can call in a loop for a single `vector`, as that can trigger quadratic complexity. I'm specifically thinking about `dist.param(const param_type&)` here.

[the remark this answers is not in the document]
Comment (AlexGuteniev) [reply stl/inc/random:4574]: A pattern like this
https://github.com/microsoft/STL/blob/1fef5f71e5c7807ad966624ef421d6ad97f746a3/stl/inc/random#L247-L251
is ideally replaced with range-based algorithm, which would result in transformed iterators, and the vector would reserve automatically at least for random-access iterator.
Maybe just create issue for now and wait for ranges?

File: stl/inc/random [hunk 4]
```diff
@@ -4771,20 +4777,15 @@ public:
         param_type(initializer_list<_Ty> _Ilist, _Fn _Func) : _Mypbase(_Noinit) {
             if (2 <= _Ilist.size()) {
                 _Bvec.assign(_Ilist);
+
+                for (const auto& _Bval : _Bvec) {
```
[the remark this answers is not in the document]
Comment (AlexGuteniev) [reply stl/inc/random:4771]: And here, range-based transform would be too good for _meh_, since I expect it to be very short and clear, and enabling `vector` to auto-reserve

File: stl/inc/random (hunk 1 above)
[the remark this answers is not in the document]
Comment (BillyONeal) [reply stl/inc/random:4574]: This needs to work in C++14 mode and thus will not have ranges avaialble.

File: stl/inc/random (hunk 3 above)
Comment (BillyONeal) [reply stl/inc/random]: > Honestly, this screams for `boost::small_vector<int, 2>`, that what I would have requested _at work_ :-)

That would be ABI breaking.

Comment (AlexGuteniev) [reply stl/inc/random]: Sure, I'm not seriously proposing it here. Including 3rd party to public headers looks not an option, and implementing small object optimization right here adds up to the complexity.

**Comment by statementreply** [comment]
**Self reminder:** investigate remaining libcxx test failures

**Comment by statementreply** [comment]
```
std/numerics/rand/rand.dis/rand.dist.samp/rand.dist.samp.pconst/eval.pass.cpp FAIL
std/numerics/rand/rand.dis/rand.dist.samp/rand.dist.samp.plinear/eval_param.pass.cpp FAIL
std/numerics/rand/rand.dis/rand.dist.samp/rand.dist.samp.plinear/eval.pass.cpp FAIL
```

These random number generation tests are failing because their pass criteria is too strict.

**Comment by StephanTLavavej** [comment]
I've pushed a merge to resolve a conflict, accepting both changes to the libcxx skip lists (for random and lerp).

**Comment by StephanTLavavej** [comment]
I've pushed another merge, resolving #1119's `STD` changes in `tr1`.

File: tests/tr1/tests/random5/test.cpp [hunk 5]
```diff
@@ -486,9 +499,10 @@ static void tpiecewise_constant() {
     dist_t dist2(10, 1.0, 2.0, myfn);
     CHECK_INT(dist2.densities().size(), 10);
 
-    double arr[] = {1.0, 1.1, 1.2, 1.3, 1.4};
+    double arr[] = {1.0, 1.5, 2.0, 3.0, 4.0};
     dist_t dist3(STD initializer_list<double>(&arr[0], &arr[5]), myfn);
```
Comment (CaseyCarter) [inline tests/tr1/tests/random5/test.cpp:503]: Ugh, using unrelated library internals in a test for no reason at all: tr1 things. (No change requested.)

image

Comment (AlexGuteniev) [reply tests/tr1/tests/random5/test.cpp:503]: Could be Good First Issue other than update define

Comment (AlexGuteniev) [reply tests/tr1/tests/random5/test.cpp:503]: A widespread problem #1184

**Comment by StephanTLavavej** [comment]
Thanks for fixing these bugs! :smile_cat: This will ship in VS 2019 16.8 Preview 3.
