### PR TITLE
Internally disable `subrange` workaround

### LINKED ISSUE #2326: `<xutility>`: `subrange` is still affected by an MSVC `constexpr` compiler bug
After updating to VS 2022 17.1 Preview 1 and removing all workarounds for DevCom-1331017 "cl does not make special member functions implicitly constexpr", including the one in `subrange`:
https://github.com/microsoft/STL/blob/178b8406a5647507e759442960f17cd33045cdf5/stl/inc/xutility#L3333-L3338

All of the tests appear to be passing, except for:

https://github.com/microsoft/STL/blob/178b8406a5647507e759442960f17cd33045cdf5/tests/std/tests/P0896R4_views_split/test.cpp#L145-L147

I've partially reduced this to:

```
D:\GitHub\STL\out\build\x64>type meow.cpp
```
```cpp
// Copyright (c) Microsoft Corporation.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

#include <algorithm>
#include <cassert>
#include <ranges>
#include <span>
#include <string_view>
#include <utility>

#include <range_algorithm_support.hpp>
using namespace std;

constexpr auto equal_ranges             = [](auto&& left, auto&& right) { return ranges::equal(left, right); };
constexpr auto text                     = "This is a test, this is only a test."sv;
constexpr string_view expected_single[] = {
    "This"sv, "is"sv, "a"sv, "test,"sv, "this"sv, "is"sv, "only"sv, "a"sv, "test."sv};

constexpr bool instantiation_test() {
    using Read = test::range<forward_iterator_tag, const char, test::Sized::no, test::CanDifference::no,
        test::Common::yes, test::CanCompare::yes, test::ProxyRef::yes, test::CanView::yes, test::Copyability::copyable>;

    Read read{span{text}};

    ranges::split_view r{read, ' '};

    assert(ranges::equal(r, expected_single, equal_ranges));

    return true;
}

int main() {
    static_assert(instantiation_test());
}
```
```
D:\GitHub\STL\out\build\x64>cl /EHsc /nologo /W4 /std:c++latest /I ..\..\..\tests\std\include meow.cpp
meow.cpp
meow.cpp(33): error C2131: expression did not evaluate to a constant
D:\GitHub\STL\out\build\x64\out\inc\ranges(3786): note: failure was caused by call of undefined function or one not declared 'constexpr'
D:\GitHub\STL\out\build\x64\out\inc\ranges(3786): note: see usage of 'std::ranges::subrange<test::iterator<Category,Element,test::CanDifference::no,test::CanCompare::yes,test::ProxyRef::yes,test::IsWrapped::yes>,test::iterator<Category,Element,test::CanDifference::no,test::CanCompare::yes,test::ProxyRef::yes,test::IsWrapped::yes>,std::ranges::subrange_kind::unsized>::operator ='
        with
        [
            Category=std::forward_iterator_tag,
            Element=const char
        ]

D:\GitHub\STL\out\build\x64>clang-cl /EHsc /nologo /W4 /std:c++latest /D_HAS_CXX23 /I ..\..\..\tests\std\include meow.cpp

D:\GitHub\STL\out\build\x64>
```

`<ranges>` and `range_algorithm_support.hpp` are complicated, so I haven't fully reduced this. I'd like to ask for help with reducing and reporting this remaining compiler bug.

### PR DESCRIPTION
**Pull request by CaseyCarter**
The workaround for GH-2326 isn't needed for the internal MSVC compiler; let's ensure it doesn't regress. Since this workaround is in product code let's rename `MSVC_INTERNAL_TESTING` to `_MSVC_INTERNAL_TESTING` (because `_Ugly`). Don't forget to update the name in `$/src/qa/distrib.yml` consistently when merging.

Resolves #2326

### CODE REVIEW

**Comment by AlexGuteniev** [comment]
Should we disable it based on the compiler full version instead of being internal?

**Review by miscco — APPROVED** [review]

**Comment by CaseyCarter** [comment]
> Should we disable it based on the compiler full version instead of being internal?

I don't trust the full version _at all_. It doesn't help that I don't know when this bug was fixed other than "between the 17.1p1 snap and last Friday." The goal is to ensure that the compiler FE doesn't regress this fixing something else, for which it suffices to only have coverage when the pertinent test is run in the internal test harness. Yes, that means the workaround won't be disabled outside of the internal harness until we do so manually, and I'm ok with consequently shipping it for an extra cycle.

**Comment by StephanTLavavej** [comment]
Another reason that we traditionally avoid inspecting `_MSC_FULL_VER` is that it can vary between different MSVC-internal branches, which historically caused trouble as code got merged here and there. This is probably less of an issue these days where there are only 3 major branches for the current version (`prod/fe` where compiler front-end and library code goes, `prod/be` where compiler back-end changes happen, and the main branch where they meet), but the conditioning was long-lasting.

File: stl/inc/xutility [hunk 1]
```diff
@@ -3330,7 +3330,10 @@ namespace ranges {
         // clang-format off
         subrange() requires default_initializable<_It> = default;
 
-#if !defined(__clang__) && !defined(__EDG__) // TRANSITION, GH-2326 (originally DevCom-1331017)
+#if !defined(MSVC_INTERNAL_TESTING) && !defined(__clang__) && !defined(__EDG__) // TRANSITION, VS 17.1p3
```
Comment (StephanTLavavej) [inline stl/inc/xutility:3333]: `MSVC_INTERNAL_TESTING` wasn't intended to be inspected by product code, which is why I didn't make it `_Ugly`. That said, I have no real concerns with shipping this briefly, and I've recorded the workaround for removal during the 17.1 Preview 3 toolset update.

**Review by StephanTLavavej — APPROVED** [review]

File: stl/inc/xutility (hunk 1 above)
Comment (CaseyCarter) [reply stl/inc/xutility:3333]: Oh, yuck. I suppose we can survive shipping this for one preview release.

Comment (StephanTLavavej) [reply stl/inc/xutility:3333]: If you want, I could easily update the internal test harness to define both `MSVC_INTERNAL_TESTING` and `_Ugly` `_MSVC_INTERNAL_TESTING` when merging this, if you want to use the underscore-prefix in product code. Probably worthwhile on its own merits since it's been a point of confusion before. (`_ENABLE_STL_INTERNAL_CHECK` is already defined by our tests, but that doesn't say the right thing here, so I wouldn't recommend it.)

Comment (CaseyCarter) [reply stl/inc/xutility:3333]: How about if we change all occurrences of `MSVC_INTERNAL_TESTING` to `_MSVC_INTERNAL_TESTING` in this PR, and switch the internal definition when porting (instead of adding another define)? I'd prefer having just one name to two.

Comment (StephanTLavavej) [reply stl/inc/xutility:3333]: Sounds good to me.

Comment (CaseyCarter) [reply stl/inc/xutility]: There's the change here - we need to remember to change the one occurrence in `distrib.yml` when we merge.

File: tests/std/tests/P0898R3_concepts/test.cpp [hunk 2]
```diff
@@ -1543,7 +1543,7 @@ namespace test_default_initializable {
         int x;
     };
     STATIC_ASSERT(default_initializable<S>);
-#if defined(MSVC_INTERNAL_TESTING) || defined(__clang__) || defined(__EDG__) // TRANSITION, DevCom-952724
+#if defined(_MSVC_INTERNAL_TESTING) || defined(__clang__) || defined(__EDG__) // TRANSITION, DevCom-952724
```
Comment (cpplearner) [inline tests/std/tests/P0898R3_concepts/test.cpp:1546]: DevCom-952724 is "Fixed In: Visual Studio 2022 version 17.0". Could this #if guard be removed? (This removal can be done in a different PR, of course.)

Comment (CaseyCarter) [reply tests/std/tests/P0898R3_concepts/test.cpp:1546]: Yes. We need to either remove the guard, or file a new bug report and update the annotation. I'd prefer not to do so in this PR since it's already been partially reviewed.

Comment (CaseyCarter) [reply tests/std/tests/P0898R3_concepts/test.cpp:1546]: If you're motivated, feel free to submit a PR and we'll fix the merge conflict if this one lands first.

Comment (cpplearner) [reply tests/std/tests/P0898R3_concepts/test.cpp:1546]: #2351

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
:warning: MSVC-PR mirroring note:
===

This will require a one-line change to the definition of the macro.

**Review by mnatsuhara — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.
