### PR TITLE
Avoid arithmetic overflow in the constructors of `weekday`

### LINKED ISSUE #5153: `<chrono>`: integer overflow in `weekday::weekday(sys_days::max())`
# Brief description

The following code fails to compile due to an `int` addition overflow:
```
#include <chrono>

using namespace std::chrono;

constexpr auto wd = weekday(sys_days::max());
```
https://godbolt.org/z/K6dW7bvYq

# Details

The overflow occurs in the evaluation of  `_Tp + 4` [below](https://github.com/microsoft/STL/blob/5e0ddadefd38b9ab50f2b8772ad4cb001133fd9d/stl/inc/chrono#L478)
```
        _NODISCARD static constexpr unsigned int _Weekday_from_days(int _Tp) noexcept {
            return static_cast<unsigned int>(_Tp >= -4 ? (_Tp + 4) % 7 : (_Tp + 5) % 7 + 6);
        }
```
Indeed, this addition overflows whenever  `_Tp > INT_MAX - 4`. 

# Fixes

Provided that the range of `long long int` is larger than that of `int`, the obvious [fix](https://godbolt.org/z/1G4e63Trs) is declaring `_Tp` as `long long int` and an alternative is this:
```
        _NODISCARD static constexpr unsigned int _Weekday_from_days(int _Tp) noexcept {
            auto const m = unsigned(_Tp) + (_Tp >= 0 ? 4 : 0);
            auto const w = m % 7;
            __assume(w != 7); // not necessary but improves codegen
            return w;
        }
```
This alternative is better than the obvious fix and better than the current implementation. Indeed, with this fix the codegen of `weekday::weekday(const sys_days&)` becomes branch-free and avoids `div` instructions on [x64](https://godbolt.org/z/Yn7vjWfhW), [x86](https://godbolt.org/z/4nsq87rzh) and [arm64](https://godbolt.org/z/G8j5o6Kae).

# Test

The alternative above works as an exhaustive [test](https://godbolt.org/z/GTod84b1G) shows:
```
int main() {

  unsigned int encoding = weekday(sys_days::min()).c_encoding();
  for (auto s = sys_days::min(); s < sys_days::max(); s += days(1)) {
    assert(weekday_ctr(s).c_encoding() == encoding);
    ++encoding;
    if (encoding == 7)
      encoding = 0;
  }
  // One more to go:
  assert(weekday_ctr(sys_days::max()).c_encoding() == encoding);
  std::puts("Success.");
}
```
(where  `weekday_ctr` is an impersonation of `weekday::weekday(const sys_days&)` using the fixed `_Weekday_from_days`.)

### PR DESCRIPTION
**Pull request by frederick-vs-ja**
Fixes #5153.

### CODE REVIEW

File: stl/inc/chrono [hunk 1]
```diff
@@ -473,10 +473,11 @@ namespace chrono {
     private:
         unsigned char _Weekday;
 
-        // courtesy of Howard Hinnant
+        // courtesy of Howard Hinnant (modified to avoid overflow)
         // https://howardhinnant.github.io/date_algorithms.html#weekday_from_days
         _NODISCARD static constexpr unsigned int _Weekday_from_days(int _Tp) noexcept {
-            return static_cast<unsigned int>(_Tp >= -4 ? (_Tp + 4) % 7 : (_Tp + 5) % 7 + 6);
+            const auto _Before_modulo = static_cast<unsigned int>(_Tp) + (_Tp >= 0 ? 4u : 0u);
```
Comment (cassioneri) [inline stl/inc/chrono:479]: The 3rd operand of the ternary operator is `0` provided that `int`/`unsigned int` are 32 bits long. I don't know if the STL supports any system where this is not true. If so or if you wish to make the code future proof, then the compiler can calculate the operand for us (see a simulation [here](https://godbolt.org/z/b4fz9EsKG)):
```suggestion
            constexpr auto minus_1_mod7 = static_cast<unsigned int>(-1) % 7;
            constexpr auto offset = (minus_1_mod7 >= 3 ? 3 : -4) - minus_1_mod7;
            const auto before_modulo = static_cast<unsigned int>(_Tp) + (_Tp >= 0 ? 4 : offset);
```
Otherwise, the code is good as it is.

**Review by cassioneri — APPROVED** [review]

File: tests/std/tests/P0355R7_calendars_and_time_zones_dates/test.cpp [hunk 2]
```diff
@@ -281,6 +281,10 @@ constexpr void weekday_test() {
     assert(Sunday - Monday == days{6});
     assert(Sunday - Tuesday == days{5});
     assert(Wednesday - Thursday == days{6});
+
+    // GH-5153 "<chrono>: Undefined behaviour in weekday::weekday(const sys_days&)."
```
Comment (CaseyCarter) [inline tests/std/tests/P0355R7_calendars_and_time_zones_dates/test.cpp:285]: I edited the issue title to make this self-explanatory, so I don't have to post a "please summarize the issue here" comment:
```suggestion
    // GH-5153 "<chrono>: integer overflow in weekday::weekday(sys_days::max())"
```

File: stl/inc/chrono [hunk 3]
```diff
@@ -473,10 +473,11 @@ namespace chrono {
     private:
         unsigned char _Weekday;
 
-        // courtesy of Howard Hinnant
+        // courtesy of Howard Hinnant (modified to avoid overflow)
         // https://howardhinnant.github.io/date_algorithms.html#weekday_from_days
         _NODISCARD static constexpr unsigned int _Weekday_from_days(int _Tp) noexcept {
-            return static_cast<unsigned int>(_Tp >= -4 ? (_Tp + 4) % 7 : (_Tp + 5) % 7 + 6);
+            const auto _Before_modulo = static_cast<unsigned int>(_Tp) + (_Tp >= 0 ? 4u : 0u);
+            return _Before_modulo % 7u; // for codegen by MSVC on x86/ARM64, see GH-5153
```
Comment (CaseyCarter) [inline stl/inc/chrono:480]:
```suggestion
            return _Before_modulo % 7u; // separate expression for MSVC codegen, see GH-5153
```

**Review by CaseyCarter — APPROVED** [review]

**Comment by CaseyCarter** [comment]
I pushed a commit to wiggle some comments and add an `_STL_INTERNAL_STATIC_ASSERT` as documentation. Thanks!

**Review by StephanTLavavej — APPROVED** [review]

**Review by cassioneri — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
Thanks for fixing this corner case! :hammer_and_wrench: :volcano: :smile_cat:
