### PR TITLE
`<algorithm>`: Fix bogus pointer arithmetic with integer-class

### LINKED ISSUE #2885: `<algorithm>`: `ranges::stable_sort` missing ` difference_type` casting for pointer arithmetic
https://github.com/microsoft/STL/blob/ef62d3fa0b8e4e2406b9bb74e916e1ca8a1df802/stl/inc/algorithm#L8149-L8154

https://github.com/microsoft/STL/blob/ef62d3fa0b8e4e2406b9bb74e916e1ca8a1df802/stl/inc/algorithm#L8191

When `_Count` is an integer-class type, `_Temp_ptr + _Count` will be ill-formed.

```cpp
#include <algorithm>
#include <ranges>
#include <vector>

int main() {
  std::vector<int> v;
  auto r = std::views::iota(0ULL, v.size())
         | std::views::transform([&v](auto i) -> auto& { return v[i]; });
  std::ranges::stable_sort(r);
}
```

https://godbolt.org/z/aPcq9Y6xh

### PR DESCRIPTION
**Pull request by frederick-vs-ja**
By using `ptrdiff_t` when the related value is guaranteed to be small enough and/or used in pointer arithmetic. Fixes #2885.

### CODE REVIEW

File: tests/std/tests/GH_002885_stable_sort_difference_type/test.cpp [hunk 1]
```diff
@@ -0,0 +1,99 @@
...
+constexpr auto pred = [](int i) { return i <= 42; };
+
+template <class I>
+void test_iota_transform() {
+    constexpr int orig[]{42, 1729};
+    int a[]{42, 1729};
+    auto vw = views::iota(I{}, static_cast<I>(ranges::size(a)))
+            | views::transform([&a](I i) -> auto& { return a[static_cast<size_t>(i)]; });
+
+    static_assert(three_way_comparable<ranges::iterator_t<ranges::iota_view<I>>>); // TRANSITION, /permissive
```
Comment (frederick-vs-ja) [inline tests/std/tests/GH_002885_stable_sort_difference_type/test.cpp:23]: This is really weird. It seems that MSVC doesn't evaluate concept specializations as quickly as required in permissive modes.

Comment (CaseyCarter) [reply tests/std/tests/GH_002885_stable_sort_difference_type/test.cpp:23]: From the last bit of the error log:
```
D:\build\out\inc\__msvc_ranges_to.hpp(865): note: while evaluating concept 'three_way_comparable<std::ranges::_Ioterator<signed char>,std::partial_ordering>'
D:\build\out\inc\__msvc_ranges_to.hpp(865): error C2131: expression did not evaluate to a constant
D:\build\out\inc\__msvc_ranges_to.hpp(865): note: failure was caused by a read of an uninitialized symbol
D:\build\out\inc\__msvc_ranges_to.hpp(865): note: see usage of 'std::three_way_comparable<std::ranges::_Ioterator<_Wi>,std::partial_ordering>'
```
"C2131 while evaluating `meow` ... see usage of `meow`" generally suggests constraint recursion, which is not that unusual in permissive mode. The fact the overload resolution sees "extra" friend overloads that ought to be hidden can easily trigger constraint recursion.

File: stl/inc/algorithm [hunk 2]
```diff
@@ -8901,7 +8907,7 @@ namespace ranges {
         }
 
         template <class _It, class _Pr, class _Pj>
-        static void _Buffered_merge_sort_common(const _It _First, const _It _Last, const iter_difference_t<_It> _Count,
+        static void _Buffered_merge_sort_common(const _It _First, const _It _Last, ptrdiff_t _Count,
```
Comment (CaseyCarter) [inline stl/inc/algorithm:8910]: I don't see any introduced modifications, I think we could keep `_Count` `const` .

**Review by CaseyCarter — APPROVED** [review]
Just some tweaks that I'll apply.

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
Thanks for fixing this bogus journey and making the STL most triumphant! :guitar: :man_singer: :stopwatch:
