### PR TITLE
Prevent crash when custom streambuf implementation throws

### LINKED ISSUE #1105: Crash if custom std::streambuf implementation throws
**Describe the bug**
Constructing an std::istream with a custom std::streambuf that throws on construction causes an access violation.

**Command-line test case**
```
C:\Temp>type foo.cpp

#include <istream>
#include <string>
#include <stdexcept>

class foo_buf : public std::streambuf {
public:
    foo_buf() {
        throw std::runtime_error("Whoops");
    }
};

class foo_stream : public std::istream {
public:
    foo_stream() : std::istream(new foo_buf) {
    }
};

int main(int, char**) {
    try {
        foo_stream f;
    } catch (const std::exception&) {
        return 1;
    }
    return 0;
}

CL.exe /c /Zi /nologo /W3 /WX- /diagnostics:column /Od /Ob0 /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /EHsc /
  RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"foo.dir\Debug\\" /Fd"foo.dir\Debug\vc142.pdb" /Gd /TP /errorReport:queue C:\Temp\foo.cpp  foo.cp

link.exe /ERRORREPORT:QUEUE /OUT:"C:\Temp\Debug\foo.exe" /INCREMENTAL /NOLOGO kernel32.lib user32.lib gdi32.lib wins
  pool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Temp/Debug/foo.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /D
  YNAMICBASE /NXCOMPAT /IMPLIB:"C:/Temp/Debug/foo.lib" /MACHINE:X64  /machine:x64 foo.dir\Debug\foo.obj

Debug\foo.exe

Exception thrown at 0x00007FFE0C6E6E85 (msvcp140d.dll) in foo.exe: 0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFFF.

```

**Expected behavior**

The `std::runtime_error` thrown from the foo_buf constructor should be caught and main should return 1.

**STL version**
* Visual Studio version
```
Microsoft Visual Studio Enterprise 2019
Version 16.6.5
```
I don't see any reason why an std::streambuf implementation shouldn't be allowed to throw and this works fine with other compilers and library implementations (Gnu and LLVM), so I assume this could be a bug in this STL implementation.

### PR DESCRIPTION
**Pull request by Arzaghi**
Fixes #1105 
Just pre-init some pointers and a numeric variable and also wrapping a pointer deletion with an `if` statement could solve the issue.
I wanted to add a test coverage and I didn't find any relative place to add the test. I've added a new folder for the new test. It's my first time that I'm adding a new folder to the tests folder. I've tried to follow the conventions. Excuse me if I missed anything here.

### CODE REVIEW

File: stl/inc/xiosbase [hunk 1]
```diff
@@ -547,9 +547,9 @@ private:
     fmtflags _Fmtfl; // format flags
     streamsize _Prec; // field precision
     streamsize _Wide; // field width
-    _Iosarray* _Arr; // pointer to first node of long/pointer array
-    _Fnarray* _Calls; // pointer to first node of call list
-    locale* _Ploc; // pointer to locale
+    _Iosarray* _Arr{nullptr}; // pointer to first node of long/pointer array
+    _Fnarray* _Calls{nullptr}; // pointer to first node of call list
+    locale* _Ploc{nullptr}; // pointer to locale
```
Comment (barcharcraz) [inline stl/inc/xiosbase:552]: Note: this changes the set of "valid" states, it should be fine since tests pass and you check for deletion

File: stl/inc/xiosbase [hunk 2]
```diff
@@ -547,9 +547,9 @@ private:
     fmtflags _Fmtfl; // format flags
     streamsize _Prec; // field precision
     streamsize _Wide; // field width
-    _Iosarray* _Arr; // pointer to first node of long/pointer array
-    _Fnarray* _Calls; // pointer to first node of call list
-    locale* _Ploc; // pointer to locale
+    _Iosarray* _Arr{nullptr}; // pointer to first node of long/pointer array
+    _Fnarray* _Calls{nullptr}; // pointer to first node of call list
```
Comment (barcharcraz) [inline stl/inc/xiosbase:551]: these can be not initialized in the constructors anymore after this addition.

**Review by barcharcraz — APPROVED** [review]
Approved with suggested changes

File: stl/inc/xiosbase (hunk 2 above)
Comment (StephanTLavavej) [reply stl/inc/xiosbase:551]: The constructor `ios_base()` doesn't initialize anything.

The member function `_Init()` assigns data members, but I don't think that it should be changed. It's fine if we redundantly assign data members, but I'm worried about unintended consequences of changing `_Init()` (I recall that it's "weird" but I don't know the details).

File: stl/inc/xiosbase (hunk 1 above)
Comment (StephanTLavavej) [reply stl/inc/xiosbase:552]: I also think it's fine because zero/null is a strict subset of garbage (i.e. zero-initialization is never worse for correctness than default-initialization).

File: stl/src/ios.cpp [hunk 3]
```diff
@@ -31,7 +31,10 @@ void __CLRCALL_PURE_OR_CDECL ios_base::_Ios_base_dtor(ios_base* _This) { // dest
     }
 
     _This->_Tidy();
-    delete _This->_Ploc;
+
+    if (_This->_Ploc != nullptr) {
+        delete _This->_Ploc;
+    }
```
Comment (StephanTLavavej) [inline stl/src/ios.cpp:37]: I don't think that this change is necessary - `delete` is a guaranteed no-op for null. See WG21-N4868
17.6.3.2 [new.delete.single]/17 "If `ptr` is null, does nothing."

File: tests/std/test.lst [hunk 4]
```diff
@@ -168,6 +168,7 @@ tests\GH_001017_discrete_distribution_out_of_range
 tests\GH_001059_hyperbolic_truncation
 tests\GH_001086_partial_sort_copy
 tests\GH_001103_countl_zero_correctness
+tests\GH_001105_streambuf
```
Comment (StephanTLavavej) [inline tests/std/test.lst:171]: This is correctly mentioning the newly added test directory in sorted order. However, I recommend making the directory name slightly more detailed. This is important because when a test fails, the name is a reminder of what the test does. Here, `custom_streambuf_throws` would be much more descriptive than just `streambuf`. (In addition to renaming it here, the directory itself should be renamed with `git mv`.)

File: tests/std/tests/GH_001105_streambuf/test.cpp [hunk 5]
```diff
@@ -0,0 +1,30 @@
+// Copyright (c) Microsoft Corporation.
+// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
+
+#include <cassert>
+#include <istream>
+#include <stdexcept>
+
+struct bad_buf : public std::streambuf {
```
Comment (StephanTLavavej) [inline tests/std/tests/GH_001105_streambuf/test.cpp:8]: `struct`s default to `public` for both their base classes and members, and we conventionally rely on this default in both product code and test code:
```suggestion
struct bad_buf : std::streambuf {
```

File: tests/std/tests/GH_001105_streambuf/test.cpp [hunk 6]
```diff
@@ -0,0 +1,30 @@
...
+#include <istream>
+#include <stdexcept>
+
+struct bad_buf : public std::streambuf {
+    bad_buf() {
+        throw std::runtime_error("throw in constructor!");
+    }
+};
+
+struct custom_stream : public std::istream {
```
Comment (StephanTLavavej) [inline tests/std/tests/GH_001105_streambuf/test.cpp:14]:
```suggestion
struct custom_stream : std::istream {
```

File: tests/std/tests/GH_001105_streambuf/test.cpp [hunk 7]
```diff
@@ -0,0 +1,30 @@
...
+    custom_stream() : std::istream(new bad_buf{}) {}
+};
+
+int main(int, char**) {
```
[the remark this answers is not in the document]
Comment (StephanTLavavej) [reply tests/std/tests/GH_001105_streambuf/test.cpp:18]: I'd also like to see `int main()` for consistency although it isn't a big deal.

**Review by StephanTLavavej — COMMENTED** [review]
Thanks for fixing this bug! I'm planning to prepare a batch of PRs for merging, so I'll validate minor changes and push them in a few minutes.

File: stl/src/ios.cpp (hunk 3 above)
Comment (Arzaghi) [reply stl/src/ios.cpp]: Honestly, I didn't know this point. Thank you very much for letting me know about this guarantee.

**Review by StephanTLavavej — APPROVED** [review]

File: stl/src/ios.cpp (hunk 3 above)
Comment (StephanTLavavej) [reply stl/src/ios.cpp]: You're welcome! :smile_cat: This requirement is also binding on any user-replacement implementations of `operator delete` so we don't need to worry about them.

**Comment by StephanTLavavej** [comment]
FYI @barcharcraz, I pushed small changes after you approved.

**Comment by StephanTLavavej** [comment]
Thanks again - we really appreciate all of your fixes! :cat2:
