### PR TITLE
Use `_STL_REPORT_ERROR` in headers

### LINKED ISSUE #5529: Call `__fastfail` instead of `abort()` in more places
# Where don't call `abort()`

Since `__fastfail` is considered a superior way to fail, and nobody asked for specific behavior in most of the places where we call abort, let's replace `abort()` calls in:

**1. Places that are not implementable in `!_HAS_EXCEPTIONS` mode:**

https://github.com/microsoft/STL/blob/cbd091e4170a84dfb8beca3119ab8e3188988848/stl/inc/xlocale#L446-L450

**2. Places that seems like direct result of doing something wrong:**

https://github.com/microsoft/STL/blob/cbd091e4170a84dfb8beca3119ab8e3188988848/stl/inc/functional#L1354-L1357

https://github.com/microsoft/STL/blob/cbd091e4170a84dfb8beca3119ab8e3188988848/stl/inc/utility#L959-L964

**3. Places that handle broken invariant:**

https://github.com/microsoft/STL/blob/cbd091e4170a84dfb8beca3119ab8e3188988848/stl/inc/atomic#L2992-L2994

**4. Places that handle robust WinAPI functions failures**

https://github.com/microsoft/STL/blob/cbd091e4170a84dfb8beca3119ab8e3188988848/stl/inc/xcall_once.h#L97-L99

**5. Places that are inherently dead code paths and exist due to having to implement a virtual function:**

https://github.com/microsoft/STL/blob/cbd091e4170a84dfb8beca3119ab8e3188988848/stl/inc/functional#L891-L893

----

# What call instead

In headers we have the following alternatives:
 * `_STL_REPORT_ERROR`
 * `_MSVC_STL_DOOM_FUNCTION`

In separately compiled code we probably should directly call `__fastfail`.

### PR DESCRIPTION
**Pull request by AlexGuteniev**
Resolves #5529.

`terminate()` still calls `abort()`. All other places use `_STL_REPORT_ERROR`.

Headers only. Keep `abort()` in separately compiled code to avoid losing a customization point.

🚨 Drops `abort()` from `<utility>` without any replacement🚨! Core headers should not call any functions.

### CODE REVIEW

File: stl/inc/xutility [hunk 1]
```diff
@@ -1121,7 +1121,7 @@ struct _Projected_impl {
 
         using value_type = remove_cvref_t<indirect_result_t<_Proj&, _It>>;
         [[noreturn]] indirect_result_t<_Proj&, _It> operator*() const {
-            _CSTD abort(); // shouldn't be called, see GH-3888
+            _MSVC_STL_DOOM_FUNCTION("");
```
Comment (AlexGuteniev) [inline stl/inc/xutility:1124]: No idea what to say here. Seems related to #5555.

File: stl/inc/yvals.h [hunk 2]
```diff
@@ -253,7 +253,9 @@ _EMIT_STL_ERROR(STL1008, "_STL_CALL_ABORT_INSTEAD_OF_INVALID_PARAMETER has been
 #define _MSVC_STL_DOOM_FUNCTION(mesg) ::_invoke_watson(nullptr, nullptr, nullptr, 0, 0)
 #else // Use the MSVC __fastfail intrinsic:
 extern "C" __declspec(noreturn) void __fastfail(unsigned int); // declared by <intrin.h>
-#define _MSVC_STL_DOOM_FUNCTION(mesg) __fastfail(5) // __fastfail(FAST_FAIL_INVALID_ARG), value defined by <winnt.h>
+#define _MSVC_STL_DOOM_FUNCTION(mesg)                                                 \
+    __fastfail(5); /* __fastfail(FAST_FAIL_INVALID_ARG), value defined by<winnt.h> */ \
```
Comment (Fulgen301) [inline stl/inc/yvals.h:257]:
```suggestion
    __fastfail(5); /* __fastfail(FAST_FAIL_INVALID_ARG), value defined by <winnt.h> */ \
```

File: stl/inc/atomic [hunk 3]
```diff
@@ -2990,7 +2990,7 @@ public:
                 break;
 
             default: // Unrecognized bit pattern
-                _CSTD abort();
+                _MSVC_STL_DOOM_FUNCTION("atomic shared_ptr invariant broken");
             }
```
Comment (StephanTLavavej) [inline stl/inc/atomic]: We should now `break;` as `_MSVC_STL_DOOM_FUNCTION` supports "continue on error".

File: stl/inc/functional [hunk 4]
```diff
@@ -808,7 +808,7 @@ private:
     }
 #else // ^^^ _HAS_STATIC_RTTI / !_HAS_STATIC_RTTI vvv
     [[noreturn]] const type_info& _Target_type() const noexcept override {
-        _CSTD abort(); // shouldn't be called, see GH-3888
+        _MSVC_STL_DOOM_FUNCTION("type info is disabled");
     }
```
Comment (StephanTLavavej) [inline stl/inc/functional]: Places like this will need to be marked as unreachable to avoid "falling off the end of a non-void function" errors when users attempt to customize this to continue-on-error.

File: stl/inc/xutility (hunk 1 above)
Comment (StephanTLavavej) [reply stl/inc/xutility]: We can just cite the Standardese.

File: stl/inc/functional [hunk 5]
```diff
@@ -1352,8 +1352,8 @@ inline constexpr size_t _Minimum_function_size = 2 * sizeof(void*);
 
 template <class _Rx, class... _Types>
 [[noreturn]] _Rx __stdcall _Function_not_callable(const _Move_only_function_data&, _Types&&...) noexcept {
-    _CSTD abort(); // Unlike std::function, move_only_function doesn't throw bad_function_call
-                   // (N4950 [func.wrap.move.inv]/2)
+    _MSVC_STL_DOOM_FUNCTION("empty move_only_function call"); // Unlike std::function, move_only_function doesn't throw
+                                                              // bad_function_call (N4950 [func.wrap.move.inv]/2)
```
Comment (StephanTLavavej) [inline stl/inc/functional]: We can fuse the comment into the reason.

**Review by StephanTLavavej — APPROVED** [review]

**Comment by AlexGuteniev** [comment]
Maybe it worth using `_STL_REPORT_ERROR` instead of `_MSVC_STL_DOOM_FUNCTION` here, just to be consistent?

**Comment by StephanTLavavej** [comment]
Thanks, updated PR title and description. The difference is significant, not cosmetic:

https://github.com/microsoft/STL/blob/7841cf88ff9af837fb980f2d2d4ac0f267e714c7/stl/inc/yvals.h#L260-L262

The UCRT's `_RPTF0` is what pops up the nice assertion dialog in debug mode (or prints to stderr etc. if redirected). Without it, `_MSVC_STL_DOOM_FUNCTION` is just a `__fastfail` that makes the process vanish. I should have noticed this earlier - thanks for catching it.

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
Thanks for making this consistent, and easier to follow precedent in the future! :heart_eyes_cat: :tada: :partying_face:
