### PR TITLE
`vector_algorithms.cpp`: Add `vzeroupper`, so that it is there even in `/Od`

### LINKED ISSUE #3601: <algorithm>: vectorized algorithms hurt performance.
**Describe the bug**

Some STL algorithms will automatically use the AVX version if supported,  without calling `_mm256_zeroupper()` at the end of the function, which will slow down subsequent SSE code on some CPUs (e.g. Skylake).

[Why is this SSE code 6 times slower without VZEROUPPER on Skylake?](https://stackoverflow.com/questions/41303780/why-is-this-sse-code-6-times-slower-without-vzeroupper-on-skylake)

In following code, the second `calculate()` is much slower than the first `calculate()`. 

**Command-line test case**
```
C:\Temp>type repro.cpp

#include <Windows.h>
#include <vector>
#include <algorithm>

void calculate() {
    int t = ::GetTickCount();
    float a = 1.0f, b = 1.0f, m = 0.0f;
    for (int i = 0; i < 30000000; i++) {
        m = a * b;
        m -= a * 0.1f;
        m += b * 0.2f;
    }
    printf("time cost %d\n", ::GetTickCount() - t);
}

int main() {
    std::vector<float> v1;
    v1.resize(10);
    for (auto it = v1.begin(); it != v1.end(); it++)
        *it = (float)rand();
    std::vector<float> tmp(10);

    std::reverse_copy(v1.end() - 7, v1.end(), tmp.begin());
    calculate();

    std::reverse_copy(v1.end() - 8, v1.end(), tmp.begin());  // AVX code path is selected.
    calculate();
}

C:\Temp>cl /EHsc /W4 /WX .\repro.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.34.31937 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

repro.cpp
Microsoft (R) Incremental Linker Version 14.34.31937.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:repro.exe
repro.obj

C:\Temp>.\repro.exe
time cost 172
time cost 296
```

### PR DESCRIPTION
**Pull request by AlexGuteniev**
Fix #3601

### CODE REVIEW

**Review by strega-nil-ms — APPROVED** [review]

File: stl/src/vector_algorithms.cpp [hunk 1]
```diff
@@ -66,6 +66,14 @@ namespace {
     void _Advance_bytes(const void*& _Target, ptrdiff_t _Offset) noexcept {
         _Target = static_cast<const unsigned char*>(_Target) + _Offset;
     }
+
+    // TRANSITION, DevCom-10331414
+    struct _Zeroupper_on_exit {
```
Comment (StephanTLavavej) [inline stl/src/vector_algorithms.cpp:71]: As this is a guard type, we should mark it as `[[nodiscard]]` to prevent classic misuse in the future.

File: stl/src/vector_algorithms.cpp [hunk 2]
```diff
@@ -66,6 +66,14 @@ namespace {
     void _Advance_bytes(const void*& _Target, ptrdiff_t _Offset) noexcept {
         _Target = static_cast<const unsigned char*>(_Target) + _Offset;
     }
+
+    // TRANSITION, DevCom-10331414
+    struct _Zeroupper_on_exit {
+        ~_Zeroupper_on_exit() {
```
Comment (StephanTLavavej) [inline stl/src/vector_algorithms.cpp:72]: We should also make this noncopyable.

**Review by StephanTLavavej — APPROVED** [review]

**Review by strega-nil-ms — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Thanks! :heart_eyes_cat: I verified that all occurrences of `_Use_avx2()` have been updated, and that the guard type is used if and only if an early `return` is possible. FYI @strega-nil-ms I pushed a small commit to enhance the guard type after you approved (no functional change, just resists future misuse).

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.
