### PR TITLE
`<regex>`: Process generic loops non-recursively

### LINKED ISSUE #997: <regex>: Grouping within repetition causes regex stack error
**Describe the bug**
`std::regex` with satisfactory large input and certain compiler options overflows the stack

**Command-line test case**
```

d:\Temp2>type repro.cpp
#include <Windows.h>
#include <iostream>
#include <regex>
#include <string>

void regex_test()
{
    try
    {
        auto str = std::string(1000, 'a');
        auto match = std::smatch{};
        std::regex_match(str, match, std::regex("a+"));     // OK
        std::regex_match(str, match, std::regex("(?:a)+")); // stack error
    }
    catch (std::exception& ex)
    {
        std::cout << ex.what() << '\n';
    }
}

int main()
{
    bool stack_overflow_observed = false;
    __try
    {
        regex_test();
    }
    __except (GetExceptionCode() == EXCEPTION_STACK_OVERFLOW)
    {
        stack_overflow_observed = true;
    }
    if (stack_overflow_observed)
    {
        _resetstkoflw();
        std::cout << "Stack overflow was observed\n";
    }
    else
    {
        std::cout << "Stack overflow was NOT observed\n";
    }
    return 0;
}

d:\Temp2>cl /EHa /RTC1 /MDd /std:c++17 .\repro.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.27.29009.1 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

repro.cpp
Microsoft (R) Incremental Linker Version 14.27.29009.1
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:repro.exe
repro.obj

d:\Temp2>.\repro.exe
Stack overflow was observed
```

**Expected behavior**
Successful parsing or C++ exception, but not stack overflow

**STL version**
```
Microsoft Visual Studio Professional 2019 Preview
Version 16.7.0 Preview 3.1
```

**Additional context**
This item is also tracked on Developer Community as DevCom-885115  and by Microsoft-internal VSO-1054746 / [AB#1054746](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1054746).

See also #405

**vNext note**: Resolving this issue will require breaking binary compatibility. We won't be able to accept pull requests for this issue until the vNext branch is available. See https://github.com/microsoft/STL/issues/169 for more information.

### LINKED ISSUE #1528: <regex>: regex_match gets caught in recursive loop until stack overflow occurs
**Describe the bug**
I have found a case where calling regex_match can result in a recursive loop until a stack overflow occurs.  Problem occurs when run as x64 debug.  When run as x64 release an exception occurs.  And when run as x86 debug or release, program works as expected.

**Command-line test case**
```
#include <iostream>
#include <regex>

int main(void)
{
	auto flags = std::regex_constants::ECMAScript | std::regex::icase;

	try
	{
		std::wregex rgx(L"^http[s]?\\:\\/\\/([^.]+\\.)*github\\.com\\/.*$", flags);
		bool bResult = std::regex_match(L"https://www.google.com/search?client=firefox-b-1-d&q=tea%20box&tbs=lf:1,lf_ui:10&tbm=lcl&sxsrf=ALeKk03GLkevbpot_6JmlWw6_IJKeKBKbw:1607540768824&rflfq=1&num=10&rldimm=11474290690396232776&lqi=Cgd0ZWEgYm94Gd9r-yQGeFTPSKvez_DmgICACFoWCgd0ZWEgYm94EAAQASIHdGVhIGJveIABAQ&phdesc=-P7Y2CJJHVU&ved=2ahUKEwjA9PKDzMHtAhVTMH0KHfnkAUIQvS4wBHoECAQQOQ&rlst=f#rlfi%3Dhd%3A%3Bsi%3A11474290690396232776%2Cl%2CCgd0ZWEgYm94Gd9r-yQGeFTPSKvez_DmgICACFoWCgd0ZWEgYm94EAAQASIHdGVhIGJveIABAQ%2Cy%2C-P7Y2CJJHVU%3Bmv%3A%5B%5B35.638039299999996%2C-117.9412485%5D%2C%5B34.634577799999995%2C-120.8545755%5D%5D%3Btbs%3Alrf%3A%211m4%211u3%212m2%213m1%211e1%211m4%211u2%212m2%212m1%211e1%212m1%211e2%212m1%211e3%213sIAE%2Clf%3A1%2Clf_ui%3A10", rgx);

		if(bResult)
			std::cout << "Match" << std::endl;
		else
			std::cout << "Does not match" << std::endl;
	}
	catch(const std::regex_error &e)
	{
		std::cout << "Exception" << std::endl;
	}

	return 0;
}
```

**Expected behavior**
The expression does not match, so the expected result is "Does not match."  As stated, the result varies depending on how the code is compiled.  x64 debug results in stack overflow.  x64 release results in an exception.  And x86 debug/release yields the correct result of "Does not match."

**STL version**
```
Microsoft Visual Studio Professional 2019
Version 16.8.3
```

**Additional context**
Tested on Linux using gcc and clang, in both cases the STL correct returns that it does not match.  Only the Windows implementation of the STL results in a stack overflow.

### PR DESCRIPTION
**Pull request by muellerj2**
Fixes #997. Fixes #1528.

This is the final change to make the matcher non-recursive, but it will be followed by a few more PRs to clean up the code and simplify the data stored in `_Rx_state_frame`s.

The new code in `_Match_pat()` is closer to the structure of the original code than for simple loops, but also quite similar to the non-recursive code for simple loops, so I chose not to split it into several PRs.

Differences compared to simple loops:
* Since non-simple loops are potentially re-entrant and repeated patterns can branch, the loop variables have to be reset whenever we backtrack. This means we have to add more members to `_Rx_state_frame` to store the original values of these loop variables and have to add an unwinding opcode just for resetting these loop variables. Moreover, we have to completely restore the match state whenever we backtrack after failure (ECMAScript) or while matching a POSIX regex.
  * In the case of greedy matching, we can restore the loop variables in the same opcode that also sets up matching of the tail when matching another repetition failed. This has the slight advantage that we need to maintain fewer frames for backtracking while matching the tail.
* I kept the structure of conditions mostly the same between simple and generic loops, except that I exchanged the order of conditions for "empty match" and "minimum number of repetitions not reached yet". This order aligns more closely with `_Do_rep()` and is a bit simpler for generic loops, I think, because the logic for handling the minimum number of repetitions isn't affected much by whether the last encountered match is empty or not (except for the optimization of increasing `_Loop_idx` by more than one when a match is empty). This is different from simple loops, where the easy case was an empty match: Because simple loops are branchless, one empty match means all are empty, so the minimum number of repetitions essentially becomes meaningless when an empty match appears.

Most of the test coverage is derived from the new coverage for simple loops, with a minor change to make the loops non-simple by making them branch. I also added another test to make sure we correctly handle an empty match that only appears in the final repetition to reach the minimum number of repetitions.

As for the two tests to verify that stack overflows no longer occur (copied from the original issues), I deliberately set one of them up to fail when matching no longer results in an exception, because the code should be changed to use the regex tester when an exception is no longer thrown. (I can't easily do this for the other test case because it currently succeeds for x86 but fails for x64. It seems out of proportion to add preprocessor logic just to make the test fail on 64-bit systems when it succeeds unexpectedly.)

### CODE REVIEW

File: stl/inc/regex [hunk 1]
```diff
@@ -4078,8 +4014,33 @@ bool _Matcher3<_BidIt, _Elem, _RxTraits, _It, _Alloc>::_Match_pat(_Node_base* _N
                             }
                         }
                     } else {
-                        _Failed = !_Do_rep(_Node, _Greedy, 0);
-                        _Next   = nullptr;
+                        if (_Node->_Min > 0 || (_Greedy && !_Longest && _Node->_Max != 0)) { // try a rep first
+                            // set up stack unwinding for greedy matching or loop val restoration
+                            auto _Frame_idx = _Push_frame(
+                                _Node->_Min == 0 ? _Rx_unwind_ops::_Loop_greedy : _Rx_unwind_ops::_Loop_restore_vals,
```
Comment (StephanTLavavej) [inline stl/inc/regex]: Suggestion: Extracting the code would make this easier to read (even though it wouldn't save a line).

File: tests/std/tests/VSO_0000000_regex_use/test.cpp [hunk 2]
```diff
@@ -899,6 +899,36 @@ void test_gh_993() {
...
+        assert(false); // adjust test when matching succeeds
+    } catch (const regex_error& ex) {
+        assert(ex.code() == error_stack);
+    }
+
+    try {
+        wregex rgx(L"^http[s]?\\:\\/\\/([^.]+\\.)*github\\.com\\/.*$", icase);
+
+        assert(!regex_match(
+            L"https://www.google.com/"
```
Comment (StephanTLavavej) [inline tests/std/tests/VSO_0000000_regex_use/test.cpp]: Although this was taken from the original bug, we should use example domains instead of one that we own and one that we don't. I also don't know what's encoded in the remainder of the URL and it doesn't appear to be important to the scenario.

File: tests/std/tests/VSO_0000000_regex_use/test.cpp [hunk 3]
```diff
@@ -899,6 +899,36 @@ void test_gh_993() {
...
+
+    try {
+        (void) regex_match(std::string(1025, 'a'), regex("(?:a)+"));
+        assert(false); // adjust test when matching succeeds
+    } catch (const regex_error& ex) {
+        assert(ex.code() == error_stack);
+    }
+
+    try {
+        wregex rgx(L"^http[s]?\\:\\/\\/([^.]+\\.)*github\\.com\\/.*$", icase);
```
Comment (StephanTLavavej) [inline tests/std/tests/VSO_0000000_regex_use/test.cpp]: I recommend using raw string literals whenever possible, to avoid having to mentally reverse C++ string literal escapes.

Comment (StephanTLavavej) [inline tests/std/tests/VSO_0000000_regex_use/test.cpp]: Also, there's unnecessary escaping here (colons and forward slashes don't need to be escaped). Again I know this came from the user repro, and usually messing with a repro is unwise, but the unnecessary escaping obscures what the regex is doing and isn't important for the repro.

File: tests/std/tests/VSO_0000000_regex_use/test.cpp [hunk 4]
```diff
@@ -899,6 +899,36 @@ void test_gh_993() {
...
+
+        assert(!regex_match(
```
Comment (StephanTLavavej) [inline tests/std/tests/VSO_0000000_regex_use/test.cpp:918]: Let's also add a positive test to make sure the regex can match something.

File: tests/std/tests/VSO_0000000_regex_use/test.cpp [hunk 5]
```diff
@@ -2232,6 +2262,89 @@ void test_gh_5792() {
     g_regexTester.should_match("bc", "(?:(?!ab))+bc");
 }
 
+void test_gh_5798() {
+    // GH-5792: <regex>: Process generic loops non-recursively.
```
Comment (StephanTLavavej) [inline tests/std/tests/VSO_0000000_regex_use/test.cpp]: Copy-pasted citation of GH-5792.

File: tests/std/tests/VSO_0000000_regex_use/test.cpp [hunk 6]
```diff
@@ -899,6 +899,36 @@ void test_gh_993() {
     }
 }
 
+void test_gh_997() {
+    // GH-997: <regex>: Grouping within repetition causes regex stack error
+    // GH-1528: <regex>: regex_match gets caught in recursive loop until stack overflow occurs
+
+    try {
+        (void) regex_match(std::string(1025, 'a'), regex("(?:a)+"));
```
Comment (StephanTLavavej) [inline tests/std/tests/VSO_0000000_regex_use/test.cpp]: This test is `using namespace std;`.

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Thanks, this is incredible! :heart_eyes_cat: I pushed some changes to the test, please double-check that I didn't mess anything up.

If the CLA Bot is snoozy I may need to close and reopen this PR.

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
An incredible achievement, thank you! :heart_eyes_cat: :tada: :smile_cat:
