### PR TITLE
<algorithm>: fix GH-1932

### LINKED ISSUE #1932: <algorithm>: Incorrect if constexpr statement in ranges::unique_copy
**Describe the bug**

[algorithm#L4130](https://github.com/microsoft/STL/blob/main/stl/inc/algorithm#L4130):

`if constexpr (input_iterator<_Out> && same_as<iter_value_t<_It>, iter_value_t<_Out>>)`
 
Since there is no short circuit in `if constexpr` statement, this will incorrectly abort compilation when `iter_value_t<_Out>` is ill-formed.
(thanks T.C. for pointing that out).

https://godbolt.org/z/5WvrYs9GM

### PR DESCRIPTION
**Pull request by CaseyCarter**
... by extracting the constant expression we'd like to short-circuit into a concept.

Fixes #1932.

### CODE REVIEW

File: stl/inc/algorithm [hunk 1]
```diff
@@ -4072,9 +4072,12 @@ namespace ranges {
 
     // VARIABLE ranges::unique_copy
     // clang-format off
+    template <class _It, class _Ty>
+    concept _Is_input_with_value_type = input_iterator<_It> && same_as<iter_value_t<_It>, _Ty>;
```
Comment (miscco) [inline stl/inc/algorithm:4076]: I am wondering whether this should be `_Is_input_with_matching_value_type `

**Review by miscco — APPROVED** [review]

File: stl/inc/algorithm (hunk 1 above)
Comment (CaseyCarter) [reply stl/inc/algorithm:4076]: I'm not married to this name. There are only two uses and they're both within 50 lines of this definition, so it doesn't need to be perfect.

**Review by mnatsuhara — APPROVED** [review]

**Review by barcharcraz — APPROVED** [review]

File: tests/std/tests/P0896R4_ranges_alg_unique_copy/test.cpp [hunk 2]
```diff
@@ -142,8 +143,21 @@ constexpr bool run_tests() {
...
 }
 
+void test_gh1932() {
+    // Defend against regression of GH-1932, in which ranges::unique_copy instantiated
+    // iter_value_t<I> for a non-input iterator I.
+
+    std::istringstream str("42 42 42");
+    std::ostringstream result;
+    std::ranges::unique_copy(
+        std::istream_iterator<int>(str), std::istream_iterator<int>(), std::ostream_iterator<int>(result, " "));
```
Comment (StephanTLavavej) [inline tests/std/tests/P0896R4_ranges_alg_unique_copy/test.cpp:153]: This test is already `using namespace std;`. Additionally, it would be nice to use braces to construct temporaries. Not worth resetting MSVC-PR testing, though.

Comment (CaseyCarter) [reply tests/std/tests/P0896R4_ranges_alg_unique_copy/test.cpp:153]:
```suggestion
    istringstream str("42 42 42");
    ostringstream result;
    ranges::unique_copy(istream_iterator<int>{str}, istream_iterator<int>{}, ostream_iterator<int>{result, " "});
```

**Review by StephanTLavavej — APPROVED** [review]

**Comment by CaseyCarter** [comment]
Thanks for fixing this _unique_ bug. (_Copy_ what I did there?)
