### PR TITLE
Formatting `thread::id`, `stacktrace_entry`, and `basic_stacktrace`

### LINKED ISSUE #3447: P2693R1 Formatting `thread::id` And `stacktrace`
WG21-P2693R1 Formatting `thread::id` And `stacktrace`

Feature-test macro (expected):
```cpp
#define __cpp_lib_formatters 202302L
```

### PR DESCRIPTION
**Pull request by JMazurkiewicz**
* Add `_Fill_align_and_width_specs`, `_Fill_align_and_width_specs_setter` and `_Fill_align_and_width_formatter` types. They are use by formatters that accept only *`fill-and-align`* and *`width`* fields (`thread::id` and `stacktrace_entry` in this PR).
* Move `std::call_once` from `<mutex>` to `<xcall_once.h>` to avoid circular dependency. I hope this is OK.
* Implement WG21-P2693R1: formatters for `thread::id`, `stacktrace_entry` and `basic_stacktrace`.
* Fix `operator<<(thread::id)` in all supported C++ modes. See [LLVM-62073](https://github.com/llvm/llvm-project/issues/62073) for bug report and @mordante's rationale.
* Add tests.
* Close #3447.

### CODE REVIEW

File: stl/inc/thread [hunk 1]
```diff
@@ -270,9 +282,38 @@ _NODISCARD inline bool operator>=(thread::id _Left, thread::id _Right) noexcept
 
 _EXPORT_STD template <class _Ch, class _Tr>
 basic_ostream<_Ch, _Tr>& operator<<(basic_ostream<_Ch, _Tr>& _Str, thread::id _Id) {
-    return _Str << _Id._Id;
+    basic_ostringstream<_Ch, _Tr> _Out;
+    _Out.imbue(locale::classic());
+    _Out << _Id._Id;
+    return _Str << _Out.str();
```
Comment (frederick-vs-ja) [inline stl/inc/thread:288]: I guess that `to_string` is sufficient.

File: stl/inc/xcall_once.h [hunk 2]
```diff
@@ -44,6 +47,74 @@ union _Immortalizer_impl { // constructs _Ty, never destroys
...
+    unsigned long _DwFlags;
+    ~_Init_once_completer() {
+        if (!_RENAME_WINDOWS_API(__std_init_once_complete)(&_Once._Opaque, _DwFlags, nullptr)) {
+            __std_init_once_link_alternate_names_and_abort();
+        }
+    }
+};
+
+_EXPORT_STD template <class _Fn, class... _Args>
+void(call_once)(once_flag& _Once, _Fn&& _Fx, _Args&&... _Ax) noexcept(
```
Comment (frederick-vs-ja) [inline stl/inc/xcall_once.h:100]: LGTM. No change requested. I'm constantly surprised at `<xcall_once.h>`'s not providing `call_once`.

File: stl/inc/thread (hunk 1 above)
Comment (JMazurkiewicz) [reply stl/inc/thread:288]: Isn't `to_(w)string` affected by the current C locale?

Comment (frederick-vs-ja) [reply stl/inc/thread:288]: They are not... by default (they are when `_ENFORCE_FACET_SPECIALIZATIONS` is defined as non-zero). E.g. `basic_ostream<char32_t>` works by default despite not guaranteed by the standard.

IIUC we can still emulate `to_string` for other character types.

Comment (frederick-vs-ja) [reply stl/inc/thread:288]: > Isn't `to_(w)string` affected by the current C locale?

Only floating-point overloads are affected by C locale (which is changed by WG21-P2587R3 in C++26).

**Comment by cpplearner** [comment]
Could `_Specs_setter`, `_Chrono_specs_setter` and the new `_Fill_align_and_width_formatter` share some common members? It's a bit awkward to have three identical definitions of `_On_fill` and others.

(Also, [P2286R8](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p2286r8.html) adds *`range-format-spec`* and *`tuple-format-spec`*, which are basically *`fill-and-align`* + *`width`* + type-specific options. It would be nice if the existing machinery can be reused when dealing with their *`fill`*, *`align`*, and *`width`*.)

**Comment by JMazurkiewicz** [comment]
> Could `_Specs_setter`, `_Chrono_specs_setter` and the new `_Fill_align_and_width_formatter` share some common members? It's a bit awkward to have three identical definitions of `_On_fill` and others.

I agree, unifying those setters is necessary, but I'd leave it for another PR, since it would require editing another header (`<chrono>`) and even more LOC.

File: stl/inc/thread (hunk 1 above)
Comment (frederick-vs-ja) [reply stl/inc/thread:288]: After looking into the implementation of `num_put::do_put`, I think we can use `_UIntegral_to_buff` here:

https://github.com/microsoft/STL/blob/2261f7edb760eb3fe0726187c818b796dc7ea798/stl/inc/string#L441

File: stl/inc/format [hunk 3]
```diff
@@ -3934,6 +3934,110 @@ _NODISCARD inline string _Unescape_braces(const _Add_newline _Add_nl, const stri
...
+
+template <class _CharT>
+struct _Fill_align_and_width_specs { // used by thread::id and stacktrace_entry formatters
+    int _Width               = -1;
+    int _Dynamic_width_index = -1;
+    _Fmt_align _Alignment    = _Fmt_align::_None;
+    uint8_t _Fill_length     = 1;
+    // At most one codepoint (so one char32_t or four utf-8 char8_t).
+    _CharT _Fill[4 / sizeof(_CharT)] = {' '};
+};
```
Comment (barcharcraz) [inline stl/inc/format:3946]: I suspect this could be unified with `_Basic_format_specs` and `_Dynamic_format_specs`, I need to work out what that would actually look like though, and it probably requires nontrivial inheritance.

**Comment by barcharcraz** [comment]
At first glance things look pretty good, I'll see if I can figure out how you might be able to eliminate all the duplicate specs setter code without changing a bunch of chrono stuff next week.

File: tests/std/tests/P2693R1_text_formatting_stacktrace/test.cpp [hunk 4]
```diff
@@ -0,0 +1,221 @@
...
+        const int fill_width = static_cast<int>(width - frame_str.size());
+
+        const auto s  = fmt("{:560}", frame);
+        const auto it = ranges::mismatch(views::reverse(s), views::repeat(' ', fill_width)).in1;
+        assert(it.base() == s.end() - fill_width);
+        assert(ranges::equal(ranges::subrange{s.begin(), it.base()}, frame_str));
+    }
+
+    { // width only (replacement field)
+        constexpr int width  = 420;
```
Comment (StephanTLavavej) [inline tests/std/tests/P2693R1_text_formatting_stacktrace/test.cpp:49]: We need to choose another arbitrary number here, sorry.

File: tests/std/tests/P2693R1_text_formatting_stacktrace/test.cpp [hunk 5]
```diff
@@ -0,0 +1,221 @@
...
+        const int fill_width = static_cast<int>(width - frame_str.size());
+
+        const auto s  = fmt("{:{}}", frame, width);
+        const auto it = ranges::mismatch(views::reverse(s), views::repeat(' ', fill_width)).in1;
+        assert(it.base() == s.end() - fill_width);
+        assert(ranges::equal(ranges::subrange{s.begin(), it.base()}, frame_str));
+    }
+
+    { // fill-and align with width
```
Comment (StephanTLavavej) [inline tests/std/tests/P2693R1_text_formatting_stacktrace/test.cpp:58]: Missing dash. Occurs below.

File: tests/std/tests/P2693R1_text_formatting_stacktrace/test.cpp [hunk 6]
```diff
@@ -0,0 +1,221 @@
...
+        fmt("{}}", frame);
+        fmt("}", frame);
+    }
+
+    { // fill-and-align should not contain '{' or '}' characters
+        fmt("{:{^}", frame);
+        fmt("{:{<}", frame);
+    }
+
+    { // sign, #, 0, precision, L or type options are not allowed in format-specs
```
Comment (StephanTLavavej) [inline tests/std/tests/P2693R1_text_formatting_stacktrace/test.cpp:139]: Missing Oxford comma.

File: tests/std/tests/P2693R1_text_formatting_thread_id/test.cpp [hunk 7]
```diff
@@ -0,0 +1,277 @@
...
+    assert(fmt(STR("{:*^}"), id) == STR("0"));
+    assert(fmt(STR("{:=>}"), id) == STR("0"));
+
+    // width only
+    assert(fmt(STR("{:5}"), id) == STR("    0"));
+
+    // width only (replacement field)
+    assert(fmt(STR("{:{}}"), id, 7) == STR("      0"));
+
+    // fill-and align with width
```
Comment (StephanTLavavej) [inline tests/std/tests/P2693R1_text_formatting_thread_id/test.cpp:47]: Missing dash, occurs below.

File: tests/std/tests/P2693R1_text_formatting_thread_id/test.cpp [hunk 8]
```diff
@@ -0,0 +1,277 @@
...
+    { // empty format-spec
+        basic_ostringstream<CharT> ss;
+        ss << id;
+        assert(fmt(STR("{}"), id) == ss.view());
+    }
+
+    { // fill-and-align only
+        basic_ostringstream<CharT> ss;
+        ss.fill('=');
+        ss.setf(ss.flags() | ios_base::left, ios_base::adjustfield);
```
Comment (StephanTLavavej) [inline tests/std/tests/P2693R1_text_formatting_thread_id/test.cpp:180]: Should technically include `<ios>`.

File: tests/std/tests/P2693R1_text_formatting_thread_id/test.cpp [hunk 9]
```diff
@@ -0,0 +1,277 @@
...
+        basic_ostringstream<CharT> ss;
+        ss.fill('*');
+        ss.setf(ss.flags() | ios_base::left, ios_base::adjustfield);
+        ss.width(w);
+        ss << id;
+        assert(fmt(STR("{:*<30}"), id) == ss.view());
+        assert(fmt(STR("{:*<{}}"), id, w) == ss.view());
+    }
+
+    { // check what happens if we change stream's locale, precision and fmtflags other than fill and alignment
```
Comment (StephanTLavavej) [inline tests/std/tests/P2693R1_text_formatting_thread_id/test.cpp:205]: Missing Oxford comma.

File: tests/std/tests/P2693R1_text_formatting_thread_id/test.cpp [hunk 10]
```diff
@@ -0,0 +1,277 @@
...
+        constexpr int w = 25;
+        basic_ostringstream<CharT> ss;
+        ss.imbue(locale{"en-US"});
```
Comment (StephanTLavavej) [inline tests/std/tests/P2693R1_text_formatting_thread_id/test.cpp:208]: Should include `<locale>`.

File: tests/std/tests/P2693R1_text_formatting_thread_id/test.cpp [hunk 11]
```diff
@@ -0,0 +1,277 @@
...
+        fmt(STR("{}}"), id);
+        fmt(STR("}"), id);
+    }
+
+    { // fill-and-align should not contain '{' or '}' characters
+        fmt(STR("{:{^}"), id);
+        fmt(STR("{:{<}"), id);
+    }
+
+    { // sign, #, 0, precision, L or type options are not allowed in format-specs
```
Comment (StephanTLavavej) [inline tests/std/tests/P2693R1_text_formatting_thread_id/test.cpp:237]: Missing Oxford comma.

**Review by StephanTLavavej — COMMENTED** [review]
Thanks! I'll validate and push changes...

**Review by StephanTLavavej — APPROVED** [review]

**Review by barcharcraz — APPROVED** [review]
In order to prevent the code duplication here we'd have to rearrange `_Basic_format_specs` and `_Dynamic_format_specs`, and I'm not sure we can do that without ABI impact.

If we want to unify things we could do something like:

```c++
template<class _CharT>
struct _Really_basic_format_specs {
    int _Width = -1;
    _Fmt_align _Alignment = _Fmt_align::_None;
    uint8_t _Fill_length  = 1;
    // At most one codepoint (so one char32_t or four utf-8 char8_t).
    _CharT _Fill[4 / sizeof(_CharT)] = {' '};
};



template <class _CharT>
struct _Basic_format_specs : _Really_basic_format_specs<_CharT> {
    int _Precision        = -1;
    char _Type            = '\0';
    _Fmt_sign _Sgn        = _Fmt_sign::_None;
    bool _Alt             = false;
    bool _Localized       = false;
    bool _Leading_zero    = false;
};

struct _Dynamic_width_format_specs {
    int _Dynamic_width_index = -1;
};

// used by thread::id and stacktrace_entry formatters
template <class _CharT>
struct _Fill_align_and_width_specs : _Really_basic_format_specs<_CharT>, _Dynamic_width_format_specs { };

template <class _CharT>
struct _Dynamic_format_specs : _Basic_format_specs<_CharT>, _Dynamic_width_format_specs {
    int _Dynamic_precision_index = -1;
};
```

The specs setter classes could be slightly refactored to use either CRTP or to just have a collection of static methods taking the specs to fill in as the first parameter (basically making the setter even closer to members of the specs classes).

Again, this changes the order of the specs members, and the spec class is included by-value as a member of all the formatters, which users are allowed to derive from. This is also a bigger refactor, so I'm comfortable leaving it for later.

**Comment by StephanTLavavej** [comment]
> Again, this changes the order of the specs members, and the spec class is included by-value as a member of all the formatters, which users are allowed to derive from.

That sounds like an unavoidably ABI-breaking change. Sounds like everyone's happy with a follow-up investigation; I suspect that no change will happen as a result.

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
I'm going to pull this from the mirror - we're getting unhandled exceptions in `P2693R1_text_formatting_stacktrace` internally.

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Well, it's not reproing today, *of course*. I've pushed a conflict-free merge with `main` followed by a commit to catch and print exceptions in the test, so we can try to mirror it again.

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
The failure appears to be consistently happening in `fmt("{:{}}", frame, width)` but I haven't been able to figure out what the problem is.

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I've pushed a defensive commit to use `clamp()` to avoid `fill_width` ever being negative. Let's see if this helps...

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
Thanks for implementing this feature! :gear: :heart_eyes_cat: :white_check_mark:
