### PR TITLE
<random>: Fix discrete_distribution result out of range

### LINKED ISSUE #1017: <random>: discrete_distribution can return out-of-bound result
**Describe the bug**

`discrete_distribution` should return an integer `i` such that `0 <= i < n`. However, with certain parameters it can return `n` rarely.

This can lead to UB in `piecewise_constant_distribution`, `piecewise_linear_distribution` and user code that use the result of `discrete_distribution` for array index.

**Command-line test case**

```
C:\Users\He\source\test>type discrete_distribution.cpp
#include <iostream>
#include <random>

using namespace std;

int main() {
    constexpr int bound = 100'000'019;
    discrete_distribution<> dist(bound, 0, 1, [](double) { return 1.0; });
    mt19937 rng;
    rng.discard(862'454'404);

    for (long long i = 0; i < 1'000'000'000'000'000'000; ++i) {
        const auto value = dist(rng);
        if (!(0 <= value && value < bound)) {
            cout << "test failure\n";
            cout << "expected an integer within [0, " << bound << "), got " << value << "\n";
            break;
        }
    }
}

C:\Users\He\source\test>cl /EHsc /W4 /WX /O2 discrete_distribution.cpp
用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.27.29009.1 版
版权所有(C) Microsoft Corporation。保留所有权利。

discrete_distribution.cpp
Microsoft (R) Incremental Linker Version 14.27.29009.1
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:discrete_distribution.exe
discrete_distribution.obj

C:\Users\He\source\test>.\discrete_distribution.exe
test failure
expected an integer within [0, 100000019), got 100000019
```

**STL version**

```
Microsoft Visual Studio Community 2019 Preview
版本 16.7.0 Preview 3.1
```

### PR DESCRIPTION
**Pull request by statementreply**
Fix #1017.

Mathematically, `_Par0._Pcdf.back()` should be one. However, when it is actually slightly smaller than one due to rounding error, there is a small probability that `_Px > _Par0._Pcdf.back()`, and the original code returns the invalid value of `_Par0._Pcdf.size()`.

### CODE REVIEW

**Comment by statementreply** [comment]
Question: do we add a (randomized) test for low probability `<random>` bugs?

File: stl/inc/random [hunk 1]
```diff
@@ -4507,7 +4507,7 @@ private:
     result_type _Eval(_Engine& _Eng, const param_type& _Par0) const {
         double _Px           = _NRAND(_Eng, double);
         const auto _First    = _Par0._Pcdf.begin();
-        const auto _Position = _STD lower_bound(_First, _Par0._Pcdf.end(), _Px);
+        const auto _Position = _STD lower_bound(_First, _STD prev(_Par0._Pcdf.end()), _Px);
```
Comment (CaseyCarter) [inline stl/inc/random:4510]: We have a utility function `_Prev_iter(i)` that's equivalent to `std::prev(i, 1)` except that it uses a single decrement instead of subtracting `1` since decrement is sometimes cheaper for complicated iterator types:
```suggestion
        const auto _Position = _STD lower_bound(_First, _Prev_iter(_Par0._Pcdf.end()), _Px);
```

**Comment by CaseyCarter** [comment]
> Question: do we add a (randomized?) test for low probability `<random>` bugs?
> 
> For this particular bug, the probability of returning an invalid result on each call is on the order of `numeric_limits<double>::epsilon() * sqrt(N)` for the average case and of `numeric_limits<double>::epsilon() * N` for the worst case, depending on distribution parameters and implementation details.

It would be nice to have at least a simple regression test with the repro from the issue. I wouldn't refuse a randomized test, but it seems like that test wouldn't provide much additional marginal coverage. (If you do choose to write a randomized test it needs to dump enough info to reproduce errors when found a la:

https://github.com/microsoft/STL/blob/550713eba27c5803addb6f615d3526400cb2df37/tests/std/tests/P0024R2_parallel_algorithms_set_intersection/test.cpp#L19-L28

**Comment by statementreply** [comment]
I find it necessary to recompile the STL (not just the test code) to make the tests pass/fail after modifying `<random>`. Smells like a ODR issue somewhere?

File: tests/std/include/bad_random_engine.hpp [hunk 2]
```diff
@@ -0,0 +1,192 @@
...
+        friend constexpr bool operator==(const my_sentinel sentinel, const my_iter& iter) noexcept {
+            return iter == sentinel;
+        }
+
+        friend constexpr bool operator!=(const my_sentinel sentinel, const my_iter& iter) noexcept {
+            return !(iter == sentinel);
+        }
+
+    private:
+        value_type current_value_ = 0;
```
Comment (CaseyCarter) [inline tests/std/include/bad_random_engine.hpp:95]: Why the trailing underscore only on `current_value_`?

File: tests/std/include/bad_random_engine.hpp [hunk 3]
```diff
@@ -0,0 +1,192 @@
...
+        limit_dimension = 0;
+        generators[0]   = ++limit_value;
+        return limit_value != sentinel{};
+    }
+
+    generator generators[Dimension] = {};
+    generator limit_value{};
+    int limit_dimension      = 0;
+    int current_dimension    = 0;
+    bool has_cycled_through_ = false;
```
Comment (CaseyCarter) [inline tests/std/include/bad_random_engine.hpp:188]: Ditto "why exactly one non-static data member with a trailing underscore?"

File: tests/std/tests/GH_001017_discrete_distribution_out_of_range/bad_random_engine.hpp [hunk 4]
```diff
@@ -0,0 +1,192 @@
...
+template <typename UInt, int Width = std::numeric_limits<UInt>::digits, int Dimension = 1>
+class bad_random_engine {
+    // Generates bit patterns with at most two transitions between 0's and 1's.
+    // (e.g. 00000000, 11111111, 00001111, 11110000, 00011000, 11100111)
+    // When its output is grouped into subsequences of length Dimension, it cycles through all possible subsequences
+    // containing only such bit patterns. Bit patterns with few 1's or few 0's are generated first, starting from all
+    // 0's and all 1's.
+
+    static_assert(std::is_integral<UInt>::value, "bad_random_engine: UInt should be unsigned integeral type");
+    static_assert(std::is_unsigned<UInt>::value, "bad_random_engine: UInt should be unsigned integeral type");
```
Comment (StephanTLavavej) [inline tests/std/tests/GH_001017_discrete_distribution_out_of_range/bad_random_engine.hpp:110]: Fix comment typos. Also, MSVC supports the type traits variable templates unconditionally, so we use them everywhere (they were added in C++17, but we implemented them before Standard modes, so they're available in `/std:c++14` which actually means "C++14 plus all of the C++17 stuff we had implemented at the time, to avoid breaking code unnecessarily").
```suggestion
    static_assert(std::is_integral_v<UInt>, "bad_random_engine: UInt should be unsigned integral type");
    static_assert(std::is_unsigned_v<UInt>, "bad_random_engine: UInt should be unsigned integral type");
```

File: tests/std/tests/GH_001017_discrete_distribution_out_of_range/bad_random_engine.hpp [hunk 5]
```diff
@@ -0,0 +1,192 @@
...
+        friend constexpr bool operator==(const my_iter& a, const my_iter& b) noexcept {
+            return *a == *b;
+        }
+
+        friend constexpr bool operator!=(const my_iter& a, const my_iter& b) noexcept {
+            return !(a == b);
+        }
+
+        friend constexpr bool operator==(const my_iter& iter, const my_sentinel sentinel) noexcept {
+            (void) sentinel;
```
Comment (StephanTLavavej) [inline tests/std/tests/GH_001017_discrete_distribution_out_of_range/bad_random_engine.hpp:78]: While this is correct, it's simpler to use an unnamed parameter, and then our conventions don't need `const` (can't modify something with no name :smile_cat: ):
```suggestion
        friend constexpr bool operator==(const my_iter& iter, my_sentinel) noexcept {
```

**Comment by CaseyCarter** [comment]
Thanks for the bugfix, @statementreply!
