### PR TITLE
Fix weak_ptr conversions, preserving control blocks for expired objects

### LINKED ISSUE #1102: <memory>: weak_ptr conversions don't preserve control blocks for expired objects
Bug Report
---

```
C:\Temp>type weakptrtest.cpp
```
```cpp
#include <iostream>
#include <memory>

template <typename T, typename W>
bool EqualOwnership(const std::weak_ptr<T>& p, const std::weak_ptr<W>& q)
{
        return !p.owner_before(q) && !q.owner_before(p);
}

template <typename T>
bool IsEmpty(const std::weak_ptr<T>& p)
{
        return EqualOwnership(p, std::weak_ptr<T>{});
}

class Base {};
class Derived : public Base {};

int main()
{
        std::weak_ptr<Derived> wpDerived;

        {
                std::shared_ptr<Derived> sp = std::make_shared<Derived>();
                wpDerived = sp;
        }

        if (IsEmpty(wpDerived))
        {
                std::cout << "This line isn't printed, which is good, wpDerived should not be empty even though it is expired \n";
        }

        // Test copy constructing a pointer of same type
        std::weak_ptr<Derived> wpDerived_CopyConstruct(wpDerived);
        if (IsEmpty(wpDerived_CopyConstruct) || !EqualOwnership(wpDerived_CopyConstruct, wpDerived))
        {
                std::cout << "This line isn't printed, which is good, copy construction should not change ownership \n";
        }

        // Test assigning to a pointer of same type
        std::weak_ptr<Derived> wpDerived_Assign;
        wpDerived_Assign = wpDerived;
        if (IsEmpty(wpDerived_Assign) || !EqualOwnership(wpDerived_Assign, wpDerived))
        {
                std::cout << "This line isn't printed, which is good, assignment should not change ownership \n";
        }

        // Test copy constructing a base pointer
        std::weak_ptr<Base> wpBase_CopyConstruct(wpDerived);
        if (IsEmpty(wpBase_CopyConstruct))
        {
                std::cout << "Error! Copy construction from a non-empty pointer should not result in an empty pointer \n";
        }

        if (!EqualOwnership(wpBase_CopyConstruct, wpDerived))
        {
                std::cout << "Error! Copy construction should not change ownership \n";
        }

        // Test assigning to a base pointer
        std::weak_ptr<Base> wpBase_Assign;
        wpBase_Assign = wpDerived;
        if (IsEmpty(wpBase_Assign))
        {
                std::cout << "Error! Assignment from a non-empty pointer should not result in an empty pointer \n";
        }

        if (!EqualOwnership(wpBase_Assign, wpDerived))
        {
                std::cout << "Error! Assignment should not change ownership \n";
        }
}
```
```
C:\Temp>cl /EHsc /nologo /W4 weakptrtest.cpp
weakptrtest.cpp

C:\Temp>weakptrtest
Error! Copy construction from a non-empty pointer should not result in an empty pointer
Error! Copy construction should not change ownership
Error! Assignment from a non-empty pointer should not result in an empty pointer
Error! Assignment should not change ownership
```

Originally reported as DevCom-1127204. Also tracked by VSO-1163049 / [AB#1163049](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1163049).

Analysis
---

This happens because `weak_ptr` contains the following code:

https://github.com/microsoft/STL/blob/35ce1cf44af6be5e6758ec79cfa61fa16995ce8b/stl/inc/memory#L2269-L2272
https://github.com/microsoft/STL/blob/35ce1cf44af6be5e6758ec79cfa61fa16995ce8b/stl/inc/memory#L2278-L2282

The reason for `_Other.lock()` is extremely subtle, to handle the following scenario:

https://github.com/microsoft/STL/blob/35ce1cf44af6be5e6758ec79cfa61fa16995ce8b/tests/std/tests/Dev10_851347_weak_ptr_virtual_inheritance/test.cpp#L10-L51

That is, when converting `weak_ptr<Source>` to `weak_ptr<Destination>`, we have to convert `Source*` to `Destination*` although the `Source` object may have been destroyed. Usually, this pointer conversion can be performed with compile-time information, as either no pointer adjustment is necessary (e.g. conversions to `void*`, conversions adding `const`, conversions in linear inheritance scenarios), or a statically-known offset needs to be added (e.g. conversions in multiple inheritance scenarios).

However, sometimes the pointer conversion needs run-time information requiring the `Source` object to be alive. This happens in **virtual inheritance** scenarios, where the offset from `Source` to `Destination` depends on the layout of the most-derived object. The Standardese for this is WG21-N4861 [basic.life]/6.3.

The `weak_ptr` Standardese doesn't mention virtual inheritance at all, which is potentially a defect. However, it may be possible to make everything work, without adding a special case to the Standardese or requesting a compiler builtin to detect when pointer conversions would involve traversing virtual bases.

I believe the key is that while `weak_ptr`'s control block can be observed through `owner_before()` as in the test case above, the stored pointer can't be directly observed. The only way to observe it (which is why we need to store it) is by `lock()`ing to `shared_ptr`. That's specified as `expired() ? shared_ptr<T>() : shared_ptr<T>(*this)`, and `expired()` is `use_count() == 0`, and `use_count()` returns "`0` if `*this` is empty; otherwise, the number of `shared_ptr` instances that share ownership with `*this`".

So, when the `weak_ptr` is empty (no control block) or there are no `shared_ptr` instances left (the object is dead), then `expired()` is true and `lock()` returns `shared_ptr<T>()` with both a null stored pointer and no control block. So, we don't need to convert the addresses of dead objects, as the result is unobservable.

I believe we can fix this bug by:

* If there's no control block, then store a null object pointer and null control block.
* Otherwise, attempt to `lock()` and then:
  + If we're successful, do what we're doing today - convert the object pointer while it's guaranteed to be alive, and add a weak reference to the control block.
  + If we're unsuccessful, store a null object pointer (as the value doesn't matter), and add a weak reference to the control block (fixing this bug).

(We can probably write this directly, like `_Construct_from_weak` and `_Weakly_construct_from`.)

A compiler builtin would make this more efficient (no reason to `lock()` in non-virtual-inheritance scenarios) but I don't think it's needed for correctness.

### PR DESCRIPTION
**Pull request by StephanTLavavej**
Fixes #1102. This adds a few comments to the product code, explaining what's going on. Then, I enhanced our existing test for `weak_ptr` conversions to test `owner_before` and then use `owner_before` to test that control blocks are preserved. Finally, I added a small test for the behavior of virtual inheritance conversions before the object expired, since we weren't actually testing that.

Performance note: it would be possible to detect `T*` to `const T*` and avoid the `_Incref_nz` (which we did before this PR too, in the form of `_Other.lock()`); I could file an issue about that after merging this PR if anyone is interested. At this time, we don't know if it's possible to detect virtual base traversal in general, without a compiler builtin.

### CODE REVIEW

File: stl/inc/memory [hunk 1]
```diff
@@ -794,6 +794,24 @@ protected:
         }
     }
 
+    template <class _Ty2>
+    void _Weakly_construct_avoiding_expired_conversions_from(const _Ptr_base<_Ty2>& _Other) noexcept {
+        // implement weak_ptr's converting ctors
+        if (_Other._Rep) {
+            _Rep = _Other._Rep; // always share ownership
+            _Rep->_Incwref();
```
Comment (CaseyCarter) [inline stl/inc/memory:802]: Should we have an rvalue version of this function to avoid the extra increment and decrement of the weak reference count?

File: tests/std/tests/Dev10_851347_weak_ptr_virtual_inheritance/test.cpp [hunk 2]
```diff
@@ -4,48 +4,109 @@
 #include <assert.h>
 #include <memory>
 #include <utility>
-
 using namespace std;
 
+// Also test GH-1102 "<memory>: weak_ptr conversions don't preserve control blocks for expired objects"
+template <typename T, typename U>
```
Comment (CaseyCarter) [inline tests/std/tests/Dev10_851347_weak_ptr_virtual_inheritance/test.cpp:10]: Should this use `class` for template type parameters to be consistent with the product code, or do you think we should continue to use arbitrary styles in test code?

File: stl/inc/memory (hunk 1 above)
Comment (StephanTLavavej) [reply stl/inc/memory:802]: Good idea! The original code predated rvalue references.

File: tests/std/tests/Dev10_851347_weak_ptr_virtual_inheritance/test.cpp (hunk 2 above)
Comment (StephanTLavavej) [reply tests/std/tests/Dev10_851347_weak_ptr_virtual_inheritance/test.cpp:10]: I think we should file an issue about making the test code consistent (I am most notably thinking of const and using-directives). We should also consider typename-ing the product code although that would change a lot of lines.

Comment (StephanTLavavej) [reply tests/std/tests/Dev10_851347_weak_ptr_virtual_inheritance/test.cpp:10]: Filed #1110.

File: stl/inc/memory [hunk 3]
```diff
@@ -796,7 +796,7 @@ protected:
 
     template <class _Ty2>
     void _Weakly_construct_avoiding_expired_conversions_from(const _Ptr_base<_Ty2>& _Other) noexcept {
-        // implement weak_ptr's converting ctors
+        // implement weak_ptr's converting copy ctor
```
Comment (CaseyCarter) [inline stl/inc/memory:799]: I'm not fond of the phrase "converting copy/move constructor", it suggests that the constructor being described is a copy/move constructor with some additional properties which is definitely not the case. Could we instead refer to these as "lvalue/rvalue converting constructor" or "copy/move converting constructor"?

File: stl/inc/memory [hunk 4]
```diff
@@ -812,6 +812,22 @@ protected:
         }
     }
 
+    template <class _Ty2>
+    void _Move_construct_avoiding_expired_conversions_from(_Ptr_base<_Ty2>&& _Other) noexcept {
```
Comment (CaseyCarter) [inline stl/inc/memory:816]: (Trigger warning: I have an irrational aversion to calling any and everything that involves an rvalue "move meow" when we wouldn't call the lvalue equivalent "copy meow".) Should we name the earlier function `_Copy_construct_meow` for consistency? Should these functions be `_Weakly convert_lvalue_avoiding_meow` and `_Weakly convert_rvalue_avoiding_meow`?

File: stl/inc/memory [hunk 5]
```diff
@@ -2295,8 +2311,7 @@ public:
 
     template <class _Ty2, enable_if_t<_SP_pointer_compatible<_Ty2, _Ty>::value, int> = 0>
     weak_ptr(weak_ptr<_Ty2>&& _Other) noexcept { // move construct from _Other
```
Comment (CaseyCarter) [inline stl/inc/memory:2313]: Pre-existing rage at "move construct from other".

File: stl/inc/memory (hunk 3 above)
Comment (StephanTLavavej) [reply stl/inc/memory:799]: I like "copy/move converting constructor". Globally cleaned up 5 occurrences.

File: stl/inc/memory (hunk 4 above)
Comment (StephanTLavavej) [reply stl/inc/memory:816]: `_Weakly_convert_lvalue_avoiding_expired_conversions` and `_Weakly_convert_rvalue_avoiding_expired_conversions` it is.

File: stl/inc/memory (hunk 5 above)
Comment (StephanTLavavej) [reply stl/inc/memory:2313]: I'll just drop these comments - they add no value and we don't comment the assigns.
