### PR TITLE
Prettify STL error output

### LINKED ISSUE #2896: Should STL errors use `pragma message` in order to make the output prettier/more obvious?
Currently, our STL errors look like:

```cxx
#error STL1003: Unexpected compiler, expected C++ compiler.
```

This results in the following output from MSVC:

```
C:\Users\nimazzuc\projects\stl\out\x64\out/inc\yvals_core.h(687): fatal error C1189: #error STL1003: Unexpected compiler, expected C++ compiler.
```

This is as opposed to our STL warnings, which result in much prettier output:

```
C:\Users\nimazzuc\projects\stl\out\x64\out/inc\yvals.h(238): warning STL4000: _STATIC_CPPLIB is deprecated and will be REMOVED.
```

Do we wish to use `pragma message` instead, so that we get prettier output?

Something like:

```cxx
// yvals_core.h
// preprocessor fun
#define _STL_PRAGMA(PRAGMA) _Pragma(#PRAGMA)
#define _STL_PRAGMA_MESSAGE(MESSAGE) _STL_PRAGMA(message(MESSAGE))

// note: clang-format does weird things to this
// clang-format off
#define _ERROR_MESSAGE(NUMBER, MESSAGE) \
    _STL_PRAGMA_MESSAGE(__FILE__ "(" _CRT_STRINGIZE(__LINE__) "): error STL" #NUMBER ": " MESSAGE) \
    static_assert(false, "Error in C++ Standard Library usage.")
// clang-format on
```

called like:

```cxx
#ifndef __cplusplus
_ERROR_MESSAGE(1003, "Unexpected compiler, expected C++ compiler.");
#endif
```

resulting in the following output:

```
PS C:\..\nimazzuc\projects\stl-tests> cl /c test.cxx
Microsoft (R) C/C++ Optimizing Compiler Version 19.33.31517 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

test.cxx
test.cxx(12): error STL1004: Unexpected compiler, expected C++ compiler.
test.cxx(12): error C2338: static_assert failed: 'Error in C++ Standard Library usage.'
```

which I at least believe is far more readable (and is probably better for VS diagnostics as well)

(if we do make this change, we should do the same pragma preprocessor nonsense for `_WARNING_MESSAGE`

### PR DESCRIPTION
**Pull request by strega-nil-ms**
Fixes #2896 

Before:

```
PS ...\stl-tests> cl /Tc .\stl-warnings.cxx
Microsoft (R) C/C++ Optimizing Compiler Version 19.33.31517 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

stl-warnings.cxx
...\yvals_core.h(23): fatal error C1189: #error:  STL1003: Unexpected compiler, expected C++ compiler.
```

After

```
PS ...\stl-tests> cl /Tc .\stl-warnings.cxx
Microsoft (R) C/C++ Optimizing Compiler Version 19.33.31517 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

stl-warnings.cxx
...\yvals_core.h(432): error STL1003: Unexpected compiler, expected C++ compiler.
...\yvals_core.h(432): error C2338: static_assert failed: 'Error in C++ Standard Library usage.'
```

### CODE REVIEW

File: stl/inc/yvals.h [hunk 1]
```diff
@@ -230,12 +230,10 @@ _STL_DISABLE_CLANG_WARNINGS
 
 #include <use_ansi.h>
 
-#define _WARNING_MESSAGE(NUMBER, MESSAGE) __FILE__ "(" _CRT_STRINGIZE(__LINE__) "): warning " NUMBER ": " MESSAGE
-
 #ifdef _STATIC_CPPLIB
 #ifndef _DISABLE_DEPRECATE_STATIC_CPPLIB
 #ifdef _DLL
-#pragma message(_WARNING_MESSAGE("STL4000", "_STATIC_CPPLIB is deprecated and will be REMOVED."))
+_EMIT_STL_WARNING(4000, "_STATIC_CPPLIB is deprecated and will be REMOVED.");
```
Comment (StephanTLavavej) [inline stl/inc/yvals.h:236]: This extracts `STL` into the central macros, but I believe that being able to search for `STL4000` in the codebase and find where it's being emitted is important. Although it is slightly redundant, I would prefer to see `STL4000` etc. mentioned in the usage sites.

(For a related example, the compiler's internal sources mention `C4996` etc. when it emits warnings, and I have found this searchability to be very useful. Plain numbers are much harder to search for.)

At a minimum, this makes it easy to search for warning/error number uniqueness.

File: stl/inc/yvals_core.h [hunk 2]
```diff
@@ -415,6 +411,23 @@
 #include <vcruntime.h>
 #include <xkeycheck.h> // The _HAS_CXX tags must be defined before including this.
 
+#define _STL_PRAGMA(PRAGMA)          _Pragma(#PRAGMA)
```
Comment (StephanTLavavej) [inline stl/inc/yvals_core.h:414]: The CUDA and Intel compilers had trouble with Standard `_Pragma`:

https://github.com/microsoft/STL/blob/04ee87830a404437f1691d6a3e8809e4986d8493/stl/inc/yvals_core.h#L590-L593

I don't know if this changed for CUDA 11.6 or if it's still a problem for Intel. Until we know for sure, I'd recommend making this switch between `_Pragma` and `__pragma`.

File: stl/inc/yvals_core.h [hunk 3]
```diff
@@ -415,6 +411,23 @@
...
+#define _STL_PRAGMA_MESSAGE(MESSAGE) _STL_PRAGMA(message(MESSAGE))
+#define _EMIT_STL_MESSAGE(MESSAGE)   _STL_PRAGMA_MESSAGE(__FILE__ "(" _CRT_STRINGIZE(__LINE__) "): " MESSAGE)
+
+// clang-format off
+#define _EMIT_STL_WARNING(NUMBER, MESSAGE) \
+    _EMIT_STL_MESSAGE("warning STL" #NUMBER ": " MESSAGE) \
+    static_assert(1, "")
+#define _EMIT_STL_ERROR(NUMBER, MESSAGE) \
+    _EMIT_STL_MESSAGE("error STL" #NUMBER ": " MESSAGE) \
+    static_assert(0, "Error in C++ Standard Library usage.")
```
Comment (StephanTLavavej) [inline stl/inc/yvals_core.h:424]: `static_assert` contextually converts its first operand to `bool`, so it would be simpler to say `true` and `false` here instead of `1` and `0`. (That is, if we need a `bool`, we conventionally use a `bool` instead of an integer constant.)

File: stl/inc/yvals.h [hunk 4]
```diff
@@ -230,12 +230,10 @@ _STL_DISABLE_CLANG_WARNINGS
 
 #include <use_ansi.h>
 
-#define _WARNING_MESSAGE(NUMBER, MESSAGE) __FILE__ "(" _CRT_STRINGIZE(__LINE__) "): warning " NUMBER ": " MESSAGE
```
Comment (StephanTLavavej) [inline stl/inc/yvals.h:233]: Note the stealth merge conflict with #2061. (Both PRs are deleting these lines, but #2061 moves them to `yvals_core.h` and introduces many uses.)

File: stl/inc/yvals_core.h (hunk 3 above)
Comment (strega-nil) [reply stl/inc/yvals_core.h:424]: Note the comment a few lines above.

Comment (Osyotr) [reply stl/inc/yvals_core.h]: Doesn't `static_assert(false)` make this code IFNDR?

Comment (strega-nil) [reply stl/inc/yvals_core.h]: No, it's in a macro definition, so unless the macro gets expanded it won't be anything; otherwise, it's fully ill-formed.

Comment (CaseyCarter) [reply stl/inc/yvals_core.h]: > Note the comment a few lines above.

`// clang-format off`? `// The _HAS_CXX tags must be defined before including this.`?

Comment (strega-nil-ms) [reply stl/inc/yvals_core.h]: ... did I delete the comment before pushing...?

**Comment by strega-nil-ms** [comment]
Given that people generally seem happy with the idea of the changes, marking non-draft

**Comment by StephanTLavavej** [comment]
Need to merge `main` in order to pick up #2061.

File: stl/inc/coroutine [hunk 5]
```diff
@@ -14,7 +14,7 @@
     "The contents of <coroutine> are not available with /await. "  \
     "Remove /await or use /await:strict for standard coroutines. " \
     "Use <experimental/coroutine> for legacy /await support."
-#pragma message(_WARNING_MESSAGE("STL4039", _STL4039_COROUTINE))
+_EMIT_STL_WARNING("STL4039", _STL4039_COROUTINE));
 #undef _STL4039_COROUTINE // TRANSITION, DevCom-1479701
 #else // ^^^ /await ^^^ / vvv no /await vvv
 #ifndef __cpp_lib_coroutine
```
Comment (StephanTLavavej) [inline stl/inc/coroutine:20]: The tests `Dev09_119644_compiler_option_gz`, `GH_001411_core_headers`, and `GH_002711_Zc_alignedNew-` are failing due to line 22:

```
D:\build\out\inc\coroutine(22): error C2220: the following warning is treated as an error
D:\build\out\inc\coroutine(22): warning C4083: expected 'string'; found identifier '_WARNING_MESSAGE'
```

**Review by StephanTLavavej — CHANGES_REQUESTED** [review]

File: stl/inc/coroutine (hunk 5 above)
Comment (strega-nil-ms) [reply stl/inc/coroutine:20]: ah, that wasn't found by my regex, thanks!

File: stl/inc/yvals_core.h [hunk 6]
```diff
@@ -413,23 +420,26 @@
 #include <vcruntime.h>
 #include <xkeycheck.h> // The _HAS_CXX tags must be defined before including this.
 
-#define _STL_PRAGMA(PRAGMA)          _Pragma(#PRAGMA)
+// Note that _STL_PRAGMA is load-bearing;
+// it still needs to exist even once CUDA and ICC support _Pragma.
+#if defined(__CUDACC__) || defined(__INTEL_COMPILER)
+#define _STL_PRAGMA(PRAGMA) __pragma(#PRAGMA)
```
Comment (CaseyCarter) [inline stl/inc/yvals_core.h:426]: Did you intend to replace the definition of `_STL_PRAGMA` on line 421? This redefinition with a different expansion makes the program ill-formed.

File: stl/inc/yvals_core.h [hunk 7]
```diff
@@ -413,23 +420,26 @@
...
+#if defined(__CUDACC__) || defined(__INTEL_COMPILER)
+#define _STL_PRAGMA(PRAGMA) __pragma(#PRAGMA)
+#else
+#define _STL_PRAGMA(PRAGMA) _Pragma(#PRAGMA)
+#endif
+
 #define _STL_PRAGMA_MESSAGE(MESSAGE) _STL_PRAGMA(message(MESSAGE))
 #define _EMIT_STL_MESSAGE(MESSAGE)   _STL_PRAGMA_MESSAGE(__FILE__ "(" _CRT_STRINGIZE(__LINE__) "): " MESSAGE)
 
 // clang-format off
```
Comment (CaseyCarter) [inline stl/inc/yvals_core.h:434]: Should we move the `STL` into the `NUMBER` arguments to keep usage of `_EMIT_STL_WARNING` consistent with `_EMIT_STL_ERROR`?

File: stl/inc/yvals_core.h [hunk 8]
```diff
@@ -413,23 +420,26 @@
...
 #define _EMIT_STL_WARNING(NUMBER, MESSAGE) \
```
Comment (CaseyCarter) [inline stl/inc/yvals_core.h:435]: Pre-existing: Why `1` instead of `true`? This line should be consistent with 437.

File: stl/inc/yvals_core.h [hunk 9]
```diff
@@ -413,23 +420,26 @@
...
-    _EMIT_STL_MESSAGE("warning STL" #NUMBER ": " MESSAGE) \
-    static_assert(1, "")
+    _EMIT_STL_MESSAGE("warning " #NUMBER ": " MESSAGE) \
```
Comment (CaseyCarter) [inline stl/inc/yvals_core.h:436]: Wat? I think we have some bad conflict resolution going on. Please audit this file because much of it makes no sense.

**Review by CaseyCarter — CHANGES_REQUESTED** [review]

File: stl/inc/yvals_core.h (hunk 6 above)
Comment (CaseyCarter) [reply stl/inc/yvals_core.h:426]: Nevermind: apparently "Changes since my last review" flipped out and was showing me garbage.

File: stl/inc/yvals_core.h [hunk 10]
```diff
@@ -19,8 +19,11 @@
 
 #if _STL_COMPILER_PREPROCESSOR
 
+// This does not use `_EMIT_STL_ERROR`, as it needs to be checked before we include anything else.
+// However, `_EMIT_STL_ERROR` has a dependency on `_CRT_STRINGIZE`, defined in `<vcruntime.h>`
 #ifndef __cplusplus
-#error STL1003: Unexpected compiler, expected C++ compiler.
+#pragma message(__FILE__ "(1): STL1003: Unexpected compiler, expected C++ compiler.");
```
Comment (CaseyCarter) [inline stl/inc/yvals_core.h:25]: Should we hard-code this line number to 25 instead of 1? Yes, it will be a PITA to maintain, but I'm concerned that the users who are confused enough to encounter this error will be _really_ confused looking at line 1 and trying to figure out what triggers it.

File: stl/inc/yvals_core.h (hunk 7 above)
Comment (CaseyCarter) [reply stl/inc/yvals_core.h:434]: Nevermind: Garbage in / Garbage out.

File: stl/inc/yvals_core.h (hunk 8 above)
Comment (CaseyCarter) [reply stl/inc/yvals_core.h:435]: Nevermind: Garbage in / Garbage out.

File: stl/inc/yvals_core.h (hunk 9 above)
Comment (CaseyCarter) [reply stl/inc/yvals_core.h:436]: Nevermind: Garbage in / Garbage out.

**Review by CaseyCarter — APPROVED** [review]

File: stl/inc/yvals_core.h (hunk 7 above)
Comment (strega-nil-ms) [reply stl/inc/yvals_core.h:434]: I feel like your "Changes since last review" is still flipping out.

File: stl/inc/yvals_core.h (hunk 10 above)
Comment (strega-nil-ms) [reply stl/inc/yvals_core.h:25]: that's a fair enough point; I wish we could use `_CRT_STRINGIZE` here -.-

File: stl/inc/yvals_core.h (hunk 7 above)
Comment (CaseyCarter) [reply stl/inc/yvals_core.h:437]: Yeah this entire review is bogus. The next one is not.

**Review by CaseyCarter — APPROVED** [review]

File: stl/inc/coroutine [hunk 11]
```diff
@@ -10,16 +10,13 @@
...
 #ifdef _RESUMABLE_FUNCTIONS_SUPPORTED
-#define _STL4039_COROUTINE                                         \
-    "The contents of <coroutine> are not available with /await. "  \
-    "Remove /await or use /await:strict for standard coroutines. " \
-    "Use <experimental/coroutine> for legacy /await support."
-#pragma message(_WARNING_MESSAGE("STL4039", _STL4039_COROUTINE))
+_EMIT_STL_WARNING("STL4039", "The contents of <coroutine> are not available with /await. "
+                             "Remove /await or use /await:strict for standard coroutines. "
+                             "Use <experimental/coroutine> for legacy /await support.");
 #undef _STL4039_COROUTINE // TRANSITION, DevCom-1479701
```
Comment (StephanTLavavej) [inline stl/inc/coroutine:16]: `_STL4039_COROUTINE` is no longer being defined, so it doesn't need to be undeffed. Ditto `_STL4038_COROUTINE` below.

File: stl/inc/yvals_core.h [hunk 12]
```diff
@@ -417,7 +423,25 @@
 #include <vcruntime.h>
 #include <xkeycheck.h> // The _HAS_CXX tags must be defined before including this.
 
-#define _WARNING_MESSAGE(NUMBER, MESSAGE) __FILE__ "(" _CRT_STRINGIZE(__LINE__) "): warning " NUMBER ": " MESSAGE
+// Note that _STL_PRAGMA is load-bearing;
+// it still needs to exist even once CUDA and ICC support _Pragma.
+#if defined(__CUDACC__) || defined(__INTEL_COMPILER)
+#define _STL_PRAGMA(PRAGMA) __pragma(#PRAGMA)
```
Comment (StephanTLavavej) [inline stl/inc/yvals_core.h:429]: This is incorrect because Standard `_Pragma` takes a string, while classic `__pragma` takes raw tokens:

https://github.com/microsoft/STL/blob/b7e0365b5e2f9de738e8fbea42b6cc6880efe531/stl/inc/yvals_core.h#L590-L602

This can be verified with MSVC itself (as checking CUDA/Intel is logistically difficult), by commenting out the conditional logic and always using classic `__pragma`. In that case, this happens:

```
D:\GitHub\STL>type meow.cpp
#include <charconv>
int main() {}

D:\GitHub\STL>cl /EHsc /nologo /W4 /std:c++14 meow.cpp
meow.cpp
D:\GitHub\STL\out\build\x64\out\inc\charconv(13): warning C4081: expected 'identifier'; found 'string'
```

Removing the stringizing for classic `__pragma` fixes the warning message:

```
D:\GitHub\STL>cl /EHsc /nologo /W4 /std:c++14 meow.cpp
meow.cpp
D:\GitHub\STL\out\build\x64\out\inc\charconv(13): warning STL4038: The contents of <charconv> are available only with C++17 or later.
```

File: stl/inc/coroutine [hunk 13]
```diff
@@ -10,16 +10,13 @@
 #if _STL_COMPILER_PREPROCESSOR
 
 #ifdef _RESUMABLE_FUNCTIONS_SUPPORTED
-#define _STL4039_COROUTINE                                         \
-    "The contents of <coroutine> are not available with /await. "  \
-    "Remove /await or use /await:strict for standard coroutines. " \
-    "Use <experimental/coroutine> for legacy /await support."
-#pragma message(_WARNING_MESSAGE("STL4039", _STL4039_COROUTINE))
+_EMIT_STL_WARNING("STL4039", "The contents of <coroutine> are not available with /await. "
```
Comment (StephanTLavavej) [inline stl/inc/coroutine:13]: STL4039 shouldn't be quoted here. Compare:

```
D:\GitHub\STL>type meow.cpp
#include <coroutine>
int main() {}

D:\GitHub\STL>cl /EHsc /nologo /W4 /std:c++14 meow.cpp
meow.cpp
D:\GitHub\STL\out\build\x64\out\inc\coroutine(18): warning STL4038: The contents of <coroutine> are available only with C++20 or later or /await:strict.

D:\GitHub\STL>cl /EHsc /nologo /W4 /std:c++14 /await meow.cpp
meow.cpp
D:\GitHub\STL\out\build\x64\out\inc\coroutine(15): warning "STL4039": The contents of <coroutine> are not available with /await. Remove /await or use /await:strict for standard coroutines. Use <experimental/coroutine> for legacy /await support.
```

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
@strega-nil-ms @CaseyCarter I've pushed a correctness fix, message appearance fix, and completed workaround removal - please double-check :smile_cat:

**Comment by strega-nil-ms** [comment]
Thanks @StephanTLavavej, looks good to me :)

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Review by CaseyCarter — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Thanks for improving how these errors are displayed! :sparkles: :tada: :smiley_cat:
