### PR TITLE
Test _Countl_zero_bsr with a dedicated test

### LINKED ISSUE #1120: <bit>: Test _Countl_zero_bsr() internal helper
Recommended by @barcharcraz in https://github.com/microsoft/STL/pull/1108#discussion_r463279067 .

After merging #1108, `<bit>` is going to have an internal helper `_Countl_zero_bsr()` for x86/x64 that's active only for very old processors; therefore it will receive no regular testing, although it is necessary for correctness. While we've manually tested it for this PR, we should investigate adding automated testing by directly calling the helper (which we generally avoid doing, but this merits a special exception).

### PR DESCRIPTION
**Pull request by AlexGuteniev**
Resolves #1120

I thought about it a bit and think that a direct test is enough.

### CODE REVIEW

File: tests/std/tests/GH_001103_countl_zero_correctness/test.cpp [hunk 1]
```diff
@@ -0,0 +1,51 @@
...
+
+// Since the fallback intrinsic is available on ARM too, don't need to exclude ARM
+
+// Currently need this test only in C++20 mode,
+// May update to older C++ if the helper is used internally too, for example in <bitset>
+
+using namespace std;
+
+int main() {
+#ifdef _CHAR_UNSIGNED
```
Comment (BillyONeal) [inline tests/std/tests/GH_001103_countl_zero_correctness/test.cpp:18]: I believe these are required regardless of the signed-ness of `char`. Also note that our default is that char is signed, so I don't think this block is tested in GitHub right now.

Comment (AlexGuteniev) [reply tests/std/tests/GH_001103_countl_zero_correctness/test.cpp:18]: count"_" only work for unsigned types, signed will fail test

Comment (barcharcraz) [reply tests/std/tests/GH_001103_countl_zero_correctness/test.cpp:18]: also: all the <bit> functions are sfiane'd out for signed char (and char, I think, probably.... boy char is an odd type.)

Comment (AlexGuteniev) [reply tests/std/tests/GH_001103_countl_zero_correctness/test.cpp:18]: maybe remove this block altogether?

Comment (StephanTLavavej) [reply tests/std/tests/GH_001103_countl_zero_correctness/test.cpp:18]: We have an extremely small number of `/J` tests (this is the option that alters the signedness of char) and I don't think it's worth testing further.

Comment (StephanTLavavej) [reply tests/std/tests/GH_001103_countl_zero_correctness/test.cpp:18]: Looking at the Standard constraint on `countl_zero`, "`T` is an unsigned integer type", that specifically restricts it to be `unsigned char`, `unsigned short`, `unsigned int`, `unsigned long`, and `unsigned long long`. (We have no extended integer types.) So this `char` coverage should be completely removed.

File: tests/std/tests/GH_001103_countl_zero_correctness/test.cpp [hunk 2]
```diff
@@ -0,0 +1,51 @@
...
+#include <bit>
+#include <cassert>
+
+// Indirectly test countl_zero on old x86/x64 processors by testing private hepler,
+// which is different from the usual branch.
+
+// Since the fallback intrinsic is available on ARM too, don't need to exclude ARM
+
+// Currently need this test only in C++20 mode,
+// May update to older C++ if the helper is used internally too, for example in <bitset>
```
Comment (StephanTLavavej) [inline tests/std/tests/GH_001103_countl_zero_correctness/test.cpp:13]:
```suggestion
// Currently need this test only in C++20 mode;
// may update to older C++ if the helper is used internally too, for example in <bitset>.
```

File: tests/std/tests/GH_001103_countl_zero_correctness/test.cpp [hunk 3]
```diff
@@ -0,0 +1,51 @@
+// Copyright (c) Microsoft Corporation.
+// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
+
+#include <bit>
+#include <cassert>
+
+// Indirectly test countl_zero on old x86/x64 processors by testing private hepler,
+// which is different from the usual branch.
+
+// Since the fallback intrinsic is available on ARM too, don't need to exclude ARM
```
[the remark this answers is not in the document]
Comment (AlexGuteniev) [reply tests/std/tests/GH_001103_countl_zero_correctness/test.cpp:10]: It could have worked, as intrinsic is available, didn't notice it was disabled. Then maybe need a different approach...

[the remark this answers is not in the document]
Comment (AlexGuteniev) [reply tests/std/tests/GH_001103_countl_zero_correctness/test.cpp:10]: It could have worked, as intrinsic is available, didn't notice it was disabled. Then maybe need a different approach...

File: tests/std/tests/GH_001103_countl_zero_correctness/test.cpp [hunk 4]
```diff
@@ -0,0 +1,43 @@
...
+    assert(_Countl_zero_bsr(static_cast<unsigned long>(0x0000'0000)) == 32);
+    assert(_Countl_zero_bsr(static_cast<unsigned long>(0x0000'0013)) == 27);
+    assert(_Countl_zero_bsr(static_cast<unsigned long>(0x8000'0003)) == 0);
+    assert(_Countl_zero_bsr(static_cast<unsigned long>(0xF000'0008)) == 0);
+
+    assert(_Countl_zero_bsr(static_cast<unsigned long long>(0x0000'0000'0000'0000)) == 64);
+    assert(_Countl_zero_bsr(static_cast<unsigned long long>(0x0000'0000'0000'0013)) == 59);
+    assert(_Countl_zero_bsr(static_cast<unsigned long long>(0x8000'0000'0000'0003)) == 0);
+    assert(_Countl_zero_bsr(static_cast<unsigned long long>(0xF000'0000'0000'0008)) == 0);
+#endif // ^^^ defined(_MIX86) || defined(_M_X64) ^^^
```
Comment (StephanTLavavej) [inline tests/std/tests/GH_001103_countl_zero_correctness/test.cpp:42]:
```suggestion
#endif // ^^^ defined(_M_IX86) || defined(_M_X64) ^^^
```

**Comment by StephanTLavavej** [comment]
Thanks for improving this test coverage! :tada:
