### PR TITLE
`<regex>`: Remove non-standard `_Uelem` from matcher

### LINKED ISSUE #995: <regex>: basic_regex wants regex_traits to provide things not required by [re.req]
**Describe the bug**
`basic_regex` relies on non-standard extensions of `regex_traits`

**Command-line test case**
```
d:\Temp2>type repro.cpp
#include <array>
#include <iostream>
#include <regex>

struct custom_traits : private std::regex_traits<char>
{
        using base_t = std::regex_traits<char>;

        using base_t::regex_traits;

        using base_t::char_type;
        using base_t::locale_type;
        using base_t::string_type;
        using base_t::char_class_type;

        using base_t::length;
        using base_t::translate;
        using base_t::translate_nocase;
        using base_t::transform;
        using base_t::transform_primary;
        using base_t::lookup_collatename;
        using base_t::lookup_classname;
        using base_t::isctype;
        using base_t::value;
        using base_t::imbue;
        using base_t::getloc;

#ifdef WORKAROUND
        using base_t::_Ch_upper;
        using base_t::_Uelem;
        using base_t::_Ch_alpha;
#endif
};

int main()
{
        std::basic_regex<char, custom_traits> r("3");
        return 0;
}

d:\Temp2>cl /EHsc /W4 /WX .\repro.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.27.29009.1 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

repro.cpp
c:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.27.29009\include\regex(3975): error C2247: 'std::_Regex_traits_base::_Ch_upper' not accessible because 'custom_traits' uses 'private' to inherit from 'std::regex_traits<char>'
c:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.27.29009\include\regex(238): note: see declaration of 'std::_Regex_traits_base::_Ch_upper'
.\repro.cpp(5): note: see declaration of 'custom_traits'
c:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.27.29009\include\regex(393): note: see declaration of 'std::regex_traits<char>'
c:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.27.29009\include\regex(3964): note: while compiling class template member function 'bool std::_Parser<_FwdIt,_Elem,_RxTraits>::_CharacterClassEscape(bool)'
** a lot of more errors **

d:\Temp2>cl /EHsc /W4 /WX /DWORKAROUND .\repro.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.27.29009.1 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

repro.cpp
Microsoft (R) Incremental Linker Version 14.27.29009.1
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:repro.exe
repro.obj
```

**Expected behavior**
Should compile without workaround.
May compile or not compile with workaround,

**STL version**
```
Microsoft Visual Studio Professional 2019 Preview
Version 16.7.0 Preview 3.1
```

**Additional context**
This item is also tracked on Developer Community as DevCom-322328 and by Microsoft-internal VSO-673897 / [AB#673897](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/673897).

**vNext note**: Resolving this issue will require breaking binary compatibility. We won't be able to accept pull requests for this issue until the vNext branch is available. See #169 for more information.

### PR DESCRIPTION
**Pull request by muellerj2**
Resolves #995 by eliminating `_Uelem` completely.

This PR does not quite complete support for custom character types: The internals of `regex_search` still place some additional requirements on such types. But except for ADL resilience, the support should be complete for `regex_match`, as the passing test confirms.

### `<regex>` changes

* Remove usage of `_Uelem` from `_Is_word` by converting to `unsigned char` instead combined with a check that re-conversion to the character type yields the same character again.
  * At this opportunity, `_STD`-qualify some `_Is_word` calls.
* Remove usage of `_Uelem` from `_Lookup_range` by relying on the `lt()` function in the char traits type instead.
  * Since this is possibly called in a tight loop, I added two overloads for `char` and `wchar_t` that avoid calling the `lt()` function for the standard traits type.
* Remove usage of `_Uelem` from `_Do_class()` by converting to `unsigned char` instead and checking that re-conversion to the character type yields the same character again.
* Remove requirement for implicit conversions when comparing with ECMAScript line terminators by explicitly converting to `unsigned int` before comparing with the line terminator code points.
  * The round trip conversion check makes sure that we don't accidentally confuse some code point values larger than 0x100000000 with the line terminators (although I don't know why anyone would ever need that).
  * Signed character types are unproblematic: The code points for line terminators are positive values in all standard C++ signed types, so they will never be sign-extended when converting to `unsigned int`.
  * Again, I added two overloads for `char` and `wchar_t`, but in this case rather because their logic is noticeably simpler.

### Test changes

The test coverage for custom character types largely remains rudimentary, but I added some test coverage that matching behaves as it should in places where the parser and matcher rely on potentially narrowing conversions.

The test covers the matcher changes in this PR: Word boundaries (`_Is_word`), single character matching (`_Matcher2::_Do_class`), character ranges (`_Lookup_range`) and line terminators (`_Is_ecmascript_line_terminator`). Additionally, some of the character ranges are chosen to validate that the implementation of `_Builder::_Add_range` remains correct for custom character types.

Beyond this, I made the following changes to tests:
* Removed workaround for #5563.
* Removed workarounds for #995.
* `wrapped_wchar` was turned into a template `wrapped_character<Elem>` so that it can be used with an `unsigned long long` character type as well.
* Removed `operator wchar_t()` from `wrapped_character<Elem>` and replaced it by friend functions `convert_to<target_type>`, which are now called by the test traits classes.
  * This tightens the test coverage for `<regex>` as it removes implicit conversions from the custom types that only existed to support the implementation the test traits classes.
  * Since ADL doesn't work for function calls with explicit template parameters in C++14 and C++17, I had to move the definitions  of the custom character types before the definitions of the traits classes.
* The test char traits class was changed to accomodate an `unsigned long long`-like character type.
* The implementation of `transform_primary` in the test regex traits was replaced by a dummy implementation to allow the test to run under /clr:pure.

### CODE REVIEW

File: stl/inc/regex [hunk 1]
```diff
@@ -3727,11 +3724,34 @@ _BidIt1 _Search_translate_left(_BidIt1 _Begin1, _BidIt1 _End1, _BidIt2 _Begin2,
     }
 }
 
-template <class _Elem>
-bool _Lookup_range(unsigned int _Ch, const _Buf<_Elem>* _Bufptr) { // check whether _Ch is in _Buf
-    using _Uelem = make_unsigned_t<_Elem>;
+template <class _Char_traits, enable_if_t<is_same_v<_Char_traits, char_traits<char>>, int> = 0>
```
Comment (StephanTLavavej) [inline stl/inc/regex]: I believe it would be better to use `if constexpr` instead of `enable_if_t` SFINAE to handle `char_traits<char>` vs. `char_traits<wchar_t>` vs. arbitrary stuff.

File: stl/inc/regex [hunk 2]
```diff
@@ -3934,9 +3955,19 @@ typename _RxTraits::char_class_type _Matcher2<_BidIt, _Elem, _RxTraits, _It, _Al
     return _Traits.lookup_classname(_Ptr, _Ptr + 1, (_Sflags & regex_constants::icase) != 0);
 }
 
+inline bool _Is_ecmascript_line_terminator(char _Ch) {
```
Comment (StephanTLavavej) [inline stl/inc/regex]: Similarly, I believe `if constexpr` would be slightly better here, instead of always emitting `inline` function definitions for character types we might never use.

File: tests/std/tests/GH_000995_regex_custom_char_types/test.cpp [hunk 3]
```diff
@@ -1,24 +1,84 @@
...
+
+template <class Elem>
+class wrapped_character {
+public:
+    wrapped_character() = default;
+    explicit wrapped_character(char ch) : character(static_cast<wchar_t>(ch)) {}
+    explicit wrapped_character(unsigned char ch) : character(ch) {}
+    explicit wrapped_character(Elem w) : character(w) {}
+    template <class T = wchar_t, enable_if_t<!is_same_v<T, Elem> && is_same_v<T, wchar_t>, int> = 0>
+    explicit wrapped_character(wchar_t w) : character(w) {}
```
Comment (StephanTLavavej) [inline tests/std/tests/GH_000995_regex_custom_char_types/test.cpp]: I believe that `is_same_v<T, wchar_t>` is unnecessary. `T` isn't deducible, and this is a constructor so it can't be explicitly provided.

File: tests/std/tests/GH_000995_regex_custom_char_types/test.cpp [hunk 4]
```diff
@@ -65,8 +125,10 @@ class test_regex_traits {
 
     template <class FwdIt>
     string_type transform_primary(FwdIt first, FwdIt last) const {
-        auto str = convert_to_underlying_string<UnderlyingChar>(first, last);
-        return convert_from_underlying_string<string_type>(inner.transform_primary(str.begin(), str.end()));
+        if (_STD distance(first, last) == 1) {
```
Comment (StephanTLavavej) [inline tests/std/tests/GH_000995_regex_custom_char_types/test.cpp]: This is using the internal `_STD` macro.

File: tests/std/tests/GH_000995_regex_custom_char_types/test.cpp [hunk 5]
```diff
@@ -1,24 +1,84 @@
...
+}
+
+template <class Elem>
+class wrapped_character {
+public:
+    wrapped_character() = default;
+    explicit wrapped_character(char ch) : character(static_cast<wchar_t>(ch)) {}
+    explicit wrapped_character(unsigned char ch) : character(ch) {}
+    explicit wrapped_character(Elem w) : character(w) {}
+    template <class T = wchar_t, enable_if_t<!is_same_v<T, Elem> && is_same_v<T, wchar_t>, int> = 0>
```
Comment (StephanTLavavej) [inline tests/std/tests/GH_000995_regex_custom_char_types/test.cpp]: Should include `<type_traits>` for `enable_if_t`.

File: tests/std/tests/GH_000995_regex_custom_char_types/test.cpp [hunk 6]
```diff
@@ -263,7 +293,146 @@ void test_gh_5592() {
...
+
+    // no issues with signed character values
+    test_regex_on_custom_wchars(
+        L"\uf000", L"\uf000", true); // U+F000 in private use area (signed for signed_wchar_enum)
+
+    // matching for very large values
+    {
+        unsigned long long pattern = 0xabababababULL;
+
+        test_regex_on_custom_ullongs(&pattern, &pattern + 1, &pattern, &pattern + 1, true);
```
Comment (StephanTLavavej) [inline tests/std/tests/GH_000995_regex_custom_char_types/test.cpp]: As `test_regex_on_custom_ullongs` takes `const unsigned long long*`, I think it would be much clearer to mark `pattern` as `const`, so that at the callsite it's obvious that we don't need to worry about it being modified.

In test code I'm somewhat more relaxed about using `const` everywhere than in product code (note: `<regex>` has a pre-existing lack of discipline so I don't usually complain there). However, when passing stuff around by pointer, I believe it's more important to be disciplined about `const`.

File: tests/std/tests/GH_000995_regex_custom_char_types/test.cpp [hunk 7]
```diff
@@ -263,7 +293,146 @@ void test_gh_5592() {
...
+}
+
+void test_gh_5671_line_terminators() {
+    // test line terminator handling for dot
+    test_regex_on_custom_wchars(L".", L"a", true);
+    test_regex_on_custom_wchars(L".", L"\r", false);
+    test_regex_on_custom_wchars(L".", L"\n", false);
+    test_regex_on_custom_wchars(L".", L"\u2028", false); // U+2028 LINE SEPARATOR
+    test_regex_on_custom_wchars(L".", L"\u2029", false); // U+2029 PARAGRAPH SEPARATOR
+    test_regex_on_custom_wchars(L".", L"\u2029", false); // U+2029 PARAGRAPH SEPARATOR
```
Comment (StephanTLavavej) [inline tests/std/tests/GH_000995_regex_custom_char_types/test.cpp]: This is exactly repeated.

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
:heart_eyes_cat: :tada: :smile_cat:
===
