### PR TITLE
Wait on condition variables independently on system time

### LINKED ISSUE #718: <thread>: this_thread::sleep_until uses system time even if based on steady_clock
**Describe the bug**
Internally, `sleep_until` calls `_To_xtime_10_day_clamped` to convert time point of any clock to time point of System clock. Then `_Thrd_sleep` sleeps on this system time point:
https://github.com/microsoft/STL/blob/31419650d472932dd24b9c5602707b0454f61fb2/stl/inc/thread#L154-L166

`_To_xtime_10_day_clamped` uses `system_clock`
https://github.com/microsoft/STL/blob/31419650d472932dd24b9c5602707b0454f61fb2/stl/inc/chrono#L629-L652

If `system_clock` is adjusted between `_To_xtime_10_day_clamped` and `_Thrd_sleep`, the sleep interval is wrong.

`sleep_for` is also subject to this problem as it is based on `sleep_until`
https://github.com/microsoft/STL/blob/31419650d472932dd24b9c5602707b0454f61fb2/stl/inc/thread#L168-L171
Though standard says
> The functions whose names end in _­for take an argument that specifies a duration. These functions produce relative timeouts. Implementations should use a steady clock to measure time for these functions.

**Command-line test case**
Hard to build stable repro, but will try if needed.

**Expected behavior**
Neither `sleep_until` relative to a steady clock nor `sleep_for` should depend on `system_clock`.

`GetTickCount64` is good enough steady clock, as `Sleep` API does not have granularity less than a millisecond anyway (calling undocumented `NtDelayExecution` is unacceptable). `GetTickCount64` is very fast clock, it is basically reading a global variable.

**STL version**
```
Microsoft Visual Studio Professional 2019 Preview
Version 16.6.0 Preview 2.1
```
**Additional context**
~~Suspect that tests for #593 are failing due to timeout because other tests simultaneously tamper with system clock.~~  Ok, this theory is defeated now, but the bug still looks valid

### PR DESCRIPTION
**Pull request by AlexGuteniev**
Fix #718

Possibly create chaos (I hope not).

I made new core header, since making `<xthreads.h>` non-core looked hard.

Thanks @achabense for the first step in this direction.

### CODE REVIEW

File: stl/inc/thread [hunk 1]
```diff
@@ -179,6 +179,24 @@ _NODISCARD auto _To_absolute_time(const chrono::duration<_Rep, _Period>& _Rel_ti
...
+    bool _Clamped;
+};
+
+template <class _Duration>
+_NODISCARD _Clamped_rel_time_ms_count_result _Clamped_rel_time_ms_count(const _Duration& _Rel) {
+    // _Clamp must be less than 2^32 - 1 (INFINITE) milliseconds, but is otherwise arbitrary.
+    constexpr chrono::milliseconds _Clamp{chrono::hours{24}};
+
+    if (_Rel >= _Clamp) {
+        return {static_cast<unsigned long>(_Clamp.count()), true};
```
Comment (StephanTLavavej) [inline stl/inc/thread:193]: It didn't matter in `this_thread::sleep_until()`, the original source of this code, but now `_Clamped_rel_time_ms_count()` cares about whether clamping happened. We should test for strictly greater-than here - if the user asked for exactly 24h, then we don't need to clamp.

Note that this is what the now-removed `_To_timespec64_sys_10_day_clamped()` did - it said

```cpp
const bool _Clamped      = _Ten_days_d < _Rel_time;
```

File: stl/src/sharedmutex.cpp [hunk 2]
```diff
@@ -39,4 +40,27 @@ void __cdecl _Smtx_unlock_shared(_Smtx_t* smtx) noexcept { // unlock non-exclusi
 void __stdcall _Thrd_sleep_for(const unsigned long ms) noexcept { // suspend current thread for `ms` milliseconds
     Sleep(ms);
 }
+
+_Thrd_result __stdcall _Cnd_timedwait_for(const _Cnd_t cond, const _Mtx_t mtx, const unsigned target) noexcept {
```
Comment (StephanTLavavej) [inline stl/src/sharedmutex.cpp:44]: Working without a units library is scary. We should clearly name this parameter, and the `GetTickCount64()` variables, to mark that they're milliseconds.

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
:warning: Note to self:
===

This will need the usual MSVC-internal changes to add a new header.

**Comment by AlexGuteniev** [comment]
One of scary things here is locking down the `_Cnd_t` and `_Mtx_t`.
We cannot further change them after this change, as the assumption on their structure are embedded into import library.

**Comment by AlexGuteniev** [comment]
> One of scary things here is locking down the `_Cnd_t` and `_Mtx_t`. We cannot further change them after this change, as the assumption on their structure are embedded into import library.

The alternative could be a satellite DLL, this makes the change possible without core header extraction, but this can be more cumbersome overall.

**Comment by StephanTLavavej** [comment]
I think I'm fine with that limitation - the headers (not just the import lib) already know about the mutex representation, and the condition variable representation has been boiled down to its essentials now.

There's one more transformation I want to perform (I want to get rid of the forward declaration squirrelliness) but that won't affect representation.

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
Thanks for fixing this notorious bug that we previously thought was unfixable! :star: :heart_eyes_cat: :tada:

**Comment by NipaJ** [comment]
`_Cnd_timedwait_for` is missing `_CRTIMP2_PURE`, forcing static linkage always. This is problematic, since the function is missing from the DLL version of the runtime library. This is also issue with the current replacement `_Cnd_timedwait_for_unchecked`

**Comment by StephanTLavavej** [comment]
This is intentional; we routinely inject new functions (non-dllexported) into the STL's import lib, effectively statically linking them. We require that the final link be performed by a toolset that's at least as new as any of the toolsets used to produce OBJs/LIBs participating in that link.
