### PR TITLE
fix `format` a `long` value with `formatter`

### LINKED ISSUE #2765: <format>: Cannot format a `long` value with `formatter`
**Describe the bug**
From https://stackoverflow.com/questions/72510490/stdformat-with-custom-types

Formatting a `long` value with `formatter` fails because `long` is not convertible to `basic_format_arg`.

With `int` it works as expected. 

**Command-line test case**
```
D:\>type repro.cpp
#include <format>
#include <iostream>

template<class T>
struct Box {
    T value;
};

template<class T, class CharT>
struct std::formatter<Box<T>, CharT> : std::formatter<T, CharT> {
    template<class FormatContext>
    auto format(Box<T> t, FormatContext& fc) const {
        return std::formatter<T, CharT>::format(t.value, fc);
    }
};

int main() {
    Box<long> v = { 42 };
    std::cout << std::format("{:#x}", v);
}


D:\>cl /std:c++20 /EHsc repro.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.33.31424 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

repro.cpp
D:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.33.31424\include\format(2900): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'std::basic_format_arg<_Context>'
        with
        [
            _Context=std::format_context
        ]
D:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.33.31424\include\format(2900): note: No constructor could take the source type, or constructor overload resolution was ambiguous
repro.cpp(13): note: see reference to function template instantiation 'std::back_insert_iterator<std::_Fmt_buffer<char>> std::_Formatter_base<long,_CharT,std::_Basic_format_arg_type::_Int_type>::format<FormatContext>(const _Ty &,_FormatContext &) const' being compiled
        with
        [
            _CharT=char,
            FormatContext=std::format_context,
            _Ty=long,
            _FormatContext=std::format_context
        ]
repro.cpp(13): note: see reference to function template instantiation 'std::back_insert_iterator<std::_Fmt_buffer<char>> std::_Formatter_base<long,_CharT,std::_Basic_format_arg_type::_Int_type>::format<FormatContext>(const _Ty &,_FormatContext &) const' being compiled
        with
        [
            _CharT=char,
            FormatContext=std::format_context,
            _Ty=long,
            _FormatContext=std::format_context
        ]
D:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.33.31424\include\format(173): note: see reference to function template instantiation 'std::back_insert_iterator<std::_Fmt_buffer<char>> std::formatter<Box<long>,_CharT>::format<_Context>(Box<long>,FormatContext &) const' being compiled
        with
        [
            _CharT=char,
            _Context=std::format_context,
            FormatContext=std::format_context
        ]
D:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.33.31424\include\format(1449): note: see reference to variable template 'bool _Has_formatter<Box<long> &,std::basic_format_context<std::back_insert_iterator<std::_Fmt_buffer<char> >,char> >' being compiled
D:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.33.31424\include\format(1499): note: see reference to alias template instantiation 'std::_Format_arg_traits<_Context>::_Storage_type<_Ty>' being compiled
        with
        [
            _Context=std::format_context,
            _Ty=Box<long> &
        ]
D:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.33.31424\include\format(1534): note: see reference to variable template 'const size_t std::_Format_arg_traits<std::basic_format_context<std::back_insert_iterator<std::_Fmt_buffer<char> >,char> >::_Storage_size<Box<long> &>' being compiled
D:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.33.31424\include\format(2980): note: see reference to class template instantiation 'std::_Format_arg_store<std::format_context,Box<long> &>' being compiled
D:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.33.31424\include\format(3098): note: see reference to function template instantiation 'std::_Format_arg_store<std::format_context,Box<long> &> std::make_format_args<std::format_context,Box<long>&>(Box<long> &)' being compiled
repro.cpp(19): note: see reference to function template instantiation 'std::string std::format<Box<long>&>(const std::_Basic_format_string<char,Box<long> &>,Box<long> &)' being compiled
D:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.33.31424\include\format(2897): error C2672: 'std::visit_format_arg': no matching overloaded function found
D:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.33.31424\include\format(2900): error C2780: 'decltype(auto) std::visit_format_arg(_Visitor &&,std::basic_format_arg<_Context>)': expects 2 arguments - 1 provided
D:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.33.31424\include\format(349): note: see declaration of 'std::visit_format_arg'
```

**Expected behavior**
Should compile

**STL version**

    Microsoft Visual Studio Community 2022 Preview
    Version 17.3.0 Preview 1.0

### PR DESCRIPTION
**Pull request by fsb4000**
Fixes #2765

Although @cpplearner wrote everything in the issue, I was able to write  
```c++
typename _Format_arg_traits<_FormatContext>::template _Storage_type<_Ty>
``` 
correctly only the third time :)

### CODE REVIEW

**Comment by StephanTLavavej** [comment]
`P0355R7_calendars_and_time_zones_formatting` is failing with:

```
D:\build\out\inc\format(3148) : Assertion failed: The custom handler should be structurally unreachable for _Arg_formatter
```

**Comment by cpplearner** [comment]
> `P0355R7_calendars_and_time_zones_formatting` is failing with:
> 
> ```
> D:\build\out\inc\format(3148) : Assertion failed: The custom handler should be structurally unreachable for _Arg_formatter
> ```

This seems to be because `std::string` gets stored as a `std::basic_format_arg::handle`, which means this function is unused: https://github.com/microsoft/STL/blob/17fde2cbab6e8724d81c9555237c9a623d7fb954/stl/inc/format#L1778-L1780

Maybe the constrained overload is considered to be more specialized?

https://github.com/microsoft/STL/blob/17fde2cbab6e8724d81c9555237c9a623d7fb954/stl/inc/format#L1744-L1745

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Thanks for fixing this bug! I pushed minor stylistic changes and a small test coverage increase - please meow if you disagree.

File: tests/std/tests/P0645R10_text_formatting_formatting/test.cpp [hunk 1]
```diff
@@ -1392,6 +1392,26 @@ void test_localized_char() {
...
+struct std::formatter<Box<T>, charT> : std::formatter<T, charT> {
+    template <class FormatContext>
+    auto format(Box<T> t, FormatContext& fc) const {
+        return formatter<T, charT>::format(t.value, fc);
+    }
+};
+
+// Also test GH-2765 "<format>: Cannot format a long value with formatter"
+template <class charT>
+void test_gh_2765() {
```
Comment (cpplearner) [inline tests/std/tests/P0645R10_text_formatting_formatting/test.cpp:1410]: I think this test is better suited for [`P0645R10_text_formatting_custom_formatting`](https://github.com/microsoft/STL/blob/main/tests/std/tests/P0645R10_text_formatting_custom_formatting/test.cpp). It can also reuse the mechanism defined there.

Comment (StephanTLavavej) [reply tests/std/tests/P0645R10_text_formatting_formatting/test.cpp:1410]: Ah, excellent catch!

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Thanks @cpplearner for noticing that `P0645R10_text_formatting_custom_formatting` already has machinery that's identical to `Box<T>`:

https://github.com/microsoft/STL/blob/17fde2cbab6e8724d81c9555237c9a623d7fb954/tests/std/tests/P0645R10_text_formatting_custom_formatting/test.cpp#L86-L97

I verified that adding test coverage for `long` here will fail without @fsb4000's fix. To be comprehensive, I also added coverage for `unsigned long` and `long double`.

**Comment by fsb4000** [comment]
> This seems to be because std::string gets stored as a std::basic_format_arg::handle, which means this function is unused: 

No, `std::string` is ok, I debugged the test.
The error from the asserts:
https://github.com/microsoft/STL/blob/17fde2cbab6e8724d81c9555237c9a623d7fb954/tests/std/tests/P0355R7_calendars_and_time_zones_formatting/test.cpp#L1094

`test_information_classes<char>();` works OK.

and inside `test_information_classes`
https://github.com/microsoft/STL/blob/17fde2cbab6e8724d81c9555237c9a623d7fb954/tests/std/tests/P0355R7_calendars_and_time_zones_formatting/test.cpp#L817-L826

All `empty_braces_helper` tests with `sys` or `loc1` are failed

https://github.com/microsoft/STL/blob/17fde2cbab6e8724d81c9555237c9a623d7fb954/tests/std/tests/P0355R7_calendars_and_time_zones_formatting/test.cpp#L234-L239

`format` `local_info` is stored as a `std::basic_format_arg::handle`
So probably it's correct

**Comment by cpplearner** [comment]
- `format(STR("{}"), val)` calls `operator<<`;
- `operator<<` calls `_Widen_string<_CharT>(_Val.abbrev)`;
- `_Widen_string` returns a `const string&` when `CharT` is `char`, but returns a `wstring` when `CharT` is `wchar_t`.

That `const` probably makes a difference here.

```c++
#include <format>
#include <string>

using namespace std;

using A = _Format_arg_traits<format_context>::_Storage_type<string>;
using B = _Format_arg_traits<format_context>::_Storage_type<const string>;

static_assert(is_same_v<A, basic_format_arg<format_context>::handle>);
static_assert(is_same_v<B, string_view>);
```

**Comment by fsb4000** [comment]
great @cpplearner 
So can we change 
```c++
template <class _Traits, class _Alloc> 
 static auto _Phony_basic_format_arg_constructor(const basic_string<_Char_type, _Traits, _Alloc>&) 
     -> basic_string_view<_Char_type>; // not defined 
```
to 
```c++
template <class _Traits, class _Alloc> 
 static auto _Phony_basic_format_arg_constructor(basic_string<_Char_type, _Traits, _Alloc>) 
     -> basic_string_view<_Char_type>; // not defined 
```
?

**Review by miscco — APPROVED** [review]

File: stl/inc/format [hunk 2]
```diff
@@ -1776,7 +1776,7 @@ struct _Format_arg_traits {
         -> basic_string_view<_Char_type>; // not defined
 
     template <class _Traits, class _Alloc>
-    static auto _Phony_basic_format_arg_constructor(const basic_string<_Char_type, _Traits, _Alloc>&)
+    static auto _Phony_basic_format_arg_constructor(basic_string<_Char_type, _Traits, _Alloc>)
```
Comment (StephanTLavavej) [inline stl/inc/format:1779]: 1. I think I see why this change is desirable (`const basic_string&` is a worse match than `_Ty&&` for a modifiable `basic_string`). However, this no longer follows WG21-N4910 [[format.arg]/10](https://eel.is/c++draft/format.arg#10). Does this mean that we need to file an LWG issue?

Comment (StephanTLavavej) [inline stl/inc/format:1779]: 2. Is there a related issue with the `const _Char_type*` overload:
   https://github.com/microsoft/STL/blob/17fde2cbab6e8724d81c9555237c9a623d7fb954/stl/inc/format#L1772
   My brain-compiler suggests that `_Char_type*` will go through the general `handle` codepath.

Comment (StephanTLavavej) [inline stl/inc/format:1779]: 3. When `handle` is selected, was the code just slower than necessary?

File: stl/inc/format [hunk 3]
```diff
@@ -3286,10 +3286,15 @@ struct _Formatter_base {
...
-            basic_format_arg<_FormatContext>{_Val});
+        _Arg_formatter<typename _FormatContext::iterator, _CharT> _Arg_fmt{
+            ._Ctx = _STD addressof(_FormatCtx), ._Specs = _STD addressof(_Format_specs)};
+
+        using _Storage_type = typename _Format_arg_traits<_FormatContext>::template _Storage_type<_Ty>;
+        if constexpr (is_same_v<typename basic_format_arg<_FormatContext>::handle, _Storage_type>) {
+            return _STD visit_format_arg(_Arg_fmt, basic_format_arg<_FormatContext>{_Val});
+        } else {
+            return _STD visit_format_arg(_Arg_fmt, basic_format_arg<_FormatContext>{static_cast<_Storage_type>(_Val)});
+        }
```
Comment (CaseyCarter) [inline stl/inc/format:3297]: Partially informed drive-by comment: I would _much_ prefer that we correctly implement `basic_format_arg`s constructor overload set instead of adding external hacks like this.

File: stl/inc/format (hunk 2 above)
Comment (CaseyCarter) [reply stl/inc/format:1779]: This sounds like the `char`-type flavor of LWG-3540.

Comment (CaseyCarter) [reply stl/inc/format:1779]: I'd love it if we could address these issues with `basic_format_arg`'s constructor overloads, revise everything to be lvalue-only, and submit an LWG issue. P2418 was very rushed, and did some damage to the wording.

File: stl/inc/format (hunk 3 above)
Comment (StephanTLavavej) [reply stl/inc/format:3297]: Ah, I see! I didn't realize how messed up `basic_format_arg`'s constructors were in the Standardese.

I agree with your suggested approach - handle `long` and `unsigned long` (I think those are the affected arithmetic types?), fix the modifiable `basic_string` issue, and fix the (apparent) `charT *` issue all in the overload set. This seems like an acceptable reason to (temporarily) diverge from the Standardese, under the "clearly broken wording" exception.

**Comment by fsb4000** [comment]
Yes, I did it intentionally because we don't modify `basic_format_arg`.
But now I am unsure, maybe the `const` is not needed.

File: stl/inc/format (hunk 2 above)
Comment (fsb4000) [reply stl/inc/format:1784]: yes, as far as I see (and because tests passed before)

File: stl/inc/format [hunk 4]
```diff
@@ -666,6 +666,10 @@ public:
         : _Active_state(_Basic_format_arg_type::_Int_type), _Int_state(_Val) {}
     explicit basic_format_arg(const unsigned int _Val) noexcept
         : _Active_state(_Basic_format_arg_type::_UInt_type), _UInt_state(_Val) {}
+    explicit basic_format_arg(const long _Val) noexcept
+        : _Active_state(_Basic_format_arg_type::_Int_type), _Int_state(_Val) {}
+    explicit basic_format_arg(const unsigned long _Val) noexcept
+        : _Active_state(_Basic_format_arg_type::_UInt_type), _UInt_state(_Val) {}
```
Comment (barcharcraz) [inline stl/inc/format:672]: I would prefer to just static cast to the storage type when creating the basic_format_arg, instead of messing around with this constructor. This overload set isn't really as horrible as the real mapping done by the phony overload set and storage type but still.

Actually: We probably shouldn't have this overload set at all, and instead just have an initializer from memory and a type enumerator, along with the T&& constructor that does the cast.

This would consolidate this overload set and the one in basic_format_args::get

This would also mean the basic_format_arg constructor could actually behave as the standard says it should (even though it's exposition only, so doesn't have to.

**Review by barcharcraz — CHANGES_REQUESTED** [review]

File: stl/inc/format (hunk 4 above)
Comment (barcharcraz) [reply stl/inc/format:672]: Actually, I retract my suggestion. If we add the overloads we don't need to mess around with the formatter when we consolidate this overload set with the phony one.

**Review by barcharcraz — APPROVED** [review]
Approved, despite this not doing what the standard says for basic_string&

Agree with Casey that we need to reformulate how this overload set works, it's been a very consistent source of bugs in both our implementation and the standard.

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
Thanks for the bugfix and targeted overhaul here, improving our implementation beyond the Standard itself! :joy_cat: :lady_beetle: :tada:
