### PR TITLE
`<cmath>`: Use Clang builtins for classification/comparison functions

### LINKED ISSUE #4609: `std::isfinite` poor codegen with Microsoft STL + Clang
I work on Skia. I recently attempted to replace our hand-rolled implementation of `std::isfinite` with the standard library version, trusting that a modern compiler's implementation would be equally efficient.

In practice, this led to a significant, measurable regression in our path-rendering code in clang-cl builds (which mixes Microsoft's STL with the Clang compiler). 

I believe the discrepancy comes from https://github.com/microsoft/STL/blob/main/stl/inc/cmath . There does not appear to be support for clang's `__builtin_isfinite`. Other Clang builtins are supported, however—there are special codepaths for [__builtin_ceilf](https://github.com/microsoft/STL/blob/main/stl/inc/cmath#L73), [__builtin_floorf](https://github.com/microsoft/STL/blob/main/stl/inc/cmath#L129), [__builtin_copysignf](https://github.com/microsoft/STL/blob/main/stl/inc/cmath#L83), and others. However, [isfinite](https://github.com/microsoft/STL/blob/main/stl/inc/cmath#L785) has no Clang builtin support, and ends up calling into `fpclassifyd` for each value, which is extremely expensive relative to the handful of instructions that a native `isfinite` needs.

I've filed this with our LLVM team ([buganizer](https://g-issues.chromium.org/issues/335901087?pli=1&authuser=0)) but they said they could not control it from their end.

### PR DESCRIPTION
**Pull request by StephanTLavavej**
Fixes #4609.

This is limited to functions that the UCRT has templated, where our non-template overloads will be preferred. For example, this PR omits `fpclassify()` because the UCRT overloads it for `float`, `double`, and `long double` (to call `_fdtest()`, `_dtest()`, and `_ldtest()`, respectively), so even though Clang provides a `constexpr`-compatible `__builtin_fpclassify`, the STL can't provide overloads without introducing ambiguity.

Note that we define our overloads in the global namespace and then drag them into `namespace std`. Therefore, as long as users include `<cmath>`, their global namespace calls *will* benefit from this improvement.

Also note an additional limitation: calls to the binary comparison functions with mixed argument types will select the UCRT templates as being better matches.

In the medium future, it looks like we're going to need a major UCRT overhaul of `<math.h>` to implement all of the `constexpr` demanded by C++23/26 - at that time we can also untangle the additional overloads that the STL is providing (for both integral and floating-point), and teach the UCRT to use MSVC and Clang builtins when possible.

The MSVC compiler back-end should probably provide similar builtins - I am a lazy kitty :cat2: :zzz: so I haven't asked them, but again the upcoming `constexpr` overhaul work will likely result in such machinery becoming available.

```
C:\Temp>type meow.cpp
```
```cpp
#include <cmath>

bool is_this_finite(double dbl) {
    return std::isfinite(dbl);
}
```
```
C:\Temp>clang-cl /EHsc /nologo /W4 /MT /O2 /c /FAs meow.cpp
```

<details><summary>Click to expand codegen before:</summary>

```
C:\Temp>type meow.asm
        .text
        .def    @feat.00;
        .scl    3;
        .type   0;
        .endef
        .globl  @feat.00
.set @feat.00, 0
        .intel_syntax noprefix
        .file   "meow.cpp"
        .def    "?is_this_finite@@YA_NN@Z";
        .scl    2;
        .type   32;
        .endef
        .section        .text,"xr",one_only,"?is_this_finite@@YA_NN@Z"
        .globl  "?is_this_finite@@YA_NN@Z"      # -- Begin function ?is_this_finite@@YA_NN@Z
        .p2align        4, 0x90
"?is_this_finite@@YA_NN@Z":             # @"?is_this_finite@@YA_NN@Z"
.seh_proc "?is_this_finite@@YA_NN@Z"
# %bb.0:
        push    rbx
        .seh_pushreg rbx
        sub     rsp, 48
        .seh_stackalloc 48
        .seh_endprologue
        mov     rax, qword ptr [rip + __security_cookie]
        xor     rax, rsp
        mov     qword ptr [rsp + 40], rax
        movsd   qword ptr [rsp + 32], xmm0
        lea     rcx, [rsp + 32]
        call    _dtest
        test    ax, ax
        setle   bl
        mov     rcx, qword ptr [rsp + 40]
        xor     rcx, rsp
        call    __security_check_cookie
        mov     eax, ebx
        add     rsp, 48
        pop     rbx
        ret
        .seh_endproc
                                        # -- End function
        .section        .drectve,"yni"
        .ascii  " /DEFAULTLIB:libcmt.lib"
        .ascii  " /DEFAULTLIB:oldnames.lib"
        .ascii  " /FAILIFMISMATCH:\"_MSC_VER=1900\""
        .ascii  " /FAILIFMISMATCH:\"_ITERATOR_DEBUG_LEVEL=0\""
        .ascii  " /FAILIFMISMATCH:\"RuntimeLibrary=MT_StaticRelease\""
        .ascii  " /DEFAULTLIB:libcpmt.lib"
        .addrsig
        .globl  _fltused
```
</details>

<details><summary>Click to expand codegen after:</summary>

```
C:\Temp>type meow.asm
        .text
        .def    @feat.00;
        .scl    3;
        .type   0;
        .endef
        .globl  @feat.00
.set @feat.00, 0
        .intel_syntax noprefix
        .file   "meow.cpp"
        .def    "?is_this_finite@@YA_NN@Z";
        .scl    2;
        .type   32;
        .endef
        .section        .text,"xr",one_only,"?is_this_finite@@YA_NN@Z"
        .globl  "?is_this_finite@@YA_NN@Z"      # -- Begin function ?is_this_finite@@YA_NN@Z
        .p2align        4, 0x90
"?is_this_finite@@YA_NN@Z":             # @"?is_this_finite@@YA_NN@Z"
# %bb.0:
        movq    rax, xmm0
        movabs  rcx, 9223372036854775807
        and     rcx, rax
        movabs  rax, 9218868437227405312
        cmp     rcx, rax
        setl    al
        ret
                                        # -- End function
        .section        .drectve,"yni"
        .ascii  " /DEFAULTLIB:libcmt.lib"
        .ascii  " /DEFAULTLIB:oldnames.lib"
        .ascii  " /FAILIFMISMATCH:\"_MSC_VER=1900\""
        .ascii  " /FAILIFMISMATCH:\"_ITERATOR_DEBUG_LEVEL=0\""
        .ascii  " /FAILIFMISMATCH:\"RuntimeLibrary=MT_StaticRelease\""
        .ascii  " /DEFAULTLIB:libcpmt.lib"
        .addrsig
        .globl  _fltused
```
</details>

### CODE REVIEW

**Comment by frederick-vs-ja** [comment]
> Also note an additional limitation: calls to the binary comparison functions with mixed argument types will select the UCRT templates as being better matches.

I'm planning to create a follow-up PR addressing this. The changes would be somehow boilerplate though.

File: tests/std/tests/GH_000519_cmath_overloads/test.cpp [hunk 1]
```diff
@@ -158,7 +159,94 @@ CONSTEXPR23 void test_other_integral_overloads() {
     }
 }
 
-CONSTEXPR23 bool test_all_integral_overloads() {
+template <class F>
+CONSTEXPR23 void test_floating_overloads() {
+    constexpr F zero = 0;
```
Comment (CaseyCarter) [inline tests/std/tests/GH_000519_cmath_overloads/test.cpp:164]: Here's hoping Nintendo lawyers don't come after us for using `F zero` in our sources =)

**Review by CaseyCarter — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.
