### PR TITLE
<chrono>: fix year_month_day_last::day()

### LINKED ISSUE #1647: <chrono>: UB in `year_month_day_last::day()` when `!ok()`
**Describe the bug**

`year_month_day_last::day()` accesses an array without bounds check.
https://github.com/microsoft/STL/blob/7f08bb3887f32156df003458b2de71fffbfe59e5/stl/inc/chrono#L1511-L1513
https://github.com/microsoft/STL/blob/7f08bb3887f32156df003458b2de71fffbfe59e5/stl/inc/chrono#L1334-L1343
Other call sites of `_Last_day` have checked `_Month.ok()` before calling, except `year_month_day_last::day()`.

[[time.cal.ymdlast.members]/15](http://eel.is/c++draft/time.cal.ymdlast.members#15)
> _Returns_: If `ok()` is `true`, [...]. Otherwise, the returned value is unspecified.

`year_month_day_last::day()` shouldn't invoke UB even if `!ok()`.

**Command-line test case**

```cpp
#include <chrono>
#include <iostream>

using namespace std;
using namespace std::chrono;

int main() {
    cout << static_cast<unsigned int>((2020y / 0 / last).day()) << "\n";
    return 0;
}
```
```
C:\Users\He\source\test>cl /EHsc /W4 /std:c++latest ymd_last.cpp
用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.28.29828 版
版权所有(C) Microsoft Corporation。保留所有权利。

/std:c++latest 作为最新的 C++
working 草稿中的语言功能预览提供。我们希望你提供有关 bug 和改进建议的反馈。
但是，请注意，这些功能按原样提供，没有支持，并且会随着工作草稿的变化
而更改或移除。有关详细信息，请参阅
https://go.microsoft.com/fwlink/?linkid=2045807。

ymd_last.cpp
Microsoft (R) Incremental Linker Version 14.28.29828.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:ymd_last.exe
ymd_last.obj

C:\Users\He\source\test>.\ymd_last.exe

C:\Users\He\source\test>echo %ERRORLEVEL%
-1073741819
```

**Expected behavior**

Should print an unspecified value, but not crash.

**STL version**

https://github.com/microsoft/STL/commit/7f08bb3887f32156df003458b2de71fffbfe59e5

### PR DESCRIPTION
**Pull request by SuperWig**
Fixes #1647

### CODE REVIEW

File: tests/std/tests/P0355R7_calendars_and_time_zones_dates/test.cpp [hunk 1]
```diff
@@ -975,7 +976,7 @@ constexpr void year_month_day_last_test() {
                 if (y.ok() && mdl.ok()) {
                     assert((y / mdl).ok());
                 } else {
-                    assert(!(y / mdl).ok());
+                    assert(!(y / static_cast<int>(m) / last).ok());
```
Comment (SuperWig) [inline tests/std/tests/P0355R7_calendars_and_time_zones_dates/test.cpp:979]: Could have sworn this failed the test without the fix earlier...

File: stl/inc/chrono [hunk 2]
```diff
@@ -1331,15 +1331,15 @@ namespace chrono {
         return *this;
     }
 
-    inline constexpr day _Last_day_table[] = {
-        day{31}, day{28}, day{31}, day{30}, day{31}, day{30}, day{31}, day{31}, day{30}, day{31}, day{30}, day{31}};
+    inline constexpr day _Last_day_table[] = {day{31}, day{28}, day{31}, day{30}, day{31}, day{30}, day{31}, day{31},
+        day{30}, day{31}, day{30}, day{31}, day{42}, day{42}, day{42}, day{42}};
```
Comment (AdamBucior) [inline stl/inc/chrono:1335]: 42 is confusing. Maybe just 0?

Comment (SuperWig) [reply stl/inc/chrono:1335]: I didn't want to just outright disrespect Casey like that.

Comment (CaseyCarter) [reply stl/inc/chrono:1335]: Now we can argue about the precise value: I am firmly of the belief that it should be `day{0}` or greater than `day{31}` so it's outside of the `ok()` range. I am slightly less certain that it should be a large enough number to create high relative error in calculations so bugs are more readily apparent. You may not notice something is off by 1 or 2 until shipping, but hopefully a calculation that requires a month with 137 days to make sense will catch your eye.

Given the above, I'm inclined to suggest a number like `day{45}` or `day{65}` that's precisely between an integral number of months worth of days. Despite being largely a joke in the issue discussion, `day{42}` wouldn't seem to be horrible.

Opinions?

Comment (CaseyCarter) [reply stl/inc/chrono:1335]: Oh, and whatever magic number we land upon, we should have a clarifying comment here. Otherwise, the PR looks good to me.

File: stl/inc/chrono [hunk 3]
```diff
@@ -1331,15 +1331,16 @@ namespace chrono {
         return *this;
     }
 
-    inline constexpr day _Last_day_table[] = {
-        day{31}, day{28}, day{31}, day{30}, day{31}, day{30}, day{31}, day{31}, day{30}, day{31}, day{30}, day{31}};
+    // To prevent UB by going out of bounds, four extra days with an invalid day are added.
```
Comment (SuperWig) [inline stl/inc/chrono:1334]: Would saying how it prevents that be necessary? The only usage of this array is _right there_ 7 lines down.

File: stl/inc/chrono (hunk 2 above)
Comment (StephanTLavavej) [reply stl/inc/chrono:1336]: I'd consider either `day{0}` or `day{255}` as the extreme values, but ultimately I'd recommend `day{255}`. It will immediately appear to be garbage in a way that `day{0}` might not always be (imagine code that is transforming these values back to integers, and summing them up; adding `0` might go unnoticed, but adding `255` will look bogus way faster). As an aside, 255 / 30 = 8.5 exactly.

File: stl/inc/chrono (hunk 3 above)
Comment (StephanTLavavej) [reply stl/inc/chrono:1334]: I think this comment is fine. The code is a little strange, so it's okay to spend one line and avoid potential confusion.

File: stl/inc/chrono [hunk 4]
```diff
@@ -1331,15 +1331,16 @@ namespace chrono {
...
+    inline constexpr day _Last_day_table[] = {day{31}, day{28}, day{31}, day{30}, day{31}, day{30}, day{31}, day{31},
+        day{30}, day{31}, day{30}, day{31}, day{42}, day{42}, day{42}, day{42}};
 
     _NODISCARD constexpr day _Last_day(const year& _Year, const month& _Month) {
         if (_Month == month{2} && _Year.is_leap()) {
             return day{29};
         }
 
-        return _Last_day_table[static_cast<unsigned int>(_Month) - 1];
+        return _Last_day_table[(static_cast<unsigned int>(_Month) - 1) & 15u];
```
Comment (StephanTLavavej) [inline stl/inc/chrono:1343]: Style: I personally find it slightly jarring to see decimal numbers in a bitwise context (for some reason, `15` doesn't immediately read as `1` less than `16`). I would recommend any of:
* `& 0xF`
* `& 0b1111` (probably too verbose, so less preferred)
* `% 16` (and trust the codegen will be good; this would *work* for any decimal value, it just happens be efficient for powers of 2, which are easy to recognize in decimal)

File: tests/std/tests/P0355R7_calendars_and_time_zones_dates/test.cpp [hunk 5]
```diff
@@ -967,6 +967,7 @@ constexpr void year_month_day_last_test() {
     if (is_constant_evaluated()) {
         static_assert((2020y / 1 / last).ok());
         static_assert(!(2020y / 13 / last).ok());
+        static_assert(!(2020y / 0 / last).day().ok());
```
Comment (StephanTLavavej) [inline tests/std/tests/P0355R7_calendars_and_time_zones_dates/test.cpp:970]: Should this have a comment that the `day()` is unspecified, and we're assuming that our implementation returns one that's `!ok()`? `// implementation-specific assumption, see GH-1647` would be sufficient.

File: tests/std/tests/P0355R7_calendars_and_time_zones_dates/test.cpp [hunk 6]
```diff
@@ -976,6 +977,7 @@ constexpr void year_month_day_last_test() {
                     assert((y / mdl).ok());
                 } else {
                     assert(!(y / mdl).ok());
+                    assert((y / mdl).day().ok() || (y / mdl).day() == day{42});
```
Comment (StephanTLavavej) [inline tests/std/tests/P0355R7_calendars_and_time_zones_dates/test.cpp:980]: Similarly, whatever the bogus value ends up being, I think this should be commented as an implementation-specific assumption.

(Our tests are not yet intended to be run against any other STL like libc++, but that's a possibility in the future, and it just makes them easier to understand years down the road, as implementations and Standards change.)

**Review by StephanTLavavej — CHANGES_REQUESTED** [review]

File: tests/std/tests/P0355R7_calendars_and_time_zones_dates/test.cpp (hunk 6 above)
Comment (SuperWig) [reply tests/std/tests/P0355R7_calendars_and_time_zones_dates/test.cpp]: Adding `"see GH-1647" to this one caused it to wrap so I just omitted it here. I thought the other would suffice since it's hopefully obvious it's the same implementation-specific assumption being made.

Comment (SuperWig) [reply tests/std/tests/P0355R7_calendars_and_time_zones_dates/test.cpp]: I guess it could also just be `// GH-1647`?

Comment (StephanTLavavej) [reply tests/std/tests/P0355R7_calendars_and_time_zones_dates/test.cpp]: Either is good, I'm happy with the `// implementation-specific assumption` that you picked.

**Review by StephanTLavavej — APPROVED** [review]

**Review by CaseyCarter — APPROVED** [review]

**Review by mnatsuhara — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Thanks for improving Standard conformance here! :smiley_cat: :tada:
