### PR TITLE
<filesystem>: `directory_entry(const path&, error_code&)` should return error code

### LINKED ISSUE #232: <filesystem>: `directory_entry(const path& p, error_code& ec)` does not return error code
https://github.com/microsoft/STL/blob/d736fe46b950860a29d420da44da40c0df62b8cb/stl/inc/filesystem#L2106-L2109

Notice the `_Ec` is cleared but never assigned the return value of `_Refresh()`. Compare this with:

https://github.com/microsoft/STL/blob/d736fe46b950860a29d420da44da40c0df62b8cb/stl/inc/filesystem#L2147-L2149

This is at best inconsistent with calling `std::directory_entry::refresh( std::error_code& ec)` but I would argue that it's the constructor that's wrong.

This can be easily tested by giving these two methods the same non-existent file path. The expected behaviour is that both of these methods return the same `error_code` value. i.e. NOT having the constructor form return success for an error code, but then calling `refresh()` returns a failure error code.

**Sample test code**
```
// compile with: cl /std:c++17 /permissive- /EHsc /Od /Zi symlink.cpp
// run: .\symlink does_not_exist
//
#include <filesystem>
#include <iostream>
namespace fs = std::filesystem;

int main(int argc, const char* argv[])
{
  if (argc < 2)
  {
    std::cerr << "Missing file path argument\n";
    return -1;
  }
  fs::path dst(argv[1]);

  std::error_code err1;
  fs::directory_entry src(dst, err1);
  std::cout << "directory_entry(" << dst << ") = " << err1 << " " << err1.message() << "\n";

  std::error_code err2;
  src.refresh(err2);
  std::cout << "refresh(" << dst << ") = " << err2 << " " << err2.message() << "\n";

  return 0;
}
```

Also tracked by Microsoft-internal VSO-1012326 / [AB#1012326](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1012326).

### PR DESCRIPTION
**Pull request by Arzaghi**
Fixes #232 

I've tried to follow `[fs.dir.entry.cons]` of the Standard document. I think there were some test cases against the Standard definition in the tests, so I have modified them. Besides the original issue, I thought the functions under `[fs.dir.entry.mods]` need the same fix as well.

### CODE REVIEW

**Comment by StephanTLavavej** [comment]
I don't understand why the CI isn't running; I'll ask the other maintainers for help tomorrow. :crying_cat_face:

**Comment by Arzaghi** [comment]
> I don't understand why the CI isn't running; I'll ask the other maintainers for help tomorrow.

My first commit triggered the pipeline and passed all the tests. At that stage, it was a draft PR. I pushed a new commit and after that, the CI isn't running anymore! :confused:

**Comment by StephanTLavavej** [comment]
My PR #1345 is also affected (and it didn't go through a draft stage) so it's not just you. I haven't seen this failure mode before so we've got some investigation to do... :detective:

File: tests/std/tests/P0218R1_filesystem/test.cpp [hunk 1]
```diff
@@ -1216,10 +1214,10 @@ void test_directory_entry() {
     for (auto&& nonexistent : nonexistentPaths) {
         cachingEntry.assign(nonexistent); // no fail
         cachingEntry.assign(nonexistent, ec);
-        EXPECT(good(ec));
+        EXPECT(bad(ec));
```
Comment (barcharcraz) [inline tests/std/tests/P0218R1_filesystem/test.cpp:1217]: at some point we should consider changing these to plain asserts, but that time is not today. No change requested.,

**Review by barcharcraz — APPROVED** [review]

File: tests/std/tests/P0218R1_filesystem/test.cpp [hunk 2]
```diff
@@ -994,12 +994,10 @@ void test_directory_entry() {
         EXPECT(!nonexistentEntry.exists());
 
         directory_entry nonexistentEntryEc(nonexistent, ec);
-        EXPECT(nonexistentEntryEc.path() == nonexistent);
+        EXPECT(nonexistentEntryEc.path() == path{});
```
Comment (StephanTLavavej) [inline tests/std/tests/P0218R1_filesystem/test.cpp:997]: While the changes to the `error_code` overloads in `<filesystem>` appear to be correct, the behavior as depicted in this test is surprising. Specifically, it is strange that the non-`error_code` construction can succeed, while the `error_code` construction fails and produces different state. The general behavior of `<filesystem>` should be that the exception interface and `error_code` interface behave identically, except for how they report errors.

(And if the non-`error_code` overloads are changed to call `refresh()` as specified by the Standard, they would begin throwing - which would restore consistency, but would result in even greater changes in observable behavior.)

I think this reduces down to a question about how `refresh()`/`refresh(ec)` should behave for nonexistent paths. Why do they report an error, instead of successfully caching the fact that the path is non-existent? Is it because the Windows API makes it hard/impossible to distinguish "the path does not exist" versus "we couldn't determine what the path resolved to"? We have:

https://github.com/microsoft/STL/blob/68b344c9dcda6ddf1a8fca112cb9033f9e50e787/stl/inc/xfilesystem_abi.h#L51-L61

, is that relevant?

File: tests/std/tests/P0218R1_filesystem/test.cpp [hunk 3]
```diff
@@ -1216,10 +1214,10 @@ void test_directory_entry() {
     for (auto&& nonexistent : nonexistentPaths) {
         cachingEntry.assign(nonexistent); // no fail
```
Comment (StephanTLavavej) [inline tests/std/tests/P0218R1_filesystem/test.cpp:1215]: Observation: The comment above this loop, `// assert that mutating the path doesn't fail even though the target doesn't exist`, and the `// no fail` comment for the non-`error_code` overload, strongly indicate that these functions should be succeeding - which seems to indicate that `refresh` should succeed for non-existent paths.

**Review by StephanTLavavej — CHANGES_REQUESTED** [review]

**Comment by Arzaghi** [comment]
@StephanTLavavej 
>  Specifically, it is strange that the non-error_code construction can succeed, while the error_code construction fails and produces a different state. The general behavior of <filesystem> should be that the exception interface and error_code interface behave identically, except for how they report errors.

I definitely agree with you. So, Because we have several tests [here](https://github.com/microsoft/STL/blob/2914b4301c59dc7ffc09d16ac6f7979fde2b7f2c/tests/std/tests/P0218R1_filesystem/test.cpp#L982-L992), [here](https://github.com/microsoft/STL/blob/2914b4301c59dc7ffc09d16ac6f7979fde2b7f2c/tests/std/tests/P0218R1_filesystem/test.cpp#L1207-L1215) and [here](https://github.com/llvm/llvm-project/blob/a668ad92d5e2161e07e1a435a19ea5072f52a989/libcxx/test/std/input.output/filesystems/class.directory_entry/directory_entry.obs/path.pass.cpp#L25-L45) that expect constructing a `directory_entry` using nonexistent path not to fail. So the `error_code` constructor should behave identically(i.e: set error code = 0)
All these tests mean constructors should not fail for nonexistent paths.

Then the standard document explicitly says _[fs.dir.entry.cons]_:
> ```
> explicit directory_entry(const filesystem::path& p);
> directory_entry(const filesystem::path& p, error_code& ec);
> ```
> 1 Effects: Calls refresh() or refresh(ec), respectively.
> 2 Postconditions: path() == p if no error occurs, otherwise path() == filesystem::path()

So we can deduce that both `refresh()` and `refresh(ec)` should not fail for nonexistent paths too. However, [this](https://github.com/microsoft/STL/blob/2914b4301c59dc7ffc09d16ac6f7979fde2b7f2c/tests/std/tests/P0218R1_filesystem/test.cpp#L994) test line was against the deduction. So I remove it!
My last commit applies the above deduction.

This behavior appears to be correct. However, both [Clang and GCC](https://godbolt.org/z/nEvon3) implementations do not follow this deduction!
Also, [this commit](https://github.com/microsoft/STL/pull/1343/commits/e95a83a486159a0a01a978847bb200da72ff1478) of my PR behave as libc++.

File: stl/inc/filesystem [hunk 4]
```diff
@@ -2134,12 +2134,14 @@ namespace filesystem {
         directory_entry(const directory_entry&)     = default;
         directory_entry(directory_entry&&) noexcept = default;
         explicit directory_entry(const filesystem::path& _Path_arg) : _Cached_data{}, _Path(_Path_arg) {
-            (void) _Refresh(_Cached_data, _Path);
+            refresh();
```
Comment (BillyONeal) [inline stl/inc/filesystem:2137]: This reverts a very intentional change, see discussion in the original issue report.

File: stl/inc/filesystem [hunk 5]
```diff
@@ -2151,35 +2153,39 @@ namespace filesystem {
...
             _Ec.clear(); // for exception safety
             _Path.assign(_Path_arg);
-            (void) _Refresh(_Cached_data, _Path);
+            refresh(_Ec);
         }
 
         void replace_filename(const filesystem::path& _Path_arg) {
             _Path.replace_filename(_Path_arg);
-            (void) _Refresh(_Cached_data, _Path);
+            refresh();
```
Comment (BillyONeal) [inline stl/inc/filesystem:2167]: This causes replace_filename(nonexistent) to throw which seems incorrect.

Comment (e4lam) [reply stl/inc/filesystem:2167]: I'm the original bug submitter and not the PR author. In my review of this PR, it looks like `refresh()` has been changed to never throw on "file not found".

**Comment by StephanTLavavej** [comment]
Note to self: catch up on the discussion in https://github.com/microsoft/STL/issues/232#issuecomment-888696588 before reviewing this PR. (Apologies for the lack of progress here lately, we've been trying to catch up on the PR backlog but it keeps growing :scream_cat:)

**Review by strega-nil-ms — CHANGES_REQUESTED** [review]
Other than those minor nits, I'm in favor of this change; the discussion in #232 implies to me that this is the correct way to go; having `refresh()` and `directory_entry(const filesystem::path&)` having different behavior is a bug.

The choice to make `refresh()` on a non-existent file succeed is, imo, the correct behavior, especially given that LLVM's libc++ makes exactly the same choice [here][libc++.std::directory_entry::__refresh]:

```cxx
  _LIBCPP_INLINE_VISIBILITY
  void __refresh(error_code* __ec = nullptr) {
    __handle_error("in directory_entry::refresh", __ec, __do_refresh(),
                   /*allow_dne*/ true);
  }
```

[libc++.std::directory_entry::__refresh]: https://github.com/llvm/llvm-project/blob/7ab1ab0db40158e6f0794637054c98376e236a6d/libcxx/include/__filesystem/directory_entry.h#L342

**Comment by BillyONeal** [comment]
> The choice to make refresh() on a non-existent file succeed is, imo, the correct behavior

That seems reasonable to me.

> especially given that LLVM's libc++ makes exactly the same choice [here](https://github.com/llvm/llvm-project/blob/7ab1ab0db40158e6f0794637054c98376e236a6d/libcxx/include/__filesystem/directory_entry.h#L342):

FWIW I don't think "what libc++ does" is an arbiter of correct behavior. Not only is caching behavior intentionally not specified in the standard, what we cache is substantially different. The attributes they cache aren't different in character for existing files vs. nonexisting files which is not true for us.

=================================

Don't forget to consider the other effect this does: it makes `directory_entry(const path&)` fail for things that are not file-not-found, where previously it was non failing. (That is, after all, what #232 is talking about) You may want to specifically consider cases like broken symlinks or symlinks of the wrong directory-ness.

(I'm intentionally not making further statements on whether to take the change or not given that I'm no longer a maintainer and haven't been looking at this closely for a long time, only pointing out things to consider :) )

**Comment by StephanTLavavej** [comment]
I have pushed a conflict-free merge with `main` so that the checks will run with toolset update #2754.

File: tests/std/tests/P0218R1_filesystem/test.cpp [hunk 6]
```diff
@@ -995,8 +995,6 @@ void test_directory_entry() {
         // Test VSO-892890 "std::filesystem::directory_entry constructor initializes wrong state"
         EXPECT(!nonexistentEntryEc.exists());
         EXPECT(good(ec));
-
-        EXPECT(throws_filesystem_error([&] { nonexistentEntryEc.refresh(); }, "directory_entry::refresh", nonexistent));
```
Comment (StephanTLavavej) [inline tests/std/tests/P0218R1_filesystem/test.cpp:999]: Removing this is a minimal way to get the test passing again, but I think it would be better to add test coverage verifying that the changed functions all accept nonexistent paths. Adding such coverage would thoroughly address @BillyONeal's concern and demonstrate that the behavior is not regressing.

The constructors are already tested above, and `assign` and `replace_filename` are already tested below, so we just need to cover `refresh()`:

https://github.com/microsoft/STL/blob/17fde2cbab6e8724d81c9555237c9a623d7fb954/tests/std/tests/P0218R1_filesystem/test.cpp#L1212-L1220

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
After catching up on all of the discussion here and in #232, checking the Standard, and checking this PR's behavior, I believe that this change is correct and avoids regressing any previous fixes. I pushed a very small addition to the test coverage.

Apologies for my exceptionally long review delay here! I've moved this to Final Review so Nicole can check the commits after her previous review - then we should be able to merge this next week.

**Review by strega-nil-ms — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
Thanks again for investigating and fixing this bug in the C++17 filesystem library! :open_file_folder: :lady_beetle: :heart_eyes_cat:

**Comment by e4lam** [comment]
Thank you all!
