### PR TITLE
Make `this_thread::sleep_until` clock-aware

### LINKED ISSUE #718: <thread>: this_thread::sleep_until uses system time even if based on steady_clock
**Describe the bug**
Internally, `sleep_until` calls `_To_xtime_10_day_clamped` to convert time point of any clock to time point of System clock. Then `_Thrd_sleep` sleeps on this system time point:
https://github.com/microsoft/STL/blob/31419650d472932dd24b9c5602707b0454f61fb2/stl/inc/thread#L154-L166

`_To_xtime_10_day_clamped` uses `system_clock`
https://github.com/microsoft/STL/blob/31419650d472932dd24b9c5602707b0454f61fb2/stl/inc/chrono#L629-L652

If `system_clock` is adjusted between `_To_xtime_10_day_clamped` and `_Thrd_sleep`, the sleep interval is wrong.

`sleep_for` is also subject to this problem as it is based on `sleep_until`
https://github.com/microsoft/STL/blob/31419650d472932dd24b9c5602707b0454f61fb2/stl/inc/thread#L168-L171
Though standard says
> The functions whose names end in _­for take an argument that specifies a duration. These functions produce relative timeouts. Implementations should use a steady clock to measure time for these functions.

**Command-line test case**
Hard to build stable repro, but will try if needed.

**Expected behavior**
Neither `sleep_until` relative to a steady clock nor `sleep_for` should depend on `system_clock`.

`GetTickCount64` is good enough steady clock, as `Sleep` API does not have granularity less than a millisecond anyway (calling undocumented `NtDelayExecution` is unacceptable). `GetTickCount64` is very fast clock, it is basically reading a global variable.

**STL version**
```
Microsoft Visual Studio Professional 2019 Preview
Version 16.6.0 Preview 2.1
```
**Additional context**
~~Suspect that tests for #593 are failing due to timeout because other tests simultaneously tamper with system clock.~~  Ok, this theory is defeated now, but the bug still looks valid

### PR DESCRIPTION
**Pull request by achabense**
Partially addresses #718.

Fixes `this_thread::sleep_until / sleep_for`: 
- replace `_Thrd_sleep` with `_Thrd_sleep_for`, which is a direct call to windows `Sleep` (`_Thrd_sleep` also relies on `Sleep`, but is bound to system-clock).
- replace usage of `_To_timespec64_sys_10_day_clamped` with clock-aware logic in `sleep_until`.

Thanks to @AlexGuteniev for helping me figure out how to add import-library functions ❤️

### CODE REVIEW

File: stl/src/sharedmutex.cpp [hunk 1]
```diff
@@ -36,4 +36,9 @@ void __cdecl _Smtx_unlock_exclusive(_Smtx_t* smtx) { // unlock exclusive shared
 void __cdecl _Smtx_unlock_shared(_Smtx_t* smtx) { // unlock non-exclusive shared mutex
     ReleaseSRWLockShared(reinterpret_cast<PSRWLOCK>(smtx));
 }
+
+void __cdecl _Thrd_sleep_for(const long long ns) { // attempt to suspend thread for at least `ns` nanoseconds
+    constexpr long _Nsec_per_msec = 1'000'000L;
```
Comment (achabense) [inline stl/src/sharedmutex.cpp:41]: I'm using the same name as in `xtime.cpp`:
https://github.com/microsoft/STL/blob/0fe653a9d6efd2ac0ad07825804436672dbffe3b/stl/src/xtime.cpp#L12

Comment (AlexGuteniev) [inline stl/src/sharedmutex.cpp:41]: The rest of the file is non-_Ugly, see `smtx` and `ns` variables, so it should be `nsec_per_msec`

File: stl/inc/xthreads.h [hunk 2]
```diff
@@ -126,6 +125,7 @@ int __cdecl _Smtx_try_lock_exclusive(_Smtx_t*);
 int __cdecl _Smtx_try_lock_shared(_Smtx_t*);
 void __cdecl _Smtx_unlock_exclusive(_Smtx_t*);
 void __cdecl _Smtx_unlock_shared(_Smtx_t*);
+void __cdecl _Thrd_sleep_for(long long /*ns*/); // TRANSITION: defined in sharedmutex.cpp for convenience
```
Comment (AlexGuteniev) [inline stl/inc/xthreads.h:128]: I'm questioning having `TRANSITION` in this comment.
I really don't think that a single function deserves its own `.cpp` file.
Later on with vNext this will be moved to the usual static/dynamic STL Library rather than Import Library, but this is implied for entire or nearly entire Import Library, so no extra `TRANSITION` comment needed.

Comment (BillyONeal) [inline stl/inc/xthreads.h:128]: I still strongly disagree with an interface in `ns` given that the underlying bits ultimately accept `FILETIME` units, as that sells the interface as doing something it ultimately can't do, and pays range loss and scaling penalties to do so. In the hypothetical future a new Windows API exists that accepts nanos exists, by all means we can add one. But this status quo has been the status quo since NT's inception in 1993 and I don't see it changing for the foreseeable future.

(nanos made sense for Linux because they wanted to speak `struct timespec` which separates out a separate nanos field from `time_t`, with most software only needing to consider the `time_t`. NT never internally used `time_t`, and choosing 100ns increments gave a simple 64 bit counter enough range that they could set the epoch back at the start of the 400 year Gregorian calendar cycle at the time (January 1 1601) while still having ~20'000+ years of future range. Given this framing I don't see any reason NT would want to adopt nanos.)

File: stl/src/sharedmutex.cpp [hunk 3]
```diff
@@ -36,4 +36,9 @@ void __cdecl _Smtx_unlock_exclusive(_Smtx_t* smtx) { // unlock exclusive shared
 void __cdecl _Smtx_unlock_shared(_Smtx_t* smtx) { // unlock non-exclusive shared mutex
     ReleaseSRWLockShared(reinterpret_cast<PSRWLOCK>(smtx));
 }
+
+void __cdecl _Thrd_sleep_for(const long long ns) { // attempt to suspend thread for at least `ns` nanoseconds
+    constexpr long nsec_per_msec = 1'000'000L;
+    Sleep(static_cast<DWORD>((ns + nsec_per_msec - 1) / nsec_per_msec));
```
Comment (BillyONeal) [inline stl/src/sharedmutex.cpp:42]: It will require preprocessor pain but you can reduce this problem to an `NtWaitForSingleObject` call which will give you more range and the ability to reasonably handle absolute waits against the system clock. Here's the code I wrote way back when we were going to do an ABI break in 2017... please excuse the Whitesmiths indent style and the `__vcp_` prefix on things back when we thought VCPlatform would be a thing.

The trick is to wait on `GetCurrentThread()`; we know the current thread can never be signaled, because it is running.

```
constexpr unsigned long _Max_sleep_length{ULONG_MAX - 1U};

static void _Bounds_check(const unsigned long long _Relative_filetime) noexcept
    {    // checks that the input FILETIME is in valid bounds
    if (_Relative_filetime > static_cast<unsigned long long>(LLONG_MAX))
        {    // out of range (~30,000 years in the future)
        __vcp_fastfail();
        }
    }

static void _Win32_sleep(unsigned long long _Relative_filetime) noexcept
    {    // low resolution relative sleep in terms of Win32 Sleep
    _Relative_filetime /= 10'000;    // convert from 100ns intervals to 1ms intervals
                                    // 1e-7 -> 1e-3 == 4 zeros
    while (_Relative_filetime > _Max_sleep_length)
        {
        Sleep(_Max_sleep_length);
        _Relative_filetime -= _Max_sleep_length;
        }

    Sleep(static_cast<unsigned long>(_Relative_filetime));
    }

extern "C" void __cdecl __std_thread_sleep_system(const unsigned long long _Relative_filetime) noexcept
    {    // sleep a relative time measured against the system clock
    _Bounds_check(_Relative_filetime);
    if (__vcp_has_NtWaitForSingleObject())
        {
        long long _Now;
        __vcp_get_system_time_precise_as_file_time(reinterpret_cast<FILETIME *>(&_Now));
        const long long _Offset = static_cast<long long>(_Relative_filetime); // safe because we _Bounds_check'ed
        if (_Now > LLONG_MAX - _Offset)
            {    // out of range
            __vcp_fastfail();
            }

        LARGE_INTEGER _Desired;
        _Desired.QuadPart = _Now + _Offset;
        __vcp_NtWaitForSingleObject(
            GetCurrentThread(), // Can't become signaled because we're running
            FALSE,
            &_Desired // positive value == absolute wait
            );
        }
    else
        {    // can't do absolute waits on this platform, fall back to relative
        _Win32_sleep(_Relative_filetime);
        }
    }

extern "C" void __cdecl __std_thread_sleep_steady(const unsigned long long _Relative_filetime) noexcept
    {    // sleep a relative time measured against a steady clock
    _Bounds_check(_Relative_filetime);
    if (__vcp_has_NtWaitForSingleObject())
        {
        LARGE_INTEGER _Desired;
        _Desired.QuadPart = -static_cast<long long>(_Relative_filetime);
        __vcp_NtWaitForSingleObject(
            GetCurrentThread(), // Can't become signaled because we're running
            FALSE,
            &_Desired // negative value == relative wait
            );
        }
    else
        {
        _Win32_sleep(_Relative_filetime);
        }
    }

template<class _Rep,
    class _Period> inline
    long long _Time_to_filetime(const chrono::duration<_Rep, _Period>& _Rel_time)
    {    // convert a relative time to the minimum time greater than or equal (so that we wait for at least _Rel_time)
    return (chrono::ceil<
        chrono::duration<long long, ratio<1, 10'000'000>>>(_Rel_time).count());
    }

template<class _Rep,
    class _Period> inline
    void sleep_for(const chrono::duration<_Rep, _Period>& _Rel_time)
    {    // sleep for duration
    if (_Rel_time > chrono::duration<_Rep, _Period>::zero())
        {
        __std_thread_sleep_steady(_Time_to_filetime(_Rel_time));
        }
    }

template<class _Clock,
    class _Duration> inline
    void sleep_until(const chrono::time_point<_Clock, _Duration>& _Abs_time)
    {    // sleep until time point
    const auto _Abs_target = _Abs_time.time_since_epoch();
    for (;;)
        {
        const auto _Now = _Clock::now().time_since_epoch();
        if (!(_Now < _Abs_target))
            return;
        const auto _Relative_filetime = _Time_to_filetime(_Abs_target - _Now);
        if (is_same_v<_Clock, chrono::system_clock>)
            {
            __std_thread_sleep_system(_Relative_filetime);
            }
        else
            {
            __std_thread_sleep_steady(_Relative_filetime);
            }
        }
    }
```

**Review by BillyONeal — COMMENTED** [review]
I'm leaving these comments in my capacity as an individual; I'm no longer a maintainer and won't be following this PR going forward, but I think the folks who actually are maintainers should consider them. In particular, I feel strongly that `ns` is not the correct type when all platform APIs speak `FILETIME` 100ns units. (The other comments are really nitpicks)

**Comment by achabense** [comment]
In this pr, should I:
1. make `_Thrd_sleep_for` accept `100ns` instead?
2. make `_Reltime_ns_10_day_clamped` more general? 
2.1. let this function take `_Now` and `_Then` as parameters, so that not to call `_Clock::now()` within the function?
2.2. make clamp value a template parameter?
2.3. make return type a template parameter?

I think these can be quality enhancements in the future:

3. Adopt more accurate machinery for `_Thrd_sleep_for`.
4. In `wait_until`, make sleep intervals more fine-grained if `_Clock` is not steady.

**Comment by achabense** [comment]
Though a bit off-topic, I think it's not harmful to add `if constexpr` in these places in this pr:
https://github.com/microsoft/STL/blob/fc444ce44a0b98eb20f95247c839cb7627af8c5e/stl/inc/__msvc_chrono.hpp#L428-L439

**Comment by frederick-vs-ja** [comment]
> Though a bit off-topic, I think it's not harmful to make a push to add `if constexpr` in these places in this pr:

It seems to me that we should do this in another PR. I think that new PR will be approved and merged before this PR.

**Comment by achabense** [comment]
As to ns vs 100ns, my perceptions are:
- `system_clock` is 100ns-based
- `steady_clock` is ns-based
- `sleep_for` use `steady_clock`
- the ns/100ns-to-ms conversion is unavoidable on the side of `_Thrd_sleep_for`
- the current wait/sleep utilities widely go through ns-based `_timespce64`, though a lot of these value comes from `_Xtime_get_ticks` which is 100ns-based

> as that sells the interface as doing something it ultimately can't do

As to this argument, as `_Thrd_sleep(_for)` cannot make a promise on either ns or 100ns precision, I think ns vs 100ns makes no difference here. Actually, as commented in `_Thrd_sleep_for`, I've loosened the promise as `attempt to suspend thread for at least ...`

**Comment by StephanTLavavej** [comment]
In my opinion, the separately compiled code should generally be a thin wrapper over the Windows API. Except when we need modifiable global state, the purpose of the DLL/LIB is to avoid dragging in `<Windows.h>` - we prefer to have as much code as possible be header-only. (Older code didn't adhere to this discipline which is where a lot of our problems come from.)

**Comment by AlexGuteniev** [comment]
> we prefer to have as much code as possible be header-only

`<charconv>` tables seem to disagree.

**Comment by StephanTLavavej** [comment]
I originally implemented them header-only! :smile_cat: (And while there are throughput advantages, there are also costs - we will never be able to remove them even after switching algorithms.) Basically there are always reasons for special exceptions, but that's the general rule - code in headers is more flexible and less burdensome for maintenance.

File: stl/src/sharedmutex.cpp (hunk 3 above)
Comment (StephanTLavavej) [reply stl/src/sharedmutex.cpp:42]: I'm going to resolve this without taking action because that's a ton of code and I'm not sure if we can use `NtWaitForSingleObject` (it's desktop-only, has to be GetProcAddressed, etc).

File: stl/inc/thread [hunk 4]
```diff
@@ -173,6 +173,23 @@ _NODISCARD auto _To_absolute_time(const chrono::duration<_Rep, _Period>& _Rel_ti
     return _Abs_time;
 }
 
+template <class _Clock, class _Duration>
+_NODISCARD chrono::nanoseconds _Reltime_ns_10_day_clamped(const chrono::time_point<_Clock, _Duration>& _Then) {
```
[the remark this answers is not in the document]
Comment (StephanTLavavej) [reply stl/inc/thread:177]: I'm not worried about the code size (or throughput) implications of having this be on the header side; how many clocks is a program going to be using? Keeping more stuff out of the separately compiled code is generally desirable in my opinion.

**Comment by S0SLA** [comment]
By achabense:

I’m sorry that I cannot take part in development these days. Before this I’ve made a feedback branch to 1. make _Thrd_sleep_for a direct call to Sleep. 2. merge _Reltime… template into sleep_for, as I think its too early to generalize this utility. Please help mark this pr work in progress temporarily, I will go back as soon as I have time(maybe several days later).
As to the constexpr if, I think it would be nice to make an issue for some newcomers to do the contribution.

**Comment by achabense** [comment]
I'm back; I was unluckily not able to upload the branch early, here it is: https://github.com/microsoft/STL/commit/c70eb1314847fb4d6f86fc15309abf7b1de0a432
I will do a push if this branch looks better.

**Comment by StephanTLavavej** [comment]
Yes, after a brief glance the direction of that branch looks good to us; by the way, we now use `__stdcall` in new code because it's slightly more efficient (smaller code size since the callee pops instead of the caller), we should follow this convention even though it means that the declaration will differ compared to the nearby `shared_mutex` support functions.

**Comment by achabense** [comment]
I've made a new push; some questions are:
1. Can we make those `_Smtx...` functions `__stdcall` as well?
2. What's the real clamp requirement in `Sleep`? (I'm blindly applying 10-day clamp by following old practices.)
3. Can we make sleep intervals more fine-grained for unstable clocks like `system_clock`?

**Comment by StephanTLavavej** [comment]
> Can we make those `_Smtx...` functions `__stdcall` as well?

No, that would break bincompat. Old user-compiled OBJs will be looking for `__cdecl` functions in the import lib.

(We could introduce new `__stdcall` functions with new names, but we can never get rid of the old `__cdecl` functions from the import lib. That's the price of bincompat, and adding things to the import lib is not "free" in that sense.)

I don't know the answers to your sleep questions.

**Comment by achabense** [comment]
> There are still the following functions:
> 
> ```c++
> _CRTIMP2_PURE int __cdecl _Mtx_timedlock(_Mtx_t, const xtime*);
> _CRTIMP2_PURE int __cdecl _Cnd_timedwait(_Cnd_t, _Mtx_t, const xtime*);
> ```
> 
> I think we should either not resolve the original issue or create a follow-up issue.

I've changed my pr description to avoid closing the original issue.

File: stl/inc/xthreads.h (hunk 2 above)
Comment (achabense) [reply stl/inc/xthreads.h]: I've removed `TRANSITION`.

File: stl/inc/thread [hunk 5]
```diff
@@ -196,10 +196,14 @@ namespace this_thread {
             if (_Abs_time <= _Now) {
                 return;
             }
-
-            _timespec64 _Tgt;
-            (void) _To_timespec64_sys_10_day_clamped(_Tgt, _Abs_time - _Now);
-            _Thrd_sleep(&_Tgt);
+            constexpr chrono::milliseconds _Clamp{chrono::hours{24}};
```
Comment (achabense) [inline stl/inc/thread:199]: I think there is no 10-day limit to `Sleep`. As there have to be a clamp to avoid integer overflow etc, I've choosed one day as clamp value. This is a bit arbitary, but I think it should work well.

File: stl/inc/xthreads.h [hunk 6]
```diff
@@ -83,10 +83,10 @@ enum class _Thrd_result : int { _Success, _Nomem, _Timedout, _Busy, _Error };
 // threads
 _CRTIMP2_PURE _Thrd_result __cdecl _Thrd_detach(_Thrd_t);
 _CRTIMP2_PURE _Thrd_result __cdecl _Thrd_join(_Thrd_t, int*);
-_CRTIMP2_PURE void __cdecl _Thrd_sleep(const _timespec64*);
 _CRTIMP2_PURE void __cdecl _Thrd_yield();
 _CRTIMP2_PURE unsigned int __cdecl _Thrd_hardware_concurrency();
 _CRTIMP2_PURE _Thrd_id_t __cdecl _Thrd_id();
+void __stdcall _Thrd_sleep_for(unsigned long /*ms*/); // defined in sharedmutex.cpp for convenience
```
Comment (achabense) [inline stl/inc/xthreads.h:89]: `noexcept`?

Comment (AlexGuteniev) [reply stl/inc/xthreads.h:89]: usually `extern C` implies `noexcept`, but there is the other mode, so I'm not sure...

**Comment by achabense** [comment]
Can we also add back the piece of test mentioned in #1642?

**Review by StephanTLavavej — APPROVED** [review]

**Review by CaseyCarter — APPROVED** [review]
I'll push changes for these nearly non-functional comments.

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
:thread: :zzz: :alarm_clock:
===

File: stl/inc/xthreads.h [hunk 7]
```diff
@@ -83,10 +83,10 @@ enum class _Thrd_result : int { _Success, _Nomem, _Timedout, _Busy, _Error };
 // threads
 _CRTIMP2_PURE _Thrd_result __cdecl _Thrd_detach(_Thrd_t);
 _CRTIMP2_PURE _Thrd_result __cdecl _Thrd_join(_Thrd_t, int*);
-_CRTIMP2_PURE void __cdecl _Thrd_sleep(const _timespec64*);
```
Comment (jjerphan) [inline stl/inc/xthreads.h:86]: Hi,

I think the removal of this line broke the ABI compatibility of `std::thread::sleep_for`.

For more context, see: https://github.com/actions/runner-images/issues/9398

**Comment by StephanTLavavej** [comment]
Yep. This is documented at https://learn.microsoft.com/en-us/cpp/porting/binary-compat-2015-2017?view=msvc-170 .

**Comment by NipaJ** [comment]
`_Thrd_sleep_for` is missing `_CRTIMP2_PURE`, forcing static linkage always. This is problematic, since the function is missing from the DLL version of the runtime library.

**Comment by StephanTLavavej** [comment]
By design: https://github.com/microsoft/STL/pull/4457#issuecomment-2941202955
