### PR TITLE
Avoid "friends of friends" (CWG1699) in `common_iterator`

### LINKED ISSUE #2065: `<iterator>`: The implementation of `common_iterator::operator==` seems to be wrong
MSVC-STL's implementation of `common_iterator` is similar to [libstdc++](https://github.com/gcc-mirror/gcc/blob/trunk/libstdc%2B%2B-v3/include/bits/stl_iterator.h#L1680), it defines `operator==` inside the class:
https://github.com/microsoft/STL/blob/bd7adb4a932725f60ba096580c415616486ab64c/stl/inc/iterator#L930-L940

and declares template `common_iterator` class as a friend:
https://github.com/microsoft/STL/blob/bd7adb4a932725f60ba096580c415616486ab64c/stl/inc/iterator#L1008-L1010

But according to the description of [[class.friend#10]](https://timsong-cpp.github.io/cppwp/n4868/class.friend#10): "Friendship is neither inherited nor transitive."
This will cause the following valid code to be rejected [(godbolt)](https://godbolt.org/z/15ao981Wb):

  ```
#include <iterator>

int main() {
    std::common_iterator<int*, std::unreachable_sentinel_t> it1;
    std::common_iterator<const int*, std::unreachable_sentinel_t> it2;
    return it1 == it2;
}
```

### PR DESCRIPTION
**Pull request by CaseyCarter**
CWG consensus is that friend functions defined inline in a class `X` should be treated as friends of classes that befriend `X`, but there's implementation divergence. (Probably because the issue has been in "drafting" for eight years.)

Fixes #2065

### CODE REVIEW

File: stl/inc/iterator [hunk 1]
```diff
@@ -994,22 +996,24 @@ public:
...
-        return _RANGES iter_swap(_Left._Val._Iterator, _Right._Val._Iterator);
+        return _RANGES iter_swap(_Left._Val._Iterator, _Right_val._Iterator);
     }
 
-private:
-    // clang-format off
-    template <input_or_output_iterator _OIter, sentinel_for<_OIter> _OSe>
-        requires (!same_as<_OIter, _OSe> && copyable<_OIter>)
-    friend class common_iterator;
-    // clang-format on
```
Comment (CaseyCarter) [inline stl/inc/iterator:1011]: Not the removal of cross-specialization friendship here; I've chosen to use `_Get_val` consistently in both member functions and friend functions.

**Comment by miscco** [comment]
LGTM except that I am missing some test coverage

**Comment by CaseyCarter** [comment]
> LGTM except that I am missing some test coverage

Something funny is going on: we are somehow missing cross-type comparison coverage, but we do have cross-type difference coverage which is not failing.

**Review by miscco — APPROVED** [review]

File: stl/inc/iterator [hunk 2]
```diff
@@ -994,22 +996,24 @@ public:
...
+    _Variantish<_Iter, _Se>& _Get_val() {
+        return _Val;
+    }
+    const _Variantish<_Iter, _Se>& _Get_val() const {
+        return _Val;
+    }
```
Comment (StephanTLavavej) [inline stl/inc/iterator:1014]: I believe these can/should be `_NODISCARD` and `noexcept`.

File: tests/std/tests/P0896R4_common_iterator/test.cpp [hunk 3]
```diff
@@ -194,8 +194,43 @@ bool test_operator_arrow() {
     return true;
 }
 
+struct poor_sentinel {
+    template <weakly_incrementable _Winc>
```
Comment (StephanTLavavej) [inline tests/std/tests/P0896R4_common_iterator/test.cpp:198]: `_Winc` shouldn't be `_Ugly`. Occurs below.

File: tests/std/tests/P0896R4_common_iterator/test.cpp [hunk 4]
```diff
@@ -194,8 +194,43 @@ bool test_operator_arrow() {
...
+        return 0;
+    }
+
+    template <weakly_incrementable _Winc>
+    [[nodiscard]] friend constexpr iter_difference_t<_Winc> operator-(const _Winc&, const poor_sentinel&) noexcept {
+        return 0;
+    }
+};
+
+void test_2065() { // Guard against regression of GH-2065, for which we previously stumbled over CWG-1699.
```
Comment (StephanTLavavej) [inline tests/std/tests/P0896R4_common_iterator/test.cpp:214]: This should be either `test_gh_2065` or `test_GH_2065` because we should never mention bug numbers without a database.

**Review by StephanTLavavej — COMMENTED** [review]
Looks good, I'll validate and push simple changes.

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
FYI @miscco, I pushed simple changes after you approved.

**Review by mnatsuhara — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I'm mirroring this to an MSVC-internal PR. Please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
Thanks for fixing this friendship bug! :smile_cat: :tada: :rocket:
