### PR TITLE
Fix <filesystem> linker errors for UWP developers

### LINKED ISSUE #322: <filesystem>: GetVolumePathNameW linker errors for UWP developers
We've defined these functions in `filesystem.cpp` to implement `std::filesystem::space()`:

https://github.com/microsoft/STL/blob/8f4c8163775d665d80642044ce27c4bc696127ce/stl/src/filesystem.cpp#L266-L277

https://github.com/microsoft/STL/blob/8f4c8163775d665d80642044ce27c4bc696127ce/stl/src/filesystem.cpp#L763-L798

Because this is a single source file, whose object file is injected into the import lib (effectively linking statically), when a developer uses anything from `std::filesystem` that needs separately compiled support machinery, `filesystem.obj` is dragged in.

For UWP developers, there's an issue with all currently available versions of the Windows SDK where `GetVolumePathNameW()` isn't usable (without linking to `onecoreuap.lib`, which is an arcane workaround that nobody knows about). This has been fixed and will be available in a future version of the Windows SDK. However, at this time, UWP developers who attempt to use anything from `std::filesystem` that needs separately compiled support, like `std::filesystem::create_directories()`, are experiencing mysterious linker errors.

We can change how the STL is built in order to fix this scenario for the vast majority of UWP developers. (Only UWP developers specifically calling `std::filesystem::space()` would still be affected; they inherently need either the `onecoreuap.lib` workaround or the future Windows SDK.)

We simply need to move `_Fs_space_attempt()` and `__std_fs_space()` into a separate source/object file, so that the linker drags it in only when specifically needed. We can comment this as `TRANSITION` to remove the workaround later, although it's unclear how long this workaround will be needed.

I am unfamiliar with UWP environments, but this should be simple to validate with desktop compilations - use `/link /verbose` to ensure that the new object file is dragged in when, and only when, `std::filesystem::space()` is directly used.

Also tracked by Microsoft-internal VSO-1000285.

### PR DESCRIPTION
**Pull request by StephanTLavavej**
# Description

* Fix #322: `<filesystem>`: `GetVolumePathNameW` linker errors for UWP developers
* Improve clang-format with `StatementMacros`.
* Rewrap comments in `<execution>`.

# Checklist

Be sure you've read README.md and understand the scope of this repo.

If you're unsure about a box, leave it unchecked. A maintainer will help you.

- [x] Identifiers in product code changes are properly `_Ugly` as per
  https://eel.is/c++draft/lex.name#3.1 or there are no product code changes.
- [x] The STL builds successfully and all tests have passed (must be manually
  verified by an STL maintainer before automated testing is enabled on GitHub,
  leave this unchecked for initial submission).
- [x] These changes introduce no known ABI breaks (adding members, renaming
  members, adding virtual functions, changing whether a type is an aggregate
  or trivially copyable, etc.).
- [x] These changes were written from scratch using only this repository,
  the C++ Working Draft (including any cited standards), other WG21 papers
  (excluding reference implementations outside of proposed standard wording),
  and LWG issues as reference material. If they were derived from a project
  that's already listed in NOTICE.txt, that's fine, but please mention it.
  If they were derived from any other project (including Boost and libc++,
  which are not yet listed in NOTICE.txt), you *must* mention it here,
  so we can determine whether the license is compatible and what else needs
  to be done.

### CODE REVIEW

File: stl/src/filesystem_space.cpp [hunk 1]
```diff
@@ -0,0 +1,73 @@
...
+
+#include <internal_shared.h>
+#include <limits.h>
+#include <xfilesystem_abi.h>
+
+#include <Windows.h>
+
+namespace {
+    static_assert(sizeof(uintmax_t) == sizeof(ULARGE_INTEGER) && alignof(uintmax_t) == alignof(ULARGE_INTEGER),
+        "Size and alignment must match for reinterpret_cast<PULARGE_INTEGER>");
```
Comment (sylveon) [inline stl/src/filesystem_space.cpp]: Curious, any reason for this `static_assert` instead of using `QuadPart` on `ULARGE_INTEGER`, `bit_cast`ing it, or using bit-shifts on `HighPart` and `LowPart`?

Comment (BillyONeal) [reply stl/src/filesystem_space.cpp]: 1. Because `QuadPart` is not necessarily `intmax_t`.
2. Because `bit_cast` didn't exist when this code was written (and still does not exist).
3. Because the shifts etc. have a code size and maintainability cost.
4. Because we want the pointers to be passed down directly without this code needing to dereference them at all.

Comment (StephanTLavavej) [reply stl/src/filesystem_space.cpp]: I've filed #357 to track this. Note that the API wants to scribble into `ULARGE_INTEGER` variables which we don't have (all we have are `uintmax_t*`), so if we want to avoid the `reinterpret_cast`s, we would need to introduce such variables (at which point we can just assign from `QuadPart`).
