### PR TITLE
`<ranges>`: Fix `views::reverse` for `ranges::reverse_view` lvalues

### LINKED ISSUE #2312: `<ranges>`: using `views::reverse` on `ranges::reverse_view` lvalue is broken
### Describe the bug

Using `views::reverse` on (possibly const) lvalue of type `ranges::reverse_view<X>` does not result in `X`, but in `ranges::reverse_view<X>`.

### Command-line test case

```c++
#include <ranges>

using namespace std;

int main() {
    using X = ranges::iota_view<int, int>;
    ranges::reverse_view<X> view;
    static_assert( same_as<decltype(view | views::reverse), X>);
    static_assert(!same_as<decltype(view | views::reverse), ranges::reverse_view<X>>);
}
```

```text
C:\Temp>cl /std:c++latest /EHsc broken-reverse.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30136 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

/std:c++latest is provided as a preview of language features from the latest C++
working draft, and we're eager to hear about bugs and suggestions for improvements.
However, note that these features are provided as-is without support, and subject
to changes or removal as the working draft evolves. See
https://go.microsoft.com/fwlink/?linkid=2045807 for details.

broken-reverse.cpp
broken-reverse.cpp(8): error C2607: static assertion failed
broken-reverse.cpp(9): error C2607: static assertion failed
```

[Test case in compiler explorer.](https://godbolt.org/z/rqYhMaxaE)

### Expected behavior

This code should compile.

### STL version

16.11.5 and 17.0.0.

### Additional context

This code can be compiled with [GCC](https://godbolt.org/z/cv63ddxob) and [clang](https://godbolt.org/z/5TvE6baPM).

[Extra test (GCC in compiler explorer).](https://godbolt.org/z/8q67aMnW8)

### PR DESCRIPTION
**Pull request by cpplearner**
Fixes #2312

### CODE REVIEW

File: stl/inc/ranges [hunk 1]
```diff
@@ -4167,24 +4167,24 @@ namespace ranges {
 
             template <class _Rng>
             _NODISCARD static _CONSTEVAL _Choice_t<_St> _Choose() noexcept {
-                if constexpr (bidirectional_range<_Rng>) {
```
Comment (cpplearner) [inline stl/inc/ranges:4170]: I removed the `bidirectional_range<_Rng>` check because

1. [\[range.reverse.overview\]/2](http://eel.is/c++draft/range.reverse.overview#2) does not seem to have this
2. this breaks the following (contrived) code:

```c++
#include <ranges>
#include <iterator>
#include <istream>

using namespace std::ranges;
using namespace std::views;

struct weird : view_interface<weird> {
    int* begin();
    int* end();
    std::istreambuf_iterator<char> begin() const;
    std::istreambuf_iterator<char> end() const;
};

int main() {
    const auto v1 = weird{};
    auto v2 = reverse(v1); // rejected by MSVC STL, accepted by libstdc++
    auto v3 = reverse_view{v1}; // accepted by MSVC STL and libstdc++
}
```

File: tests/std/tests/P0896R4_views_reverse/test.cpp [hunk 2]
```diff
@@ -317,6 +317,13 @@ using move_only_view = test::range<Category, const int, test::Sized{is_random},
     IsCommon, test::CanCompare{derived_from<Category, forward_iterator_tag>},
     test::ProxyRef{!derived_from<Category, contiguous_iterator_tag>}, test::CanView::yes, test::Copyability::move_only>;
 
+void test_gh2312() {
```
Comment (CaseyCarter) [inline tests/std/tests/P0896R4_views_reverse/test.cpp:320]: Let's remind our future selves that this code doesn't actually execute:
```suggestion
void test_gh2312() { // COMPILE-ONLY
```

File: stl/inc/ranges (hunk 1 above)
Comment (CaseyCarter) [reply stl/inc/ranges:4170]: I must have been thinking this was `bidirectional_range<remove_cvref_t<_Rng>>`?  Even if that is correct, checking it first seems to make the first 3 cases more expensive and has no effect on the `reverse_view` case. I'll put this in the "I don't know what I was thinking, but I know I was wrong" bucket. (No change requested.)

**Review by CaseyCarter — CHANGES_REQUESTED** [review]

**Review by CaseyCarter — APPROVED** [review]

**Review by miscco — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Updated title so we can easily see what this PR does.

File: tests/std/tests/P0896R4_views_reverse/test.cpp [hunk 3]
```diff
@@ -317,6 +317,12 @@ using move_only_view = test::range<Category, const int, test::Sized{is_random},
     IsCommon, test::CanCompare{derived_from<Category, forward_iterator_tag>},
     test::ProxyRef{!derived_from<Category, contiguous_iterator_tag>}, test::CanView::yes, test::Copyability::move_only>;
 
+void test_gh2312() { // COMPILE-ONLY
+    using X = ranges::iota_view<int, int>;
+    ranges::reverse_view<X> view;
```
Comment (StephanTLavavej) [inline tests/std/tests/P0896R4_views_reverse/test.cpp:322]: This comes close to shadowing `ranges::view`:
https://github.com/microsoft/STL/blob/ee5a216b516ef033d9153b324842369eee7653d1/stl/inc/xutility#L2701-L2702

In general, I recommend avoiding top-level Standard identifiers. This improves codebase searchability, and makes tests quickly scannable by humans (e.g. if I see `vector` or `string` in a test, I can assume I'm looking at the Standard one).

However, as this doesn't actually shadow, no change requested - I think this is sufficiently small that a rename is not worth resetting testing.

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
Thanks for fixing this ranges bug!

(I reversed this message twice, but you can't tell the difference now! :joy_cat: :zany_face: :tada:)
