### PR TITLE
<format> locale fixes

### LINKED ISSUE #1852: <format>: Formatting functions use a wrong locale
**Describe the bug**

`std::format` and other formatting functions other than those that take locale as an argument incorrectly use the "C" locale.
It doesn't make sense because it results in the output of the `L` specifier to be effectively unlocalized. The global locale should be used instead, quoting https://eel.is/c++draft/format#context-6:

> std::locale locale();
> Returns: The locale passed to the formatting function if the latter takes one, and std​::​locale() otherwise.

Additionally, the current locale handling is inefficient because the locale is obtained eagerly (although with a wrong function) even in the common case when it's unused. Instead it's better to obtain it lazily when processing the `L` specifier.

**Command-line test case**
```
C:\Temp>type test.cc
#include <format>
#include <iostream>

int main() {
  std::locale loc("English_United States.UTF8");
  std::locale::global(loc);
  std::cout.imbue(loc);
  std::cout << std::format("{:L}\n", 12345);
  std::cout << 12345;
}

C:\Temp>cl test.cc /utf-8 /I STL/stl/inc /std:c++latest
Microsoft (R) C/C++ Optimizing Compiler Version 19.29.29917 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

/std:c++latest is provided as a preview of language features from the latest C++
working draft, and we're eager to hear about bugs and suggestions for improvements.
However, note that these features are provided as-is without support, and subject
to changes or removal as the working draft evolves. See
https://go.microsoft.com/fwlink/?linkid=2045807 for details.

test.cc
STL/stl/inc\ostream(284): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc
STL/stl/inc\ostream(269): note: while compiling class template member function 'std::basic_ostream<char,std::char_traits<char>> &std::basic_ostream<char,std::char_traits<char>>::operator <<(int)'
test.cc(9): note: see reference to function template instantiation 'std::basic_ostream<char,std::char_traits<char>> &std::basic_ostream<char,std::char_traits<char>>::operator <<(int)' being compiled
test.cc(7): note: see reference to class template instantiation 'std::basic_ostream<char,std::char_traits<char>>' being compiled
Microsoft (R) Incremental Linker Version 14.29.29917.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:test.exe
test.obj

C:\Temp>test
12345
12,345
```

**Expected behavior**
Expected the output to be
```
12,345
12,345
```
because `std::format`'s locale-dependent (`L`) formatting should use the global locale.

**STL version**

https://github.com/microsoft/STL/commit/99e0477

### PR DESCRIPTION
**Pull request by barcharcraz**
* Fixes #1852 
* improves performance by only constructing locales if the format string actually has a locale sensitive format specifier in it. This gives a small but notable performance boost (for simple char* output I got ~130ns/call before and ~105ns/call after in my extremely unscientific benchmarks). I did verify that `std::locale::locale` no longer shows up in the profile after the change.

Note: there's an alternate, slightly more clever approach, where _Default_arg_formatter and basic_format_context store uninitialized storage for a locale, and it's again initialized on demand. The advantage of this is that in format strings with multiple locale sensitive format-specs the locale would only have to be constructed once, it also _might_ be possible to adopt this method without breaking ABI (although it would be scary). The disadvantage here is the code gets more confusing and it will be much harder to break the dependency on <locale> if we want to do that in the future.

### CODE REVIEW

**Comment by bhardwajs** [comment]
FYI @vitaut

File: stl/inc/format [hunk 1]
```diff
@@ -2133,9 +2162,9 @@ _NODISCARD _OutputIt _Fmt_write(
 
         if (_Specs._Localized) {
             _Out = _Write_separated_integer(_Buffer_start, _Integral_end, _Groups,
-                _STD use_facet<numpunct<_CharT>>(_Locale).thousands_sep(), _Separators, _STD move(_Out));
+                _STD use_facet<numpunct<_CharT>>(_Locale._Get()).thousands_sep(), _Separators, _STD move(_Out));
             if (_Radix_point != _Result.ptr || _Append_decimal) {
-                *_Out++         = _STD use_facet<numpunct<_CharT>>(_Locale).decimal_point();
+                *_Out++         = _STD use_facet<numpunct<_CharT>>(_Locale._Get()).decimal_point();
```
Comment (StephanTLavavej) [inline stl/inc/format:2167]: Pre-existing: It would be less verbose and more efficient to extract these `use_facet` calls. (There's a third one above, but this is conditional on `_Specs._Localized`, so unifying them all would be a bit of a headache.)

File: tests/std/tests/P0645R10_text_formatting_formatting/test.cpp [hunk 2]
```diff
@@ -1296,6 +1296,16 @@ void libfmt_formatter_test_runtime_precision() {
     assert(format(STR("{0:.{1}}"), STR("str"), 2) == STR("st"));
 }
 
+template <class charT>
+void test_locale_speicifc_formatting_without_locale() {
+#if !defined(_DLL) || _ITERATOR_DEBUG_LEVEL == DEFAULT_IDL_SETTING
+    std::locale loc("en_US.UTF-8");
```
Comment (StephanTLavavej) [inline tests/std/tests/P0645R10_text_formatting_formatting/test.cpp:1302]: This test is already `using namespace std`.

File: tests/std/tests/P0645R10_text_formatting_formatting/test.cpp [hunk 3]
```diff
@@ -1296,6 +1296,16 @@ void libfmt_formatter_test_runtime_precision() {
     assert(format(STR("{0:.{1}}"), STR("str"), 2) == STR("st"));
 }
 
+template <class charT>
+void test_locale_speicifc_formatting_without_locale() {
```
Comment (StephanTLavavej) [inline tests/std/tests/P0645R10_text_formatting_formatting/test.cpp:1300]: Typo.

File: tests/std/tests/P0645R10_text_formatting_formatting/test.cpp (hunk 2 above)
Comment (StephanTLavavej) [inline tests/std/tests/P0645R10_text_formatting_formatting/test.cpp:1302]: I think this should be hyphenated (other tests say `"en-US"`, and we've had repeated issues with underscore locales on different OSes). Also, because it's UTF-8, I think we need to guard this to run for GitHub only, as the internal test machines are too old. I'll do so pre-emptively because discovering this during the port process will be a timesink and GitHub provides sufficient coverage.

**Review by StephanTLavavej — COMMENTED** [review]
Thanks! I have a few comments that I'll push changes for.

**Review by StephanTLavavej — APPROVED** [review]

**Review by CaseyCarter — APPROVED** [review]
Approving as a clear improvement, but I think I'd like to investigate storing lazily-constructed `locale` and `_Cvtvec` in `basic_format_context` so we can guarantee at-most-one construction of each per `format` call.

**Comment by barcharcraz** [comment]
> 
> 
> Approving as a clear improvement, but I think I'd like to investigate storing lazily-constructed `locale` and `_Cvtvec` in `basic_format_context` so we can guarantee at-most-one construction of each per `format` call.

I don't think the effects the cvtvec at all, since that's populated once in the parsing functions, no matter how many format arguments you use.

**Comment by statementreply** [comment]
> I don't think this effects the cvtvec at all, since that's populated once in the parsing functions, no matter how many format arguments you use.

I observed that `format("{:.2f}", numbers::pi)` calls `__std_get_cvt` twice.

Besides, `GetCPInfoW` is so much slower than core `format` code that I think it’s worth going further and investigate 
catching the result across the program execution.

**Comment by barcharcraz** [comment]
> > I don't think this effects the cvtvec at all, since that's populated once in the parsing functions, no matter how many format arguments you use.
> 
> I observed that `format("{:.2f}", numbers::pi)` calls `__std_get_cvt` twice in non UTF-8 setting.
> 
> Besides, `GetCPInfoExW` is so much slower than core `format` code that I think it’s worth going further and investigate
> catching the result across the program execution.

Yeah, I want to investigate faster options, however it's not ABI and users have an escape hatch with `/utf-8` and the wide format. It's likely we'll make it faster in a future patch release, especially if the compiler grows the ability to just tell us what the execution charset is.

**Comment by StephanTLavavej** [comment]
Thanks for this combination bugfix/perf improvement! :beetle: :rocket: :smile_cat:
