### PR TITLE
Orphan before reallocation in vector<:ghost:>

### LINKED ISSUE #2440: `<vector>`: orphan after reallocation in `_Insert_x` has UB
Compiling this well-formed TU:
```c++
#include <iterator>
#include <vector>

using namespace std;

struct I { // demote pointer to input iterator
    using iterator_category = std::input_iterator_tag;
    using value_type = int;
    using difference_type = std::ptrdiff_t;
    using reference = const int&;
    using pointer = void;

    constexpr explicit I(const int* p) : ptr{p} {}

    constexpr bool operator==(const I& that) const {
        return this->ptr == that.ptr;
    }

    constexpr reference operator*() const {
        return *ptr;
    }

    constexpr I& operator++() {
        ++ptr;
        return *this;
    }
    constexpr void operator++(int) {
        ++*this;
    }

    const int* ptr;
};

static constexpr int numbers[33] = { // Just long enough to force a reallocation
    0, 1, 2, 3, 4, 5, 6, 7, 8, 9,
    0, 1, 2, 3, 4, 5, 6, 7, 8, 9,
    0, 1, 2, 3, 4, 5, 6, 7, 8, 9,
    0, 1, 2};

constexpr bool meow() {
    vector<bool> vec;
    vec.insert(vec.end(), I{numbers}, I{numbers + 33});
    return true;
}
static_assert(meow());
```
with `cl /nologo /std:c++20 /EHsc /Od /MTd` diagnoses:
```
repro.cpp
repro.cpp(45): error C2131: expression did not evaluate to a constant
c:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.31.30818\include\vector(2967): note: failure was caused by subtracting pointers to elements of different arrays
```
`clang-cl` produces the more informative compiletime call-stack:
```
repro.cpp(45,15): error: static_assert expression is not an integral constant
      expression
static_assert(meow());
              ^~~~~~
c:\[...]\include\vector(2967,82): note:
      subexpression not valid in a constant expression
            const auto _Off = static_cast<size_type>(_VBITS * (_Pnextiter._Myptr - _Base)) + _Pnextiter._Myoff;
                                                                                 ^
c:\[...]\include\vector(2985,13): note: in call
      to '&vec->_Orphan_range_unlocked(0, 33)'
            _Orphan_range_unlocked(_Offlo, _Offhi);
            ^
c:\[...]\include\vector(2947,13): note: in call
      to '&vec->_Orphan_range(0, 33)'
            _Orphan_range(static_cast<size_type>(_Realloc ? 0 : _Off), this->_Mysize);
            ^
c:\[...]\include\vector(2917,30): note: in call
      to '&vec->_Insert_x({{{&{*new std::_Container_proxy[1]#1}[0], &_Where}, &{*new unsigned int[1]#2}[1], 0}}, 1)'
        size_type _Off     = _Insert_x(_Where, _Count);
                             ^
c:\[...]\include\vector(2816,16): note: in call
      to '&vec->_Insert_n({{{&{*new std::_Container_proxy[1]#1}[0], &_Where}, &{*new unsigned int[1]#2}[1], 0}}, 1, *
      _First)'
        return _Insert_n(_Where, static_cast<size_type>(1), _Val);
               ^
c:\[...]\include\vector(2835,13): note: in call
      to '&vec->insert({{{&{*new std::_Container_proxy[1]#1}[0], &this->begin() + _Off}, &{*new unsigned int[1]#2}[1],
      0}}, * _First)'
            insert(begin() + _Off, *_First);
            ^
c:\[...]\include\vector(2826,9): note: in call to
      '&vec->_Insert({{{nullptr, &_Where}, nullptr, 0}}, {&numbers[32]}, {&numbers[33]}, {})'
        _Insert(_Where, _First, _Last, _Iter_cat_t<_Iter>{});
        ^
reprp.cpp(42,9): note: in call to '&vec->insert({{{nullptr, &vec.end()}, nullptr, 0}},
      {&numbers[0]}, {&numbers[33]})'
    vec.insert(vec.end(), I{numbers}, I{numbers + 33});
        ^
reprp.cpp(45,15): note: in call to 'meow()'
static_assert(meow());
              ^
1 error generated.
```
Invalid pointer comparison sounds like UB we can't get away with at compile time. It is, but a peek at `_Orphan_range`:

https://github.com/microsoft/STL/blob/303df3dae6f5ed9fe4f1c35257f663af8355584a/stl/inc/vector#L3200-L3220

shows this is a runtime bug also: computation of `_Off` for an iterator created when `_Base` (`_Myvec.data()`) had a different value results in something ludicrously out-of-range that won't be properly invalidated.

Popping up the call stack, the root cause is in `_Insert_x`:

https://github.com/microsoft/STL/blob/303df3dae6f5ed9fe4f1c35257f663af8355584a/stl/inc/vector#L3168-L3197

The call to `Myvec.resize` on line 3182 can potentially reallocate `_Myvec` (when `_Realloc` is `true`),  rendering all outstanding iterators invalid, which manifests the bug when we call `_Orphan_range` on line 3192.

The fix is straightforward: invalidate _before_ reallocating. Moving the `_Orphan_range` call before the `resize` call in `_Insert_x` corrects the bug.

### PR DESCRIPTION
**Pull request by CaseyCarter**
Fixes #2440

Drive-by: remove extraneous `public` in `deque`.

### CODE REVIEW

File: stl/inc/deque [hunk 1]
```diff
@@ -722,7 +722,6 @@ public:
         _Take_contents(_Right);
     }
 
-public:
```
Comment (CaseyCarter) [inline stl/inc/deque:725]: Redundant with `public` on line 703.

File: tests/std/tests/P1004R2_constexpr_vector_bool/test.cpp [hunk 2]
```diff
@@ -620,6 +620,52 @@ constexpr bool test_iterators() {
     return true;
 }
 
+#ifndef __EDG__ // TRANSITION, VSO_1274387
+constexpr bool test_gh2440() { // COMPILE-ONLY
```
Comment (miscco) [inline tests/std/tests/P1004R2_constexpr_vector_bool/test.cpp:624]: Could we move that to the Tests around line 400 instead?

This is basic functionality

File: tests/std/tests/P1004R2_constexpr_vector_bool/test.cpp [hunk 3]
```diff
@@ -620,6 +620,52 @@ constexpr bool test_iterators() {
     return true;
 }
 
+#ifndef __EDG__ // TRANSITION, VSO_1274387
+constexpr bool test_gh2440() { // COMPILE-ONLY
+    // vector<bool> was incorrectly reallocating before orphaning iterators
+    // (resulting in UB) when reallocating while inserting ranges of unknown
+    // length
```
Comment (CaseyCarter) [inline tests/std/tests/P1004R2_constexpr_vector_bool/test.cpp:627]: The repetition of "reallocating" is awkward here.

File: tests/std/tests/P1004R2_constexpr_vector_bool/test.cpp (hunk 2 above)
Comment (CaseyCarter) [reply tests/std/tests/P1004R2_constexpr_vector_bool/test.cpp:624]: IIUC, you mean to insert (pun intended) this as a normal "insert a non-forward range" test case - which we are missing - among the rest of the test coverage. Yes, this makes sense to me. I'll move it and rephrase the comment into an "this also guards against regression of GH-2440" comment.

Comment (miscco) [reply tests/std/tests/P1004R2_constexpr_vector_bool/test.cpp:624]: Thanks, and appologies for not covering input ranges.

You know we could also construct from an input range 😇

File: tests/std/tests/P1004R2_constexpr_vector_bool/test.cpp [hunk 4]
```diff
@@ -16,6 +16,39 @@ using namespace std;
 static constexpr bool input[]         = {true, false, true, true, false, true};
 static constexpr bool input_flipped[] = {false, true, false, false, true, false};
 
+struct demoterator { // demote pointer to input iterator
+    using iterator_category = std::input_iterator_tag;
+    using value_type        = int;
+    using difference_type   = std::ptrdiff_t;
+    using reference         = const int&;
+    using pointer           = void;
```
Comment (CaseyCarter) [inline tests/std/tests/P1004R2_constexpr_vector_bool/test.cpp:24]: Since this test is C++20-only, we could get by defining only `value_type` and `difference_type` here. Don't bother to change if we don't need to touch something else.

**Review by miscco — APPROVED** [review]

File: tests/std/tests/P1004R2_constexpr_vector_bool/test.cpp [hunk 5]
```diff
@@ -16,6 +16,39 @@ using namespace std;
 static constexpr bool input[]         = {true, false, true, true, false, true};
 static constexpr bool input_flipped[] = {false, true, false, false, true, false};
 
+struct demoterator { // demote pointer to input iterator
+    using iterator_category = std::input_iterator_tag;
+    using value_type        = int;
+    using difference_type   = std::ptrdiff_t;
```
Comment (StephanTLavavej) [inline tests/std/tests/P1004R2_constexpr_vector_bool/test.cpp:22]: This test is already `using namespace std`.

File: tests/std/tests/P1004R2_constexpr_vector_bool/test.cpp [hunk 6]
```diff
@@ -16,6 +16,39 @@ using namespace std;
...
 
+struct demoterator { // demote pointer to input iterator
+    using iterator_category = std::input_iterator_tag;
+    using value_type        = int;
+    using difference_type   = std::ptrdiff_t;
+    using reference         = const int&;
+    using pointer           = void;
+
+    constexpr bool operator==(const demoterator& that) const {
+        return this->ptr == that.ptr;
```
Comment (StephanTLavavej) [inline tests/std/tests/P1004R2_constexpr_vector_bool/test.cpp:27]: `this->` is unnecessary for a direct data member.

File: tests/std/tests/P1004R2_constexpr_vector_bool/test.cpp (hunk 4 above)
Comment (StephanTLavavej) [reply tests/std/tests/P1004R2_constexpr_vector_bool/test.cpp:24]: I am not sure whether we could make such a change. I see N4901 [algorithms.requirements]/4.1 "If an algorithm’s template parameter is named `InputIterator`, `InputIterator1`, or `InputIterator2`, the template argument shall meet the *Cpp17InputIterator* requirements (23.3.5.3)." Then [vector.bool] specifies `template<class InputIterator> constexpr iterator insert(const_iterator position, InputIterator first, InputIterator last);`.

I don't see anything saying that `vector<bool>::insert()` can accept C++20 input iterators. (I also can't find the paragraph that makes `InputIterator` in the Containers clause have the same Word Of Power meaning as in the Algorithms clause, although I thought such a paragraph existed.)

**Review by StephanTLavavej — APPROVED** [review]

File: tests/std/tests/P1004R2_constexpr_vector_bool/test.cpp (hunk 4 above)
Comment (CaseyCarter) [reply tests/std/tests/P1004R2_constexpr_vector_bool/test.cpp]: [algorithms.requirements] only applies to function templates that appear in subclauses of [algorithms]. The requirement that `vector<bool>::insert` takes Cpp17InputIterators comes from many miles away in [[sequence.reqmts]/3.5](https://eel.is/c++draft/sequence.reqmts#3.5). More importantly, removing all nested types other than `value_type` and `difference_type` would not alter the fact that this type meets the Cpp17InputIterator requirements; C++20's `iterator_traits` is smart enough to fill in the rest of the types if you declare `value_type` and `difference_type` ([[iterator.traits]/3.2](https://eel.is/c++draft/iterator.traits#3.2)).

Comment (StephanTLavavej) [reply tests/std/tests/P1004R2_constexpr_vector_bool/test.cpp]: [tab:inputiterator] says that *Cpp17InputIterator* requires `*r++` to be well-formed and "convertible to `T`", but `demoterator::operator++(int)` returns `void`.

Comment (CaseyCarter) [reply tests/std/tests/P1004R2_constexpr_vector_bool/test.cpp]: That requirement is broken enough (LWG-484, LWG2962) that I tend to just ignore it.

**Review by barcharcraz — APPROVED** [review]

File: tests/std/tests/P1004R2_constexpr_vector_bool/test.cpp (hunk 4 above)
Comment (StephanTLavavej) [reply tests/std/tests/P1004R2_constexpr_vector_bool/test.cpp]: Ah, ok. No other changes were necessary, so I'm going to resolve this without changes.

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
Thanks for fixing this haunted data structure! :ghost: :bat: :joy_cat:
