### PR TITLE
Fix not unlocking  and relocking in condition_variable_any::wait_for

### LINKED ISSUE #369: <condition_variable>: condition_variable_any::wait_for(0) does not unlock the lock
**Describe the bug**
In `condition_variable_any`, if the timeout is already expired, we immediately return with a timeout status:

https://github.com/microsoft/STL/blob/aa0a7a3d859ade0f6f1ff13aa4ef74b3d5ce2326/stl/inc/condition_variable#L74-L76

However, the standard depicts `condition_variable(_any)?` as unlocking the lock unconditionally as their first action: https://eel.is/c++draft/thread.condition.condvarany#thread.condvarany.wait-6

For `condition_variable`, this is unobservable; the user doesn't get to inspect what `std::mutex` does, so we can optimize that unlock and immediate lock as a no-op. (Indeed, even if we did not do this, Windows' locks are 'unfair' meaning that's the likely outcome even if we were to try to unlock and relock). However, for `condition_variable_any`, the user might be using a fair lock, or might even just log attempts to unlock and relock, so we should be calling their unlock even for an already expired timeout.

Also tracked by Developer Community as DevCom-733115, and Microsoft-internal VSO-973579.

### PR DESCRIPTION
**Pull request by bhardwajs**
In `condition_variable_any`, if the timeout is already expired, we immediately return with a timeout status. However, the standard depicts condition_variable(_any)? as unlocking the lock unconditionally as their first action: https://eel.is/c++draft/thread.condition.condvarany#thread.condvarany.wait-6

This PR fixes the bug in `condition_variable_any` to unlock and relock the user's lock for an already expired timeout.

Fixes #369

### CODE REVIEW

File: stl/inc/condition_variable [hunk 1]
```diff
@@ -99,6 +100,7 @@ public:
         for (;;) {
             const auto _Now = _Clock::now();
             if (_Abs_time <= _Now) {
+                _Unlock_relock(_Lck);
```
[the remark this answers is not in the document]
Comment (CaseyCarter) [reply stl/inc/condition_variable:103]: The `_Wait_until1` overload on 193-209 seems to need a similar treatment.

[the remark this answers is not in the document]
Comment (bhardwajs) [reply stl/inc/condition_variable:103]: Yes, `_Wait_until1` overload also needs change. I wanted it to be minimal change, but the right course would be to change all the implementations at once. Let me do that in the next iteration.

File: stl/inc/condition_variable [hunk 2]
```diff
@@ -156,6 +158,18 @@ private:
         return reinterpret_cast<_Cnd_t>(&_Cnd_storage);
     }
 
+    template <class _Lock>
+    void _Unlock_relock(_Lock& _Lck) noexcept /* terminates */ {
+        {
+            shared_ptr<mutex> _Ptr = _Myptr; // for immunity to *this destruction
+            lock_guard<mutex> _Lckguard(*_Ptr);
```
[the remark this answers is not in the document]
Comment (bhardwajs) [reply stl/inc/condition_variable:165]: Don't we need to lock-and-unlock the internal mutex to `block on *this`?

[the remark this answers is not in the document]
Comment (bhardwajs) [reply stl/inc/condition_variable]: @CaseyCarter - I just pushed a new iteration that uses internal `wait_until` implementation. Resolving this comment as the code is deleted.

File: stl/inc/condition_variable (hunk 1 above)
[the remark this answers is not in the document]
Comment (bhardwajs) [reply stl/inc/condition_variable]: @CaseyCarter - I just pushed a new iteration that uses internal `wait_until` implementation and aligns all the implementations. Resolving this comment as well.

**Comment by bhardwajs** [comment]
@CaseyCarter I pushed a new iteration that I think addresses your comments. Please have another look. Thanks!

**Comment by BillyONeal** [comment]
Can you add a test?

**Comment by bhardwajs** [comment]
> 
> 
> Can you add a test?

Sure, I can add a test just for this case. Would this be in `std/tests/GH_00000685...`?

**Comment by BillyONeal** [comment]
Yes, but only 3 zeroes :)

**Comment by bhardwajs** [comment]
> Yes, but only 3 zeroes :)

Pushed unit test, with only three zeroes :) (GH_000685_condition_variable_any)

File: tests/std/tests/GH_000685_condition_variable_any/test.cpp [hunk 3]
```diff
@@ -0,0 +1,59 @@
...
+using namespace std;
+
+namespace { // anonymous namespace
+    class my_mutex { // user-defined mutex type
+    public:
+        void lock() {
+            mtx.lock();
+            ++num_lock;
+        }
+        void unlock() {
```
Comment (cbezault) [inline tests/std/tests/GH_000685_condition_variable_any/test.cpp:20]: Nit: missing newline

Comment (bhardwajs) [reply tests/std/tests/GH_000685_condition_variable_any/test.cpp:21]: Added newline. Thanks @cbezault

File: tests/std/test.lst [hunk 4]
```diff
@@ -157,6 +157,7 @@ tests\Dev11_1158803_regex_thread_safety
 tests\Dev11_1180290_filesystem_error_code
 tests\GH_000457_system_error_message
 tests\GH_000545_include_compare
+tests\GH_000685_condition_variable_any
```
Comment (StephanTLavavej) [inline tests/std/test.lst:160]: I just realized that we're accumulating inconsistency here. All of our Dev11, VSO, etc. tests refer to bug numbers (in internal databases). I thought that was going to be our policy for GH tests, so my GH-545 test refers to an issue number. However, the GH-457 test refers to a PR number, as does this GH-685 test.

Since PRs and issues are cross-referenced, I suppose it doesn't matter, and our policy going forward can be "either PR or issue numbers are acceptable". Still, I wanted to mention this as an explicit decision.

File: tests/std/tests/GH_000685_condition_variable_any/test.cpp [hunk 5]
```diff
@@ -0,0 +1,60 @@
+// Copyright (c) Microsoft Corporation.
+// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
+
+// Test GH#685 "wait_for in condition_variable_any should unlock and lock"
```
Comment (StephanTLavavej) [inline tests/std/tests/GH_000685_condition_variable_any/test.cpp:4]: We conventionally use dashes in product/test code comments when referring to GitHub issues and other bugs, for consistency with GitHub autolinking (although it isn't active in the code itself).

```suggestion
// Test GH-685 "wait_for in condition_variable_any should unlock and lock"
```

File: tests/std/tests/GH_000685_condition_variable_any/test.cpp [hunk 6]
```diff
@@ -0,0 +1,60 @@
...
+        void lock() {
+            mtx.lock();
+            ++num_lock;
+        }
+
+        void unlock() {
+            mtx.unlock();
+        }
+
+        inline int num_locks() {
```
Comment (StephanTLavavej) [inline tests/std/tests/GH_000685_condition_variable_any/test.cpp:25]: Member functions defined within their class definition are already implicitly `inline`. Also, this should probably be `const` as it's a pure observer:

```suggestion
        int num_locks() const {
```

File: tests/std/test.lst (hunk 4 above)
Comment (cbezault) [reply tests/std/test.lst:160]: I think if we're willing to move to accepting PR numbers we should be more explicit about always linking an issue to the PR.

**Comment by StephanTLavavej** [comment]
I'm going to go ahead and push fixes for these incredibly tiny issues, plus a comment consistency cleanup.

File: tests/std/test.lst (hunk 4 above)
Comment (StephanTLavavej) [reply tests/std/test.lst:160]: Good idea, I've updated https://github.com/microsoft/STL/wiki/Checklist-For-Merging-A-Pull-Request with "Verify that the PR is linked to the issues that it resolves."

File: stl/inc/condition_variable [hunk 7]
```diff
@@ -96,19 +82,10 @@ public:
...
-            (void) _To_xtime_10_day_clamped(_Tgt, _Abs_time - _Now);
-            const cv_status _Result = wait_until(_Lck, &_Tgt);
-            if (_Result == cv_status::no_timeout) {
-                return cv_status::no_timeout;
-            }
-        }
+        const auto _Now = _Clock::now();
+        _CSTD xtime _Tgt;
+        (void) _To_xtime_10_day_clamped(_Tgt, _Abs_time - _Now);
+        return wait_until(_Lck, &_Tgt);
```
Comment (CaseyCarter) [inline stl/inc/condition_variable:88]: This seems to damage correctness by returning `cv_status::timeout` after 10 days if `_Abs_time` is more than 10 days in the future.

File: stl/inc/condition_variable [hunk 8]
```diff
@@ -70,21 +70,7 @@ public:
...
-        // but unfortunately our ABI speaks struct xtime, which is relative to the system clock.
-        _CSTD xtime _Tgt;
-        const bool _Clamped     = _To_xtime_10_day_clamped(_Tgt, _Rel_time);
-        const cv_status _Result = wait_until(_Lck, &_Tgt);
-        if (_Clamped) {
-            return cv_status::no_timeout;
-        }
-
-        return _Result;
+        return wait_until(_Lck, chrono::steady_clock::now() + _Rel_time);
```
Comment (CaseyCarter) [inline stl/inc/condition_variable:73]: It's unfortunate that we call `steady_clock::now()` here and immediately again on line 85. Could we avoid this with some clever refactoring?

File: stl/inc/condition_variable [hunk 9]
```diff
@@ -178,20 +155,10 @@ private:
...
-            if (wait_until(_Xtrnl, &_Tgt) == cv_status::timeout && !_Clamped) {
-                return _Pred();
-            }
-        }
-
-        return true;
+        const auto _Now = _Clock::now();
+        _CSTD xtime _Tgt;
+        (void) _To_xtime_10_day_clamped(_Tgt, _Abs_time - _Now);
+        return _Wait_until1(_Xtrnl, &_Tgt, _Pred);
```
Comment (CaseyCarter) [inline stl/inc/condition_variable:161]: Ditto "This damages correctness if `_Abs_time` is more than 10 days in the future" by prematurely returning even if `_Pred` is `false`.

File: stl/inc/condition_variable (hunk 7 above)
Comment (CaseyCarter) [reply stl/inc/condition_variable:88]: I think we want to:
```c++
const bool _Clamped = _To_xtime_10_day_clamped(_Tgt, _Abs_time - _Now);
const cv_status _Result = wait_until(_Lck, &_Tgt);
if (_Clamped) {
  return cv_status::no_timeout;
}
return _Result;
```

Comment (CaseyCarter) [reply stl/inc/condition_variable:88]: I think we've also damaged correctness by allowing negative durations into `_To_xtime_10_day_clamped` which previously couldn't happen. That function should probably pretend the input is `0` when negative - IIRC all callers treat negatives and 0 the same.

Comment (StephanTLavavej) [reply stl/inc/condition_variable:88]: Great catch! I wonder if we should make the 10-day clamp configurable for the purposes of manual testing (a 10-second clamp is testable in a way that a 10-day clamp is not).

File: stl/inc/condition_variable (hunk 8 above)
Comment (StephanTLavavej) [reply stl/inc/condition_variable:73]: If I substitute in `wait_until`'s fixed definition according to your suggestion, and eliminate `now - now` (which we can assume to be zero given infinitely fast execution), I just get the original definition of this function except missing the early return for `if (_Rel_time <= chrono::duration<_Rep, _Period>::zero())`. So should that just be the change here?

Comment (CaseyCarter) [reply stl/inc/condition_variable:73]: Yes, I think that sounds great.

File: stl/inc/condition_variable (hunk 7 above)
Comment (CaseyCarter) [reply stl/inc/condition_variable:88]: > I wonder if we should make the 10-day clamp configurable for the purposes of manual testing (a 10-second clamp is testable in a way that a 10-day clamp is not).

That would be great. It's nightmarish to test anything timeout-related. @bhardwajs, let us know if that sounds like more work than you signed on for and we'll make a separate issue.

File: stl/inc/condition_variable (hunk 9 above)
Comment (CaseyCarter) [reply stl/inc/condition_variable:161]: Nope. There's more to fix: the Standard says this (well, the pretty function anyway) returns immediately when `_Pred()` is `true`, for example. I think:
```c++
while (!_Pred()) {
    const auto _Now = _Clock::now();
    _CSTD xtime _Tgt;
    const bool _Clamped = _To_xtime_10_day_clamped(_Tgt, _Abs_time - _Now);
    const cv_status _Result = _Wait_until1(_Xtrnl, &_Tgt, _Pred);
    if (!_Clamped && _Result == cv_status::timeout) {
        return _Pred();
    }
}
return true;
```

File: stl/inc/condition_variable (hunk 7 above)
Comment (bhardwajs) [reply stl/inc/condition_variable:88]: @CaseyCarter - I can take on the configurability of `_clamped`. I think it should be a small change. Right?

For tracking purposes, that should be a separate issue of enhancement in infrastructure. Not sure, if we want to have a separate PR for that. What do you think?

File: stl/inc/condition_variable (hunk 8 above)
Comment (bhardwajs) [reply stl/inc/condition_variable:73]: @CaseyCarter , @StephanTLavavej  - Original bug was in the early return for `_Rel_time <= chrono::duration<_Rep, _Period>::zero()` as the code was skipping unlock and lock. I think the code is easier to understand and maintain if we don't try to optimize away those cases. Thoughts?

Comment (StephanTLavavej) [reply stl/inc/condition_variable:73]: It's true that the current state of the PR centralizes more of the logic, which is usually good for understanding and maintenance as you mentioned. However, translating from the relative time domain to absolute time, and back to relative, adds an additional point of confusion for understanding, adds performance cost, and affects the behavior slightly (as the elapsed time between the two `now()` calls affects reasoning about the code).

I believe that going back to the original implementation here (minus the early, incorrect return) would be more desirable - it would be more lines of code, but without the repeated `now()` calls with their performance and conceptual complexity cost. (If we were merely recomputing some pure value, I might feel differently, but `now()` is an OS call.)

File: stl/inc/condition_variable (hunk 7 above)
Comment (StephanTLavavej) [reply stl/inc/condition_variable:88]: A separate PR seems best; that way if we ever need to port, modify, or revert the bugfix, we don't have to worry about the test machinery enhancement getting tangled up with it.

File: stl/inc/condition_variable (hunk 8 above)
Comment (bhardwajs) [reply stl/inc/condition_variable:73]: Sounds good. Let me send a new iteration. Most likely later in the week or weekend.

**Comment by bhardwajs** [comment]
@StephanTLavavej @BillyONeal @CaseyCarter @cbezault This PR was failing build because of a spurious issue. I just merged master and pushed again and build is passing. I think it's ready for review and possibly, merging.

File: stl/inc/condition_variable [hunk 10]
```diff
@@ -90,31 +92,42 @@ public:
     template <class _Lock, class _Rep, class _Period, class _Predicate>
     bool wait_for(_Lock& _Lck, const chrono::duration<_Rep, _Period>& _Rel_time, _Predicate _Pred) {
         // wait for signal with timeout and check predicate
-        return _Wait_until1(_Lck, chrono::steady_clock::now() + _Rel_time, _Pred);
+        while (!_Pred()) {
+            if (wait_for(_Lck, _Rel_time) == cv_status::timeout) {
```
Comment (StephanTLavavej) [inline stl/inc/condition_variable:96]: This is incorrect. WG21-N4861 32.6.4.1 [[thread.condvarany.wait]/19](https://eel.is/c++draft/thread.condvarany.wait#19) says:

> *Effects:* Equivalent to:
> ```cpp
> return wait_until(lock, chrono::steady_clock::now() + rel_time, std::move(pred));
> ```

That translates relative time to absolute time, exactly once.

Your code can repeatedly call `wait_for(_Lck, _Rel_time)`. If the user originally asked "wait for 5 minutes", and this waits for 4 minutes before being spuriously woken up, it will wait another 5 minutes, which isn't what the user asked for.

File: stl/inc/condition_variable [hunk 11]
```diff
@@ -156,43 +174,19 @@ private:
         return reinterpret_cast<_Cnd_t>(&_Cnd_storage);
     }
 
+    template <class _Lock>
+    void _Unlock_relock(_Lock& _Lck) noexcept /* terminates */ {
+        _Lck.unlock(); // could throw
+        _Lck.lock();
```
Comment (StephanTLavavej) [inline stl/inc/condition_variable:180]: According to WG21-N4861 32.5.3.2 [[thread.mutex.requirements.mutex]/26](https://eel.is/c++draft/thread.mutex.requirements.mutex#26), `unlock()` can't throw, but `lock()` can throw ([/12](https://eel.is/c++draft/thread.mutex.requirements.mutex#12)).

File: stl/inc/condition_variable [hunk 12]
```diff
@@ -90,46 +111,47 @@ public:
...
-    template <class _Lock, class _Clock, class _Duration>
-    cv_status wait_until(_Lock& _Lck, const chrono::time_point<_Clock, _Duration>& _Abs_time) {
-        // wait until time point
-        for (;;) {
-            const auto _Now = _Clock::now();
-            if (_Abs_time <= _Now) {
-                return cv_status::timeout;
-            }
+    template <class _Lock>
+    [[deprecated("This extension is deprecated and WILL BE REMOVED.")]] cv_status wait_until(
```
Comment (CaseyCarter) [inline stl/inc/condition_variable:118]: Let's pull these `xtime` deprecations for now and come back with something more comprehensive. (And on 124.)

File: stl/inc/condition_variable [hunk 13]
```diff
@@ -40,48 +39,68 @@ public:
     condition_variable_any& operator=(const condition_variable_any&) = delete;
 
     void notify_one() noexcept { // wake up one waiter
-        lock_guard<mutex> _Lck(*_Myptr);
-        _Check_C_return(_Cnd_signal(_Mycnd()));
+        const shared_ptr<mutex> _Ptr = _Myptr; // for immunity to *this destruction
```
Comment (CaseyCarter) [inline stl/inc/condition_variable:42]: In the interest of getting this PR applied, let's pull this alleged race fix out into a separate PR. (And on 48.)

Comment (CaseyCarter) [reply stl/inc/condition_variable]: This is #883.

**Comment by CaseyCarter** [comment]
Thanks for the bugfix!
