### PR TITLE
<complex> Implement p0415r1

### LINKED ISSUE #16: P0415R1 constexpr For <complex> (Again)
[P0415R1](https://wg21.link/P0415R1) `constexpr` For `<complex>` (Again)

Feature-test macro after LWG-3349 was accepted:
`#define __cpp_lib_constexpr_complex 201711L`

As @Neargye observed below, due to the NaN interactions, this depends on #22 WG21-P0476 `<bit>` `bit_cast`.

### LINKED ISSUE #190: <complex>: real(T) and imag(T) setters should return void
The return types of our `complex` setters are incorrect, compared with https://eel.is/c++draft/complex :

https://github.com/microsoft/STL/blob/957fe99f41748b80c3108447e5dd5ce2be962f4e/stl/inc/complex#L534-L540

This is technically a bug, but no user has noticed it. I could devise situations where this would affect conformant code, beyond just `decltype`.

We'll need to change these functions while implementing #16, so we may as well fix their return types while we're in the neighborhood. This is unlikely to be a significant source breaking change.

(Standardese citations as of WG21-N4835.)

### PR DESCRIPTION
**Pull request by Neargye**
# Description

This is an in progress implementation of constexpr `<complex>`.
Will resolve issue #16, #190.

# Checklist

- [x] Fix #190
- [x] Fix #16

Be sure you've read README.md and understand the scope of this repo.

If you're unsure about a box, leave it unchecked. A maintainer will help you.

- [x] Identifiers in product code changes are properly `_Ugly` as per
  https://eel.is/c++draft/lex.name#3.1 or there are no product code changes.
- [x] The STL builds successfully and all tests have passed (must be manually
  verified by an STL maintainer before automated testing is enabled on GitHub,
  leave this unchecked for initial submission).
- [x] These changes introduce no known ABI breaks (adding members, renaming
  members, adding virtual functions, changing whether a type is an aggregate
  or trivially copyable, etc.).
- [x] These changes were written from scratch using only this repository,
  the C++ Working Draft (including any cited standards), other WG21 papers
  (excluding reference implementations outside of proposed standard wording),
  and LWG issues as reference material. If they were derived from a project
  that's already listed in NOTICE.txt, that's fine, but please mention it.
  If they were derived from any other project (including Boost and libc++,
  which are not yet listed in NOTICE.txt), you *must* mention it here,
  so we can determine whether the license is compatible and what else needs
  to be done.

### CODE REVIEW

File: stl/inc/complex [hunk 1]
```diff
@@ -531,12 +531,12 @@ public:
 
     constexpr _Complex_base(const _Ty& _Realval, const _Ty& _Imagval) : _Valbase{{_Realval, _Imagval}} {}
 
-    _Ty real(const _Ty& _Right) { // set real component
```
Comment (miscco) [inline stl/inc/complex]: I believe you need to preserve backwards compatability here. So this should be guarded by an `#ifdef _HAS_CXX20`

File: stl/inc/yvals_core.h [hunk 2]
```diff
@@ -993,6 +1000,8 @@
 #define __cpp_lib_to_array                201907L
 #define __cpp_lib_type_identity           201806L
 #define __cpp_lib_unwrap_ref              201811L
+
+#define __cpp_lib_constexpr_complex 201711L
```
Comment (miscco) [inline stl/inc/yvals_core.h]: The feature test macros are sorted lexicographically . So this should be further up

File: stl/inc/complex (hunk 1 above)
Comment (Neargye) [reply stl/inc/complex]: It's not c++20 changes, see https://github.com/microsoft/STL/issues/190.

File: stl/inc/yvals_core.h (hunk 2 above)
Comment (Neargye) [reply stl/inc/yvals_core.h]: Ok, thanks, will fix this.

File: stl/inc/complex (hunk 1 above)
Comment (CaseyCarter) [reply stl/inc/complex]: These two functions were added in C++11 with return type `void`, so this is correct.

File: stl/inc/yvals_core.h [hunk 3]
```diff
@@ -130,6 +130,7 @@
 // P0318R1 unwrap_reference, unwrap_ref_decay
 // P0325R4 to_array()
 // P0356R5 bind_front()
+// P0415R1 Constexpr for std::complex
```
Comment (StephanTLavavej) [inline stl/inc/yvals_core.h]: Nitpick: This should be cited as `P0415R1 constexpr For <complex> (Again)`, copying #16's title exactly. (I clean up paper titles to have consistent capitalization and make them more systematic.)

File: stl/inc/complex [hunk 4]
```diff
@@ -635,46 +635,45 @@ public:
         : _Complex_base<float, _Fcomplex_value>(
             static_cast<float>(_Right._Val[_RE]), static_cast<float>(_Right._Val[_IM])) {}
 
-    complex<_Ty>& operator=(const _Ty& _Right) {
-
+    _CONSTEXPR20 complex<_Ty>& operator=(const _Ty& _Right) {
```
Comment (StephanTLavavej) [inline stl/inc/complex]: Pre-existing: This should use the injected-class-name and return `complex&` to be consistent with the compound assignment operators below. I'll comment the two identical occurrences in the other specializations.

File: stl/inc/complex [hunk 5]
```diff
@@ -735,46 +734,45 @@ public:
         : _Complex_base<double, _Dcomplex_value>(
             static_cast<double>(_Right._Val[_RE]), static_cast<double>(_Right._Val[_IM])) {}
 
-    complex<_Ty>& operator=(const _Ty& _Right) {
-
+    _CONSTEXPR20 complex<_Ty>& operator=(const _Ty& _Right) {
```
Comment (StephanTLavavej) [inline stl/inc/complex]: Ditto `complex&` here.

File: stl/inc/complex [hunk 6]
```diff
@@ -831,46 +829,45 @@ public:
     constexpr complex(const _Lcomplex_value& _Right)
         : _Complex_base<long double, _Lcomplex_value>(_Right._Val[_RE], _Right._Val[_IM]) {}
 
-    complex<_Ty>& operator=(const _Ty& _Right) {
-
+    _CONSTEXPR20 complex<_Ty>& operator=(const _Ty& _Right) {
```
Comment (StephanTLavavej) [inline stl/inc/complex]: Ditto `complex&` here.

**Comment by Neargye** [comment]
@StephanTLavavej
1. About `_Div` - mark `_Ctraits` some fun constexpr, which call numeric_limits:
* _Nanv()
* _Infv()
* _Flt_eps()
* _Flt_max()

2. About "additional overloads"  generaded as:
```
_GENERIC_MATHC0X(arg, 0)
_GENERIC_MATHC0X(imag, 0)
_GENERIC_MATHC1X(real, _Left)

_GENERIC_MATHC1X(norm, (_Left * _Left))

_GENERIC_MATHC1X(conj, _Left)
_GENERIC_MATHC1X(proj, _Left)
```
arg and proj not marked constexpr by p0415r1. So we need to make two macros to generate?

**Comment by Neargye** [comment]
Maybe I should break it down into a few pr?

**Comment by StephanTLavavej** [comment]
> Maybe I should break it down into a few pr?
> Or it's ok one big pr to update `<complex>`?

It's a judgement call. We prefer feature PRs to be complete, i.e. not requiring additional PRs to complete the feature. (We make exceptions in rare cases, e.g. charconv, spaceship, and ranges.) We also prefer bugfixes to be complete, but incremental changes can be okay as long as each step is a strict improvement. Separating PRs is useful when changes are large and not intertwined (especially when one of the changes is mechanical or nearly so). It's usually okay to have a large change bundled with a few small improvements "while you're in the neighborhood", though. And sometimes it's just difficult to avoid bundling large, interconnected changes together.

One final reason to prefer splitting PRs when possible is that it makes the commit history more comprehensible, even if your reviewers have a high tolerance for larger PRs (as I do, having reviewed truly massive changes over the last decade).

In this case, I believe that fixing #325 isn't strongly related to constexprization (and WG21-P0415 doesn't change `pow()` as far as I see), so I'd prefer to see separate PRs. But if they're related for some reason, then a single PR is fine.

**Comment by Neargye** [comment]
@StephanTLavavej 
For fix #325 creat new pr #358 

For this pr, everything is done, except `operator/` because block by  #22.

**Comment by StephanTLavavej** [comment]
`bit_cast` is now available.

**Comment by Neargye** [comment]
* Rebase pr to master
* constexpr operator/

**Comment by Neargye** [comment]
Apparently I need a little more time.
After the update to vs2019  16.5 preview 5, build  STL is broken, and I can't test locally.

**Comment by cbezault** [comment]
Hmmm, what is failing for you? I can build with no problems.

**Comment by StephanTLavavej** [comment]
We broke your build! 🙀 The recent `bit_cast` checkin unconditionally attempted to use the compiler builtin (for non-EDG compilers), but that isn't available in the public Preview you're using.

This may be resolved by the upcoming release of VS 2019 16.6 Preview 1. We could push a change to guard `bit_cast` before then, but then you wouldn't be able to use it in `<complex>` unconditionally.

**Comment by cbezault** [comment]
I've enabled the libcxx tests that are supposed to check this feature.

File: stl/inc/complex [hunk 7]
```diff
@@ -175,12 +186,12 @@ class _Ctraits<long double> {
...
-    static _Ty _Flt_eps() { // get epsilon
-        return LDBL_EPSILON;
+    static constexpr _Ty _Flt_eps() { // get epsilon
+        return numeric_limits<long double>::epsilon();
     }
 
-    static _Ty _Flt_max() {
-        return LDBL_MAX;
+    static constexpr _Ty _Flt_max() {
+        return (numeric_limits<long double>::max)();
```
[the remark this answers is not in the document]
Comment (Neargye) [reply stl/inc/complex]: To fix `warning C4003: not enough actual parameters for macro 'max'`

[the remark this answers is not in the document]
Comment (cbezault) [reply stl/inc/complex]: Okay, makes sense, that's too bad.

File: stl/inc/complex [hunk 8]
```diff
@@ -76,22 +81,28 @@ public:
         return _Ans;
     }
 
-    static _Ty _Infv() { // return infinity
-        return numeric_limits<_Ty>::infinity();
+    static constexpr _Ty _Infv() { // return infinity
+        return numeric_limits<double>::infinity();
```
[the remark this answers is not in the document]
Comment (Neargye) [reply stl/inc/complex:85]: Fix

File: stl/inc/complex [hunk 9]
```diff
@@ -76,22 +81,28 @@ public:
...
     }
 
-    static bool _Isnan(_Ty _Left) {
+    static _CONSTEXPR20 bool _Isnan(_Ty _Left) {
         double _Tmp = static_cast<double>(_Left);
-        return _CSTD _Dtest(&_Tmp) == _NANCODE;
+#if defined(__cpp_lib_is_constant_evaluated) && defined(__cpp_lib_bit_cast)
+        if (_STD is_constant_evaluated()) {
+            uint64_t _Uint = _STD bit_cast<uint64_t>(_Tmp);
+            return ((_Uint >> 32) & 0x7fffffffU) + (_Uint != 0U) > 0x7ff00000U;
```
[the remark this answers is not in the document]
Comment (Neargye) [reply stl/inc/complex:98]: Thanks, I think `return (_Uint & 0x7fffffffffffffffU) > 0x7ff0000000000000U;` will be good

File: stl/inc/complex [hunk 10]
```diff
@@ -76,22 +81,28 @@ public:
...
+        } else
+#endif // __cpp_lib_is_constant_evaluated && __cpp_lib_bit_cast
+            return _CSTD _Dtest(&_Tmp) == _NANCODE;
     }
 
-    static _Ty _Nanv() { // return NaN
-        return numeric_limits<_Ty>::quiet_NaN();
+    static constexpr _Ty _Nanv() { // return NaN
+        return numeric_limits<double>::quiet_NaN();
```
[the remark this answers is not in the document]
Comment (Neargye) [reply stl/inc/complex:105]: Fix

File: stl/inc/complex [hunk 11]
```diff
@@ -76,22 +81,28 @@ public:
...
-    static bool _Isnan(_Ty _Left) {
+    static _CONSTEXPR20 bool _Isnan(_Ty _Left) {
         double _Tmp = static_cast<double>(_Left);
-        return _CSTD _Dtest(&_Tmp) == _NANCODE;
+#if defined(__cpp_lib_is_constant_evaluated) && defined(__cpp_lib_bit_cast)
+        if (_STD is_constant_evaluated()) {
+            uint64_t _Uint = _STD bit_cast<uint64_t>(_Tmp);
+            return ((_Uint >> 32) & 0x7fffffffU) + (_Uint != 0U) > 0x7ff00000U;
+        } else
+#endif // __cpp_lib_is_constant_evaluated && __cpp_lib_bit_cast
```
[the remark this answers is not in the document]
Comment (Neargye) [reply stl/inc/complex:100]: @StephanTLavavej is it ok?

**Comment by cbezault** [comment]
The last thing I might ask for is that you add a test to the `std` testsuite which tests the correctness of the constexpr `isnan` implementation. `libcxx` already has tests for simply checking that the functions are constexpr.

I'd probably defer to @StephanTLavavej as to whether or not that is necessary though.

File: stl/inc/complex (hunk 11 above)
[the remark this answers is not in the document]
Comment (cbezault) [reply stl/inc/complex:100]: Let's resolve this. I think it's fine.

**Comment by StephanTLavavej** [comment]
I'm reviewing this now - I've pushed a merge with master, a feature-test macro test update, and `bit_cast` changes. Microsoft-internal tests are passing. I still need to actually review `<complex>` and write some basic testing. Should be ready for checkin next week. Thanks for your patience while we clear out the PR backlog! 😸

File: stl/inc/complex [hunk 12]
```diff
@@ -76,21 +77,23 @@ public:
...
-        return _CSTD _Dtest(&_Tmp) == _INFCODE;
+        const auto _Tmp  = static_cast<double>(_Left);
+        const auto _Uint = _Bit_cast<uint64_t>(_Tmp);
+        return (_Uint & 0x7fffffffffffffffU) == 0x7ff0000000000000U;
     }
 
-    static bool _Isnan(_Ty _Left) {
-        double _Tmp = static_cast<double>(_Left);
-        return _CSTD _Dtest(&_Tmp) == _NANCODE;
+    static _CONSTEXPR20 bool _Isnan(_Ty _Left) {
```
Comment (CaseyCarter) [inline stl/inc/complex:90]: `_CONSTEXPR20` on internal machinery is unusual - does this deserve a comment? (And 206 and 321.)

Comment (StephanTLavavej) [reply stl/inc/complex:90]: We could actually mark it as `constexpr`, assuming CUDA won't complain that the workaround `_Bit_cast` is never `constexpr` for it. Thoughts?

**Comment by StephanTLavavej** [comment]
I am writing test coverage at this very moment.

File: stl/inc/complex (hunk 12 above)
Comment (CaseyCarter) [reply stl/inc/complex:90]: I'd rather not rely on IFNDR when it's easily avoided like this. (I'd rather have `_CONSTEXPR20` with no comment than `constexpr` with no comment.) Admittedly, it's taking longer to devise a reasonable comment than it did to see why this is `_CONSTEXPR20` instead of `constexpr` in the first place, so it wouldn't be the end of the world to have no comment.

Comment (StephanTLavavej) [reply stl/inc/complex:90]: I think we should leave it as-is then.

**Comment by StephanTLavavej** [comment]
Thanks for implementing this feature - we're one step closer to C++20 completeness! 😸🎉

(Along this way, this uncovered a bug in the compiler's support for modules, which our FE dev Cameron DaCamara has already fixed!)
