### PR TITLE
`<deque>`: Fix single-element insertion of `deque`

### LINKED ISSUE #1023: <deque>: std::deque::insert performance
**Describe the bug**
The DevCom-216960 reporter suggested that inserting to the middle of `deque` can be accomplished by inserting a `move`'d new first/last element to begin/end, and then `move`ing elements further, and finally emplacing the destination element to `move`'d-out place.

It is faster than using `rotate`. 
It is still O(N), but it is expected to execute faster.

Reporter's code uses `std::move` by default, but for _string-like_ classes it uses `swap`.

**Reporter's code sample**
```
#define ZForward(T, v) static_cast<decltype(std::forward<T>(v))>(v)
#define ZMove(v) ((decltype(std::move(v))) (v))


template<typename T>
struct is_string_like
{
	enum { value = false };
};


template<class _Elem, class _Traits, class _Alloc>
struct is_string_like<std::basic_string<_Elem, _Traits, _Alloc>>
{
	enum { value = true };
};


template<typename Deque, typename... T>
auto deque_insert(Deque& d, typename Deque::iterator itr, T&&... args)
{
	auto begin = d.begin();
	typename Deque::size_type _Off = itr - begin;
	auto size = d.size();
	if (_Off < size / 2)
	{
		if (_Off == 0)
			d.emplace_front(ZForward(T, args)...);
		else
		{
			d.emplace_front(ZMove(*begin));
			begin = d.begin();
			typename Deque::iterator itrFrom = begin + 1;
			typename Deque::pointer pFrom = NULL, pWrite = &*itrFrom, pFinal = &begin[_Off];
			for (; pWrite != pFinal;)
			{
				pFrom = &*++itrFrom;
#if _HAS_CXX17
				if constexpr(sizeof(char[is_string_like<Deque::value_type>::value+1])==2)
					pWrite->swap(*pFrom);
				else
#endif
					*pWrite = ZMove(*pFrom);
				count_1++;
				pWrite = pFrom;
			}
			*pWrite = Deque::value_type{ ZForward(T, args)... };
		}
	}
	else
	{
		if (_Off == size)
			d.emplace_back(ZForward(T, args)...);
		else
		{
			d.emplace_back(ZMove(d.back()));
			begin = d.begin();
			typename Deque::iterator itrFrom = d.end() - 2;
			typename Deque::pointer pFrom = NULL, pWrite = &*itrFrom, pFinal = &begin[_Off];
			for (; pWrite != pFinal;)
			{
				pFrom = &*--itrFrom;
#if _HAS_CXX17
				if constexpr(sizeof(char[is_string_like<Deque::value_type>::value + 1]) == 2)
					pWrite->swap(*pFrom);
				else
#endif
					*pWrite = ZMove(*pFrom);
				count_1++;
				pWrite = pFrom;
			}
			*pWrite = Deque::value_type{ ZForward(T, args)... };
		}
	}
	//return (d.begin() + _Off);
}
```

**Additional context**
This item was originally reprted on Developer Community as DevCom-216960 and is also tracked by Microsoft-internal VSO-586319 / [AB#586319](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/586319).

### PR DESCRIPTION
**Pull request by frederick-vs-ja**
As said in https://github.com/microsoft/STL/issues/1023#issuecomment-1713683463, it's non-conforming to use `rotate` which requires swappability.

~It seems to me that we should sometime use copy construction/assignment instead or moving, as done in `vector`.~ No, the requirements for `deque` are more relaxed.

Fixes #1023. Note that there'll be merge conflict with #4016.

### CODE REVIEW

File: tests/std/tests/Dev10_860421_deque_push_back_pop_front/test.cpp [hunk 1]
```diff
@@ -47,3 +46,190 @@ void test_391805() {
...
+    ThrowingMovable(ThrowingMovable&&) {
+        throw UniqueError{};
+    }
+    ThrowingMovable(const ThrowingMovable&) noexcept = default;
+
+    explicit ThrowingMovable(int n) noexcept : payload{n} {}
+
+    ThrowingMovable& operator=(ThrowingMovable&& other) {
+        throw UniqueError{};
+    }
```
Comment (StephanTLavavej) [inline tests/std/tests/Dev10_860421_deque_push_back_pop_front/test.cpp:160]: This is failing due to an unreferenced parameter warning. As a reminder, please always run any modified test directories.

**Review by StephanTLavavej — CHANGES_REQUESTED** [review]

File: tests/std/tests/Dev10_860421_deque_push_back_pop_front/test.cpp (hunk 1 above)
Comment (frederick-vs-ja) [reply tests/std/tests/Dev10_860421_deque_push_back_pop_front/test.cpp]: 😿I ran the modified test locally in a project but I forgot to compile it with the options for tests. I should do this in a more proper way, sorry.

File: stl/inc/deque [hunk 2]
```diff
@@ -871,13 +871,48 @@ public:
...
+        _Orphan_all();
+        if (_Off == 0) { // at the beginning
+            _Emplace_front_internal(_STD forward<_Valty>(_Val)...);
+        } else if (_Off <= _Mysize() / 2) { // closer to front, push to front then rotate
+            auto& _Al = _Getal();
+            _Alloc_temporary2<_Alty> _Obj(_Al, _STD forward<_Valty>(_Val)...); // handle aliasing
+
+            auto _Old_unwrapped_begin = _Unchecked_begin();
+            auto _Old_unwrapped_where = _Old_unwrapped_begin + static_cast<difference_type>(_Off);
+
```
Comment (achabense) [inline stl/inc/deque:886]: I think we'd better acquire the iterators after doing `_Emplace_front_internal`. Otherwise, this relies on that unchecked iterator will implementationaly not be invalidated by `_Emplace_front_internal`.

I find it very hard to reason about its safety. Unchecked iterators has an internal offset, which does not share the same meaning as `_Off` as in `deque[_Off]`. And `_Emplace_front_internal` calls `_Growmap` which can also mess with `_Myoff()` etc(which will be the internal offset for `begin()` (the usage of `off` is just too chaotic)... Even finally safe, I think this is a heavy reliance, as what's going on here is far from obvious.

File: stl/inc/deque [hunk 3]
```diff
@@ -871,13 +871,48 @@ public:
...
+            _Emplace_front_internal(_STD move_if_noexcept(*_Old_unwrapped_begin));
+            if constexpr (_Uses_move_assignment) {
+                _STD _Move_unchecked(_STD _Next_iter(_Old_unwrapped_begin), _Old_unwrapped_where, _Old_unwrapped_begin);
+                *_STD _Prev_iter(_Old_unwrapped_where) = _STD move(_Obj._Get_value());
+            } else {
+                _STD _Copy_unchecked(_STD _Next_iter(_Old_unwrapped_begin), _Old_unwrapped_where, _Old_unwrapped_begin);
+                *_STD _Prev_iter(_Old_unwrapped_where) = _STD as_const(_Obj._Get_value());
```
[the remark this answers is not in the document]
Comment (frederick-vs-ja) [reply stl/inc/deque:893]: > 1. It seems there is no need to provide strong-guarantee here. (I can just find [this](https://en.cppreference.com/w/cpp/container/deque/emplace#:~:text=other%20than%20by%20the%20copy%20constructor%2C%20move%20constructor%2C%20assignment%20operator%2C%20or%20move%20assignment%20operator%20of%20the%20value%20type), but have difficulty finding formal references in the standard :(

[[deque.modifiers]/3](https://eel.is/c++draft/deque.modifiers#3) is the source.

But I think you're right. When exception is thrown, we can't reliably restore the original state if any original element needs to be assigned. Maybe we should unconditionally use move construction/assignment.

I strongly feel that [deque.modifiers]/3 doesn't cover all cases...

[the remark this answers is not in the document]
Comment (frederick-vs-ja) [reply stl/inc/deque:893]: > 1. It seems there is no need to provide strong-guarantee here. (I can just find [this](https://en.cppreference.com/w/cpp/container/deque/emplace#:~:text=other%20than%20by%20the%20copy%20constructor%2C%20move%20constructor%2C%20assignment%20operator%2C%20or%20move%20assignment%20operator%20of%20the%20value%20type), but have difficulty finding formal references in the standard :(

[[deque.modifiers]/3](https://eel.is/c++draft/deque.modifiers#3) is the source. But I think you're right, perhaps we should always use move assignment.

I'm not sure whether `move_if_noexcept` can/should be used.

File: stl/inc/deque (hunk 2 above)
Comment (frederick-vs-ja) [reply stl/inc/deque:881]: In the future (may be near or in vNext), I think the iterator type used here should be changed to store a beginning `_Map` pointer and an offset in order to reduce indirection. Such an iterator can definitely be invalidated by `_Growmap`.

Comment (achabense) [reply stl/inc/deque:881]: I guess this will not work, as deque relies on ring buffer. An iterator needs 1.mapptr 2.offset to access element, but also needs 3.mapsize to correctly perform iterator arithmetic.

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I thought carefully about these cases, and I think we have sufficient test coverage, so we can merge this without a second maintainer approval. I believe that resolving the merge conflict in this batch should be simple but I'll see.

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Review by CaseyCarter — APPROVED** [review]

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I've pushed a merge with `main` to resolve the conflict with how #4016 moved code around. For `iterator emplace(const_iterator _Where, _Valty&&... _Val)`, I pasted #4022's implementation in the new location, as no other changes had been made. For `iterator insert(const_iterator _Where, const _Ty& _Val)`, both PRs made the exact same change, so I kept the new location.

**Comment by StephanTLavavej** [comment]
Thanks for fixing this bug in the STL's favorite and best container! :joy_cat: :lady_beetle: :white_check_mark:
