### PR TITLE
Toolset update: VS 2022 17.14 Preview 2, Clang 19.1.5

### LINKED ISSUE #5074: libcxx: Sporadic crash in `thread.thread.destr/dtor.pass.cpp`
#5073 encountered a sporadic crash in [`libcxx/test/std/thread/thread.threads/thread.thread.class/thread.thread.destr/dtor.pass.cpp`](https://github.com/llvm/llvm-project/blob/69ead949d08ff0bb8cbbf4f7143aaa6687830f6b/libcxx/test/std/thread/thread.threads/thread.thread.class/thread.thread.destr/dtor.pass.cpp).

[Test logs](https://dev.azure.com/vclibs/STL/_build/results?buildId=17863&view=results), x64:

```
Build steps:
Command: "C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.42.34430\bin\HostX64\x64\cl.EXE" "D:\a\_work\1\s\llvm-project\libcxx\test\std\thread\thread.threads\thread.thread.class\thread.thread.destr\dtor.pass.cpp" "-ID:\build\out\inc" "-ID:\a\_work\1\s\llvm-project\libcxx\test\support" "/nologo" "/Od" "/W4" "/w14061" "/w14242" "/w14265" "/w14582" "/w14583" "/w14587" "/w14588" "/w14749" "/w14841" "/w14842" "/w15038" "/w15214" "/w15215" "/w15216" "/w15217" "/w15262" "/sdl" "/WX" "/D_ENABLE_STL_INTERNAL_CHECK" "/bigobj" "/EHsc" "/MTd" "/std:c++latest" "/permissive-" "/utf-8" "/FImsvc_stdlib_force_include.h" "/wd4643" "/D_STL_CALL_ABORT_INSTEAD_OF_INVALID_PARAMETER" "/analyze:autolog-" "/Zc:preprocessor" "/wd6262" "-FeD:\build\tests\libcxx\std\thread\thread.threads\thread.thread.class\thread.thread.destr\Output\dtor.pass.cpp.dir\0\dtor.pass.exe" "-link" "-LIBPATH:D:\build\out\lib\amd64" "-LIBPATH:C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.42.34430\lib\x64" "/MANIFEST:EMBED"
Exit Code: 0 (0x0)
Standard Output:
--
dtor.pass.cpp
--

Intellisense response file steps:
Test setup steps:
Test steps:
Test step failed unexpectedly.
Command: "D:\build\tests\libcxx\std\thread\thread.threads\thread.thread.class\thread.thread.destr\Output\dtor.pass.cpp.dir\0\dtor.pass.exe"
Exit Code: 3221225477 (0xC0000005)
```

### LINKED ISSUE #5282: CUDA's installer hangs for VS 2022 17.13 and later
Known issue: https://forums.developer.nvidia.com/t/stuck-installing-nsight-on-cuda-12-8-0-571-96-windows/323732/2

I encountered this when updating the toolset (from Preview 2) to VS 2022 17.13 Preview 3 in #5247 but didn't understand the cause then.

Unfortunately, my "solution" of installing just 'nvcc_12.4' didn't work, but I didn't realize it. `nvcc` was no longer being found on the path, causing the test harness to skip `GH_000639_nvcc_include_all`, and I didn't think to look for this.

I can't figure out how `nvcc` is normally added to the developer command prompt path (i.e. if there's a particular subpackage that will do it, or only the full installation). As a workaround, I'm going to try to manually add it to the path. I also need to install the CUDA runtime libraries.

This is a tracking issue to remember what's going on here. I'm not sure if this will be fixed on the CUDA side or the VS side. Either way, my workaround should be removed at that time, and if CUDA is the one that's fixed, we should strongly consider increasing our minimum required CUDA version.

### PR DESCRIPTION
**Pull request by StephanTLavavej**
Resolves #5074. Resolves #5282. Resolves DevCom-10863472 VSO-2411436.

# :scroll: Changelog
- Fixed bugs:
  * Fixed compiler errors when using `<format>` in a CUDA project, by adding a compiler bug workaround.
- Code cleanups:
  * Removed compiler bug workarounds.
- Infrastructure improvements:
  * Updated dependencies.
    + Updated build compiler to VS 2022 17.14 Preview 2 (now required).
    + Updated Clang to 19.1.5.

# :gear: Commits

* Node.js 23.9.0.
  + Increasing our minimum required Node version for the Status Chart isn't necessary at this time, but I like to keep this updated on a semi-regular basis.
* Require VS 2022 17.14.
  + The MSVC-internal toolset has *finally* been updated, allowing us to require 17.14.
* Remove workaround for CUDA 9.2's lack of `if constexpr`.
  + I added this workaround in #772, merged 2020-05-01. We began using `if constexpr` unconditionally (requiring CUDA 10.1 Update 2) in #1544, merged 2021-01-05. This workaround could have been removed then. At least I noticed this 4 years later! I'm going back to always calling `_Integral_to_string()`, now enhanced with `if constexpr`.
* Remove workaround for VSO-612785 "'expect_error' assertion when testing a constexpr 'hidden friend'".
  + This was fixed for VS by EDG 5.0 on 2018-12-15. In #759 merged on 2020-04-30, I had to preserve the workaround because it was still needed for CUDA 9.2 (released 2018-05). Fortunately I commented it, although very poorly. It's been 5 years and we now require CUDA 12.4 (released 2024-03), so we can remove this workaround.
* Remove workaround for VSO-1132704 "Bogus C3615 when implicitly-constexpr defaulted SMF calls non-trivial SMF in base class".
* Remove workaround for VSO-1284799 "constexpr ICE: binding a reference to a temporary emits Assertion failed: Nerrors > 0".
* Remove workaround for VSO-1664293 "/clr C++20 chk assertion failed: rhs.is_lvalue() in constexpr.cpp" in `Dev11_0535636_functional_overhaul`.
  + Update citation to VSO-2417635 "/clr C++20 chk assertion failed: rhs.is_lvalue() in constexpr.cpp, again" in `P0466R5_layout_compatibility_and_pointer_interconvertibility_traits`.
* Remove workaround for VSO-2343282 "C1XX assertion 'If lookup found RDSymbol before it should find something this time, too' affecting STL atomic_ref test".
* Remove workaround now that the internal toolset supports static call operators.
* Remove workaround for DevCom-10841757 (CUDA's installer hangs for VS 2022 17.13 and later).
  + Goodbye #5282!
  + :white_check_mark: Verified that all 6 configurations of `GH_000639_nvcc_include_all` are passing instead of being skipped.
* Skip a sporadic libcxx failure.
  + Goodbye #5074!
* Work around VSO-2253317 "ICE when calling std::to_underlying()".
  + This is a very obscure bug that I encountered while modernizing the MSVC codebase to C++23. (It involves multiplying a `float` by the result of `to_underlying()`.) As a compiler fix hasn't arrived in a timely manner, temporarily removing our "MSVC intrinsic" annotation is easy.
* create-1es-hosted-pool.ps1: Opt-in early to disable default outbound access, [before it's retired on 2025-09-30](https://learn.microsoft.com/en-us/azure/virtual-network/ip-services/default-outbound-access).
  + I verified that this takes effect (i.e. with no other changes, this prevents outbound Internet access, so the script can't download anything and totally fails).
* create-1es-hosted-pool.ps1: Create a NAT gateway.
  + This is the most preferred method for explicit outbound connectivity, [according to Azure docs](https://learn.microsoft.com/en-us/azure/load-balancer/load-balancer-outbound-connections#scenarios).
* create-1es-hosted-pool.ps1: Consistently indent wrapped options.
* create-1es-hosted-pool.ps1: Add more progress bar messages.
* New pool.
* VS 2022 17.14 Preview 2.
* Add workaround to fix DevCom-10863472 VSO-2411436 "CUDA (12.8) host code compilation fails with std::format and VS2022".
  + And add test coverage, verified in a VM.
* Remove CUDA workaround for `__has_cpp_attribute(msvc::x)`.
  + This was added by #772, merged 2020-05-01, for CUDA 9.2 (released May 2018). I don't observe this warning with CUDA 12.4 (released March 2024).
* Remove workarounds for CUDA/Intel, always use Standard `_Pragma`.
  + These were added by #1342, merged 2021-05-20, for VSO-1329304 "EDG doesn't understand Standard _Pragma". We immediately fixed that locally and reported it upstream to EDG. In that release, VS 2019 16.10, we had just begun requiring CUDA 10.1 Update 2 (released Aug 2019). We now require CUDA 12.4 (released March 2024), and I observe that it understands Standard `_Pragma` just fine.
  + I've verified that Intel accepts Standard `_Pragma` on Windows, see below.
* Remove all `__INTEL_COMPILER` workarounds.
  + Intel deprecated and removed their old compiler (icc), which we no longer attempt to avoid breaking in any way. (See DevCom-10200300.)
  + Their new compiler (icx) is LLVM-based and doesn't define `__INTEL_COMPILER` anymore, so all of our accumulated workarounds don't affect it and can be removed. Instead, icx uses `__INTEL_LLVM_COMPILER` to specifically distinguish itself. It also identifies itself as a `__clang__`, activating all of our Clang codepaths. For example, it accepts Clang-style diagnostic pragmas. See icx usage example below.
  + We still don't officially support or test icx. However, following our unofficial policy of avoiding *gratuitous* breakage should be easier now. (We were treating it as a Clang without realizing it, and it worked!)
* Clarify comment: "TRANSITION, fixed in CUDA 12.5"
  + Added by #4974.
* Add `retryCountOnTaskFailure: 4` to checkout-self.yml.
  + See: https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/steps-checkout?view=azure-pipelines
  + This matches what we do in checkout-submodule.yml: https://github.com/microsoft/STL/blob/0d8f517ae3828284fed594741b847db940167a59/azure-devops/checkout-submodule.yml#L12-L15
  + Retrying *tests* is an abomination. However, it's fine to retry checkouts, to be resilient to network gremlins.
* Clang 19.1.5.
  + VS performed a minor version update. It doesn't affect clang-format output, or any of our product/test code, but we should still update our expected clang-format version to avoid emitting warnings during CMake configuration.

:white_check_mark: [STL-ASan-CI passed.](https://dev.azure.com/vclibs/STL/_build/results?buildId=18317&view=results)

# :computer: icx Usage Example

```
C:\Temp>type meow.cpp
```
```cpp
#include <cstdio>
#include <vector>

[[deprecated]] int square(int x) { return x * x; }

int main() {
#ifdef __INTEL_COMPILER
    std::puts("__INTEL_COMPILER is defined.");
#else
    std::puts("__INTEL_COMPILER is NOT defined!");
#endif

#ifdef __INTEL_LLVM_COMPILER
    std::puts("__INTEL_LLVM_COMPILER is defined.");
#endif

#ifdef __clang__
    std::puts("__clang__ is defined.");
#endif

#ifdef SILENCE_DEPRECATED_WARNING
    _Pragma("clang diagnostic push")
    _Pragma("clang diagnostic ignored \"-Wdeprecated-declarations\"")
    return square(0);
    _Pragma("clang diagnostic pop")
#else
    return square(0);
#endif
}
```
```
C:\Temp>icx --version
Intel(R) oneAPI DPC++/C++ Compiler for applications running on Intel(R) 64, Version 2025.0.4 Build 20241205
Copyright (C) 1985-2024 Intel Corporation. All rights reserved.

Intel(R) oneAPI DPC++/C++ Compiler 2025.0.4 (2025.0.4.20241205)
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files (x86)\Intel\oneAPI\compiler\2025.0\bin\compiler
Configuration file: C:\Program Files (x86)\Intel\oneAPI\compiler\2025.0\bin\compiler\..\icx.cfg

C:\Temp>icx /EHsc /nologo /W4 /DSILENCE_DEPRECATED_WARNING meow.cpp && meow
__INTEL_COMPILER is NOT defined!
__INTEL_LLVM_COMPILER is defined.
__clang__ is defined.

C:\Temp>icx /EHsc /nologo /W4 meow.cpp
C:\Temp\meow.cpp(27,12): warning: 'square' is deprecated [-Wdeprecated-declarations]
27 |     return square(0);
    |            ^
C:\Temp\meow.cpp(4,3): note: 'square' has been explicitly marked deprecated here
    4 | [[deprecated]] int square(int x) { return x * x; }
    |   ^
1 warning generated.
```

### CODE REVIEW

**Comment by StephanTLavavej** [comment]
I'm *speculatively* mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

File: tests/std/tests/P0896R4_views_take/test.cpp [hunk 1]
```diff
@@ -561,22 +561,17 @@ constexpr void move_only_test() {
...
-        static_assert(same_as<decltype(views::take(R{some_writable_ints}, 99999)), ranges::take_view<R>>);
+    using R = test::range<output_iterator_tag, int, test::Sized::no, test::CanDifference::no, test::Common::no,
+        test::CanCompare::no, test::ProxyRef::yes, test::CanView::yes, test::Copyability::move_only>;
+    int some_writable_ints[] = {0, 1, 2, 3};
+    static_assert(same_as<decltype(views::take(R{some_writable_ints}, 99999)), ranges::take_view<R>>);
 
-        // How do I implement "Fill up to n elements in {output range} with {value}"?
-        ranges::fill(R{some_writable_ints} | views::take(99999), 42);
-        assert(ranges::equal(some_writable_ints, initializer_list<int>{42, 42, 42, 42}));
+    // How do I implement "Fill up to n elements in {output range} with {value}"?
```
Comment (davidmrdavid) [inline tests/std/tests/P0896R4_views_take/test.cpp:569]: out of scope - what's the context behind this comment? Isn't the line below doing precisely this (filling up to `99999` elements with `42`)?

File: stl/inc/yvals_core.h [hunk 2]
```diff
@@ -526,14 +526,7 @@
...
 
-// Note that _STL_PRAGMA is load-bearing;
-// it still needs to exist even once CUDA and ICC support _Pragma.
-#if defined(__CUDACC__) || defined(__INTEL_COMPILER)
-#define _STL_PRAGMA(PRAGMA) __pragma(PRAGMA)
-#else
-#define _STL_PRAGMA(PRAGMA) _Pragma(#PRAGMA)
-#endif
-
+#define _STL_PRAGMA(PRAGMA)          _Pragma(#PRAGMA)
```
Comment (davidmrdavid) [inline stl/inc/yvals_core.h:529]: nit - why the large spacing? Shouldn't it be:

```suggestion
#define _STL_PRAGMA(PRAGMA) _Pragma(#PRAGMA)
```

**Review by davidmrdavid — APPROVED** [review]
Thanks :star:!

No blockers, just two questions:

File: tests/std/tests/P0896R4_views_take/test.cpp (hunk 1 above)
Comment (StephanTLavavej) [reply tests/std/tests/P0896R4_views_take/test.cpp:569]: I'm not sure - this goes back to the original PR #1253 on 2020-09-04. I think it's a rhetorical question, to be immediately answered by the code below, but it's not our usual style.

File: stl/inc/yvals_core.h (hunk 2 above)
Comment (StephanTLavavej) [reply stl/inc/yvals_core.h:529]: This is the effect of [`AlignConsecutiveMacros: Consecutive`](https://releases.llvm.org/19.1.0/tools/clang/docs/ClangFormatStyleOptions.html#alignconsecutivemacros):

https://github.com/microsoft/STL/blob/0d8f517ae3828284fed594741b847db940167a59/.clang-format#L53
