### PR TITLE
`<string>`: Fix handling for `char_traits<unicorn>`

### LINKED ISSUE #4930: `<string>`: `basic_string<unicorn>::find_meow_of` family with `std::char_traits<unicorn>` specialization are not supported
# Describe the bug

Discovered when trying to make follow up optimizations after #4744 

`basic_string` with odd types and `char_traits` specialization in `std::` can exist.
From [[namespace.std]/2](https://eel.is/c++draft/namespace.std#2) :
> Unless explicitly prohibited, a program may add a template specialization for any standard library class template to namespace `std` provided that
> - the added declaration depends on at least one program-defined type, and
> - the specialization meets the standard library requirements for the original template

However with `std::char_traits<unicorn>` specialization provided, `basic_string<unicorn>::find_first_of` fails to compile here:
https://github.com/microsoft/STL/blob/91e425587a0b9b5ac0d1005844c661fee2e2813b/stl/inc/__msvc_string_view.hpp#L678-L680

# Command-line test case
```
**********************************************************************
** Visual Studio 2022 Developer Command Prompt v17.12.0-pre.1.0
** Copyright (c) 2022 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'

C:\Program Files\Microsoft Visual Studio\2022\Preview>cd %temp%

C:\Users\ALEXG~1\AppData\Local\Temp>type repro.cpp
```
```c++
#include <cassert>
#include <string>

static constexpr unsigned char odd_mask = 0xF;

enum odd_char : unsigned char {};

namespace std {
    template <>
    class char_traits<odd_char> {
    public:
        using char_type  = odd_char;
        using int_type   = int;
        using off_type   = streamoff;
        using pos_type   = streampos;
        using state_type = mbstate_t;

        static bool eq(const char_type c, const char_type d) {
            return ((static_cast<unsigned char>(c) ^ static_cast<unsigned char>(d)) & odd_mask) == 0;
        }

        static bool lt(const char_type c, const char_type d) {
            return (static_cast<unsigned char>(c) & odd_mask) < (static_cast<unsigned char>(d) & odd_mask);
        }

        static int compare(const char_type* const c, const char_type* const d, const size_t n) {
            for (size_t i = 0; i != n; ++i) {
                int ci = static_cast<unsigned char>(c[i]) & odd_mask;
                int di = static_cast<unsigned char>(d[i]) & odd_mask;
                int r  = ci - di;
                if (r != 0) {
                    return r;
                }
            }

            return 0;
        }

        static size_t length(const char_type* const p) {
            const char_type* c = p;
            while (static_cast<unsigned char>(*c) != 0) {
                ++c;
            }

            return static_cast<size_t>(c - p);
        }

        static const char_type* find(const char_type* p, const size_t n, const char_type c) {
            for (size_t i = 0; i != n; ++i) {
                if (eq(p[i], c)) {
                    return p + i;
                }
            }

            return nullptr;
        }

        static char_type* move(char_type* s, const char_type* p, const size_t n) {
            memmove(s, p, n);
            return s;
        }

        static char_type* copy(char_type* s, const char_type* p, const size_t n) {
            memmove(s, p, n);
            return s;
        }

        static void assign(char_type& r, const char_type& d) {
            r = d;
        }
        static char_type* assign(char_type* const s, const std::size_t n, const char_type c) {
            memset(s, static_cast<unsigned char>(c), n);
            return s;
        }

        static bool not_eof(int) {
            return true;
        }

        static char_type to_char_type(const int_type i) {
            return char_type(static_cast<unsigned char>(i));
        }

        static int_type to_int_type(const char_type i) {
            return static_cast<unsigned char>(i);
        }

        static bool eq_int_type(const int_type c, const int_type d) {
            if (c == -1) {
                return d == -1;
            } else {
                return ((c ^ d) & odd_mask) == 0;
            }
        }

        static int_type eof() {
            return -1;
        }
    };
}; // namespace std

using odd_string = std::basic_string<odd_char>;

int main() {
    const odd_char s_init[] = {static_cast<odd_char>(0x55), static_cast<odd_char>(0x44), static_cast<odd_char>(0x33),
        static_cast<odd_char>(0x22), static_cast<odd_char>(0x11), static_cast<odd_char>(0)};
    odd_string s(s_init);

    assert(s.length() == 5);
    assert(s.find(static_cast<odd_char>(0x54)) == 1);
    assert(s.find(static_cast<odd_char>(0x26)) == s.npos);

    const odd_char s2_init[] = {static_cast<odd_char>(0x83), static_cast<odd_char>(0x12), static_cast<odd_char>(0)};
    odd_string s2(s2_init);

    assert(s.find_first_of(s2) == 2);
    assert(s2.find_first_of(s) == 0);

    assert(s.find_last_of(s2) == 3);
    assert(s2.find_last_of(s) == 1);

    return 0;
}
```
```
C:\Users\ALEXG~1\AppData\Local\Temp>cl /Od /MDd repro.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.42.34226.3 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

repro.cpp
C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.42.34226\include\__msvc_string_view.hpp(664): error C2338: static_assert failed: 'Standard char_traits is only provided for char, wchar_t, char16_t, and char32_t. See N4950 [char.traits]. Visual C++ accepts other unsigned integral types as an extension.'
C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.42.34226\include\__msvc_string_view.hpp(664): note: the template instantiation context (the oldest one first) is
repro.cpp(107): note: see reference to class template instantiation 'std::basic_string<odd_char,std::char_traits<odd_char>,std::allocator<odd_char>>' being compiled
C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.42.34226\include\xstring(2693): note: while compiling class template member function 'unsigned __int64 std::basic_string<odd_char,std::char_traits<odd_char>,std::allocator<odd_char>>::find_last_of(const std::basic_string<odd_char,std::char_traits<odd_char>,std::allocator<odd_char>> &,unsigned __int64) noexcept const'
repro.cpp(119): note: see the first reference to 'std::basic_string<odd_char,std::char_traits<odd_char>,std::allocator<odd_char>>::find_last_of' in 'main'
C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.42.34226\include\xstring(2695): note: see reference to function template instantiation 'size_t std::_Traits_find_last_of<_Traits,true>(const odd_char *const ,const size_t,const size_t,const odd_char *const ,const size_t) noexcept' being compiled
        with
        [
            _Traits=std::char_traits<odd_char>
        ]
C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.42.34226\include\__msvc_string_view.hpp(730): note: see reference to class template instantiation 'std::_String_bitmap<std::char_traits<odd_char>::char_type,false>' being compiled
```

# Expected behavior
Should compile

# STL version
Version 17.12.0 Preview 1.0

### PR DESCRIPTION
**Pull request by frederick-vs-ja**
Fixes #4930. Ideally, when `T` is an implementation-controlled type, special handling should be enabled for `char_traits<T>` to reject more unintended element types. But the complete work is impractical, so this PR restricts the handling to arithmetic types and `nullptr_t`.

Drive-by changes:
- Update the `static_assert` message to mention `char8_t`.
- Resolve `TRANSITION` comments in `<regex>`, but test coverage is currently missing (which would be complicated and weird).

### CODE REVIEW

File: stl/inc/__msvc_string_view.hpp [hunk 1]
```diff
@@ -702,7 +713,7 @@ class _String_bitmap<_Elem, false> { // _String_bitmap for wchar_t/unsigned shor
     bool _Matches[256] = {};
 };
 
-template <class _Traits, bool _Special = _Is_specialization_v<_Traits, char_traits>>
+template <class _Traits, bool _Special = _Is_implementation_handled_char_traits<_Traits>>
```
Comment (AlexGuteniev) [inline stl/inc/__msvc_string_view.hpp:716]: I observe that you have proposed to eliminate the template parameter.
However, as we still have tail call with a different value in some functions, we can't.
Perhaps this still should be done as a follow-up enhancement, after all vectorization, including `_not_` is done, and we have no tail calls.

File: stl/inc/regex [hunk 2]
```diff
@@ -193,19 +193,29 @@ struct _Char_traits_lt {
...
+// signed char and other unsigned integral types are supported as an extension.
+template <class _Ty>
+constexpr bool _Is_predefined_char_like_type = _Is_character<_Ty>::value || is_unsigned_v<_Ty>;
+
 // library-provided char_traits::eq behaves like equal_to<_Elem>
-// TRANSITION: This should not be activated for user-defined specializations of char_traits
 template <class _Elem>
 constexpr bool _Can_memcmp_elements_with_pred<_Elem, _Elem, _Char_traits_eq<char_traits<_Elem>>> =
-    _Can_memcmp_elements<_Elem, _Elem>;
+    _Is_predefined_char_like_type<_Elem> && _Can_memcmp_elements<_Elem, _Elem>;
```
Comment (AlexGuteniev) [inline stl/inc/regex:203]: Good catch! i thought the issue is limited to methods of `basic_string`/`basic_string_view` and `find_first_of` algorithm.

File: tests/std/tests/GH_004930_char_traits_user_specialization/test.cpp [hunk 3]
```diff
@@ -0,0 +1,210 @@
...
+        } else
+#endif // _HAS_CXX20
+        {
+            memset(s, static_cast<unsigned char>(c), n);
+        }
+        return s;
+    }
+
+    static constexpr bool not_eof(int) noexcept {
+        return true;
```
Comment (AlexGuteniev) [inline tests/std/tests/GH_004930_char_traits_user_specialization/test.cpp:136]: I recognize you copied my repro and it didn't implement `not_eof` right.
Maybe worth attempting, as it might be used in streaming tests as well someday.

File: tests/std/tests/GH_004930_char_traits_user_specialization/test.cpp [hunk 4]
```diff
@@ -0,0 +1,210 @@
...
+        odd_string_view sv2(s2_init);
+
+        assert(sv.find_first_of(sv2) == 2);
+        assert(sv2.find_first_of(sv) == 0);
+
+        assert(sv.find_last_of(sv2) == 3);
+        assert(sv2.find_last_of(sv) == 1);
+    }
+#endif // _HAS_CXX17
+
```
Comment (AlexGuteniev) [inline tests/std/tests/GH_004930_char_traits_user_specialization/test.cpp:200]: Apparently it is lacking lex compare coverage.

**Review by AlexGuteniev — APPROVED** [review]

File: stl/inc/__msvc_string_view.hpp (hunk 1 above)
Comment (AlexGuteniev) [reply stl/inc/__msvc_string_view.hpp:716]: Maybe I'll do this when last tail call with the different template argument is eliminated as a result of control flow enhancements in vectorization changes.

File: tests/std/tests/GH_004930_char_traits_user_specialization/test.cpp (hunk 3 above)
Comment (frederick-vs-ja) [reply tests/std/tests/GH_004930_char_traits_user_specialization/test.cpp]: Fixed. I found that `length` also needed to be fixed.

File: tests/std/tests/GH_004930_char_traits_user_specialization/test.cpp (hunk 4 above)
Comment (frederick-vs-ja) [reply tests/std/tests/GH_004930_char_traits_user_specialization/test.cpp:269]: I'm trying to expand the coverage now.

Comment (AlexGuteniev) [reply tests/std/tests/GH_004930_char_traits_user_specialization/test.cpp:269]: Actually I don't even know whar that regex part does, not sure if it is lex compare

File: tests/std/tests/GH_004930_char_traits_user_specialization/test.cpp [hunk 5]
```diff
@@ -0,0 +1,279 @@
...
+        }
+        return s;
+    }
+
+    static constexpr bool not_eof(const int_type i) noexcept {
+        return i != -1;
+    }
+
+    static constexpr char_type to_char_type(const int_type i) noexcept {
+        return char_type(static_cast<unsigned char>(i));
```
Comment (StephanTLavavej) [inline tests/std/tests/GH_004930_char_traits_user_specialization/test.cpp:141]: This is a functional-style cast from `unsigned char` to the enum `char_type`.

File: tests/std/tests/GH_004930_char_traits_user_specialization/test.cpp [hunk 6]
```diff
@@ -0,0 +1,279 @@
...
+    assert(s.find_first_of(s2) == 2);
+    assert(s2.find_first_of(s) == 0);
+
+    assert(s.find_last_of(s2) == 3);
+    assert(s2.find_last_of(s) == 1);
+
+    assert(s.find_first_not_of(s2) == 0);
+    assert(s2.find_first_not_of(s) == s2.npos);
+
+#if _HAS_CXX17
```
Comment (StephanTLavavej) [inline tests/std/tests/GH_004930_char_traits_user_specialization/test.cpp:243]: `find_last_not_of` coverage is missing.

**Review by StephanTLavavej — APPROVED** [review]

File: tests/std/tests/GH_004930_char_traits_user_specialization/test.cpp (hunk 4 above)
Comment (StephanTLavavej) [reply tests/std/tests/GH_004930_char_traits_user_specialization/test.cpp:275]: I'm fine with this level of test coverage.

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
:thread: :unicorn: :hammer_and_wrench:
===

File: stl/inc/__msvc_string_view.hpp [hunk 7]
```diff
@@ -331,6 +331,17 @@ template <>
 struct char_traits<unsigned short> : _WChar_traits<unsigned short> {};
 #endif // defined(_CRTBLD)
 
+// signed char and other unsigned integral types are supported as an extension.
+// Use of other arithmetic types and nullptr_t should be rejected.
+template <class _Ty>
+constexpr bool _Is_implementation_handled_char_like_type = is_arithmetic_v<_Ty> || is_null_pointer_v<_Ty>;
```
Comment (AlexGuteniev) [inline stl/inc/__msvc_string_view.hpp:337]: I came from the future to ask: why exactly `is_arithmetic_v<_Ty> || is_null_pointer_v<_Ty>`? Can we limit to `is_integral<_Ty>` ?

Comment (AlexGuteniev) [reply stl/inc/__msvc_string_view.hpp:337]: Ah, got it, that are impossible to specialize
