### PR TITLE
`<regex>`: Always reject character ranges with set limits

### LINKED ISSUE #4995: `<regex>`: `R"([\d-e])"` should be rejected
# Describe the bug
The regex [\d-e] (character class containing the range \d to e) is accepted (treated as \d, and the literal characters - and e), contrary to [the ECMA-262 spec](https://262.ecma-international.org/5.1/#sec-15.10.2.15) (\d isn't a single character, so it can't be used like that)

# Command-line test case
```
#include <regex>

int main()
{
    try {
        std::regex r("[\\d-e]");
        puts("it's legal");
    } catch (std::exception& e) {
        puts(e.what());
    }
    try {
        std::regex r("[b-a]");
        puts("it's legal");
    } catch (std::exception& e) {
        puts(e.what());
    }
}
```
https://godbolt.org/z/oMvEr5YTs

# Expected behavior
Both should be illegal (currently, only the latter is rejected)

# STL version
Ask Godbolt

# Additional context
Feel free to close this one as wontfix, if you feel it's ossified into a vendor extension. As long as it's a conscious choice, I'm fine with whichever outcome.

### PR DESCRIPTION
**Pull request by muellerj2**
Fixes #4995.

Unblocks libcxx test `std/re/re.regex/re.regex.construct/bad_range.pass.cpp`.

Note that I did not add test coverage for regular expressions like `[[.a.]-e]`: After this change, this regex is rejected as well (rather than parsed incorrectly). However, such regular expressions should actually be accepted (!), because `[.xxx.]` is not a set of characters, but (kind of) a single character if `xxx` is the name of a valid collating element. But support of collating symbols is currently so terribly broken that it is basically guaranteed to produce wrong results (see https://github.com/microsoft/STL/issues/994#issuecomment-1603697429), so I think it would be a major disservice to users if we actually accepted this regex without a major overhaul of collation support in the implementation.

### CODE REVIEW

File: tests/std/tests/VSO_0000000_regex_use/test.cpp [hunk 1]
```diff
@@ -582,6 +582,19 @@ void test_gh_993() {
...
+    g_regexTester.should_throw("[\\d-e]", error_range);
+    g_regexTester.should_throw("[e-\\d]", error_range);
+    g_regexTester.should_throw("[\\w-\\d]", error_range);
+    g_regexTester.should_throw("[[:digit:]-e]", error_range);
+    g_regexTester.should_throw("[e-[:digit:]]", error_range);
+    g_regexTester.should_throw("[[:alpha:]-[:digit:]]", error_range);
+    g_regexTester.should_throw("[[=a=]-e]", error_range, ECMAScript | regex::collate);
+    g_regexTester.should_throw("[e-[=a=]]", error_range, ECMAScript | regex::collate);
+    g_regexTester.should_throw("[[=a=]-[=b=]]", error_range, ECMAScript | regex::collate);
+}
```
Comment (StephanTLavavej) [inline tests/std/tests/VSO_0000000_regex_use/test.cpp:596]: This is great test coverage of the error cases. As you're adjusting the control flow, let's also add positive test coverage of sets that should still be accepted.

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Thanks for fixing this complicated control flow! :heart_eyes_cat: I pushed minor stylistic changes and test improvements after debugging through the code and convincing myself that your changes were correct.

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
Thanks for figuring out how this code was broken and how to fix it! :heart_eyes_cat: :yarn: :hammer_and_wrench:
