### PR TITLE
Merging format

### LINKED ISSUE #30: P0645R10 <format> Text Formatting
[P0645R10](https://wg21.link/P0645R10) `<format>` Text Formatting
[P1361R2](https://wg21.link/P1361R2) Integrating `<chrono>` With `<format>`
[P1652R1](https://wg21.link/P1652R1) `printf()` Corner Cases In `std::format()`
[P1868R2](https://wg21.link/P1868R2) Clarifying Units Of Width And Precision In `std::format()`
[P1892R1](https://wg21.link/P1892R1) Extended Locale-Specific Presentation Specifiers For `std::format()`

LWG-3242 `std::format` missing rules for `arg-id` in `width` and `precision`
LWG-3243 `std::format` and negative zeroes
LWG-3246 What are the constraints on the template parameter of `basic_format_arg`?
LWG-3248 `std::format` `#b`, `#B`, `#o`, `#x`, and `#X` presentation types misformat negative numbers
LWG-3250 `std::format` `#` (alternate form) for NaN and inf
LWG-3251 Are `std::format` alignment specifiers applied to string arguments?
LWG-3327 Format alignment specifiers vs. text direction
LWG-3340 Formatting functions should throw on argument/format string mismatch in `[format.functions]`
LWG-3371 `visit_format_arg` and `make_format_args` are not hidden friends
LWG-3372 `vformat_to` should not try to deduce `Out` twice
LWG-3373 `{to,from}_chars_result` and `format_to_n_result` need the "we really mean what we say" wording
LWG-3473 Normative encouragement in non-normative note

The IDE's list of extensionless headers has been updated for VS 2019 16.5.

Feature-test macro as of WG21-N4842:
`#define __cpp_lib_format 201907L`

### LINKED ISSUE #1826: <format>: Avoid dependency on <variant>
**Describe the bug**

The `<format>` header currently includes `<varaint>` which is a big dependency. However, `std::variant` itself is not used in the implementation, only `std::monostate` which is a trivial struct. Is it possible to move `std::monostate` to a common header to be used from `<format>` and `<variant>` to break the unnecessary dependency and potentially reduce compile times?

**Command-line test case**
```
C:\Temp>type test.cc
#include <format>

int main() {
  auto v = std::variant<int>();
}

C:\Temp>cl /I STL/stl/inc /std:c++latest test.cc
Microsoft (R) C/C++ Optimizing Compiler Version 19.29.29917 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

/std:c++latest is provided as a preview of language features from the latest C++
working draft, and we're eager to hear about bugs and suggestions for improvements.
However, note that these features are provided as-is without support, and subject
to changes or removal as the working draft evolves. See
https://go.microsoft.com/fwlink/?linkid=2045807 for details.

test.cc
Microsoft (R) Incremental Linker Version 14.29.29917.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:test.exe
test.obj
```

**Expected behavior**
The test shouldn't compile because `<format>` shoudn't provide `std::variant`.

**STL version**

https://github.com/microsoft/STL/commit/4d7d4f1

### PR DESCRIPTION
**Pull request by barcharcraz**
* adds an implementation of `<format>`
* Resolves #30.
* Resolves #1826.

### CODE REVIEW

File: stl/inc/format [hunk 1]
```diff
@@ -0,0 +1,2734 @@
...
+            _Value = _Max_int + 1;
+            break;
+        }
+        _Value = _Value * 10 + static_cast<unsigned int>(*_Begin - '0');
+        ++_Begin;
+    } while (_Begin != _End && '0' <= *_Begin && *_Begin <= '9');
+    if (_Value > _Max_int) {
+        throw format_error("Number is too big");
+    }
+    return _Begin;
```
Comment (miscco) [inline stl/inc/format:372]: I *think* we also conventionally add a newline here
```suggestion

    return _Begin;
```

File: stl/inc/format [hunk 2]
```diff
@@ -0,0 +1,2734 @@
...
+        unsigned int _Index = 0;
+        // arg_id is not allowed to have any leading zeros, but is allowed to be
+        // equal to zero (but not '00'). So if _Ch is zero we skip the parsing, leave
+        // _Index set to zero and let the validity checks below ensure that the arg_id
+        // wasn't something like "00", or "023".
+        if (_Ch != '0') {
+            _Begin = _Parse_nonnegative_integer(_Begin, _End, _Index);
+        } else {
+            ++_Begin;
+        }
```
Comment (miscco) [inline stl/inc/format:406]: Super nitpick: We usually avoid negations in comparisons also there should be a newline i guess?
```suggestion
        if (_Ch == '0') {
            ++_Begin;
        } else {
            _Begin = _Parse_nonnegative_integer(_Begin, _End, _Index);
        }
        
```

File: stl/inc/format [hunk 3]
```diff
@@ -0,0 +1,2734 @@
...
+        // The format string shouldn't end right after the index number.
+        // The only things permitted after the index are the end of the replacement field ('}')
+        // or the beginning of the format spec (':').
+        if (_Begin == _End || (*_Begin != '}' && *_Begin != ':')) {
+            throw format_error("Invalid format string.");
+        }
+        _Callbacks._On_manual_id(_Index);
```
Comment (miscco) [inline stl/inc/format:413]:
```suggestion

        _Callbacks._On_manual_id(_Index);
```

File: stl/inc/format [hunk 4]
```diff
@@ -0,0 +1,2734 @@
...
+            return (_Len >= 4) ? 4 : -1;
+        }
+    }
+}
+
+_NODISCARD inline int _Code_units_in_next_character(const wchar_t* _First, const wchar_t* _Last, const _Cvtvec&) {
+    // Returns a count of the number of code units that compose the first encoded character in
+    // [_First, _Last), or -1 if [_First, _Last) doesn't contain an entire encoded character or
+    // *_First is an unpaired surrogate.
+
```
Comment (miscco) [inline stl/inc/format:477]: I will need that newline for some other place
```suggestion
```

File: stl/inc/format [hunk 5]
```diff
@@ -0,0 +1,2734 @@
...
+        return -1;
+    }
+
+    return 2; // surrogate pair
+}
+
+template <class _CharT, _Parse_align_callbacks<_CharT> _Callbacks_type>
+_NODISCARD const _CharT* _Parse_align(const _CharT* _Begin, const _CharT* _End, _Callbacks_type&& _Callbacks) {
+    _STL_INTERNAL_CHECK(_Begin != _End && *_Begin != '}');
+    // align and fill
```
Comment (miscco) [inline stl/inc/format:498]: In the above functions it is always comment then check
```suggestion
    // align and fill
    _STL_INTERNAL_CHECK(_Begin != _End && *_Begin != '}');
```

File: stl/inc/format [hunk 6]
```diff
@@ -0,0 +1,2734 @@
...
+    auto _Parsed_align = _Align::_None;
+
+    const int _Units = _Code_units_in_next_character(_Begin, _End, _Getcvt());
+    if (_Units < 0) { // invalid fill character encoding
+        throw format_error("Invalid format string.");
+    }
+    auto _Align_pt = _Begin + _Units;
```
Comment (miscco) [inline stl/inc/format:505]: It is super ugly but newline
```suggestion
    auto _Align_pt = _Begin + _Units;

```

File: stl/inc/format [hunk 7]
```diff
@@ -0,0 +1,2734 @@
...
+    if (_Align_pt == _End) {
+        _Align_pt = _Begin;
+    }
+    for (;;) {
```
Comment (miscco) [inline stl/inc/format:509]:
```suggestion

    for (;;) {
```

File: stl/inc/format [hunk 8]
```diff
@@ -0,0 +1,2734 @@
...
+            _Parsed_align = _Align::_Left;
+            break;
+        case '>':
+            _Parsed_align = _Align::_Right;
+            break;
+        case '^':
+            _Parsed_align = _Align::_Center;
+            break;
+        }
+        if (_Parsed_align != _Align::_None) {
```
Comment (miscco) [inline stl/inc/format:521]:
```suggestion

        if (_Parsed_align != _Align::_None) {
```

File: stl/inc/format [hunk 9]
```diff
@@ -0,0 +1,2734 @@
...
+                ++_Begin;
+            }
+            _Callbacks._On_align(_Parsed_align);
+            break;
+        } else if (_Align_pt == _Begin) {
+            break;
+        }
+        _Align_pt = _Begin;
+    }
+    return _Begin;
```
Comment (miscco) [inline stl/inc/format:538]:
```suggestion

    return _Begin;
```

File: stl/inc/format [hunk 10]
```diff
@@ -0,0 +1,2734 @@
...
+template <class _CharT, _Width_adapter_callbacks<_CharT> _Callbacks_type>
+struct _Width_adapter {
+    _Callbacks_type& _Callbacks;
+
+    constexpr explicit _Width_adapter(_Callbacks_type& _Handler) : _Callbacks(_Handler) {}
+
+    constexpr void _On_auto_id() {
+        _Callbacks._On_dynamic_width(_Auto_id_tag{});
+    }
+    constexpr void _On_manual_id(size_t _Id) {
```
Comment (miscco) [inline stl/inc/format:552]: could be const
```suggestion
    constexpr void _On_manual_id(const size_t _Id) {
```

File: stl/inc/format [hunk 11]
```diff
@@ -0,0 +1,2734 @@
...
+template <class _CharT, _Precision_adapter_callbacks<_CharT> _Callbacks_type>
+struct _Precision_adapter {
+    _Callbacks_type& _Callbacks;
+
+    constexpr explicit _Precision_adapter(_Callbacks_type& _Handler) : _Callbacks(_Handler) {}
+
+    constexpr void _On_auto_id() {
+        _Callbacks._On_dynamic_precision(_Auto_id_tag{});
+    }
+    constexpr void _On_manual_id(size_t _Id) {
```
Comment (miscco) [inline stl/inc/format:568]: could be const
```suggestion
    constexpr void _On_manual_id(const size_t _Id) {
```

File: stl/inc/format [hunk 12]
```diff
@@ -0,0 +1,2734 @@
...
+template <class _CharT>
+struct _Id_adapter {
+    basic_format_parse_context<_CharT>& _Parse_context;
+    size_t _Arg_id = static_cast<size_t>(-1);
+
+    constexpr void _On_auto_id() {
+        _Arg_id = _Parse_context.next_arg_id();
+        _STL_INTERNAL_CHECK(_Arg_id != static_cast<size_t>(-1));
+    }
+    constexpr void _On_manual_id(size_t _Id) {
```
Comment (miscco) [inline stl/inc/format:586]:
```suggestion
    constexpr void _On_manual_id(const size_t _Id) {
```

File: stl/inc/format [hunk 13]
```diff
@@ -0,0 +1,2734 @@
...
+    if ('1' <= *_Begin && *_Begin <= '9') {
+        int _Value = 0;
+        _Begin     = _Parse_nonnegative_integer(_Begin, _End, _Value);
+        _Callbacks._On_width(_Value);
+    } else if (*_Begin == '{') {
+        ++_Begin;
+        if (_Begin != _End) {
+            _Begin = _Parse_arg_id(_Begin, _End, _Width_adapter<_CharT, _Callbacks_type>{_Callbacks});
+        }
+        if (_Begin == _End || *_Begin != '}') {
```
Comment (miscco) [inline stl/inc/format:606]:
```suggestion

        if (_Begin == _End || *_Begin != '}') {
```

File: stl/inc/format [hunk 14]
```diff
@@ -0,0 +1,2734 @@
...
+    }
+
+    if (_Ch >= '0' && _Ch <= '9') {
+        unsigned int _Index = 0;
+        // arg_id is not allowed to have any leading zeros, but is allowed to be
+        // equal to zero (but not '00'). So if _Ch is zero we skip the parsing, leave
+        // _Index set to zero and let the validity checks below ensure that the arg_id
+        // wasn't something like "00", or "023".
+        if (_Ch != '0') {
+            _Begin = _Parse_nonnegative_integer(_Begin, _End, _Index);
```
Comment (miscco) [inline stl/inc/format:403]: This is the only place where we need `_Index` to be an in-out parameter. Is it worth it to slightly change the code here to not rely on in-out parameters, which would most likely clean up other places a bit

File: stl/inc/format [hunk 15]
```diff
@@ -0,0 +1,2734 @@
...
+            _Begin = _Parse_arg_id(_Begin, _End, _Precision_adapter<_CharT, _Callbacks_type>{_Callbacks});
+        }
+
+        if (_Begin == _End || *_Begin != '}') {
+            throw format_error("Invalid format string.");
+        }
+    } else {
+        throw format_error("Missing precision specifier.");
+    }
+    return _Begin;
```
Comment (miscco) [inline stl/inc/format:639]:
```suggestion

    return _Begin;
```

File: stl/inc/format [hunk 16]
```diff
@@ -0,0 +1,2734 @@
...
+    if (*_Begin == 'L') {
+        _Callbacks._On_localized();
+        if (++_Begin == _End) {
+            return _Begin;
+        }
+    }
+
+    // If there's anything remaining we assume it's a type.
+    if (*_Begin != '}') {
+        _Callbacks._On_type(*_Begin++);
```
Comment (miscco) [inline stl/inc/format:710]: Nitpick: Can we move the post decrement out of the function argument? It is easy to miss and different than all other places
```suggestion
        _Callbacks._On_type(*_Begin);
        ++_Begin;
```

File: stl/inc/format [hunk 17]
```diff
@@ -0,0 +1,2734 @@
...
+    }
+    return _Begin;
```
Comment (miscco) [inline stl/inc/format:712]:
```suggestion

    return _Begin;
```

File: stl/inc/format [hunk 18]
```diff
@@ -0,0 +1,2734 @@
...
+        // string was "{{", so we have a literal "{" to print
+        _Handler._On_text(_Begin, _Begin + 1);
+    } else {
+        _Id_adapter<_CharT> _Adapter{_Handler._Parse_context};
+        _Begin     = _Parse_arg_id(_Begin, _End, _Adapter);
+        _CharT _Ch = _CharT{};
+        if (_Begin != _End) {
+            _Ch = *_Begin;
+        }
+        if (_Ch == '}') {
```
Comment (miscco) [inline stl/inc/format:736]:
```suggestion

        if (_Ch == '}') {
```

File: stl/inc/format [hunk 19]
```diff
@@ -0,0 +1,2734 @@
...
+        } else if (_Ch == ':') {
+            _Begin = _Handler._On_format_specs(_Adapter._Arg_id, _Begin + 1, _End);
+            if (_Begin == _End || *_Begin != '}') {
+                throw format_error("Unknown format specifier.");
+            }
+        } else {
+            throw format_error("Missing '}' in format string.");
+        }
+    }
+    return _Begin + 1;
```
Comment (miscco) [inline stl/inc/format:747]:
```suggestion

    return _Begin + 1;
```

File: stl/inc/format [hunk 20]
```diff
@@ -0,0 +1,2734 @@
...
+struct _Basic_format_specs {
+    int _Width           = 0;
+    int _Precision       = -1;
+    char _Type           = '\0';
+    _Align _Alignment    = _Align::_None;
+    _Sign _Sgn           = _Sign::_None;
+    bool _Alt            = false;
+    bool _Localized      = false;
+    bool _Leading_zero   = false;
+    uint8_t _Fill_length = 1;
```
Comment (miscco) [inline stl/inc/format:823]: We *could* pack this a bit better into one `uint8_t`. Is it worth it?

File: stl/inc/format [hunk 21]
```diff
@@ -0,0 +1,2734 @@
...
+    int _Dynamic_precision_index = -1;
+};
+
+// Model of _Parse_spec_callbacks that fills a _Basic_format_specs with the parsed data.
+template <class _CharT>
+class _Specs_setter {
+public:
+    explicit constexpr _Specs_setter(_Basic_format_specs<_CharT>& _Specs_) : _Specs(_Specs_) {}
+
+    constexpr void _On_align(_Align _Aln) {
```
Comment (miscco) [inline stl/inc/format:843]: could be const
```suggestion
    constexpr void _On_align(const _Align _Aln) {
```

File: stl/inc/format [hunk 22]
```diff
@@ -0,0 +1,2734 @@
...
+        _Specs._Alignment = _Aln;
+    }
+
+    constexpr void _On_fill(basic_string_view<_CharT> _Sv) {
```
Comment (miscco) [inline stl/inc/format:847]: could be const
```suggestion
    constexpr void _On_fill(const basic_string_view<_CharT> _Sv) {
```

File: stl/inc/format [hunk 23]
```diff
@@ -0,0 +1,2734 @@
...
+        if (_Sv.size() > _STD size(_Specs._Fill)) {
+            throw format_error("Invalid fill (too long).");
+        }
+
+        const auto _Pos = _STD _Copy_unchecked(_Sv._Unchecked_begin(), _Sv._Unchecked_end(), _Specs._Fill);
+        _STD fill(_Pos, _STD end(_Specs._Fill), _CharT{});
+        _Specs._Fill_length = static_cast<uint8_t>(_Sv.size());
+    }
+
+    constexpr void _On_sign(_Sign _Sgn) {
```
Comment (miscco) [inline stl/inc/format:857]:
```suggestion
    constexpr void _On_sign(const _Sign _Sgn) {
```

File: stl/inc/format [hunk 24]
```diff
@@ -0,0 +1,2734 @@
...
+
+    constexpr void _On_hash() {
+        _Specs._Alt = true;
+    }
+
+    constexpr void _On_zero() {
+        _Specs._Leading_zero = true;
+    }
+
+    constexpr void _On_width(int _Width) {
```
Comment (miscco) [inline stl/inc/format:869]:
```suggestion
    constexpr void _On_width(const int _Width) {
```

File: stl/inc/format [hunk 25]
```diff
@@ -0,0 +1,2734 @@
...
+        _Specs._Width = _Width;
+    }
+
+    constexpr void _On_precision(int _Precision) {
```
Comment (miscco) [inline stl/inc/format:873]:
```suggestion
    constexpr void _On_precision(const int _Precision) {
```

File: stl/inc/format [hunk 26]
```diff
@@ -0,0 +1,2734 @@
...
+        _Specs._Precision = _Precision;
+    }
+
+    constexpr void _On_localized() {
+        _Specs._Localized = true;
+    }
+
+    constexpr void _On_type(_CharT _Type) {
```
Comment (miscco) [inline stl/inc/format:881]:
```suggestion
    constexpr void _On_type(const _CharT _Type) {
```

File: stl/inc/format [hunk 27]
```diff
@@ -0,0 +1,2734 @@
...
+        // performance note: this could be optimized to one comparison by
+        // first casting to unsigned int (the negative values will be 128-255)
+        if (_Type < 0 || _Type > (numeric_limits<signed char>::max)()) {
```
Comment (miscco) [inline stl/inc/format:884]: Should we apply this optimization?
```suggestion
        if (static_cast<unsigned int>(_Type) >= 128) { // negative values start at 128
```

File: stl/inc/format [hunk 28]
```diff
@@ -0,0 +1,2734 @@
...
+template <class _Context>
+_NODISCARD constexpr basic_format_arg<_Context> _Get_arg(const _Context& _Ctx, size_t _Arg_id) {
+    // note: while this is parameterized on the _Arg_id type in libfmt we don't
+    // need to do that in std::format because it's only called with either an integer
+    // id or a named id (which we do not support in std::format)
+    auto _Arg = _Ctx.arg(_Arg_id);
+    if (!_Arg) {
+        throw format_error("Argument not found.");
+    }
+    return _Arg;
```
Comment (miscco) [inline stl/inc/format:903]:
```suggestion

    return _Arg;
```

File: stl/inc/format [hunk 29]
```diff
@@ -0,0 +1,2734 @@
...
+        }
+        _Specs._Type = static_cast<char>(_Type);
+    }
+
+protected:
+    _Basic_format_specs<_CharT>& _Specs;
+};
+
+template <class _Context>
+_NODISCARD constexpr basic_format_arg<_Context> _Get_arg(const _Context& _Ctx, size_t _Arg_id) {
```
Comment (miscco) [inline stl/inc/format:895]:
```suggestion
_NODISCARD constexpr basic_format_arg<_Context> _Get_arg(const _Context& _Ctx, const size_t _Arg_id) {
```

File: stl/inc/format [hunk 30]
```diff
@@ -0,0 +1,2734 @@
...
+    }
+    return _Arg;
+}
+
+// Checks that the type and value of an argument associated with a dynamic
+// width specifier are valid.
+class _Width_checker {
+public:
+    template <class _Ty>
+    _NODISCARD constexpr unsigned long long operator()(_Ty _Value) {
```
Comment (miscco) [inline stl/inc/format:911]: Should we use `auto` here given that we cast below. Should that be a const method?
```suggestion
    _NODISCARD constexpr auto operator()(const _Ty _Value) const {
```

File: stl/inc/format [hunk 31]
```diff
@@ -0,0 +1,2734 @@
...
+        }
+    }
+};
+
+// Checks that the type and value of an argument associated with a dynamic
+// precision specifier are valid.
+class _Precision_checker {
+public:
+    template <class _Ty>
+    _NODISCARD constexpr unsigned long long operator()(_Ty _Value) {
```
Comment (miscco) [inline stl/inc/format:930]: Ditto should we use `auto` and make this a `const` method
```suggestion
    _NODISCARD constexpr auto operator()(const _Ty _Value) const {
```

File: stl/inc/format [hunk 32]
```diff
@@ -0,0 +1,2734 @@
...
+};
+
+// Fetch the value of an argument associated with a dynamic
+// width or precision specifier. This will be called with either
+// _Width_checker or _Precision_checker as "_Handler".
+template <class _Handler, class _FormatArg>
+_NODISCARD constexpr int _Get_dynamic_specs(const _FormatArg _Arg) {
+    _STL_INTERNAL_STATIC_ASSERT(_Is_any_of_v<_Handler, _Width_checker, _Precision_checker>);
+    const unsigned long long _Val = _STD visit_format_arg(_Handler(), _Arg);
+    if (_Val > (numeric_limits<int>::max)()) {
```
Comment (miscco) [inline stl/inc/format:951]: This compares `unsigned long long` with `int` Should we cast?

File: stl/inc/format [hunk 33]
```diff
@@ -0,0 +1,2734 @@
...
+        throw format_error("Number is too big.");
+    }
+    return static_cast<int>(_Val);
```
Comment (miscco) [inline stl/inc/format:954]:
```suggestion

    return static_cast<int>(_Val);
```

File: stl/inc/format [hunk 34]
```diff
@@ -0,0 +1,2734 @@
...
+
+private:
+    _Dynamic_format_specs<_CharT>& _Dynamic_specs;
+    _ParseContext& _Parse_ctx;
+
+    _NODISCARD static constexpr int _Verify_dynamic_arg_index_in_range(const size_t _Idx) {
+        if (_Idx > static_cast<size_t>((numeric_limits<int>::max)())) {
+            throw format_error("Dynamic width or precision index too large.");
+        }
+        return static_cast<int>(_Idx);
```
Comment (miscco) [inline stl/inc/format:1026]:
```suggestion

        return static_cast<int>(_Idx);
```

File: stl/inc/format [hunk 35]
```diff
@@ -0,0 +1,2734 @@
...
+// a replacement field with format specs actually satisfies the requirements for
+// that format spec. If the requirements are met then calls the base class
+// handler method.
+template <class _Handler>
+class _Specs_checker : public _Handler {
+private:
+    _Numeric_specs_checker _Numeric_checker;
+
+public:
+    constexpr explicit _Specs_checker(const _Handler& _Handler_inst, _Basic_format_arg_type _Arg_type_)
```
Comment (miscco) [inline stl/inc/format:1069]:
```suggestion
    constexpr explicit _Specs_checker(const _Handler& _Handler_inst, const _Basic_format_arg_type _Arg_type_)
```

File: stl/inc/format [hunk 36]
```diff
@@ -0,0 +1,2734 @@
...
+public:
+    using iterator  = _Out;
+    using char_type = _CharT;
+
+    template <class _Ty>
+    using formatter_type = formatter<_Ty, _CharT>;
+
+    constexpr basic_format_context(
+        _Out _OutputIt_, basic_format_args<basic_format_context> _Ctx_args, const locale& _Loc_)
+        : _OutputIt(_STD move(_OutputIt_)), _Args(_Ctx_args), _Loc(_Loc_) {}
```
Comment (miscco) [inline stl/inc/format:1385]: Should we move the `_Ctx_args`?
```suggestion
        : _OutputIt(_STD move(_OutputIt_)), _Args(_STD move(_Ctx_args)), _Loc(_Loc_) {}
```

File: stl/inc/format [hunk 37]
```diff
@@ -0,0 +1,2734 @@
...
+        return _Args.get(_Id);
+    }
+    _NODISCARD locale locale() {
+        return _Loc;
+    }
+
+    _NODISCARD iterator out() {
+        return _STD move(_OutputIt);
+    }
+    void advance_to(iterator _It) {
```
Comment (miscco) [inline stl/inc/format:1397]: Can this be noexcept?
```suggestion
    void advance_to(iterator _It) noexcept {
```

File: stl/inc/format [hunk 38]
```diff
@@ -0,0 +1,2734 @@
...
+        : _OutputIt(_STD move(_OutputIt_)), _Args(_Ctx_args), _Loc(_Loc_) {}
+
+    _NODISCARD basic_format_arg<basic_format_context> arg(size_t _Id) const {
+        return _Args.get(_Id);
+    }
+    _NODISCARD locale locale() {
+        return _Loc;
+    }
+
+    _NODISCARD iterator out() {
```
Comment (miscco) [inline stl/inc/format:1394]: Should be noexcept
```suggestion
    _NODISCARD iterator out() noexcept {
```

File: stl/inc/format [hunk 39]
```diff
@@ -0,0 +1,2734 @@
...
+        return _STD move(_OutputIt);
+    }
+    void advance_to(iterator _It) {
+        _OutputIt = _STD move(_It);
+    }
+
+    _NODISCARD const basic_format_args<basic_format_context>& _Get_args() const {
```
Comment (miscco) [inline stl/inc/format:1401]: We all love our language defaults dont we?
```suggestion
    _NODISCARD const basic_format_args<basic_format_context>& _Get_args() const noexcept {
```

File: stl/inc/format [hunk 40]
```diff
@@ -0,0 +1,2734 @@
...
+        return _Args;
+    }
+};
+
+template <class _CharT>
+_NODISCARD constexpr size_t _Get_format_arg_type_storage_size(_Basic_format_arg_type _Type) {
```
Comment (miscco) [inline stl/inc/format:1407]:
```suggestion
_NODISCARD constexpr size_t _Get_format_arg_type_storage_size(_Basic_format_arg_type _Type) noexcept {
```

File: stl/inc/format [hunk 41]
```diff
@@ -0,0 +1,2734 @@
...
+#pragma warning(push)
+#pragma warning(disable : 4365) // 'argument': conversion from 'char' to 'const wchar_t', signed/unsigned mismatch
+// clang-format off
+template <class _CharT, class _OutputIt, class _Arithmetic>
+    requires (is_arithmetic_v<_Arithmetic> && !_CharT_or_bool<_Arithmetic, _CharT>)
+_NODISCARD _OutputIt _Fmt_write(_OutputIt _Out, const _Arithmetic _Value) {
+    // clang-format on
+    // TRANSITION, Reusable buffer
+    array<char, _Format_min_buffer_length> _Buffer;
+    const auto [_End, _Ec] = _STD to_chars(_Buffer.data(), _Buffer.data() + _Buffer.size(), _Value);
```
Comment (miscco) [inline stl/inc/format:1484]: I vaguely remember that we wanted to make this a plain array

File: stl/inc/format [hunk 42]
```diff
@@ -0,0 +1,2734 @@
...
+    return _RANGES _Copy_unchecked(_Buffer.data(), _End, _STD move(_Out)).out;
+}
+#pragma warning(pop)
+
+template <class _CharT, class _OutputIt>
+_NODISCARD _OutputIt _Fmt_write(_OutputIt _Out, const _CharT* _Value) {
+    if (!_Value) {
+        throw format_error("String pointer is null.");
+    }
+    while (*_Value) {
```
Comment (miscco) [inline stl/inc/format:1525]:
```suggestion

    while (*_Value) {
```

File: stl/inc/format [hunk 43]
```diff
@@ -0,0 +1,2734 @@
...
+        *_Out++ = *_Value++;
+    }
+    return _Out;
```
Comment (miscco) [inline stl/inc/format:1528]:
```suggestion

    return _Out;
```

File: stl/inc/format [hunk 44]
```diff
@@ -0,0 +1,2734 @@
...
+
+    for (; _Fill_right > 0; --_Fill_right) {
+        _Out = _RANGES copy(_Fill_char, _STD move(_Out)).out;
+    }
+
+    return _Out;
+}
+
+template <integral _Integral>
+_NODISCARD constexpr string_view _Get_integral_prefix(const char _Type, const _Integral _Value) {
```
Comment (miscco) [inline stl/inc/format:1580]:
```suggestion
_NODISCARD constexpr string_view _Get_integral_prefix(const char _Type, const _Integral _Value) noexcept {
```

File: stl/inc/format [hunk 45]
```diff
@@ -0,0 +1,2734 @@
...
+        auto _Group_it = _Groups.begin();
+        while (_Digits > static_cast<size_t>(*_Group_it)) {
+            _Digits -= static_cast<size_t>(*_Group_it);
+            ++_Separators;
+            if (_Group_it + 1 != _Groups.end()) {
+                ++_Group_it;
+            }
+        }
+    }
+    return _Separators;
```
Comment (miscco) [inline stl/inc/format:1652]: I believe it would be cleaner if we would directly return for empty groups
```suggestion
    if (_Groups.empty()) {
        return 0;
    }
    
    // Calculate the amount of separators that are going to be inserted based on the groupings of the locale.
    int _Separators = 0;
    auto _Group_it = _Groups.begin();
    while (_Digits > static_cast<size_t>(*_Group_it)) {
        _Digits -= static_cast<size_t>(*_Group_it);
        ++_Separators;
         if (_Group_it + 1 != _Groups.end()) {
            ++_Group_it;
        }
    }
    }
    return _Separators;
```

File: stl/inc/format [hunk 46]
```diff
@@ -0,0 +1,2734 @@
...
+    case 'o':
+        _Base = 8;
+        break;
+    default:
+        throw format_error("invalid integral type");
+    }
+
+    // long long -1 representation in binary is 64 bits + sign
+    array<char, 65> _Buffer;
+    const auto [_End, _Ec] = _STD to_chars(_Buffer.data(), _Buffer.data() + _Buffer.size(), _Value, _Base);
```
Comment (miscco) [inline stl/inc/format:1777]: Ditto plain buffer

File: stl/inc/format [hunk 47]
```diff
@@ -0,0 +1,2734 @@
...
+_NODISCARD constexpr int _Unicode_width_estimate(const char32_t _Ch) noexcept {
+    // Computes the width estimation for Unicode characters from N4885 [format.string.std]/11
+    int _Result = 1;
+    for (const auto& _Bound : _Bounds) {
+        if (_Ch < _Bound) {
+            return _Result;
+        }
+        _Result ^= 1;
+    }
+    return 1;
```
Comment (miscco) [inline stl/inc/format:2163]:
```suggestion

    return 1;
```

File: stl/inc/format [hunk 48]
```diff
@@ -0,0 +1,2734 @@
...
+
+    explicit _Format_handler(
+        _OutputIt _Out, basic_string_view<_CharT> _Str, basic_format_args<_Context> _Format_args, const locale& _Loc)
+        : _Parse_context(_Str), _Ctx(_STD move(_Out), _Format_args, _Loc) {}
+
+    void _On_text(const _CharT* _Begin, const _CharT* _End) {
+        _Ctx.advance_to(_RANGES _Copy_unchecked(_Begin, _End, _Ctx.out()).out);
+    }
+
+    void _On_replacement_field(size_t _Id, const _CharT*) {
```
Comment (miscco) [inline stl/inc/format:2355]:
```suggestion
    void _On_replacement_field(const size_t _Id, const _CharT*) {
```

File: stl/inc/format [hunk 49]
```diff
@@ -0,0 +1,2734 @@
...
+        auto _Arg = _Ctx.arg(_Id);
+        _Ctx.advance_to(_STD visit_format_arg(
+            _Default_arg_formatter<_OutputIt, _CharT>{_Ctx.out(), _Ctx._Get_args(), _Ctx.locale()}, _Arg));
+    }
+
+    const _CharT* _On_format_specs(size_t _Id, const _CharT* _Begin, const _CharT* _End) {
```
Comment (miscco) [inline stl/inc/format:2361]:
```suggestion
    const _CharT* _On_format_specs(const size_t _Id, const _CharT* _Begin, const _CharT* _End) {
```

File: stl/inc/format [hunk 50]
```diff
@@ -0,0 +1,2734 @@
...
+        _Parse_context.advance_to(_Parse_context.begin() + (_Begin - &*_Parse_context.begin()));
+        auto _Arg = _Ctx.arg(_Id);
+        if (_Arg._Active_state == _Basic_format_arg_type::_Custom_type) {
+            _Arg._Custom_state.format(_Parse_context, _Ctx);
+            return _Parse_context.begin()._Unwrapped();
+        }
+        _Basic_format_specs<_CharT> _Specs;
```
Comment (miscco) [inline stl/inc/format:2368]:
```suggestion

        _Basic_format_specs<_CharT> _Specs;
```

File: stl/inc/format [hunk 51]
```diff
@@ -0,0 +1,2734 @@
...
+        _Specs_checker<_Specs_handler<basic_format_parse_context<_CharT>, _Context>> _Handler(
+            _Specs_handler<basic_format_parse_context<_CharT>, _Context>(_Specs, _Parse_context, _Ctx),
+            _Arg._Active_state);
+        _Begin = _Parse_format_specs(_Begin, _End, _Handler);
+        if (_Begin == _End || *_Begin != '}') {
+            throw format_error("Missing '}' in format string.");
+        }
+        _Ctx.advance_to(_STD visit_format_arg(
```
Comment (miscco) [inline stl/inc/format:2376]:
```suggestion

        _Ctx.advance_to(_STD visit_format_arg(
```

File: stl/inc/format [hunk 52]
```diff
@@ -0,0 +1,2734 @@
...
+        return _ParseCtx.begin() + (_It - _ParseCtx._Unchecked_begin());
+    }
+
+    template <class _FormatContext>
+    typename _FormatContext::iterator format(const _Ty& _Val, _FormatContext& _FormatCtx) {
+        if (_Specs._Dynamic_width_index >= 0) {
+            _Specs._Width =
+                _Get_dynamic_specs<_Width_checker>(_FormatCtx.arg(static_cast<size_t>(_Specs._Dynamic_width_index)));
+        }
+        if (_Specs._Dynamic_precision_index >= 0) {
```
Comment (miscco) [inline stl/inc/format:2410]:
```suggestion

        if (_Specs._Dynamic_precision_index >= 0) {
```

Comment (miscco) [inline stl/inc/format:2410]:
```suggestion

        if (_Specs._Dynamic_precision_index >= 0) {
```

File: stl/inc/format [hunk 53]
```diff
@@ -0,0 +1,2734 @@
...
+            _Specs._Precision = _Get_dynamic_specs<_Precision_checker>(
+                _FormatCtx.arg(static_cast<size_t>(_Specs._Dynamic_precision_index)));
+        }
+        return _STD visit_format_arg(
```
Comment (miscco) [inline stl/inc/format:2414]:
```suggestion

        return _STD visit_format_arg(
```

**Review by miscco — COMMENTED** [review]
I am super sorry. I was a bit overzealous with ... formatting

File: stl/inc/format (hunk 37 above)
Comment (StephanTLavavej) [reply stl/inc/format:1397]: For arbitrary output iterators, I'm not sure.

File: stl/inc/format (hunk 38 above)
Comment (StephanTLavavej) [reply stl/inc/format:1394]: Also not sure for arbitrary output iterators.

File: stl/inc/format (hunk 36 above)
Comment (StephanTLavavej) [reply stl/inc/format:1385]: It contains a `size_t` and non-owning `const unsigned char*` if I understand the code correctly, so it looks like it doesn't benefit from move semantics.

File: stl/inc/format (hunk 20 above)
Comment (StephanTLavavej) [reply stl/inc/format:823]: This trades time (additional bitwise operations) for space, so it isn't a pure win. I would prefer to see profiling data indicating that this is an issue, before adding code complexity here.

File: stl/inc/format (hunk 16 above)
Comment (StephanTLavavej) [reply stl/inc/format:710]: Agreed, good catch. I checked all of the other postincrements in `<format>` and this was the only atypical occurrence.

File: stl/inc/format (hunk 30 above)
Comment (StephanTLavavej) [reply stl/inc/format:911]: We prefer to use `auto` when initializing a variable from a cast, since there's no reason to repeat the type information on a single line. However, I don't believe that this should be carried over to a function's return type, where `auto` forces readers to look at the implementation. (`auto` and `decltype(auto)` are useful when the return type is being computed in a nontrivial manner.)

Adding `const` is good though.

File: stl/inc/format [hunk 54]
```diff
@@ -0,0 +1,2734 @@
...
+// we need to implement this ourselves because from_chars does not work with wide characters and isn't constexpr
+template <class _CharT>
+_NODISCARD constexpr const _CharT* _Parse_nonnegative_integer(
+    const _CharT* _Begin, const _CharT* _End, unsigned int& _Value) {
+    _STL_INTERNAL_CHECK(_Begin != _End && '0' <= *_Begin && *_Begin <= '9');
+    _Value                          = 0;
+    constexpr unsigned int _Max_int = static_cast<unsigned int>((numeric_limits<int>::max)());
+    constexpr unsigned int _Big_int = _Max_int / 10;
+
+    do {
```
[the remark this answers is not in the document]
Comment (StephanTLavavej) [reply stl/inc/format:361]: Sounds good. For additional clarity, I'll use `10u` here - the result of `unsigned int / int` is `unsigned int` but it's perhaps better to not require knowledge of the usual arithmetic conversions here.

File: stl/inc/format (hunk 27 above)
Comment (StephanTLavavej) [reply stl/inc/format:884]: I recall asking this in another CR, and someone showed me that compilers already perform this optimization. Here, even if the character type is signed with a range that could be too negative or too positive, we still get a single comparison: https://godbolt.org/z/PPj16eeqT

Accordingly, I think we should simply remove this performance note and keep the clear code.

File: stl/inc/format (hunk 32 above)
Comment (StephanTLavavej) [reply stl/inc/format:951]: Although the compilers don't seem to be warning here (and the specific value is preserved), mixing signed and unsigned is always scary, so a cast is reasonable.

File: stl/inc/format (hunk 36 above)
Comment (StephanTLavavej) [reply stl/inc/format:1385]: I looked at other occurrences and none of them are moved. I think no change is necessary here.

File: stl/inc/format (hunk 41 above)
Comment (StephanTLavavej) [reply stl/inc/format:1484]: That could improve throughput and debug codegen slightly, but could reduce code clarity slightly. I'm not opposed as long as we centralize the built-in array's length (instead of repeating magic numbers), but I'm not sure we should do this.

File: stl/inc/format (hunk 32 above)
Comment (miscco) [reply stl/inc/format]: I think the cleaner solution would be to make `_Val` an int, as that is what we are returning

File: stl/inc/format (hunk 37 above)
Comment (miscco) [reply stl/inc/format:1446]: Ah I thought we would controll them.

Thanks for the clarification

**Comment by StephanTLavavej** [comment]
* Addressed most of @miscco's feedback.
* Fixed a comment typo.
* Removed a performance note after verifying that compilers already perform that optimization.
* Moved up the definition of `_Get_format_arg_type_storage_size()`, so it doesn't have to be forward-declared.
* Updated `header-units.json`.
* `P0645R10_text_formatting_args` and `P0645R10_text_formatting_parse_contexts` can use the plain `concepts_matrix.lst`, they don't need the `strict_winsdk_concepts_matrix.lst`.
* `_Value < _Integral{0}` was emitting `warning C4296: '<': expression is always false`. Silencing it seemed simpler than refactoring the code to avoid it (e.g. with `if constexpr`).
* Refined the `<xlocnum>` workaround. The internal build was failing due to ConcRT (where, I believe, `_CRTBLD` is defined). After moderately educated guessing and tons of trial and error, I found that `#if !defined(_CRTBLD) || defined(CRTDLL2) || !defined(_DLL) || defined(_M_CEE_PURE)` works. I don't truly understand what's happening here, but this says to provide the `numpunct::id` definition when:
  + It's an ordinary user build (`!defined(_CRTBLD)`), or
  + We're building the STL's main DLL where we need to export the ID (`defined(CRTDLL2)`), or
  + We're building a static LIB (`!defined(_DLL)`) in which case there's no import/export headaches (note that the deprecated `_STATIC_CPPLIB` will not be set when `_CRTBLD` is defined, so we don't need to check it), or
  + We're `/clr:pure` (`defined(_M_CEE_PURE)`) which is not considered static, but avoids saying import.
* Defend against macroized `signbit`, `isnan`, `isinf`. There's an internal-for-now test verifying this, and the rest of the STL follows this pattern: https://github.com/microsoft/STL/blob/4ee3f91e06956ed2d8da4adcb8fcbf6bd75dc3b9/stl/inc/complex#L422
* Use `_THROW` to throw exceptions. (Also fixes an internal test failure.)
* Improve locale testing in `P0645R10_text_formatting_formatting` and `P0645R10_text_formatting_parsing`.
  + Construct a locale from `"de-DE"` because `"de_DE"` fails on older versions of Windows (used by our internal test infrastructure). This was previously seen in `Dev11_0836436_get_time`.
  + Similarly, change `".932"` to `"ja-JP"` although I don't *think* this was causing failures.
  + `assert()` that `setlocale()` succeeds.
  + Slightly revise the `MSVC_INTERNAL_TESTING` comment.
  + `setlocale(LC_ALL, nullptr)` had no effect (it queries the current locale). Changed to `setlocale(LC_ALL, "C")` to reset the locale.
  + Catch `format_error` and `exception`, printing them before `assert(false);`, providing a clue as to why the test failed. (When `locale` construction failed for `"de_DE"`, we just got an exit code of `3`.)
* Work around VSO-1309454 "Standard Library Header Units: CTAD fails when deduction guides are duplicated across header units".

**Comment by StephanTLavavej** [comment]
* Add `const` to a local variable in `<chrono>`.
* Add two missing occurrences of `_WIDEN(_CharT, '.')` in `<xcharconv_ryu.h>`.
* In `P0067R5_charconv/test.cpp`, add `const` and verify that `__d2s_buffered_n()` etc. succeeded.
* Merge #1824.

File: stl/inc/chrono [hunk 55]
```diff
@@ -5171,6 +5176,183 @@ namespace chrono {
...
+        }
+
+        constexpr void _On_precision(int _Prec) {
+            _Specs._Precision = _Prec;
+        }
+
+        constexpr void _On_conversion_spec(_CharT _Modifier, _CharT _Type) {
+            // NOTE: same performance note from _Basic_format_specs also applies here
+            const char _Char_mod  = static_cast<char>(_Modifier);
+            const char _Char_type = static_cast<char>(_Type);
```
Comment (barcharcraz) [inline stl/inc/chrono:5250]: Note (no action required): this probably breaks EBCDIC, we don't really care about EBCDIC though.

File: stl/inc/format (hunk 20 above)
Comment (barcharcraz) [reply stl/inc/format:872]: if you mean combining the bools into the top bits of the `_Fill_length` I'm with STL, I don't think it's worth it. That said we could probably move things around a bit to eliminate padding bytes. Also this structure will probably be difficult to modify in the future because of ABI.

File: stl/inc/format (hunk 38 above)
Comment (barcharcraz) [reply stl/inc/format:1477]: not sure either, and I don't really love the idea of making it conditional noexcept without looking at binary size

File: stl/inc/format (hunk 20 above)
Comment (miscco) [reply stl/inc/format:872]: Yeah, I think it is not worth packing it but maybe optimizing the order would be useful

File: stl/inc/format (hunk 41 above)
Comment (barcharcraz) [reply stl/inc/format:1531]: Well we already use `_Format_min_buffer_length`. The big advantage of the array is that it's impossible to have it decay without realizing it. Although I think it we use std::end()/std::size() it's not a huge deal.

Comment (barcharcraz) [reply stl/inc/format:1531]: even if we don't centralize the length I'm OK changing to a plain array if we use std::end() and std::size() instead of directly using the size. Since those will fail if the array decays.

**Comment by StephanTLavavej** [comment]
* Include more headers.
* In `P0645R10_text_formatting_formatting`, rename `integral` to `Integral` to avoid shadowing the Standard concept.
* **Representation change:** Change `_Align` and `_Sign`'s underlying type to `uint8_t`. `_Align` is stored as a data member, so this matters.
* `static_assert` that `_Basic_format_arg_type::_Custom_type` is *strictly* less than 16, because it must fit in a 4-bit bitfield.
* Style: Add newlines.
* **Bugfix:** Add missing typedefs `format_parse_context` and `wformat_parse_context`.
* **Representation change (sort of):** `basic_format_arg::handle` should store a `__cdecl` function pointer. This will make it immune to the default calling convention.
* **Bugfix (maybe?):** `basic_format_arg::handle::format()` is `const` in the Standard.
* **Bugfix:** `visit_format_arg()` must return `decltype(auto)` as depicted by the Standard.
* Style: `constexpr explicit` is conventional.
* Add `_NODISCARD` to `_Find_encoded()`.
* Style: Use braces to construct temporaries.
* Style: In `_Format_arg_store_packed_index`, avoid shadowing between the constructor parameter and data member, and remove an unnecessary `static_cast` (they're both `size_t`).
* **Representation change:** Add `alignas(_Index_type)` to `_Format_arg_store::_Storage`.
  + Also fix the comment; `_Index_length` is the number of *bytes* needed to store `_Num_args` *elements* of type `_Format_arg_store_packed_index`.
* Improve comments.
  + Fix typo, `_OpenCurl` should be `_OpeningCurl`.
  + Add a WP citation.
  + Overhaul the `_Format_min_buffer_length` comment, fixing its math.
  + "hex number" is slightly unclear; other comments in the STL (especially `<charconv>`) say "hexit" (for "hexadecimal digit").
  + I couldn't understand what "(with overloaded)" intended to say, so I dropped it.
  + Capitalize "ASCII".
* Style: Adjust spacing and indentation of `requires` clauses. A space goes after `requires` when it doesn't look like a function signature.
* Style: When declaring functions, don't mark value parameters as `const`.
* Use `isfinite` for simplicity.
* Style: Use `_Nx` for N instead of `_Nty` (it's not a type, or a number of types).
* Big rename: `_Align` to `_Fmt_align`.
* Big rename: `_Sign` to `_Fmt_sign`.

File: stl/inc/chrono (hunk 55 above)
Comment (StephanTLavavej) [reply stl/inc/chrono:5250]: We don't support any EBCDIC platforms.

**Review by StephanTLavavej — APPROVED** [review]

File: stl/inc/format [hunk 56]
```diff
@@ -0,0 +1,2822 @@
...
+#include <charconv>
+#include <concepts>
+#include <cstdint>
+#include <exception>
+#include <iterator>
+#include <locale>
+#include <stdexcept>
+#include <string>
+#include <string_view>
+#include <variant>
```
Comment (miscco) [inline stl/inc/format:56]: As mentioned in #1826 we should probably pull `monostate` out of `variant`

**Review by StephanTLavavej — APPROVED** [review]

File: stl/inc/format [hunk 57]
```diff
@@ -0,0 +1,2806 @@
...
+    return _STD vformat(_Loc, _Fmt, _STD make_format_args(_Args...));
+}
+
+template <class... _Types>
+_NODISCARD wstring format(const locale& _Loc, const wstring_view _Fmt, const _Types&... _Args) {
+    return _STD vformat(_Loc, _Fmt, _STD make_wformat_args(_Args...));
+}
+
+template <class _OutputIt, class _CharT>
+struct _Format_to_n_iterator {
```
[the remark this answers is not in the document]
Comment (barcharcraz) [reply stl/inc/format:2682]: nope! it does not need to be an old style iterator

File: stl/inc/format [hunk 58]
```diff
@@ -0,0 +1,2806 @@
...
+    const wstring_view _Fmt, const _Types&... _Args) {
+    _Format_to_n_iterator<_OutputIt, wchar_t> _It{._Out = _STD move(_Out), ._Max = _Max};
+
+    using _Context  = basic_format_context<decltype(_It), wchar_t>;
+    auto _Arg_store = _STD make_format_args<_Context>(_Args...);
+    _It             = _STD vformat_to(_STD move(_It), _Loc, _Fmt, _STD move(_Arg_store));
+    return {.out = _STD move(_It._Out), .size = _It._Count};
+}
+
+struct _Counting_iterator {
```
[the remark this answers is not in the document]
Comment (barcharcraz) [reply stl/inc/format:2760]: same response, the standard only needs the output iterators to satisfy the concepts, they don't need to be LegacyIterators

File: tests/std/tests/P0645R10_text_formatting_parsing/test.cpp [hunk 59]
```diff
@@ -0,0 +1,256 @@
...
+
+template <class CharT>
+constexpr bool test_specs_setter() {
+    // just instantiate for now.
+    _Basic_format_specs<CharT> specs = {};
+    _Specs_setter<CharT> setter(specs);
+
+    (void) setter;
+    return true;
+}
```
[the remark this answers is not in the document]
Comment (barcharcraz) [reply tests/std/tests/P0645R10_text_formatting_parsing/test.cpp:210]: we could, but it's a very low ROI set of tests, for catching new bugs. There's no reason to remove the parsing and args tests but they were mostly useful when implementing those parts of format before we could run end-to-end tests.

File: tests/std/tests/P0645R10_text_formatting_args/test.cpp [hunk 60]
```diff
@@ -0,0 +1,224 @@
...
+
+        basic_format_arg<Context> from_literal{get_input_literal<char_type>()};
+        assert(from_literal);
+
+        basic_format_arg<Context> from_string_view{get_input_sv<char_type>()};
+        assert(from_string_view);
+
+        // TRANSITION, implement handle
+        // basic_format_arg<context> from_handle{};
+        // assert(from_handle);
```
[the remark this answers is not in the document]
Comment (barcharcraz) [reply tests/std/tests/P0645R10_text_formatting_args/test.cpp:124]: yes, however there's no actual constructor that constructs from a handle. it's only for types that don't have formatters. trying to pass a handle to the constructor won't work because it'll try and make a `handle<handle<int>>` (or similar) and won't find a formatter.

File: stl/inc/format (hunk 14 above)
Comment (barcharcraz) [reply stl/inc/format]: I changed it back and forth several times, this ended up being the easiest. It's an out parameter, not in-out.

File: tests/std/tests/P0645R10_text_formatting_args/test.cpp (hunk 60 above)
[the remark this answers is not in the document]
Comment (StephanTLavavej) [reply tests/std/tests/P0645R10_text_formatting_args/test.cpp:124]: Should we simply remove this test comment then?

File: tests/std/tests/P0645R10_text_formatting_parsing/test.cpp (hunk 59 above)
[the remark this answers is not in the document]
Comment (StephanTLavavej) [reply tests/std/tests/P0645R10_text_formatting_parsing/test.cpp:210]: I'm fine with leaving this as-is then, thanks.

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I've pushed a merge with `main` to resolve a conflict with #1832 in `<xutility>`: that PR added `_Rewrap_iterator` above `_Convertible_from` which this PR is moving. I resolved it by leaving `_Rewrap_iterator` in place (now immediately above `in_in_result`) so only `_Convertible_from` is moving. This is fine because nothing in `<xutility>` itself needs `_Rewrap_iterator`.

File: tests/std/tests/P0645R10_text_formatting_formatting/test.cpp [hunk 61]
```diff
@@ -8,6 +8,7 @@
 #include <exception>
 #include <format>
 #include <iterator>
+#include <limits.h>
```
Comment (StephanTLavavej) [inline tests/std/tests/P0645R10_text_formatting_formatting/test.cpp:11]: This test already includes `<climits>`.

File: tests/std/tests/P0645R10_text_formatting_formatting/test.cpp [hunk 62]
```diff
@@ -1028,6 +1029,18 @@ void libfmt_formatter_test_args_in_different_position() {
     assert(format(STR("{1} is the {0}"), STR("answer"), 42) == STR("42 is the answer"));
     assert(format(STR("{0}{1}{0}"), STR("abra"), STR("cad")) == STR("abracadabra"));
 }
+
+template <class charT>
+void libfmt_formatter_test_auto_arg_index() {
+    assert(format(STR("{}{}{}"), 'a', 'b', 'c') == STR("abc"));
+    throw_helper(STR("{0}{}"), 'a', 'b');
+    throw_helper(STR("{}{0}"), 'a', 'b');
+    // assert(format(STR("{:.{}}"), 1.2345, 2) == STR("1.2"));
```
Comment (StephanTLavavej) [inline tests/std/tests/P0645R10_text_formatting_formatting/test.cpp:1038]: Why is this commented out?

File: tests/std/tests/P0645R10_text_formatting_formatting/test.cpp [hunk 63]
```diff
@@ -1277,16 +1356,14 @@ void test() {
...
-    try {
-        test();
-    } catch (const format_error& e) {
-        printf("format_error: %s\n", e.what());
-        assert(false);
-    } catch (const exception& e) {
-        printf("exception: %s\n", e.what());
-        assert(false);
-    }
+    test();
```
Comment (StephanTLavavej) [inline tests/std/tests/P0645R10_text_formatting_formatting/test.cpp]: Why is this try/catch machinery being dropped? I added this when investigating test failures (otherwise unhandled exceptions result in an error code of 3 which is not informative).

**Review by StephanTLavavej — CHANGES_REQUESTED** [review]

File: tests/std/tests/P0645R10_text_formatting_formatting/test.cpp (hunk 63 above)
Comment (barcharcraz) [reply tests/std/tests/P0645R10_text_formatting_formatting/test.cpp]: unfortunately I removed them for the same reason! they make investigating the errors with a debugger really hard, since you'll either have to first chance on format_error (there are a lot of expected format_errors thrown in the tests) or you'll break on the abort and the originating callstack is gone.

Comment (StephanTLavavej) [reply tests/std/tests/P0645R10_text_formatting_formatting/test.cpp]: Ok, makes sense.

**Review by StephanTLavavej — APPROVED** [review]

**Review by miscco — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Thanks to everyone who worked on implementing this major feature! :tada: :heart_eyes_cat: :rocket:

**Comment by Sixshaman** [comment]
Thank you everyone! I've been waiting for that

**Comment by CaseyCarter** [comment]
Belated approval: everything looks acceptable to me (which is no great surprise, since I've reviewed most of this already, and worked on some of it).
