### PR TITLE
Use permissive wide-to-narrow transcoding in filesystem_error

### LINKED ISSUE #927: <filesystem>: system_error thrown from copy_file
**Describe the bug**
When a `std::filesystem::path` object `p` contains characters that cannot be represented in the current code page, `p.string()` throws a `system_error` because of the conversion failure. This may cause a `system_error` exception being thrown from a `filesystem_error` constructor.

These `system_error` exceptions are not catched in the `filesystem_error` constructor or the `std::filesystem::copy_file` function. I think the standard intends `copy_file` to still throw a `filesystem_error` in this situation (http://eel.is/c++draft/fs.err.report#2.1). Other functions constructing `filesystem_error` exceptions are likely affected as well.

**Command-line test case**
Set the system locale to English (United States)

```
C:\repro> type fsbug.cpp
#include <filesystem>
#include <iostream>

namespace fs = std::filesystem;

int main() {
  std::wstring const alef = L"\u05D0";

  try {
    fs::copy_file(fs::path{ alef }, fs::path{ L"Foo" });
  }
  catch (fs::filesystem_error const& e) {
    std::cout << e.what() << "\n";
  }
  catch (std::system_error const& e) {
    std::cout << "This line should not be reachable\n";
    std::cout << e.what() << "\n";
  }
  return 0;
}

C:\repro> cl.exe /D _UNICODE /D UNICODE /Zc:wchar_t /std:c++17 /EHsc fsbug.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.24.28315 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

fsbug.cpp
Microsoft (R) Incremental Linker Version 14.24.28315.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:fsbug.exe
fsbug.obj

C:\repro> .\fsbug.exe
This line should not be reachable
No mapping for the Unicode character exists in the target multi-byte code page.
```

**Expected behavior**
`filesystem_error` should be thrown by `copy_file`, not `system_error`. I think constructing a `filesystem_error` with paths not representable in the current locale should not cause the construction of the `filesystem_error` object to fail.

**STL version**
```
Microsoft Visual Studio Professional 2019
Version 16.4.3 
```

(Edit: minor clarifications)

### PR DESCRIPTION
**Pull request by Chronial**
Fixes #927: `std::filesystem_error` constructor used to raise a `std::system_error` when given paths that are not representable in the current codepage. This replaces unrepresentable characters with a replacement character instead of raising `system_error`.

### CODE REVIEW

**Comment by BillyONeal** [comment]
This looks reasonable but needs tests.

**Comment by BillyONeal** [comment]
I don't know why the CI got unhappy there :(

> This looks reasonable but needs tests.

For example:

**Comment by BillyONeal** [comment]
I don't know why the CI is unhappy.

> This looks reasonable but needs tests.

For example:

```
#include <assert.h>
#include <filesystem>
#include <string_view>
#include <system_error>

using namespace std;
namespace fs = std::filesystem;

void test_filesystem_error_with_bad_codepage_characters() {
    fs::path problem_path{L"\U0001F4A3"}; // an emoji that goes boom
    fs::filesystem_error err{"something bad happened", problem_path, error_code{}};
    assert(string_view{err.what()}.find('?') != string_view::npos);
}

int main() { test_filesystem_error_with_bad_codepage_characters(); }
```

**Comment by Chronial** [comment]
Thanks, I'll add a test. Is it ok to assume that the tests won't run with a utf-8 system codepage? Not that I have any idea what else to do about that :).

**Comment by BillyONeal** [comment]
> Thanks, I'll add a test. Is it ok to assume that the tests won't run with a utf-8 system codepage? Not that I have any idea what else to do about that :).

If I understand correctly getting that requires a manifest we aren't going to be adding to our bits. If you're concerned you can replace my 'emoji that goes boom' with an incorrect surrogate pair or something like that.

**Comment by Chronial** [comment]
Added a test. I am not sure whether `WideCharToMultiByte` will always use a `?` as replacement character – according to the docs, that's up to the codepage to specify. I think that's fine, so I rather checked to make sure that the rest of the path is still there.

I also added a check to make sure the test is actually testing something.

**Comment by Chronial** [comment]
Regarding the CI failure: This seems unrelated to the contents of this PR.  Running [`python -m pip install --upgrade pip` fails in the setup step](https://dev.azure.com/vclibs/STL/_build/results?buildId=3752&view=logs&j=cdd012bc-41eb-580d-7644-e3ee22f60668&t=1ae3265d-22be-5c49-79f0-b996cadeee7f).

That error is caused by the fact that the python in question is installed in `C:\Program Files` and the command is trying to upgrade a package in there. Apparently the command is executed in a non-elevated context and thus is lacking permission to write to that folder.

I couldn't see what changed compared to the working runs.

**Comment by StephanTLavavej** [comment]
We're working on fixing the CI. Thanks for looking into the failures - we're not 100% sure whether the CI should be progressing past the admin-permissions-required upgrade, but clearly that problem needs to be fixed.

File: stl/inc/filesystem [hunk 1]
```diff
@@ -1786,8 +1812,11 @@ namespace filesystem {
         static string _Pretty_message(const string_view _Op, const path& _Path1, const path& _Path2 = {}) {
             using namespace _STD string_view_literals; // TRANSITION, VSO-571749
             string _Result;
-            const string _Path1_str = _Path1.string();
-            const string _Path2_str = _Path2.string();
+            // Convert the paths to narrow encoding in a way that gracefully handles non-encodeable characters
```
Comment (StephanTLavavej) [inline stl/inc/filesystem:1815]:
```suggestion
            // Convert the paths to narrow encoding in a way that gracefully handles non-encodable characters
```

File: tests/std/tests/GH_001010_filesystem_error_encoding/test.cpp [hunk 2]
```diff
@@ -0,0 +1,32 @@
...
+#include <string_view>
+#include <system_error>
+
+using namespace std;
+namespace fs = std::filesystem;
+
+void test_filesystem_error_with_bad_codepage_characters() {
+    fs::path problem_path{L"problematic\xD83Dtestpath"}; // path containing lone high surrogate
+
+    // Make sure the path is not encodeable in our current locale, otherwise the test tests nothing
```
Comment (StephanTLavavej) [inline tests/std/tests/GH_001010_filesystem_error_encoding/test.cpp:15]:
```suggestion
    // Make sure the path is not encodable in our current locale, otherwise the test tests nothing
```

File: tests/std/tests/GH_001010_filesystem_error_encoding/test.cpp [hunk 3]
```diff
@@ -0,0 +1,32 @@
...
+    bool exception_caught = false;
+    try {
+        (void) problem_path.string();
+    } catch (std::exception const&) {
+        exception_caught = true;
+    }
+    assert(exception_caught);
+
+    // filesystem_error should handle the non-enceable character gracefully when building its message
```
Comment (StephanTLavavej) [inline tests/std/tests/GH_001010_filesystem_error_encoding/test.cpp:24]:
```suggestion
    // filesystem_error should handle the non-encodable character gracefully when building its message
```

File: stl/src/filesystem.cpp [hunk 4]
```diff
@@ -421,6 +421,27 @@ void __stdcall __std_fs_directory_iterator_close(const __std_fs_dir_handle _Hand
...
+    const __std_code_page _Code_page, const wchar_t* const _Input_str, const int _Input_len, char* const _Output_str,
+    const int _Output_len) noexcept {
+    __std_fs_convert_result _Result;
+
+    _Result._Len = WideCharToMultiByte(static_cast<unsigned int>(_Code_page), WC_NO_BEST_FIT_CHARS, _Input_str,
+        _Input_len, _Output_str, _Output_len, nullptr, nullptr);
+
+    _Result._Err = _Result._Len == 0 ? __std_win_error{GetLastError()} : __std_win_error::_Success;
+
+    // Some Codepages don't support WC_NO_BEST_FIT_CHARS, fall back to default conversion.
```
Comment (StephanTLavavej) [inline stl/src/filesystem.cpp:434]:
```suggestion
    // Some codepages don't support WC_NO_BEST_FIT_CHARS, fall back to default conversion.
```

File: tests/std/tests/GH_001010_filesystem_error_encoding/test.cpp [hunk 5]
```diff
@@ -0,0 +1,32 @@
+// Copyright (c) Microsoft Corporation.
+// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
+
+#include <assert.h>
+#include <filesystem>
```
Comment (StephanTLavavej) [inline tests/std/tests/GH_001010_filesystem_error_encoding/test.cpp:5]: Technically need to include `<exception>` for `std::exception` below:
```suggestion
#include <assert.h>
#include <exception>
#include <filesystem>
```

File: tests/std/tests/GH_001010_filesystem_error_encoding/test.cpp [hunk 6]
```diff
@@ -0,0 +1,32 @@
...
+namespace fs = std::filesystem;
+
+void test_filesystem_error_with_bad_codepage_characters() {
+    fs::path problem_path{L"problematic\xD83Dtestpath"}; // path containing lone high surrogate
+
+    // Make sure the path is not encodeable in our current locale, otherwise the test tests nothing
+    bool exception_caught = false;
+    try {
+        (void) problem_path.string();
+    } catch (std::exception const&) {
```
Comment (StephanTLavavej) [inline tests/std/tests/GH_001010_filesystem_error_encoding/test.cpp:19]: Nitpicks: This test is already `using namespace std;`. Also, while we previously followed a convention of "every test gets to decide whether it's east `const` or west `const`", we're probably going to change the tests to be consistently west `const` like product code (simpler to explain to new contributors), so we may as well follow that for new tests.
```suggestion
    } catch (const exception&) {
```

File: stl/inc/filesystem [hunk 7]
```diff
@@ -1786,8 +1812,11 @@ namespace filesystem {
         static string _Pretty_message(const string_view _Op, const path& _Path1, const path& _Path2 = {}) {
             using namespace _STD string_view_literals; // TRANSITION, VSO-571749
             string _Result;
-            const string _Path1_str = _Path1.string();
-            const string _Path2_str = _Path2.string();
+            // Convert the paths to narrow encoding in a way that gracefully handles non-encodeable characters
+            const string _Path1_str = _Convert_wide_to_narrow_replace_chars<char_traits<char>>(
+                __std_fs_code_page(), _Path1.native(), allocator<char>());
+            const string _Path2_str = _Convert_wide_to_narrow_replace_chars<char_traits<char>>(
+                __std_fs_code_page(), _Path2.native(), allocator<char>());
```
Comment (StephanTLavavej) [inline stl/inc/filesystem:1819]: We've started following a convention of using empty braces to construct temporary objects; this makes code slightly more readable since they don't look like function calls.
Also, while the runtime performance doesn't really matter, there should be a very slight codegen size benefit to extracting the non-inlinable call to `__std_fs_code_page()`. (Note: haven't compiled or tested this, but I've brain-simulated clang-format)
```suggestion
            const auto _Code_page   = __std_fs_code_page();
            const string _Path1_str = _Convert_wide_to_narrow_replace_chars<char_traits<char>>(_Code_page,
                _Path1.native(), allocator<char>{});
            const string _Path2_str = _Convert_wide_to_narrow_replace_chars<char_traits<char>>(_Code_page,
                _Path2.native(), allocator<char>{});
```

**Comment by Chronial** [comment]
Thanks for your quick feedback 👍

**Comment by CaseyCarter** [comment]
Congratulations on your first STL contribution!
