### PR TITLE
Fixes incorrect rounding in rejection method.

### LINKED ISSUE #1001: <random>: binomial_distribution is broken
**Describe the bug**

`binomial_distribution` doesn't produce the correct random number distribution.

**Command-line test case**

```
G:\Temp>type devcom_606865.cpp
#include <cstdio>
#include <random>

using namespace std;

int main() {
    constexpr int num = 1000;
    constexpr double prob = 0.001238;
    constexpr int iters = 100'000;
    constexpr int seed = 12345;

    mt19937 mt_rand(seed);
    binomial_distribution<int> distribution(num, prob);

    double sum = 0;
    for (int i = 0; i < iters; i++) {
        sum += distribution(mt_rand);
    }

    printf("Actual average            = %f\n", sum / iters);
    printf("Mathematical expectiation = %f\n", prob * num);
}

G:\Temp>cl /EHsc /W4 /WX devcom_606865.cpp
用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.27.29009.1 版
版权所有(C) Microsoft Corporation。保留所有权利。

devcom_606865.cpp
Microsoft (R) Incremental Linker Version 14.27.29009.1
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:devcom_606865.exe
devcom_606865.obj

G:\Temp>.\devcom_606865.exe
Actual average            = 0.996960
Mathematical expectiation = 1.238000
```

**Expected behavior**

The average value should be close to the mathematical expectation.

**STL version**
 ```
https://github.com/microsoft/STL/commit/5be7d49c243979231dff35919d3a3d813d75d714
```

**Additional context**

It appears that the code in `<random>` does not exactly follow the referenced Numerical Recipes function.

The `<random>` header code casts the result of the `(_Par0._Sqrt * _Yx + _Par0._Mean)` calculation to an `int`, before performing the comparison:
https://github.com/microsoft/STL/blob/5be7d49c243979231dff35919d3a3d813d75d714/stl/inc/random#L2497-L2502

The Numerical Recipes `bnldev` function calculates the floor after performing the comparison (the variable `em` is declared as a `double`):
```
do {
	angle=PI*ran1(idum);
	y=tan(angle);
	em=sq*y+am;
} while (em < 0.0 || em >= (en+1.0));
em=floor(em);
```

When the original issue reporter modified the `<random>` header as follows:
```
for (;;) { // generate a tentative value
    _Yx = (_Ty1)_CSTD tan(_Pi * _NRAND(_Eng, _Ty1));
    double val = (_Par0._Sqrt * _Yx + _Par0._Mean);
    _Res = (_Ty)(val);
    if (static_cast<_Ty>(0) <= val && val <= _Par0._Tx)
        break;
}
```
(_sic_, unfortunately still incorrect) and recompile, she/he got a more reasonable result.

Also tracked by DevCom-606865 and Microsoft-internal VSO-923008 / [AB#923008](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/923008).

### LINKED ISSUE #1123: <random>: UB in random number distributions: type casting out of range
**Describe the bug**

`geometric_distribution`, `poisson_distribution`, `binomial_distribution`, and `gamma_distribution` could cast potentially huge floating point values to an integer type, resulting in UB.

**Command-line test case**

`#include`s [tests/std/tests/GH_001017_discrete_distribution_out_of_range/bad_random_engine.hpp](https://github.com/microsoft/STL/blob/8e8770cb1635386e84c8ab12f0df47fb0e35951c/tests/std/tests/GH_001017_discrete_distribution_out_of_range/bad_random_engine.hpp)

```
C:\Users\He\source\test>type bad_random.cpp
```

```
#include <cassert>
#include <cstdint>
#include <random>

// tests/std/tests/GH_001017_discrete_distribution_out_of_range/bad_random_engine.hpp
#include "bad_random_engine.hpp"

using namespace std;

template <class Distribution>
void test(Distribution&& distribution) {
    for (bad_random_generator rng; !rng.has_cycled_through();) {
        (void) distribution(rng);
    }
}

int main() {
    test(geometric_distribution<>{});
    test(poisson_distribution<>(100));
    test(binomial_distribution<>(100, 0.5));
    test(gamma_distribution<>(1e+10, 1));
}
```

```
C:\Users\He\source\test>clang++ -O2 -Wall -Wextra -Werror -fsanitize=undefined bad_random.cpp -o bad_random.exe
  正在创建库 bad_random.lib 和对象 bad_random.exp

C:\Users\He\source\test>.\bad_random.exe
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.27.29109\include\random:2148:33: runtime error: inf is outside the range of representable values of type 'int'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.27.29109\include\random:2148:33 in
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.27.29109\include\random:2317:41: runtime error: 2.30959e+17 is outside the range of representable values of type 'int'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.27.29109\include\random:2317:41 in
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.27.29109\include\random:2500:45: runtime error: 1.15479e+17 is outside the range of representable values of type 'int'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.27.29109\include\random:2500:45 in
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.27.29109\include\random:3149:40: runtime error: 1e+10 is outside the range of representable values of type 'int'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.27.29109\include\random:3149:40 in
```

**STL version**
```
Microsoft Visual Studio Community 2019 Preview
版本 16.7.0 Preview 5.0
```

### PR DESCRIPTION
**Pull request by MattStephanson**
Fixes #1001.
The "0 <= _Res" part of the rejection test should be based on floor(x). With truncation, -1 < x <0 is mistakenly accepted, causing 0 to be overrepresented in the output.

Fixes #1123.
Adds function to calculate largest float that will truncate down to a given unsigned value.

### CODE REVIEW

**Comment by statementreply** [comment]
Could you please add tests for the bug fix to the test suite?

File: stl/inc/random [hunk 1]
```diff
@@ -2472,9 +2473,10 @@ private:
             for (;;) { // generate and reject
                 _Ty1 _Yx;
                 for (;;) { // generate a tentative value
-                    _Yx  = static_cast<_Ty1>(_CSTD tan(_Pi * _NRAND(_Eng, _Ty1)));
-                    _Res = static_cast<_Ty>(_Par0._Sqrt * _Yx + _Par0._Mean);
-                    if (_Ty{0} <= _Res && _Res <= _Par0._Tx) {
+                    _Yx = static_cast<_Ty1>(_CSTD tan(_Pi * _NRAND(_Eng, _Ty1)));
+                    const _Ty1 _Mx{_Par0._Sqrt * _Yx + _Par0._Mean};
+                    if (0.0 <= _Mx && _Mx < _Par0._Tx + _Ty{1}) {
```
Comment (statementreply) [inline stl/inc/random:2478]: `_Par0._Tx + _Ty{1}` could be UB (signed `_Ty`) or wrap to zero (unsigned `_Ty`) when `_Par0._Tx` is `numeric_limits<_Ty>::max()`.

Comment (MattStephanson) [reply stl/inc/random]: Thanks, this should be fixed as part of #1123

File: tests/std/tests/GH_001001_random_rejection_rounding/test.cpp [hunk 2]
```diff
@@ -0,0 +1,40 @@
...
+    const double p0_x{static_cast<double>(count[0]) / iters};
+    const double p1_x{static_cast<double>(count[1]) / iters};
+
+    const double p0{std::pow(1.0 - p, static_cast<double>(N))};
+    const double p1{1000.0 * p * std::pow(1.0 - p, static_cast<double>(N - 1))};
+    const double mean{p * N};
+
+    assert(mean_x / mean - 1.0 < 0.002);
+    assert(p0_x / p0 - 1.0 < 0.002);
+    assert(p1_x / p1 - 1.0 < 0.002);
```
Comment (statementreply) [inline tests/std/tests/GH_001001_random_rejection_rounding/test.cpp:35]: - These assertions wouldn't fire on `mean_x`, `p0_x`, and `p1_x` below expected values.
- I think the thresholds are too tight (probability of false test failure is too high). e.g. `P(p0_x / p0 - 1.0 >= 0.002)` is approximately 0.1.

File: stl/inc/random [hunk 3]
```diff
@@ -2025,6 +2027,42 @@ basic_ostream<_Elem, _Traits>& operator<<(basic_ostream<_Elem, _Traits>& _Ostr,
...
 }
 
+// FUNCTION TEMPLATE _Trunc_to_float
+
+// - Returns largest _Flt s.t. static_cast<_Ty>(_Result) <= _Val
+// - First truncate to largest _Flt <= _Val, then add ceil(ulp)-ulp. If
+//   ulp > 1, this is a nop, so skip the expensive nextafter call.
+
+template <class _Flt, class _Ty>
+_NODISCARD inline _Flt _Trunc_to_float(_Ty _Val) {
```
[the remark this answers is not in the document]
Comment (MattStephanson) [reply stl/inc/random]: Agreed.

File: stl/inc/random [hunk 4]
```diff
@@ -2025,6 +2027,42 @@ basic_ostream<_Elem, _Traits>& operator<<(basic_ostream<_Elem, _Traits>& _Ostr,
...
+    constexpr auto _Ty_digits  = numeric_limits<_Ty>::digits;
+    constexpr auto _Flt_digits = numeric_limits<_Flt>::digits;
+    // workaround for lack of constexpr-if to avoid negative shift warning
+    constexpr auto _Abs_diff_digits = (_Ty_digits > _Flt_digits) ? _Ty_digits - _Flt_digits : _Flt_digits - _Ty_digits;
+
+    if _CONSTEXPR_IF (_Ty_digits <= _Flt_digits) {
+        _Flt _Result = _Val < numeric_limits<_Ty>::max()
+                           ? static_cast<_Flt>(_Val + _Ty{1})
+                           : _STD exp2(static_cast<_Flt>(_STD numeric_limits<_Ty>::digits));
```
[the remark this answers is not in the document]
Comment (MattStephanson) [reply stl/inc/random]: Done.

File: stl/inc/random [hunk 5]
```diff
@@ -2123,7 +2161,15 @@ public:
 private:
     template <class _Engine>
     result_type _Eval(_Engine& _Eng, const param_type& _Par0) const {
-        return static_cast<_Ty>(_CSTD log(_NRAND(_Eng, _Ty1)) / _Par0._Log_1_p);
+        using _Uty = make_unsigned_t<_Ty>;
+        constexpr auto _Ty_max{numeric_limits<_Ty>::max()};
```
[the remark this answers is not in the document]
Comment (MattStephanson) [reply stl/inc/random]: Done.

File: tests/std/tests/GH_001001_random_rejection_rounding/test.cpp (hunk 2 above)
Comment (MattStephanson) [reply tests/std/tests/GH_001001_random_rejection_rounding/test.cpp]: - D'oh, fixed.
 - The seed is fixed, so I think this should work, but I've relaxed it to be safe.

**Comment by StephanTLavavej** [comment]
The test `tests/std/tests/Dev09_192736_tr1_prngs_not_copyconstructible` is failing on x86 due to a compiler warning:
```
D:\build\x86\out\inc\random(2047): warning C4244: 'argument': conversion from '_Ty' to 'size_t', possible loss of data
        with
        [
            _Ty=_Uty
        ]
```
(It appears that `_Ty` is `unsigned long long` here, explaining why this is x86-specific.)

**Comment by MattStephanson** [comment]
@StephanTLavavej  I'll take a look after work, but it appears that `_Bit_scan_reverse` will do what I need. Could it be moved to `xbit_ops.h`? https://github.com/microsoft/STL/blob/e7451b3f9da800420a20ae4474ff9c8c0f14ed22/stl/inc/charconv#L463

**Comment by StephanTLavavej** [comment]
Moving `_Bit_scan_reverse` should be fine, as long as `<charconv>` still includes it. Please let us know if you need help investigating the test failures here.

File: stl/inc/random [hunk 6]
```diff
@@ -2025,6 +2027,39 @@ basic_ostream<_Elem, _Traits>& operator<<(basic_ostream<_Elem, _Traits>& _Ostr,
     return _Dist._Write(_Ostr);
 }
 
+// FUNCTION TEMPLATE _Float_upper_bound
+
+// Returns smallest _Flt s.t. static_cast<_Ty>(_Result) > _Val. First
+// truncate to largest _Flt <= _Val, then add ceil(ulp)
+
+template <class _Flt, class _Ty, typename = enable_if_t<is_unsigned_v<_Ty> && is_floating_point_v<_Flt>>>
```
Comment (StephanTLavavej) [inline stl/inc/random:2035]: 1. Because this is an internal function, do we need a SFINAE constraint? SFINAE is important when we're dealing with an overload set, or when we want type traits like `is_constructible` to report useful answers. Here, if we just want to enforce that the internal function is called correctly, `static_assert` within the function body is simpler and will result in better error messages for misuse.
2. (moot point due to (1)) We conventionally use `enable_if_t<SomeCondition, int> = 0` for SFINAE in product code, which works in more situations.
3. (moot point due to (1)) We conventionally say `class` in product code instead of `typename` (although I would like to globally change to `typename` someday, that would be a lot of syntax changes for little value).

File: stl/inc/random [hunk 7]
```diff
@@ -2025,6 +2027,39 @@ basic_ostream<_Elem, _Traits>& operator<<(basic_ostream<_Elem, _Traits>& _Ostr,
     return _Dist._Write(_Ostr);
 }
 
+// FUNCTION TEMPLATE _Float_upper_bound
+
+// Returns smallest _Flt s.t. static_cast<_Ty>(_Result) > _Val. First
+// truncate to largest _Flt <= _Val, then add ceil(ulp)
+
+template <class _Flt, class _Ty, typename = enable_if_t<is_unsigned_v<_Ty> && is_floating_point_v<_Flt>>>
+_NODISCARD inline _Flt _Float_upper_bound(_Ty _Val) {
```
Comment (StephanTLavavej) [inline stl/inc/random:2036]: A year or two ago, we changed our conventions - now we avoid saying `inline` for `template` functions (which are already header-only (if they aren't explicit specializations)). `inline` had very little influence on optimizer inlining decisions and we largely trust it to do the right thing now.
```suggestion
_NODISCARD _Flt _Float_upper_bound(_Ty _Val) {
```

File: tests/std/tests/GH_001123_random_cast_out_of_range/test.cpp [hunk 8]
```diff
@@ -0,0 +1,69 @@
...
+#include <cstdint>
+#include <limits>
+#include <random>
+
+template <class T>
+using lim = std::numeric_limits<T>;
+
+template <class T>
+void CheckUpperBound(T i, float fmax) {
+    const float x{std::_Float_upper_bound<float, T>(i)};
```
Comment (StephanTLavavej) [inline tests/std/tests/GH_001123_random_cast_out_of_range/test.cpp:12]: Template argument deduction should be able to deduce `T` here.

File: stl/inc/random [hunk 9]
```diff
@@ -2123,7 +2158,15 @@ public:
 private:
     template <class _Engine>
     result_type _Eval(_Engine& _Eng, const param_type& _Par0) const {
-        return static_cast<_Ty>(_CSTD log(_NRAND(_Eng, _Ty1)) / _Par0._Log_1_p);
+        using _Uty = make_unsigned_t<_Ty>;
+        constexpr auto _Ty_max{(numeric_limits<_Ty>::max)()};
+        const auto _Ty1_max{_Float_upper_bound<_Ty1, _Uty>(static_cast<_Uty>(_Ty_max))};
```
Comment (StephanTLavavej) [inline stl/inc/random:2163]: Template argument deduction should be able to deduce `_Uty` here. Occurs below. (Our usual convention is "don't help the compiler" - i.e. don't provide explicit template arguments when they can be deduced.)

**Review by cbezault — APPROVED** [review]

File: stl/inc/random [hunk 10]
```diff
@@ -2123,7 +2161,15 @@ public:
...
     result_type _Eval(_Engine& _Eng, const param_type& _Par0) const {
-        return static_cast<_Ty>(_CSTD log(_NRAND(_Eng, _Ty1)) / _Par0._Log_1_p);
+        using _Uty = make_unsigned_t<_Ty>;
+        constexpr auto _Ty_max{numeric_limits<_Ty>::max()};
+        const auto _Ty1_max{_Trunc_to_float<_Ty1, _Uty>(static_cast<_Uty>(_Ty_max))};
+
+        _Ty1 _Val;
+        do {
+            _Val = _CSTD log(_NRAND(_Eng, _Ty1)) / _Par0._Log_1_p;
+        } while (_Val > _Ty1_max);
```
[the remark this answers is not in the document]
Comment (cbezault) [reply stl/inc/random]: My preference is also 1. @STL could you weigh in?

File: stl/inc/random [hunk 11]
```diff
@@ -2025,6 +2027,40 @@ basic_ostream<_Elem, _Traits>& operator<<(basic_ostream<_Elem, _Traits>& _Ostr,
...
+    constexpr auto _Ty_digits  = numeric_limits<_Ty>::digits;
+    constexpr auto _Flt_digits = numeric_limits<_Flt>::digits;
+    using _Ty_32or64           = conditional_t<_Ty_digits <= 32, uint32_t, uint64_t>;
+
+    if _CONSTEXPR_IF (_Ty_digits <= _Flt_digits) {
+        return static_cast<_Flt>(_Val) + _Flt{1};
+    } else {
+#pragma warning(push)
+#pragma warning(disable : 4146 4293) // unary minus of unsigned, negative shift
+        constexpr auto _Mask     = _Ty(-1) << (_Ty_digits - _Flt_digits);
```
Comment (StephanTLavavej) [inline stl/inc/random:2048]: I missed this earlier - `_Ty(-1)` is technically a functional-style cast with C cast semantics. We conventionally avoid this (because they're hard to grep for, and they're willing to do things like reinterpret pointers to/from integers, although the latter is not a danger here). Here, since you need a value-modifying conversion from `-1` to an unsigned `_Ty`, brace syntax won't work, so our style is to use a verbose-but-noticeable `static_cast`:
```suggestion
        constexpr auto _Mask     = static_cast<_Ty>(-1) << (_Ty_digits - _Flt_digits);
```

File: tests/std/tests/GH_001123_random_cast_out_of_range/test.cpp [hunk 12]
```diff
@@ -0,0 +1,86 @@
...
+
+int main() {
+    TestUpperBoundExhaustive<std::uint8_t, float>();
+    TestUpperBoundExhaustive<std::uint16_t, float>();
+    TestUpperBoundSelective<std::uint32_t, float>();
+
+    TestUpperBoundExhaustive<unsigned short int, double>();
+    TestUpperBoundSelective<unsigned int, double>();
+    TestUpperBoundSelective<unsigned long int, double>();
+    TestUpperBoundSelective<unsigned long long int, double>();
```
Comment (StephanTLavavej) [inline tests/std/tests/GH_001123_random_cast_out_of_range/test.cpp:85]: Convention nitpick: we never say `unsigned short int` (or `short int`), etc. - it's always `unsigned short` (or `short`), to the point where I tend to forget that C++ even permits the other form. But we do say `unsigned int` always, never `unsigned` by itself. If I had to explain the principles they would be:
* Avoid unnecessary `int`, decreasing verbosity and making it so that when `int` appears, we can immediately recognize it as the type ranked between `short` and `long`
* Avoid unnecessary `signed` as it is the default (we use it only for `signed char`), decreasing verbosity
* Treat `unsigned` like a modifier that can't appear without one of the 5 types; this requires a bit more verbosity but then we don't need to treat it like "implicitly `int`"
```suggestion
    TestUpperBoundExhaustive<unsigned short, double>();
    TestUpperBoundSelective<unsigned int, double>();
    TestUpperBoundSelective<unsigned long, double>();
    TestUpperBoundSelective<unsigned long long, double>();
```

File: stl/inc/random [hunk 13]
```diff
@@ -2287,12 +2331,17 @@ private:
         }
 
         for (;;) { // generate and reject
+            using _Uty = make_unsigned_t<_Ty>;
+            constexpr auto _Ty_max{(numeric_limits<_Ty>::max)()};
+            const auto _Ty1_max{_Float_upper_bound<_Ty1, _Uty>(static_cast<_Uty>(_Ty_max))};
```
Comment (StephanTLavavej) [inline stl/inc/random:2336]: We should use template argument deduction for the `_Uty` argument:
```suggestion
            const auto _Ty1_max{_Float_upper_bound<_Ty1>(static_cast<_Uty>(_Ty_max))};
```
Earlier, I noted this on one line, but failed to explain that my extremely terse, easily missed "Occurs below." is our shorthand for "There are several occurrences of this issue that should be fixed; please search for them as they are highly systematic - that will be faster than commenting on each of them separately." Sorry about that!

File: stl/inc/random [hunk 14]
```diff
@@ -2469,12 +2518,16 @@ private:
             // events are rare, use Poisson distribution
             _Res = _Par0._Small(_Eng);
         } else { // no shortcuts
+            using _Uty = make_unsigned_t<_Ty>;
+            const auto _Ty1_Tx{_Float_upper_bound<_Ty1, _Uty>(static_cast<_Uty>(_Par0._Tx))};
```
Comment (StephanTLavavej) [inline stl/inc/random:2522]:
```suggestion
            const auto _Ty1_Tx{_Float_upper_bound<_Ty1>(static_cast<_Uty>(_Par0._Tx))};
```

**Review by StephanTLavavej — COMMENTED** [review]
Thanks, this looks great. Upon re-review I found extremely minor stylistic issues; I'll validate that the proposed fixes build and pass your tests, and I'll go ahead and push a commit to save time.

**Review by StephanTLavavej — APPROVED** [review]
FYI @cbezault, I pushed minor changes after you approved.

**Comment by StephanTLavavej** [comment]
I need to push a fix for `/clr:pure`. Manual targeted testing:

```
C:\Temp>type meow.cpp
```
```cpp
#include <cassert>
#include <cstdio>
#include <limits>
#include <random>
using namespace std;

template <typename _Ty_32or64>
int TestMeow(_Ty_32or64 value) {
#ifdef _M_CEE_PURE
    constexpr auto _Ty_32or64_digits = numeric_limits<_Ty_32or64>::digits;
    return _Ty_32or64_digits - _Countl_zero_fallback(value);
#else // _M_CEE_PURE
    return _Bit_scan_reverse(value);
#endif // _M_CEE_PURE
}

int main() {
    assert(TestMeow(0x0000'0000u) == 0);

    assert(TestMeow(0x0000'0001u) == 1);
    assert(TestMeow(0x0000'0002u) == 2);
    assert(TestMeow(0x0000'0004u) == 3);
    assert(TestMeow(0x0000'0008u) == 4);

    assert(TestMeow(0x1000'0000u) == 29);
    assert(TestMeow(0x2000'0000u) == 30);
    assert(TestMeow(0x4000'0000u) == 31);
    assert(TestMeow(0x8000'0000u) == 32);

    assert(TestMeow(0x0000'0000'0000'0000ull) == 0);

    assert(TestMeow(0x0000'0000'0000'0001ull) == 1);
    assert(TestMeow(0x0000'0000'0000'0002ull) == 2);
    assert(TestMeow(0x0000'0000'0000'0004ull) == 3);
    assert(TestMeow(0x0000'0000'0000'0008ull) == 4);

    assert(TestMeow(0x1000'0000'0000'0000ull) == 61);
    assert(TestMeow(0x2000'0000'0000'0000ull) == 62);
    assert(TestMeow(0x4000'0000'0000'0000ull) == 63);
    assert(TestMeow(0x8000'0000'0000'0000ull) == 64);

    assert(TestMeow(0x0000'0003u) == 2);
    assert(TestMeow(0x0000'0005u) == 3);
    assert(TestMeow(0x0000'0009u) == 4);

    assert(TestMeow(0x10F1'234Au) == 29);
    assert(TestMeow(0x20F1'234Au) == 30);
    assert(TestMeow(0x40F1'234Au) == 31);
    assert(TestMeow(0x80F1'234Au) == 32);

    assert(TestMeow(0x0000'0000'0000'0003ull) == 2);
    assert(TestMeow(0x0000'0000'0000'0005ull) == 3);
    assert(TestMeow(0x0000'0000'0000'0009ull) == 4);

    assert(TestMeow(0x1000'000F'1234'A000ull) == 61);
    assert(TestMeow(0x2000'000F'1234'A000ull) == 62);
    assert(TestMeow(0x4000'000F'1234'A000ull) == 63);
    assert(TestMeow(0x8000'000F'1234'A000ull) == 64);

    puts("PASS");
}
```
```
C:\Temp>cl /EHsc /nologo /W4 meow.cpp && meow
meow.cpp
PASS

C:\Temp>cl /clr /nologo /W4 meow.cpp && meow
meow.cpp
PASS

C:\Temp>cl /clr:pure /nologo /W4 meow.cpp && meow
cl : Command line warning D9035 : option 'clr:pure' has been deprecated and will be removed in a future release
meow.cpp
S:\msvc\binaries\x86chk\inc\yvals.h(245): warning STL4001: /clr:pure is deprecated and will be REMOVED.
PASS
```

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Thanks again for fixing this silent bad codegen! We _really_ appreciate it. :smiley_cat:
