### PR TITLE
fix writing NaN to the output stream with a set locale

### LINKED ISSUE #3867: `<iostream>`: Writing NaN to the output stream with a set locale results in a weird output
# Command-line test case
```
C:\Temp>type main.cpp
#include <iostream>
#include <locale>
#include <cmath>

int main()
{
    std::cout << (long double)std::sqrt(-1) << std::endl;
    std::cout << (double)std::sqrt(-1) << std::endl;
    std::cout << (float)std::sqrt(-1) << std::endl;

    std::cout.imbue(std::locale("en_us"));
    std::cout << (long double)std::sqrt(-1) << std::endl;
    std::cout << (double)std::sqrt(-1) << std::endl;
    std::cout << (float)std::sqrt(-1) << std::endl;

    return 0;
}

C:\Temp>cl /EHsc /W4 /WX /std:c++latest .\main.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.37.32820 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

/std:c++latest is provided as a preview of language features from the latest C++
working draft, and we're eager to hear about bugs and suggestions for improvements.
However, note that these features are provided as-is without support, and subject
to changes or removal as the working draft evolves. See
https://go.microsoft.com/fwlink/?linkid=2045807 for details.

main.cpp
Microsoft (R) Incremental Linker Version 14.37.32820.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:main.exe
main.obj

C:\Temp>.\main.exe
-nan(ind)
-nan(ind)
-nan(ind)
-na,n(i,nd)
-na,n(i,nd)
-na,n(i,nd)
```

# Expected behavior
Should be `-nan(ind)` for every output

# STL version
```
Microsoft Visual Studio Community 2022
Version 17.7.0 Preview 3.0
```
# Additional context
Devcom-10410933 / VSO-1848294 / AB#1848294

### PR DESCRIPTION
**Pull request by fsb4000**
Fixes #3867

### CODE REVIEW

File: stl/inc/xlocnum [hunk 1]
```diff
@@ -1461,8 +1461,8 @@ private:
         return _Fmt;
     }
 
-    _OutIt __CLRCALL_OR_CDECL _Fput(_OutIt _Dest, ios_base& _Iosbase, _Elem _Fill, const char* _Buf,
-        size_t _Count) const { // put formatted floating-point to _Dest
+    _OutIt __CLRCALL_OR_CDECL _Fput(_OutIt _Dest, ios_base& _Iosbase, _Elem _Fill, const char* _Buf, size_t _Count,
```
Comment (frederick-vs-ja) [inline stl/inc/xlocnum:1464]: I'm afraid that the current approach may cause ABI incompatibility since this function is DLL-exported.

Perhaps we should add a new function template with the `template <int = 0>` trick to avoid ABI-breaking.

Comment (fsb4000) [reply stl/inc/xlocnum:1464]: Sure, we can rename the method or add `template <int = 0>` if needed but if I understand correctly these 2 methods will be named differently: https://godbolt.org/z/nqz4xP5e6

Comment (StephanTLavavej) [reply stl/inc/xlocnum:1464]: I'll need to look at this in detail, but I suspect that @frederick-vs-ja is correct. Note that we (currently) cannot change the DLL export surface in *any* way, including adding differently-mangled functions. If this appears on the export surface (as is likely due to the `__CLRCALL_OR_CDECL` calling convention), then we likely need to leave it alone, and add a `template <int = 0>` overload that won't be separately compiled.

Comment (StephanTLavavej) [reply stl/inc/xlocnum:1464]: Note that you can use `dumpbin /exports` to manually check (we still need to migrate this part of the build validation from the MS-internal build, sorry).

Comment (StephanTLavavej) [reply stl/inc/xlocnum:1464]: Yep, this affects the name mangling of the exports. I'll validate and push changes.

File: tests/std/tests/GH_003867_output_nan/test.cpp [hunk 2]
```diff
@@ -0,0 +1,24 @@
...
+#include <limits>
+#include <locale>
+#include <sstream>
+
+using namespace std;
+
+template <typename T>
+void test_gh_3867() {
+    // GH-3867 Writing NaN to the output stream with a set locale results in a weird output
+    stringstream s;
```
Comment (StephanTLavavej) [inline tests/std/tests/GH_003867_output_nan/test.cpp]: Suggestion: This can be an `ostringstream` since we're only testing output.

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Thanks! I've verified that the export surface is now unaffected.

**Comment by StephanTLavavej** [comment]
I'm *speculatively* mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Review by CaseyCarter — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I've had to push an additional commit to defend against macroized `isnan`. (We consistently do so, and have a test in the MSVC-internal test harness to verify this.)

FYI @CaseyCarter as you approved right before I pushed.

**Review by CaseyCarter — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Tha,nks for fix,ing thi,s hil,ari,ous bug! :lady_beetle: :hammer_and_wrench: :joy_cat:
