### PR TITLE
<utility>: Remove self swap check from pair.

### LINKED ISSUE #4597: `<utility>`: Side effects in self-swaps of `pair` are skipped
# Describe the bug
Currently, self-swaps of `pair` are no-op:

https://github.com/microsoft/STL/blob/9aca22477df4eed3222b4974746ee79129eb44e7/stl/inc/utility#L441-L460

However, the _Cpp17Swappable_ requirements ([[swappable.requirements]](https://eel.is/c++draft/swappable.requirements)) doesn't seem to exclude self-swaps or side effects in them, and no special case is specified for self-swaps of `pair`.

Perhaps we should just unconditionally swap members.

# Command-line test case
[Godbolt link](https://godbolt.org/z/5hqE8naET).
```C++
#include <utility>

struct swap_counter {
    unsigned int* pcnt_ = nullptr;

    friend constexpr void swap(swap_counter& lhs, swap_counter& rhs) noexcept
    {
        std::swap(lhs.pcnt_, rhs.pcnt_);
        if (lhs.pcnt_ != nullptr)
            ++*lhs.pcnt_;
        if (rhs.pcnt_ != nullptr)
            ++*lhs.pcnt_;
    }
};

static_assert([]
{
    unsigned int cnt{};
    std::pair<swap_counter, int> pr{swap_counter{&cnt}, 0};
    pr.swap(pr);
    return cnt == 2u;
}());
```

# Expected behavior
The code snippet compiles.

### PR DESCRIPTION
**Pull request by Andor233**
Fixes #4597

### CODE REVIEW

**Comment by Andor233** [comment]
@microsoft-github-policy-service agree

File: tests/std/tests/GH_004597_self_swap/test.cpp [hunk 1]
```diff
@@ -0,0 +1,61 @@
+// Copyright (c) Microsoft Corporation.
+// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
+
+#include <utility>
+
+// Test GH-4597 "<utility>: Side effects in self-swaps of pair are skipped"
+struct swap_counter {
+    unsigned int* pcnt_ = nullptr;
+
+    friend constexpr void swap(swap_counter& lhs, swap_counter& rhs) noexcept {
```
Comment (frederick-vs-ja) [inline tests/std/tests/GH_004597_self_swap/test.cpp:10]: Note that the `constexpr` for `std::swap` is since C++20. Perphaps we should introduce this

```C++
#if _HAS_CXX20
#define CONSTEXPR20 constexpr
#else // ^^^ _HAS_CXX20 / !_HAS_CXX20 vvv
#define CONSTEXPR20 inline
#endif // ^^^ !_HAS_CXX20 ^^^
```

and then apply `CONSTEXPR20` to the `swap` functions in this test.

File: tests/std/tests/GH_004597_self_swap/test.cpp [hunk 2]
```diff
@@ -0,0 +1,61 @@
...
+
+
+void test_gh_4595() {
+    {
+        static_assert([] {
+            unsigned int cnt{};
+            std::pair<swap_counter, int> pr{swap_counter{&cnt}, 0};
+            pr.swap(pr);
+            return (cnt == 2u) && (pr.first == 2u) && (pr.second == 0);
+        }());
```
Comment (frederick-vs-ja) [inline tests/std/tests/GH_004597_self_swap/test.cpp:33]: Lambda-expression in constant expression is only valid in C++17. I think we can add some usual functions marked with `CONSTEXPR20`, and then always `assert` their results and `static_assert` their results since C++20.

... like this
```C++
#if _HAS_CXX20
static_assert(fun(args));
#endif // _HAS_CXX20
// ...
assert(fun(args));
```

File: stl/inc/utility [hunk 3]
```diff
@@ -441,21 +441,17 @@ struct pair { // store a pair of values
...
     template <int = 0> // see GH-3013
     constexpr void swap(const pair& _Right) const
         noexcept(is_nothrow_swappable_v<const _Ty1> && is_nothrow_swappable_v<const _Ty2>) {
         using _STD swap;
-        if (this != _STD addressof(_Right)) {
-            swap(first, _Right.first); // intentional ADL
-            swap(second, _Right.second); // intentional ADL
-        }
+        swap(first, _Right.first); // intentional ADL
+        swap(second, _Right.second); // intentional ADL
```
Comment (frederick-vs-ja) [inline stl/inc/utility:454]: I think we can test this overload with `pair<swap_counter&, tuple<>>` or `pair<swap_counter&, SomeOtherType&>`. Such types are const-swappable since C++23.

File: tests/std/tests/GH_004597_self_swap/test.cpp (hunk 1 above)
Comment (Andor233) [reply tests/std/tests/GH_004597_self_swap/test.cpp]: Done

File: tests/std/tests/GH_004597_self_swap/test.cpp (hunk 2 above)
Comment (Andor233) [reply tests/std/tests/GH_004597_self_swap/test.cpp]: Done

File: stl/inc/utility (hunk 3 above)
Comment (Andor233) [reply stl/inc/utility:454]: This is a test for this issue. If we are going to test these things, would it be better to change the name of the test?
Or leave it to their own tests?

Comment (frederick-vs-ja) [reply stl/inc/utility:454]: IMO they are all about this issue.

Comment (Andor233) [reply stl/inc/utility:454]: Done

File: tests/std/tests/GH_004597_self_swap/test.cpp [hunk 4]
```diff
@@ -0,0 +1,80 @@
+// Copyright (c) Microsoft Corporation.
+// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
+
+#include <cassert>
+#include <utility>
+
+// Test GH-4597 "<utility>: Side effects in self-swaps of pair are skipped"
```
Comment (frederick-vs-ja) [inline tests/std/tests/GH_004597_self_swap/test.cpp:7]: This line is redundant because GH_004597 is already in the folder name.
```suggestion
```

File: tests/std/tests/GH_004597_self_swap/test.cpp [hunk 5]
```diff
@@ -0,0 +1,80 @@
...
+        int i2  = 3;
+        auto s1 = swap_counter{&c1};
+        auto s2 = swap_counter{&c2};
+        const std::pair<swap_counter&, int&> p1{s1, i1};
+        const std::pair<swap_counter&, int&> p2{s2, i2};
+        p1.swap(p2);
+        return (c1 == 1u) && (c2 == 3u) && (p1.first == 3u) && (p1.second == 3) && (p2.first == 1u) && (p2.second == 1);
+    }();
+
+#endif
```
Comment (frederick-vs-ja) [inline tests/std/tests/GH_004597_self_swap/test.cpp:70]: Just for consistency.
```suggestion
#endif // _HAS_CXX23
```

File: tests/std/tests/GH_004597_self_swap/test.cpp [hunk 6]
```diff
@@ -0,0 +1,80 @@
...
+    return res1 && res2 && res3 && res4;
+}
+
+int main() {
+#if _HAS_CXX20
+    static_assert(test_gh_4595());
+#else
+    assert(test_gh_4595());
+#endif
```
Comment (frederick-vs-ja) [inline tests/std/tests/GH_004597_self_swap/test.cpp:79]: We should always `assert` the runtime results.
```suggestion
#if _HAS_CXX20
    static_assert(test_gh_4595());
#endif // _HAS_CXX20
    assert(test_gh_4595());
```

**Comment by frederick-vs-ja** [comment]
Finally, we should add `tests\GH_004597_self_swap` here to ensure the MS-internal mechanisms to run this test.
https://github.com/microsoft/STL/blob/8dc4faadafb52e3e0a627e046b41258032d9bc6a/tests/std/test.lst#L245-L246

File: .gitignore [hunk 7]
```diff
@@ -9,3 +9,4 @@ __pycache__/
 /tools/out/
 /CMakeLists.txt.user
 /*.log
+/.idea
```
Comment (frederick-vs-ja) [inline .gitignore:12]: This line is probably unrelated.
But given there's already `.vs/` and `.vscode/`, would it be better to add `/.idea` here? @StephanTLavavej

Comment (Andor233) [reply .gitignore]: I think so

Comment (StephanTLavavej) [reply .gitignore]: What IDE is emitting this - CLion? A web search turned up IntelliJ IDEA which seems unlikely for C++ code.

I don't object to a one-line drive-by addition but I'd like to understand what it's for, and the PR description doesn't say.

Comment (frederick-vs-ja) [reply .gitignore]: As this line was removed later, it didn't seem related to this PR, I opened #4678 to track this.

Comment (StephanTLavavej) [reply .gitignore]: Great, thank you.

File: tests/std/tests/GH_004597_self_swap/test.cpp [hunk 8]
```diff
@@ -0,0 +1,77 @@
...
+        }
+    }
+
+    _CONSTEXPR20 bool operator==(unsigned int x) const {
+        return *pcnt_ == x;
+    }
+};
+
+
+_CONSTEXPR20 bool test_gh_4595() {
```
Comment (StephanTLavavej) [inline tests/std/tests/GH_004597_self_swap/test.cpp:26]: 4595 isn't the right bug number - it should be #4597, as in the test directory name. We should also have a comment reminding us what the bug title was.

File: tests/std/tests/GH_004597_self_swap/test.cpp [hunk 9]
```diff
@@ -0,0 +1,77 @@
...
+
+struct swap_counter {
+    unsigned int* pcnt_ = nullptr;
+
+    friend _CONSTEXPR20 void swap(swap_counter& lhs, swap_counter& rhs) noexcept {
+        std::swap(lhs.pcnt_, rhs.pcnt_);
+        if (lhs.pcnt_ != nullptr) {
+            ++(*lhs.pcnt_);
+        }
+        if (rhs.pcnt_ != nullptr) {
```
Comment (StephanTLavavej) [inline tests/std/tests/GH_004597_self_swap/test.cpp:15]: We conventionally insert a newline between "non-chained" `if`-statements, which helps to make control flow clearer.

File: tests/std/tests/GH_004597_self_swap/test.cpp [hunk 10]
```diff
@@ -0,0 +1,77 @@
...
+#include <cassert>
+#include <utility>
+
+struct swap_counter {
+    unsigned int* pcnt_ = nullptr;
+
+    friend _CONSTEXPR20 void swap(swap_counter& lhs, swap_counter& rhs) noexcept {
+        std::swap(lhs.pcnt_, rhs.pcnt_);
+        if (lhs.pcnt_ != nullptr) {
+            ++(*lhs.pcnt_);
```
Comment (StephanTLavavej) [inline tests/std/tests/GH_004597_self_swap/test.cpp:13]: The parentheses here are unnecessary - there's no other way that the `++` and `*` operators could possibly bind. Occurs below.

We generally avoid unnecessary parentheses, to make the necessary ones stand out more. We do make exceptions for certain visually confusing cases - sometimes conditional operators, and always when bitwise operators are mixed with anything else.

File: tests/std/tests/GH_004597_self_swap/test.cpp [hunk 11]
```diff
@@ -0,0 +1,77 @@
...
+    }
+};
+
+
+_CONSTEXPR20 bool test_gh_4595() {
+    auto res1 = [] {
+        unsigned int cnt{};
+        std::pair<swap_counter, int> pr{swap_counter{&cnt}, 0};
+        pr.swap(pr);
+        return (cnt == 2u) && (pr.first == 2u) && (pr.second == 0);
```
Comment (StephanTLavavej) [inline tests/std/tests/GH_004597_self_swap/test.cpp:31]: The parentheses here are unnecessary - we consider equality to have well-known higher precedence than logical operators. Occurs below.

File: tests/std/tests/GH_004597_self_swap/test.cpp [hunk 12]
```diff
@@ -0,0 +1,77 @@
...
+    auto res4 = true;
+
+#if _HAS_CXX23
+    res4 = [] {
+        unsigned int c1{};
+        unsigned int c2{2};
+        int i1  = 1;
+        int i2  = 3;
+        auto s1 = swap_counter{&c1};
+        auto s2 = swap_counter{&c2};
```
Comment (StephanTLavavej) [inline tests/std/tests/GH_004597_self_swap/test.cpp:62]: We conventionally avoid the pattern `auto variable = Type{initializer};`. Direct-initializing `Type variable{initializer};` is simpler, and reserves `auto` for the cases where it's actually needed to deduce a type.

File: tests/std/tests/GH_004597_self_swap/test.cpp [hunk 13]
```diff
@@ -0,0 +1,77 @@
...
+        const std::pair<swap_counter&, int&> p1{s1, i1};
+        const std::pair<swap_counter&, int&> p2{s2, i2};
+        p1.swap(p2);
+        return (c1 == 1u) && (c2 == 3u) && (p1.first == 3u) && (p1.second == 3) && (p2.first == 1u) && (p2.second == 1);
+    }();
+#endif // _HAS_CXX23
+    return res1 && res2 && res3 && res4;
```
Comment (StephanTLavavej) [inline tests/std/tests/GH_004597_self_swap/test.cpp:69]: While correct, this logic is unnecessarily complicated and makes it harder to find out what went wrong if the test ever fails.

What we usually do is simply `assert()` each condition separately, then `return true;` from the `constexpr` test function. This provides both runtime and compile-time coverage. At runtime, the inner `assert()`s work normally. At compiletime, if any of the inner `assert()`s would fail, they make the whole function ineligible for constant evaluation (because a failed `assert` wants to do very non-`constexpr` things like terminate the program), so the outer `static_assert()` will fail.

Following this pattern is more important to set a consistent precedent for other tests; this test (currently) is small enough that it doesn't *really* matter when considered in isolation.

File: tests/std/tests/GH_004597_self_swap/test.cpp [hunk 14]
```diff
@@ -0,0 +1,77 @@
...
+        if (lhs.pcnt_ != nullptr) {
+            ++(*lhs.pcnt_);
+        }
+        if (rhs.pcnt_ != nullptr) {
+            ++(*rhs.pcnt_);
+        }
+    }
+
+    _CONSTEXPR20 bool operator==(unsigned int x) const {
+        return *pcnt_ == x;
```
Comment (StephanTLavavej) [inline tests/std/tests/GH_004597_self_swap/test.cpp:21]: There's an inconsistency here - `swap()` is written to tolerate null pointers, but `operator==()` assumes they're impossible.

This is test code, and we've ensured that they're always non-null, so we could simply `assert()` that consistently.

File: tests/std/tests/GH_004597_self_swap/test.cpp [hunk 15]
```diff
@@ -0,0 +1,77 @@
...
+    }();
+
+    auto res4 = true;
+
+#if _HAS_CXX23
+    res4 = [] {
+        unsigned int c1{};
+        unsigned int c2{2};
+        int i1  = 1;
+        int i2  = 3;
```
Comment (StephanTLavavej) [inline tests/std/tests/GH_004597_self_swap/test.cpp:60]: This is a test style nitpick, but I consider it to be fairly important as far as nitpicks go: when writing tests, I strongly recommend "unique numbers for unique purposes". Here, you have two distinct kinds of integers - swap counters (the `first` elements) and plain `int` payloads (the `second` elements). There's no reason to reuse the same numbers, and it makes it a bit harder to follow along where the `c2` counter is increased from `2u` to `3u`, when one of the `int`s is also `3`.

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Thanks, this is awesome! :heart_eyes_cat: I pushed a series of fine-grained commits to follow our coding conventions in the test, but nothing serious (beyond a bug number typo).

We merge changes to the GitHub and MSVC-internal repos simultaneously in a semi-manual process. To save time, we merge PRs in batches, and your PR will be part of the next batch. I'll post comments here as I prepare this (likely later this week although possibly next week if I get busy).

File: tests/std/tests/GH_004597_self_swap/test.cpp (hunk 8 above)
Comment (Andor233) [reply tests/std/tests/GH_004597_self_swap/test.cpp]: I remove it beacuse @frederick-vs-ja said:
> This line is redundant because GH_004597 is already in the folder name.

So we still need it.

**Comment by Andor233** [comment]
> Thanks, this is awesome! 😻 I pushed a series of fine-grained commits to follow our coding conventions in the test, but nothing serious (beyond a bug number typo).
> 
> We merge changes to the GitHub and MSVC-internal repos simultaneously in a semi-manual process. To save time, we merge PRs in batches, and your PR will be part of the next batch. I'll post comments here as I prepare this (likely later this week although possibly next week if I get busy).

Thank you.

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
Thanks for fixing this bug, and congratulations on your first microsoft/STL commit! :heart_eyes_cat: :tada: :magic_wand:

This change is expected to ship in VS 2022 17.11 Preview 3.
