### PR TITLE
<regex>: add checks for integer overflow

### LINKED ISSUE #2168: <regex>: integer overflow on large backreference value
The following simple program leads to a signed integer overflow inside [_Do_digits](https://github.com/microsoft/STL/blob/78ff4618d4fa43eeb4bb714d76f27d88cf11a1b6/stl/inc/regex#L3913)

```cpp
#include <regex>

int main() {
  std::regex regex{ "\\3333333334", std::regex_constants::ECMAScript };
}
```

Compiling with clang, using undefined behaviour sanitizer gives the following report: 
```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\regex:3965:14: runtime error: signed integer overflow: 333333333 * 10 cannot be represented in type 'int'
```
I verified this by using msvc and stopping in the debugger at the mentioned place in regex.

**Expected behavior**
I expected a std::regex_error exception to be thrown.

**STL version**
 MSVC 16.11.2. I copied the latest regex from this repo into a local file, the same thing happened so it applies to the latest version as well.

**Additional context**
Both gcc 11 (with libstdc++) and clang 12 (with either libc++ or libstdc++) on linux throw a std::regex_error exception for this particular program (tested on godbolt). Here is a link: https://godbolt.org/z/obKn549da

### PR DESCRIPTION
**Pull request by fsb4000**
Fixes #2168

### CODE REVIEW

File: tests/std/tests/GH_002168_regex_overflow/test.cpp [hunk 1]
```diff
@@ -0,0 +1,21 @@
...
+#include <regex>
+
+using namespace std;
+
+bool shouldThrow(const char* const regexString) {
+    try {
+        regex regex{regexString, regex_constants::ECMAScript};
+        return false;
+    } catch (const regex_error& e) {
+        return e.code() == regex_constants::error_backref;
```
Comment (AlexGuteniev) [inline tests/std/tests/GH_002168_regex_overflow/test.cpp:14]: Maybe it is better to embed `assert` into test function. This way there would be two `assert`s, and this gives more immediate context when debugging.

File: tests/std/tests/GH_002168_regex_overflow/test.cpp [hunk 2]
```diff
@@ -0,0 +1,21 @@
...
+// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
+
+#include <cassert>
+#include <regex>
+
+using namespace std;
+
+bool shouldThrow(const char* const regexString) {
+    try {
+        regex regex{regexString, regex_constants::ECMAScript};
```
Comment (AlexGuteniev) [inline tests/std/tests/GH_002168_regex_overflow/test.cpp:11]: Avoid calling a variable `regex`. There's an intention that "search all" on standard identifiers would show only these standard identifiers used as such; i.e. "regex" would only find `regex` as the class name.

**Review by AlexGuteniev — APPROVED** [review]

File: stl/inc/regex [hunk 3]
```diff
@@ -3910,6 +3910,10 @@ int _Parser<_FwdIt, _Elem, _RxTraits>::_Do_digits(int _Base, int _Count) { // tr
     _Val = 0;
     while (_Count != 0 && (_Chv = _Traits.value(_Char, _Base)) != -1) { // append next digit
         --_Count;
+        if (_Val > ((INT_MAX - _Chv) / _Base)) {
+            _Val = INT_MAX;
```
Comment (miscco) [inline stl/inc/regex:3914]: Why not directly call `_Error(regex_constants::error_backref);`

Comment (AlexGuteniev) [reply stl/inc/regex:3914]: I think this part is used in multiple contexts; see unskipped libc++ tests catching a different exception

Comment (fsb4000) [reply stl/inc/regex:3914]: I did it there: https://github.com/microsoft/STL/pull/2169/commits/30b4de669a19c716acdf2a4239ba39c2afb8629d
But tests fails.

Sometimes we need different exceptions.

https://github.com/microsoft/STL/blob/bc2c6b80dcaf6b10466cfb6f61fa32bcf70680ad/stl/inc/regex#L4326-L4328

File: tests/std/tests/GH_002168_regex_overflow/test.cpp [hunk 4]
```diff
@@ -0,0 +1,19 @@
...
+// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
+
+#include <cassert>
+#include <regex>
+
+using namespace std;
+
+// GH-2168 <regex>: integer overflow on large backreference value
+int main() {
+    for (const char* regexString : {"\\3333333334", "\\2147483648"}) {
```
Comment (strega-nil-ms) [inline tests/std/tests/GH_002168_regex_overflow/test.cpp:11]: Note that this is not testing what you think it's testing; this test succeeds on old code, because `\\2147483648` is not a backreference that exists in the string.

Comment (strega-nil-ms) [inline tests/std/tests/GH_002168_regex_overflow/test.cpp:11]: Note that this is not testing what you think it's testing; this test succeeds on old code, because \\2147483648 is not a backreference that exists in the string.

**Review by strega-nil-ms — COMMENTED** [review]
Going to push test changes, then check product code.

File: stl/inc/regex [hunk 5]
```diff
@@ -3900,20 +3904,21 @@ int _Parser<_FwdIt, _Elem, _RxTraits>::_Do_digits(int _Base, int _Count) { // tr
...
-    return _Do_digits(10, INT_MAX) != INT_MAX;
+bool _Parser<_FwdIt, _Elem, _RxTraits>::_DecimalDigits(
+    regex_constants::error_type _ErrorType) { // check for decimal value
+    return _Do_digits(10, INT_MAX, _ErrorType) != INT_MAX;
 }
 
 template <class _FwdIt, class _Elem, class _RxTraits>
 void _Parser<_FwdIt, _Elem, _RxTraits>::_HexDigits(int _Count) { // check for _Count hex digits
-    if (_Do_digits(16, _Count) != 0) {
+    if (_Do_digits(16, _Count, regex_constants::error_escape) != 0) {
```
Comment (strega-nil-ms) [inline stl/inc/regex:3914]: Noting here that `_HexDigits` will never fail in this way (and neither will `_OctalDigits`) - no changes requested.

File: stl/inc/regex [hunk 6]
```diff
@@ -3983,7 +3988,7 @@ _Prs_ret _Parser<_FwdIt, _Elem, _RxTraits>::_ClassEscape(bool _Addit) { // check
         return _Prs_chr;
     } else if ((_L_flags & _L_esc_wsd) && _CharacterClassEscape(_Addit)) {
         return _Prs_set;
-    } else if (_DecimalDigits()) { // check for invalid value
+    } else if (_DecimalDigits(regex_constants::error_escape)) { // check for invalid value
```
Comment (strega-nil-ms) [inline stl/inc/regex:3991]: I'm not sure when this happens; it would be good to test, though.

File: stl/inc/regex [hunk 7]
```diff
@@ -4302,7 +4307,7 @@ void _Parser<_FwdIt, _Elem, _RxTraits>::_Quantifier() { // check for quantifier
             _Max = 1;
         } else if (_Mchar == _Meta_lbr) { // check for valid bracketed value
             _Next();
-            if (!_DecimalDigits()) {
+            if (!_DecimalDigits(regex_constants::error_badbrace)) {
```
Comment (strega-nil-ms) [inline stl/inc/regex:4310]: We should test for this as well (even if, yes, LLVM already does test this.)

**Review by strega-nil-ms — CHANGES_REQUESTED** [review]
Needs some more testing changes

File: stl/inc/regex (hunk 7 above)
Comment (fsb4000) [reply stl/inc/regex:4322]: Thank you!
yes, LLVM tests only 4310 line (but their implementation passes our tests)
I added another test for 4320 line.

I also found that libstdc++ has some bugs with regex too: https://gcc.godbolt.org/z/evW3jfG3W
I will report them now.

File: tests/std/tests/GH_002168_regex_overflow/test.cpp (hunk 4 above)
Comment (fsb4000) [reply tests/std/tests/GH_002168_regex_overflow/test.cpp]: Your test is great!
I also found that libstdc++ has the same bug: https://gcc.godbolt.org/z/nzET6nvxo
I created https://gcc.gnu.org/bugzilla/show_bug.cgi?id=106607

**Review by strega-nil-ms — APPROVED** [review]
Thanks so much!

File: tests/std/tests/GH_002168_regex_overflow/test.cpp [hunk 8]
```diff
@@ -0,0 +1,40 @@
...
+    }
+
+    try {
+        // 4294967296 = 0 mod 2^32, so this will succeed if we don't check for overflow.
+        regex testRegex{"[\\4294967296-1]", regex_constants::ECMAScript};
+        assert(false);
+    } catch (const regex_error& e) {
+        assert(e.code() == regex_constants::error_escape);
+    }
+}
```
Comment (StephanTLavavej) [inline tests/std/tests/GH_002168_regex_overflow/test.cpp:40]: These test cases are great, covering all altered codepaths that could be activated. As the overflow threshold is `INT_MAX`, I think we should additionally have test cases for 2^31, the first value past that threshold.

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Thanks, this looks correct and complete to me! FYI @strega-nil-ms I pushed minor style changes and additional test cases after you approved.

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
Thanks two billion, one hundred forty-seven million, four hundred eighty-three thousand, six hundred forty-eight times for fixing this long-standing incorrect behavior! :abacus: :lady_beetle: :joy_cat:
